### ISSUE TITLE
No logs in debug console anymore

### ISSUE THREAD

**Issue by marcoms** [Dart-Code/Dart-Code#2062] opened 2019-10-21 19:20 UTC
Since I believe 3.4 and upwards, there are no logs shown in the debug console when running anymore. For example:

```
Launching lib/main.dart on iPhone in debug mode...
Warning: Missing build name (CFBundleShortVersionString).
Warning: Missing build number (CFBundleVersion).
Action Required: You must set a build name and number in the pubspec.yaml file version field before submitting to the App Store.
Automatically signing iOS for device deployment using specified development team in Xcode project: S7W3BYVXF2
Xcode build done.                                           16.0s
Reloaded 25 of 653 libraries in 368ms.
Reloaded 25 of 653 libraries in 342ms.
Reloaded 25 of 653 libraries in 339ms.
Reloaded 25 of 653 libraries in 334ms.
Reloaded 25 of 653 libraries in 320ms.
```

Missing from the above are all the logs from my application, passed to `print()`. Yes, I can see them in the Flutter DevTools, but they are mixed with very verbose messages as well, making it very difficult to read through.

**Comment by DanTup** [comment] 2019-10-21 21:26
This is unfortunately a bug in Flutter:

flutter/flutter#41133

There are some possible workarounds in that thread, but it sounds like a fix is being worked on. I'll close this as a dupe of that. Sorry for the inconvenience!

**Closed by DanTup** 2019-10-21 21:26 UTC
