### ISSUE TITLE
String interpolation + Map = no highlighting

### ISSUE THREAD

**Issue by Skylled** [Dart-Code/Dart-Code#305] opened 2017-05-19 13:16 UTC
I love the way string interpolation is highlighted, it makes my day, but with all the JSON I use (from Firebase), I end up with a lot of maps, which don't play well with the interpolation highlighter.

See gif: 
![String Interpolation with Map](https://thumbs.gfycat.com/LikableHappyEarwig-size_restricted.gif)

This is obviously minor. Point me in the right direction and I might be able to take a swing at it myself.

**Comment by DanTup** [comment] 2017-05-19 14:46
I did have a go at fixing this but was unable to come up with a regex that would work reliably (see https://github.com/Dart-Code/Dart-Code/issues/105#issuecomment-288986721):

> Since JS regex (AFAIK) doesn't have support for counting braces to figure out which closing brace actually matches the expression (consider ${something('with a } in a string'){) I don't think I can properly fix this (though if anyone has ideas, I'm all ears!).

**Comment by DanTup** [comment] 2017-05-19 14:48
The relevant code if anyone wants to have a go is here:

https://github.com/Dart-Code/Dart-Code/blob/252e73238d096201cc0693f5efd2616f8dbd67ab/syntaxes/dart.json#L292

**Comment by Skylled** [comment] 2017-05-19 22:07
Considering Dart doesn't care what kind of [crazy things](https://dartpad.dartlang.org/ec9c5987c3d7ebf6cc56d36fdd7ee159) you do inside of an interpolated string, would it make sense to reduce the regex to just seek out a `${` with a closing `}`? The analyzer will catch any issues inside of the expression, or if it's not closed properly.

**Comment by DanTup** [comment] 2017-05-20 07:01
Yeah, the problem is making sure that the correct `}` is detecting. I did think it'd be possible (it's just Dart inside Dart!) but because you're actually inside quotes, it's not the same as just parsing Dart, since quotes will be escaped. I did spend some time on it but couldn't make it work :(

Maybe in future VS Code will let us use dynamic highlight info and then we can swap from the regexes to the three provided by the Analyzer.

**Comment by Skylled** [comment] 2017-05-21 15:00
Okay, so Dart allows a string inside of the `${ }` to use the same quote symbol as the outer string without issue. It seems to me the only character the regex needs to be watchful for are the brackets. The change would at least patch this issue, but I agree, one day the syntax highlighting needs to be re-written.

**Comment by DanTup** [comment] 2017-05-21 16:19
Thanks; I'll take a look at this when next working on it :)

Have you checked it with crud like this?

````dart
List names = ['John', 'Sophena', 'Henrietta'];
print("${
  ((names) {
      return names[(new math.Random()).nextInt(names.length)];
  })(names)} is the most valueable member of our team");
```

:D

**Comment by Skylled** [comment] 2017-05-21 17:00
The above example still fails to highlight correctly, for the reason you listed, regex's inability to tell which is the closing bracket. But the change doesn't fail any differently than before.

[The above examples after the change.](https://zippy.gfycat.com/GoodPlushBustard.gif)

**Comment by DanTup** [comment] 2017-05-25 19:28
I think we can consider this fixed with #310. I think there's still room for improvement, but I'm not sure we'll ever get all the way with the regex; we really need Code to implement https://github.com/Microsoft/vscode/issues/1967 (go vote for support! :-))

**Closed by DanTup** 2017-05-25 19:28 UTC
Labels: enhancement, up for grabs

**Comment by maxwell8888** [comment] 2021-05-03 12:26
Any update on this? For me, basic nesting like `String test = "${(() => 'one ${"two"}')()}";` only highlights the inner most expression. You mentioned the need for [microsoft/vscode#1967](https://github.com/microsoft/vscode/issues/1967) which seems to have been implemented now.

**Comment by DanTup** [comment] 2021-05-03 15:01
@maxwell8888 could you file a new issue about that? With LSP semantic tokens, I would expect (or at least like) for expressions to be coloured reasonably inside strings. The previous limitations were around the textmate grammar and LSP Semantic Tokens hands this off to the server where we don't need to rely on regex to identify these. Thanks!

**Comment by maxwell8888** [comment] 2021-05-03 19:38
@DanTup As well as handling nested string interpolation, I'd also like to request the expression to be highlighted with multiple colours in the same way as normal code, whereas at the moment the entire expression is just highlighted with a single colour. Should I include this in the ticket or create a separate one? Thanks

**Comment by DanTup** [comment] 2021-05-03 19:58
@maxwell8888 I'm not sure how that differs from the earlier comment, though I think one issue for colouring interpolated expressions better is probably sufficient. Thanks!
