### ISSUE TITLE
odd indent behavior with the create method quick fix

### ISSUE THREAD

**Issue by devoncarew** [Dart-Code/Dart-Code#947] opened 2018-05-28 01:58 UTC
When invoking the create method quick fix, I see odd indentation in the resulting code (I don't see this behavior from IntelliJ).

When quick fixing to create `fooBar`:

<img width="528" alt="screen shot 2018-05-27 at 6 54 25 pm" src="https://user-images.githubusercontent.com/1269969/40593792-ab8d440c-61df-11e8-84bb-69b44a83a394.png">

the resulting code is:

<img width="534" alt="screen shot 2018-05-27 at 6 54 35 pm" src="https://user-images.githubusercontent.com/1269969/40593800-b690133e-61df-11e8-887c-6ebc13c82a7e.png">

which is indented 2 spaces too many. Formatting the code w/ dartfmt corrects it to:

<img width="532" alt="screen shot 2018-05-27 at 6 54 46 pm" src="https://user-images.githubusercontent.com/1269969/40593812-c99c7300-61df-11e8-86a7-e3d9e1cdf7f5.png">

which is the indent that I do see when the operation is run from IntelliJ.

**Comment by DanTup** [comment] 2018-05-28 06:32
This seems like a dupe of #584/#700 which I believe is a bug in Code. I've opened https://github.com/Microsoft/vscode/issues/44200 but it's not had much traffic. Please :+1 it :-)

**Closed by DanTup** 2018-05-28 06:32 UTC
