### ISSUE TITLE
Support Dart 2 for Flutter development

### ISSUE THREAD

**Issue by vogella** [Dart-Code/Dart-Code#515] opened 2018-01-30 11:58 UTC
It would be great if you could support also the new Dart 2 programming language constructors for Flutter development.

See https://flutter.institute/flutter-with-dart-2 for reference.  To use it via the command line, you have to use "flutter run --preview-dart-2".

The following shows syntax errors in the Dart editor.

````
import 'package:flutter/material.dart';
import 'package:google_sign_in/google_sign_in.dart';   
import 'dart:async';

class OctalClockApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return  MaterialApp(
      title: 'Octal Clock',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        fontFamily: 'Fixed',
      ),
      debugShowCheckedModeBanner: false,
    
    );
  }
}

````

**Comment by DanTup** [comment] 2018-01-30 12:06
@devoncarew Is it possible to support this yet (I can pass the flag to `flutter run`, but it won't match the analyzer, etc. - do they have equivs?). I guess the more people that can opt-in, the better the testing we'll get.

**Comment by devoncarew** [comment] 2018-01-30 15:06
Support for optional new and const is just now landing in the analyzer. In order to not see analysis issues in the code, you'll need to run the analysis server with `--preview-dart-2` as well, and I think that's currently a bit premature (though perhaps worth testing).

A global flag to opt-into `--preview-dart-2` - that gets passed into both flutter run and the analysis server - sounds like a reasonable idea.

**Comment by DanTup** [comment] 2018-01-30 15:13
@devoncarew 

> A global flag to opt-into `--preview-dart-2` - that gets passed into both flutter run and the analysis server - sounds like a reasonable idea.

That's my plan - I want to support people that want to try it out but not affect users wanting something stable.

Do you know when the first dev release will be that has this update in (if not already available).

**Comment by devoncarew** [comment] 2018-01-30 15:21
I'd have to check, but my guess is that `--preview-dart-2` would be a no-opt for the analysis server now, so safe to pass in. Definitely worth checking.

**Comment by DanTup** [comment] 2018-01-30 17:11
You're right - latest stable just ignores the flag and doesn't error so that simplifies things :)

**Comment by DanTup** [comment] 2018-01-31 18:21
Just noticed that we have `analyzerAdditionalArgs` you could use to fix the analyzer part of this if you really want it now; but I'm just working on adding proper support via a flag.

**Comment by DanTup** [comment] 2018-01-31 18:28
@devoncarew @bwilkerson When testing out `--preview-dart-2` in the Flutter repo (latest code pulled from Flutter just a few minutes ago) and opening the Stocks app I get a lot of errors (various crashes from the analysis server as well as some strange errors reported - like no call method on `dart.core::Type`.

Do you want me to raise all of these, or is this expected right now?

I'm passing the flag after the analysis server snapshot so assume the flag is getting to the analyzer (and not being used by the VM running the analyzer code) - I presume that's correct?

The analyzer was launched with the arguments:

```text
--client-id=Dart-Code.dart-code
--client-version=2.8.0-dev
--preview-dart-2
```

**Comment by devoncarew** [comment] 2018-01-31 18:39
It's very likely that the meaning of the `--preview-dart-2` to the analysis server is different in the sdk release that flutter has, and the one that they'll soon get. It used to mean 'use the new front end'; it now means 'support the dart 2.0 language features'.

If you're seeing crashes, I would hold off on adding a feature to pass the flag in - we should wait until the next sdk rolls into flutter (and then possibly verify that they're running the right sdk to support the flag).

Can you attach one crash just so we can verify the handling of the flag?

**Comment by DanTup** [comment] 2018-01-31 18:46
Sure, here's a report. I'll dump the code on a branch for now - I would like to see it work before I push anything out!

<details>
<summary>Crash report</summary>
### Versions

- Dart SDK 2.0.0-dev.16.0
- Visual Studio Code 1.19.3
- Dart Code 2.8.0-dev

### Analyzer Info

The analyzer was launched using the arguments:

```text
/Users/danny/Dev/Google/flutter/bin/cache/dart-sdk/bin/snapshots/analysis_server.dart.snapshot
--client-id=Dart-Code.dart-code
--client-version=2.8.0-dev
--preview-dart-2
```

### Exception

Analysis failed: /Users/danny/Dev/Google/flutter/examples/stocks/test_driver/scroll_perf_test.dart context: exception_20180131_184448_798

```text
NoSuchMethodError: The method '&' was called on null.
Receiver: null
Tried calling: &(7)
#0      Object.noSuchMethod (dart:core-patch/dart:core/object_patch.dart:46)
#1      BinaryPrinter.visitVariableGet (package:kernel/binary/ast_to_binary.dart:881)
#2      VariableGet.accept (package:kernel/ast.dart:2070)
#3      BinaryPrinter.writeNode (package:kernel/binary/ast_to_binary.dart:217)
#4      LimitedBinaryPrinter.writeNode (package:kernel/binary/limited_ast_to_binary.dart:55)
#5      BinaryPrinter.writeOptionalNode (package:kernel/binary/ast_to_binary.dart:225)
#6      BinaryPrinter.writeVariableDeclaration (package:kernel/binary/ast_to_binary.dart:1426)
#7      BinaryPrinter.visitLet (package:kernel/binary/ast_to_binary.dart:1188)
#8      Let.accept (package:kernel/ast.dart:3491)
#9      BinaryPrinter.writeNode (package:kernel/binary/ast_to_binary.dart:217)
#10     LimitedBinaryPrinter.writeNode (package:kernel/binary/limited_ast_to_binary.dart:55)
#11     BinaryPrinter.visitMethodInvocation (package:kernel/binary/ast_to_binary.dart:980)
#12     MethodInvocation.accept (package:kernel/ast.dart:2749)
#13     BinaryPrinter.writeNode (package:kernel/binary/ast_to_binary.dart:217)
#14     LimitedBinaryPrinter.writeNode (package:kernel/binary/limited_ast_to_binary.dart:55)
#15     BinaryPrinter.writeOptionalNode (package:kernel/binary/ast_to_binary.dart:225)
#16     BinaryPrinter.visitReturnStatement (package:kernel/binary/ast_to_binary.dart:1370)
#17     ReturnStatement.accept (package:kernel/ast.dart:4149)
#18     BinaryPrinter.writeNode (package:kernel/binary/ast_to_binary.dart:217)
#19     LimitedBinaryPrinter.writeNode (package:kernel/binary/limited_ast_to_binary.dart:55)
#20     BinaryPrinter.writeOptionalNode (package:kernel/binary/ast_to_binary.dart:225)
#21     BinaryPrinter.visitFunctionNode (package:kernel/binary/ast_to_binary.dart:864)
#22     FunctionNode.accept (package:kernel/ast.dart:1923)
#23     BinaryPrinter.writeNode (package:kernel/binary/ast_to_binary.dart:217)
#24     LimitedBinaryPrinter.writeNode (package:kernel/binary/limited_ast_to_binary.dart:55)
#25     BinaryPrinter.writeOptionalNode (package:kernel/binary/ast_to_binary.dart:225)
#26     BinaryPrinter.visitProcedure (package:kernel/binary/ast_to_binary.dart:756)
#27     Procedure.accept (package:kernel/ast.dart:1585)
#28     BinaryPrinter.writeNode (package:kernel/binary/ast_to_binary.dart:217)
#29     LimitedBinaryPrinter.writeNode (package:kernel/binary/limited_ast_to_binary.dart:55)
#30     BinaryPrinter.writeNodeList (package:kernel/binary/ast_to_binary.dart:209)
#31     BinaryPrinter.visitClass (package:kernel/binary/ast_to_binary.dart:704)
#32     Class.accept (package:kernel/ast.dart:862)
#33     BinaryPrinter.writeNode (package:kernel/binary/ast_to_binary.dart:217)
#34     LimitedBinaryPrinter.writeNode (package:kernel/binary/limited_ast_to_binary.dart:55)
#35     BinaryPrinter.writeNodeList (package:kernel/binary/ast_to_binary.dart:209)
#36     BinaryPrinter.visitLibrary (package:kernel/binary/ast_to_binary.dart:568)
#37     Library.accept (package:kernel/ast.dart:409)
#38     BinaryPrinter.writeNode (package:kernel/binary/ast_to_binary.dart:217)
#39     LimitedBinaryPrinter.writeNode (package:kernel/binary/limited_ast_to_binary.dart:55)
#40     List.forEach (dart:core-patch/dart:core/growable_array.dart:274)
#41     BinaryPrinter.writeList (package:kernel/binary/ast_to_binary.dart:201)
#42     LimitedBinaryPrinter.writeLibraries (package:kernel/binary/limited_ast_to_binary.dart:49)
#43     BinaryPrinter.writeProgramFile (package:kernel/binary/ast_to_binary.dart:288)
#44     serializeProgram (package:front_end/src/fasta/kernel/utils.dart:57)
#45     KernelDriver._compileCycle.<anonymous closure>.<anonymous closure> (package:front_end/src/incremental/kernel_driver.dart:482)
#46     PerformanceLog.run (package:front_end/src/base/performance_logger.dart:34)
#47     KernelDriver._compileCycle.<anonymous closure> (package:front_end/src/incremental/kernel_driver.dart:480)
<asynchronous suspension>
#48     PerformanceLog.runAsync (package:front_end/src/base/performance_logger.dart:52)
<asynchronous suspension>
#49     KernelDriver._compileCycle (package:front_end/src/incremental/kernel_driver.dart:384)
<asynchronous suspension>
#50     KernelDriver.getKernelSequence.<anonymous closure>.<anonymous closure> (package:front_end/src/incremental/kernel_driver.dart:330)
<asynchronous suspension>
#51     PerformanceLog.runAsync (package:front_end/src/base/performance_logger.dart:52)
<asynchronous suspension>
#52     KernelDriver.getKernelSequence.<anonymous closure> (package:front_end/src/incremental/kernel_driver.dart:327)
<asynchronous suspension>
#53     PerformanceLog.runAsync (package:front_end/src/base/performance_logger.dart:52)
<asynchronous suspension>
#54     KernelDriver.runWithFrontEndContext.<anonymous closure> (package:front_end/src/incremental/kernel_driver.dart:361)
#55     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:96)
#56     _rootRun (dart:async/zone.dart:1126)
#57     _CustomZone.run (dart:async/zone.dart:1023)
#58     runZoned (dart:async/zone.dart:1501)
#59     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:96)
#60     CompilerContext.runWithOptions (package:front_end/src/fasta/compiler_context.dart:107)
#61     KernelDriver.runWithFrontEndContext (package:front_end/src/incremental/kernel_driver.dart:359)
<asynchronous suspension>
#62     KernelDriver.getKernelSequence (package:front_end/src/incremental/kernel_driver.dart:271)
<asynchronous suspension>
#63     KernelDriver.getKernel (package:front_end/src/incremental/kernel_driver.dart:237)
<asynchronous suspension>
#64     KernelContext.forSingleLibrary.<anonymous closure> (package:analyzer/src/dart/analysis/kernel_context.dart:162)
<asynchronous suspension>
#65     PerformanceLog.runAsync (package:front_end/src/base/performance_logger.dart:52)
<asynchronous suspension>
#66     KernelContext.forSingleLibrary (package:analyzer/src/dart/analysis/kernel_context.dart:160)
<asynchronous suspension>
#67     AnalysisDriver._createKernelContext (package:analyzer/src/dart/analysis/driver.dart:1339)
<asynchronous suspension>
#68     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1192)
<asynchronous suspension>
#69     PerformanceLog.runAsync (package:front_end/src/base/performance_logger.dart:52)
<asynchronous suspension>
#70     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1183)
<asynchronous suspension>
#71     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1010)
<asynchronous suspension>
#72     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:1887)
<asynchronous suspension>
#73     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1830)
#74     new AnalysisServer (package:analysis_server/src/analysis_server.dart:386)
#75     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:79)
#76     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37)
#77     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:436)
#78     _rootRun (dart:async/zone.dart:1126)
#79     _CustomZone.run (dart:async/zone.dart:1023)
#80     runZoned (dart:async/zone.dart:1501)
#81     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:476)
#82     Driver.start (package:analysis_server/src/server/driver.dart:435)
#83     main (file:///b/build/slave/dart-sdk-mac-dev/build/sdk/pkg/analysis_server/bin/server.dart:12)
#84     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:275)
#85     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:163)
```

Diagnostics requested after the error occurred are:

```js
[
    {
        "name": "/Users/danny/Dev/Google/flutter/examples/stocks",
        "explicitFileCount": 15,
        "implicitFileCount": 957,
        "workItemQueueLength": 12,
        "cacheEntryExceptions": []
    }
]
```
</details>

**Comment by DanTup** [comment] 2018-02-02 10:48
@devoncarew @bwilkerson Tried this again today on latest flutter code and there don't seem to be any crashes (so I presume this means the SDK had been updated) but it still complains when I remove const/new. Any ideas?

> and then possibly verify that they're running the right sdk to support the flag

What's a good way to do this? I can't access the analysis server version before I launch it - should we do checks on the SDK version? Or is it reasonable to just makes this the users responsibility?

**Comment by bwilkerson** [comment] 2018-02-02 14:16
> ... but it still complains when I remove const/new. Any ideas?

Yes. The support for optional new and const is still under active development, and hence doesn't work in all cases yet.

**Comment by DanTup** [comment] 2018-02-02 14:29
@bwilkerson Cool; thanks for confirming. I'd had a few messages about it (some from Googlers) so wasn't sure if expected or not. Is it best for me to hold off shipping this flag until you think it's all done, or do you need users using it and reporting issues in order to complete it?

**Comment by bwilkerson** [comment] 2018-02-02 15:24
I think it's probably better to hold off until the one feature behind the flag is working.

**Comment by DanTup** [comment] 2018-02-02 15:32
Will do - if possible, please ping me when you think it's good enough for people to be able to opt-in to!

**Comment by devoncarew** [comment] 2018-02-02 16:52
It'll probably be earliest next week; we'll follow up on this issue.

**Comment by bwilkerson** [comment] 2018-02-07 18:29
This morning I finally got the last major change committed (there's still one minor detail to clean up), so I think it's probably far enough along to make it worth adding support for the flag.

**Comment by DanTup** [comment] 2018-02-08 09:25
@bwilkerson Cool; v2.9 isn't planned to ship till towards end of month.

@devoncarew Is there a consistent schedule for the dart SDK in flutter being updated or does it just happen ad-hoc? (I'd like to test this with flutter before merging).

**Comment by devoncarew** [comment] 2018-02-08 16:17
I expect that 2.0.0-dev.22.0 will have the latest analyzer work.

The dart sdk in flutter will be updated fairly frequently between now and the end of the month. You can try sdks out yourself by editing the bin/internal/dart-sdk.version file, and re-running the bin/internal/update-sdk script.

**Comment by DanTup** [comment] 2018-02-08 16:27
> I expect that 2.0.0-dev.22.0 will have the latest analyzer work.

I presume that's the next one, and not available yet? The download page still only shows .20 for me so not sure if there's supposed to be a 21?

> You can try sdks out yourself by editing the bin/internal/dart-sdk.version file, and re-running the bin/internal/update-sdk script.

Aha, that's good to know!

I am trying to get the analysis server running from source on both my PC and MacBook so I don't have to wait for dev releases and can test on both, hwoever I think there are Windows path casing issues (https://github.com/dart-lang/sdk/issues/32095) on the PC (ironically, I think it turns out that the thing stopping me from running it on Windows might actually be the bug I was trying to investigate!).

I'll pick this one back up on Monday; suspect it'll be a simple test and then merge.

**Comment by DanTup** [comment] 2018-02-12 10:52
> I expect that 2.0.0-dev.22.0 will have the latest analyzer work.

I'm testing with `2.0.0-dev.23.0` and it still doesn't seem to work, but I don't know whether it's my bug and I need to dig into it, or whether it might just not be included there?

Just to clarify, am I right in thinking `--preview-dart-2` could be passed in two positions - 1) before the analyzer snapshot path (which would cause it to be used for execution of the analyzer code) and 2) after the snapshot path which makes it an arg to the analyzer which will cause it to use the new rules for analysis?

I'm currently passing it after, like this:

```dart
args.push(analyzerPath);

// Optionally start the analyzer's diagnostic web server on the given port.
if (config.analyzerDiagnosticsPort)
	args.push(`--port=${config.analyzerDiagnosticsPort}`);

// Add info about the extension that will be collected for crash reports etc.
args.push(`--client-id=Dart-Code.dart-code`);
args.push(`--client-version=${extensionVersion}`);

// The analysis server supports a verbose instrumentation log file.
if (config.analyzerInstrumentationLogFile)
	args.push(`--instrumentation-log-file=${config.analyzerInstrumentationLogFile}`);

if (config.previewDart2)
	args.push(`--preview-dart-2`);
```

**Comment by DanTup** [comment] 2018-02-12 11:11
I figured it was quicker to test this than wait - so I moved the flag before the snapshot path and the analysis server failed to start:

```text
[11:07:55]: ERR Invalid isolate state - Unable to make it runnable
```

So I think I have my flag in the right place but wonder if `dev.23.0` doesn't include all the changes? I'll see if I can finish getting up and running from source - it seems to run currently (and do initial analysis) but fails to respond to requests.

**Comment by DanTup** [comment] 2018-02-12 11:19
Seeing same when running from source:

```text
[11:15:57]: Spawning
  M:\Apps\Dart\Dart-2.0.0-dev.23.0\bin\dart.exe with args
  ["M:\\Coding\\Applications\\Google\\dart-sdk\\sdk\\pkg\\analysis_server\\bin\\server.dart","--client-id=Dart-Code.dart-code","--client-version=2.9.0-dev","--preview-dart-2"]
```

```js
{
	"id": "3",
	"method": "analysis.updateContent",
	"params": {
		"files": {
			"c:\\Users\\danny\\Desktop\\DartHelloWorld\\bin\\main.dart": {
				"content": "main() {\r\n  print(\"Hello, world\");\r\n  var a = new Danny();\r\n  var b = Danny();\r\n}\r\n\r\nclass Danny {}\r\n",
				"type": "add"
			}
		}
	}
}
```

```js
{
	"severity": "WARNING",
	"type": "STATIC_TYPE_WARNING",
	"location": {
		"file": "c:\\Users\\danny\\Desktop\\DartHelloWorld\\bin\\main.dart",
		"offset": 70,
		"length": 5,
		"startLine": 4,
		"startColumn": 11
	},
	"message": "The function 'Danny' isn't defined.",
	"correction": "Try importing the library that defines 'Danny', correcting the name to the name of an existing function, or defining a function named 'Danny'.",
	"code": "undefined_function",
	"hasFix": true
}
```

It's possible I've misunderstood, but this is the source I'm testing with - it's valid, right?

```dart
main() {
  print("Hello, world");
  var a = new Danny();
  var b = Danny();
}

class Danny {}
```

**Comment by bwilkerson** [comment] 2018-02-12 14:52
Yes, that code is correct, and it ought to be inferring a `new` in the initializer for `b`. Could you try adding an explicit constructor to `Danny`? I'm wondering if we have a bug related to implicit constructors.

**Comment by DanTup** [comment] 2018-02-12 15:03
I think I'm more confused now... The named constructor is failing but the other one is now working?

![Named constructor](https://user-images.githubusercontent.com/1078012/36102964-d8c28f26-1005-11e8-8883-2e7906d27ef9.png)

**Comment by DanTup** [comment] 2018-02-12 15:06
No, that was a copy/paste error... I didn't put WithNamed on the end (I'd put it in a separate class because I thought I saw another issue). However, now it all seems fine... Seems like maybe I didn't update properly; but I haven't been back since this morning so I am slightly confused.

![Fixed](https://user-images.githubusercontent.com/1078012/36103069-2d033c84-1006-11e8-8e29-6d9ad51c7770.png)

Let's assume it was user error (seems most likely) and if I happen to see it again I'll do some more digging and let you know.

For now, I can progress testing/merging this 👍

**Comment by bwilkerson** [comment] 2018-02-12 15:06
Notice that
```
var c = Danny.named();
```
ought to be
```
var c = DannyWithNamed.named();
```
Aside from that, what I was trying to ask for was replacing `Danny` with
```
class Danny {
  Danny();
}
```

**Comment by devoncarew** [comment] 2018-02-12 15:07
You only want to pass the flag into the analysis server (the snapshot), and not the VM - you don't currently want to force the analysis server to run on a --preview-dart-2 VM - we'll just take whatever defaults the VM has.

I don't believe that the current dev sdk has a (necessary) fix to plumb the --preview-dart-2 flag through the analysis server. W/o that, optional new/const won't be enabled (it does however work correctly for the cli dartanalyzer).

**Comment by DanTup** [comment] 2018-02-12 15:09
Whoops; I read `named` for some reason! Here's them all (and they all seem to work):

![good](https://user-images.githubusercontent.com/1078012/36103185-88a8ef7a-1006-11e8-81bb-1f1b99fc5672.png)

> You only want to pass the flag into the analysis server (the snapshot), and not the VM

Yeah, that's what I figured but when I hit issues I wondered whether the analyzer might be deciding based on whether it was itself running with the flag.

> I don't believe that the current dev sdk has a (necessary) fix to plumb the `--preview-dart-2` flag through the analysis server.

Based on last few comments above, I think it's actually working now (dev.23) :-)

**Comment by DanTup** [comment] 2018-02-12 15:15
Possibly explanation for earlier weirdness - I have two sdks checked out (once cloned from github, one using gclient); possibly I updated the wrong one (I realised at some point this morning I had two and blew one away and updated the other).

Anyway, looks good in flutter too (I manually changed the SDK to dev.23):

![Flutter](https://user-images.githubusercontent.com/1078012/36103524-75159dea-1007-11e8-805c-9ec621f4aa82.png)

I'll check it gets passed to `flutter run` then gonna merge this in (it's off by default, enabled with a flag) for v2.9 (planned to ship towards end of month).

**Comment by DanTup** [comment] 2018-02-12 15:35
@devoncarew On current code (2d47481f1e48d744bcbd7d4b33ab9cc5ef2de8e1) I get a crash doing `flutter run --preview-dart-2` even from the command line:

<details>
<summary>type '(ByteData) => dynamic' is not a subtype of type '(ByteData) => Future<ByteData>' of 'handler'</summary>
<code><pre>
M:\Coding\Applications\flutter\examples\stocks [master ≡ +1 ~3 -0 !]> flutter run --preview-dart-2
Launching lib/main.dart on XT1562 in debug mode...
Initializing gradle...                                0.8s
Resolving dependencies...                             1.6s
Running 'gradlew assembleDebug'...                    8.4s
Built build\app\outputs\apk\app-debug.apk (24.1MB).
I/FlutterActivityDelegate(27441): onResume setting current activity to this
I/flutter (27441): Observatory server failed to start after 1 tries
E/flutter (27441): [ERROR:topaz/lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
E/flutter (27441): type '(ByteData) => dynamic' is not a subtype of type '(ByteData) => Future<ByteData>' of 'handler'
E/flutter (27441): #0      BinaryMessages.setMessageHandler (package:flutter/src/services/platform_messages.dart:99)
E/flutter (27441): #1      BasicMessageChannel.setMessageHandler (package:flutter/src/services/platform_channel.dart:64)
E/flutter (27441): #2      BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.initInstances (package:flutter/src/scheduler/binding.dart:179)
E/flutter (27441): #3      BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding.initInstances (package:flutter/src/painting/binding.dart:22)
E/flutter (27441): #4      BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding.initInstances (package:flutter/src/rendering/binding.dart:31)
E/flutter (27441): #5      BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding&WidgetsBinding.initInstances (package:flutter/src/widgets/binding.dart:241)
E/flutter (27441): #6      new BindingBase (package:flutter/src/foundation/binding.dart:51)
E/flutter (27441): #7      new BindingBase&GestureBinding (package:flutter/src/gestures/binding.dart:19)
E/flutter (27441): #8      new BindingBase&GestureBinding&ServicesBinding (package:flutter/src/services/binding.dart:19)
E/flutter (27441): #9      new BindingBase&GestureBinding&ServicesBinding&SchedulerBinding (package:flutter/src/scheduler/binding.dart:168)
E/flutter (27441): #10     new BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding (package:flutter/src/painting/binding.dart:15)
E/flutter (27441): #11     new BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding (package:flutter/src/rendering/binding.dart:24)
E/flutter (27441): #12     new BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding&WidgetsBinding (package:flutter/src/widgets/binding.dart:234)
E/flutter (27441): #13     new WidgetsFlutterBinding (package:flutter/src/widgets/binding.dart:882)
E/flutter (27441): #14     WidgetsFlutterBinding.ensureInitialized (package:flutter/src/widgets/binding.dart:897)
E/flutter (27441): #15     runApp (package:flutter/src/widgets/binding.dart:689)
E/flutter (27441): #16     main (file:///m:/Coding/Applications/flutter/examples/stocks/lib/main.dart:146)
E/flutter (27441): #17     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:277)
E/flutter (27441): #18     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:163)
E/flutter (27441): [ERROR:topaz/lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
E/flutter (27441): type 'List' is not a subtype of type 'List<_HashSetEntry<int>>' of '_buckets@3220832' where
E/flutter (27441):   List is from dart:core
E/flutter (27441):   List is from dart:core
E/flutter (27441):   _HashSetEntry is from dart:collection
E/flutter (27441):   int is from dart:core
E/flutter (27441):
E/flutter (27441): #0      _HashSet._buckets= (dart:collection-patch/dart:collection/collection_patch.dart:567)
E/flutter (27441): #1      _HashSet.clear (dart:collection-patch/dart:collection/collection_patch.dart:698)
E/flutter (27441): #2      BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleBeginFrame (package:flutter/src/scheduler/binding.dart:839)
E/flutter (27441): #3      BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleBeginFrame (package:flutter/src/scheduler/binding.dart:765)
E/flutter (27441): #4      _invoke1 (file:///b/build/slave/Linux_Engine/build/src/flutter/lib/ui/hooks.dart:134)
E/flutter (27441): #5      _beginFrame (file:///b/build/slave/Linux_Engine/build/src/flutter/lib/ui/hooks.dart:105)
E/flutter (27441): [ERROR:topaz/lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
E/flutter (27441): type 'List' is not a subtype of type 'List<String>' of '_parts@0150898' where
E/flutter (27441):   List is from dart:core
E/flutter (27441):   List is from dart:core
E/flutter (27441):   String is from dart:core
E/flutter (27441):
E/flutter (27441): #0      StringBuffer._parts= (dart:core-patch/dart:core/string_buffer_patch.dart:17)
E/flutter (27441): #1      StringBuffer._addPart (dart:core-patch/dart:core/string_buffer_patch.dart:163)
E/flutter (27441): #2      StringBuffer.write (dart:core-patch/dart:core/string_buffer_patch.dart:67)
E/flutter (27441): #3      _JsonStringStringifier.writeString (dart:convert/json.dart:883)
E/flutter (27441): #4      _JsonStringifier.writeMap (dart:convert/json.dart:750)
E/flutter (27441): #5      _JsonStringifier.writeJsonValue (dart:convert/json.dart:712)
E/flutter (27441): #6      _JsonStringifier.writeObject (dart:convert/json.dart:664)
E/flutter (27441): #7      _JsonStringStringifier.printOn (dart:convert/json.dart:873)
E/flutter (27441): #8      _JsonStringStringifier.stringify (dart:convert/json.dart:855)
E/flutter (27441): #9      JsonEncoder.convert (dart:convert/json.dart:256)
E/flutter (27441): #10     JsonCodec.encode (dart:convert/json.dart:155)
E/flutter (27441): #11     postEvent (dart:developer/extension.dart:161)
E/flutter (27441): #12     BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._profileFramePostEvent (package:flutter/src/scheduler/binding.dart:888)
E/flutter (27441): #13     BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:875)
E/flutter (27441): #14     profile (package:flutter/src/foundation/profile.dart:17)
E/flutter (27441): #15     BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:873)
E/flutter (27441): #16     BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:773)
E/flutter (27441): #17     _invoke (file:///b/build/slave/Linux_Engine/build/src/flutter/lib/ui/hooks.dart:120)
E/flutter (27441): #18     _drawFrame (file:///b/build/slave/Linux_Engine/build/src/flutter/lib/ui/hooks.dart:109)
I/flutter (27441): Observatory server failed to start after 2 tries
I/flutter (27441): Observatory server failed to start after 3 tries
I/flutter (27441): Observatory server failed to start after 4 tries
I/flutter (27441): Observatory server failed to start after 5 tries
I/flutter (27441): Observatory server failed to start after 6 tries
</pre></code>
</details>

I was under the impression this already worked a little while ago - any ideas?

**Comment by devoncarew** [comment] 2018-02-12 16:00
--preview-dart-2 on the VM is under very active development; I currently see crashes on reload w/ --preview-dart-2 and daemon mode. I'd file issues on flutter/flutter, to make sure these are known (the daemon one is already filed).

**Comment by DanTup** [comment] 2018-02-12 16:28
@devoncarew Ok, will do!

**Comment by DanTup** [comment] 2018-02-12 16:49
https://github.com/flutter/flutter/issues/14642

**Comment by DanTup** [comment] 2018-02-14 08:57
This is merged into v2.9.0. There are still some issues in the SDK (spews errors during launch) which I believe are being worked on but I've confirmed no analyzer warnings (so we're correctly passing the flag to the analyzer) and the app runs (so we're correctly passing to `flutter run`).

**Closed by DanTup** 2018-02-14 08:57 UTC
Labels: in flutter, is enhancement

**Comment by vogella** [comment] 2018-02-15 09:03
Nice. How can this preview feature activate?

**Comment by DanTup** [comment] 2018-02-15 09:12
@vogella v2.9.0 isn't quite ready to ship, but you can try this out in [v2.9.0-beta.1](https://github.com/Dart-Code/Dart-Code/releases/tag/v2.9.0-beta.1). You should download the vsix and install into code with the "Install extension from vsix" command. Then you should enable the `dart.previewDart2` flag. You may wish to set this in your workspace/folder settings rather than user-level so that it only applies to the project(s) you want.

**Note**: This functionality is being actively worked on in the SDK/Flutter tooling and was still a little broken last time I tried it (it was dumping errors during launch even though it did actually launch successfully). I believe this was fixed yesterday (haven't tested it yet) so be aware that you need to be on the very latest Flutter code and it might still be somewhat unstable right now.

**Comment by vogella** [comment] 2018-02-15 16:39
Ok thanks @DanTup . I wait a bit more until things are stabilizing in this case.
