### ISSUE TITLE
Sometimes autoComplete words deleted the next letter

### ISSUE THREAD

**Issue by MohammadAminZamaniAfshar** [Dart-Code/Dart-Code#3892] opened 2022-03-30 07:56 UTC
**Versions (please complete the following information):**
 - VS Code version: 1.65.2 (user setup)
 - Dart extension version:  v3.36.0
 - Dart/Flutter SDK version: 2.5.2

https://user-images.githubusercontent.com/88077166/160160121-2fefc2f5-8e38-4807-ae79-56eb2efa2abe.mp4

### How can i fix it?

Thanks

**Comment by DanTup** [comment] 2022-03-30 08:54
Do you have precise steps to trigger this? The behaviour seems a bit like this VS Code issue:

https://github.com/microsoft/vscode/issues/134013

However it's hard to say if the cause is the same because it's not clear what happened prior to start of the video. If you can reliably reproduce it, does it happen in a new project or only this one?

Things that I might affect it:

- The `editor.autoClosingBrackets` setting
- The `editor.acceptSuggestionOnCommitCharacter` setting
- Whether you pressed `(` to accept the `Text(...)` from completion before this happened

**Comment by MohammadAminZamaniAfshar** [comment] 2022-03-30 12:42
I realized it's happen when i'm coding very fast  and i have a weak computer mabey that's why it's happens rarely
But it happens in all of my projects 
I opened a issue as vscode bug but they sayed it's dart/flutter extensions bugs:
https://github.com/microsoft/vscode/issues/146065

It's not just delete `(` it also deletes `,` or ` ' ` 
Even sometimes it suggest me a named parameter without `:` and when i press `Tap` and then press `ctrl + z` it's work as expected 
### Before:
![Untitled](https://user-images.githubusercontent.com/88077166/160832665-baec2e4c-93c3-47d1-b736-797fa1e4bf62.png)

### Then:
![Untitled](https://user-images.githubusercontent.com/88077166/160833020-364a53f2-bfe9-4aee-9b46-36f9cdcaf299.png)

**Comment by MohammadAminZamaniAfshar** [comment] 2022-03-31 11:59
Thanks 
I hope this problem is fixed it's so annoying

**Comment by DanTup** [comment] 2022-03-31 13:59
I was able to reproduce this in a test and believe I have an understanding of the issue - there is some asynchronous code in compiling the completion list, which leaving a small window for the edit from your "next" keystroke to be processed before the completion list. This means the range in the completion items is more up-to-date than VS Code expects, which throws off the changes it makes to compensate for your typing.

We're discussing some possible ways to fix it, but unfortunately they may not be trivial.

**Comment by MohammadAminZamaniAfshar** [comment] 2022-04-23 16:38
Hello 
Did this problem fixed?
It's still annoying😥😕

**Comment by DanTup** [comment] 2022-04-26 14:45
I believe (hope?) the issue is fixed by https://github.com/dart-lang/sdk/commit/b2464707410db0dc9bf02b4742b2dddc59019ff9. That change is not in a stable release of Dart or Flutter yet though.

**Comment by MohammadAminZamaniAfshar** [comment] 2022-04-27 08:37
> I believe (hope?) the issue is fixed by [dart-lang/sdk@b246470](https://github.com/dart-lang/sdk/commit/b2464707410db0dc9bf02b4742b2dddc59019ff9). That change is not in a stable release of Dart or Flutter yet though.

Thanks

**Comment by DanTup** [comment] 2022-05-02 12:53
Closing this as I believe it's all fixed, but please let me know if you're still seeing this after the next stable SDK releases go out. Thanks!

**Closed by DanTup** 2022-05-02 12:53 UTC
Labels: is bug, in editor, in lsp/analysis server

**Comment by MohammadAminZamaniAfshar** [comment] 2022-07-04 06:26
> Closing this as I believe it's all fixed, but please let me know if you're still seeing this after the next stable SDK releases go out. Thanks!

I still have this problemg :(

**Comment by DanTup** [comment] 2022-07-06 09:15
@MohammadAminZamaniAfshar can you confirm the exact version of your Flutter SDK?

**Comment by DanTup** [comment] 2022-07-06 09:19
Oh, I just checked and the fix above did not make the branch for the last stable release of Dart/Flutter. So if you're on stable, the issue may still exist. I would expect it to be resolved in the next stable (non-hotfix) release though.

**Comment by DanTup** [comment] 2022-07-07 10:02
@MohammadAminZamaniAfshar thanks - see my last comment above. It turns out the fix missed the branch for the last stable release, so it should show up in the next (non-hotfix) stable release.

**Comment by MohammadAminZamaniAfshar** [comment] 2022-07-07 10:02
> Oh, I just checked and the fix above did not make the branch for the last stable release of Dart/Flutter. So if you're on stable, the issue may still exist. I would expect it to be resolved in the next stable (non-hotfix) release though.

I hope.
Thank you

**Comment by DanTup** [comment] 2022-07-07 10:02
If after the next stable release you're still seeing this, please do let me know!
