### ISSUE TITLE
VS Code hot reload taking too much time

### ISSUE THREAD

**Issue by MundaneAdvice** [Dart-Code/Dart-Code#3667] opened 2021-11-13 08:26 UTC
Hello All,
While developing app I found out that VS code as well as Android studio is taking too much time to execute simple file.
Too beanchmark it i just created simple dart file having below code > 
void main() {
  final x = 123;
  print(x);
}
There is nothing else in complete project except for this file as well as note/text file. 
> l
total 48
-rw-r--r--   1 akshay  staff    45B Nov 13 13:21 scratch.dart
drwxr-xr-x   6 akshay  staff   192B Nov  9 12:52 .
-rw-r--r--   1 akshay  staff   571B Nov  9 12:52 dartapp.txt
drwxr-xr-x  19 akshay  staff   608B Nov  6 12:37 ..
-rw-r--r--   1 akshay  staff    15B Oct 31 14:06 main.dart
-rw-r--r--   1 akshay  staff   9.6K Oct 29 18:52 notes.tx

Now if this scratch is file is executed for Web(using Crome) or any emulator/simulator, its really taking too much time to execute and worst part is if i do hot reload it almost takes 4 to 5 mins ( I am on 32gigs machine so memory should not be constraint here), but log shows only millisecs time!

Restarted application in 209,074ms.
123

Fun part is when you try to just do below, it takes not even a second. Am I missing something here? For simple file it is ok to go to terminal and fire dart command but for larger project its pain!

> dart run --verbose scratch.dart
scratch.dart: Warning: Interpreting this as package URI, 'package:scratch/scratch.dart'.
123

is there any way to speed up the things ?

> flutter doctor -v
[✓] Flutter (Channel stable, 2.5.3, on macOS 11.4 20F71 darwin-x64, locale en-GB)
    • Flutter version 2.5.3 at /Users/akshay/Installs/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (4 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/akshay/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.1, Build version 13A1030d
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.62.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.28.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 95.0.4638.69

• No issues found!
 ~/Pr/f/b/s/lib

**Comment by DanTup** [comment] 2021-11-15 11:17
> While developing app I found out that VS code as well as Android studio is taking too much time to execute simple file.

If this issue occurs in Android Studio as well, then it's probably not a bug that can be fixed in the VS Code issue, and probably something inside Flutter and should be filed at https://github.com/flutter/flutter/.

Although - I remember seeing some slow reloads in web a few months back and it was caused by the reload not completing unless the mouse cursor was over the Chrome window. If the mouse was not, then moving it over the Chrome window would cause the reload to immediately complete! I believe that issue is fixed (I think it was in webdev/dwds), but it's possible it's not been released yet. So I would first see whether moving your cursor around in the Chrome window makes any difference. If not, I would file an issue at https://github.com/flutter/flutter/.

Thanks!

**Closed** 2021-11-15 11:18 UTC
Labels: upstream in dart / flutter
