### ISSUE TITLE
Go-to-Defintion does not work for isInsecureConnectionAllowed in dart:io when inside a Flutter project

### ISSUE THREAD

**Issue by escamoteur** [Dart-Code/Dart-Code#3017] opened 2020-12-17 17:18 UTC
![grafik](https://user-images.githubusercontent.com/16635729/102520308-de5dee00-4093-11eb-88e3-e5f584f7263b.png)

Trying to hit F12 on `isInsecureConnectionAllowed` you get the error 'No defintion found ' although you can step ito the function if you use a debugger.

```
[√] Flutter (Channel master, 1.26.0-2.0.pre.45, on Microsoft Windows [Version 10.0.18363.1256], locale de-DE)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.4.3)
[√] Android Studio (version 4.1.0)
[√] IntelliJ IDEA Community Edition (version 2018.2)
[√] VS Code, 64-bit edition (version 1.52.1)
[√] Connected device (3 available)
```

**Comment by DanTup** [comment] 2021-02-17 17:27
@bwilkerson @scheglov this appears to be specific to the `isInsecureConnectionAllowed` function here (or at least some smaller set of symbols than the entire file) as other symbols I tried in this file work fine. I can reduce the repro to not need the HTTP files by just pasting the following into a simple Dart script:

```dart
import 'dart:io';

final a = isInsecureConnectionAllowed('');
```

In a simple Dart project, there's code completion for `isInsecureConnectionAllowed` and the navigation works. In a Flutter app, neither work (nor hovers). Any ideas what could be the cause (or where I could dig further)? I'm not very familiar with the details of how the Dart SDK inside Flutter differs from a standard Dart SDK.

**Comment by bwilkerson** [comment] 2021-02-17 17:54
The docs for Flutter's version of `dart:io` (https://api.flutter.dev/flutter/dart-io/dart-io-library.html) don't include a top-level function named `isInsecureConnectionAllowed`. I don't know whether the library is different between Dart and Flutter or whether the documentation is out of date, but if it's the former then that would explain the difference in behavior.

**Comment by escamoteur** [comment] 2021-02-17 17:56
you can step into it while debugging

**Comment by DanTup** [comment] 2021-02-17 18:14
Ah, interesting! I hadn't considered the packages might have different exposed APIs. Looking again, it seems that `dart:io` normally gets this via `network_policy.dart`, but that doesn't exist in Flutter:

<img width="1011" alt="Screenshot 2021-02-17 at 18 01 05" src="https://user-images.githubusercontent.com/1078012/108247145-307dc700-714a-11eb-8063-c47a7f711ea7.png">

When stepping into it, the source code is actually being downloaded from the VM:

<img width="635" alt="Screenshot 2021-02-17 at 18 07 42" src="https://user-images.githubusercontent.com/1078012/108247851-185a7780-714b-11eb-8232-e740e53fd09f.png">

So I'm not sure the analysis server could really handle this (at least not without being able to consume sources from a running VM - which I expect is not a simple thing). The implementation of that function appears to not exist in the source on disk (although surprisingly, code that calls it does). When debugging, sources are downloaded from the VM for files that aren't available on disk, which is what you see here (you can tell if a file you're debugging is from the VM because hovering its tab will show a non-filesystem path like `/dart:io/network_policy.dart`).

**Comment by bwilkerson** [comment] 2021-02-17 19:17
> ... it seems that `dart:io` normally gets this via `network_policy.dart`, but that doesn't exist in Flutter ...

Using either an IDE or `flutter analyze`, does the analyzer flag the function as not existing?

**Comment by DanTup** [comment] 2021-02-17 19:37
> Using either an IDE or `flutter analyze`, does the analyzer flag the function as not existing?

When I tested it earlier, I don't recall seeing errors - however testing again I definitely do when trying to use it manually:

<img width="973" alt="Screenshot 2021-02-17 at 19 34 17" src="https://user-images.githubusercontent.com/1078012/108257788-3332e900-7157-11eb-8f33-d7dcbf2abb53.png">

Although if I Go-to-Definition on `HttpClient` to get into `http.dart` then Go-to-Definition on `part 'http_impl.dart'` then scroll down to the code, I do _not_ see errors there - however, I suspect this may be because we filter out diagnostics outside of the analysis roots.. Go-to-Def and hovers don't work here, so I suspect this would be invalid code if we were sending diagnostics for it.

<img width="890" alt="Screenshot 2021-02-17 at 19 36 16" src="https://user-images.githubusercontent.com/1078012/108258009-79884800-7157-11eb-9671-53cfc0203d30.png">

**Comment by bwilkerson** [comment] 2021-02-17 19:41
Then the next step is likely to be to open an issue with the Flutter team to ask that the source be included in the SDK shipped with Flutter so that analyzer and IDEs can find it.

**Comment by DanTup** [comment] 2021-02-17 19:52
I've opened https://github.com/flutter/flutter/issues/76228. Thanks!

**Comment by DanTup** [comment] 2021-02-19 17:38
This should be fixed by https://github.com/dart-lang/sdk/commit/91ae755c3534d8eb0e1490d30ccaf05229aae0f2 (which is a change in the SDK, so will show up in a future SDK release). Thanks!

**Closed** 2021-02-19 17:38 UTC
Labels: in editor, in lsp/analysis server, is bug
