### ISSUE TITLE
 Suggestion of VSCode is not showing extracted widgets and variable.

### ISSUE THREAD

**Issue by jayant246** [Dart-Code/Dart-Code#3085] opened 2021-01-21 07:48 UTC
I have customise a TextStyle() and assign it to a variable named 'kLabelTextStyle'. When I try to use that variable name to assign to a TextStyle VSCode suggestion not showing the name, I have to write the whole name by myself. Same issue for the Widgets that I have extracted and put in a separate dart file. I imported the separate dart file into my current file.
I have attach a 2 screenshots where the auto suggestion is not showing the name of 'kLabelTextStyle' and 2nd file where i have saved the 'kLabelTextStyle'
<img width="470" alt="label" src="https://user-images.githubusercontent.com/43151324/105319476-ec4ee380-5bea-11eb-9f53-cbe1fe40262c.PNG">
<img width="684" alt="label2" src="https://user-images.githubusercontent.com/43151324/105319516-f96bd280-5bea-11eb-93c4-72455f4d7a56.PNG">

**Comment by jayant246** [comment] 2021-01-21 17:15
I don't know but somehow on restart it working fine & on pressing Ctrl+ Space it shows all my constants and many in built widgets. I will use it for some days, if suggestions does not show again extracted widgets or variables then I will let you know.

**Comment by jayant246** [comment] 2021-01-25 19:17
> If you remove the text `kLabel` so the caret is right after `style: ` and then press Ctrl+Space (or Cmd+Space if on Mac), does the completion list show at all? If so, what _is_ in it?

It shows all in built widgets and my constants too.

**Comment by DanTup** [comment] 2021-01-26 12:01
I'm a little confused about what the issue is. If it's showing all of the widgets and constants when you press Ctrl+Space, wht _isn't_ working correctly?

Can you also confirm your OS? There is an issue on Windows where running a Flutter app can cause completion not to return all items (see https://github.com/Dart-Code/Dart-Code/issues/2973). It's been fixed in master, but the fix has not made it to the Flutter stable branch yet.

**Comment by jayant246** [comment] 2021-01-27 06:40
@DanTup I am currently using "Windows 10". The 'constants and widget' issue was resolved automatically. But now 'import' is not showing any autocomplete suggestion. 
ex - I have to write( import 'package:flutter/material.dart') this whole line on my own, no autocompletion working for import.

**Comment by DanTup** [comment] 2021-02-01 11:39
@jayant246 to avoid confusion, please file a new issue for that one with a screenshot showing what you see if you press Ctrl+Space (to forcefully invoke code completion) after typing part of the import, for example:

```dart
import 'pack';
```

Press `Ctrl+Space` after the word `pack` but before the `'` and take a screenshot.

I'll close this one since this issue sounds resolved. Thanks!

**Closed by DanTup** 2021-02-01 11:39 UTC
Labels: awaiting info

**Comment by masaori** [comment] 2021-08-16 06:16
I think the same problem came to me.
As @jayant246 said, my auto-completion doesn't suggest most of the symbols in 'package:flutter/material.dart'.

![Kapture 2021-08-16 at 15 06 02](https://user-images.githubusercontent.com/722164/129518783-8a26dc1e-b366-4fce-9ae6-60455051b103.gif)

It seems that
- Most of symbols in 'package:flutter/material.dart' doesn't appear auto-completion (even though I use `Ctrl+Space`).
- But some properties, for example, names of arguments appear in suggestions. 
- The compiler seems to be able to refer definition of these symbols.
    - When I put the cursor over on symbols, the correct definition shows up as in the movie above.

My `flutter doctor`
```
[✓] Flutter (Channel stable, 2.2.3, on Mac OS X 10.15.7 19H1323 darwin-x64, locale ja-JP)
    • Flutter version 2.2.3 at /usr/local/flutter
    • Framework revision f4abaa0735 (6 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/masaori/Library/Android/sdk
    • Platform android-30, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.59.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.25.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 92.0.4515.131
    ! Error: Errors were encountered while preparing your device for development. Please check the Devices and Simulators Window.  (code -1)

• No issues found!
```

VSCode version: 
<img width="419" alt="スクリーンショット 2021-08-16 15 13 09" src="https://user-images.githubusercontent.com/722164/129519023-017a4ca3-f615-4269-a3c8-fb5e7ebea99c.png">

Flutter Plug-in version:
<img width="473" alt="スクリーンショット 2021-08-16 15 13 23" src="https://user-images.githubusercontent.com/722164/129519040-62b5b9d1-dd26-4902-b93a-92ecffd8ecc4.png">


I hope this could be a hint.
Thanks.
