### ISSUE TITLE
Use the VM's getStack() limit argument to fetch only the stack frames required to respond to DAP's getStackTraceRequest

### ISSUE THREAD

**Issue by DanTup** [Dart-Code/Dart-Code#2920] opened 2020-11-02 10:32 UTC
Requires https://dart-review.googlesource.com/c/sdk/+/169980 to be landed, and will need a capabilities check (or to detect whether it was used or not).

**Comment by BootBlock** [comment] 2020-11-06 15:16
Dupe of #2933.

**Closed by BootBlock** 2020-11-06 15:16 UTC
Labels: duplicate
