### ISSUE TITLE
Only able to test with debugging f5 on the first file read

### ISSUE THREAD

**Issue by moseskarunia** [Dart-Code/Dart-Code#2234] opened 2020-01-24 18:18 UTC
So, I have 3 test files. They all works as  intended if I run the test with `flutter test` from the terminal = 'All tests passed!`

But when I'm trying to run the test using f5, only the first test file is passing (with correct test description in debug console)

And then, the second test file will be green checked too, but the debug console message is 

> ✓ loading <path-to-project-folder>/test/features/authentication/data/models/customer_model_test.dart

And the third test will be grey with a question mark. With no debug console message. 

I wonder what is the problem?

P.S Running test with only 1 file is behaving as expected.

System: MacOS Catalina 10.15.2
VS Code extension: Dart 3.7.1 & Flutter 3.7.1

**.vscode/launch.json**

```
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Flutter: Run all Tests",
      "type": "dart",
      "request": "launch",
      "program": "./test/"
    },
    {
      "name": "Flutter",
      "request": "launch",
      "type": "dart"
    }
  ]
}
```

Thank you!

**Screenshot 1**
<img width="373" alt="Screen Shot 2020-01-25 at 01 22 22" src="https://user-images.githubusercontent.com/19493989/73093505-41d9ad00-3f11-11ea-99a4-6080481c32b4.png">
_(Nothing below the last line, even when expanded)_

**Screenshot 2**
<img width="1007" alt="Screen Shot 2020-01-25 at 01 22 42" src="https://user-images.githubusercontent.com/19493989/73093512-44d49d80-3f11-11ea-8145-d71aed76681c.png">
_(Nothing on problems, output, and terminal)_

**Comment by DanTup** [comment] 2020-01-27 15:56
How are you running the tests when they don't work? You said using `F5` - do you have a `launch.json` or are you just letting it run the current file? (if the `launch.json`, can you paste it here?)

You could also try capturing logs with the **Dart: Capture Logs** command (untick Analysis Server, but leave the other things all ticked), then reproduce the issue and then click **Cancel** on the logging dialog to get the log. Thanks!

**Comment by moseskarunia** [comment] 2020-01-28 12:32
> How are you running the tests when they don't work? You said using `F5` - do you have a `launch.json` or are you just letting it run the current file? (if the `launch.json`, can you paste it here?)
> 
> You could also try capturing logs with the **Dart: Capture Logs** command (untick Analysis Server, but leave the other things all ticked), then reproduce the issue and then click **Cancel** on the logging dialog to get the log. Thanks!

Updated OP to include .vscode/launch.json

**Comment by DanTup** [comment] 2020-01-29 10:12
Thanks! In that case, I think this is a dupe of https://github.com/Dart-Code/Dart-Code/issues/2082. The issue is that running all tests with debugging won't work. As a workaround you can use `Debug -> Start Without Debugging`, add `"noDebug": true` to the `launch.json`, or use the **Dart: Run All Tests** command from the palette (of course, you won't get debugging).

You can subscribe to https://github.com/Dart-Code/Dart-Code/issues/2082 for updates on supporting debugging (though right now I don't know what the solution will be). I'll close this as a dupe. Thanks!

**Comment by DanTup** [comment] 2020-01-29 10:13
> About Dart: Capture Logs, It seems I cannot find it on preferences.

Sorry, it's a command in the VS Code Command Palette (though since this is the same as above, you don't need to capture log now).

**Closed by DanTup** 2020-01-29 10:12 UTC
Labels: awaiting info
