### ISSUE TITLE
Completion/Go-to-definition sometimes do not work correctly after changing git branch

### ISSUE THREAD

**Issue by johnbland-wf** [Dart-Code/Dart-Code#316] opened 2017-06-13 17:30 UTC
The analyzer can sometimes get stuck in a state where it does not recognize the current code so code completion and cmd+clicking on code do not work anymore.

This is normally seen when switching between different git branches. I cannot accurately provide a repeatable pattern, but it happens once a day or so.

This action would be similar to the [Atom Dartlang](https://github.com/dart-atom/dartlang) package and would allow us to restart the analyzer when it gets into this odd state without restarting the entire editor.

**Comment by DanTup** [comment] 2017-06-13 17:39
@johnbland-wf I tend to use the `Reload Window` command for this, since it reinitialised the project. Analyzer crashes are detected and a toast appears to let the user reload the window (as well as report the crash). Given this alternative and that crashes are already handled, I don't know if adding another command is all that worthwhile.

That said, I'd really like to track down the original issue. I believe this is likely the same cause as #269.

@bwilkerson Have you had any other reports of this? Unless it's isolated to open files (where Dart Code might be sending content) I think this might be something in `git` confusing the analyzer. I found a similar issue at https://github.com/flutter/flutter-intellij/issues/348 which @devoncarew suspected would be fixed with new driver, but it seems like maybe not.

@johnbland-wf If you can set the option `dart.analyzerInstrumentationLogFile` in your Code settings (note: you won't get completion for it and may get a squiggle, it's a hidden option) then the analyzer will log a load of stuff that might be helpful in tracking this down. Also; can you confirm what platform you're on (as well as versions of Code, Dart Code and the SDK) and whether the errors you see as a result of this are only in files that are open in Code or not?

**Comment by DanTup** [comment] 2017-06-13 17:42
(I've renamed this bug to handle the real issue; I think the `Reload Window` command is as reasonable alternative to the request; since restarting the analyzer would be almost as much work as the reload - feel free to disagree if I'm overlooking something!).

**Comment by johnbland-wf** [comment] 2017-06-13 17:46
As noted, your `Reload Window` suggestion is basically telling folks "restart to fix the bug" and that may be acceptable for this repo. I'd disagree wholeheartedly, though.

**Comment by Skylled** [comment] 2017-06-13 17:46
Would it be unreasonable to hook `Reload Window` into switching branches? Just as a stopgap measure.

**Comment by johnbland-wf** [comment] 2017-06-13 17:55
#269 does look familiar/similar.

**Comment by DanTup** [comment] 2017-06-13 17:55
> `Reload Window` does not show in this scenario

Can you clarify what you mean? AFAIK it's built into Code and should appear in the command palette at all times?

> so unless this is a known resolution by all it is basically a hack around the issue.

> As noted, your Reload Window suggestion is basically telling folks "restart to fix the bug"

Not at all; I want to fix the bug! But your original request was for a "Restart analyzer" command which (if I understood correctly) is exactly the same - a hack/workaround. My suggestion was an equivalent *that you can use today* while we work on the bug. I am not closing this issue, I really want it fixed properly!

> Yes, the result of this is only related to files in VS Code.

Sorry, I probably wasn't specific enough. What I meant was, does the broken functionality (missing completion/go-to-def errors) relate to files that are actually open in editors in Code, or just files in the open project that might not be open. My thinking is that if it only applies to files that have open editors, then this might be caused by Dart Code sending stale data to the analyzer, but if you're seeing it for files that aren't open in editors then I think it's more likely an analyzer bug.

> Would it be unreasonable to hook `Reload Window` into switching branches? Just as a stopgap measure.

Given the (relative) infrequency of the bug and the jarring experience of reloading, I think this would suck. I'm also not sure how reliably we could detect the branch change (the other issue reported doing this from the command line).

I think the best way to track this down is with a log (`dart.analyzerInstrumentationLogFile`) and knowing at what timestamp the branch was changed so if anyone is able to get one, I'd be very grateful! :-)

**Comment by johnbland-wf** [comment] 2017-06-13 18:07
Yes, it is in the command palette. I thought you meant the alert that shows when there is a crash (it showed earlier so that was my reference point).

Restart analyzer is fixing an analyzer issue by restarting the thing that has failed. The editor hasn't failed so it isn't the same thing.

As for the files being open or just in the project, it is for both, if I recall correctly. I've seen it for library files imported into the current file as well as local files and I'm pretty sure files open in the editor as well.

I have the log running. I'll likely hit the bug in a few hours, per normal, so I'll ping back when I see it again.

**Comment by bwilkerson** [comment] 2017-06-19 15:24
> Have you had any other reports of this?

Not that I'm aware of. The new driver that @devoncarew mentioned no longer keeps as much data cached as before, so we're much less likely to get out of sync. The two most likely reasons for analyzer being out of sync are (1) files that it has the content for (such as those that have been modified in an editor but not yet saved) and (2) missed watch events. The watch events are also recorded in the instrumentation log file, so we could look for both of these causes if we have such a file.

Another possibility that occurs to me is that we might be (incorrectly) ignoring changes to files that have been excluded from analysis even when they end up being analyzed because they are referenced from a library that _is_ being analyzed. @johnbland-wf Does this sound like a possibility to you? Are any of the files that git is changing that analysis depends on outside the package that is being analyzed, or are inside but excluded?

**Comment by DanTup** [comment] 2018-02-21 15:18
Has this been seen recently?

**Comment by DanTup** [comment] 2018-05-03 16:57
Closing this as I haven't seen any complaints of it lately. Feel free to shout if you think there's still an issue here.

**Closed by DanTup** 2018-05-03 16:57 UTC
Labels: in editor, is bug
