### ISSUE TITLE
Cursor is at start of line with lines_longer_than_80_chars

### ISSUE THREAD

**Issue by chrisnorman7** [Dart-Code/Dart-Code#3263] opened 2021-04-08 09:14 UTC
Issue Type: <b>Bug</b>

When an issue is found with the linter rule `lines_longer_than_80_chars` enabled, the cursor is placed at the start of the offending line.

As the next most likely action is to move the cursor to character 80 (or nearby at least), it would save keystrokes if the cursor were automatically placed there when the error is found.

To reproduce this, enable the `lines_longer_than_80_chars` linter rule in your `analysis_options.yaml` file, and make yourself a really long comment line:

```dart
/// The handle used by all calls to [getInt], [setInt], [getBool], and [setBool].
```

Press F8 to go to the next problem in files, and your cursor should be placed at the start of your long line, rather at the 80th character.

Extension version: 3.21.1
VS Code version: Code 1.55.0 (c185983a683d14c396952dd432459097bc7f757f, 2021-03-30T16:01:55.261Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 3700U with Radeon Vega Mobile Gfx   (8 x 2296)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|13.95GB (5.69GB free)|
|Process Argv|--crash-reporter-id 18f46c6e-60cd-45d3-a2f1-fe06aa8b9f5a|
|Screen Reader|yes|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspyt653:30270858
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry914:30276682
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
pythontb:30283811
openwslfolder:30282073
vspre833:30267464
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30276952
pythondataviewer:30285071

```

</details>

**Comment by DanTup** [comment] 2021-04-08 09:37
The cursor position isn't directly controllable by the extension - VS Code always places the cursor at the start of the range associated with the error (this is the same range that you see squiggly lines under).

Having the cursor start at the 80th character would either need a change to VS Code (to allow specifying a cursor position with each diagnostic) or changing the Dart language server to set the range to only the part of the line that goes over the 80 characters. Unfortunately I think the first is unlikely, and the second would result in the squiggle no longer showing for the whole line (which for lines that only expand past 80 characters by a few characters, might make them much less noticeable).

**Comment by chrisnorman7** [comment] 2021-04-08 10:27
That's a shame, although I do understand.

As a compromise, is there any chance of a new option to control the
behavior so that option 2 could be enacted? I'm using a screen reader, so
actually the cursor position is of far more use to me than a squiggly line.
:)

Take care,

Chris Norman

**Comment by DanTup** [comment] 2021-04-08 10:36
The diagnostic range comes from the language server, and I'm not sure there's a reasonable way to have it depend on the editors settings.

Out of interest - is it just comments where this is a problem (presumably code is automatically wrapped below 80 chars by the formatter)? Something I'd like to do is have an option to try to [automatically re-wrap comments](https://github.com/dart-lang/dart_style/issues/982). It's a little complicated (because they may contain things like markdown/code/lists etc.), but I think would be quite useful (and if it worked well, perhaps it could also be included as a quick-fix against the lint).

cc @bwilkerson in case he has any thoughts on adjusting the reported range.

**Comment by chrisnorman7** [comment] 2021-04-08 10:41
Hi,
Thank you for the info. I did not realise the language server couldn't
access CV Code preferences, although it makes sense now you've said it.

Would it be worth me submitting an issue against the dart analyzer or
whatever is doing the linting? See what they reckon?

Certainly most sensible lines get wrapped. I just printed a very long
string, and that did not. Of course the cursor was at the start of the
line, as with comments.

Splitting comments would be nice, although I agree it would be somewhat
subjective.

Thank you for your help and clarifications.

Take care,

Chris Norman

**Comment by DanTup** [comment] 2021-04-08 11:19
> Thank you for the info. I did not realise the language server couldn't
> access CV Code preferences, although it makes sense now you've said it.

The language server _can_ access the settings (the LSP server requests them from VS Code), though there's no route for them to influence the diagnostics produced (things that affect analysis options would come from analysis_options.yaml).

> Would it be worth me submitting an issue against the dart analyzer or
> whatever is doing the linting? See what they reckon?

It's probably worth seeing what @bwilkerson thinks first (Brian works on the Dart team on the analyzer). Although I think it would be a little strange to have a setting in the analysis server that changes the range of a diagnostic specifically try to influence this behaviour in VS Code - although I also can't think of another way besides VS Code having the ability to set a specific cursor position against a diagnostic (although that would still require the language server to provide that position against the diagnostic).

**Comment by chrisnorman7** [comment] 2021-04-08 11:56
OK magic, thanks for all the info.

I look forward to hearing what you clever people come up with.

Take care,

Chris Norman

**Comment by bwilkerson** [comment] 2021-04-08 14:46
I can't think of any reason why the highlight region needs to include the whole the line. We generally try to keep the highlight region as small as possible, and highlighting the portion of the line that extends past 80 characters seems reasonable to me. It's true that that might be harder to see if it's a single character over the limit, but I don't think it will be very common nor too hard for most people to deal with. It probably just seemed like a good default to someone. So yes, you're welcome to file an issue (https://github.com/dart-lang/linter/issues/new?assignees=&labels=&template=issue-report.md&title=) to request a change. (Of course, you'd be welcome to file an issue even if I didn't think it was a good idea. :-)) I doubt that anyone had considered the impact of the choice on those using a screen reader, so it would be worth mentioning this consideration.

I agree with @DanTup that it would probably be a bad idea for options from the client to influence the lint, especially if different users can have different settings. But in this case I also don't think it's necessary.

**Comment by chrisnorman7** [comment] 2021-04-08 15:50
Thanks @bwilkerson, I have done that.

For anyone following along, I created the suggested issue [here](https://github.com/dart-lang/linter/issues/2570).

**Comment by DanTup** [comment] 2021-04-11 18:51
Great! Updating the lint and not needing an option definitely sounds better. I filed a PR with what I think the change is here:

https://github.com/dart-lang/linter/pull/2578

After trying it out, I'm not concerned about the reduced squiggle length - it's pretty noticeable even for a single character, and it's actually a lot less noisy than before so I prefer it.

![Screenshot showing long lines of code with only the characters past 80 underlined](https://user-images.githubusercontent.com/1078012/114316755-cf94be80-9afc-11eb-914c-c9418f900660.png)

I'll close this issue as a dupe of [the linter issue](https://github.com/dart-lang/linter/issues/2570) since there's nothing to do here in the VS Code extension - if the fix ships in the SDK, you'll get it automatically when updating to a future SDK version.

If you find any other places you think can/should be improved (for screen readers or otherwise), please do file additional issues. Thanks!

**Comment by chrisnorman7** [comment] 2021-04-12 04:54
Legend, thank you so much.

Take care,

Chris Norman

**Closed** 2021-04-12 09:58 UTC
