### ISSUE TITLE
Automatic completion for method handlers / signatures not work when there is a parameter settled before the function

### ISSUE THREAD

**Issue by MiniSuperDev** [Dart-Code/Dart-Code#3959] opened 2022-05-13 20:02 UTC
**Describe the bug**
Automatic completion for method handlers / signatures not work when there is a parameter settled before the function.

**To Reproduce**
```dart
import 'package:flutter/material.dart';

void main() {
  const Foo(
    fun: , // auto complete works
    boolean: true,
  );

  const Foo(
    boolean: true,
    fun: , // auto complete not works
  );
}

class Foo<T> extends StatelessWidget {
  const Foo({
    Key? key,
    this.boolean,
    this.fun,
  }) : super(key: key);

  final Widget Function(bool boolean)? fun;
  final bool? boolean;

  @override
  Widget build(BuildContext context) {
    return Container();
  }
}
```

**Expected behavior**
It should show the correct code completion regardless of the order of the parameters

**Screenshots**
![image](https://user-images.githubusercontent.com/105388540/168380745-64307fcc-03c4-4a7c-a880-2200c6febdad.png)
![image](https://user-images.githubusercontent.com/105388540/168380628-12d443e3-fe5f-4e76-a3e8-043fa8eff22c.png)

**Please complete the following information:**
 - Operating System and version: Windows 10
 - VS Code version: 1.67.1
 - Dart extension version: v3.40.0 
 - Dart/Flutter SDK version: tested on flutter 2-3

**Comment by DanTup** [comment] 2022-05-16 09:31
I don't seem to be able to reproduce this on Flutter 3.0.0, here's what I see:

<img width="678" alt="Screenshot 2022-05-16 at 10 28 21" src="https://user-images.githubusercontent.com/1078012/168562420-127eab71-2882-41e2-b8e4-2e3a9d51016d.png">

Could you confirm the exact version of Flutter you're using (it should show in the status bar, bottom right) and also include a screenshot showing a larger number of items in the completion list so I can see exactly what _is_ showing up to compare?

Can you also confirm:

- how you're opening code completion - are you pressing `ctrl+space` at exactly that location?
- whether you have the "Dart: Use LSP" setting ticked in VS Code
  <img width="995" alt="Screenshot 2022-05-16 at 10 30 18" src="https://user-images.githubusercontent.com/1078012/168562753-1bf7c56c-a6f7-4f95-80a9-8243ac7dcfa1.png">
- what the Editor: Suggest Selection" is set to (if it's not set to "First", try setting it to first to see if that makes a difference)
  <img width="621" alt="Screenshot 2022-05-16 at 10 30 42" src="https://user-images.githubusercontent.com/1078012/168562882-080e472b-9140-4f52-910a-244d7d5b2197.png">

Thanks!

**Comment by MiniSuperDev** [comment] 2022-05-16 15:01
Hi,
I already had them activated

![image](https://user-images.githubusercontent.com/105388540/168613854-7c2d4633-434e-4113-9e14-a63e729c261c.png)
![image](https://user-images.githubusercontent.com/105388540/168614064-51d984df-661b-45dd-b7ec-1f031537b819.png)
Flutter 3.0.0
![image](https://user-images.githubusercontent.com/105388540/168614479-cf8b29cd-e8bf-487c-8619-36284d1a4c6c.png)

When auto complete works:
![image](https://user-images.githubusercontent.com/105388540/168620094-6f4a150f-4139-443a-9c9e-bd978035cf53.png)

When auto complete not works:
![image](https://user-images.githubusercontent.com/105388540/168620011-e6f70b84-dda0-4ee9-85b7-74d6d253c4d7.png)



it not works in flutter 2.10.0:
![image](https://user-images.githubusercontent.com/105388540/168617851-0f0630af-976d-4b4a-8bcd-f521f1292f1a.png)


It works normal in flutter 2.8.0
![image](https://user-images.githubusercontent.com/105388540/168617066-de055299-2eb7-4ff5-9d95-6ee8fce838c2.png)

It works normal in flutter 2.5.0
![image](https://user-images.githubusercontent.com/105388540/168618554-842839f1-d03c-4c0a-9fe6-99a5630696c7.png)

* I also tried and it does not autocomplete in Android Studio in version 2.10.0 or 3.0.0, previous versions work fine like in vs code 
![image](https://user-images.githubusercontent.com/105388540/168619780-89bbbea4-a97b-45b5-b960-69757e45a688.png)


* I use `ctrl+space` before the `,`

* I also tried in other pc with windows 10, and the same behavior in VS Code and Android Studio, so not work in Flutter versions 2.10.0 or 3.0.0

* flutter doctor -v
```bash
PS C:\flutter> flutter doctor -v
[√] Flutter (Channel unknown, 3.0.0, on Microsoft Windows [Version 10.0.19044.1706], locale en-US)
    • Flutter version 3.0.0 at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ee4e09cce0 (7 days ago), 2022-05-09 16:45:18 -0700
    • Engine revision d1b9a6938a
    • Dart version 2.17.0
    • DevTools version 2.12.2

[√] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at C:\Users\User\AppData\Local\Android\Sdk
    • Platform android-32, build-tools 32.0.0
    • ANDROID_SDK_ROOT = C:\Users\User\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Build Tools 2019 16.11.14)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools
    • Visual Studio Build Tools 2019 version 16.11.32428.217
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] VS Code (version 1.67.1)
    • VS Code at C:\Users\User\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.40.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19044.1706]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 101.0.4951.67
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 100.0.1185.44

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

Thank you

**Comment by DanTup** [comment] 2022-05-16 16:27
Looks like this has already been fixed via https://github.com/dart-lang/sdk/issues/48310 and https://github.com/dart-lang/sdk/commit/3428b449d191d5837558faf492cd60480496ea8d. Testing on latest Flutter `master` the issue does not reproduce.

So the fix will show up automatically in a future Flutter SDK release :-)

Thanks!

**Closed by DanTup** 2022-05-16 16:27 UTC
Labels: is bug, awaiting info
