### ISSUE TITLE
"Unable to find the library" for global evaluation when the current file is inside the lib folder

### ISSUE THREAD

**Issue by techvx** [Dart-Code/Dart-Code#4932] opened 2024-01-12 09:03 UTC
**Describe the bug**
Any attempt to execute an expression in VS Code's debug console for a Flutter app running in debug mode prints back:

```
1 + 1
Unable to find the library for file:///e%3A/Development/_code/Flutter/app_5/lib/main.dart
#0      DartDebugAdapter.evaluateRequest (package:dds/src/dap/adapters/dart.dart:1060:7)
<asynchronous suspension>
#1      BaseDebugAdapter.handle (package:dds/src/dap/base_debug_adapter.dart:141:7)
<asynchronous suspension>
```

**To Reproduce**
1. Create a new app via "Flutter: New Project".
2. Build it for Windows, in my case.
3. Attempt to evaluate any expression in VSC's debug console.
4. Observe the `unable to find the library` aforementioned error from above.

**Expected behavior**
Prior to the most recent upgrade to Flutter 3+ and Dart SDK 3.2.3, it was perfectly possible not only to evaluate arbitrary operations in global context, but also to reference the declarations in the `main.dart` directly. This was extremely useful for custom debugging, which would allow for inspection of surgical precision within any runtime object that required additional monitoring, as needed.

It would be most useful to get such an option back. Running the DevTools (2.28.4) directly in the browser, furthermore, still allows to do just that - at any point in time, with or without the breakpoint. DevTools aren't nearly as versatile and free of friction as the standard built-in debug console within VSC, however. Having to go back and forth in and out of the IDE adds quite a bit of additional mental overhead as well, which doesn't exactly feel as absolutely necessary.  

I see that the #4636 issue was closed as completed. Can this be considered a regression? The #4899 appears to have similar working, though the context seems to be limited to Dart only, with no mentioning of Flutter. The exact error appears to be different too, here.

**Screenshots**
<details>
<summary>compare the debug console:</summary>

![image](https://github.com/Dart-Code/Dart-Code/assets/25274461/aa2f3d63-f287-4a7c-9d53-64e33ee06641)
</details>

<details>
<summary>to the DevTools console:</summary>

![image](https://github.com/Dart-Code/Dart-Code/assets/25274461/b79c9dd9-9101-4fc1-8742-66e7c3a6fd49)
</details>

**Diagnostics**

<details>

<summary>Workspace Environment</summary>

```text
Dart Code extension: 3.80.0
Flutter extension: 3.80.0 (activated)

App: Visual Studio Code
App Host: desktop
Version: win 1.85.1

Workspace type: Flutter (LSP)

Dart (3.2.3): E:\Development\Flutter\3.3.10\bin\cache\dart-sdk
Flutter (3.16.6): E:\Development\Flutter\3.3.10 (Windows (windows-x64/windows))

```

</details>

<details>

<summary>Output from `dart info`</strong></summary>

`E:\Development\Flutter\3.3.10\bin\cache\dart-sdk\bin\dart.exe info`

If providing this information as part of reporting a bug, please review the information
below to ensure it only contains things you're comfortable posting publicly.

#### General info

- Dart 3.2.3 (stable) (Tue Dec 5 17:58:33 2023 +0000) on "windows_x64"
- on windows / "Windows 10 Pro" 10.0 (Build 19045)
- locale is en-US

#### Project info

- sdk constraint: '>=3.2.3 <4.0.0'
- dependencies: flutter
- dev_dependencies: flutter_lints, flutter_test
- elided dependencies: 2

#### Process info

| Memory | CPU | Elapsed time | Command line |
| -----: | --: | -----------: | ------------ |
|  82 MB |  -- |              | dart.exe     |
|  14 MB |  -- |              | dart.exe     |
|  39 MB |  -- |              | dart.exe     |
| 456 MB |  -- |              | dart.exe     |
|  47 MB |  -- |              | dart.exe     |
|  41 MB |  -- |              | dart.exe     |
|  86 MB |  -- |              | dart.exe     |
| 126 MB |  -- |              | dart.exe     |
| 374 MB |  -- |              | dart.exe     |
|  85 MB |  -- |              | dart.exe     |

</details>

<details>

<summary>Output from `flutter doctor`</summary>

`E:\Development\Flutter\3.3.10\bin\flutter.bat doctor -v`

```text
[√] Flutter (Channel stable, 3.16.6, on Microsoft Windows [Version 10.0.19045.3930], locale en-US)
    • Flutter version 3.16.6 on channel stable at E:\Development\Flutter\3.3.10
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 46787ee49c (2 days ago), 2024-01-09 14:36:07 -0800
    • Engine revision 3f3e560236
    • Dart version 3.2.3
    • DevTools version 2.28.4

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at E:\Programs\AndroidSDK
    • Platform android-33, build-tools 30.0.3
    • Java binary at: E:\Programs\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Community 2019 16.11.21)
    • Visual Studio at E:\Development\VS\Community
    • Visual Studio Community 2019 version 16.11.33027.164
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 4.2)
    • Android Studio at E:\Programs\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = E:\Programs\Android Studio
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19045.3930]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 120.0.6099.217
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 120.0.2210.121

[√] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by DanTup** [comment] 2024-01-15 12:01
I can repro.. seems to be specific to Windows and Flutter. On macOS, Dart+Flutter work and on Windows, Dart works.

For Windows + Flutter I get:

```
Unable to find the library for file:///c%3A/Dev/Test%20Projects/dartcode_4932/lib/main.dart
```

It seems unrelated to the casing of the drive letter (a common cause of errors like this) or the encoded colon (sending `C:/` does not fix anything).

**Comment by DanTup** [comment] 2024-01-15 15:23
Working on a fix at https://dart-review.googlesource.com/c/sdk/+/346400. Unfortunately it's not possible to work around the issue in the VS Code extension so the fix is going to come via a future SDK release.

**Comment by DanTup** [comment] 2024-01-24 13:29
Fixed by https://github.com/dart-lang/sdk/commit/a95b5841011dfbf888189b13e98df15cf1bc22e9. Ships in a future SDK release (rather than a Dart-Code release).

**Closed by DanTup** 2024-01-24 13:29 UTC
Labels: is bug, in debugger, relies on sdk changes

**Comment by dotkaio** [comment] 2024-05-25 07:51
the error persists

**Comment by DanTup** [comment] 2024-05-28 10:20
@dotkaio if you're on the latest version of the Dart/Flutter SDK and also the latest version of VS Code + Dart extension, could you file a new issue about this and include a log file from reproducing this in a sample project?

- Use the **Dart: New Project** or **Flutter: New Project** commands to create a new project
- Run the **Dart: Capture Debugging Logs** command to start capturing logs
- Reproduce the issue
- Click **Cancel** on the logging notification to stop logging and open the log file
- Open a new issue with the log file (ensuring it contains nothing sensitive - which should only be file paths if you did it using a new sample project)

Thanks!

**Comment by iulian0512** [comment] 2024-08-19 14:13
@DanTup is global evaluation supposed to work when attached to an android device(flutter app) ?
