### ISSUE TITLE
Saving and running 'Dart' formatter

### ISSUE THREAD

**Issue by t-kozak** [Dart-Code/Dart-Code#3398] opened 2021-06-09 05:18 UTC
This is a repost of https://github.com/microsoft/vscode/issues/124686 as per latest comment. 

Originally reported by @Garrison88

> Issue Type: Performance Issue
> 
> VS Code hangs while saving a file, even after making just a minor adjustment. It is trying to run the 'Dart' formatter, but never completes. I have tried completely uninstalling VS Code and restarting my Mac, but I am still experiencing the problem. It started when I updated Flutter to 2.2
> 
> VS Code version: Code 1.56.2 (Universal) ([054a929](https://github.com/microsoft/vscode/commit/054a9295330880ed74ceaedda236253b4f39a335), 2021-05-12T17:44:30.902Z)
> OS version: Darwin x64 20.5.0
> 
> System Info
> Item	Value
> CPUs	Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)
> GPU Status	2d_canvas: enabled
> gpu_compositing: enabled
> metal: disabled_off
> multiple_raster_threads: enabled_on
> oop_rasterization: enabled
> opengl: enabled_on
> rasterization: enabled
> skia_renderer: disabled_off_ok
> video_decode: enabled
> webgl: enabled
> webgl2: enabled
> Load (avg)	2, 2, 2
> Memory (System)	32.00GB (11.23GB free)
> Process Argv	--crash-reporter-id 3fdaa67d-ab40-4dbe-980d-b458b70df8e3
> Screen Reader	no
> VM	0%
> Process Info
> ```
> CPU %	Mem MB	   PID	Process
>    18	   164	  1261	code main
>     5	    98	  1265	   gpu-process
>     0	    33	  1270	   utility
>     4	   393	  1271	   window (master_details_view.dart — cmic_mobile_field)
>     0	   197	  1277	     extensionHost
>     0	    33	  1316	       /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Renderer).app/Contents/MacOS/Code Helper (Renderer) /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/json-language-features/server/dist/node/jsonServerMain --node-ipc --clientProcessId=1277
>     0	   721	  1335	       /Users/garrison/Development/flutter/bin/cache/dart-sdk/bin/dart /Users/garrison/Development/flutter/bin/cache/dart-sdk/bin/snapshots/analysis_server.dart.snapshot --lsp --client-id=VS-Code --client-version=3.22.0
>     0	     0	  1336	       bash /Users/garrison/Development/flutter/bin/flutter daemon
>     0	   164	  1355	         /Users/garrison/Development/flutter/bin/cache/dart-sdk/bin/dart --disable-dart-dev --packages=/Users/garrison/Development/flutter/packages/flutter_tools/.packages /Users/garrison/Development/flutter/bin/cache/flutter_tools.snapshot daemon
>     0	     0	  1382	           /usr/bin/script -t 0 /dev/null xcrun xcdevice observe --both
>     0	    33	  1383	             /Applications/Xcode.app/Contents/Developer/usr/bin/xcdevice observe --both
>     0	    66	  1356	       /Users/garrison/Development/flutter/bin/cache/dart-sdk/bin/dart /Users/garrison/Development/flutter/bin/cache/dart-sdk/bin/snapshots/pub.dart.snapshot global run devtools --machine --try-ports 10 --allow-embedding
>     0	    98	  1279	     watcherService
>     0	    33	  1433	     searchService
>     1	   131	  1278	   shared-process
>     0	    33	  1280	     ptyHost
>     0	     0	  6289	     /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
>     0	    66	  6276	   window (Issue Reporter)
> ```
> 
> Workspace Info
> ```
> |  Window (master_details_view.dart — cmic_mobile_field)
> |    Folder (cmic_mobile_field): 8211 files
> |      File types: svn-base(2037) dart(1421) h(754) png(479) strings(126)
> |                  m(115) plist(106) json(96) swift(91)
> |                  xcconfig(84)
> |      Conf files: settings.json(2) launch.json(1)
> |      Launch Configs: dart(9);
> ```
> 
> Extensions (4)
> Extension	Author (truncated)	Version
> bracket-pair-colorizer	Coe	1.0.61
> dart-code	Dar	3.22.0
> flutter	Dar	3.22.0
> material-icon-theme	PKi	4.7.0
> A/B Experiments
> ```
> vsliv368cf:30146710
> vsreu685:30147344
> python383:30185418
> pythonvspyt602:30300191
> vspor879:30202332
> vspor708:30202333
> vspor363:30204092
> vstes627:30244334
> pythonvspyt639:30300192
> pythontb:30283811
> vspre833:30267464
> pythonptprofiler:30281270
> vshan820:30294714
> pythondataviewer:30285071
> vscus158:30286553
> vscgsv2:30307504
> vscorehovct:30302760
> bridgeflight:30302069
> vscod805cf:30301675
> ```

**Comment by t-kozak** [comment] 2021-06-09 05:19
I am also experiencing this quite often. What can we (the community) do to help understand and root cause the issue?

**Comment by DanTup** [comment] 2021-06-09 09:02
There are a few issues that have been recently fixed that could lead to this, but it's not clear if they're the same issue you're hitting:

- Some people report removing code signing from Code helps (https://github.com/microsoft/vscode/issues/107103#issuecomment-731664821). It's not clear to me why that should be necessary, but it may be worth a try.
- Some complex expressions may take a while to format (if it never seems to complete it's probably not this) - https://github.com/dart-lang/dart_style/issues/1022
- Opening/Closing files may trigger expensive work in the analysis server - this was resolved in Fluter 2.2 by https://github.com/dart-lang/sdk/commit/e8d53cff924214ea8dd20b36bb82f7d2dde7a131.
- Some file modifications (particularly when running Flutter apps) may cause the analysis server to stop responding (https://github.com/dart-lang/sdk/issues/45996) - this has been fixed in Flutter master and there's an open request to cherry-pick to stable (https://github.com/dart-lang/sdk/issues/46249 and https://github.com/dart-lang/sdk/issues/46298)

If you've already upgraded to Flutter 2.2 and you're on macOS, then it could be the last one. If you're able to easily test using Flutter's master channel, I'd be very interested to know if the problem is solved. If that's not easy, then if the cherry-pick requests above are released in a hotfix, then it could be tested on stable once released.

If you can still reproduce on master (or after a hotfix that includes that fix), please let me know in #3270 which is tracking this issue (I'll close this one as a dupe of that). Thanks!

**Closed** 2021-06-09 09:02 UTC
Labels: duplicate

**Comment by t-kozak** [comment] 2021-06-09 23:05
Thanks, @DanTup I checked the dart-lang issue - good stuff!
