### ISSUE TITLE
Moving a file from one directory to another creates errors in a deleted file

### ISSUE THREAD

**Issue by nshahan** [Dart-Code/Dart-Code#5305] opened 2024-10-08 17:14 UTC
When moving files around in a package, I found this strange issue where there are analysis errors in a file that no longer exists. The only way I can find to clear the error is to close vscode and open it again.

<img width="846" alt="Screenshot 2024-10-08 at 10 09 52 AM" src="https://github.com/user-attachments/assets/51071169-b4a9-45af-9341-ea0246bbb3f4">

To reproduce start with a directory and file structure like this:
**lib/dir_a/a.dart**
```dart
import 'b.dart';
import '../dir_b/c.dart';

class A {
  final b = B();
  final c = C();
}
```

**lib/dir_a/b.dart**
```dart
class B {}
```

**lib/dir_b/c.dart**
```dart
class C {}
```

1) From the file explorer pane drag and drop `a.dart` from `dir_a` to `dir_b`. 
2) You will be prompted: "**_Are you sure you want to move 'a.dart' into 'dir_b'?_**" Chose "**_Move_**".
3) You will be promted: "**_Extension 'Dart' wants to make refactoring changes with this file move_**". Chose "**_OK_**".

**Comment by sv-22** [comment] 2024-10-09 13:41
Having same issue. It looks like it's not limited to Dart, I'm experiencing the same problem with go and it cropped up in the new VS Code release which appears to have broken a few things.

**Comment by DanTup** [comment] 2024-10-09 15:22
I don't seem to be able to reproduce this using the steps above (I'm also on the latest VS Code).

https://github.com/user-attachments/assets/b50d038a-a25c-4561-8975-7778b9de647a

Can you reproduce this reliable? If so, could you try running the **Dart: Capture Analysis Server Logs** command from the palette (`F1`), then reproduce the issue, then click **Cancel** on the logging notification to stop logging and open the log file to provide here?

If it's happening in Go, maybe there's a VS Code issue here, but I'd like to see the analyzer traffic to see if the right events are being sent to clear the diagnostics.

**Comment by nshahan** [comment] 2024-10-09 16:47
Yes, I can reproduce this issue consistently.

Visual Studio Code:
Version: 1.94.1 (Universal)
Commit: e10f2369d0d9614a452462f2e01cdc4aa9486296
Date: 2024-10-05T05:44:32.189Z (4 days ago)
Electron: 30.5.1
ElectronBuildId: 10262041
Chromium: 124.0.6367.243
Node.js: 20.16.0
V8: 12.4.254.20-electron.0
OS: Darwin arm64 23.6.0

```
Dart Code extension: 3.98.1

App: Visual Studio Code
App Host: desktop
Version: mac 1.94.1

Workspace type: Dart (LSP)
Workspace name: test_package

Dart (3.7.0-edge): /Users/nshahan/code/dart-sdk/sdk/xcodebuild/ReleaseARM64/dart-sdk
Flutter (3.22.0-6.0.pre.19): /Users/nshahan/code/flutter/flutter (No device)


Logging Categories:
    General, Analyzer, CommandProcesses

Wed Oct 09 2024 [09:34:35 GMT-0700 (Pacific Daylight Time)] Log file started
[9:34:36 AM] [Analyzer] [Info] ==> Content-Length: 230
[9:34:36 AM] [Analyzer] [Info] ==> {"jsonrpc":"2.0","id":506,"method":"textDocument/hover","params":{"textDocument":{"uri":"file:///Users/nshahan/code/test_files/test_package/lib/dir_a/a.dart"},"position":{"line":1,"character":5}},"clientRequestTime":1728491676911}
[9:34:36 AM] [Analyzer] [Info] <== Content-Length: 40
Content-Type: application/vscode-jsonrpc; charset=utf-8
[9:34:36 AM] [Analyzer] [Info] <== {"id":506,"jsonrpc":"2.0","result":null}
[9:34:42 AM] [Analyzer] [Info] ==> Content-Length: 278
[9:34:42 AM] [Analyzer] [Info] ==> {"jsonrpc":"2.0","id":507,"method":"workspace/willRenameFiles","params":{"files":[{"oldUri":"file:///Users/nshahan/code/test_files/test_package/lib/dir_a/a.dart","newUri":"file:///Users/nshahan/code/test_files/test_package/lib/dir_b/a.dart"}]},"clientRequestTime":1728491682940}
[9:34:42 AM] [Analyzer] [Info] <== Content-Length: 99
Content-Type: application/vscode-jsonrpc; charset=utf-8
[9:34:42 AM] [Analyzer] [Info] <== {"id":138,"jsonrpc":"2.0","method":"window/workDoneProgress/create","params":{"token":"ANALYZING"}}
[9:34:42 AM] [Analyzer] [Info] ==> Content-Length: 74
[9:34:42 AM] [Analyzer] [Info] ==> {"jsonrpc":"2.0","id":138,"result":null,"clientRequestTime":1728491682947}
[9:34:42 AM] [Analyzer] [Info] <== Content-Length: 118
Content-Type: application/vscode-jsonrpc; charset=utf-8
[9:34:42 AM] [Analyzer] [Info] <== {"jsonrpc":"2.0","method":"$/progress","params":{"token":"ANALYZING","value":{"kind":"begin","title":"Analyzing…"}}}
[9:34:42 AM] [Analyzer] [Info] <== Content-Length: 93
Content-Type: application/vscode-jsonrpc; charset=utf-8

{"jsonrpc":"2.0","method":"$/progress","params":{"token":"ANALYZING","value":{"kind":"end"}}}Content-Length: 596
Content-Type: application/vscode-jsonrpc; charset=utf-8
[9:34:42 AM] [Analyzer] [Info] <== {"id":507,"jsonrpc":"2.0","result":{"documentChanges":[{"edits":[{"newText":"'../dir_a/b.dart'","range":{"end":{"character":15,"line":0},"start":{"character":7,"line":0}}},{"newText":"'c.dart'","range":{"end":{"character":24,"line":1},"start":{"character":7,"line":1}}}],"textDocument":{"uri":"file:///Users/nshahan/code/test_files/test_package/lib/dir_a/a.dart","version":11}},{"edits":[{"newText":"'a.dart'","range":{"end":{"character":24,"line":0},"start":{"character":7,"line":0}}}],"textDocument":{"uri":"file:///Users/nshahan/code/test_files/test_package/lib/dir_b/d.dart","version":32}}]}}
[9:34:44 AM] [Analyzer] [Info] ==> Content-Length: 435
[9:34:44 AM] [Analyzer] [Info] ==> {"jsonrpc":"2.0","method":"textDocument/didChange","params":{"textDocument":{"uri":"file:///Users/nshahan/code/test_files/test_package/lib/dir_a/a.dart","version":12},"contentChanges":[{"range":{"start":{"line":1,"character":8},"end":{"line":1,"character":17}},"rangeLength":9,"text":""},{"range":{"start":{"line":0,"character":8},"end":{"line":0,"character":8}},"rangeLength":0,"text":"../dir_a/"}]},"clientRequestTime":1728491684565}
[9:34:44 AM] [Analyzer] [Info] <== Content-Length: 99
Content-Type: application/vscode-jsonrpc; charset=utf-8
[9:34:44 AM] [Analyzer] [Info] ==> Content-Length: 333
[9:34:44 AM] [Analyzer] [Info] ==> {"jsonrpc":"2.0","method":"textDocument/didChange","params":{"textDocument":{"uri":"file:///Users/nshahan/code/test_files/test_package/lib/dir_b/d.dart","version":33},"contentChanges":[{"range":{"start":{"line":0,"character":7},"end":{"line":0,"character":24}},"rangeLength":17,"text":"'a.dart'"}]},"clientRequestTime":1728491684567}
[9:34:44 AM] [Analyzer] [Info] <== {"id":139,"jsonrpc":"2.0","method":"window/workDoneProgress/create","params":{"token":"ANALYZING"}}
[9:34:44 AM] [Analyzer] [Info] <== Content-Length: 166
Content-Type: application/vscode-jsonrpc; charset=utf-8
[9:34:44 AM] [Analyzer] [Info] ==> Content-Length: 74
[9:34:44 AM] [Analyzer] [Info] ==> {"jsonrpc":"2.0","id":139,"result":null,"clientRequestTime":1728491684575}
[9:34:44 AM] [Analyzer] [Info] <== {"jsonrpc":"2.0","method":"dart/textDocument/publishClosingLabels","params":{"labels":[],"uri":"file:///Users/nshahan/code/test_files/test_package/lib/dir_b/a.dart"}}
[9:34:44 AM] [Analyzer] [Info] <== Content-Length: 1300
Content-Type: application/vscode-jsonrpc; charset=utf-8

{"jsonrpc":"2.0","method":"dart/textDocument/publishOutline","params":{"outline":{"children":[{"children":[{"codeRange":{"end":{"character":15,"line":4},"start":{"character":8,"line":4}},"element":{"kind":"FIELD","name":"b","range":{"end":{"character":9,"line":4},"start":{"character":8,"line":4}},"returnType":""},"range":{"end":{"character":16,"line":4},"start":{"character":2,"line":4}}},{"codeRange":{"end":{"character":15,"line":5},"start":{"character":8,"line":5}},"element":{"kind":"FIELD","name":"c","range":{"end":{"character":9,"line":5},"start":{"character":8,"line":5}},"returnType":""},"range":{"end":{"character":16,"line":5},"start":{"character":2,"line":5}}}],"codeRange":{"end":{"character":1,"line":6},"start":{"character":0,"line":3}},"element":{"kind":"CLASS","name":"A","range":{"end":{"character":7,"line":3},"start":{"character":6,"line":3}}},"range":{"end":{"character":1,"line":6},"start":{"character":0,"line":3}}}],"codeRange":{"end":{"character":0,"line":7},"start":{"character":0,"line":0}},"element":{"kind":"COMPILATION_UNIT","name":"<unit>","range":{"end":{"character":0,"line":7},"start":{"character":0,"line":0}}},"range":{"end":{"character":0,"line":7},"start":{"character":0,"line":0}}},"uri":"file:///Users/nshahan/code/test_files/test_package/lib/dir_b/a.dart"}}Content-Length: 166
Content-Type: application/vscode-jsonrpc; charset=utf-8
[9:34:44 AM] [Analyzer] [Info] <== {"jsonrpc":"2.0","method":"dart/textDocument/publishClosingLabels","params":{"labels":[],"uri":"file:///Users/nshahan/code/test_files/test_package/lib/dir_b/a.dart"}}
[9:34:44 AM] [Analyzer] [Info] <== Content-Length: 1300
Content-Type: application/vscode-jsonrpc; charset=utf-8
[9:34:44 AM] [Analyzer] [Info] <== {"jsonrpc":"2.0","method":"dart/textDocument/publishOutline","params":{"outline":{"children":[{"children":[{"codeRange":{"end":{"character":15,"line":4},"start":{"character":8,"line":4}},"element":{"kind":"FIELD","name":"b","range":{"end":{"character":9,"line":4},"start":{"character":8,"line":4}},"returnType":""},"range":{"end":{"character":16,"line":4},"start":{"character":2,"line":4}}},{"codeRange":{"end":{"character":15,"line":5},"start":{"character":8,"line":5}},"element":{"kind":"FIELD","name":"c","range":{"end":{"character":9,"line":5},"start":{"character":8,"line":5}},"returnType":""},"range":{"end":{"character":16,"line":5},"start":{"character":2,"line":5}}}],"codeRange":{"end":{"character":1,"line":6},"start":{"character":0,"line":3}},"element":{"kind":"CLASS","name":"A","range":{"end":{"character":7,"line":3},"start":{"character":6,"line":3}}},"range":{"end":{"character":1,"line":6},"start":{"character":0,"line":3}}}],"codeRange":{"end":{"character":0,"line":7},"start":{"character":0,"line":0}},"element":{"kind":"COMPILATION_UNIT","name":"<unit>","range":{"end":{"character":0,"line":7},"start":{"character":0,"line":0}}},"range":{"end":{"character":0,"line":7},"start":{"character":0,"line":0}}},"uri":"file:///Users/nshahan/code/test_files/test_package/lib/dir_b/a.dart"}}
[9:34:44 AM] [Analyzer] [Info] <== Content-Length: 877
Content-Type: application/vscode-jsonrpc; charset=utf-8

{"jsonrpc":"2.0","method":"textDocument/publishDiagnostics","params":{"diagnostics":[{"code":"uri_does_not_exist","codeDescription":{"href":"https://dart.dev/diagnostics/uri_does_not_exist"},"message":"Target of URI doesn't exist: 'c.dart'.\nTry creating the file referenced by the URI, or try using a URI for a file that does exist.","range":{"end":{"character":15,"line":1},"start":{"character":7,"line":1}},"severity":1,"source":"dart"},{"code":"undefined_method","codeDescription":{"href":"https://dart.dev/diagnostics/undefined_method"},"message":"The method 'C' isn't defined for the type 'A'.\nTry correcting the name to the name of an existing method, or defining a method named 'C'.","range":{"end":{"character":13,"line":5},"start":{"character":12,"line":5}},"severity":1,"source":"dart"}],"uri":"file:///Users/nshahan/code/test_files/test_package/lib/dir_a/a.dart"}}
[9:34:44 AM] [Analyzer] [Info] <== Content-Length: 166
Content-Type: application/vscode-jsonrpc; charset=utf-8

{"jsonrpc":"2.0","method":"dart/textDocument/publishClosingLabels","params":{"labels":[],"uri":"file:///Users/nshahan/code/test_files/test_package/lib/dir_a/a.dart"}}Content-Length: 1300
Content-Type: application/vscode-jsonrpc; charset=utf-8

{"jsonrpc":"2.0","method":"dart/textDocument/publishOutline","params":{"outline":{"children":[{"children":[{"codeRange":{"end":{"character":15,"line":4},"start":{"character":8,"line":4}},"element":{"kind":"FIELD","name":"b","range":{"end":{"character":9,"line":4},"start":{"character":8,"line":4}},"returnType":""},"range":{"end":{"character":16,"line":4},"start":{"character":2,"line":4}}},{"codeRange":{"end":{"character":15,"line":5},"start":{"character":8,"line":5}},"element":{"kind":"FIELD","name":"c","range":{"end":{"character":9,"line":5},"start":{"character":8,"line":5}},"returnType":""},"range":{"end":{"character":16,"line":5},"start":{"character":2,"line":5}}}],"codeRange":{"end":{"character":1,"line":6},"start":{"character":0,"line":3}},"element":{"kind":"CLASS","name":"A","range":{"end":{"character":7,"line":3},"start":{"character":6,"line":3}}},"range":{"end":{"character":1,"line":6},"start":{"character":0,"line":3}}}],"codeRange":{"end":{"character":0,"line":7},"start":{"character":0,"line":0}},"element":{"kind":"COMPILATION_UNIT","name":"<unit>","range":{"end":{"character":0,"line":7},"start":{"character":0,"line":0}}},"range":{"end":{"character":0,"line":7},"start":{"character":0,"line":0}}},"uri":"file:///Users/nshahan/code/test_files/test_package/lib/dir_a/a.dart"}}Content-Length: 118
Content-Type: application/vscode-jsonrpc; charset=utf-8

{"jsonrpc":"2.0","method":"$/progress","params":{"token":"ANALYZING","value":{"kind":"begin","title":"Analyzing…"}}}
[9:34:44 AM] [Analyzer] [Info] <== Content-Length: 166
Content-Type: application/vscode-jsonrpc; charset=utf-8

{"jsonrpc":"2.0","method":"dart/textDocument/publishClosingLabels","params":{"labels":[],"uri":"file:///Users/nshahan/code/test_files/test_package/lib/dir_b/d.dart"}}Content-Length: 1016
Content-Type: application/vscode-jsonrpc; charset=utf-8
[9:34:44 AM] [Analyzer] [Info] <== {"jsonrpc":"2.0","method":"dart/textDocument/publishOutline","params":{"outline":{"children":[{"children":[{"codeRange":{"end":{"character":15,"line":3},"start":{"character":8,"line":3}},"element":{"kind":"FIELD","name":"a","range":{"end":{"character":9,"line":3},"start":{"character":8,"line":3}},"returnType":""},"range":{"end":{"character":16,"line":3},"start":{"character":2,"line":3}}}],"codeRange":{"end":{"character":1,"line":4},"start":{"character":0,"line":2}},"element":{"kind":"CLASS","name":"D","range":{"end":{"character":7,"line":2},"start":{"character":6,"line":2}}},"range":{"end":{"character":1,"line":4},"start":{"character":0,"line":2}}}],"codeRange":{"end":{"character":0,"line":5},"start":{"character":0,"line":0}},"element":{"kind":"COMPILATION_UNIT","name":"<unit>","range":{"end":{"character":0,"line":5},"start":{"character":0,"line":0}}},"range":{"end":{"character":0,"line":5},"start":{"character":0,"line":0}}},"uri":"file:///Users/nshahan/code/test_files/test_package/lib/dir_b/d.dart"}}Content-Length: 93
Content-Type: application/vscode-jsonrpc; charset=utf-8

{"jsonrpc":"2.0","method":"$/progress","params":{"token":"ANALYZING","value":{"kind":"end"}}}
[9:34:44 AM] [Analyzer] [Info] ==> Content-Length: 202
[9:34:44 AM] [Analyzer] [Info] ==> {"jsonrpc":"2.0","id":508,"method":"textDocument/documentColor","params":{"textDocument":{"uri":"file:///Users/nshahan/code/test_files/test_package/lib/dir_b/a.dart"}},"clientRequestTime":1728491684607}
[9:34:44 AM] [Analyzer] [Info] ==> Content-Length: 318
[9:34:44 AM] [Analyzer] [Info] ==> {"jsonrpc":"2.0","id":509,"method":"textDocument/codeAction","params":{"textDocument":{"uri":"file:///Users/nshahan/code/test_files/test_package/lib/dir_b/a.dart"},"range":{"start":{"line":0,"character":0},"end":{"line":0,"character":0}},"context":{"diagnostics":[],"triggerKind":2}},"clientRequestTime":1728491684607}
[9:34:44 AM] [Analyzer] [Info] <== Content-Length: 99
Content-Type: application/vscode-jsonrpc; charset=utf-8
[9:34:44 AM] [Analyzer] [Info] <== {"id":140,"jsonrpc":"2.0","method":"window/workDoneProgress/create","params":{"token":"ANALYZING"}}
[9:34:44 AM] [Analyzer] [Info] ==> Content-Length: 74
[9:34:44 AM] [Analyzer] [Info] ==> {"jsonrpc":"2.0","id":140,"result":null,"clientRequestTime":1728491684611}
[9:34:44 AM] [Analyzer] [Info] <== Content-Length: 38
Content-Type: application/vscode-jsonrpc; charset=utf-8
[9:34:44 AM] [Analyzer] [Info] <== {"id":508,"jsonrpc":"2.0","result":[]}
[9:34:44 AM] [Analyzer] [Info] <== Content-Length: 1689
Content-Type: application/vscode-jsonrpc; charset=utf-8
[9:34:44 AM] [Analyzer] [Info] <== {"id":509,"jsonrpc":"2.0","result":[{"command":{"arguments":[{"path":"/Users/nshahan/code/test_files/test_package/lib/dir_b/a.dart","autoTriggered":true}],"command":"dart.edit.sortMembers","title":"Sort Members"},"kind":"source.sortMembers","title":"Sort Members"},{"command":{"arguments":[{"path":"/Users/nshahan/code/test_files/test_package/lib/dir_b/a.dart","autoTriggered":true}],"command":"dart.edit.organizeImports","title":"Organize Imports"},"kind":"source.organizeImports","title":"Organize Imports"},{"command":{"arguments":[{"path":"/Users/nshahan/code/test_files/test_package/lib/dir_b/a.dart","autoTriggered":true}],"command":"dart.edit.fixAll","title":"Fix All"},"kind":"source.fixAll","title":"Fix All"},{"command":{"arguments":[{"action":"dart.assist.convert.relativeToPackageImport"}],"command":"dart.logAction","title":"Log Action"},"diagnostics":[],"edit":{"documentChanges":[{"edits":[{"newText":"'package:test_package/dir_a/b.dart'","range":{"end":{"character":24,"line":0},"start":{"character":7,"line":0}}}],"textDocument":{"uri":"file:///Users/nshahan/code/test_files/test_package/lib/dir_b/a.dart","version":1}}]},"kind":"refactor.convert.relativeToPackageImport","title":"Convert to 'package:' import"},{"command":{"arguments":[{"action":"dart.assist.add.showCombinator"}],"command":"dart.logAction","title":"Log Action"},"diagnostics":[],"edit":{"documentChanges":[{"edits":[{"newText":" show B","range":{"end":{"character":24,"line":0},"start":{"character":24,"line":0}}}],"textDocument":{"uri":"file:///Users/nshahan/code/test_files/test_package/lib/dir_b/a.dart","version":1}}]},"kind":"refactor.add.showCombinator","title":"Add explicit 'show' combinator"}]}
[9:34:44 AM] [Analyzer] [Info] <== Content-Length: 118
Content-Type: application/vscode-jsonrpc; charset=utf-8

{"jsonrpc":"2.0","method":"$/progress","params":{"token":"ANALYZING","value":{"kind":"begin","title":"Analyzing…"}}}
[9:34:44 AM] [Analyzer] [Info] <== Content-Length: 93
Content-Type: application/vscode-jsonrpc; charset=utf-8
[9:34:44 AM] [Analyzer] [Info] <== {"jsonrpc":"2.0","method":"$/progress","params":{"token":"ANALYZING","value":{"kind":"end"}}}
[9:34:44 AM] [Analyzer] [Info] ==> Content-Length: 201
[9:34:44 AM] [Analyzer] [Info] ==> {"jsonrpc":"2.0","id":510,"method":"textDocument/documentLink","params":{"textDocument":{"uri":"file:///Users/nshahan/code/test_files/test_package/lib/dir_b/a.dart"}},"clientRequestTime":1728491684633}
[9:34:44 AM] [Analyzer] [Info] ==> Content-Length: 272
[9:34:44 AM] [Analyzer] [Info] ==> {"jsonrpc":"2.0","id":511,"method":"textDocument/inlayHint","params":{"textDocument":{"uri":"file:///Users/nshahan/code/test_files/test_package/lib/dir_b/a.dart"},"range":{"start":{"line":0,"character":0},"end":{"line":7,"character":0}}},"clientRequestTime":1728491684633}
[9:34:44 AM] [Analyzer] [Info] <== Content-Length: 38
Content-Type: application/vscode-jsonrpc; charset=utf-8
[9:34:44 AM] [Analyzer] [Info] <== {"id":510,"jsonrpc":"2.0","result":[]}Content-Length: 545
Content-Type: application/vscode-jsonrpc; charset=utf-8

{"id":511,"jsonrpc":"2.0","result":[{"kind":1,"label":[{"location":{"range":{"end":{"character":7,"line":0},"start":{"character":6,"line":0}},"uri":"file:///Users/nshahan/code/test_files/test_package/lib/dir_a/b.dart"},"value":"B"}],"paddingRight":true,"position":{"character":8,"line":4}},{"kind":1,"label":[{"location":{"range":{"end":{"character":7,"line":0},"start":{"character":6,"line":0}},"uri":"file:///Users/nshahan/code/test_files/test_package/lib/dir_b/c.dart"},"value":"C"}],"paddingRight":true,"position":{"character":8,"line":5}}]}
[9:34:44 AM] [Analyzer] [Info] <== Content-Length: 99
Content-Type: application/vscode-jsonrpc; charset=utf-8

{"id":141,"jsonrpc":"2.0","method":"window/workDoneProgress/create","params":{"token":"ANALYZING"}}
[9:34:44 AM] [Analyzer] [Info] ==> Content-Length: 201
[9:34:44 AM] [Analyzer] [Info] ==> {"jsonrpc":"2.0","id":512,"method":"textDocument/foldingRange","params":{"textDocument":{"uri":"file:///Users/nshahan/code/test_files/test_package/lib/dir_b/a.dart"}},"clientRequestTime":1728491684822}
[9:34:44 AM] [Analyzer] [Info] <== Content-Length: 110
Content-Type: application/vscode-jsonrpc; charset=utf-8

{"id":512,"jsonrpc":"2.0","result":[{"endLine":1,"kind":"imports","startLine":0},{"endLine":6,"startLine":3}]}
[9:34:44 AM] [Analyzer] [Info] ==> Content-Length: 74
[9:34:44 AM] [Analyzer] [Info] ==> {"jsonrpc":"2.0","id":141,"result":null,"clientRequestTime":1728491684829}
[9:34:44 AM] [Analyzer] [Info] <== Content-Length: 118
Content-Type: application/vscode-jsonrpc; charset=utf-8
[9:34:44 AM] [Analyzer] [Info] <== {"jsonrpc":"2.0","method":"$/progress","params":{"token":"ANALYZING","value":{"kind":"begin","title":"Analyzing…"}}}
[9:34:44 AM] [Analyzer] [Info] <== Content-Length: 93
Content-Type: application/vscode-jsonrpc; charset=utf-8

{"jsonrpc":"2.0","method":"$/progress","params":{"token":"ANALYZING","value":{"kind":"end"}}}
[9:34:44 AM] [Analyzer] [Info] ==> Content-Length: 320
[9:34:44 AM] [Analyzer] [Info] ==> {"jsonrpc":"2.0","id":513,"method":"textDocument/codeAction","params":{"textDocument":{"uri":"file:///Users/nshahan/code/test_files/test_package/lib/dir_b/a.dart"},"range":{"start":{"line":5,"character":16},"end":{"line":5,"character":16}},"context":{"diagnostics":[],"triggerKind":2}},"clientRequestTime":1728491684855}
[9:34:44 AM] [Analyzer] [Info] <== Content-Length: 99
Content-Type: application/vscode-jsonrpc; charset=utf-8
[9:34:44 AM] [Analyzer] [Info] <== {"id":142,"jsonrpc":"2.0","method":"window/workDoneProgress/create","params":{"token":"ANALYZING"}}
[9:34:44 AM] [Analyzer] [Info] <== Content-Length: 1187
Content-Type: application/vscode-jsonrpc; charset=utf-8
[9:34:44 AM] [Analyzer] [Info] <== {"id":513,"jsonrpc":"2.0","result":[{"command":{"arguments":[{"path":"/Users/nshahan/code/test_files/test_package/lib/dir_b/a.dart","autoTriggered":true}],"command":"dart.edit.sortMembers","title":"Sort Members"},"kind":"source.sortMembers","title":"Sort Members"},{"command":{"arguments":[{"path":"/Users/nshahan/code/test_files/test_package/lib/dir_b/a.dart","autoTriggered":true}],"command":"dart.edit.organizeImports","title":"Organize Imports"},"kind":"source.organizeImports","title":"Organize Imports"},{"command":{"arguments":[{"path":"/Users/nshahan/code/test_files/test_package/lib/dir_b/a.dart","autoTriggered":true}],"command":"dart.edit.fixAll","title":"Fix All"},"kind":"source.fixAll","title":"Fix All"},{"command":{"arguments":[{"action":"dart.assist.convert.finalFieldToGetter"}],"command":"dart.logAction","title":"Log Action"},"diagnostics":[],"edit":{"documentChanges":[{"edits":[{"newText":"get c => C();","range":{"end":{"character":16,"line":5},"start":{"character":2,"line":5}}}],"textDocument":{"uri":"file:///Users/nshahan/code/test_files/test_package/lib/dir_b/a.dart","version":1}}]},"kind":"refactor.convert.finalFieldToGetter","title":"Convert to getter"}]}
[9:34:44 AM] [Analyzer] [Info] ==> Content-Length: 74
[9:34:44 AM] [Analyzer] [Info] ==> {"jsonrpc":"2.0","id":142,"result":null,"clientRequestTime":1728491684858}
[9:34:44 AM] [Analyzer] [Info] <== Content-Length: 118
Content-Type: application/vscode-jsonrpc; charset=utf-8

{"jsonrpc":"2.0","method":"$/progress","params":{"token":"ANALYZING","value":{"kind":"begin","title":"Analyzing…"}}}Content-Length: 93
Content-Type: application/vscode-jsonrpc; charset=utf-8
[9:34:44 AM] [Analyzer] [Info] <== {"jsonrpc":"2.0","method":"$/progress","params":{"token":"ANALYZING","value":{"kind":"end"}}}
[9:34:44 AM] [Analyzer] [Info] ==> Content-Length: 197
[9:34:44 AM] [Analyzer] [Info] ==> {"jsonrpc":"2.0","id":514,"method":"textDocument/codeLens","params":{"textDocument":{"uri":"file:///Users/nshahan/code/test_files/test_package/lib/dir_b/a.dart"}},"clientRequestTime":1728491684878}
[9:34:44 AM] [Analyzer] [Info] <== Content-Length: 38
Content-Type: application/vscode-jsonrpc; charset=utf-8
[9:34:44 AM] [Analyzer] [Info] <== {"id":514,"jsonrpc":"2.0","result":[]}
[9:34:44 AM] [Analyzer] [Info] ==> Content-Length: 208
[9:34:44 AM] [Analyzer] [Info] ==> {"jsonrpc":"2.0","id":515,"method":"textDocument/semanticTokens/full","params":{"textDocument":{"uri":"file:///Users/nshahan/code/test_files/test_package/lib/dir_b/a.dart"}},"clientRequestTime":1728491684902}
[9:34:44 AM] [Analyzer] [Info] <== Content-Length: 171
Content-Type: application/vscode-jsonrpc; charset=utf-8
[9:34:44 AM] [Analyzer] [Info] <== {"id":515,"jsonrpc":"2.0","result":{"data":[0,0,6,1,0,0,7,17,15,0,1,0,6,1,0,0,7,8,15,0,2,0,5,1,0,0,6,1,2,4,1,2,5,1,0,0,6,1,5,20,0,4,1,2,2,1,2,5,1,0,0,6,1,5,20,0,4,1,2,2]}}
[9:34:44 AM] [Analyzer] [Info] ==> Content-Length: 203
[9:34:44 AM] [Analyzer] [Info] ==> {"jsonrpc":"2.0","id":516,"method":"textDocument/documentSymbol","params":{"textDocument":{"uri":"file:///Users/nshahan/code/test_files/test_package/lib/dir_b/a.dart"}},"clientRequestTime":1728491684930}
[9:34:44 AM] [Analyzer] [Info] <== Content-Length: 646
Content-Type: application/vscode-jsonrpc; charset=utf-8
[9:34:44 AM] [Analyzer] [Info] <== {"id":516,"jsonrpc":"2.0","result":[{"children":[{"deprecated":false,"kind":8,"name":"b","range":{"end":{"character":15,"line":4},"start":{"character":8,"line":4}},"selectionRange":{"end":{"character":9,"line":4},"start":{"character":8,"line":4}}},{"deprecated":false,"kind":8,"name":"c","range":{"end":{"character":15,"line":5},"start":{"character":8,"line":5}},"selectionRange":{"end":{"character":9,"line":5},"start":{"character":8,"line":5}}}],"deprecated":false,"kind":5,"name":"A","range":{"end":{"character":1,"line":6},"start":{"character":0,"line":3}},"selectionRange":{"end":{"character":7,"line":3},"start":{"character":6,"line":3}}}]}
Wed Oct 09 2024 [09:34:47 GMT-0700 (Pacific Daylight Time)] Log file ended
```

**Comment by nshahan** [comment] 2024-10-09 16:51
An interesting note, I can see in the log references to another file `d.dart` that was deleted previously before I moved the `a.dart` from one directory to another.

**Comment by chenzhiguang** [comment] 2024-10-10 02:55
I have been suffering this issue for a while, not sure when. As Nicholas mentioned, it might not be related to the Dart analyzer. Here's another way to reproduce the issue:

- Open `a.dart` and import `b.dart`.
- Delete `b.dart` without opening it in the current session -- a file does not exist error is shown in `a.dart`.
- Reproduce the issue by opening `b.dart`, then deleting it -- no error is shown in `a.dart` after deletion.

Also, undo could restore the history before the tab was closed. I'm not sure if this is related to the setting: `"files.restoreUndoStack": false` as it has been set to `false` since I started using VSCode.

**Comment by chenzhiguang** [comment] 2024-10-10 03:00
It could be related:
https://github.com/microsoft/vscode/issues/230453

**Comment by chenzhiguang** [comment] 2024-10-10 09:34
Cool, they will fix it :) 
https://github.com/microsoft/vscode/issues/230995#issuecomment-2404145870

**Comment by DanTup** [comment] 2024-10-10 09:46
@nshahan thanks - in your log I don't see any events for the old file being closed, so I'm not surprised you see the behaviour you see. But it's not clear to me why VS code would not have sent events for this.

Is it possible you can capture an [instrumentation log](https://dartcode.org/docs/logging/#analyzer-instrumentation) for this? That is logged from the server and will include the file watcher events.

@chenzhiguang it's not clear to me how that issue is related (it seems related to the undo stack?).. though if the issue might be preventing the files from being closed, maybe it is. It would be good if someone that can repro this can test once that version is out (it's still not clear to me why I can't repro though).

**Comment by chenzhiguang** [comment] 2024-10-11 06:35
I just tried version 1.94.2, and now the issues @nshahan reported, and the ones I encountered, are all fixed.

**Comment by nshahan** [comment] 2024-10-11 16:45
Since updating to 1.94.2 I have not been able to reproduce the issue. Feel free to close this issue unless someone else can reproduce it now.

**Comment by DanTup** [comment] 2024-10-11 16:48
Thanks for confirming - seems likely it was this VS Code issue so I'll close this. If the issue comes back we can re-open (or file a new issue).

**Closed by DanTup** 2024-10-11 16:48 UTC
Labels: awaiting info
