### ISSUE TITLE
single/double quote refactor, auto add ending semicolon

### ISSUE THREAD

**Issue by liudonghua123** [Dart-Code/Dart-Code#2276] opened 2020-02-28 09:21 UTC
Is there any plans to refactor the coding using the consistent quotes single or double, and auto add the missing ending semicolon like ESLint in Javascript world.

This would be nice for beginers.

Now I am using VSCode a lot, these two features are very practical for me.

**Comment by DanTup** [comment] 2020-02-29 12:12
There are existing quick-fixes to help you change quotes, but they need invoking on each string you want to change. Are you looking for something that will just run on a whole project? I don't know of anything that adds semicolons (though I think you'll probably get used to typing these yourself in time).

There are two tools that make fixes to code though - `dartfmt` which fixes formatting, and `dartfix` which is aimed to help migrate code for new SDKs/features. The formatter is integrated with VS Code, though `dartfix` is not currently (it may be in future). Since the VS Code extension doesn't parse the language itself (everything is delegated to tools in the SDK) any fixes like this would need to be implemented there - so these requests would need to be raised at https://github.com/dart-lang/sdk.

Thanks!

**Comment by liudonghua123** [comment] 2020-03-01 01:24
Hi @DanTup , Thanks for your detailed solutions, I will try and give you the feedback later.

**Comment by liudonghua123** [comment] 2020-03-01 01:39
I reference a dart-sdk issue https://github.com/dart-lang/sdk/issues/30347 here for community discussion and feedback.

**Comment by DanTup** [comment] 2020-04-23 09:20
Closing this as I think it's a dupe of other issues (https://github.com/dart-lang/sdk/issues/30347 and perhaps https://github.com/Dart-Code/Dart-Code/issues/2367).

**Closed by DanTup** 2020-04-23 09:20 UTC
Labels: upstream in dart / flutter
