### ISSUE TITLE
macOS Regression - Start Debugging button/command/icon missing from Touch Bar

### ISSUE THREAD

**Issue by Abhijit-Revamp** [Dart-Code/Dart-Code#3342] opened 2021-05-14 07:32 UTC
**Describe the bug**
The start debugging button/icon on the Mac touch-bar is not visible if you are in EXPLORER view (left pane) 

**To Reproduce**
1. Update to latest DART plugin v3.22.0
2. Open flutter project (any one)
3. Activate Explorer view.
4. On Touch Bar start debugging icon / button is missing
5. Before v3.22.0, the icon was appearing and was also working fine

**Expected behavior**
Start debugging option on Touch Bar must be available in explorer view as earlier.

**Screenshots**

**Versions (please complete the following information):**
 - VS Code version: 1.56.0
 - Dart extension version: v3.22.0
 - Dart/Flutter SDK version: Channel master, 2.3.0-2.0.pre.79, on macOS 11.3.1 20E241 darwin-x64

**Comment by Abhijit-Revamp** [comment] 2021-05-14 07:35
![image](https://user-images.githubusercontent.com/44320018/118237437-f4da6b00-b4b4-11eb-8d42-9c864cd2386f.png)

**Comment by DanTup** [comment] 2021-05-17 10:41
I'm not able to reproduce this - when I open a Flutter project and put focus in the explorer view I see this in the touchbar:

![PXL_20210517_103932692 MP](https://user-images.githubusercontent.com/1078012/118475884-bf2bc100-b704-11eb-91d6-919c4c937eea.jpg)

Can you confirm exactly what you're seeing when the explorer has focus?

**Comment by Abhijit-Revamp** [comment] 2021-05-27 20:34
Sorry, I missed the trigger.

Here are the steps. 
1. Open any flutter project in VSCode - by default the explorer pane is opened
2. Touch Bar shows the debug icons - so far so good
3. open any dart file from explorer and single click on any line in the dart file
4. DEBUG icon disappear from Touch Bar
5. Close the dart file -- Debug icons come back
6. Now start debugging - Touch Bar shows multiple debug icons -- GOOD
7. open any dart file from explorer -- Icons gone

**Comment by DanTup** [comment] 2021-06-09 12:29
Thanks - I think I see what you mean now. When I open a file, I see the following:

![PXL_20210609_122325080](https://user-images.githubusercontent.com/1078012/121353977-58c24900-c926-11eb-9707-54bfd402524a.jpg)

This appears to be showing text suggestions because the cursor is in a text field. Tapping the small arrow pointing to the right collapses it and the buttons show up again:

![PXL_20210609_122332257](https://user-images.githubusercontent.com/1078012/121354053-6bd51900-c926-11eb-87c4-cacc8f9f5c38.jpg)

Unfortunately this is either VS Code or Electron behaviour, and not something the Dart extension has any influence over (you'll see it in any file, not only Dart).

It looks like it was fixed in the past in https://github.com/microsoft/vscode/issues/106541, but seems like it's come back. I would suggest filing a new VS Code issue and lining to that one, since if it's been fixed in the past this seems like a regression.

Thanks!

**Closed** 2021-06-09 12:30 UTC
Labels: upstream in vs code / lsp / dap

**Comment by DanTup** [comment] 2021-06-09 12:33
Looks like this was already re-raised and fixed in the upcoming VS Code release:

https://github.com/microsoft/vscode/issues/123105
