### ISSUE TITLE
Link package URIs in terminal output

### ISSUE THREAD

**Issue by audkar** [Dart-Code/Dart-Code#2099] opened 2019-11-14 10:24 UTC
Stacktrace is printed out to `Test Output` as plain text. It would be useful if we could click on specific line and navigate to related code.

#### case:
e.g. test fails with such output in `Test Output` window:
```
ERROR: NoSuchMethodError: The method 'call' was called on null.
Receiver: null
Tried calling: call()
dart:core                                                                       Object.noSuchMethod
test/service/geocode_repository_mock.dart 12:7                                  MockGeocodeRepository.locationsFromCoordinates
package:mypackage/src/feature/location_picker/bloc/location_picker_bloc.dart 32:29
<...>
```
#### expectation:
clicking `package:mypackage/src/feature/location_picker/bloc/location_picker_bloc.dart 32:29` navigates to `location_picker_bloc.dart 32`

**Comment by DanTup** [comment] 2019-11-14 12:58
Unfortunately as far as I can tell, the Output window doesn't seem have an API for attaching source locations to messages. Automatic detection of links is something that would have to be done by VS Code (and would need to provide us an API to supply information for resolving `package:` paths).

When you run tests, the output should also appear in the Debug Console, which should have its stack frames linked to the source locations - does that work for you?

**Comment by audkar** [comment] 2019-11-14 13:17
Maybe that would work. But I am not debugging my tests. I am simply running them. It should not be necessary to use debbuging only to get test result. 

Other tools properly registers test tasks:
![image](https://user-images.githubusercontent.com/1947112/68860080-6cc5aa80-06f1-11ea-9c75-62dd435e0b70.png)
And also creates new task window for output.
![image](https://user-images.githubusercontent.com/1947112/68860158-9bdc1c00-06f1-11ea-91f6-b997edaadf4e.png)

**Comment by DanTup** [comment] 2019-11-14 14:37
You can "run" the tests without debugging and still get the output to the Debug Console.

The test tasks you're showing are just running commands in the built-in terminal. There's no way for an extension to provide links for those since they can be any arbitrary task. In order to have links there, VS Code would need to support extensions being able to contribute rules for link detection (which as far as I am aware, it does not currently). I don't believe there's any way we can make package: URIs in the terminal be linked.

The best way would be to run the tests though the Dart debugger (you can "run" without debugging if you don't want them pausing). Not only would this allow for links in the output (in the Debug Console), you'll also see the tests in a tree (see https://dartcode.org/releases/v2-16/#dart-test-runner).

**Comment by audkar** [comment] 2019-11-14 15:15
Hmmm 3 points:

1. > I don't believe there's any way we can make package: URIs in the terminal be linked.

Not sure what magic these extensions does, but all links points to source files in these screenshots. It's is definitely possible unless VSCode has built-in linking for typescript only. Extension I am using is: `Jest`.

![Screenshot from 2019-11-14 16-53-06](https://user-images.githubusercontent.com/1947112/68868677-9e923d80-0700-11ea-86c6-5efd23fe1fba.png)

Top link points to test and bottom one to particular line which failed in test. Also if unexpected crash happens during test then printed out stacktrace is also clickable.

2. > The best way would be to run the tests though the Dart debugger

Debug console prints out colored output. But stacktraces of applications crashes is still not clickable. Maybe because it contains full package paths? like:
`package:mypackage/src/feature/location_picker/bloc/location_picker_bloc.dart 32:29`

3. > you'll also see the tests in a tree

Clicking on single test in `test tree` opens `Output`. Which contains nonclickable stack traces

**Comment by DanTup** [comment] 2019-11-14 15:32
> Not sure what magic these extensions does

Ah sorry, in your example above you said `package:` links, and the answer for that is slightly different.

Anything that starts with `package:` is not currently linkable - since VS Code doesn't know what a `package:` URI is, or how that relates to the content on disk. There's no API for us to tell it how to resolve them (some package URIs may be inside your workspace, and some may be elsewhere - for example in your pub cache).

For other links - in some places (like the debug console) VS Code is supposed to detect basic relative links itself. However for tasks, extensions can contribute a "problem matcher" which includes some regular expressions to extract paths too (main so errors/warnings can be extracted from tool output and mapped back to locations).

I'm not totally sure which of these is doing the links in your last screenshot - do those failures appear in the Problems window? If so, they're likely coming from a problem matcher. If not, then I'm not sure why that's linked there but a simple Dart path in the output is not - if you can give me an easy way to reproduce that sort of output, I can take a look.

> Debug console prints out colored output. But stacktraces of applications crashes is still not clickable. Maybe because it contains full package paths? like:
package:mypackage/src/feature/location_picker/bloc/location_picker_bloc.dart 32:29

Can you provide a screenshot? Filenames should now be slit from the stacks and shown on the right (see https://dartcode.org/releases/v2-22/#clickable-stack-trace-locations-).

> Clicking on single test in test tree opens Output. Which contains nonclickable stack traces

That's correct. The test output is streamed to the Debug Console while running (where they should be clickable), however we also capture all the output for each individual test so you can easily refer back to it later. Unfortunately that has to go into an output pane which we don't have the ability to link. If you're debugging a test I would recommend re-running it and using the debug console. The output view is not great, it was really just a convenience to see the output for a single test if you'd run the whole lot of tests.

**Comment by audkar** [comment] 2019-11-18 15:21
> If not, then I'm not sure why that's linked there but a simple Dart path in the output is not - if you can give me an easy way to reproduce that sort of output, I can take a look.

Simple example: https://github.com/audkar/jest-example . To reproduce that case I wrote steps in README file. Also you will need latest *Node* and *yarn/npm* installed.

**Comment by DanTup** [comment] 2019-11-18 17:30
Ok, so I did some testing and I also saw that Dart files were not linked, yet your example JS giles were... So I did some digging, and I found that the filenames are only linked in the terminal/task output *if there are no spaces in them*. And I don't just mean in what's visible, I mean *anywhere in the path*.

This is what I see when my project folder is named `dart-sample`:

<img width="477" alt="Screenshot 2019-11-18 at 5 24 39 pm" src="https://user-images.githubusercontent.com/1078012/69075014-779d7980-0a28-11ea-8ff6-7dbecd04b2d2.png">

Yet if my folder is named `dart sample`, even though the output still says `test/test.dart`, it does not become clickable.

I found an issue collecting issues like this in the VS Code tracker, so I added a comment here:

https://github.com/microsoft/vscode/issues/21125#issuecomment-555122017

So, if you ensure your paths don't have spaces, then running the tests using a task should result in links in the terminal. I would still recommend using the Run/Debug options/CodeLens links and the output in the Debug Console though, it provides more than just running in the terminal with a task.

**Comment by DanTup** [comment] 2019-11-18 17:34
Based on the above, I don't think there's anything to do in the extension here. There are three places you can get the test output:

- Output Pane - links here are entirely VS Code's domain
- Terminal Output - links here are also VS Code's domain - seems like this will sometimes work, but it's rather buggy
- Debug Console - we can inject links here, and they should work for stack traces that the extension recognises

I'd recommend using the last one - and we can probably fix any issues with link detection there. The others would need to be raised with VS Code (or they'd need to give us an API to handle these).

Let me know if this makes sense and I'll close this, or if you think there's something we can improve.

**Comment by audkar** [comment] 2019-11-18 18:54
Ok there there are many options but all of them have quite severe limits in one or another way... I will try to describe my workflow to showcase pain-points with current Dart testing on VSCode.

- I try to use mostly keyboard (with vim plugin)
- I use TDD for all my code. Write failing test first, execute it, see it failing with meaningful error message, write code implementation.
- I mostly used Emacs or Intellij products before. Switched to VS code only because of Dart. So I might not know all tricks with it. Please correct me if there are better ways :)))

Exact steps on different environments for comparisons

#### Spacemacs + Clojure *(watch tests toggle ON)(0 additional key presses)*:
1. Write test (Tests are executed while I am writing them. So I see state/errors without any additional manual steps)
1. Write implementation (Live results always visible)
![image](https://user-images.githubusercontent.com/1947112/69080820-56975180-0a45-11ea-81d8-59276eedf888.png)

#### Spacemacs + Clojure *(watch tests toggle OFF)(2 additional key presses)*:
1. Write test
1. Press keyboard shortcut *Run tests* (Tests results are shown and first error is focused automatically).
1. Press *Enter* navigates to failing test.
1. Write implementation
1. Press keyboard shortcut *Run tests*. See success or repeat steps 3-5(3 steps)
#### VSCode + Typescript + Jest plugin *(0 additional key presses)*:
1. Write test (Jest plugin runs tests in watch mode and . So I see state/errors without any additional manual steps)
1. Write implementation (Live results always visible)
![image](https://user-images.githubusercontent.com/1947112/69077814-251b8780-0a3f-11ea-9a27-adcb351b8436.png)
#### VSCode + Dart *(a lot of additional key presses)
1. Write test
1. Press shortcut for `Tasks: Rerun last task` (which was task for Dart task to execute Tests in single file)
1. Press shortcut for `Test: Focus on Dart & Flutter view` (`Tests` window is not focused after running tests)
1. Press navigation key 1-10s times to navigate to first failing test in `Test` window. (After tests execution tests in list is not expanded nor focused to first failing test.
1. Press *Enter* to see failing test result.
1. Write implementation 
1. Press shortcut for `Tasks: Rerun last task`. See success or repeat steps 3-7(a lot of steps)
------------
So problems:
- Dart doesn't have `tests --watch` mode which means that I can't run `All tests`. Have to tests single file. (This is Dart tooling problem not VSCode Dart plugin)
- After running tests `Tests` window is not focused
- All tests collapsed on initial run. Need a lot of key pressed to get to failing test
- Failing test is not focused
- Clicking test in `Tests` window opens `Output` which has uncolored/unclickable stacktraces
-----------
Could you suggest more optimal way code Dart on VSCode with TDD and keyboard?

**Comment by DanTup** [comment] 2019-11-19 07:53
Thanks for the info!

> See success or repeat steps 3-7(a lot of steps)

When you run tests, the output should appear in the Debug Console. If that's not automatically shown when you run, you can set the `"debug.openDebug": "openOnSessionStart"` setting to force it at the start of each session. However, I don't know if you can efficiently navigate the links in there with the keyboard (if not, I think there's a VS Code feature request there).

> Press shortcut for `Test: Focus on Dart & Flutter view` (`Tests` window is not focused after running tests)

There is an option called [`dart.openTestView`](https://dartcode.org/docs/settings/#dartopentestview) which defaults to `testRunStart` that has an option for `testFailure` that will show the tree and expand to reveal the first failure (it won't move focus to the tree, but if you can get there with one command/keypress that might still be an improvement).

If showing the Output window when selecting a tree node is more of an annoyance (eg. leaving the debug console visible would be better), we could make that optional. It was added so you can easily get at the history, but if your primary way of navigating tests is using the tree with the keyboard that might not be the best.

> Dart doesn't have `tests --watch` mode which means that I can't run `All tests`.

There is a command for `**Dart: Run All Tests** that will run them all. You can also run them all with a launch.json launch config where `program` is set to a folder (eg. `test` or `test/some_subset`). Then you could just run them with F5 (if the right launch config is selected).

There's an open issue about `watch` support in Dart (https://github.com/dart-lang/test/issues/1093) but it doesn't seem like it's something being worked on in the near-term.

Let me know if any of the above makes any of this easier, and if not we can try to come up with improvements.

**Comment by audkar** [comment] 2019-11-19 08:27
I failed to reproduce behavior which expands tests tree to first failed test. Steps:
- New flutter project `flutter create asdf`
- set `dart.openTestView testFailure`
- Run `All tests` first time when `Test` window is closed
- Run `All tests` when `Test` window is open

In both cases test tree is still collapsed
Result:
![dart-test-run](https://user-images.githubusercontent.com/1947112/69129505-2d170e00-0ab7-11ea-95b9-3f9c83dec7da.gif)

**Comment by DanTup** [comment] 2019-11-19 09:02
@audkar you're right, turns out this had bugs. I've fixed this and published a build here if you'd like to try it out:

https://github.com/Dart-Code/Dart-Code/releases/tag/v3.7.0-alpha.2

Grab the vsix file from there and run **Extension: Install from VSIX** then select it and click the Reload button. Let me know if this helps!

**Comment by maks** [comment] 2020-09-15 00:24
hi @DanTup I'm trying option #3 - running tests inside VSC using the "Dart: Run all tests" command palette entry  and the lookign a the output of a failed test in Debug console but I don't get the any linking to src of the lines in the stack trace inside the Debug Console as per screenshot below.
I've got [the commit that causes the error in my repo](https://github.com/maks/mknotes/commit/924a40cbe92ff1f46fa61a5204f43dd1b3077f76) if you wanted to try it out yourself.

![Screenshot 2020-09-15 at 10 20 16](https://user-images.githubusercontent.com/71999/93150849-9601fd80-f73d-11ea-88c6-3d14c29ce2c8.png)

**Comment by DanTup** [comment] 2020-09-15 08:40
@maks that seems like a different issue (this one here is tracking the Terminal, but that's the Debug Console). I've opened https://github.com/Dart-Code/Dart-Code/issues/2794 for it. Thanks!

**Closed** 2020-09-24 12:35 UTC
Labels: in editor, is enhancement
