### ISSUE TITLE
Code completion at the beginning of a word deletes the following word.

### ISSUE THREAD

**Issue by escamoteur** [Dart-Code/Dart-Code#1991] opened 2019-09-13 14:58 UTC
I guess this is closely related to https://github.com/Microsoft/vscode/issues/10266

But slightly different. My case is that if I insert a new word directly in front of another and select auto-complete the whole following word is deleted.
Maybe I'm the only one who has the problem but I regularly delete worde because I forget to add a space first.

This is especially annoying if you have moved a variaable to anotehr clas and now have to prefix everywhere the new class instance. When you use autocomplete for the instances name you delete the property name after it if you haven't included a space, that you have to delete again before you can type '.'

Also when you are inside a word and trigger autocomplete '.' as completion trigger doesn't work

**Comment by DanTup** [comment] 2019-09-16 09:56
> I guess this is closely related to microsoft/vscode#10266

I don't think so - that issue was about TypeScript doing bad things, and the Dart server generally does good things here :-)

> My case is that if I insert a new word directly in front of another and select auto-complete the whole following word is deleted.

This is intended (and what I'm asking for in the TS issue above). I do sometimes have the same issue as you and insert a space to avoid this, but having worked with TypeScript doing it the opposite way, I'm not sure having that default behaviour would be better. For example, if you typo a function:

```dart
someFuntcionCall(1);
```

To fix it, you can just put the cursor somewhere in there and hit Ctrl+Space, which brings up the completion:

<img width="454" alt="Screenshot 2019-09-16 at 10 50 54 am" src="https://user-images.githubusercontent.com/1078012/64948851-dfd8af00-d86f-11e9-8df6-d2b08e4bc813.png">

Selecting the right item will correctly replace the whole thing. Doing it "the TypeScript way" you'd end up with `someFunctionCallmeFuntcionCall` depending on where you put the cursor. I see this a lot in TS and it's quite infuriating as there's no quick way to select the bit to delete.

It's true that sometimes I'm trying to completion a function call before some other code (eg. wrap it around a variable), but I think that's less frequent than fixing simple typos. Most of the time, the completion includes the exact symbol name you want, so completing the whole thing is good.

> This is especially annoying if you have moved a variaable to anotehr clas and now have to prefix everywhere the new class instance. When you use autocomplete for the instances name you delete the property name after it if you haven't included a space, that you have to delete again before you can type '.'

Would typing the `.` first (instead of a space) work? I think in this situation I'd probably put `newProperty.` in the clipboard and paste it in front of them, so maybe I don't think I've seen this enough to know how annoying it is.

> Also when you are inside a word and trigger autocomplete '.' as completion trigger doesn't work

I can't repro this - pressing `.` in the middle of a word seems to open completion for me. If you can make a small repro, file a separate bug and I can look into it :-)

**Comment by escamoteur** [comment] 2019-09-16 11:32
I'm with you that the behavior that if you trigger autocomplete inside the word it should replace. But could we avoid that when standing at the first character of the next word?

**Comment by DanTup** [comment] 2019-09-16 13:55
> But could we avoid that when standing at the first character of the next word?

I'm not sure exactly what you mean - could you give an example?

**Comment by escamoteur** [comment] 2019-09-16 14:03
Sorry if I was unclear. I meant if the cursor is directly in front of the next word, could we in this case not delete the following word when triggering completion. Am 16.09.2019 15:55 schrieb Danny Tuppeny <notifications@github.com>:
But could we avoid that when standing at the first character of the next word?

I'm not sure exactly what you mean - could you give an example?

**Comment by DanTup** [comment] 2019-09-17 11:04
I'm not sure how you would make this distinction. For example, given this code:

```
myClass.myMethod();
```

If I want to change the `myMethod` call to `myOtherMethod()` because I selected the wrong one, I might put my cursor before the `m` in `myMethod` and invoke completion, expecting to select `myOtherMethod` and have it replace the text.

I think with the change you're suggesting, it would end up with `myClass.myOtherMethodmyMethod()`?

**Comment by escamoteur** [comment] 2019-09-17 11:09
Yes, that would be the consequence. But if I want to replace the whole word I type Ctrl+d and the word is selected. If I then do control space it would replace the word.

**Comment by DanTup** [comment] 2019-09-17 11:39
Right, so you'd prefer it to be dependant on whether you had a selection? I don't think we have the ability to do that (from the extension). We give the completion list to VS Code, and it's in charge of applying the edits. We can't change the edits dynamically/conditionally.

I think the only workaround would be to delete the selected text before invoking the completion.

**Comment by escamoteur** [comment] 2019-09-17 12:33
When I hit ctrl+d the cursor is then at the end of the word no longer at the beginning. How would it then replace the whole word?

**Comment by DanTup** [comment] 2019-11-11 17:01
VS Code now has support for both insert and replace completions and we'll adopt the new API in the next  version:

https://code.visualstudio.com/updates/v1_40#_support-intellisense-replace-mode

By default VS Code wants to do insert, but I personally think this is the less common case and since it differs from our current behaviour we may override `editor.suggest.overwriteOnAccept` for Dart to match the current behaviour (and you can press with `<shift>` to get insert mode).

**Comment by DanTup** [comment] 2019-11-19 10:55
This is essentially "fixed in VS Code, soon". I've added a setting that will ensure when the new VS Code API rolls out, the curent behaviour will be preserved (by default we'll overwrite). However if you hold `shift` then VS Code will truncate the insertion range to the current cursor location, preserving the characters after the cursor.

I don't know what the timeline is for that behaviour being finalised - it was dumped from the current version to give extensions time to override the default (as we are here) to prevent unexpected behaviour changes.

**Comment by DanTup** [comment] 2019-11-19 16:28
Turns out VS Code isn't going to do this automatically - we need to wait for the new API to ship, then set the option and also provide both insert and replace ranges.

**Closed** 2020-04-20 13:12 UTC
Labels: in editor, is enhancement

**Comment by DanTup** [comment] 2020-04-20 13:13
You can now control this behaviour by holding `<shift>` when completing. By default, we will replace (the original behaviour) but holding shift will insert. If you want to swap these around (so insert is the default), you should override the `editor.suggest.insertMode` setting for Dart (note: you'll need to specifically set it for Dart, or our override will win):

```
"[dart]": {
  "editor.suggest.insertMode": "insert"
}
```

**Comment by artoale** [comment] 2025-04-08 08:13
Sorry for resurrecting a very old issue...but would it be possible to actually respect the API and global configuration instead of requiring a language-specific override? It "looks" unnecessary and, more importantly, is quite hard to find.

**Comment by artoale** [comment] 2025-04-08 10:00
Ah! Appreciate that and thanks for the reply! 👍
