### ISSUE TITLE
Change Dart's SDK path from Command Pallette does not apply to built-in terminal

### ISSUE THREAD

**Issue by FaridAhamat** [Dart-Code/Dart-Code#2209] opened 2020-01-11 03:03 UTC
**VS Code version:**
Version: 1.41.1 (system setup)
Commit: 26076a4de974ead31f97692a0d32f90d735645c0
Date: 2019-12-18T14:58:56.166Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18362

Dart's extension version 3.7.1

I have added in settings.json:

    "dart.sdkPaths": [
        "C:\\Program Files\\Dart\\dart-sdk"
    ]

![2ZrZkfAogS](https://user-images.githubusercontent.com/11820522/72197938-03001d80-3462-11ea-9288-20aa640146ee.gif)

**Comment by DanTup** [comment] 2020-01-11 09:10
Unfortunately this is expectede behaviour. Changing the SDK only affects the SDK used for analysis and the commands built-in to VS Code. We cannot influence the built-in terminal. I've opened an issue in VS Code about this (https://github.com/microsoft/vscode/issues/46696) but until it's implemented you should avoid using the terminal if using an SDK that's not on `PATH`.

That said, there is a built-in command for **Flutter: Get Packages** that does the same thing as you're doing from the terminal, but *will* use the selected SDK. Also, if you save the `pubspec.yaml` file, it'll be run automatically.

**Comment by DanTup** [comment] 2020-06-11 15:07
VS Code shipped a feature to fix this, but it doesn't currently work on macOS. I've opened https://github.com/microsoft/vscode/issues/99878 (please add 👍 ) to see if it can be reviewed. I'd really like to support this, but I don't want to add it if it's going to br broken for a significant number of users and cause confusion/raised issues.

**Comment by DanTup** [comment] 2020-11-12 08:04
Dupe of #737.

**Closed by DanTup** 2020-11-12 08:04 UTC
Labels: blocked on vs code / lsp / dap, is enhancement
