### ISSUE TITLE
LSP crashes while editing one specific file on my Flutter project.

### ISSUE THREAD

**Issue by RVYA** [Dart-Code/Dart-Code#3226] opened 2021-03-23 18:40 UTC
**Describe the bug**
After updating to null-safe Flutter, a file named _decorations.dart_ on my file hiearchy shows errors, crashes LSP and does not respond to modifications to the file (errors are still indicated even after modifying/fixing them.). LSP keeps producing error messages after every keystroke and mouse movement.

**To Reproduce**
1. Generate a file named _decorations.dart_. (On my project, file path is as following: `lib/values/decorations.dart`)
2. Write some code which violates null-safety.
3. Try to modify file.

**Expected behavior**
I expect the editor and LSP to behave same way as when I modify any other file.

**Flutter Doctor Log**
```
[√] Flutter (Channel stable, 2.0.2, on Microsoft Windows [Version 10.0.18363.1441], locale tr-TR)
[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[√] Chrome - develop for the web
[√] Android Studio (version 3.5)
[√] IntelliJ IDEA Community Edition (version 2018.3)
[√] VS Code, 64-bit edition (version 1.54.2)
[√] Connected device (2 available)
```

---

**Note**
I get a seperate report from LSP for every action performed while modifying the file; here is a few examples:

```
[Error - 21:22:13] Request textDocument/hover failed.
  Message: Invalid file path
  Code: -32003 
...\lib\values\decorations.dart
[Error - 21:22:13] Request textDocument/codeAction failed.
  Message: Invalid file path
  Code: -32003 
...\lib\values\decorations.dart
[Error - 21:22:14] Request textDocument/documentHighlight failed.
  Message: Invalid file path
  Code: -32003 
...\lib\values\decorations.dart
[Error - 21:22:14] Request textDocument/codeAction failed.
  Message: Invalid file path
  Code: -32003 
...\lib\values\decorations.dart
[Error - 21:22:14] Request textDocument/hover failed.
  Message: Invalid file path
  Code: -32003 
...\lib\values\decorations.dart
[Error - 21:32:58] Request textDocument/hover failed.
  Message: Invalid file path
  Code: -32003 
...\lib\values\decorations.dart
[Error - 21:32:59] Request textDocument/hover failed.
  Message: Invalid file path
  Code: -32003 
...\lib\values\decorations.dart
[Error - 21:32:59] Request textDocument/hover failed.
  Message: Invalid file path
  Code: -32003 
...\lib\values\decorations.dart
[Error - 21:32:59] Request textDocument/codeAction failed.
  Message: Invalid file path
  Code: -32003 
...\lib\values\decorations.dart
```

**Comment by DanTup** [comment] 2021-03-23 18:42
Are you able to share the contents of the file that's triggering the error?

**Comment by RVYA** [comment] 2021-03-23 18:46
Sure, it is an constants file for some decorations I use in my project.
```dart
import 'package:flutter/material.dart';

import '../widgets/custom_borders/outlined_gradient_border.dart';
import 'colours.dart';
import 'text_styles.dart';


const Radius
  kMaterialSmallComponentRadii = const Radius.circular(4.0),  //dp
  kMaterialLargeComponentRadii = const Radius.circular(24.0); //dp


InputDecoration kGetInputDecorationFor({
  Brightness brightness = Brightness.light,
  required String labelText,
}) {
  final OutlinedGradientInputBorder
      fadingBorder = OutlinedGradientInputBorder(
                      gradient: (brightness == Brightness.light)? kBlackFade : kWhiteFade,
                      gapPadding: 5.0,
                      radii: const BorderRadius.all(Radius.circular(50.0)),
                      width: 2.0,
                     );

  final TextStyle
      inputStyle = kGetBodyStyleFor(brightness: brightness),
      labelStyle = inputStyle.copyWith(
                    color: inputStyle.color!.withOpacity(0.6),
                   );


  return
    InputDecoration(
      enabledBorder: fadingBorder,
      focusedBorder: fadingBorder,
      isDense: true,
      labelText: labelText,
      labelStyle: labelStyle,
    );
}

BoxDecoration kGetBoxDecorationFor({
  Brightness brightness = Brightness.light,
  BoxShape shape = BoxShape.rectangle,
  bool isFilled = true,
}) {
  final BorderRadiusGeometry borderRadius = (shape == BoxShape.rectangle)?
      const BorderRadius.all(kMaterialLargeComponentRadii)
      : null;

  BoxBorder? border;
  Color? color;
  if (isFilled) {
    border = null;
    color = (brightness == Brightness.light)? kPrimary : kBackground;
  } else {
    color = null;
    border = Border.all(color: Colors.white); // TODO: Implement GradientBoxBorder.
  }


  return BoxDecoration(
    borderRadius: borderRadius,
    border: border,
    color: color,
    shape: shape,
  );
}
```

I have recently updated the SDK and I was updating syntax to apply sound null-safety to my files. In this file, against any modifications I make, errors stay where they are and LSP keeps throwing crash logs.

**Comment by DanTup** [comment] 2021-03-23 18:48
Doesn't seem like there's anything wrong with the syntax of the file - are you able to make a copy of your project and trim it down to something you can share that still triggers the error?

**Comment by RVYA** [comment] 2021-03-23 18:49
Actually, I think I understand the issue, this happens with 2 other files on my project that I noticed now. I think it is about the name of the files; name of the other 2 files that are affected by this are `fading_elevated_button.dart` and `fading_outlined_button.dart`. Names of these files, and the file specified before _(`decorations.dart`)_ are similiar/same as the ones used in Flutter SDK. I believe this confuses the LSP.

**Comment by RVYA** [comment] 2021-03-23 18:50
Oh, I need to make a few tests to see how can I trim down a project that will prove the error, it is under constant development right now. Give me a few minutes, I must try reproducing in a new project; this will make things easier for you.

**Comment by RVYA** [comment] 2021-03-23 19:03
I could not reproduce the issue in a new project... What details from the relevant project would help you to understand the issue?

**Comment by RVYA** [comment] 2021-03-23 19:37
I tried a few things while waiting, and I am not able to understand why is this issue arising...
1- I toggled `dart.previewLsp` flag to false, navigated to the mentioned files; none of them have highlighted when hovered mouse over, _Go to source_ did not work, parameters for constructors did not show using InteliSense. (_Control+Space_) It is almost like this file is being ignored.
2- While LSP is disabled, I tried deleting and regenerating the file and renaming it. Neither of them changed the outcome. The file with the same content is not triggering IDE/anaylzer/plugin features.
3- I enabled the LSP again and tried the same thing again (_regenerating and renaming_), crashes were there again. Also, it shows same issues in the mark 2.

What may be the issue, do you have any insights? Corrupted project? _Cursed files_? :D

**Comment by DanTup** [comment] 2021-03-23 19:52
> I toggled `dart.previewLsp` flag to false, navigated to the mentioned files; none of them have highlighted 

I'm not surprised that things don't work with LSP disabled, as this issue seems to me like a parsing/resolution issue, which is preventing most language features from working. It's more obvious something is wrong with LSP as the LSP client makes it really obvious when a request fails with an error.

> What details from the relevant project would help you to understand the issue?

The simplest thing would be a complete repro, then I could attach a debugger or add more logging. If you make a _copy_ of your project does it still occur there? If so, could you then trim it down, deleting as much as possible until you have something you could share?

(I don't think it's related, but there was an issue with similar consequences yesterday at https://github.com/Dart-Code/Dart-Code/issues/3222 - I don't suppose you've used `implements` on a `mixin`?)

**Comment by RVYA** [comment] 2021-03-24 18:51
Thank you for your time; I will return to you with results as soon as possible.

**Comment by RVYA** [comment] 2021-03-25 18:39
@DanTup Sorry for the delay; the problem indeed persists, in a copy of the relevant project, too. I stripped down my project to files that are relevant to the issue, and linked files in case you would like to run it with a widget. How could I send it to you?

Also; no, I did not implemented any `mixin` in my project, yet.

**Comment by DanTup** [comment] 2021-03-25 18:45
@RVYA you can send me emails to logs@dartcode.org (I think they have a 25MB limit - it's Gmail), or send a GDrive link or similar. Thanks!

**Comment by RVYA** [comment] 2021-03-25 19:01
I have sent you the project via e-mail. When you understand the source of the issue, please let me know too; I am curious.

**Comment by DanTup** [comment] 2021-03-29 10:13
Thanks! I can reproduce this - it's definitely failing to parse something in that code. I'll try narrow it down and file an SDK issue with a small repro. Thanks!

**Comment by DanTup** [comment] 2021-03-29 10:36
I was able to reduce this to a small amount of code in https://github.com/dart-lang/sdk/issues/45504. I think it _might_ be related to having both private and public variables in the same definition:

```dart
const kOne = 1, _kTwo = 2;
```

Renaming `_kTwo` to just `kTwo` or putting it in its own declaration seemed to prevent the issue, so that might be a reasonable workaround for you for now until the issue is fixed.

I'll close this issue as once it's fixed in the SDK (and you have an updated SDK) there will be nothing to do in the VS Code extension. Thanks!

**Closed** 2021-03-29 10:37 UTC
Labels: upstream in dart / flutter
