### ISSUE TITLE
Can not open file from debug console 

### ISSUE THREAD

**Issue by jtdLab** [Dart-Code/Dart-Code#4744] opened 2023-09-14 20:09 UTC
**Describe the bug**
When having a runtime error occurring in some file and clicking on the link to the file where the error occurred inside debug console the file is not found and thus not opened.

<img width="1027" alt="Bildschirmfoto 2023-09-14 um 22 06 42" src="https://github.com/Dart-Code/Dart-Code/assets/72231111/1243fd8a-734c-4abc-938f-16ee60537887">

**Comment by DanTup** [comment] 2023-09-18 14:15
This seems like a dupe of https://github.com/Dart-Code/Dart-Code/issues/4573 which has been fixed but not before the last stable SDK branch. The fix should be included in the next SDK release (and is likely already included in the current beta releases).

**Closed** 2023-09-18 14:15 UTC
Labels: duplicate
