### ISSUE TITLE
broken Suggestions and weird useless suggestions

### ISSUE THREAD

**Issue by fisforfaheem** [Dart-Code/Dart-Code#3153] opened 2021-02-21 09:50 UTC
Please the following examples:
![Screen Shot 2021-02-19 at 8 31 00 PM](https://user-images.githubusercontent.com/35878088/108621371-1991ea00-7454-11eb-91c0-610891f73914.png)
![Screen Shot 2021-02-19 at 7 18 27 PM](https://user-images.githubusercontent.com/35878088/108621377-1e569e00-7454-11eb-85d3-15f47668f58a.png)
![Screen Shot 2021-02-19 at 7 13 27 PM](https://user-images.githubusercontent.com/35878088/108621378-1eef3480-7454-11eb-97b9-3e403a03af40.png)

**Comment by DanTup** [comment] 2021-02-22 11:15
Thanks for the report!

In the first screenshot, because there is a "prefix" typed ("red"), VS Code is doing the ranking there so unfortunately we can't affect the sort (see https://github.com/microsoft/vscode/blob/3781f94ba41041d4d61354a8e08f699849569765/src/vs/vscode.d.ts#L3886-L3891 and https://github.com/microsoft/vscode/issues/105999).

If the item you're looking for (I presume `Colors.Red`) is _missing_ from the list (rather than just further down), then that probably is a bug.

The second/third screenshots I think are also ranking issues, and there's an existing issue open at https://github.com/dart-lang/sdk/issues/38739 covering this (the ranking is done by the language server), so I'll close this as a dupe of that.

Thanks!

**Closed** 2021-02-22 11:15 UTC
Labels: upstream in dart / flutter

**Comment by fisforfaheem** [comment] 2021-02-27 20:23
Thanks, But please let me know when this issue will be resolved as it's very difficult  to use the flutter without proper sugegstions

**Comment by DanTup** [comment] 2021-03-01 09:50
@fisforfaheem can you be more specific? There were multiple issues described above.

If the issue is VS Code re-ranking things, then that can't be fixed - that's a decision made by VS Code.

If the issue is just that the default ranking (when you have not typed a prefix) is bad, then you can follow the SDK issue linked above for updates, as that issue will be closed once resolved. I don't have any timeline for that, it would likely be done by someone on the analyzer team.

I appreciate it's frustrating when the ranking is bad though, and it's definitely something the analyzer team are aware of. Thanks!

**Comment by fisforfaheem** [comment] 2021-03-01 10:58
Thanks :) hopefully it would be addressed in flutter 2.0 also looking
forward  for dartcode to speed up and improve
