### ISSUE TITLE
Let wrap/move widget helpers be key binding assignable

### ISSUE THREAD

**Issue by xster** [Dart-Code/Dart-Code#367] opened 2017-07-17 20:44 UTC
The light bulb editing helpers are super awesome. Would be great to let those commands show in the command palette and assignable to key bindings.

**Comment by DanTup** [comment] 2017-07-21 10:58
I'm not sure I'll be able to do this very well... With some (eg. refactorings like `CONVERT_GETTER_TO_METHOD`) there's a defined list in the spec which I could use to add to the command palette. Others I only know about when the analyzer serves them up (eg. `Wrap in new widget`).

It's possible I could register them on-the-fly, but not being able to list them in `packages.json` means I can't assign nice names to them.

When I find some time, I'll have a look though. (I presume you already know there's a keybinding to open the lightbulb menu (`Ctrl+.` on Windows) and wanted the specific entries?)

**Comment by xster** [comment] 2017-07-21 15:40
Ha, I did not (know the ctrl+. hotkey). That's good enough for me for now :)

**Comment by DanTup** [comment] 2018-02-21 14:48
Considering this a dupe of #561. Once that's all done, you'll be able to make keybindings for individual (or groups) of quickfixes. Subscribe there for updates!

**Closed by DanTup** 2018-02-21 14:48 UTC
Labels: in editor, is enhancement

**Comment by DanTup** [comment] 2018-03-06 10:10
#561 will ship in vNext so you can bind specific refactors to their own keys (or subsets of them based on their groupings). So if you want a key that always does "Wrap in Center" for ex, you will be able to. It will require an SDK that provides IDs for the assists though (Flutter beta surely will, but older non-Flutter Dart SDKs may not).

**Comment by xster** [comment] 2018-03-06 22:02
Cool, neat
