### ISSUE TITLE
On Const widgets inellisense is broken

### ISSUE THREAD

**Issue by petrnymsa** [Dart-Code/Dart-Code#5295] opened 2024-10-01 11:53 UTC
**Describe the bug**
When editing `const` widgets Intellisense doesn't popup at all or isn't working as expected. It seems that it will not offer completion for non-const results.

**To Reproduce**
```
// EDIT this code
const  SizedBox(height: 16)

// into for example 

 SizedBox(height: MediaQuery.of(context).size.height)
```

**Expected behavior**
Intellisense should work even when resulting code could not be const.

**Screenshots**
![Oct-01-2024 13-42-44](https://github.com/user-attachments/assets/edb52556-7e0b-4b2f-bd16-4f531ff542a0)

**Please complete the following information:**

You can run the **Dart: Collect Diagnostic Information** command from the VS Code command palette (`F1`) to easily capture this information or provide it manually.

<details>
<summary>Details</summary>

Workspace Environment

Dart Code extension: 3.96.0  
Flutter extension: 3.96.0 (activated)  

App: Visual Studio Code  
App Host: desktop  
Version: mac 1.93.1  

Workspace type: Dart, Flutter (LSP)  
Workspace name: [REDACTED]  

Dart (3.5.1): /Users/petrnymsa/fvm/versions/3.24.1/bin/cache/dart-sdk  
Flutter (3.24.1): /Users/petrnymsa/fvm/versions/3.24.1 (Petr - iPhone (ios/ios))

Output from 'dart info'

/Users/petrnymsa/fvm/versions/3.24.1/bin/cache/dart-sdk/bin/dart info

If providing this information as part of reporting a bug, please review the information below to ensure it only contains things you're comfortable posting publicly.

General info:  

- Dart 3.5.1 (stable) (Tue Aug 13 21:02:17 2024 +0000) on "macos_arm64"  
- on macos / Version 14.6.1 (Build 23G93)  
- locale is en-CZ

Project info:  

- sdk constraint: '^3.5.0'  
- dependencies:  
- dev_dependencies: lints, melos

Process info:  

Memory: 13 MB, CPU: 0.0%, Elapsed time: 01-04:54:16  
Command line: dart devtools --machine --allow-embedding --dtd-uri ws:<path>/2yMUdmR2PbkcajdJ

Memory: 8 MB, CPU: 0.0%, Elapsed time: 23:13:42  
Command line: dart devtools --machine --allow-embedding --dtd-uri ws:<path>/x6X1ylp3ckt1x7GZ

Memory: 12 MB, CPU: 0.0%, Elapsed time: 23:13:43  
Command line: dart language-server --protocol=lsp --client-id=VS-Code --client-version=3.96.0

Memory: 182 MB, CPU: 0.0%, Elapsed time: 01-04:54:18  
Command line: dart language-server --protocol=lsp --client-id=VS-Code --client-version=3.96.0

Memory: 7 MB, CPU: 0.0%, Elapsed time: 23:13:43  
Command line: dart tooling-daemon --machine  

Memory: 10 MB, CPU: 0.0%, Elapsed time: 01-04:54:18  
Command line: dart tooling-daemon --machine  

Memory: 32 MB, CPU: 0.0%, Elapsed time: 01-04:54:18  
Command line: flutter_tools.snapshot daemon  

Memory: 19 MB, CPU: 0.0%, Elapsed time: 58:12  
Command line: flutter_tools.snapshot debug_adapter  

Memory: 71 MB, CPU: 0.4%, Elapsed time: 58:02  
Command line: flutter_tools.snapshot debug_adapter  

Memory: 63 MB, CPU: 0.3%, Elapsed time: 57:53  
Command line: flutter_tools.snapshot debug_adapter  

Memory: 26 MB, CPU: 0.0%, Elapsed time: 58:11  
Command line: flutter_tools.snapshot run --machine --start-paused -d 67a7263a0305 --devtools-server-address http:<path>/ --target <path>/main_dev.dart --flavor dev  

Memory: 152 MB, CPU: 0.9%, Elapsed time: 57:52  
Command line: flutter_tools.snapshot run --machine --start-paused -d 7a43e6f2cc9dd329b31356945aceb63c9594c939 --devtools-server-address http:<path>/ --target <path>/main_dev.dart --flavor dev  

Memory: 100 MB, CPU: 0.9%, Elapsed time: 58:02  
Command line: flutter_tools.snapshot run --machine --start-paused -d emulator-5554 --devtools-server-address http:<path>/ --target <path>/main_dev.dart --flavor dev

Output from 'flutter doctor'

/Users/petrnymsa/fvm/versions/3.24.1/bin/flutter doctor -v

[!] Flutter (Channel stable, 3.24.1, on macOS 14.6.1 23G93 darwin-arm64, locale en-CZ)  
- Flutter version 3.24.1 on channel stable at /Users/petrnymsa/fvm/versions/3.24.1  
- Warning: `flutter` on your path resolves to /Users/petrnymsa/fvm/versions/3.24.0/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/petrnymsa/fvm/versions/3.24.1. Consider adding /Users/petrnymsa/fvm/versions/3.24.1/bin to the front of your path.  
- Warning: `dart` on your path resolves to /Users/petrnymsa/fvm/versions/3.24.0/bin/dart, which is not inside your current Flutter SDK checkout at /Users/petrnymsa/fvm/versions/3.24.1. Consider adding /Users/petrnymsa/fvm/versions/3.24.1/bin to the front of your path.  
- Upstream repository https://github.com/flutter/flutter.git  
- Framework revision 5874a72aa4 (6 weeks ago), 2024-08-20 16:46:00 -0500  
- Engine revision c9b9d5780d  
- Dart version 3.5.1  
- DevTools version 2.37.2  
- If those were intentional, you can disregard the above warnings; however, it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)  
- Android SDK at /Users/petrnymsa/Library/Android/sdk  
- Platform android-34, build-tools 34.0.0  
- ANDROID_HOME = /Users/petrnymsa/Library/Android/sdk  
- Java binary at: /Users/petrnymsa/Applications/Android Studio Jellyfish 2023.3.1 Patch 2.app/Contents/jbr/Contents/Home/bin/java  
- Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11572160)  
- All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.0)  
- Xcode at /Applications/Xcode.app/Contents/Developer  
- Build 16A242d  
- CocoaPods version 1.15.2

[✓] Chrome - develop for the web  
- Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.3)  
- Android Studio at /Users/petrnymsa/Applications/Android Studio Jellyfish 2023.3.

</details>

**Comment by incendial** [comment] 2024-10-01 12:03
I'll just leave it here: https://github.com/dart-lang/sdk/issues/54987 😁

**Comment by DanTup** [comment] 2024-10-01 17:25
Thanks - it does seem that this is a dupe of https://github.com/dart-lang/sdk/issues/54987.

I'll close this one, since any changes need to be in the SDK and it's better to keep discussion in one place. Thanks!

**Closed by DanTup** 2024-10-01 17:25 UTC
Labels: is bug
