### ISSUE TITLE
Async execution freezes after hitting a breakpoint

### ISSUE THREAD

**Issue by szotp** [Dart-Code/Dart-Code#1801] opened 2019-06-16 04:41 UTC
After reaching a breakpoint, it looks like async execution stops working, where regular execution still works. It's easier to explain on example.

1. Run code attached below.
1. Add the breakpoint in build method.
1. Reach the breakpoint and press continue.
1. If this worked fine, after continuing you would reach the breakpoint again, and again... but it doesn't, it just stops.
1. Remove the breakpoint - counter starts again.
1. Add breakpoint again and continue when it's reached.
1. Press Increment button - you should reach the breakpoint again, but only once.
1. Press Increment with delay button - you will not reach the breakpoint because it contains await inside.
1. Try to hot restart - you will reach the breakpoint again and then hot restart will not finish.

Additional notes:
1. Android Studio does not have this problem.
1. The breakpoint must be inside build method, breakpoint inside increment method works ok.
1. It kinda looks like app is paused on breakpoint but VSCode does not show it. That's why removing it fixes the problem.
1. Maybe it would be good idea to detach breakpoints during hot restart and attach them again after it's finished. Reaching a breakpoint during hot restart seems to break it completely and require cold restart.
```dart
import 'package:flutter/material.dart';

Future<void> main() async {
  runApp(MyApp());
}

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  var _counter = 0;

  @override
  void initState() {
    super.initState();
    update();
  }

  void update() {
    increment();
    Future.delayed(Duration(milliseconds: 100)).then((_) => update());
  }

  void increment() {
    setState(() {
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    // add breakpoint here
    return MaterialApp(
      home: Container(
        color: Colors.white,
        alignment: Alignment.center,
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.center,
          mainAxisSize: MainAxisSize.min,
          children: <Widget>[
            Text(_counter.toString()),
            FlatButton(
              child: Text('Increment'),
              onPressed: increment,
            )
          ],
        ),
      ),
    );
  }
}
```

flutter doctor
```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel master, v1.5.4-pre.17, on Microsoft Windows [Version 10.0.17763.557], locale pl-PL)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[√] Android Studio (version 3.3)
[√] VS Code (version 1.35.1)
[√] Connected device (2 available)
```

**Comment by DanTup** [comment] 2019-06-17 10:47
@bkonyi I can repro this, but it doesn't seem like a VS Code issue. If I put a breakpoint on the first line of the build method and then run, it hits it. If I click resume, it hits the breakpoint again (and I see the count increase). If I press resume again, it increments and hits the breakpoint again. Then I click resume again, but nothing... It doesn't comeback and hit the breakpoint, and the app is not counting up (nor are there any frame events).

Seems like the last Resume didn't work. What's weird is if I remove the breakpoint and re-add it, it suddenly bursts back into life.

```
// Hit breakpoint
[11:41:57] <== {"jsonrpc":"2.0","method":"streamNotify","params":{"streamId":"Debug","event":{"type":"Event","kind":"PauseBreakpoint","isolate":{"type":"@Isolate","id":"isolates\/58989095","name":"main","number":"58989095"},"timestamp":1560768117061,"pauseBreakpoints":[{"type":"Breakpoint","fixedId":true,"id":"breakpoints\/1","breakpointNumber":1,"resolved":true,"location":{"type":"SourceLocation","script":{"type":"@Script","fixedId":true,"id":"libraries\/@42473383\/scripts\/package%3Arrrrrrr%2Fmain.dart\/16b65073cc2","uri":"package:rrrrrrr\/main.dart","_kind":"kernel"},"tokenPos":596}}],"topFrame":{"type":"Frame","kind":"Regular","location":{"type":"SourceLocation","script":{"type":"@Script","fixedId":true,"id":"libraries\/@42473383\/scripts\/package%3Arrrrrrr%2Fmain.dart\/16b65073cc2","uri":"package:rrrrrrr\/main.dart","_kind":"kernel"},"tokenPos":596},"function":{"type":"@Function","fixedId":true,"id":"classes\/1276\/functions\/build","name":"build","owner":{"type":"@Class","fixedId":true,"id":"classes\/1276","name":"_MyAppState","_vmName":"_MyAppState@42473383"},"_kind":"RegularFunction","static":false,"const":false,"_intrinsic":false,"_native":false},"code":{"type":"@Code","fixedId":true,"id":"code\/24a14c199-11e5f9080","name":"[Unoptimized] _MyAppState.build","_vmName":"[Unoptimized] build","kind":"Dart","_optimized":false,"_intrinsic":false,"_native":false},"vars":[{"type":"BoundVariable","name":"this","value":{"type":"@Instance","class":{"type":"@Class","fixedId":true,"id":"classes\/1276","name":"_MyAppState","_vmName":"_MyAppState@42473383"},"kind":"PlainInstance","id":"objects\/280"},"declarationTokenPos":-1,"scopeStartTokenPos":-1,"scopeEndTokenPos":1046},{"type":"BoundVariable","name":"context","value":{"type":"@Instance","class":{"type":"@Class","fixedId":true,"id":"classes\/3229","name":"StatefulElement"},"kind":"PlainInstance","id":"objects\/281"},"declarationTokenPos":547,"scopeStartTokenPos":547,"scopeEndTokenPos":1046}],"index":0}}}}
[11:41:57] ==> {"id":"470","method":"getStack","params":{"isolateId":"isolates/58989095"}}
[11:41:57] <== {"jsonrpc":"2.0", "result":{"type":"Stack","frames":[{"type":"Frame","kind":"Regular","location":{"type":"SourceLocation","script":{"type":"@Script","fixedId":true,"id":"libraries\/@42473383\/scripts\/package%3Arrrrrrr%2Fmain.dart\/16b65073cc2","uri":"package:rrrrrrr\/main.dart","_kind":"kernel"},"tokenPos":596},"function":{"type":"@Function","fixedId":true,"id":"classes\/1276\/functions\/build","name":"build","owner":{"type":"@Class","fixedId":true,"id":"classes\/1276","name":"_MyAppState","_vmName":"_MyAppState@42473383"},"_kind":"RegularFunction","static":false,"const":false,"_intrinsic":false,"_native":false},"code":{"type":"@Code","fixedId":true,"id":"code\/24a14c199-11e5f9080","name":"[Unoptimized] _MyAppState.build","_vmName":"[Unoptimized] build","kind":"Dart","_optimized":false,"_intrinsic":false,"_native":false},"vars":[{"type":"BoundVariable","name":"this","value":{"type":"@Instance","class":{"type":"@Class","fixedId":true,"id":"classes\/1276","name":"_MyAppState","_vmName":"_MyAppState@42473383"},"kind":"PlainInstance","id":"objects\/282"},"declarationTokenPos":-1,"scopeStartTokenPos":-1,"scopeEndTokenPos":1046},{"type":"BoundVariable","name":"context","value":{"type":"@Instance","class":{"type":"@Class","fixedId":true,"id":"classes\/3229","name":"StatefulElement"},"kind":"PlainInstance","id":"objects\/283"},"declarationTokenPos":547,"scopeStartTokenPos":547,"scopeEndTokenPos":1046}],"index":0},{"type":"Frame","kind":"Regular","location":{"type":"SourceLocation","script":{"type":"@Script","fixedId":true,"id":"libraries\/@44042623\/scripts\/package%3Aflutter%2Fsrc%2Fwidgets%2Fframework.dart\/16b65073d3d","uri":"package:flutter\/src\/widgets\/framework.dart","_kind":"kernel"},"tokenPos":166988},"function":{"type":"@Function","fixedId":true,"id":"classes\/3229\/functions\/build","name":"build","owner":{"type":"@Class","fixedId":true,"id":"classes\/3229","name":"StatefulElement"},"_kind":"RegularFunction","static":false,"const":false,"_intrinsic":false,"…
[11:41:57] ==> {"id":"471","method":"getStack","params":{"isolateId":"isolates/58989095"}}
[11:41:57] <== {"jsonrpc":"2.0", "result":{"type":"Stack","frames":[{"type":"Frame","kind":"Regular","location":{"type":"SourceLocation","script":{"type":"@Script","fixedId":true,"id":"libraries\/@42473383\/scripts\/package%3Arrrrrrr%2Fmain.dart\/16b65073cc2","uri":"package:rrrrrrr\/main.dart","_kind":"kernel"},"tokenPos":596},"function":{"type":"@Function","fixedId":true,"id":"classes\/1276\/functions\/build","name":"build","owner":{"type":"@Class","fixedId":true,"id":"classes\/1276","name":"_MyAppState","_vmName":"_MyAppState@42473383"},"_kind":"RegularFunction","static":false,"const":false,"_intrinsic":false,"_native":false},"code":{"type":"@Code","fixedId":true,"id":"code\/24a14c199-11e5f9080","name":"[Unoptimized] _MyAppState.build","_vmName":"[Unoptimized] build","kind":"Dart","_optimized":false,"_intrinsic":false,"_native":false},"vars":[{"type":"BoundVariable","name":"this","value":{"type":"@Instance","class":{"type":"@Class","fixedId":true,"id":"classes\/1276","name":"_MyAppState","_vmName":"_MyAppState@42473383"},"kind":"PlainInstance","id":"objects\/342"},"declarationTokenPos":-1,"scopeStartTokenPos":-1,"scopeEndTokenPos":1046},{"type":"BoundVariable","name":"context","value":{"type":"@Instance","class":{"type":"@Class","fixedId":true,"id":"classes\/3229","name":"StatefulElement"},"kind":"PlainInstance","id":"objects\/343"},"declarationTokenPos":547,"scopeStartTokenPos":547,"scopeEndTokenPos":1046}],"index":0},{"type":"Frame","kind":"Regular","location":{"type":"SourceLocation","script":{"type":"@Script","fixedId":true,"id":"libraries\/@44042623\/scripts\/package%3Aflutter%2Fsrc%2Fwidgets%2Fframework.dart\/16b65073d3d","uri":"package:flutter\/src\/widgets\/framework.dart","_kind":"kernel"},"tokenPos":166988},"function":{"type":"@Function","fixedId":true,"id":"classes\/3229\/functions\/build","name":"build","owner":{"type":"@Class","fixedId":true,"id":"classes\/3229","name":"StatefulElement"},"_kind":"RegularFunction","static":false,"const":false,"_intrinsic":false,"…

// Resume
[11:42:03] ==> {"id":"477","method":"resume","params":{"isolateId":"isolates/58989095"}}
[11:42:03] <== {"jsonrpc":"2.0", "result":{"type":"Success"},"id":"477"}
[11:42:03] <== {"jsonrpc":"2.0","method":"streamNotify","params":{"streamId":"Debug","event":{"type":"Event","kind":"Resume","isolate":{"type":"@Isolate","id":"isolates\/58989095","name":"main","number":"58989095"},"timestamp":1560768123615,"topFrame":{"type":"Frame","kind":"Regular","location":{"type":"SourceLocation","script":{"type":"@Script","fixedId":true,"id":"libraries\/@42473383\/scripts\/package%3Arrrrrrr%2Fmain.dart\/16b65073cc2","uri":"package:rrrrrrr\/main.dart","_kind":"kernel"},"tokenPos":596},"function":{"type":"@Function","fixedId":true,"id":"classes\/1276\/functions\/build","name":"build","owner":{"type":"@Class","fixedId":true,"id":"classes\/1276","name":"_MyAppState","_vmName":"_MyAppState@42473383"},"_kind":"RegularFunction","static":false,"const":false,"_intrinsic":false,"_native":false},"code":{"type":"@Code","fixedId":true,"id":"code\/24a14c199-11e5f9080","name":"[Unoptimized] _MyAppState.build","_vmName":"[Unoptimized] build","kind":"Dart","_optimized":false,"_intrinsic":false,"_native":false},"vars":[{"type":"BoundVariable","name":"this","value":{"type":"@Instance","class":{"type":"@Class","fixedId":true,"id":"classes\/1276","name":"_MyAppState","_vmName":"_MyAppState@42473383"},"kind":"PlainInstance","id":"objects\/402"},"declarationTokenPos":-1,"scopeStartTokenPos":-1,"scopeEndTokenPos":1046},{"type":"BoundVariable","name":"context","value":{"type":"@Instance","class":{"type":"@Class","fixedId":true,"id":"classes\/3229","name":"StatefulElement"},"kind":"PlainInstance","id":"objects\/403"},"declarationTokenPos":547,"scopeStartTokenPos":547,"scopeEndTokenPos":1046}],"index":0}}}}
[11:42:03] <== {"jsonrpc":"2.0","method":"streamNotify","params":{"streamId":"Extension","event":{"type":"Event","kind":"Extension","extensionKind":"Flutter.FirstFrame","isolate":{"type":"@Isolate","id":"isolates\/58989095","name":"main","number":"58989095"},"timestamp":1560768123751,"extensionData":{}}}}
[11:42:03] <== {"jsonrpc":"2.0","method":"streamNotify","params":{"streamId":"Extension","event":{"type":"Event","kind":"Extension","extensionKind":"Flutter.Frame","isolate":{"type":"@Isolate","id":"isolates\/58989095","name":"main","number":"58989095"},"timestamp":1560768123753,"extensionData":{"number":1,"startTime":0,"elapsed":6693083}}}}

// Hit breakpoint
[11:42:03] <== {"jsonrpc":"2.0","method":"streamNotify","params":{"streamId":"Debug","event":{"type":"Event","kind":"PauseBreakpoint","isolate":{"type":"@Isolate","id":"isolates\/58989095","name":"main","number":"58989095"},"timestamp":1560768123800,"pauseBreakpoints":[{"type":"Breakpoint","fixedId":true,"id":"breakpoints\/1","breakpointNumber":1,"resolved":true,"location":{"type":"SourceLocation","script":{"type":"@Script","fixedId":true,"id":"libraries\/@42473383\/scripts\/package%3Arrrrrrr%2Fmain.dart\/16b65073cc2","uri":"package:rrrrrrr\/main.dart","_kind":"kernel"},"tokenPos":596}}],"topFrame":{"type":"Frame","kind":"Regular","location":{"type":"SourceLocation","script":{"type":"@Script","fixedId":true,"id":"libraries\/@42473383\/scripts\/package%3Arrrrrrr%2Fmain.dart\/16b65073cc2","uri":"package:rrrrrrr\/main.dart","_kind":"kernel"},"tokenPos":596},"function":{"type":"@Function","fixedId":true,"id":"classes\/1276\/functions\/build","name":"build","owner":{"type":"@Class","fixedId":true,"id":"classes\/1276","name":"_MyAppState","_vmName":"_MyAppState@42473383"},"_kind":"RegularFunction","static":false,"const":false,"_intrinsic":false,"_native":false},"code":{"type":"@Code","fixedId":true,"id":"code\/24a14c199-11e5f9080","name":"[Unoptimized] _MyAppState.build","_vmName":"[Unoptimized] build","kind":"Dart","_optimized":false,"_intrinsic":false,"_native":false},"vars":[{"type":"BoundVariable","name":"this","value":{"type":"@Instance","class":{"type":"@Class","fixedId":true,"id":"classes\/1276","name":"_MyAppState","_vmName":"_MyAppState@42473383"},"kind":"PlainInstance","id":"objects\/404"},"declarationTokenPos":-1,"scopeStartTokenPos":-1,"scopeEndTokenPos":1046},{"type":"BoundVariable","name":"context","value":{"type":"@Instance","class":{"type":"@Class","fixedId":true,"id":"classes\/3229","name":"StatefulElement"},"kind":"PlainInstance","id":"objects\/405"},"declarationTokenPos":547,"scopeStartTokenPos":547,"scopeEndTokenPos":1046}],"index":0}}}}
[11:42:03] ==> {"id":"478","method":"getStack","params":{"isolateId":"isolates/58989095"}}
[11:42:03] <== {"jsonrpc":"2.0", "result":{"type":"Stack","frames":[{"type":"Frame","kind":"Regular","location":{"type":"SourceLocation","script":{"type":"@Script","fixedId":true,"id":"libraries\/@42473383\/scripts\/package%3Arrrrrrr%2Fmain.dart\/16b65073cc2","uri":"package:rrrrrrr\/main.dart","_kind":"kernel"},"tokenPos":596},"function":{"type":"@Function","fixedId":true,"id":"classes\/1276\/functions\/build","name":"build","owner":{"type":"@Class","fixedId":true,"id":"classes\/1276","name":"_MyAppState","_vmName":"_MyAppState@42473383"},"_kind":"RegularFunction","static":false,"const":false,"_intrinsic":false,"_native":false},"code":{"type":"@Code","fixedId":true,"id":"code\/24a14c199-11e5f9080","name":"[Unoptimized] _MyAppState.build","_vmName":"[Unoptimized] build","kind":"Dart","_optimized":false,"_intrinsic":false,"_native":false},"vars":[{"type":"BoundVariable","name":"this","value":{"type":"@Instance","class":{"type":"@Class","fixedId":true,"id":"classes\/1276","name":"_MyAppState","_vmName":"_MyAppState@42473383"},"kind":"PlainInstance","id":"objects\/406"},"declarationTokenPos":-1,"scopeStartTokenPos":-1,"scopeEndTokenPos":1046},{"type":"BoundVariable","name":"context","value":{"type":"@Instance","class":{"type":"@Class","fixedId":true,"id":"classes\/3229","name":"StatefulElement"},"kind":"PlainInstance","id":"objects\/407"},"declarationTokenPos":547,"scopeStartTokenPos":547,"scopeEndTokenPos":1046}],"index":0},{"type":"Frame","kind":"Regular","location":{"type":"SourceLocation","script":{"type":"@Script","fixedId":true,"id":"libraries\/@44042623\/scripts\/package%3Aflutter%2Fsrc%2Fwidgets%2Fframework.dart\/16b65073d3d","uri":"package:flutter\/src\/widgets\/framework.dart","_kind":"kernel"},"tokenPos":166988},"function":{"type":"@Function","fixedId":true,"id":"classes\/3229\/functions\/build","name":"build","owner":{"type":"@Class","fixedId":true,"id":"classes\/3229","name":"StatefulElement"},"_kind":"RegularFunction","static":false,"const":false,"_intrinsic":false,"…
[11:42:04] ==> {"id":"479","method":"getStack","params":{"isolateId":"isolates/58989095"}}
[11:42:04] <== {"jsonrpc":"2.0", "result":{"type":"Stack","frames":[{"type":"Frame","kind":"Regular","location":{"type":"SourceLocation","script":{"type":"@Script","fixedId":true,"id":"libraries\/@42473383\/scripts\/package%3Arrrrrrr%2Fmain.dart\/16b65073cc2","uri":"package:rrrrrrr\/main.dart","_kind":"kernel"},"tokenPos":596},"function":{"type":"@Function","fixedId":true,"id":"classes\/1276\/functions\/build","name":"build","owner":{"type":"@Class","fixedId":true,"id":"classes\/1276","name":"_MyAppState","_vmName":"_MyAppState@42473383"},"_kind":"RegularFunction","static":false,"const":false,"_intrinsic":false,"_native":false},"code":{"type":"@Code","fixedId":true,"id":"code\/24a14c199-11e5f9080","name":"[Unoptimized] _MyAppState.build","_vmName":"[Unoptimized] build","kind":"Dart","_optimized":false,"_intrinsic":false,"_native":false},"vars":[{"type":"BoundVariable","name":"this","value":{"type":"@Instance","class":{"type":"@Class","fixedId":true,"id":"classes\/1276","name":"_MyAppState","_vmName":"_MyAppState@42473383"},"kind":"PlainInstance","id":"objects\/442"},"declarationTokenPos":-1,"scopeStartTokenPos":-1,"scopeEndTokenPos":1046},{"type":"BoundVariable","name":"context","value":{"type":"@Instance","class":{"type":"@Class","fixedId":true,"id":"classes\/3229","name":"StatefulElement"},"kind":"PlainInstance","id":"objects\/443"},"declarationTokenPos":547,"scopeStartTokenPos":547,"scopeEndTokenPos":1046}],"index":0},{"type":"Frame","kind":"Regular","location":{"type":"SourceLocation","script":{"type":"@Script","fixedId":true,"id":"libraries\/@44042623\/scripts\/package%3Aflutter%2Fsrc%2Fwidgets%2Fframework.dart\/16b65073d3d","uri":"package:flutter\/src\/widgets\/framework.dart","_kind":"kernel"},"tokenPos":166988},"function":{"type":"@Function","fixedId":true,"id":"classes\/3229\/functions\/build","name":"build","owner":{"type":"@Class","fixedId":true,"id":"classes\/3229","name":"StatefulElement"},"_kind":"RegularFunction","static":false,"const":false,"_intrinsic":false,"…

// Resume
[11:42:08] ==> {"id":"480","method":"resume","params":{"isolateId":"isolates/58989095"}}
[11:42:09] <== {"jsonrpc":"2.0", "result":{"type":"Success"},"id":"480"}
[11:42:09] <== {"jsonrpc":"2.0","method":"streamNotify","params":{"streamId":"Debug","event":{"type":"Event","kind":"Resume","isolate":{"type":"@Isolate","id":"isolates\/58989095","name":"main","number":"58989095"},"timestamp":1560768128998,"topFrame":{"type":"Frame","kind":"Regular","location":{"type":"SourceLocation","script":{"type":"@Script","fixedId":true,"id":"libraries\/@42473383\/scripts\/package%3Arrrrrrr%2Fmain.dart\/16b65073cc2","uri":"package:rrrrrrr\/main.dart","_kind":"kernel"},"tokenPos":596},"function":{"type":"@Function","fixedId":true,"id":"classes\/1276\/functions\/build","name":"build","owner":{"type":"@Class","fixedId":true,"id":"classes\/1276","name":"_MyAppState","_vmName":"_MyAppState@42473383"},"_kind":"RegularFunction","static":false,"const":false,"_intrinsic":false,"_native":false},"code":{"type":"@Code","fixedId":true,"id":"code\/24a14c199-11e5f9080","name":"[Unoptimized] _MyAppState.build","_vmName":"[Unoptimized] build","kind":"Dart","_optimized":false,"_intrinsic":false,"_native":false},"vars":[{"type":"BoundVariable","name":"this","value":{"type":"@Instance","class":{"type":"@Class","fixedId":true,"id":"classes\/1276","name":"_MyAppState","_vmName":"_MyAppState@42473383"},"kind":"PlainInstance","id":"objects\/478"},"declarationTokenPos":-1,"scopeStartTokenPos":-1,"scopeEndTokenPos":1046},{"type":"BoundVariable","name":"context","value":{"type":"@Instance","class":{"type":"@Class","fixedId":true,"id":"classes\/3229","name":"StatefulElement"},"kind":"PlainInstance","id":"objects\/479"},"declarationTokenPos":547,"scopeStartTokenPos":547,"scopeEndTokenPos":1046}],"index":0}}}}
[11:42:09] <== {"jsonrpc":"2.0","method":"streamNotify","params":{"streamId":"Extension","event":{"type":"Event","kind":"Extension","extensionKind":"Flutter.Frame","isolate":{"type":"@Isolate","id":"isolates\/58989095","name":"main","number":"58989095"},"timestamp":1560768129008,"extensionData":{"number":2,"startTime":0,"elapsed":5208652}}}}
[11:42:09] <== {"jsonrpc":"2.0","method":"streamNotify","params":{"streamId":"Extension","event":{"type":"Event","kind":"Extension","extensionKind":"Flutter.Frame","isolate":{"type":"@Isolate","id":"isolates\/58989095","name":"main","number":"58989095"},"timestamp":1560768129029,"extensionData":{"number":3,"startTime":5237166,"elapsed":8559}}}}

// Did not hit breakpoint, yet the app is not counting up, suggesting that it is paused

[11:42:19] Log file ended
```

**Comment by DanTup** [comment] 2019-06-17 10:49
I can repro without VS Code:

- `flutter run --start-paused`
- Open Observatory and add a breakpoint on the first line of the build method
- Open debugger and type `continue`
- Type `continue`
- Type `continue`

After a few continues, it'll do the same thing, and not hit the breakpoint anymore.

**Comment by szotp** [comment] 2019-06-17 15:31
Interesting.... I tried this now on Dart DevTools and it worked fine.

**Comment by bkonyi** [comment] 2019-06-19 17:17
I can reproduce in both Observatory and DevTools. It almost looks like there's a race condition or something similar. @ZichangG, is this similar to anything you've seen?

**Comment by ZichangG** [comment] 2019-06-19 18:02
Not really. Perhaps relative to context chaining of async functions.

**Comment by DanTup** [comment] 2019-06-20 14:24
Ok cool, I'll close this since I don't think there's anything to do here once it's fixed in the SDK.

**Comment by DanTup** [comment] 2019-06-20 14:25
@szotp you might want to subscribe to https://github.com/dart-lang/sdk/issues/37312 for updates.

**Closed by DanTup** 2019-06-20 14:24 UTC
Labels: in debugger, is bug, upstream in dart / flutter

**Comment by DanTup** [comment] 2019-07-08 17:20
Great, thanks!
