### ISSUE TITLE
Breakpoints disappear

### ISSUE THREAD

**Issue by incendial** [Dart-Code/Dart-Code#4598] opened 2023-06-20 16:26 UTC
**Describe the bug**
Adding breakpoints causes some of the existing breakpoints to disappear.
I mean, I like arcades, but this feels too much 😂.

https://github.com/Dart-Code/Dart-Code/assets/21116742/6ead370a-b93a-44e8-82ca-8c1fdbe38673

**To Reproduce**
1. Run a test with a breakpoint
2. When the tests stops at the breakpoint, try add new breakpoints

**Please complete the following information:**
 - Operating System and version: MacOS 12.6
 - VS Code version: 1.79.2
 - Dart extension version: 3.66.0
 - Dart/Flutter SDK version: Dart SDK version: 3.1.0-63.1.beta (beta)

**Comment by incendial** [comment] 2023-06-20 16:46
Do you need a new app AND logs? Or I can just collect logs in my project and send you?

**Comment by DanTup** [comment] 2023-06-20 16:49
A new app is best, because it confirms it can be reproduced in the code I'm testing with (I often spend time trying to repro things that seem like they should always happen, but are actually triggered by some specific things).

Logs are useful in both cases :-)

**Comment by incendial** [comment] 2023-06-25 12:09
I was not able to repro it on a new project, but here is the log from the one I have the problem in:

[Dart-Code-Log-2023-05-00 16-07-29.txt](https://github.com/Dart-Code/Dart-Code/files/11859655/Dart-Code-Log-2023-05-00.16-07-29.txt)

Does it help?

**Comment by woprandi** [comment] 2023-06-26 13:26
I was able to reproduce on a new app : 

[Dart-Code-Log-2023-05-01 15-22-36.txt](https://github.com/Dart-Code/Dart-Code/files/11869414/Dart-Code-Log-2023-05-01.15-22-36.txt)

**Comment by DanTup** [comment] 2023-06-26 14:15
@incendial thanks - looking through your log I see something wrong - we seem to resolve two breakpoints using the same ID, and I think that could be "merging" them in VS Code (we don't actually have any code that ever _removes_ breakpoints):

```
[16:07:47] [DAP] [Info] <== {"seq":220,"type":"event","body":{"breakpoint":{"id":100072,"line":39,"verified":false},"reason":"changed"},"event":"breakpoint"}
[16:07:47] [DAP] [Info] <== {"seq":221,"type":"event","body":{"breakpoint":{"column":18,"id":100072,"line":39,"verified":true},"reason":"changed"},"event":"breakpoint"}
[16:07:47] [DAP] [Info] <== {"seq":222,"type":"event","body":{"breakpoint":{"column":9,"id":100072,"line":42,"verified":true},"reason":"changed"},"event":"breakpoint"}
```

However, it's not clear to me why this happened because the VM Service traffic was not logged and I'm not sure what the source file looked liked. Are you able to capture a log while also recording what you see, and ensure you start logging _before_ you start the debug session, so that the VM Service traffic is also logged?



@woprandi I checked your log, but I only see a single breakpoint being set - it's not clear to me what you're seeing. Can you provide details of what you did/saw, and if possible also a recording of what you're seeing with a matching log. Thanks!

**Comment by incendial** [comment] 2023-06-26 14:20
Ah, I started the recording after pressing the debug button. Sure, I'll send you a full version.

**Comment by incendial** [comment] 2023-06-26 14:57
@DanTup send you an email

**Comment by woprandi** [comment] 2023-06-26 15:01
@DanTup I'm not sure I had this bug. Also a bad analysis and a wrong code. Or it's fixed now. Anyway I can't help you anymore. I'll monitor that and back here if it comes (back)

**Comment by incendial** [comment] 2023-06-26 15:27
Yeah, I was not sure what exactly you need, so send the full log. But there is a lot of data 😅.

**Comment by DanTup** [comment] 2023-06-26 15:27
@incendial out of interest, does this only happen if you click fairly quickly? I see some overlapped requests in the logs which make it difficult to follow. I'm wondering if that's related or not. If you can repro with a longer pause between each, that log file would be much easier to understand (and if it doesn't, it might confirm it's timing related).

**Comment by DanTup** [comment] 2023-06-26 15:32
Any chance you can capture a log going slowly like that (with a matching video so I can see the behaviour)? Thanks! :)

**Comment by incendial** [comment] 2023-06-26 15:34
Are you trying to make it even more entertaining for me? 😂
I didn't ask for additional quests! 

But on a serious note, sure, but probably later.

**Comment by DanTup** [comment] 2023-06-26 15:35
heh, sorry - what I see in the logs doesn't make a lot of sense so I'm trying to eliminate some variables :-)

I do see you have two isolates though, and we're adding these breakpoints twice (once to each isolate).  It seems like the VM is then giving us back different lines. Is there any possibility you have two versions of this code running in different isolates?

**Comment by DanTup** [comment] 2023-06-26 16:01
@incendial I can repro what's shown in your last videos (and it's definitely not just delayed updates), so no need to try to capture additional logs for now. Thanks for the help though :-)

**Comment by incendial** [comment] 2023-06-26 16:17
Happy to hear that! So, is it just invalid line or something worse?

**Comment by DanTup** [comment] 2023-06-26 16:19
@incendial I think it's restricted to lines where you can't stop.

I created a simple test with `debugger()` (to reduce breakpoint calls in the logs) and after it paused, I added a breakpoint to line 18. That breakpoint seemed to jump between 18 and 35 during the next breakpoint operations.

Here's an annotated log:

```
// Add breakpoint for Isolate 1
[5:03:51 PM] [General] [Info] [Dart] ==> [VM] {"jsonrpc":"2.0","id":"1209","method":"addBreakpointWithScriptUri","params":{"isolateId":"isolates/2195611364753563","scriptUri":"file:///C:/Dev/Test%20Projects/dartcode_4598/test/dartcode_4598_test.dart","line":18}}
// Add breakpoint for Isolate 2
[5:03:51 PM] [General] [Info] [Dart] ==> [VM] {"jsonrpc":"2.0","id":"1210","method":"addBreakpointWithScriptUri","params":{"isolateId":"isolates/4072316058156895","scriptUri":"file:///C:/Dev/Test%20Projects/dartcode_4598/test/dartcode_4598_test.dart","line":18}}

// Breakpoint is added to Isolate 1 and resolves to line 35 (since line 18 is not executable).
// This is correct, and results in the breakpoint moving to line 35 and turning red.
[5:03:51 PM] [General] [Info] [Dart] <== [VM] {"jsonrpc":"2.0","method":"streamNotify","params":{"streamId":"Debug","event":{"type":"Event","kind":"BreakpointAdded","isolateGroup":{"type":"@IsolateGroup","id":"isolateGroups/6623578455879048220","name":"file:///C:/Users/danny/AppData/Local/Temp/dart_test.kernel.51d6c01a/test.dart_1.dill","number":"6623578455879048220","isSystemIsolateGroup":false},"isolate":{"type":"@Isolate","id":"isolates/4072316058156895","name":"main","number":"4072316058156895","isSystemIsolate":false,"isolateGroupId":"isolateGroups/6623578455879048220"},"timestamp":1687795431020,"breakpoint":{"type":"Breakpoint","fixedId":true,"id":"breakpoints/1","enabled":true,"breakpointNumber":1,"resolved":true,"location":{"type":"SourceLocation","script":{"type":"@Script","fixedId":true,"id":"libraries/@18308214/scripts/file%3A%2F%2F%2FC%3A%2FDev%2FTest%2520Projects%2Fdartcode_4598%2Ftest%2Fdartcode_4598_test.dart/188f87266fc","uri":"file:///C:/Dev/Test%20Projects/dartcode_4598/test/dartcode_4598_test.dart"},"tokenPos":455,"line":35,"column":4}}}}}
[5:03:51 PM] [General] [Info] [Dart] <== [VM] {"jsonrpc":"2.0","result":{"type":"Breakpoint","fixedId":true,"id":"breakpoints/1","enabled":true,"breakpointNumber":1,"resolved":true,"location":{"type":"SourceLocation","script":{"type":"@Script","fixedId":true,"id":"libraries/@18308214/scripts/file%3A%2F%2F%2FC%3A%2FDev%2FTest%2520Projects%2Fdartcode_4598%2Ftest%2Fdartcode_4598_test.dart/188f87266fc","uri":"file:///C:/Dev/Test%20Projects/dartcode_4598/test/dartcode_4598_test.dart","_kind":"kernel"},"tokenPos":455,"line":35,"column":4}},"id":"1210"}


// However, we now get an event saying the breakpoint was added (unresolved) to Isolate 2.
// This never resolves, but we treat this event as the most up-to-date information about this breakpoint, so
// mark is back as unresolved and move it back to line 18.
// We may flip-flop between line 18 and line 35 depending on timing.
[5:03:51 PM] [General] [Info] [Dart] <== [VM] {"jsonrpc":"2.0","method":"streamNotify","params":{"streamId":"Debug","event":{"type":"Event","kind":"BreakpointAdded","isolateGroup":{"type":"@IsolateGroup","id":"isolateGroups/12503133928779848659","name":".dart_tool\\pub\\bin\\test\\test.dart-3.1.0-edge.4aebac3d288ca3dd9a307f0b5a96ae4ab9034a31.snapshot","number":"12503133928779848659","isSystemIsolateGroup":false},"isolate":{"type":"@Isolate","id":"isolates/2195611364753563","name":"main","number":"2195611364753563","isSystemIsolate":false,"isolateGroupId":"isolateGroups/12503133928779848659"},"timestamp":1687795431022,"breakpoint":{"type":"Breakpoint","fixedId":true,"id":"breakpoints/1","enabled":true,"breakpointNumber":1,"resolved":false,"location":{"type":"UnresolvedSourceLocation","scriptUri":"file:///C:/Dev/Test%20Projects/dartcode_4598/test/dartcode_4598_test.dart","line":18}}}}}
[5:03:51 PM] [General] [Info] [Dart] <== [VM] {"jsonrpc":"2.0","result":{"type":"Breakpoint","fixedId":true,"id":"breakpoints/1","enabled":true,"breakpointNumber":1,"resolved":false,"location":{"type":"UnresolvedSourceLocation","scriptUri":"file:///C:/Dev/Test%20Projects/dartcode_4598/test/dartcode_4598_test.dart","line":18}},"id":"1209"}
```

I think an easy fix is that we just always ignore breakpoint events that are unresolved. We never want to move a resolved breakpoint back to its unresolved location just because we didn't know which isolates it was valid for. I'll try this out shortly and post back.

**Comment by DanTup** [comment] 2023-06-26 16:22
> I think it's restricted to lines where you can't stop.

To clarify: the thing I repro'd and your most recent video I think this is the case. I'm less sure about the very top video here though.

**Comment by DanTup** [comment] 2023-06-26 16:25
> This feels scary in case there are some problems with them marked unresolved unintentionally. I'm actually wondering why there are two isolates and why they both participate...

Not sure I understand. Breakpoints can never be unresolved once resolved. It just happens that we get the events for each isolate, and because we blindly read the "verified" flag from the VM, we pass it on to VS and essentially instruct it to go back to the unresolved state. It's always possible we'll add the breakpoint to isolates that won't resolve it so we need to handle that.

> I'm actually wondering why there are two isolates and why they both participate...

I'm pretty sure one of them is `package:test` being invoked, and the other is an isolate it uses to run your tests (so you can't crash it, or consume the whole isolate and prevent it timing out your test, etc.).

**Comment by incendial** [comment] 2023-06-26 16:25
I'm not sure about that "only invalid lines" thing 🙂.

https://github.com/Dart-Code/Dart-Code/assets/21116742/d8933b37-54af-43a2-af73-20c133d4aa1c

**Comment by DanTup** [comment] 2023-06-26 16:26
> I'm not sure about that "only invalid lines" thing 🙂.

Yeah, see https://github.com/Dart-Code/Dart-Code/issues/4598#issuecomment-1607818155

I think it explains what I can repro but I'm less sure it's the whole issue. If you can get a log+video of that (with pauses between each action), that would be appreciated :-)

**Comment by incendial** [comment] 2023-06-26 16:29
> Breakpoints can never be unresolved once resolved.

Ah, then it makes sense. I thought that (due to the current behaviour in VS Code) they can get back to unresolved.

> I'm pretty sure one of them is package:test being invoked, and the other is an isolate it uses to run your tests (so you can't crash it, or consume the whole isolate and prevent it timing out your test, etc.).

Okay, but why both of them participate? Shouldn't it be only one isolate (the main, controlling)?

**Comment by DanTup** [comment] 2023-06-26 16:32
> Ah, then it makes sense. I thought that (due to the current behaviour in VS Code) they can get back to unresolved.

To be more specific - a breakpoint set in an isolate in the VM cannot be unresolved. However when you modify breakpoints, VS Code just gives us a whole new set (it doesn't tell us about added/removed breakpoints), so we remove and re-add them. So in that respect, they may become unresolved as far as VS Code is concerned (because they're actually new breakpoints that need to be resolved).

> Okay, but why they both participate? Shouldn't it be only one isolate (the main, controlling)?

The UI in VS Code doesn't let you set breakpoints per-thread, so when it tells us to set breakpoints, we have to send them to all isolates. While some isolates might have not loaded your script, it's possible they will load it in future, so we still need to send them the breakpoint.

**Comment by incendial** [comment] 2023-07-04 05:59
@DanTup sorry, but do you remind me what do you need from me?

> https://github.com/dart-lang/sdk/commit/4d1b41823061b17dea1418e45688d2f8dc8b2c27 just landed which fixes at least some of the issues above
Do test this or there is something else?

**Comment by DanTup** [comment] 2023-07-04 16:29
@incendial I wanted to know if you can still reproduce this issue with an SDK that includes the change above. If so, I'd be interested in a log/video. I was never able to reproduce them them disappearing on "valid" lines, only when they resolved to the same location.

**Comment by DanTup** [comment] 2023-07-27 11:50
@incendial are you able to reproduce this at all using a bleeding-edge/master SDK?

**Comment by incendial** [comment] 2023-07-27 12:51
Which Dart version includes this fix? I have Flutter master with dart `3.1.0-348.0.dev (dev)` and still see this issue

**Comment by DanTup** [comment] 2023-07-27 13:30
That version includes the change above (as long as you're running a Dart project, not Flutter, and using the new SDK debug adapters).

Are you able to capture a log file of this happening (and ideally a video from the same repro as the log file)? The only issue I was able to reproduce above was the one that change fixed.

Thanks!

**Comment by incendial** [comment] 2023-08-07 17:51
Upgraded to the master channel again (now it's Dart 3.2.0-41.0.dev) and can't reproduce the issue.

Although, breakpoints blink a bit annoyingly

https://github.com/Dart-Code/Dart-Code/assets/21116742/daa2f555-2830-4fd7-8f21-7b00d4dc103c

**Comment by DanTup** [comment] 2023-08-07 18:01
Thanks for testing!

I think the blinking is because when you add/remove a breakpoint, VS Code doesn't tell us about the individual change, it just sends us a whole new set and says "replace all the breakpoints with these" so we end up deleting all the old ones and adding the new ones.

It's possible now that we're able to provide IDs for them that it'll send our IDs back that would make it easier to figure out which ones are added/deleted. I've filed https://github.com/Dart-Code/Dart-Code/issues/4678 to have a look at this.

I'll close this one as it seems like the issue was solved (probably by changes for #4599 - they probably were related). Thanks!

**Closed by DanTup** 2023-08-07 18:01 UTC
Labels: is bug, in debugger, awaiting info

**Comment by jackmchristie** [comment] 2024-04-02 17:18
@DanTup I am experiencing behavior very similarly to this still. 

Let me know if I can help in any other way. This problem is very intermittent for me. Reloading VS Code fixes it for a while usually. 

Here is a video recorder - I am trying to set a break point on line 35 - every time I click, it does something weird with my breakpoints.

https://github.com/Dart-Code/Dart-Code/assets/11194069/9ecf0e74-f97d-4a60-9a88-1b77bf82f354



Here is the log that I tried to get:

[Dart-Code-Log-2024-03-02 13-09-35.txt](https://github.com/Dart-Code/Dart-Code/files/14841546/Dart-Code-Log-2024-03-02.13-09-35.txt)

**Comment by DanTup** [comment] 2024-04-22 13:51
@jackmchristie sorry for the delay, I just found the notification for this.

Are you able to make a small sample that reproduces this issue and share it in a new issue? I had a quick try but couldn't reproduce it. Can you also include details of your Dart extension version and your Flutter SDK version? Thanks!
