### ISSUE TITLE
Huge CPU spike when using android studio

### ISSUE THREAD

**Issue by MiguelSOliveira** [Dart-Code/Dart-Code#3249] opened 2021-04-02 00:28 UTC
**Describe the bug**
Ever since I've upgraded to Flutter 2(I think it was at this time), developing with both Android Studio and VsCode, honestly, has been unbearable. Auto completion does not work, syntax highlighting takes close to a minute at times, I get stuck saving files on VSCode running the formatter... 

It's basically like not using the plugin at all, since I can almost write everything before the pop ups come in to help me.

I honestly don't know how to help here with more information. Maybe the size of my project? Is this an already known issue?

**To Reproduce**
Can't reproduce, I suspect it's due to the size of my project. I also can't share the source code.

**Expected behavior**
CPU usage should remain down

**Screenshots**
![image](https://user-images.githubusercontent.com/8149533/113366814-332b2900-9352-11eb-92a2-ad9c840307a2.png)

**Versions (please complete the following information):**
- My CPU: 2,8 GHz Quad-Core Intel Core i7
 - VS Code version: N/A
 - Android Studio: 4.2 Beta 5 (but also occurs on 4.1)
 - Dart extension version: 202.8443
 - Dart/Flutter SDK version: 
```
Flutter 2.0.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 4d7946a68d (2 weeks ago) • 2021-03-18 17:24:33 -0700
Engine • revision 3459eb2436
Tools • Dart 2.12.2
```

**EDIT:** Visual code's problems appear to have been sorted by disabling "previewLsp" as suggested in other issues. The problem appears to be only on Android Studio now.

**Comment by DanTup** [comment] 2021-04-06 10:59
> Can't reproduce, I suspect it's due to the size of my project.

There is a known issue in the current Flutter stable when using LSP that can cause some expensive work to run when you open new files. If your project is very large, that could take a little time.

I would recommend disabling LSP for now. That issue is resolved in the dev/master branch and should be included in an upcoming Flutter version. (If you're able to easily test/verify on dev/master, it would be good to know that the fix definitely resolves the issue for you too).

Thanks!

**Comment by fredgrott** [comment] 2021-04-17 19:29
@DanTup are you not missing something? the VSCodeDartCode plugin does not run on Android Studio at all per the original issue report listing VSCode version as N/a.  the issue author is having a problem with the dart plugin for Android Studio not VSCODe.

**Comment by DanTup** [comment] 2021-04-20 11:21
@fredgrott it wasn't clear if the issue was when you ran both - though it also mentioned slow formatting and that disabling LSP fixed it. Android Studio doesn't use LSP, so it sounded like there was at least something not right in VS Code (though whether it's issues I've recently fixed that haven't made Flutter stable, I'm not sure).

I'll leave this as awaiting-info so the bot will close it after 30-40 days of no updates, so if the issue is still seen in the latest versions of Flutter (beta/dev/master) I'd like to know. Thanks!

**Comment by MiguelSOliveira** [comment] 2021-04-20 20:28
Sorry guys, hadn't seen this discussion. I don't know if it was an upgrade of flutter or what, but it appears that the problem is no longer present in android studio.

This is running:
Flutter 2.0.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision adc687823a (4 days ago) • 2021-04-16 09:40:20 -0700
Engine • revision b09f014e96
Tools • Dart 2.12.3

So for me, this issue can be closed as I can no longer reproduce the problem.

**Comment by DanTup** [comment] 2021-04-21 15:01
Ok - do let us know if you see the issue again (although if it's reproducible using Android Studio it's likely not an issue here in the VS Code extension - if you have issues that occur only in VS Code, then it may be). Thanks!

**Closed by DanTup** 2021-04-21 15:01 UTC
Labels: awaiting info, is bug
