### ISSUE TITLE
LSP completion does not include any items when the cursor is in whitespace before an identifier

### ISSUE THREAD

**Issue by Maistho** [Dart-Code/Dart-Code#2672] opened 2020-07-26 15:26 UTC
It's the most visible inside flutter code, see example below.

The issue only occurs if `dart.previewLsp` is enabled in the settings.

```dart
return Container(
  // If I put my cursor on the first line and press ctrl+space I do not get any suggestions
  child: Text(“test”),
  // I also don't get any suggestions between two items
  color: Colors.red,
  // But, if there's a comma between my cursor and the next word, the suggestions appear
  ,
  alignment: Alignment.center,
);
```

**Comment by DanTup** [comment] 2020-07-29 09:18
Can you clarify exactly where you have your cursor when invoking completion, and which items you expect to see (that show for non-LSP mode) that don't? I did some testing, but I couldn't find any differences in LSP/DAS modes. Thanks!

**Comment by RaviKavaiya** [comment] 2020-07-30 03:59
@DanTup  Same problem here.
Let me show the screenshots:

### LSP: OFF
![Screenshot 2020-07-30 at 9 23 09 AM](https://user-images.githubusercontent.com/45350182/88878853-76268100-d246-11ea-9391-c2663daf9fed.png)
Here, as you can see, on `line 8`, I have a child parameter already set. My cursor is on `line 7`, still it shows suggestions for Container parameters. THIS IS AS EXPECTED.

---

### LSP: ON
![Screenshot 2020-07-30 at 9 21 47 AM](https://user-images.githubusercontent.com/45350182/88878940-aff78780-d246-11ea-994a-8ab8d68a26a4.png)
Now, the same example as above. You can see that there is no property suggested of Container. This is not expected.

The issue only comes when the cursor is at first line or in the middle...

I hope I could convince.

**Comment by DanTup** [comment] 2020-07-30 09:33
@RaviKavaiya perfect - I can reproduce now. Will take a look. Thanks!

**Comment by DanTup** [comment] 2020-07-30 10:28
I think I've figured this out. I've sent a change for review at https://dart-review.googlesource.com/c/sdk/+/156501/.

**Comment by Maistho** [comment] 2020-08-07 21:43
I tried it again today since I saw that the patch had landed.

Using the latest master release of the flutter sdk, which has dart `2.10.0-3.0.dev`. It seems like it works as expected now.

I guess it will be a while before it is rolled out fully on the stable/beta branches. Thanks for the fix :)

**Comment by RaviKavaiya** [comment] 2020-08-09 01:34
Hi @DanTup :wave:   
This issue seems to be fixed on latest dev version. You can close... 

Thanks.

**Comment by DanTup** [comment] 2020-08-10 09:04
Yep, this was fixed in https://github.com/dart-lang/sdk/commit/38fa4aea172c249a3c10ff9ec66b1a352fb5b753. Thanks!

**Closed by DanTup** 2020-08-10 09:04 UTC
Labels: in editor, in lsp server, is bug
