### ISSUE TITLE
Tests are not being shown anymore in "Testing" tool of vscode

### ISSUE THREAD

**Issue by maboumra** [Dart-Code/Dart-Code#3600] opened 2021-10-08 10:16 UTC
I really don't know if this is an extension issue and I am sorry if it isn't. Anyway, I have a flutter project and all tests were shown when I used the testing tool of vscode. Now the tool doesn't show any tests and shows the message "No tests have been found in this workspace yet" but the tests are there.

If I manually open the tests it shows only the ones I've opened.

1. Open a flutter project with tests in vscode
2. Click on the testing tool

**Expected behavior**
Should show all tests 

![image](https://user-images.githubusercontent.com/18405469/136539391-f6d0a582-49be-4a1b-ab9b-8a2187c276f8.png)
![image](https://user-images.githubusercontent.com/18405469/136539442-ce0123c5-e794-4456-afce-a5f9e5996bc0.png)

**Versions:**
 - VS Code version: 1.61.0
 - Dart extension version:  3.27.0
 - Dart/Flutter SDK version: 2.5.2

**Comment by DanTup** [comment] 2021-10-08 14:04
It's always been the behaviour that tests would only show up once you open a test file. We've not scanned the workspace for test files before - although that's being implemented for the next release.

What is different though, is that in the custom test runner, the "Run All Tests" button would run all tests in the `test` folder using `dart test`, which indirectly discovered them all. The equivalent "Run Tests" button in the new VS Code test runner does not behave the same, and only runs _already discovered_ tests.

The short-term workaround is to run the **Dart: Run All Tests** command from the command palette, which is what used to run when you clicked the button in the test runner.

For the next major release, there will be better test discovery to test files and tests within them can be discovered without opening the files.

Closing this as a dupe of #3591, as I think it's essentially the same request.

**Closed by DanTup** 2021-10-08 14:04 UTC
Labels: is bug
