### ISSUE TITLE
left angle bracket color before string interpolation is incorrect 

### ISSUE THREAD

**Issue by osaxma** [Dart-Code/Dart-Code#4107] opened 2022-08-17 23:39 UTC
**Describe the bug**

- The color of the angle bracket becomes the same as the `$` sign. 
- Also the `$` between the two angle brackets loses its distinct color before typing the variable. 

**To Reproduce**

https://user-images.githubusercontent.com/46427323/185261570-aac6be4f-71f4-4f88-8ab6-f8e058e07378.mov

**Please complete the following information:**
 - Operating System and version: MacOS
 - VS Code version: 1.70.0
 - Dart extension version: v3.46.1
 - Dart/Flutter SDK version: 2.17.6 (stable)

--- 
I've been working a lot with code generation lately and when the left angle bracket turns white, it confuses me as if it's part of the interpolation 😅 

Sorry if this is not the right place to file the bug.
Cheers

**Comment by DanTup** [comment] 2022-08-31 10:59
I don't seem to be able to reproduce this. This is what I see with semantic tokens disabled:

<img width="328" alt="Screenshot 2022-08-31 at 11 57 03" src="https://user-images.githubusercontent.com/1078012/187663396-fad5cb72-df26-42dc-976e-0e4a811e77e2.png">

And where's what I see with them enabled:

<img width="340" alt="Screenshot 2022-08-31 at 11 57 31" src="https://user-images.githubusercontent.com/1078012/187663433-edbb1f6b-196d-460c-b09d-2f0a88db9088.png">

I tried both current stable and pre-release versions of the Dart extension. I tried both the Dark and Dark+ colour themes.

Could you paste some exact code that you see this one, confirm which theme you're using, and whether you have semantic tokens (`editor.semanticHighlighting.enabled`) enabled? Thanks!

**Comment by osaxma** [comment] 2022-08-31 12:11
- Theme:
  <img width="629" alt="Screen Shot 2022-08-31 at 2 57 06 PM" src="https://user-images.githubusercontent.com/46427323/187673829-ce49367a-4394-41e8-94c6-e330a4965255.png">

- `editor.semanticHighlighting.enabled` was not in "settings.json" but here is how it looked when:
  -  set to `false` -- no issue:
  
      <img width="513" alt="Screen Shot 2022-08-31 at 3 00 43 PM" src="https://user-images.githubusercontent.com/46427323/187673979-e3547e45-cb87-4c58-ae14-1fa785a29d3d.png">

  - set to `true` (seems the default) -- has issue:
   
    <img width="489" alt="Screen Shot 2022-08-31 at 3 00 59 PM" src="https://user-images.githubusercontent.com/46427323/187674210-cb26f94e-652d-4065-97d8-94d100505681.png">
  
  - Code snippet:
    ```dart
      String _ensureReturnTypeHasFuture(DartType type) {
      if (type.isDartAsyncFuture || type.isDartAsyncStream) {
        return type.getDisplayString(withNullability: true);
      }
  
      return 'Future<${type.getDisplayString(withNullability: true)}>';
    }
    ```


Please let me know if you need any additional info.

**Comment by osaxma** [comment] 2022-08-31 12:13
Also here's all my `editior.*` settings:
```json
    "editor.minimap.enabled": false,
    "editor.codeLens": false,
    "editor.semanticHighlighting.enabled": true,
    "editor.fontFamily": "JetBrains Mono",
    "editor.fontSize": 12,
    "editor.fontLigatures": true,
    "editor.accessibilitySupport": "off",
    "editor.foldingHighlight": false,
    "editor.suggestSelection": "first",
    "dart.lineLength": 120,
    "[dart]": {
        "editor.formatOnSave": false,
        "editor.formatOnType": false,
        "editor.rulers": [
            120
        ],
        "editor.selectionHighlight": false,
        "editor.suggest.snippetsPreventQuickSuggestions": false,
        "editor.suggestSelection": "first",
        "editor.tabCompletion": "onlySnippets",
        "editor.wordBasedSuggestions": false
    },
```

**Comment by osaxma** [comment] 2022-08-31 12:14
Found it -- it's the Font!

When I commented out `"editor.fontFamily": "JetBrains Mono",` -- there is no issue ...

**Comment by DanTup** [comment] 2022-08-31 12:53
WAT? 😬

Can you run the "Inspect tokens and scopes" command and put your caret between `Future` and `<` and see what you get?

I get this, which shows that `Future<` is all a single token. If you see the same, I don't understand how the front is affecting the color 🤔

<img width="624" alt="Screenshot 2022-08-31 at 13 52 22" src="https://user-images.githubusercontent.com/1078012/187682675-42378068-2b39-40ef-879e-4f6fceeba2de.png">

**Comment by DanTup** [comment] 2022-08-31 12:55
Also - does changing `fontLigatures` affect it?

**Comment by osaxma** [comment] 2022-08-31 13:39
>  Can you run the "Inspect tokens and scopes" command and put your caret between Future and < and see what you get?

One token apparently :/ 

<img width="507" alt="Screen Shot 2022-08-31 at 4 37 14 PM" src="https://user-images.githubusercontent.com/46427323/187691757-5f151c06-faa9-483d-8c38-b52e8ed4fc03.png">


> Also - does changing `fontLigatures` affect it?

Disabling `fontLigatures` makes the issue go away.

**Comment by DanTup** [comment] 2022-08-31 13:45
Thanks - I think that's it.  In your screenshot it looks like the `<` and `$` are joined together, which I guess is because of ligatures, which seems to be https://github.com/microsoft/vscode/issues/131092. I don't know whether that's a bug somewhere, or it's by design that ligatures can only be one color, but I don't think there's anything we can do here unfortunately (so going to close this as an upstream issue).

There was a request in VS Code to allow disabling specific ligatures (so you could blacklist `<$` for example), but it was closed for not getting enough 👍s:

https://github.com/microsoft/vscode/issues/98758

**Closed by DanTup** 2022-08-31 13:45 UTC
Labels: is bug, in editor, awaiting info
