### ISSUE TITLE
vscode is leaking "flutter_test" processes

### ISSUE THREAD

**Issue by gaaclarke** [Dart-Code/Dart-Code#5256] opened 2024-09-10 15:59 UTC
While VSCode was open I saw I had a lot of `flutter_test` processes running despite the fact I wasn't running any tests.  I then closed VSCode and saw that the processes were still alive.

We had to fix something like this for analysis, remember?  Hopefully it will be a similar fix.

## seen result
`flutter_test` instances despite no tests running and no VSCode open

<img width="909" alt="Screenshot 2024-09-10 at 8 55 25 AM" src="https://github.com/user-attachments/assets/da9390ce-47eb-4f88-8742-a43f5994b564">

## expected result

1) I expect no `flutter_test` instances unless I'm executing tests
1) I expect subprocesses to vscode to be cleaned up when exiting the app

## info

**platform:** macos

**Comment by DanTup** [comment] 2024-09-11 10:29
Thanks for the report! This seems to be a Flutter issue (see https://github.com/flutter/flutter/issues/144222#issuecomment-1970945402) or Dart issue (see https://github.com/dart-lang/sdk/issues/49234) and can be reproduce without VS Code.

We can't do any cleanup of the process from VS Code, because we don't know which (if any) of those `flutter_tester` processes relate to the test run we started (`flutter_tester` is spawned from within `flutter test` and not by the VS Code extension itself).

I'll close this in favour of those issues, as once they are resolved I expect the issue to disappear from VS Code.

**Closed** 2024-09-11 10:29 UTC
Labels: upstream in dart / flutter
