### ISSUE TITLE
Code navigation doesn't work correctly for conditional imports 

### ISSUE THREAD

**Issue by osaxma** [Dart-Code/Dart-Code#3071] opened 2021-01-15 17:28 UTC
**Describe the bug**

In VS code, conditional imports breaks code navigation (i.e. pressing cmd+click) and linting (i.e., showing error for invalid paths) as shown below:

```dart
import 'package:file_picker/file_picker.dart'; // cmd+click ✅  lint ✅  
import 'image_cropper/cropper_stub.dart' // cmd+click ❌  lint ✅  
    if (dart.library.io) 'image_cropper/cropper_mobile.dart' // cmd+click ❌  lint ❌
    if (dart.library.html) 'image_cropper/cropper_web.dart'; // cmd+click ❌  lint ❌
```

**Versions (please complete the following information):**
- VS Code version: 1.52.1
- Dart extension version: v3.18.1
- Dart/Flutter SDK version: v3.18.1

**Comment by DanTup** [comment] 2021-06-08 16:57
@bwilkerson do you know what the expected behaviour is for the missing files here?

```dart
import 'invalid_1.dart'
    if (dart.library.io) 'invalid_2.dart'
    if (dart.library.html) 'invalid_3.dart';
```

The code in [`LibraryAnalyzer._validateUriBasedDirective`](https://github.com/dart-lang/sdk/blob/a0f7d56ca501d67edbba2327026d87f2c19db52d/pkg/analyzer/lib/src/dart/analysis/library_analyzer.dart#L783-L786) looks like it will validate the "selected" one (the one whose condition is matched), although in my testing it seems to always only ever validate the main uri (in a test it seems like the selected URI is always the main one, although I'm not sure if that's just because something isn't set up for the test or that's also what's happening when I try it in a real project).

I suspect it's not difficult to additionally validate each conditional uri, though since the existing code appears to be trying to use the "selected" URI I'm not certain if that's the right route.

**Comment by bwilkerson** [comment] 2021-06-08 17:03
The analyzer's support for conditional imports is not as complete as I'd like it to be. I suspect that the code you pointed to was an earlier attempt to conform to the specification before we realized that it didn't really make sense to do so in the analyzer (because there's no way for users to define the flags that control which URI would be selected).

We can, and should, both validate the conditional URIs and provide navigation from them to the referenced file. I don't think either of those should be tied to the "selected" URI.

**Comment by DanTup** [comment] 2021-06-08 17:55
Great - I'll take a look at validating each URI then.

For the navigation, it seemed to be working but was returning too many regions which caused VS Code to open a Peek window letting you pick between them (it would include all conditional uris instead of only the one at the requested location). I have a fix for that at https://dart-review.googlesource.com/c/sdk/+/202772/ (@osaxma if that wasn't what you were seeing, let me know and we can debug some more).

**Comment by DanTup** [comment] 2021-06-21 13:20
I'm splitting this issue because there are two problems and one is fixed, but the other has some complications.

#3422 relates to not showing errors, which I have a fix in progress for but there are some details to work out.

This issue is now just for navigation, which is fixed by https://github.com/dart-lang/sdk/commit/eb2836872a5c3d6b02f5fe4bfdd1393bc9efc5eb (if my reproduction of the issue is the same - which is that multiple ranges are returned and VS Code shows them all in the peek window, rather than just jumping to the correct one). The fix will be included in an upcoming (non-hotfix) SDK release.

**Closed by DanTup** 2021-06-21 13:20 UTC
Labels: in editor, in lsp/analysis server, is enhancement
