### ISSUE TITLE
Misalignment in Run Test Buttons

### ISSUE THREAD

**Issue by osaxma** [Dart-Code/Dart-Code#4163] opened 2022-09-17 10:02 UTC
**Describe the bug**
The bug usually occurs while creating new tests, moving them around or grouping them.. See screenshot below. 

Reloading VS Code seems the only option atm to realign the buttons (closing/reopening the file does not help)

**To Reproduce**
Unable to reproduce at the moment. I've seen it multiple time 

**Expected behavior**
The buttons should be aligned with tests. 

**Screenshots**

<img width="465" alt="Screen Shot 2022-09-16 at 2 49 11 PM" src="https://user-images.githubusercontent.com/46427323/190851214-2a8eec6f-a605-4903-a13c-4c863e484182.png">

**Please complete the following information:**
 - Operating System and version: MacOS
 - VS Code version: 1.71.2
 - Dart extension version: v3.48.4
 - Dart/Flutter SDK version: Dart 2.18 

**Additional Context**
When I observed the issues, I had `"editor.codeLens": false"`  in the VS Code settings. I've enabled the code lens now and I'll follow up with an update if the issue appears.

Related Discord discussion ([here](https://discord.com/channels/615553440969392147/615553440969392151/1020609676221616139))

**Comment by DanTup** [comment] 2022-09-20 14:31
Maye something to do with debouncing? If I cut the entire doc and wait for the test runner to clear, then paste, things come back correctly. If I paste before it updates, then it gets into the broken state.

**Comment by DanTup** [comment] 2022-09-20 14:56
I think this might be a VS Code issue. I've filed https://github.com/microsoft/vscode/issues/161320 with some steps to repro what seems like this issue using their sample project.

I believe VS Code's test runner is doing an internal diff and skipping some work when the tests have not really changed. However, because of our debouncing, it's easy to make a set of changes where the test ends up back on the same line as it was originally (and thus doesn't get updated), but VS Code's editor had moved the gutter icons to compensate for some change in-between.

**Comment by DanTup** [comment] 2022-09-22 11:33
A fix has been made in VS Code: https://github.com/microsoft/vscode/issues/161320. I'm not certain that it's the same issue, but I think there's a good chance. VS Code usually releases in the first week of each month, so it's probably ~2weeks away. Please let me know if you see this at all again after VS Code updates and we can do some more digging.

**Comment by osaxma** [comment] 2022-09-22 11:45
Hi @DanTup 

Thanks for your effort in looking into this. 

I haven't faced the issue again so far -- probably because I turned "`editor.codeLens"`  to `true` (thanks again for that awesome tip). 

I'll circle back if it appears again.

**Comment by DanTup** [comment] 2022-09-22 13:15
I had a quick scan through the code again and I suspect the CodeLens setting doesn't actually impact this now. Our test discovery works even without the CodeLens (which is show we populate the test runner even when codeLens is not enabled).

I'll keep this open a little until the VS Code release goes out and if it doesn't come up again after that, close it (or let the stale bot).

Thanks!

**Comment by osaxma** [comment] 2022-11-16 22:26
Hi @DanTup 

I'm not sure if this is the same issue (in line 12, I believe the checkmark should be next to main)

<img width="707" alt="Screen Shot 2022-11-17 at 1 20 53 AM" src="https://user-images.githubusercontent.com/46427323/202306981-cd4cb366-a48e-4872-85e7-6d1e17eb9151.png">


To reproduce:
- `git clone https://github.com/isoos/postgresql-dart.git`
- open `tests/logical_replication_test.dart` file
- Run the test (either using git lense or from the testing tab)
  - the test needs Docker to be installed and may download a postgres image. Though I think a failing check mark would be placed at line 12 for timeout if docker not available.
- You'll see a spinning indicator in line 12  

<img width="250" alt="Screen Shot 2022-11-17 at 1 23 52 AM" src="https://user-images.githubusercontent.com/46427323/202307506-0e3eafab-58d3-43da-b278-cdbda1a968a0.png">


Sorry wrote this in a rush before I forget about it...

**Comment by DanTup** [comment] 2022-11-28 19:09
I don't know if it's the same issue either, but since one issue was fixed by VS Code which may or may not have been the original issue, we can use this issue for the above (since I can repro and it should be easier to track down), and if any other issues continues after this is fixed, we can file a new issue.

I can repro your issue, but small refactors to try and get it into a small single file seem to stop it from happening. I'll do some debugging and see what's going on. Sorry for the delay!

**Comment by DanTup** [comment] 2022-11-28 19:27
So, I expect this probably is the original issue you saw. What seems to be happening is that then `setUpAll` and `tearDownAll` calls inside `usePostgresDocker` are being registered as tests (which is somewhat expected - it's how success/failure is shown for those calls), but assumed to be in the test file:

<img width="1147" alt="Screenshot 2022-11-28 at 19 24 17" src="https://user-images.githubusercontent.com/1078012/204363647-ff188cd2-5bdd-4c31-bff6-d7254a61b8ef.png">

The JSON from `package:test` looks reasonable.. it looks as if we're using the correct line/col (A+B) but the wrong file (D instead of C):

```
{
	"seq": 12,
	"type": "event",
	"body": {
		"test": {
			"id": 3,
			"name": "(setUpAll)",
			"suiteID": 0,
			"groupIDs": [
				2
			],
			"metadata": {
				"skip": false,
				"skipReason": null
			},
			"line": 10, // A
			"column": 3, // B
			"url": "file:///Users/danny/Dev/TestStuff/postgresql-dart/test/docker.dart", // C
			"root_line": 8,
			"root_column": 3,
			"root_url": "file:///Users/danny/Dev/TestStuff/postgresql-dart/test/logical_replication_test.dart" // D
		},
		"type": "testStart",
		"time": 570
	},
	"event": "dart.testNotification"
}
```

**Comment by DanTup** [comment] 2022-11-28 19:34
(sorry for the spam, I tend to keep notes on issues in case I get distracted and have to come back to them 😄)

It seems we use `root_` for both cases here. We're actually using line 8, but there's an off-by-one somewhere. So the ticks should actually show up against `usePostgresDocker`.

It's a little odd/confusing having them show up this way, but it's how `package:test` presents them and if we don't show them, it wouldn't be so obvious when a failure is caused by a setup/teardown:

![Screenshot 2022-11-28 at 19 31 24](https://user-images.githubusercontent.com/1078012/204364634-c719c553-8074-48b7-8517-54978628777d.png)

So I think if we fix the off-by-one error, maybe that would be fine.

However - given that, I'm now less convinced that it's the same issue as the screenshot right at the top 😄

I'm outta time for today, but will do some more digging into this tomorrow.. I'm hoping to do an extension release tomorrow, but if this is an easy fix I'd like to get it in the release.

**Closed** 2022-11-29 10:32 UTC
Labels: is bug, in editor, in testing

**Comment by DanTup** [comment] 2022-11-29 10:36
I've pushed a fix for the off-by-one error:

![Screenshot 2022-11-29 at 10 32 28](https://user-images.githubusercontent.com/1078012/204506214-9973edfb-2da4-4883-8e87-a3067ca05ac6.png)

It's a little odd (confusing?) that this appears here, but the general design here is that if your test calls functions in other files (which may call `test` or `setup`/`teardown`) we use the frame from the stack that is in the file where the entry to the test is. This avoids all of your tests being attributed to some shared "runTest" function if you have some wrapper around the `test` function.

I think it would probably be better if VS Code let us mark setup/teardown as "not runnable", so we can still show them in the tree (to indicate where the failure was), but without them behaving like tests that can be run. Right now if you try to run one of these, it will fail.

I'll file a VS Code issue and see what the response is. If they don't want to do this, maybe we can reconsider showing them in the tree in this way.

If you see any additional issues with bad alignment like this, let's file new issues to investigate them specifically. Thanks!

**Comment by DanTup** [comment] 2022-11-29 10:45
Looks like we might actually be able to already restrict this, so I've filed #4286 about this.

**Comment by osaxma** [comment] 2022-11-29 14:05
Thank you @DanTup for your time and efforts -- they are much appreciated 🙏🏽

**Comment by DanTup** [comment] 2022-11-29 15:13
np! Thanks for taking time to file issues and provide repros, it makes things much easier for me to track down and fix :-)

**Comment by louis-grimaldi** [comment] 2024-07-31 14:38
Any updates ? Still happening very frequently.

**Comment by DanTup** [comment] 2024-07-31 14:50
@louis-grimaldi this issue has been closed for a long time - if you're having trouble please open a new issue and include as much detail as you can. Thanks!
