### ISSUE TITLE
getObject: (-32603) Unexpected DWDS error for getObject: type 'Null' is not a subtype of type 'Map<String, dynamic>' in type cast

### ISSUE THREAD

**Issue by Lerobindesbois** [Dart-Code/Dart-Code#4886] opened 2023-12-06 18:50 UTC
**Describe the bug**
Expressions in the debugger always give the result as in the screenshot when inspecting variables and class in web development, VS Code DArt debugger fail to evaluatte expression. :-(

**To Reproduce**
Make a new flutter project
Put a break point
look at the variables and the results of the values in the debugger always give the result as in the screenshot in section VARIABLES.

**Screenshots**

![Capture d’écran, le 2023-12-06 à 13 44 09](https://github.com/Dart-Code/Dart-Code/assets/69640665/ca9ccca4-a720-486f-b255-19f2afa9d39c)

**!! ⚠️ PLEASE REVIEW THIS REPORT FOR SENSITIVE INFORMATION BEFORE SHARING ⚠️ !!**

<details>

<summary><strong>Workspace Environment</strong></summary>

```text
Dart Code extension: 3.78.0
Flutter extension: 3.78.0 (activated)

App: Visual Studio Code
App Host: desktop
Version: mac 1.84.2

Workspace type: Flutter (LSP)

Dart (3.2.3): /Users/robintre/flutter/bin/cache/dart-sdk
Flutter (3.16.3): /Users/robintre/flutter (Chrome (web-javascript/web))

```

</details>

<details>

<summary><strong>Output from 'dart info'</strong></summary>

`/Users/robintre/flutter/bin/cache/dart-sdk/bin/dart info`

If providing this information as part of reporting a bug, please review the information
below to ensure it only contains things you're comfortable posting publicly.

#### General info

- Dart 3.2.3 (stable) (Tue Dec 5 17:58:33 2023 +0000) on "macos_arm64"
- on macos / Version 14.1.2 (Build 23B2091)
- locale is fr-CA

#### Project info

- sdk constraint: '>=3.2.2 <4.0.0'
- dependencies: flutter
- dev_dependencies: build_runner, flutter_lints, flutter_test

#### Process info

|  Memory |  CPU | Elapsed time | Command line                                                                               |
| ------: | ---: | -----------: | ------------------------------------------------------------------------------------------ |
|   51 MB | 0.0% |        10:52 | dart devtools --machine --allow-embedding --port 9100                                      |
|   51 MB | 0.0% |        06:22 | dart devtools --machine --allow-embedding --port 9102                                      |
|  402 MB | 0.0% |     03:35:26 | dart language-server --client-id=Android-Studio --client-version=AI-223.8836.35 --protocol=analyzer |
| 1144 MB | 0.0% |        10:52 | dart language-server --protocol=lsp --client-id=VS-Code --client-version=3.78.0            |
|  492 MB | 0.0% |        06:22 | dart language-server --protocol=lsp --client-id=VS-Code --client-version=3.78.0            |
|   68 MB | 0.0% |        12:06 | flutter_tools.snapshot daemon                                                              |
|   74 MB | 0.5% |        10:52 | flutter_tools.snapshot daemon                                                              |
|   85 MB | 0.0% |        06:22 | flutter_tools.snapshot daemon                                                              |
|  135 MB | 0.0% |        06:11 | flutter_tools.snapshot debug_adapter                                                       |
|  295 MB | 0.4% |        06:11 | flutter_tools.snapshot run --machine --start-paused -d chrome --devtools-server-address http:<path>/ --target <path>/main.dart |
|  588 MB | 0.0% |        06:10 | frontend_server.dart.snapshot --sdk-root <path>/ --incremental --target=dartdevc --experimental-emit-debug-metadata -DFLUTTER_WEB_AUTO_DETECT=true -DFLUTTER_WEB_CANVASKIT_URL=https:<path>/ --output-dill <path>/app.dill --packages <path>/package_config.json -Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts --track-widget-creation --filesystem-root <path>/flutter_tools.57n5xj --filesystem-scheme org-dartlang-app --initialize-from-dill build/dd790fb8357d75a1d04c81b76e13c123.cache.dill.track.dill --platform file:<path>/ddc_outline_sound.dill --verbosity=error --sound-null-safety |

</details>

<details>

<summary><strong>Output from 'flutter doctor'</strong></summary>

`/Users/robintre/flutter/bin/flutter doctor -v`

```text
[✓] Flutter (Channel stable, 3.16.3, on macOS 14.1.2 23B2091 darwin-arm64, locale fr-CA)
    • Flutter version 3.16.3 on channel stable at /Users/robintre/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b0366e0a3f (15 hours ago), 2023-12-05 19:46:39 -0800
    • Engine revision 54a7145303
    • Dart version 3.2.3
    • DevTools version 2.28.4

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/robintre/Library/Android/sdk
    • Platform android-34-ext8, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A507
    • CocoaPods version 1.14.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] VS Code (version 1.84.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.78.0

[✓] Connected device (3 available)
    • iPhone 15 Pro Max (mobile) • 84075265-E30E-4DAE-8DB3-332AF6E0B4AE • ios            • com.apple.CoreSimulator.SimRuntime.iOS-17-0 (simulator)
    • macOS (desktop)            • macos                                • darwin-arm64   • macOS 14.1.2 23B2091 darwin-arm64
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 120.0.6099.62

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

My file launch.json in .vscode
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "flutter_application_empty",
            "request": "launch",
            "type": "dart"
        },
        {
            "name": "flutter_application_empty (profile mode)",
            "request": "launch",
            "type": "dart",
            "flutterMode": "profile"
        },
        {
            "name": "flutter_application_empty (release mode)",
            "request": "launch",
            "type": "dart",
            "flutterMode": "release"
        }
    ]
}

my setting.json  in .vscode
{
    "editor.bracketPairColorization.enabled": true,
    "editor.guides.bracketPairs": "active",
    "dart.previewFlutterUiGuides": true,
    "dart.previewFlutterUiGuidesCustomTracking": true,
    "dart.showGettersInDebugViews": true,
    "workbench.tree.renderIndentGuides": "always",
    "debug.allowBreakpointsEverywhere": true,
    "java.configuration.updateBuildConfiguration": "disabled"
}

**Comment by Lerobindesbois** [comment] 2023-12-07 00:03
same bug ?

https://github.com/dart-lang/webdev/issues/2297

**Comment by DanTup** [comment] 2023-12-07 10:31
Yep, looks like the same issue to me. I think the issue is a DWDS issue not handling nulls correctly. The exception is being caught and wrapped here:

https://github.com/dart-lang/webdev/blob/63e09e5060813a971ec0f95472613d6958f75b95/dwds/lib/src/utilities/shared.dart#L44

I'll close this as a dupe of that, but I'll subscribe to that issue so if it turns out to be something Dart-Code is doing wrong, I'll re-open this. Thanks!

**Closed by DanTup** 2023-12-07 10:31 UTC
Labels: is bug

**Comment by Lerobindesbois** [comment] 2023-12-07 18:57
Thank you for your response much appreciated
