### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by carlgaussrugero** [Dart-Code/Dart-Code#1805] opened 2019-06-18 22:48 UTC
- Issue Type: `Performance`
- Extension Name: `dart-code`
- Extension Version: `3.1.0`
- OS Version: `Windows_NT x64 10.0.17134`
- VSCode version: `1.35.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\Carl Gauss Rugero\Dart-Code.dart-code-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by DanTup** [comment] 2019-06-19 06:54
> ⚠️ Make sure to attach this file from your home-directory:
> ⚠️C:\Users\Carl Gauss Rugero\Dart-Code.dart-code-unresponsive.cpuprofile.txt

You need to attach this file in order for us to investigate. I suspect this is a duplicate of #1628 but I can't say without the profile.

Did you see this immediately after opening your project?

**Comment by carlgaussrugero** [comment] 2019-06-19 08:14
Yes , I confirm. After opening my  project, I saw this link.

Le 19 juin 2019 08:54, Danny Tuppeny <notifications@github.com> a écrit :

⚠️ Make sure to attach this file from your home-directory:
⚠️C:\Users\Carl Gauss Rugero\Dart-Code.dart-code-unresponsive.cpuprofile.txt

You need to attach this file in order for us to investigate. I suspect this is a duplicate of #1628<https://github.com/Dart-Code/Dart-Code/issues/1628> but I can't say without the profile.

Did you see this immediately after opening your project?

**Comment by DanTup** [comment] 2019-06-19 08:25
Ok great, then I'll close this as a dupe of #1628.

There's a beta build of the next version with the fixes here:

https://github.com/Dart-Code/Dart-Code/releases

**Closed by DanTup** 2019-06-19 08:25 UTC
Labels: awaiting info
