### ISSUE TITLE
VSCode Extension fails to re-analyze when changing branches

### ISSUE THREAD

**Issue by mentoc3000** [Dart-Code/Dart-Code#2329] opened 2020-03-31 12:22 UTC
When switching between branches where files are moved between directories, VSCode Dart extension fails to recognize the change and shows errors, necessitating reloading VSCode.

**Steps to reproduce**
1. Create a new git repository
1. Add `foo.dart`
```dart
class Foo {}
```
3. Add `bar.dart`
```dart
import 'foo.dart';
class Bar {
  Foo foo;
}
```
4. Commit changes to `master`
5. Create `develop` branch off of `master`
7. Move `./foo.dart` to `./foo/foo.dart` and update import path in `bar.dart`
8. Commit changes to `develop`
9. Checkout master branch

**System Information**
MacOS Catalina 10.15.3
VSCode 1.43.2
Dart 2.8.0-dev.18.0
Dart Code Extension 3.8.1

**Comment by DanTup** [comment] 2020-04-06 09:51
Thanks for the report! A similar issue came up before (#269) but wasn't reproduced on a new build. I was able to repro with the instructions once, but while trying to capture logs, I'm no longer able to. I can reliable reproduce an issue I've raised at https://github.com/dart-lang/sdk/issues/41350 but I'm not sure if it's the cause of this (it seems like the opposite - you'd end up missing the error, rather than an extra error).

Can you reproduce this with the instrumentation log enabled ([`dart.analyzerInstrumentationLogFile`](https://dartcode.org/docs/settings/#dartanalyzerinstrumentationlogfile))? I'm wondering if it's a race and the logging is affecting the timing.

**Comment by mentoc3000** [comment] 2020-04-06 17:00
Thanks for looking into this! I was able to reproduce it while logging. Here's the [log file](https://github.com/Dart-Code/Dart-Code/files/4439767/log.txt).

**Comment by DanTup** [comment] 2020-04-08 14:24
This log doesn't seem to include any file system watch events at all. I wonder whether the overlays are complicating things.

Does it reproduce any differently if you don't have the files open (and visible in your editor) when you change git branch? And are you changing using the VS Code git client, or a terminal?

**Comment by mentoc3000** [comment] 2020-04-10 20:57
I don't reproduce this issue when I change branches while the files are closed. Once I reopen them after switching branches there is no error. I do reproduce this error both when using Git Lens in VS Code and in the terminal (in VS Code).

**Comment by DanTup** [comment] 2020-04-16 07:18
A fix has been made in https://github.com/dart-lang/watcher/issues/83 that fixes some file watcher events being lost when a modified folder is a prefix of a file. I'll ping you once the fix is available in an SDK so you can test if it solves this for you (I'm not having much look reproducing it now, even without the fix).

**Comment by DanTup** [comment] 2020-04-23 08:08
The watcher change has rolled into the Dart SDK, so for a non-Flutter project you could test using the nightly here:

http://gsdview.appspot.com/dart-archive/channels/be/raw/latest/sdk/

For Flutter, you'll need to wait for that SDK to be rolled into Flutter.

If you can still reproduce any issues like this with that fix, please let me know!

**Comment by DanTup** [comment] 2020-04-27 12:57
If I'm reading the hashes correctly, I think this change is in the Flutter `master` channel now, so if you're using that (and have pulled latest) I think you'll have the fix.

If you're still able to produce these sorts of errors with that code, do post back (or file a new issue with repro). Thanks!

**Closed by DanTup** 2020-04-27 12:57 UTC
Labels: upstream in dart / flutter
