### ISSUE TITLE
Recognize multi-line TODO comments

### ISSUE THREAD

**Issue by timsneath** [Dart-Code/Dart-Code#3030] opened 2020-12-22 17:30 UTC
It's great that we [recognize](https://github.com/Dart-Code/Dart-Code/issues/3010) `// TODO:`! It would be even awesomer if we were able to concatenate multi-line TODO comments. Right now they're cut off at the first line break, for example:

![image](https://user-images.githubusercontent.com/2319867/102916294-2a17eb00-4438-11eb-8cda-5fa2fe792b00.png)

**Comment by DanTup** [comment] 2020-12-22 17:59
To do(!) this, I think we'd need to make some assumptions about whether the following lines are part of the TODO (as opposed to existing comments the TODO was added above). I had a quick scan through the SDK and mostly what I found seems to be multiline TODOs, but I did see some instances of code that was commented out with a TODO above it:

```dart
// TODO(dantup): Fix this
// if (blah) {
//   brokenFunction();
// }
```

I don't know how common that is generally (and squiggling(?) the full code sample might look bad), of if there are any conventions that could be used to make this distinction clear.

@bwilkerson has this come up/been discussed before?

**Comment by timsneath** [comment] 2020-12-22 18:21
Yeah -- there's some good prior art here, I think. Here's IntelliJ:
https://stackoverflow.com/a/53472479

**Comment by DanTup** [comment] 2020-12-22 18:34
Ah, nice! All the ideas I had (like putting a dash on the end of the TODO line) sucked, but that seems pretty reasonable. If ther are no objections/concerns, I'll take a look. Thanks!

**Comment by bwilkerson** [comment] 2020-12-22 18:37
I've been wanting for a while to make time to implement the IntelliJ semantics, but haven't yet. I'd be happy to have you look at it, though it should be done in a way that will work for both protocols. (IntelliJ users loose this feature when working with Dart code because server overwrites the highlighting.)

**Comment by DanTup** [comment] 2020-12-22 18:51
> I'd be happy to have you look at it, though it should be done in a way that will work for both protocols

Yep, I was thinking it could be implemented in here where it should apply to both:

https://github.com/dart-lang/sdk/blob/d63d5d93a59b370bf5f5c277109110cb67a96b75/pkg/analyzer/lib/src/error/todo_finder.dart#L34

Currently `_scrapeTodoComment` processes a single token (and its caller, `_gatherTodoComments` loops through them), but perhaps `_scrapeTodoComment` could read ahead to append more text, and return the next token to process?

**Comment by bwilkerson** [comment] 2020-12-22 19:13
I agree that `todo_finder.dart` is the right place to implement this. I don't have any strong preference for how it gets implemented. I'm sure you'll figure out what works best when you start working on it.

**Comment by DanTup** [comment] 2021-01-11 18:38
@bwilkerson I've got a rough version of this working:

https://dart-review.googlesource.com/c/sdk/+/178680/

![multi_line_todos](https://user-images.githubusercontent.com/1078012/104223470-94bab600-543b-11eb-8294-78b2b92a26fe.gif)

However there's a case I'm unsure how to handle:

```dart
// TODO: aaa
//  a

//  b
```

Here, there are three single line tokens and the 2nd/3rd look like candidates to unwrap (they're both indented extra). Really we don't want to roll over a blank line, however I can't see an easy way from the tokens to know that there's a blank line between (I thought I could compare the end/offsets, however the newlines aren't included so it's not possible to tell the difference between `\n\n` and `\r\n`).

It seems like a bit of an edge case, but there's some code in the SDK that triggered it when testing so it might be common in the wild too:

https://github.com/dart-lang/sdk/blob/d63d5d93a59b370bf5f5c277109110cb67a96b75/pkg/analyzer/test/src/lint/io_test.dart#L15-L17

Is there an easy way I could detect this?

**Comment by bwilkerson** [comment] 2021-01-11 19:18
If you have access to an instance of `LineInfo` then it can tell you which line each comment is on. That's the easiest way.

**Comment by DanTup** [comment] 2021-01-11 19:22
I thought I didn't, but turns out I do from the `CompilationUnit`. Thanks!

**Comment by DanTup** [comment] 2021-01-19 10:24
This landed in https://github.com/dart-lang/sdk/commit/6c33457014ef6b3ceef2f30b342c8a48589724d5 and should be available in Flutter master now. Do let me know if you spot any places where it doesn't do what you'd expect!

**Closed by DanTup** 2021-01-19 10:24 UTC
Labels: in editor, in lsp/analysis server, is enhancement

**Comment by DanTup** [comment] 2022-09-14 13:30
@CartmanGD are you referring to the blue colouring? I think you may have another extension installed that's doing that. The change I made above is for range reported on the diagnostics (which show on the Problems window, and usually have a squiggle under the text).

I can't see the squiggle in your screenshot, so can you check whether you have this setting enabled in VS Code:

<img width="634" alt="Screenshot 2022-09-14 at 14 29 35" src="https://user-images.githubusercontent.com/1078012/190167294-f98e4fea-1295-4440-ae44-8b6b4609fe78.png">

**Comment by CartmanGD** [comment] 2022-09-15 07:36
Hey @DanTup thanks for replying. I'm using Android Studio, and the colors seem to reflect exactly the todo comment that presented on the Todos list section.

**Comment by CartmanGD** [comment] 2022-09-15 07:43
Hey @DanTup thanks for replying. I'm using Android Studio, and the colors seem to reflect the todo which is presented on the Todos list section.

In other words, the first and second examples are not working in Flutter 3.3.1 (using simple commenting with space `//`). On the other hand, your third and fourth examples work fine using `/* */`.

Code screenshot:
![Screen Shot 2022-09-15 at 10 40 07](https://user-images.githubusercontent.com/110026289/190345020-242c27c7-2887-430a-81e5-d2e372e3f750.png)

Screenshot of the TODO list section on Android Studio:
![Screen Shot 2022-09-15 at 10 40 28](https://user-images.githubusercontent.com/110026289/190345089-b1e74560-15ea-445e-8655-1b717df4d679.png)

As you can see, simple commenting `//` does not present the full description.

**Comment by DanTup** [comment] 2022-09-15 09:11
@CartmanGD ah, gotcha. I thought it was VS Code (there are some extensions that colour TODOs and other comments based on prefix, but they find their own ranges).

Do you see a difference if you capitalize `TODO`? For me, I only seem to get diagnostics when it's uppercase which makes me wonder if what you're seeing is coming from the IDE itself rather than the analysis server (see https://www.jetbrains.com/help/idea/using-todo.html).

<img width="294" alt="Screenshot 2022-09-15 at 10 11 17" src="https://user-images.githubusercontent.com/1078012/190364657-ff0786b6-359b-4645-b51f-6be552f2d35a.png">

**Comment by CartmanGD** [comment] 2022-09-16 21:19
There is no difference with capitalization, also I'm not using that "using-todo" plugin, so I assume it's from the IDE

**Comment by DanTup** [comment] 2022-09-20 15:30
@CartmanGD as far as I can tell, that is built-in functionality in IntelliJ/Android Studio and not a plugin. I was able to reproduce this. I created the following file:

```dart
void f() {
  // TODO: Capitalized
  //  across multiple lines

  // todo: first and second examples
  //  there is another space
  //  there is another space

  /*
    todo: third and fourth examples
     there is another space
     there is another space
   */
}
```

In the editor it looks like yours:

<img width="502" alt="Screenshot 2022-09-20 at 16 25 45" src="https://user-images.githubusercontent.com/1078012/191299485-41b4b8e7-8dd9-4eb5-8d1f-0b5cd6ee5e93.png">

However if I log the server traffic, I only see this:

```js
{
	"event": "analysis.errors",
	"params": {
		"file": "/Users/danny/Desktop/dart_sample/lib/todos.dart",
		"errors": [
			{
				"severity": "INFO",
				"type": "TODO",
				"location": {
					"file": "/Users/danny/Desktop/dart_sample/lib/todos.dart",
					"offset": 16,
					"length": 45,
					"startLine": 2,
					"startColumn": 6,
					"endLine": 3,
					"endColumn": 28
				},
				"message": "TODO: Capitalized across multiple lines",
				"code": "todo",
				"hasFix": false
			}
		]
	}
}
```

This only includes the capitalized TODO, and its range does span both lines. So as far as I can tell, the Dart server is providing the correct ranges to Android Studio (at least for capitalized TODOs), but Android Studio is doing its own rendering.

I do have the setting described above ticked:

<img width="776" alt="Screenshot 2022-09-20 at 16 27 56" src="https://user-images.githubusercontent.com/1078012/191300031-ba03d5e5-ee87-43e0-a0e9-ac24f8c263cd.png">

But it doesn't seem to work as expected. Unfortunately this seems like an IntelliJ/Android Studio problem and not something that can be fixed in the Dart server (at least as far as I know.. but maybe @alexander-doroshko would be able to confirm this).

**Comment by alexander-doroshko** [comment] 2022-09-20 16:13
I can confirm that this is controlled by the Dart plugin. The feature is tracked as https://youtrack.jetbrains.com/issue/WEB-34694/.

**Comment by DanTup** [comment] 2022-09-20 16:46
@alexander-doroshko Ah got it, thanks!
