### ISSUE TITLE
All Breakpoints appear as unverified when debug target is running

### ISSUE THREAD

**Issue by dedvalson** [Dart-Code/Dart-Code#4745] opened 2023-09-15 13:49 UTC
I see this issue starting with Rev 3.72.0. It seems unlikely to be an actual bug but I am at a loss as of how to fix it. Is there a better place to report issues like this?

When I set breakpoints before running a Flutter App they appear as normal.  But as soon as I start debugging the app they all change to the white circle (unverified breakpoint). However they still work properly. If I stop the debug they all return to normal (red dot).

This takes place even in a newly created "Hello World" Flutter App, as well as all of my other apps.

I do not see any similar issues in Android Studio, though I don't know if it even has "unverified" breakpoints.

Here is the info from VSCode:

```
Version: 1.82.2 (user setup)
Commit: abd2f3db4bdb28f9e95536dfa84d8479f1eb312d
Date: 2023-09-14T05:55:25.390Z
Electron: 25.8.1
ElectronBuildId: 23779380
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.19045
```

I am currently running DartCode version 3.72.2

Here is the result from flutter doctor:

```
flutter doctor -v
[√] Flutter (Channel stable, 3.13.4, on Microsoft Windows [Version 10.0.19045.3324], locale en-US)
    • Flutter version 3.13.4 on channel stable at c:\Src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 367f9ea16b (2 days ago), 2023-09-12 23:27:53 -0500
    • Engine revision 9064459a8b
    • Dart version 3.1.2
    • DevTools version 2.25.0

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Don\AppData\Local\Android\sdk
    • Platform android-33, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Community 2019 16.6.2)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.6.30204.135
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 2022.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)

[√] IntelliJ IDEA Community Edition (version 2018.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2018.3.3
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin version 183.5153.38

[√] VS Code (version 1.82.2)
    • VS Code at C:\Users\Don\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.34.0

[√] Connected device (4 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 10 (API 29) (emulator)
    • Windows (desktop)                  • windows       • windows-x64    • Microsoft Windows [Version 10.0.19045.3324]
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 116.0.5845.180
    • Edge (web)                         • edge          • web-javascript • Microsoft Edge 113.0.1774.42

[√] Network resources
    • All expected network resources are available.

• No issues found!
```

**Comment by DanTup** [comment] 2023-09-15 15:32
This is intended (although perhaps not very intuitive) behaviour.

There's an open issue about this at https://github.com/Dart-Code/Dart-Code/issues/4734 and some discussion about possibly improving this for DAP/VS Code at https://github.com/microsoft/debug-adapter-protocol/issues/425.

I'll close this one as a dupe of https://github.com/Dart-Code/Dart-Code/issues/4734. Thanks!

**Closed by DanTup** 2023-09-15 15:32 UTC
