### ISSUE TITLE
Flutter lightbulb completions are formatting weird.

### ISSUE THREAD

**Issue by Skylled** [Dart-Code/Dart-Code#306] opened 2017-05-19 13:43 UTC
![Flutter lightbulbs](https://zippy.gfycat.com/SillyPlushFrillneckedlizard.gif)

The spacing is chaotic, excess new lines where they aren't needed, etc.

I'll tackle this one in a few. Just wanted to document it first.

**Comment by Skylled** [comment] 2017-05-19 13:58
Oh wow, are these code assists coming straight from the analyzer?
Looks like it's an analyzer problem, not a Dart-Code problem.

**Comment by DanTup** [comment] 2017-05-19 14:36
Yeah, these do come from the analyzer, though the few I tried didn't seem to do this. Might be worth trying to get the log that comes back when you execute this to see whether the response from the analyzer is bad or something is happening in the Code side.

If you set `dart.analyzerLogFile` to a full path in your settings (you won't get intellisense for it and it'll say it's not valid, but it is) then traffic to/from the analyzer will be logged. If you invoke this and then look for the response, it'll show whether the response from the analyzer was bad or whether we've messed something up after that.

@abarth @bwilkerson If this is coming back bad from the analyzer, is this something for the flutter or sdk repos? I'm not entirely sure how these things are implemented.

**Comment by bwilkerson** [comment] 2017-05-19 14:42
They're all implemented in analysis server at the moment, so that would be an SDK issue.

@Skylled Are you using Windows, Mac, or Linux? I'm wondering if we might have an issue with the end-of-line character.

**Comment by Skylled** [comment] 2017-05-19 15:14
@bwilkerson I'm on Windows.
I've already found the [relevant code](https://github.com/dart-lang/sdk/blob/master/pkg/analysis_server/lib/src/services/correction/assist_internal.dart) in the sdk, but I'm not confident in the exact changes to be made.

@DanTup The log's relevant line looks like this:
```
[10:09:17 AM]: <== {"id":"30","result":{"assists":[{"message":"Convert into expression body","edits":[{"file":"c:\\Users\\Kyle\\Source\\Flutter\\Cybertronix\\lib\\cards\\category\\location.dart","fileStamp":0,"edits":[{"offset":3781,"length":237,"replacement":"=> new Container(\r\n      padding: const EdgeInsets.fromLTRB(8.0, 28.0, 8.0, 12.0),\r\n      child: new Card(\r\n        child: new ListView(\r\n          children: new List<Widget>.from(cardLines),\r\n        ),\r\n      ),\r\n    );"}]}],"linkedEditGroups":[]},{"message":"Convert to children:","edits":[{"file":"c:\\Users\\Kyle\\Source\\Flutter\\Cybertronix\\lib\\cards\\category\\location.dart","fileStamp":0,"edits":[{"offset":3889,"length":115,"replacement":"\r\n    new Card(\r  \n          child: new ListView(\r  \n            children: new List<Widget>.from(cardLines),\r  \n          ),\r  \n        ),\r\n]"},{"offset":3889,"length":0,"replacement":"<Widget>["},{"offset":3887,"length":0,"replacement":"ren"}]}],"linkedEditGroups":[]},{"message":"Move widget down","edits":[{"file":"c:\\Users\\Kyle\\Source\\Flutter\\Cybertronix\\lib\\cards\\category\\location.dart","fileStamp":0,"edits":[{"offset":3795,"length":217,"replacement":"new Card(\r\n      child: new Container(\r\n        padding: const EdgeInsets.fromLTRB(8.0, 28.0, 8.0, 12.0),\r\n        child: new ListView(\r\n          children: new List<Widget>.from(cardLines),\r\n        ),\r\n      ),\r\n    )"}]}],"linkedEditGroups":[],"selection":{"file":"c:\\Users\\Kyle\\Source\\Flutter\\Cybertronix\\lib\\cards\\category\\location.dart","offset":4014}},{"message":"Wrap new-expression with new widget","edits":[{"file":"c:\\Users\\Kyle\\Source\\Flutter\\Cybertronix\\lib\\cards\\category\\location.dart","fileStamp":0,"edits":[{"offset":3795,"length":217,"replacement":"new widget(\r\n  child:   new Container(\r  \n        padding: const EdgeInsets.fromLTRB(8.0, 28.0, 8.0, 12.0),\r  \n        child: new Card(\r  \n          child: new ListView(\r  \n            children: new ...
```
I'm not sure how much help that is, as the log cuts off after 2000 characters per line.

I'll look into reducing the repro.

**Comment by DanTup** [comment] 2017-05-19 15:19
If you find the `logTraffic` function in Dart Code you can increase/remove the truncation while testing (though be aware some of the responses can be HUGE).

I think I can see the problem in the first part of the replacement string though:

```js
new Container(\r  \n        padding: const EdgeInsets.fromLTRB(8.0, 28.0, 8.0, 12.0),\r  \n        child: new Card(\r  \n          child: new ListView(\r  \n            children: new ...
```

There appear to be spaces between the `\r` and `\n`; I suspect they're causing a newline each.

**Comment by bwilkerson** [comment] 2017-05-19 15:24
I agree. The problem is almost certainly the extra space. I don't see, off-hand, where that might be happening, though.

**Comment by DanTup** [comment] 2017-05-19 15:26
Nor me; I found what looks like the code for the assist [here](https://github.com/dart-lang/sdk/blob/1040fefdea3d4190a236f1ba95ae0ca21f254899/pkg/analysis_server/lib/src/services/correction/assist_internal.dart#L1760) but it doesn't seem to deal with the formatting/indenting in there.

Do you want an issue raising in sdk for investigation? Any additional info we can gather that'll help?

**Comment by Skylled** [comment] 2017-05-19 15:30
Reduced repro to
```
import 'package:flutter/material.dart';

Widget x = new Container(
);
```

with a new log containing
```
[10:25:53 AM]: <== {"id":"49","result":{"assists":[{"message":"Wrap new-expression with new widget","edits":[{"file":"c:\\Users\\Kyle\\Source\\Flutter\\Cybertronix\\lib\\reports.dart","fileStamp":0,"edits":[{"offset":54,"length":17,"replacement":"new widget(\r\n  child:   new Container(\r  \n  ),\r\n)"}]}],"linkedEditGroups":[{"positions":[{"file":"c:\\Users\\Kyle\\Source\\Flutter\\Cybertronix\\lib\\reports.dart","offset":58}],"length":6,"suggestions":[]},{"positions":[{"file":"c:\\Users\\Kyle\\Source\\Flutter\\Cybertronix\\lib\\reports.dart","offset":69}],"length":5,"suggestions":[]}],"selection":{"file":"c:\\Users\\Kyle\\Source\\Flutter\\Cybertronix\\lib\\reports.dart","offset":103}}]}}
```

Same issue. It seems to be an issue between newlines already in the code and the indentation, almost as though an indent is being placed between existing `\r` and `\n`.

**Comment by DanTup** [comment] 2017-05-19 15:38
Ah, I guess the indenting is dynamic (the indenting from the assist needs to be increased based on the indent within your code). I guess the code that's rewriting the indents isn't considering two-character newlines for Windows (or they shouldn't be `\r\n` at that point, but are)?

**Comment by bwilkerson** [comment] 2017-05-19 15:53
It's likely to be in this [if statement](https://github.com/dart-lang/sdk/blob/1040fefdea3d4190a236f1ba95ae0ca21f254899/pkg/analysis_server/lib/src/services/correction/assist_internal.dart#L1773) where the indent is being replaced.

**Comment by DanTup** [comment] 2017-05-19 16:15
Yeah, that looks likely. I think if `eol` is two characters, the `lastIndexOf` will return the first, then `util.getLinePrefix` will only read up to the first (the `\r`) and then the replacements will end up replacing `{whitespace}\r` with `{whitespace}\r{new whitespace}` instead of including the `\n`.

The fix is possibly to change:

```dart
int newlineIdx = newExprSrc.lastIndexOf(eol);
```

to

```dart
int newlineIdx = newExprSrc.lastIndexOf(eol) + eol.length - 1;
```

Though the `-1` is weird, so maybe better to remove it and the `+ 1` further down (though the `-= 1` condition may need tweaking too.

If you want an issue raising in sdk, let me know!

**Comment by stevemessick** [comment] 2017-05-19 17:10
Thanks for reporting this problem! I had temporary dementia, apparently, when writing the code. Here's the fix:
```dart
      int eolLen = eol.length;
      if (newlineIdx == newExprSrc.length - eolLen) {
        newlineIdx -= eolLen;
      }
      String indentOld =
          utils.getLinePrefix(newExpr.offset + eolLen + newlineIdx);
```

**Comment by DanTup** [comment] 2017-05-19 17:12
Yeah, that looks better :) @stevemessick Are you able to commit the fix? I could send a PR with that pasted in but I don't want it to look like I know what I'm doing (and I don't have anything set up to run tests etc.!)

**Comment by stevemessick** [comment] 2017-05-19 17:14
In progress:
https://codereview.chromium.org/2892963002/

**Comment by DanTup** [comment] 2017-05-19 17:14
Great, thanks! 👍

**Comment by DanTup** [comment] 2017-05-19 17:15
Btw, I never got things building from source, but if you can send an analyzer snapshot we could give it a test.

(ofc, if you need to generate the snapshot on Windows, then that probably doesn't help you at all!)

**Comment by stevemessick** [comment] 2017-05-19 17:20
I'm working remotely today, with low bandwidth. I'll ask someone at the office for help once the patch is committed.

**Comment by DanTup** [comment] 2017-07-02 11:55
Sorry for the delay in testing this! The issue is resolved now. The indenting isn't perfect (note the `MaterialApp` construct args are at the same level as `child:` which is misleading), but really that's an issue to raise with SDK. In Dart Code once you fix the compile error (replace `widget`) the auto-formatting will fix things.

![Indent](https://user-images.githubusercontent.com/1078012/27769608-7d0391e4-5f25-11e7-96b6-748d57031d3a.png)

**Closed by DanTup** 2017-07-02 11:55 UTC
Labels: area: flutter, bug, fixed externally: dart
