### ISSUE TITLE
Analysis server hangs when import/part contains illegal windows filenames

### ISSUE THREAD

**Issue by DrecDroid** [Dart-Code/Dart-Code#156] opened 2016-09-02 19:57 UTC
When editing `import` or `part` statements the analyzer stucks and autocomplete and code analyzing stop working.

Example:
```
part 'math/Matrix.dart' //If I repeatedly erase and write, sometimes It makes the analyzer to get stuck.
```

Not only in v0.10.0, also in v0.9.0, I don't know if in previous versions.

**Comment by DanTup** [comment] 2016-09-02 20:00
If you add a log file path to your settings like this:

```
"dart.analyzerLogFile": "M:\\analyzer.log",
```

This will log all data back and forth to the analysis service. If you reproduce the issue with that enabled, do the last events reveal anything (such as a server error notification)?

**Comment by DrecDroid** [comment] 2016-09-02 21:37
Can't reproduce in a clean small project. But in my current project I get this.
```
[16:13:33]: <== {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
[16:13:33]: ==> {"id":"34","method":"analysis.updateContent","params":{"files":{"d:\\demo\lib\src\px.dart":{"type":"change","edits":[{"offset":339,"length":1,"replacement":"","id":""}]}}}}
[16:13:33]: ==> {"id":"35","method":"completion.getSuggestions","params":{"file":"d:\\demo\lib\src\px.dart","offset":339}}
[16:13:33]: <== {"id":"34","result":{}}
[16:13:33]: <== {"id":"35","result":{"id":"9"}}
[16:13:33]: <== {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
[16:13:33]: <== {"event":"analysis.errors","params":{"file":"d:\\demo\lib\src\px.dart","errors":[]}}
[16:13:34]: ==> {"id":"36","method":"analysis.updateContent","params":{"files":{"d:\\demo\lib\src\px.dart":{"type":"change","edits":[{"offset":338,"length":1,"replacement":"","id":""}]}}}}
[16:13:34]: ==> {"id":"37","method":"completion.getSuggestions","params":{"file":"d:\\demo\lib\src\px.dart","offset":338}}
[16:13:59]: ==> {"id":"38","method":"analysis.setPriorityFiles","params":{"files":["d:\\demo\lib\src\px.dart"]}}
[16:13:59]: ==> {"id":"39","method":"analysis.setPriorityFiles","params":{"files":["d:\\demo\lib\src\px.dart"]}}
[16:13:59]: ==> {"id":"40","method":"analysis.setPriorityFiles","params":{"files":["d:\\demo\lib\src\px.dart"]}}
[16:14:04]: ==> {"id":"41","method":"analysis.setPriorityFiles","params":{"files":["d:\\demo\lib\src\px.dart"]}}
[16:14:04]: ==> {"id":"42","method":"analysis.setPriorityFiles","params":{"files":["d:\\demo\lib\src\px.dart"]}}
[16:14:08]: ==> {"id":"43","method":"analysis.setPriorityFiles","params":{"files":["d:\\demo\lib\src\px.dart"]}}
[16:14:09]: ==> {"id":"44","method":"analysis.setPriorityFiles","params":{"files":["d:\\demo\lib\src\px.dart"]}}
[16:14:18]: ==> {"id":"45","method":"analysis.setPriorityFiles","params":{"files":["d:\\demo\lib\src\px.dart"]}}
[16:14:18]: ==> {"id":"46","method":"analysis.setPriorityFiles","params":{"files":["d:\\demo\lib\src\px.dart"]}}
[16:16:00]: ==> {"id":"47","method":"analysis.setPriorityFiles","params":{"files":["d:\\demo\lib\src\px.dart"]}}
[16:16:01]: ==> {"id":"48","method":"analysis.setPriorityFiles","params":{"files":["d:\\demo\lib\src\px.dart"]}}
[16:16:03]: ==> {"id":"49","method":"analysis.updateContent","params":{"files":{"d:\\demo\lib\src\px.dart":{"type":"change","edits":[{"offset":338,"length":0,"replacement":"n","id":""}]}}}}
[16:16:03]: ==> {"id":"50","method":"completion.getSuggestions","params":{"file":"d:\\demo\lib\src\px.dart","offset":339}}
[16:16:03]: ==> {"id":"51","method":"analysis.updateContent","params":{"files":{"d:\\demo\lib\src\px.dart":{"type":"change","edits":[{"offset":339,"length":0,"replacement":"t","id":""}]}}}}
[16:16:03]: ==> {"id":"52","method":"analysis.updateContent","params":{"files":{"d:\\demo\lib\src\px.dart":{"type":"change","edits":[{"offset":340,"length":0,"replacement":"a","id":""}]}}}}
[16:16:04]: ==> {"id":"53","method":"analysis.updateContent","params":{"files":{"d:\\demo\lib\src\px.dart":{"type":"change","edits":[{"offset":341,"length":0,"replacement":"i","id":""}]}}}}
[16:16:04]: ==> {"id":"54","method":"analysis.updateContent","params":{"files":{"d:\\demo\lib\src\px.dart":{"type":"change","edits":[{"offset":342,"length":0,"replacement":"n","id":""}]}}}}
[16:16:04]: ==> {"id":"55","method":"analysis.updateContent","params":{"files":{"d:\\demo\lib\src\px.dart":{"type":"change","edits":[{"offset":343,"length":0,"replacement":"e","id":""}]}}}}
[16:16:04]: ==> {"id":"56","method":"analysis.updateContent","params":{"files":{"d:\\demo\lib\src\px.dart":{"type":"change","edits":[{"offset":344,"length":0,"replacement":"r","id":""}]}}}}
[16:16:05]: ==> {"id":"57","method":"analysis.updateContent","params":{"files":{"d:\\demo\lib\src\px.dart":{"type":"change","edits":[{"offset":345,"length":0,"replacement":".","id":""}]}}}}
[16:16:05]: ==> {"id":"58","method":"completion.getSuggestions","params":{"file":"d:\\demo\lib\src\px.dart","offset":346}}
[16:16:05]: ==> {"id":"59","method":"analysis.updateContent","params":{"files":{"d:\\demo\lib\src\px.dart":{"type":"change","edits":[{"offset":346,"length":0,"replacement":"d","id":""}]}}}}
[16:16:05]: ==> {"id":"60","method":"analysis.updateContent","params":{"files":{"d:\\demo\lib\src\px.dart":{"type":"change","edits":[{"offset":347,"length":0,"replacement":"a","id":""}]}}}}
[16:16:05]: ==> {"id":"61","method":"analysis.updateContent","params":{"files":{"d:\\demo\lib\src\px.dart":{"type":"change","edits":[{"offset":348,"length":0,"replacement":"r","id":""}]}}}}
[16:16:05]: ==> {"id":"62","method":"analysis.updateContent","params":{"files":{"d:\\demo\lib\src\px.dart":{"type":"change","edits":[{"offset":349,"length":0,"replacement":"t","id":""}]}}}}
[16:16:07]: ==> {"id":"63","method":"analysis.setPriorityFiles","params":{"files":["d:\\demo\lib\src\px.dart"]}}
[16:16:07]: ==> {"id":"64","method":"analysis.setPriorityFiles","params":{"files":["d:\\demo\lib\src\px.dart"]}}
[16:16:07]: ==> {"id":"65","method":"analysis.setPriorityFiles","params":{"files":["d:\\demo\lib\src\px.dart"]}}
[16:16:08]: ==> {"id":"66","method":"analysis.setPriorityFiles","params":{"files":["d:\\demo\lib\src\px.dart"]}}
[16:16:08]: ==> {"id":"67","method":"analysis.setPriorityFiles","params":{"files":["d:\\demo\lib\src\px.dart"]}}
[16:17:01]: ==> {"id":"68","method":"analysis.setPriorityFiles","params":{"files":["d:\\demo\lib\src\px.dart"]}}
[16:17:01]: ==> {"id":"69","method":"analysis.setPriorityFiles","params":{"files":["d:\\demo\lib\src\px.dart"]}}
[16:17:05]: ==> {"id":"70","method":"analysis.setPriorityFiles","params":{"files":["d:\\demo\lib\src\px.dart"]}}
[16:17:05]: ==> {"id":"71","method":"analysis.setPriorityFiles","params":{"files":["d:\\demo\lib\src\px.dart"]}}
[16:17:47]: ==> {"id":"72","method":"analysis.setPriorityFiles","params":{"files":["d:\\demo\lib\src\px.dart"]}}
[16:17:47]: ==> {"id":"73","method":"analysis.setPriorityFiles","params":{"files":["d:\\demo\lib\src\px.dart"]}}
[16:18:37]: ==> {"id":"74","method":"analysis.setPriorityFiles","params":{"files":["d:\\demo\lib\src\px.dart"]}}
[16:18:37]: ==> {"id":"75","method":"analysis.setPriorityFiles","params":{"files":["d:\\demo\lib\src\px.dart"]}}
[16:18:39]: ==> {"id":"76","method":"analysis.setPriorityFiles","params":{"files":["d:\\demo\lib\src\px.dart"]}}
[16:18:39]: ==> {"id":"77","method":"analysis.setPriorityFiles","params":{"files":["d:\\demo\lib\src\px.dart"]}}
[16:18:47]: ==> {"id":"78","method":"analysis.setPriorityFiles","params":{"files":["d:\\demo\lib\src\px.dart"]}}
[16:18:47]: ==> {"id":"79","method":"analysis.setPriorityFiles","params":{"files":["d:\\demo\lib\src\px.dart"]}}
[16:23:29]: ==> {"id":"80","method":"analysis.setPriorityFiles","params":{"files":["d:\\demo\lib\src\px.dart"]}}
[16:23:30]: ==> {"id":"81","method":"analysis.setPriorityFiles","params":{"files":["d:\\demo\lib\src\px.dart"]}}
[16:23:35]: ==> {"id":"82","method":"analysis.setPriorityFiles","params":{"files":["d:\\demo\lib\src\px.dart"]}}
[16:23:35]: ==> {"id":"83","method":"analysis.setPriorityFiles","params":{"files":["d:\\demo\lib\src\px.dart"]}}
[16:23:36]: ==> {"id":"84","method":"analysis.setPriorityFiles","params":{"files":["d:\\demo\lib\src\px.dart"]}}
[16:23:36]: ==> {"id":"85","method":"analysis.setPriorityFiles","params":{"files":["d:\\demo\lib\src\px.dart"]}}
[16:23:41]: ==> {"id":"86","method":"analysis.setPriorityFiles","params":{"files":["d:\\demo\lib\src\px.dart"]}}
[16:23:41]: ==> {"id":"87","method":"analysis.setPriorityFiles","params":{"files":["d:\\demo\lib\src\px.dart"]}}
[16:23:42]: ==> {"id":"88","method":"analysis.setPriorityFiles","params":{"files":["d:\\demo\lib\src\px.dart"]}}
[16:23:43]: ==> {"id":"89","method":"analysis.setPriorityFiles","params":{"files":["d:\\demo\lib\src\px.dart"]}}
[16:24:13]: ==> {"id":"90","method":"analysis.setPriorityFiles","params":{"files":["d:\\demo\lib\src\px.dart"]}}
[16:24:13]: ==> {"id":"91","method":"analysis.setPriorityFiles","params":{"files":["d:\\demo\lib\src\px.dart"]}}
[16:24:17]: ==> {"id":"92","method":"analysis.setPriorityFiles","params":{"files":["d:\\demo\lib\src\px.dart"]}}
[16:24:17]: ==> {"id":"93","method":"analysis.setPriorityFiles","params":{"files":["d:\\demo\lib\src\px.dart"]}}
[16:25:32]: ==> {"id":"94","method":"analysis.setPriorityFiles","params":{"files":["d:\\demo\lib\src\px.dart"]}}
[16:25:32]: ==> {"id":"95","method":"analysis.setPriorityFiles","params":{"files":["d:\\demo\lib\src\px.dart"]}}
[16:29:09]: ==> {"id":"96","method":"analysis.setPriorityFiles","params":{"files":["d:\\demo\lib\src\px.dart"]}}
[16:29:09]: ==> {"id":"97","method":"analysis.setPriorityFiles","params":{"files":["d:\\demo\lib\src\px.dart"]}}
[16:29:42]: ==> {"id":"98","method":"analysis.setPriorityFiles","params":{"files":["d:\\demo\lib\src\px.dart"]}}
[16:30:26]: ==> {"id":"99","method":"analysis.setPriorityFiles","params":{"files":["d:\\demo\lib\src\px.dart"]}}
[16:30:26]: ==> {"id":"100","method":"analysis.setPriorityFiles","params":{"files":["d:\\demo\lib\src\px.dart"]}}
[16:32:32]: ==> {"id":"101","method":"analysis.setPriorityFiles","params":{"files":["d:\\demo\lib\src\px.dart"]}}
```

**Comment by DanTup** [comment] 2016-09-02 22:15
There seem to be an awful lot of `setPriorityFiles` calls there! Shouldn't have any real effect but doesn't seem normal.

I'll have a play around and see if I can repro on some large projects. Obviously if you're able to repro in a project you can share at all, that would be tremendously useful!

Could you also confirm which version of VS Code (Stable 1.4?) and Dart SDK your using (this is shown on right side of status bar).

**Comment by DrecDroid** [comment] 2016-09-02 22:49
I'm in other pc an splitted my project, the same happened. I'm using vsCode 1.4.0 and Dart 1.19.0 but this happens also in Dart 1.18.1.

In this new project I have no external dependencies.

I have this line:

```
part 'src/core/display/Container.dart';
```

When I erase the line to (because for example I want to point to other part or I copied the line and just want to change the last part):

```
part 'src/core/display/Con';
```
It hangs.

**Comment by DanTup** [comment] 2016-09-03 16:45
We're going to add a flag that allows us to access Observatory for the analysis server (this will allow suspending of execution and reviewing the stack trace for what it was doing, which might help the Dart Team understand what's gone wrong). I've raised #161 for this and will try to do it in the next few days.

In the meantime, here's some things to try:

1. See if the Dart process is still running (it'll show as `dart.exe` in Task Manager on Windows; or `dart` in the equiv on Linux/Mac).. If you have other Dart processes running, I'm not sure how easily you'll be able to identify the one running the analysis server!

2. We already have the ability to access the analysis server diagnostics app which may or may not help. To enable, you need to add a new option called `dart.analyzerDiagnosticsPort` to your VS Code settings. This should be a numeric value and will be used as a port number. Restart Code and open the Dart project and then in a browser go to `localhost:{portNumber}/status` which may give some additional info:

> The main status page, under "Analysis Domain" will show the status of analysis (which project was being analyzed at the time the page was produced). If you click on one of the projects being analyzed, at the bottom of the page you'll find a listing of all of the exceptions that were thrown during analysis

Post back anything useful you find, or questions if you need more help. Don't forget to remove the VS Code settings once finished and you don't need them.

I'll post back here once I've been able to add an option for adding Observatory for the analysis server which might be able to give us additional info.

Sorry for the bother, and thanks for taking time to send the details! :+1:

**Comment by DrecDroid** [comment] 2016-09-03 17:01
I've got this:
I can run the diagnostics server, but when reproducing the error the server also hangs.

Also, I've found that when saving the file when the analyzer breaks and then reload de window, the analyzer breaks instantly, no need to erase or write something.

**Comment by DrecDroid** [comment] 2016-09-03 17:09
Ok, I got it, the analyzer breaks any time I write the string 'con' with `import` or `part`.

```
import 'con' //breaks instantly;
import 'package:demo/con' //breaks also, for example if I trying to write connection.dart it will fail.
```

**Comment by DanTup** [comment] 2016-09-03 17:11
Excellent debugging! I should've tried that sooner - you're on Windows right? You can't have files with that name on Windows and I guess the AS is chocking on something relating to that. I'll pass the info on and hopefully can be fixed in an upcoming Dart SDK release :)

**Comment by DrecDroid** [comment] 2016-09-03 17:20
So the problem is in Dart SDK?, I don't know, but probably could be checked before passing the string to the analyzer.

**Comment by DanTup** [comment] 2016-09-03 17:23
The analysis server (which does all the heavy lifting for Dart Code) is part of the SDK and is developed the Dart Team. We don't parse any Dart directly, so this will need fixing in the SDK.

Most Dart IDE integrations work this way; it makes them far easier to build because Google did ask the hard stuff! :)

**Comment by DanTup** [comment] 2016-09-03 18:23
Hmmm, I actually still can't repro this. What version of Windows are you on?

Are you able to create a sample file/project that crashes in this way at startup and attach here?

**Comment by DrecDroid** [comment] 2016-09-03 18:49
Don't need to, just create a single .dart file with the line `import 'con'` or `part 'con'` and it fails instantly.
I'm using Windows 8.1 x64.

**Comment by DanTup** [comment] 2016-09-03 20:06
Great; that actually worked fine for me; not sure what I did wrong earlier.

I've raised a case against the SDK for this here: https://github.com/dart-lang/sdk/issues/27243

**Comment by DanTup** [comment] 2016-09-07 20:45
This is fixed in Dart, I expect it'll be in the v1.20 SDK. Thanks for reporting!

**Comment by DrecDroid** [comment] 2016-09-08 15:14
Thanks :D, It was a nightmare, I don't know how but my project ended with many files stating with `con`.

**Comment by DanTup** [comment] 2016-09-08 16:35
Keeping this open until 1.20 is released as a reminder to put a note in the release notes.

If you hit this while developing and it's annoying, the "Reload Window" command will reload the analysis server (it basically reloads your folder, which is slightly faster than quitting and restarting Code).

**Closed** 2016-10-22 10:19 UTC
Labels: bug, fixed externally: dart 1.20
