### ISSUE TITLE
Compilation fails but no error in editor

### ISSUE THREAD

**Issue by kinex** [Dart-Code/Dart-Code#3506] opened 2021-08-01 18:14 UTC
This "Web safe" code is not valid (does not compile), but no errors are shown in editor:

```dart
import 'dart:io';
import 'package:flutter/foundation.dart';

const isAndroid = !kIsWeb && Platform.isAndroid;
```

The fixed code gives warning "prefer_const_declarations":
```dart
import 'dart:io';
import 'package:flutter/foundation.dart';

late final isAndroid = !kIsWeb && Platform.isAndroid;
```

Dart Code v3.24.2

Flutter 2.2.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision f4abaa0735 (4 weeks ago) • 2021-07-01 12:46:11 -0700
Engine • revision 241c87ad80
Tools • Dart 2.13.4

**Comment by DanTup** [comment] 2021-08-02 09:05
> This "Web safe" code is not valid (does not compile), but no errors are shown in editor:

I can reproduce not getting an error in Flutter stable:

<img width="490" alt="Screenshot 2021-08-02 at 10 01 23" src="https://user-images.githubusercontent.com/1078012/127834440-38f7d041-f45a-4477-b9f1-4a44219cb48d.png">

Which seems incorrect because `isAndroid` is not const:

<img width="689" alt="Screenshot 2021-08-02 at 10 01 41" src="https://user-images.githubusercontent.com/1078012/127834484-39b7abfc-caac-429f-bfb0-0d253459812d.png">

However if I switch to Flutter master, the correct error is reported:

<img width="1080" alt="Screenshot 2021-08-02 at 10 04 40" src="https://user-images.githubusercontent.com/1078012/127834982-e27a80ce-572a-47fb-9850-a2dc56615048.png">

So it appears that this has been fixed in Dart/Flutter and just hasn't made the stable channel yet. I expect it will be resolved in the next stable release.

Thanks!

**Closed** 2021-08-02 09:05 UTC
Labels: fixed in dart / flutter
