### ISSUE TITLE
"Extension causes high cpu load" warnings from VS Code due to slow module loading

### ISSUE THREAD

**Issue by TUKenStone** [Dart-Code/Dart-Code#1628] opened 2019-04-18 07:27 UTC
- Issue Type: `Performance`
- Extension Name: `dart-code`
- Extension Version: `2.25.1`
- OS Version: `Darwin x64 18.5.0`
- VSCode version: `1.33.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`/Users/ken/Dart-Code.dart-code-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by DanTup** [comment] 2019-04-18 07:29
@TUKenStone are you able to attach the file mentioned in your message?

> ⚠️ Make sure to attach this file from your home-directory:
> ⚠️/Users/ken/Dart-Code.dart-code-unresponsive.cpuprofile.txt

**Comment by TUKenStone** [comment] 2019-04-18 07:35
I’m not even sure what’s attaching to my home directory is since it’s already attached at /Users/Ken or ~/ which is my home directory.

**Comment by DanTup** [comment] 2019-04-18 07:58
> I’m not even sure what I need to attach to

@TUKenStone sorry, what I mean was there is a file at `/Users/ken/Dart-Code.dart-code-unresponsive.cpuprofile.txt` that VS Code created when it gave you this warning, and you are supposed to attach it to this GitHub issue. It's a CPU profile of the extension code, which will show what code was running when this happened.

Unfortunately I can't reproduce this issue (though my machine is very fast). I've had a few people raise it in the past, but none have ever attached the CPU profile, so I've never been able to investigate where the time is going.

If you can attach that file (which I believe VS Code has sanitized to ensure there is no personally identifiable info, pathnames, etc.) I can investigate. If you'd rather share it privately, you can email it to logs@dartcode.org.

Thanks!

**Comment by DanTup** [comment] 2019-04-18 08:20
@TUKenStone Thanks! I got the trace, and it looks like the cause is that the extension has lots of files, and the loading and compiling of each is slow (this explains VS Code's push to have extensions bundle their JS recently).

I don't think this is related to the other issue you mentioned though ("Error connecting to the service protocol: HttpException: , uri = http://127.0.0.1:1027/ws"). Can you open another issue about that? We might need to move it to the Flutter repo, but we can do a little debugging first to get more info.

**Comment by DanTup** [comment] 2019-04-18 08:55
I can repro this now - not the warning, but the poor performance at least. It seems to be related to loading `dart_debug_protocol.ts` and all its descendant `require()`s. There are calls to things like `Module._resolveFilename` which take > 250ms (because it goes and reads the JSON for the package). No wonder VS Code wants all the modules bundled. Looks like this will need to be revisited...

![Screenshot 2019-04-18 at 9 53 55 am](https://user-images.githubusercontent.com/1078012/56349199-f2b35e80-61bf-11e9-86e1-ec27623a656d.png)

**Comment by DanTup** [comment] 2019-06-06 14:22
Fixed by #1741.

**Closed by DanTup** 2019-06-06 14:22 UTC
Labels: is performance
