### ISSUE TITLE
"The Dart Analyzer has terminated" loop 

### ISSUE THREAD

**Issue by talent-apps** [Dart-Code/Dart-Code#2756] opened 2020-08-31 06:49 UTC
While using the VSCode Dart extension version **v3.13.2** with VSCode, the Dart Analyzer keeps terminating in a loop:

**VSCode version:**

![Untitled](https://user-images.githubusercontent.com/48091135/91690764-2d2c5a00-eb6f-11ea-8d3f-ea1c296ed030.png)

**Crash message:**

![Untitled2](https://user-images.githubusercontent.com/48091135/91691013-957b3b80-eb6f-11ea-9263-1c4b16b105c9.png)

**Crash log:**
```
[9:44:29 AM] [General] [Error] Cannot call write after a stream was destroyed
Error [ERR_STREAM_DESTROYED] [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
    at doWrite (_stream_writable.js:414:19)
    at writeOrBuffer (_stream_writable.js:402:5)
    at Socket.Writable.write (_stream_writable.js:302:11)
    at b.sendMessage (c:\Users\XXX\.vscode\extensions\dart-code.dart-code-3.13.2\out\dist\extension.js:1:152923)
    at b.sendMessage (c:\Users\XXX\.vscode\extensions\dart-code.dart-code-3.13.2\out\dist…
[9:44:30 AM] [Analyzer] [Info] ==> {"id":"25","method":"analysis.getHover","params":{"file":"XXX.dart","offset":24230},"clientRequestTime":1598856270234}
[9:44:30 AM] [General] [Error] Cannot call write after a stream was destroyed
Error [ERR_STREAM_DESTROYED] [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
    at doWrite (_stream_writable.js:414:19)
    at writeOrBuffer (_stream_writable.js:402:5)
    at Socket.Writable.write (_stream_writable.js:302:11)
    at b.sendMessage (c:\Users\XXX\.vscode\extensions\dart-code.dart-code-3.13.2\out\dist\extension.js:1:152923)
    at b.sendMessage (c:\Users\XXX\.vscode\extensions\dart-code.dart-code-3.13.2\out\dist…
[9:44:39 AM] [Analyzer] [Info] ==> {"id":"26","method":"analysis.setPriorityFiles","params":{"files":[]},"clientRequestTime":1598856279562}
```

**Comment by DanTup** [comment] 2020-08-31 07:52
Is there anything more in the log before the lines you posted?

When does this happen? Is it immediately at startup, or when you do something specific?

**Comment by talent-apps** [comment] 2020-09-01 06:49
The issue doesn't happen as a result of a specific action, it suddenly occurs while working on a flutter project.

**Comment by talent-apps** [comment] 2020-09-01 06:54
More logs:
```
[9:50:21 AM] [VmService] [Info] [Flutter] <== {"jsonrpc":"2.0","method":"streamNotify","params":{"streamId":"Debug","event":{"type":"Event","kind":"PauseException","isolate":{"type":"@Isolate","id":"isolates\/4079229187977411","name":"main","number":"4079229187977411"},"timestamp":1598943022269,"topFrame":{"type":"Frame","kind":"Regular","location":{"type":"SourceLocation","script":{"type":"@Script","fixedId":true,"id":"libraries\/@0150898\/scripts\/dart%3Acore-patch%2Ferrors_patch.dart\/0","uri":"dart:core-patch\/errors_patch…
[9:50:21 AM] [VmService] [Info] [Flutter] ==> {"id":"1673","jsonrpc":"2.0","method":"invoke","params":{"argumentIds":[],"disableBreakpoints":true,"isolateId":"isolates/4079229187977411","selector":"toString","targetId":"objects/1"}}
[9:50:21 AM] [VmService] [Info] [Flutter] <== {"jsonrpc":"2.0", "result":{"type":"@Instance","_vmType":"String","class":{"type":"@Class","fixedId":true,"id":"classes\/80","name":"_OneByteString","_vmName":"_OneByteString@0150898"},"kind":"String","id":"objects\/2","length":254,"valueAsString":"'package:flutter\/src\/animation\/animation_controller.dart': Failed assertion: line 457 pos 7: '_ticker != null': AnimationControl","count":128,"valueAsStringIsTruncated":true},"id":"1673"}
[9:50:21 AM] [VmService] [Info] [Flutter] ==> {"id":"1674","jsonrpc":"2.0","method":"getObject","params":{"isolateId":"isolates/4079229187977411","objectId":"objects/2"}}
[9:50:21 AM] [VmService] [Info] [Flutter] <== {"jsonrpc":"2.0", "result":{"type":"Instance","_vmType":"String","class":{"type":"@Class","fixedId":true,"id":"classes\/80","name":"_OneByteString","_vmName":"_OneByteString@0150898"},"size":272,"fields":[],"kind":"String","id":"objects\/3","length":254,"valueAsString":"'package:flutter\/src\/animation\/animation_controller.dart': Failed assertion: line 457 pos 7: '_ticker != null': AnimationController.forward() called after AnimationController.dispose()\nAnimationController method…
[9:50:21 AM] [VmService] [Info] [Flutter] ==> {"id":"1675","jsonrpc":"2.0","method":"getStack","params":{"isolateId":"isolates/4079229187977411"}}
[9:50:21 AM] [VmService] [Info] [Flutter] <== {"jsonrpc":"2.0", "result":{"type":"Stack","frames":[{"type":"Frame","kind":"Regular","location":{"type":"SourceLocation","script":{"type":"@Script","fixedId":true,"id":"libraries\/@0150898\/scripts\/dart%3Acore-patch%2Ferrors_patch.dart\/0","uri":"dart:core-patch\/errors_patch.dart","_kind":"kernel"},"tokenPos":1483},"function":{"type":"@Function","fixedId":true,"id":"classes\/180\/functions\/_doThrowNew%400150898","name":"_doThrowNew","_vmName":"_doThrowNew@0150898","owner":{"typ…
[9:50:21 AM] [VmService] [Info] [Flutter] ==> {"id":"1676","jsonrpc":"2.0","method":"getObject","params":{"isolateId":"isolates/4079229187977411","objectId":"libraries/@0150898/scripts/dart%3Acore-patch%2Ferrors_patch.dart/0"}}
[9:50:21 AM] [VmService] [Info] [Flutter] <== {"jsonrpc":"2.0", "result":{"type":"Script","class":{"type":"@Class","fixedId":true,"id":"classes\/12","name":"Script"},"size":96,"fixedId":true,"id":"libraries\/@0150898\/scripts\/dart%3Acore-patch%2Ferrors_patch.dart\/0","uri":"dart:core-patch\/errors_patch.dart","_kind":"kernel","_loadTime":0,"library":{"type":"@Library","fixedId":true,"id":"libraries\/@0150898","name":"dart.core","uri":"dart:core"},"lineOffset":0,"columnOffset":0,"source":"\/\/ Copyright (c) 2012, the Dart proj…
[9:50:22 AM] [VmService] [Info] [Flutter] ==> {"id":"1677","jsonrpc":"2.0","method":"getStack","params":{"isolateId":"isolates/4079229187977411"}}
[9:50:22 AM] [VmService] [Info] [Flutter] <== {"jsonrpc":"2.0", "result":{"type":"Stack","frames":[{"type":"Frame","kind":"Regular","location":{"type":"SourceLocation","script":{"type":"@Script","fixedId":true,"id":"libraries\/@0150898\/scripts\/dart%3Acore-patch%2Ferrors_patch.dart\/0","uri":"dart:core-patch\/errors_patch.dart","_kind":"kernel"},"tokenPos":1483},"function":{"type":"@Function","fixedId":true,"id":"classes\/180\/functions\/_doThrowNew%400150898","name":"_doThrowNew","_vmName":"_doThrowNew@0150898","owner":{"typ…
[9:50:22 AM] [VmService] [Info] [Flutter] ==> {"id":"1678","jsonrpc":"2.0","method":"getObject","params":{"isolateId":"isolates/4079229187977411","objectId":"libraries/@287066280/scripts/package%3Aflutter%2Fsrc%2Fanimation%2Fanimation_controller.dart/174486e037b"}}
[9:50:22 AM] [VmService] [Info] [Flutter] ==> {"id":"1680","jsonrpc":"2.0","method":"getObject","params":{"isolateId":"isolates/4079229187977411","objectId":"libraries/@105042623/scripts/package%3Aflutter%2Fsrc%2Fwidgets%2Fframework.dart/174486e03d8"}}
[9:50:22 AM] [VmService] [Info] [Flutter] ==> {"id":"1681","jsonrpc":"2.0","method":"getObject","params":{"isolateId":"isolates/4079229187977411","objectId":"libraries/@409005770/scripts/package%3Aflutter%2Fsrc%2Fwidgets%2Fbinding.dart/174486e03a1"}}
[9:50:22 AM] [VmService] [Info] [Flutter] ==> {"id":"1682","jsonrpc":"2.0","method":"getObject","params":{"isolateId":"isolates/4079229187977411","objectId":"libraries/@537452173/scripts/package%3Aflutter%2Fsrc%2Frendering%2Fbinding.dart/174486e03b6"}}
[9:50:22 AM] [VmService] [Info] [Flutter] ==> {"id":"1683","jsonrpc":"2.0","method":"getObject","params":{"isolateId":"isolates/4079229187977411","objectId":"libraries/@537452173/scripts/package%3Aflutter%2Fsrc%2Fscheduler%2Fbinding.dart/174486e03b6"}}
[9:50:22 AM] [VmService] [Info] [Flutter] <== {"jsonrpc":"2.0", "result":{"type":"Script","class":{"type":"@Class","fixedId":true,"id":"classes\/12","name":"Script"},"size":96,"fixedId":true,"id":"libraries\/@287066280\/scripts\/package%3Aflutter%2Fsrc%2Fanimation%2Fanimation_controller.dart\/174486e037b","uri":"package:flutter\/src\/animation\/animation_controller.dart","_kind":"kernel","_loadTime":1598943003515,"library":{"type":"@Library","fixedId":true,"id":"libraries\/@287066280","name":"","uri":"package:flutter\/src\/ani…
[9:50:22 AM] [VmService] [Info] [Flutter] <== {"jsonrpc":"2.0", "result":{"type":"Script","class":{"type":"@Class","fixedId":true,"id":"classes\/12","name":"Script"},"size":96,"fixedId":true,"id":"libraries\/@105042623\/scripts\/package%3Aflutter%2Fsrc%2Fwidgets%2Fframework.dart\/174486e03d8","uri":"package:flutter\/src\/widgets\/framework.dart","_kind":"kernel","_loadTime":1598943003608,"library":{"type":"@Library","fixedId":true,"id":"libraries\/@105042623","name":"","uri":"package:flutter\/src\/widgets\/framework.dart"},"li…
[9:50:22 AM] [VmService] [Info] [Flutter] <== {"jsonrpc":"2.0", "result":{"type":"Script","class":{"type":"@Class","fixedId":true,"id":"classes\/12","name":"Script"},"size":96,"fixedId":true,"id":"libraries\/@409005770\/scripts\/package%3Aflutter%2Fsrc%2Fwidgets%2Fbinding.dart\/174486e03a1","uri":"package:flutter\/src\/widgets\/binding.dart","_kind":"kernel","_loadTime":1598943003553,"library":{"type":"@Library","fixedId":true,"id":"libraries\/@409005770","name":"","uri":"package:flutter\/src\/material\/dropdown.dart"},"lineOf…
[9:50:22 AM] [VmService] [Info] [Flutter] <== {"jsonrpc":"2.0", "result":{"type":"Script","class":{"type":"@Class","fixedId":true,"id":"classes\/12","name":"Script"},"size":96,"fixedId":true,"id":"libraries\/@537452173\/scripts\/package%3Aflutter%2Fsrc%2Frendering%2Fbinding.dart\/174486e03b6","uri":"package:flutter\/src\/rendering\/binding.dart","_kind":"kernel","_loadTime":1598943003574,"library":{"type":"@Library","fixedId":true,"id":"libraries\/@537452173","name":"","uri":"package:flutter\/src\/rendering\/binding.dart"},"li…
[9:50:22 AM] [VmService] [Info] [Flutter] <== {"jsonrpc":"2.0", "result":{"type":"Script","class":{"type":"@Class","fixedId":true,"id":"classes\/12","name":"Script"},"size":96,"fixedId":true,"id":"libraries\/@537452173\/scripts\/package%3Aflutter%2Fsrc%2Fscheduler%2Fbinding.dart\/174486e03b6","uri":"package:flutter\/src\/scheduler\/binding.dart","_kind":"kernel","_loadTime":1598943003574,"library":{"type":"@Library","fixedId":true,"id":"libraries\/@537452173","name":"","uri":"package:flutter\/src\/rendering\/binding.dart"},"li…
[9:50:22 AM] [Analyzer] [Info] ==> {"id":"3403","method":"analysis.setPriorityFiles","params":{"files":["C:\\flutter\\packages\\flutter\\lib\\src\\animation\\animation_controller.dart"]},"clientRequestTime":1598943022384}
[9:50:22 AM] [Analyzer] [Info] ==> {"id":"3404","method":"analysis.updateContent","params":{"files":{"C:\\flutter\\packages\\flutter\\lib\\src\\animation\\animation_controller.dart":{"edits":[{"offset":0,"length":0,"replacement":"","id":""}],"type":"change"}}},"clientRequestTime":1598943022387}
[9:50:22 AM] [General] [Error] Cannot call write after a stream was destroyed
Error [ERR_STREAM_DESTROYED] [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
    at doWrite (_stream_writable.js:414:19)
    at writeOrBuffer (_stream_writable.js:402:5)
    at Socket.Writable.write (_stream_writable.js:302:11)
    at b.sendMessage (c:\Users\XXX\.vscode\extensions\dart-code.dart-code-3.13.2\out\dist\extension.js:1:152923)
    at b.sendMessage (c:\Users\XXX\.vscode\extensions\dart-code.dart-code-3.13.2\out\dist…
[9:50:22 AM] [Analyzer] [Info] ==> {"id":"3405","method":"analysis.updateContent","params":{"files":{"C:\\flutter\\packages\\flutter\\lib\\src\\animation\\animation_controller.dart":{"edits":[{"offset":0,"length":0,"replacement":"","id":""}],"type":"change"}}},"clientRequestTime":1598943022397}
[9:50:29 AM] [VmService] [Info] [Flutter] Termination requested!
[9:50:29 AM] [FlutterRun] [Info] [Flutter] ==> [{"id":"5","method":"app.stop","params":{"appId":"3f66d988-bff0-4cad-9f7a-efa814d6fbf0"}}]
[9:50:29 AM] [FlutterRun] [Info] [Flutter] <== [{"id":"5","result":true}]
[9:50:29 AM] [FlutterRun] [Info] [Flutter] <== Application finished.
[9:50:29 AM] [FlutterRun] [Info] [Flutter] <== [{"event":"app.stop","params":{"appId":"3f66d988-bff0-4cad-9f7a-efa814d6fbf0"}}]
[9:50:29 AM] [FlutterRun] [Info] [Flutter] Process terminated! null, SIGTERM
[9:50:29 AM] [VmService] [Info] [Flutter] Process exited (sigterm)
[9:50:29 AM] [VmService] [Info] [Flutter] TERM: Requested to terminate with SIGINT...
[9:50:29 AM] [VmService] [Info] [Flutter] TERM: Did not need to terminate processes
[9:50:29 AM] [VmService] [Info] [Flutter] TERM: Removing all stored data...
[9:50:29 AM] [VmService] [Info] [Flutter] TERM: Waiting for process to finish...
[9:50:29 AM] [VmService] [Info] [Flutter] TERM: Disconnecting...
[9:50:29 AM] [VmService] [Info] [Flutter] VM service connection closed: 1006 ()
[9:50:30 AM] [VmService] [Info] [Flutter] Disconnect requested!
[9:50:30 AM] [VmService] [Info] [Flutter] TERM: Requested to terminate with SIGINT...
[9:50:30 AM] [VmService] [Info] [Flutter] TERM: Did not need to terminate processes
[9:50:30 AM] [VmService] [Info] [Flutter] TERM: Removing all stored data...
[9:50:30 AM] [VmService] [Info] [Flutter] TERM: Waiting for process to finish...
[9:50:30 AM] [VmService] [Info] [Flutter] TERM: Disconnecting...
[9:50:30 AM] [General] [Info] Debugger:SessionDuration timing: 63452ms (Flutter)
[9:50:34 AM] [Analyzer] [Info] ==> {"id":"3406","method":"analysis.getHover","params":{"file":"C:\\flutter\\packages\\flutter\\lib\\src\\animation\\animation_controller.dart","offset":17097},"clientRequestTime":1598943034908}
[9:50:34 AM] [General] [Error] Cannot call write after a stream was destroyed
Error [ERR_STREAM_DESTROYED] [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
    at doWrite (_stream_writable.js:414:19)
    at writeOrBuffer (_stream_writable.js:402:5)
    at Socket.Writable.write (_stream_writable.js:302:11)
    at b.sendMessage (c:\Users\XXX\.vscode\extensions\dart-code.dart-code-3.13.2\out\dist\extension.js:1:152923)
    at b.sendMessage (c:\Users\XXX\.vscode\extensions\dart-code.dart-code-3.13.2\out\dist…
[9:50:42 AM] [Analyzer] [Info] ==> {"id":"3407","method":"edit.getFixes","params":{"file":"XXX","offset":0},"clientRequestTime":1598943042014}
[9:50:42 AM] [Analyzer] [Info] ==> {"id":"3408","method":"edit.getAssists","params":{"file":"XXX","length":0,"offset":0},"clientRequestTime":1598943042017}
[9:50:42 AM] [Analyzer] [Info] ==> {"id":"3409","method":"edit.getAvailableRefactorings","params":{"file":"XXX","length":0,"offset":0},"clientRequestTime":1598943042019}
[9:50:42 AM] [Analyzer] [Info] ==> {"id":"3410","method":"analysis.setPriorityFiles","params":{"files":["XXX"]},"clientRequestTime":1598943042023}
[9:50:42 AM] [Analyzer] [Info] ==> {"id":"3411","method":"analysis.updateContent","params":{"files":{"XXX":{"edits":[{"offset":0,"length":0,"replacement":"","id":""}],"type":"change"}}},"clientRequestTime":1598943042025}
[9:50:42 AM] [General] [Error] Cannot call write after a stream was destroyed
Error [ERR_STREAM_DESTROYED] [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
    at doWrite (_stream_writable.js:414:19)
    at writeOrBuffer (_stream_writable.js:402:5)
    at Socket.Writable.write (_stream_writable.js:302:11)
    at b.sendMessage (c:\Users\XXX\.vscode\extensions\dart-code.dart-code-3.13.2\out\dist\extension.js:1:152923)
    at b.sendMessage (c:\Users\XXX\.vscode\extensions\dart-code.dart-code-3.13.2\out\dist…
[9:50:42 AM] [General] [Error] Cannot call write after a stream was destroyed
Error [ERR_STREAM_DESTROYED] [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
    at doWrite (_stream_writable.js:414:19)
    at writeOrBuffer (_stream_writable.js:402:5)
    at Socket.Writable.write (_stream_writable.js:302:11)
    at b.sendMessage (c:\Users\XXX\.vscode\extensions\dart-code.dart-code-3.13.2\out\dist\extension.js:1:152923)
    at b.sendMessage (c:\Users\XXX\.vscode\extensions\dart-code.dart-code-3.13.2\out\dist…
[9:50:42 AM] [General] [Error] Cannot call write after a stream was destroyed
Error [ERR_STREAM_DESTROYED] [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
    at doWrite (_stream_writable.js:414:19)
    at writeOrBuffer (_stream_writable.js:402:5)
    at Socket.Writable.write (_stream_writable.js:302:11)
    at b.sendMessage (c:\Users\XXX\.vscode\extensions\dart-code.dart-code-3.13.2\out\dist\extension.js:1:152923)
    at b.sendMessage (c:\Users\XXX\.vscode\extensions\dart-code.dart-code-3.13.2\out\dist…
[9:50:42 AM] [Analyzer] [Info] ==> {"id":"3412","method":"analysis.updateContent","params":{"files":{"XXX":{"edits":[{"offset":0,"length":0,"replacement":"","id":""}],"type":"change"}}},"clientRequestTime":1598943042033}
[9:50:42 AM] [Analyzer] [Info] ==> {"id":"3413","method":"edit.getFixes","params":{"file":"XXX","offset":1541},"clientRequestTime":1598943042225}
[9:50:42 AM] [Analyzer] [Info] ==> {"id":"3414","method":"edit.getAssists","params":{"file":"XXX","length":0,"offset":1541},"clientRequestTime":1598943042229}
[9:50:42 AM] [Analyzer] [Info] ==> {"id":"3415","method":"edit.getAvailableRefactorings","params":{"file":"XXX","length":0,"offset":1541},"clientRequestTime":1598943042236}
[9:50:42 AM] [General] [Error] Cannot call write after a stream was destroyed
Error [ERR_STREAM_DESTROYED] [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
    at doWrite (_stream_writable.js:414:19)
    at writeOrBuffer (_stream_writable.js:402:5)
    at Socket.Writable.write (_stream_writable.js:302:11)
    at b.sendMessage (c:\Users\XXX\.vscode\extensions\dart-code.dart-code-3.13.2\out\dist\extension.js:1:152923)
    at b.sendMessage (c:\Users\XXX\.vscode\extensions\dart-code.dart-code-3.13.2\out\dist…
[9:50:42 AM] [General] [Error] Cannot call write after a stream was destroyed
Error [ERR_STREAM_DESTROYED] [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
    at doWrite (_stream_writable.js:414:19)
    at writeOrBuffer (_stream_writable.js:402:5)
    at Socket.Writable.write (_stream_writable.js:302:11)
    at b.sendMessage (c:\Users\XXX\.vscode\extensions\dart-code.dart-code-3.13.2\out\dist\extension.js:1:152923)
    at b.sendMessage (c:\Users\XXX\.vscode\extensions\dart-code.dart-code-3.13.2\out\dist…
[9:50:42 AM] [Analyzer] [Info] ==> {"id":"3416","method":"analysis.getHover","params":{"file":"XXX","offset":1241},"clientRequestTime":1598943042821}
[9:50:42 AM] [General] [Error] Cannot call write after a stream was destroyed
Error [ERR_STREAM_DESTROYED] [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
    at doWrite (_stream_writable.js:414:19)
    at writeOrBuffer (_stream_writable.js:402:5)
    at Socket.Writable.write (_stream_writable.js:302:11)
    at b.sendMessage (c:\Users\XXX\.vscode\extensions\dart-code.dart-code-3.13.2\out\dist\extension.js:1:152923)
    at b.sendMessage (c:\Users\XXX\.vscode\extensions\dart-code.dart-code-3.13.2\out\dist…
[9:50:50 AM] [Analyzer] [Info] ==> {"id":"3417","method":"analysis.getHover","params":{"file":"XXX","offset":310},"clientRequestTime":1598943050326}
[9:50:50 AM] [General] [Error] Cannot call write after a stream was destroyed
Error [ERR_STREAM_DESTROYED] [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
    at doWrite (_stream_writable.js:414:19)
    at writeOrBuffer (_stream_writable.js:402:5)
    at Socket.Writable.write (_stream_writable.js:302:11)
    at b.sendMessage (c:\Users\XXX\.vscode\extensions\dart-code.dart-code-3.13.2\out\dist\extension.js:1:152923)
    at b.sendMessage (c:\Users\XXX\.vscode\extensions\dart-code.dart-code-3.13.2\out\dist…
[9:50:50 AM] [Analyzer] [Info] ==> {"id":"3418","method":"analysis.getHover","params":{"file":"XXX","offset":310},"clientRequestTime":1598943050529}
```

**Comment by talent-apps** [comment] 2020-09-01 06:56
The project uses this `analysis_options.yaml` file:

```
include: package:pedantic/analysis_options.yaml

# See https://dart-lang.github.io/linter/lints/
analyzer:
  exclude: [build/**]

linter:
  rules:
    curly_braces_in_flow_control_structures: false
    unawaited_futures: false
    omit_local_variable_types: false
    prefer_single_quotes: false
    prefer_collection_literals: false
    unnecessary_this: false
```

**Comment by DanTup** [comment] 2020-09-01 10:50
I think you may be hitting https://github.com/dart-lang/sdk/issues/40348. That's a bug in the file-watcher in Dart that is often triggered by Flutter builds. Based on the log you posted, it looks like you had a Flutter debug session running, so I'm guessing it may have occurred after you saved a file that triggered a hot reload (which could trigger activity in the `build` folder).

Which Flutter channel are you currently using?

**Comment by talent-apps** [comment] 2020-09-01 10:52
This was indeed the case.
We use the 'stable' channel.

**Comment by DanTup** [comment] 2020-09-01 10:57
@zichangg do you know when the fix re-landed in https://github.com/dart-lang/sdk/commit/04879fa4cdc2fc173b99472bae186feecc7e08e0 was lost? Is it possible the current Flutter stable release is missing the fix? (If so, that probably explains this issue - if not, it may be a different (but similar) issue). Thanks!

**Comment by zichangg** [comment] 2020-09-01 18:54
I think it was in the March. I can't remember the exact date. When we did the null safety migration, the file with fixes was replaced. Flutter seems to be affected as well.

**Comment by DanTup** [comment] 2020-09-02 11:21
Ah, sounds like it would've made it to Flutter stable so the issue above is likely the same.

@talent-apps I'll close this as a dupe of https://github.com/dart-lang/sdk/issues/40348. If you still see it occurring in a Flutter release that includes https://github.com/dart-lang/sdk/commit/04879fa4cdc2fc173b99472bae186feecc7e08e0 (which presumably will be in the next stable release), please comment on that issue. Thanks!

**Closed by DanTup** 2020-09-02 11:21 UTC
Labels: awaiting info

**Comment by Abdelmjid-ASOUAB** [comment] 2021-03-06 21:17
@DanTup  is there any solution  i have the same problem !

**Comment by DanTup** [comment] 2021-03-08 10:47
@Abdelmjid-ASOUAB if you're seeing this one the latest version of Flutter (2.0.1), please file a new issue and include the log. Thanks!
