### ISSUE TITLE
Refactoring not working

### ISSUE THREAD

**Issue by jaworskig** [Dart-Code/Dart-Code#4893] opened 2023-12-11 10:48 UTC
Type: <b>Bug</b>

Not working Refactoring from rigth click menu, nothing is showing.

Extension version: 3.78.0
VS Code version: Code 1.85.0 (af28b32d7e553898b2a91af498b1fb666fdebe0c, 2023-12-06T20:48:09.019Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-10850K CPU @ 3.60GHz (20 x 3600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.92GB (1.85GB free)|
|Process Argv|--crash-reporter-id 004b5184-f7c5-455e-ae0e-347dedc9ba38|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263:30899288
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
3biah626:30602489
f6dab269:30613381
showlangstatbar:30737416
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
welcomedialog:30910333
pythonnosmt12:30797651
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
dsvsc013:30795093
dsvsc014:30804076
dsvsc015:30845448
pythontestfixt:30902429
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
aa_t_chat:30882232

```

</details>

**Comment by bdesilvaA** [comment] 2023-12-11 11:36
I had the same issue but Pressing` ( Ctrl+. )`  , again right click refactoring menu worked for me

**Comment by DanTup** [comment] 2023-12-11 11:36
> Not working Refactoring from rigth click menu, nothing is showing.

Can you provide a screenshot of what you see? I just tried this but the refactor option shows up:

![image](https://github.com/Dart-Code/Dart-Code/assets/1078012/8f2231a6-0d0b-4546-9dd1-804332f40e54)


Can you also click Help -> Toggle Developer Tools and then on the Console tab to see if there are any errors reported?

**Comment by jaworskig** [comment] 2023-12-11 11:49
After select Refactor from right-click menu nothing is showing up.
But when I use Ctrl+Shift+R it's open corect Refactor menu, and also right-click menu starts working.

 WARN Via 'product.json#extensionEnabledApiProposals' extension 'ms-python.python' wants API proposal 'registerIssueDataProvider' but that proposal DOES NOT EXIST. Likely, the proposal has been finalized (check 'vscode.d.ts') or was abandoned.
log.ts:421  INFO Started local extension host with pid 30732.
TMScopeRegistry.ts:46 Overwriting grammar scope name to file mapping for scope source.dart.
Old grammar file: file:///c%3A/Users/jawor/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/extensions/dart/syntaxes/dart.tmLanguage.json.
New grammar file: file:///c%3A/Users/jawor/.vscode/extensions/dart-code.dart-code-3.78.0/syntaxes/dart.json
register @ TMScopeRegistry.ts:46
TMScopeRegistry.ts:46 Overwriting grammar scope name to file mapping for scope source.groovy.
Old grammar file: file:///c%3A/Users/jawor/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/extensions/groovy/syntaxes/groovy.tmLanguage.json.
New grammar file: file:///c%3A/Users/jawor/.vscode/extensions/vscjava.vscode-gradle-3.13.5/syntaxes/groovy.tmLanguage.json
register @ TMScopeRegistry.ts:46
TMScopeRegistry.ts:46 Overwriting grammar scope name to file mapping for scope source.dart.
Old grammar file: file:///c%3A/Users/jawor/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/extensions/dart/syntaxes/dart.tmLanguage.json.
New grammar file: file:///c%3A/Users/jawor/.vscode/extensions/dart-code.dart-code-3.78.0/syntaxes/dart.json
register @ TMScopeRegistry.ts:46
TMScopeRegistry.ts:46 Overwriting grammar scope name to file mapping for scope source.groovy.
Old grammar file: file:///c%3A/Users/jawor/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/extensions/groovy/syntaxes/groovy.tmLanguage.json.
New grammar file: file:///c%3A/Users/jawor/.vscode/extensions/vscjava.vscode-gradle-3.13.5/syntaxes/groovy.tmLanguage.json
register @ TMScopeRegistry.ts:46
log.ts:421  INFO [perf] Render performance baseline is 29ms

**Comment by DanTup** [comment] 2023-12-11 12:24
> After select Refactor from right-click menu nothing is showing up.
> But when I use Ctrl+Shift+R it's open corect Refactor menu, and also from right-click menu starts working.

Ah, I can reproduce this - thanks!

I think it might be a VS Code bug, but I'll do some testing and post back.

**Comment by DanTup** [comment] 2023-12-11 12:30
This appears to have been broken in the latest version of VS Code. It's also reproducible (although looks likely different) in other languages.

Some upstream issues:

- https://github.com/microsoft/vscode/issues/200466
- https://github.com/microsoft/vscode/issues/200442
- https://github.com/microsoft/vscode/issues/200436
- https://github.com/microsoft/vscode/issues/198881
- https://github.com/microsoft/vscode/issues/199556

I'll close this because it'll unfortunately need fixing (and releasing) in VS Code.

**Closed by DanTup** 2023-12-11 12:30 UTC
Labels: awaiting info
