### ISSUE TITLE
After running 'flutter pub get', dart analyzer crashes in code

### ISSUE THREAD

**Issue by acoutts** [Dart-Code/Dart-Code#3295] opened 2021-04-22 11:47 UTC
**Describe the bug**
When you run `flutter pub get`, the dart analyzer crashes (problem count tab goes to 0), then it (sometimes) will restart itself, but other times I have to manually restart the extension host which involves shutting down my current debug session, restarting extension host, and doing another full build to run it again.

**To Reproduce**
1. Run flutter pub get
2. Observe the problems window disappear

**Expected behavior**
Analyzer shouldn't crash.

**Screenshots**

**Versions (please complete the following information):**
 - VS Code version:
 ```
 Version: 1.56.0-insider
Commit: 7ce1499d9541ba2acf66cd30a9054bd7818a8f80
Date: 2021-04-22T05:12:09.510Z (6 hrs ago)
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Darwin x64 20.3.0
```
 - Dart extension version: `3.21.1`
 - Dart/Flutter SDK version:
 ```
 Flutter 2.2.0-11.0.pre.180 • channel master • https://github.com/flutter/flutter.git
Framework • revision 71cb40f46a (2 days ago) • 2021-04-20 14:19:02 -0400
Engine • revision 79c5ebe835
Tools • Dart 2.14.0 (build 2.14.0-18.0.dev)
```

**Comment by DanTup** [comment] 2021-04-23 17:11
How reliably can you reproduce this? I wasn't able to repro, I see errors vanish but then come back (which I think is because `flutter pub get` is causing the server to rebuild its contexts, rather than it crashing and restarting). I'm not sure why your errors wouldn't come back though if they're not fixed.

Do you see the same behaviour with `dart.previewLsp` enabled? Can you capture a log and give an example of a file that had errors that vanished but didn't come back? If you can capture a log with **Dart: Capture Logs** and include both Command Processes and Analysis Server, and fetch packages using the **Flutter: Get Packages** command from the command palette, that may be useful (it just calls `flutter pub get`, but it will show up in the log so it's easier to match up with the server activity at the time).

**Comment by acoutts** [comment] 2021-04-23 17:14
Aha indeed, I think it just takes a bit to come back now after looking again.

**Comment by DanTup** [comment] 2021-04-23 17:23
Cool - though if it seems particularly slow for what was being updated, it may be worth getting a repro (it was a fraction of a second for me, although my project was tiny). My guess is that it triggers a context rebuild and therefore has to reanalyze - though if the package update didn't do anything (for example) then it probably shouldn't do anything at all.

**Comment by acoutts** [comment] 2021-04-23 20:03
Here's a full log dump - managed to make it happen! This is only about 1-2 minutes of time total.

https://gist.github.com/acoutts/64618f74ca57654d0683ea8e0da7c6fe

**Comment by DanTup** [comment] 2021-04-26 10:24
Can you repro when not in a debug session (or using **Capture Logs** with the VM Service/Flutter Run _unticked_) and using **Flutter: Get Packages** (so the `pub get` command is included in the log file)? It's not clear from this log when the process ran, and the individual analysis sections are < 5 seconds so it's hard to match up.

I can reproduce the behaviour, although it's very quick on the projects I tested with. For example, I cloned latest `flutter_gallery` and introduced a warning (`var a = "";` warns due to double quotes) and ran **Flutter: Get Packages**. The error vanished, it came back in < 1 second.

I'd be interested to know:

- what time you see doing this for flutter_gallery
- how big your project is (for example, how long is the `pubspec.lock` file compared to flutter_gallery's 657 lines?)

**Comment by acoutts** [comment] 2021-04-26 15:23
Hm it seems I can only repro it if there is an active debug session.
* Start a debug session
* Run flutter pub get while it's building or running
* Problems window count disappears and hot reloads on save stop working, and it never recovers.

If there's no debug session active then it recovers after the flutter pub get.

**Comment by DanTup** [comment] 2021-05-03 16:51
@acoutts sorry for the delay. You mention "Ran code generator".. can you confirm what this is? Are you able to provide a repro project you can trigger it in for me to test? Can you also confirm the version of Flutter you're using? Your output says d72bfb8d07 but I can't see a commit with that hash in the Flutter repo. If there are custom commits, can you confirm which commit it's branched from?

Thanks!

**Comment by acoutts** [comment] 2021-05-04 14:10
Sorry for the bad bug report, I just can't figure out how to reproduce this issue! I'll be using code and the issue will happen, then I turn on debugging and try to reproduce it and it will work every time. Could turning on logs actively fix it in some way too?

Here's the tag i'm using (it's on the dev channel now iirc):
https://github.com/flutter/flutter/tree/2.3.0-0.1.pre

**Comment by acoutts** [comment] 2021-05-04 15:28
Damnit, I had logging running and finally noticed the issue happened but then the logs were too big to save and they're gone now.
>Command 'Dart: Capture Logs' resulted in an error (Running the contributed command: 'dart.startLogging' failed.)

**Comment by acoutts** [comment] 2021-05-04 20:16
Potentially related issue:
* go to save a file
* file doesn't save
* hangs saying `saving 'file': Running 'Dart' Formatter`
* if I click cancel, file saves immediately and then hot reload happens

Here's a log capture of that:
https://gist.github.com/acoutts/84af00e009752433ddb1cfd8f73021b8

**Comment by DanTup** [comment] 2021-05-05 09:00
> Could turning on logs actively fix it in some way too?

It shouldn't really, although because it adds a small amount of work it could affect timing. I'd be surprised, but anything is possible.

> Potentially related issue:

That could be related. When this happens, it seems like the server is not responding (though it's not clear if it's just really busy doing something slow, or if it's broken). Clicking "cancel" on the formatting dialog tells VS Code not to wait for the server to respond to the formatting request and just save immediately.

It looks like the log you attached started _after_ the last response from the server (the first analyzer request in there is to request a hover, which also never completes), so it's not clear what happened. If you can enable the `analyzerInstrumentationLog` and get a copy next time you see that, that would definitely help. It will get large, but probably only the last few analyzer responses (which you can find by searching for `[Analyzer] [Info] <==`) and everything after them would be useful.

There have been a few reports of this kind of behaviour (analyzer doesn't seem to respond while formatting, making the save slow) but so far I've not been able to get a log so I'm a bit stuck trying to track down what's going on 😞

**Comment by acoutts** [comment] 2021-05-05 11:52
On it! I'll keep an eye on it today and see if I can catch it with this log file recording now.

**Comment by acoutts** [comment] 2021-05-05 12:08
I think I caught it. This one happened quickly.
* Everything was normal
* I started a debug session. While the iOs app was building, analyzer problems window was empty and I can't hover on anything (says loading).
* Debug build finishes and app launches
* Left it for a few minutes and the analyzer had still not recovered

The log file is about 38mb. I uploaded it to a gist here by zipping it and then base64 encoding the zip file to share it.

https://gist.githubusercontent.com/acoutts/0526551682d3fd4e83f7df6f92f18d35/raw/0d00a5de8ed52365ea6f91c60fc107c1e8b65b3e/gistfile1.txt

To put it back to a zip:
```
cat gistfile1.txt | base64 --decode > log.zip
```

**Comment by DanTup** [comment] 2021-05-05 12:46
> I uploaded it to a gist here by zipping it and then base64 encoding the zip file to share it.

FWIW, you can email up to 25MB to me at logs@dartcode.org :-)

Out of interest - which problem did you see when this occurred? Was it the hanging formatting? I can't any instances of `"edit.format"` in the log (which is the call to format when using the original protocol), so I'm not sure whether something went wrong before it got there.

Sorry to be a pain, but are you able to also enable the `analyzerLogFile` (which logs from the _client_ instead of the server) and try to grab both when this occurs? It may also be useful to enable `dart.previewLsp` as the log will be cleaner, and there's less code running on the client (which makes it easier to debug from the logs). LSP will become the default soon (it already is for some subset of users).

**Comment by acoutts** [comment] 2021-05-05 12:49
No prob! Setting that up now.

One thing on LSP - it changes the colors of the code, is there any way to revert that to how it usually is on the old analyzer?

**Comment by acoutts** [comment] 2021-05-05 12:52
Before LSP:
<img width="768" alt="Screen Shot 2021-05-05 at 8 49 51 AM" src="https://user-images.githubusercontent.com/9597207/117143746-277eb800-ad7f-11eb-85ae-73bad9abff37.png">


After LSP:
<img width="766" alt="Screen Shot 2021-05-05 at 8 51 46 AM" src="https://user-images.githubusercontent.com/9597207/117143761-2baad580-ad7f-11eb-8893-a04c083f5e9b.png">

**Comment by DanTup** [comment] 2021-05-05 13:04
Yeah, before semantic tokens a lot of stuff was left uncoloured. Now, variables (etc.) are coloured by the theme (which usually makes them different to uncoloured things like parens and operators).

If you want to change them back to white (or anything else), you can customise them in your theme settings (see https://github.com/Dart-Code/Dart-Code/issues/3168#issuecomment-787832710).

**Comment by acoutts** [comment] 2021-05-05 13:06
Aha! Great to know this is how it should be now.

**Comment by acoutts** [comment] 2021-05-05 13:30
Got it to hang and stop responding- sent an email to the logs inbox for you 👍

**Comment by DanTup** [comment] 2021-05-05 14:59
@acoutts by the way - the title of this issue says "flutter pub get", but I've been assuming it was during hot reload. Which is correct (or is it both)?

**Comment by acoutts** [comment] 2021-05-05 15:07
I think it started with me thinking flutter pub get was crashing it but I learned after that this is normal, and the issue is sometimes the analyzer just becomes unresponsive now that we've dug into it.

* `code --status` note: the app i'm running is in the `app` folder:
```
Version:          Code - Insiders 1.56.0-insider (85f8ebf1687661c45fe2633bdd7f640164a20cc2, 2021-05-04T08:00:19.452Z)
OS Version:       Darwin x64 20.3.0
CPUs:             Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz (8 x 3600)
Memory (System):  64.00GB (0.03GB free)
Load (avg):       2, 2, 3
VM:               0%
Screen Reader:    no
Process Argv:     --crash-reporter-id 39fa896b-c053-47eb-a0df-633a5e471769
GPU Status:       2d_canvas:                  enabled
                  gpu_compositing:            enabled
                  metal:                      disabled_off
                  multiple_raster_threads:    enabled_on
                  oop_rasterization:          enabled
                  opengl:                     enabled_on
                  rasterization:              enabled
                  skia_renderer:              disabled_off_ok
                  video_decode:               enabled
                  webgl:                      enabled
                  webgl2:                     enabled

CPU %	Mem MB	   PID	Process
    2	   131	 60808	code-insiders main
    0	    66	 60812	   gpu-process
    0	     0	 60814	   utility
    0	   459	 60815	   window (push_notification_store.dart — PROJECTS (Workspace))
    0	    66	 60845	     watcherService
    0	    66	 60840	   shared-process
    0	     0	 60847	     ptyHost
    0	     0	 60850	       /bin/zsh --login

Workspace Stats: 
|  Window (push_notification_store.dart — PROJECTS (Workspace))
|    Folder (bottlepay_apis): 93 files
|      File types: dart(57) proto(3) md(2) json(1) gitignore(1) packages(1)
|                  lock(1) yaml(1)
|      Conf files: makefile(1)
|    Folder (btc): 313 files
|      File types: go(169) sql(16) proto(10) example(5) DS_Store(4) yml(2)
|                  png(2) dockerignore(1) gitattributes(1)
|                  gitignore(1)
|      Conf files: makefile(1)
|    Folder (scope): 528 files
|      File types: png(62) dart(59) dylib(28) plist(26) h(23) json(14)
|                  xcconfig(10) nib(8) stamp(7) xml(7)
|      Conf files:
|    Folder (dev-omnibus): 11723 files
|      File types: snap(8176) beam(216) ejs(47) js(26) hrl(11) conf(10)
|                  queue_name(10) jif(10) app(10) html(8)
|      Conf files: makefile(1) package.json(1)
|    Folder (hive): 5006 files
|      File types: go(2867) md(176) h(172) hpp(144) yml(95) mod(66)
|                  gitignore(63) s(46) sum(45) a(32)
|      Conf files: makefile(42) cmake(4)
|    Folder (pay): 11881 files
|      File types: go(7532) md(424) yml(236) mod(167) gitignore(157) s(123)
|                  sum(113) proto(62) sh(50) dart(42)
|      Conf files: makefile(81) launch.json(1)
|    Folder (app): more than 20870 files
|      File types: rb(6159) xml(1309) svg(1288) flat(1154) png(589) json(424)
|                  md(323) h(306) class(258) len(239)
|      Conf files: makefile(34) launch.json(1) settings.json(1) tasks.json(1)
|      Launch Configs: dart(20)
```

* Dependencies: `72`. pubspec.lock is 1600 lines.
* No codegen running on hot reload, just normal hot reload here.
* It happens when I run on a simulator and physical device. Sometimes I have 2 debug sessions open (one on each) and it will happen there too.

I've added those 2 exclude folders and will watch it again.

**Comment by DanTup** [comment] 2021-05-10 09:24
The additional logs you sent me all seem to end after similar watcher notifications:

```
1620421259477:Watch:<unknown>:/Users/andrewcoutts/Projects/app/ios/Runner.xcodeproj/project.pbxproj:modify
1620421261126:Watch:<unknown>:/Users/andrewcoutts/Projects/app/ios/Flutter/Generated.xcconfig:modify
1620421261126:Watch:<unknown>:/Users/andrewcoutts/Projects/app/ios/Flutter/flutter_export_environment.sh:modify
1620421261226:Watch:<unknown>:/Users/andrewcoutts/Projects/app/.flutter-plugins:modify
1620421261226:Watch:<unknown>:/Users/andrewcoutts/Projects/app/.flutter-plugins-dependencies:modify
1620421262523:Watch:<unknown>:/Users/andrewcoutts/Projects/app/ios/Flutter/Flutter.podspec:modify
```

If you can reproduce this reliably now, does the same occur on a smaller project that you should share or only this large project?

**Comment by DanTup** [comment] 2021-05-12 15:51
Since this has been reported in Android Studio too, let's close this one in favour of the SDK issue at https://github.com/dart-lang/sdk/issues/45996.

**Closed by DanTup** 2021-05-12 15:51 UTC
Labels: awaiting info, is bug
