### ISSUE TITLE
Dart analysis server at 100% cpu indefinitely when editing flutter engine

### ISSUE THREAD

**Issue by gaaclarke** [Dart-Code/Dart-Code#5101] opened 2024-05-09 16:07 UTC
## Description
The dart analysis server just sits at 100% when editing the flutter engine repo.

## To Reproduce
1) Check out the flutter engine repo
1) Open it in VSCode with the dart plugin installed
1) Notice that `dart` process that is running the analysis server sits at around 100% and never stops.

## Expected behavior
I would expect the process to reach some stasis of VSCode is not being interacted with.

## Screenshots
Maybe it's related that there is a huge number of issues that are reported that I never mind:

<img width="911" alt="Screenshot 2024-05-09 at 9 03 50 AM" src="https://github.com/Dart-Code/Dart-Code/assets/30870216/405f16eb-cc87-46cf-bc87-d2e75ac5962e">

## Logs
[openfiles.txt](https://github.com/Dart-Code/Dart-Code/files/15264663/openfiles.txt)

[sample.txt](https://github.com/Dart-Code/Dart-Code/files/15264667/sample.txt)

## Details
 - Operating System and version: macOS 14.4.1
 - VS Code version: 1.89.0
 - Dart extension version: v3.89.20240509 (pre-release)
 - Dart/Flutter SDK version: engine 0e23e60093d162e19108fcf28233f918fdafc136 
 - Target device (if the issue relates to Flutter debugging):

(spawned from https://github.com/Dart-Code/Dart-Code/issues/5084)

**Comment by gaaclarke** [comment] 2024-05-09 16:51
This PR to the analysis options seems to resolve this issue: https://github.com/flutter/engine/pull/52699

We were just overloading it and getting it into a bad state.  It's probably still worth fixing, but it's not an issue for me anymore.

**Comment by DanTup** [comment] 2024-05-13 14:48
@gaaclarke do you know if there are extra steps beyond cloning the repo required to trigger this? I wasn't able to reproduce (even with `gclient sync`). I wonder if there are other steps you may have performed during setting up your environment for the engine.

(eg., if you clone a new copy of the repo, can you trigger it on that?)

**Comment by DanTup** [comment] 2024-05-14 09:53
btw, in your workspace above you have:

```
"path": "src/third_party/vulkan-deps/vulkan-headers"
```

But I don't have a vulkan-deps at that location (even after `gclient sync`), it's only at `src/flutter/third_party`, so this folder shows as "missing". Did I set something up differently to you?

**Comment by DanTup** [comment] 2024-05-14 11:47
Seems that this is caused by the Dart SDK in `src/third_party/dart`. If I open _only_ that folder, I still see the same behaviour. And, if I just open a clone of the Dart SDK directly (not part of engine), I see the same too.

It is known that there are issues trying to analyze the whole SDK repo (it's full of test projects and things), but I'm surprised that it seems to be analyze forever (or at least, it's so slow it doesn't complete in any reasonable amount of time).

An extra weird thing - this repros on Windows (server is stuck forever analyzing), yet it uses almost no CPU to do so (I presume something else is a bottleneck, but nothing else like disk seem saturated oddly).

I'm gonna leave it running in the background and while I for lunch on the chance it does complete, but otherwise I'll do some more debugging to see what's going on.

**Comment by DanTup** [comment] 2024-05-14 13:30
I tracked this down to an infinite loop in the linter when there are cycling redirecting constructors. The Dart SDK includes a test file that has that (but I guess never triggers the linter over it in tests).

I've opened https://github.com/dart-lang/sdk/issues/55717 with the details and will close this one. Thanks!

**Closed by DanTup** 2024-05-14 13:30 UTC
Labels: is bug
