### ISSUE TITLE
Code action to implement missing overrides generates messy code

### ISSUE THREAD

**Issue by orestesgaolin** [Dart-Code/Dart-Code#2537] opened 2020-06-09 10:23 UTC
1. Create definition of some class that's extending other (e.g. CustomPainter)
2. Position cursor on the first line 
3. Press `cmd+.` to show code actions
4. Select `Create 2 missing overrides`
5. Observe that some parameters are printed twice or more and other are shorter than they should be.
6. Press `cmd+z` to observe that now overrides are correct

![CleanShot 2020-06-09 at 12 18 13](https://user-images.githubusercontent.com/16854239/84136294-627f4b00-aa4b-11ea-801f-1dc95ca2cedc.gif)

Example wrong code:

```
class BasicPainter extends CustomPainter{
  @override
  void paint(Canvas canvascanvascanvas, SizSizSize size) {
      // TODO: implement paint
    }
  
    @override
    bool shouldRepaint(Canvas canvas canvas, Siz) {
    // TODO: implement shouldRepaint
    throw UnimplementedError();
  }
}
```

---
Flutter and Dart extensions 3.11.0
VS Code Version: 1.45.1

Flutter doctor:

```
[✓] Flutter (Channel dev, 1.19.0-4.0.pre, on Mac OS X 10.15.5 19F101, locale pl-PL)
    • Flutter version 1.19.0-4.0.pre at /Users/dominik/fvm/versions/dev
    • Framework revision 2f7a59a8da (4 days ago), 2020-06-05 03:44:02 -0700
    • Engine revision d17c84e7af
    • Dart version 2.9.0 (build 2.9.0-13.0.dev 02915ec5ce)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/dominik/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Users/dominik/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.45.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[✓] Connected device (4 available)
    • iPhone (Dominik) • f96e187ec1f51b6be1830c7965a482dc653765d2 • ios            • iOS 13.4.1
    • macOS            • macOS                                    • darwin-x64     • Mac OS X 10.15.5 19F101
    • Web Server       • web-server                               • web-javascript • Flutter Tools
    • Chrome           • chrome                                   • web-javascript • Google Chrome 83.0.4103.97

• No issues found!
```

Installed extensions:

```
2gua.rainbow-brackets
ban.spellright
bconnect-berlin.pubmanager
Dart-Code.dart-code
Dart-Code.flutter
dracula-theme.theme-dracula
eamodio.gitlens
FelixAngelov.bloc
foxundermoon.shell-format
jeroen-meijer.pubspec-assist
jnbt.vscode-rufo
localizely.flutter-intl
mariomatheu.syntax-project-pbxproj
mechatroner.rainbow-csv
ms-vsliveshare.vsliveshare
plibither8.remove-comments
redhat.java
redhat.vscode-yaml
uloco.theme-bluloco-dark
VisualStudioExptTeam.vscodeintellicode
vscjava.vscode-java-debug
vscjava.vscode-java-dependency
vscjava.vscode-java-pack
vscjava.vscode-java-test
vscjava.vscode-maven
vscodevim.vim
wingrunr21.vscode-ruby
wx-chevalier.google-java-format
```

**Comment by DanTup** [comment] 2020-06-11 10:42
Thanks for the report! This is an issue in the analysis server and there's an open issue at dart-lang/sdk#41147 so I'll close this as a dupe of that.

**Closed by DanTup** 2020-06-11 10:42 UTC
