### ISSUE TITLE
Editor gets very slow with the large number of issues in the PROBLEMS tab

### ISSUE THREAD

**Issue by algor** [Dart-Code/Dart-Code#1321] opened 2018-11-28 18:10 UTC
With 2K+ items in the PROBLEMS tab the editor is lagging significantly on each key press. 
Sorry in advance if it is solely an issue of Visual Studio Code per se and has nothing to do with the way problems are reevaluated. Otherwise it would probably make sense to throttle updates to the PROBLEMS tab when the number of issues reaches a certain number.

**Comment by DanTup** [comment] 2018-11-28 20:32
I think this may be a VS Code issue - the tree they used was quite slow and I believe they've been porting things to a new implementation.

@joaomoreno @jrieken does this sound right? Would you expect performance issues with 2k+ items in the Problems list?

**Comment by joaomoreno** [comment] 2018-11-29 08:13
@algor What VS Code version are on you? The latest stable already ships with a high performance tree widget. There could be other issues around the Problems panel though. It would be great if you could give me steps to reproduce.

**Comment by DanTup** [comment] 2018-11-29 08:47
I just tried reproducing this on latest stable VS Code, latest Dart+Flutter extensions and the Dart SDK from latest Flutter with no luck. I have over 6k errors in my error list (I have a few packages from the Flutter repo open and replaced `void` with `void2`) but the editor and problems windows are both very responsive.

@algor When you have these issues, is CPU usage high? If so, which process? Does it show "Analyzing..." in the status bar?

There was a bug in a previous Dart release that could consume a lot of memory (which could significantly slow down your machine) https://github.com/dart-lang/sdk/issues/34850. If you can confirm your Dart or Flutter SDK versions we can check if it's that (or just upgrade to latest and see if it goes away). This wouldn't be related to the number of Problems shown though, it was triggered by specific code. It would be a `dart.exe` process consuming all the memory if this was the case.

**Comment by algor** [comment] 2018-11-29 17:55
Thanks @DanTup for digging into the issue.
To answer  your questions:
- CPU usage is about 7% on average. 
- There is no "Analyzing..." in the status bar
- dart process does not consume a lot of CPU - less than 1% overall (Soralis mode of top utility).

Dart VM version: 2.1.0
OS: Linux Debian 4.17.17-1 x86_64

Visual Studio Code:
Version: 1.29.1
Date: 2018-11-15T19:07:43.495Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

**Comment by DanTup** [comment] 2018-11-29 17:59
Can you repro this on any open source code that we can clone?

If you run the `Dart: Capture Logs` command and select the `Analyzer` option and then repro, then click Stop Logging - is there a huge amount of stuff being written to the log while the issue was occurring?

And finally, are the errors spread across many files or few? For ex., are there a large number of errors in the very file you're editing when this happens?

**Comment by DanTup** [comment] 2018-11-29 18:00
It may be worth trying to get a profile trace from the Chrome dev tools (Help -> Toggle Developer Tools). I don't know enough about VS Code to know if it'll show everything that's required, but maybe @joaomoreno or @sandy081 can give some pointers.

**Comment by DanTup** [comment] 2019-01-07 18:56
@algor Are you still seeing this? Are you able to try some of the things mentioned above?

**Comment by DanTup** [comment] 2019-01-22 14:34
Closing this since I can't progress it with more info, but please let me know if you still see it and can provide some of the info above.

**Closed by DanTup** 2019-01-22 14:34 UTC
Labels: awaiting info

**Comment by DanTup** [comment] 2019-03-27 11:01
FWIW, while investigating another performance issue for a user we found that it related to the number of problems. I opened https://github.com/Microsoft/vscode/issues/71165 and it's been fixed in VS Code (it's available in Insiders now). It's made a massive difference (gone from looooong hangs from no hangs at all) and I suspect it was probably what this issue was related to.
