### ISSUE TITLE
Code-completion considers pkg:test's test/group functions to be deprecated, analysis does not

### ISSUE THREAD

**Issue by dcharkes** [Dart-Code/Dart-Code#4480] opened 2023-04-04 07:35 UTC
**Describe the bug**

Auto-complete of the `test(..` from `package:test` shows up a strike-through in the auto-complete popup.

**To Reproduce**

Make a new project and import `package:test`.

**Expected behavior**

I expected `test(..` to not be strike-through in the autocomplete. (It's not strike-through in the normal highlighting in the editor.)

**Screenshots**

Auto-complete: strike through:

<img width="1029" alt="image" src="https://user-images.githubusercontent.com/3601775/229719538-a57bedcb-9bfe-4346-8f62-6bb169d45965.png">

Normal highlighting: not strike through:

<img width="397" alt="image" src="https://user-images.githubusercontent.com/3601775/229720997-8b849cd3-ba8f-485e-95ed-7d15289b0ae6.png">

**Please complete the following information:**
 - Operating System and version: gLinux
 - VS Code version: `Version: 1.77.0 Commit: 7f329fe6c66b0f86ae1574c2911b681ad5a45d63`
 - Dart extension version: `v3.63.20230303`
 - Dart/Flutter SDK version:  `Dart SDK version: 3.0.0-edge.f27548aa5aac3919cd5f279063b6a877f69aef32 (be) (Mon Mar 27 10:01:53 2023 +0000) on "linux_x64"`

**Comment by DanTup** [comment] 2023-04-04 09:32
I can reproduce this, and it seems to be because `test` is in a library that is marked as `@Deprecated`. The definition is in [package:test_core/lib/scaffolding.dart](https://github.com/dart-lang/test/blob/49f7e17a22a8366dfb2f324e651739fb702811f6/pkgs/test_core/lib/scaffolding.dart#L136) and [the top of that file has](https://github.com/dart-lang/test/blob/49f7e17a22a8366dfb2f324e651739fb702811f6/pkgs/test_core/lib/scaffolding.dart#L5):

```
@Deprecated('package:test_core is not intended for general use. '
    'Please use package:test.')
library test_core.scaffolding;
```

In the dartdoc on the `Deprecated` class it says:

```
/// `Deprecation applies transitively to parts of a deprecated feature:
///
///  - If a library is deprecated, so is every member of it.
```

So my feeling is that this is an incorrect use of `Deprecated` in `package:test_core`. The library is being marked as deprecated, when the intention is (presumably) that they only wanted to prevent direct imports of it.

I'm surprised this hasn't come up before though - apparently that `Deprecated` tag has been there [for at least 2 years](https://github.com/dart-lang/test/pull/1460#discussion_r594692975).

@natebosch @bwilkerson does my understanding above seem correct? Should this `Deprecated` tag be removed? I can't think of another way to structure this to block the import without doing this though (at least not without `package:test` importing from `lib/src` in `package_core` so the declarations could be moved to a private library that doesn't have Deprecated).

**Comment by bwilkerson** [comment] 2023-04-04 15:51
I don't know why it's being marked as deprecated, but I'm seeing the same behavior. We could try debugging it, or we could try bisecting to find out which CL caused the server to start having this behavior (I'm assuming that it hasn't always been this way, but I don't know that for sure).

**Comment by DanTup** [comment] 2023-04-04 15:54
> I don't know why it's being marked as deprecated

I can take a look, but first I'm trying to understand whether the question is "why is it deprecated in completion" or "why is it not deprecated in the diagnostics"?

The `Deprecated` class says "If a library is deprecated, so is every member of it" and it's not clear to me why that _wouldn't_ apply here. Are we missing a diagnostic that this is use of a deprecated function, or is there a rule for why it's not (which completion isn't matching)?

**Comment by bwilkerson** [comment] 2023-04-04 16:19
> I can take a look, but first I'm trying to understand whether the question is "why is it deprecated in completion" or "why is it not deprecated in the diagnostics"?

Yes. There's clearly a difference in the way these two features are handling deprecated code, and the real goal is to understand which is correct and how to make them consistent. Ideally they should be kept consistent by having an `isDeprecated` getter on `Element` that applies the rule that members of a deprecated element are deprecated, but we don't have that. All we have is `hasDeprecated` (which shouldn't be changed) that tells us whether the annotation is on that element.

> The Deprecated class says "If a library is deprecated, so is every member of it" and it's not clear to me why that wouldn't apply here. Are we missing a diagnostic that this is use of a deprecated function, or is there a rule for why it's not (which completion isn't matching)?

I that question is essentially equivalent to:

> Well, so if you re-export something, then in which library is it?

I don't know the intent of the annotation author, but the analyzer considers an element to be in the library in which it was declared, no matter how it was imported. It's possible that the analyzer's behavior doesn't match the annotation author's intent.

**Comment by DanTup** [comment] 2023-04-04 17:16
Who is best placed to make a decision about what is correct? It looks like @lrhn added most of the documentation on `Deprecated` (https://github.com/dart-lang/sdk/commit/36332f61888f9f3194aa0fc1ee9f052bece1ffba) so perhaps knows the answer (or at least has an opinion)?

**Comment by lrhn** [comment] 2023-04-05 19:12
The "correct" behavior around deprecation is that you should be warned if the deprecated declaration being deleted would cause an error in your program. That's the entirety of the intent.

If a library is deprecated, then "deleting the deprecated declaration" would mean removing the library file entirely.

That means that your `import` itself will cause a warning, whether you use anything from it or not.

Also every declaration that you access *only* through that import will also go away. Even if its provided through an export from another non-deprecated library, because the *export* is going away too. The declaration will still exist, but you don't have it in your import scope, so you accessing it will become an error.

The tricky part is when you get the same declaration through more than one import path.
Say you import "foo.dart" and "bar.dart", "foo.dart" exports `bar` from "bar.dart", and then "foo.dart" is deprecated.

In this case, you should probably *not* get a warning where you use `bar`. If "foo.dart" goes away, that reference will still work, because you have a non-deprecated path to `bar`.
(You still get a warning at the `import "foo.dart";`, but if you remove that import, there won't be any remaining problems about `bar`, it's still there through the `import "bar.dart";`.)

I think that should be reasonable to implement if you do it while resolving import scopes, but not trivial if you do it afterwards, because at that point you just know that `bar` is in your import scope from somewhere, and `bar` itself is not deprecated.

**Comment by DanTup** [comment] 2023-04-05 19:19
Thanks for the info! In that case, I think we should avoid changing anything until `package:test` is updated, because "fixing" this will result in every call to `group`/`test` generating unexpected warnings.

(I also wonder how many other projects might have code that would generate new warnings with this changed?)

@natebosch @jakemac53 does the above seem reasonable? Should I file an issue in https://github.com/dart-lang/test?

**Comment by jakemac53** [comment] 2023-04-05 19:46
Just to make sure I got this right, the suggestion is to essentially move these currently public imports from `test_core` and `test_api` into a `src/` library, and change the existing libraries to export those (and leave them deprecated)? And then in `test` we would export the non-deprecated `src` imports?

That does sound feasible to me, although we do try to avoid `src` imports even among our own packages, I believe that is largely why we have these deprecated libraries to begin with, its a clear public api but with a moderate discouragement for use.

But we could open an issue on `test` to discuss. It might end up being quite a lot of work.

**Comment by DanTup** [comment] 2023-04-05 20:13
> Just to make sure I got this right...

That's my understanding. It means `package:test` has to import from `package:test_core/src/` but I don't think that can be avoided without having a non-deprecated public library in `test_core` that exports them (which I presume you want to avoid).

I've opened https://github.com/dart-lang/test/issues/1990.

**Comment by DanTup** [comment] 2023-04-25 14:14
Now that `package:test` has changed to not have `group`/`test` in a deprecated library, I've opened https://github.com/dart-lang/sdk/issues/52163 since this will need fixing in the analyzer (although shipping a fix for it might be complicated if it will tell all users of older versions of `package:test` they're calling deprecated functions? 🤔).

**Closed by DanTup** 2023-04-25 14:14 UTC
Labels: is bug, blocked on dart / flutter, in editor, in lsp/analysis server
