### ISSUE TITLE
Tests fail to run for projects referencing flutter_test but not flutter in pubspec

### ISSUE THREAD

**Issue by shyndman** [Dart-Code/Dart-Code#1696] opened 2019-05-08 18:17 UTC
Hello there,

It appears that in order to use the run/debug functionality in a test, the project's pubspec requires a direct dependency on the Flutter SDK, whether or not the project uses Flutter. Omitting the flutter dependency outputs:

```
The Flutter SDK is not available.

Exited (1)
```

Setting `dart.flutterSdkPath` in `settings.json` also has no effect.

Shouldn't a dependency on the `test` package be enough? Should the user setting work?

**Comment by shyndman** [comment] 2019-05-08 18:30
Btw, running 3.0, but the problem appears in the previous two versions as well.

**Comment by DanTup** [comment] 2019-05-08 18:38
Can you clarify how you're running the test?

Also, please run the **Dart: Capture Logs** command, then try to run the test, then click **Stop Logging** and attach the log. It sounds like something is deciding that your project is Flutter when it shouldn't.

**Comment by shyndman** [comment] 2019-05-08 18:46
By pressing the little run/debug links that float above tests in the editor.

```
!! PLEASE REVIEW THIS LOG FOR SENSITIVE INFORMATION BEFORE SHARING !!

Dart Code extension: 3.0.0
Flutter extension: 3.0.0 (not activated)
VS Code: 1.33.1
Platform: mac
Workspace type: Fuchsia
Multi-root?: false
Dart SDK:
    Loc: /Users/xxxxxx/work-code/xxxxxxxxx/flutter/bin/cache/dart-sdk
    Ver: 2.3.0-edge.67df3ff878281bb24a80e3dff134d2ab4f091e1a
Flutter SDK:
    Loc: /Users/xxxxxx/work-code/xxxxxxxxx/flutter
    Ver: 1.5.9-pre.171
HTTP_PROXY: undefined
NO_PROXY: undefined

Wed May 08 2019 [11:44:50 GMT-0700 (PDT)] Log file started
[11:44:52 GMT-0700 (PDT)] [Analyzer] [Info] ==> {"id":"19","method":"analysis.getHover","params":{"file":"/Users/xxxxxx/work-code/xxxxxxxxx/xxxxxxx/view/test/views_test.dart","offset":476},"clientRequestTime":1557341092294}
[11:44:52 GMT-0700 (PDT)] [Analyzer] [Info] <== {"id":"19","result":{"hovers":[{"offset":475,"length":807,"staticType":"Map<String, Object>"}]}}
[11:44:53 GMT-0700 (PDT)] [Analyzer] [Info] ==> {"id":"20","method":"analysis.getHover","params":{"file":"/Users/xxxxxx/work-code/xxxxxxxxx/xxxxxxx/view/test/views_test.dart","offset":405},"clientRequestTime":1557341093160}
[11:44:53 GMT-0700 (PDT)] [Analyzer] [Info] <== {"id":"20","result":{"hovers":[{"offset":403,"length":4,"containingLibraryPath":"/Users/xxxxxx/.pub-cache/hosted/pub.dartlang.org/test_core-0.2.5/lib/test_core.dart","containingLibraryName":"","dartdoc":"Creates a new test case with the given description (converted to a string)\nand body.\n\nThe description will be added to the descriptions of any surrounding\n[group]s. If [testOn] is passed, it's parsed as a [platform selector][]; the\ntest will only be run on matching platforms.\n\n[platform selector]: https://github.com/dart-lang/test/tree/master/pkgs/test#platform-selectors\n\nIf [timeout] is passed, it's used to modify or replace the default timeout\nof 30 seconds. Timeout modifications take precedence in suite-group-test\norder, so [timeout] will also modify any timeouts set on the group or suite.\n\nIf [skip] is a String or `true`, the test is skipped. If it's a String, it\nshould explain why the test is skipped; this reason will be printed instead\nof running the test.\n\nIf [tags] is passed, it declares user-defined tags that are applied to the\ntest. These tags can be used to select or skip the test on the command line,\nor to do bulk test configuration. All tags should be declared in the\n[package configuration file][configuring tags]. The parameter can be an\n[Iterable] of tag names, or a [String] representing a single tag.\n\nIf [retry] is passed, the test will be retried the provided number of times\nbefore being marked as a failure.\n\n[configuring tags]: https://github.com/dart-lang/test/blob/master/doc/package_config.md#configuring-tags\n\n[onPlatform] allows tests to be configured on a platform-by-platform\nbasis. It's a map from strings that are parsed as [PlatformSelector]s to\nannotation classes: [Timeout], [Skip], or lists of those. These\nannotations apply only on the given platforms. For example:\n\n    test(\"potentially slow test\", () {\n      // ...\n    }, onPlatform: {\n      // This test is especially slow on Windows.\n      \"wi…
[11:44:53 GMT-0700 (PDT)] [General] [Info] Starting debug session...
[11:44:53 GMT-0700 (PDT)] [General] [Info]     workspace: /Users/xxxxxx/work-code/xxxxxxxxx/xxxxxxx/view
[11:44:53 GMT-0700 (PDT)] [General] [Info]     program  : /Users/xxxxxx/work-code/xxxxxxxxx/xxxxxxx/view/test/views_test.dart
[11:44:53 GMT-0700 (PDT)] [General] [Info] Using workspace as cwd: /Users/xxxxxx/work-code/xxxxxxxxx/xxxxxxx/view
[11:44:53 GMT-0700 (PDT)] [General] [Info] Non-Dart Project (/Users/xxxxxx/work-code/xxxxxxxxx/xxxxxxx/view/test/views_test.dart) not recognised as Flutter or FlutterWeb, will use Dart debugger
[11:44:53 GMT-0700 (PDT)] [General] [Info] Detected launch project as Dart
[11:44:53 GMT-0700 (PDT)] [General] [Info] Detected launch project as a Test project
[11:44:53 GMT-0700 (PDT)] [General] [Info] Using PubTest debug adapter for this session
[11:44:53 GMT-0700 (PDT)] [General] [Info] Checking for errors before launching
[11:44:53 GMT-0700 (PDT)] [General] [Info] Debug session starting...
    {
        "args": [
            "--name",
            "^Views Text$"
        ],
        "name": "Tests",
        "noDebug": true,
        "program": "/Users/xxxxxx/work-code/xxxxxxxxx/xxxxxxx/view/test/views_test.dart",
        "request": "launch",
        "type": "dart",
        "cwd": "/Users/xxxxxx/work-code/xxxxxxxxx/xxxxxxx/view",
        "vmAdditionalArgs": [],
        "vmServicePort": 0,
        "dartPath": "/Users/xxxxxx/work-code/xxxxxxxxx/flutter/bin/cache/dart-sdk/bin/dart",
        "maxLogLineLength": 2000,
        "pubPath": "/Users/xxxxxx/work-code/xxxxxxxxx/flutter/bin/cache/dart-sdk/bin/pub",
        "pubSnapshotPath": "/Users/xxxxxx/work-code/xxxxxxxxx/flutter/bin/cache/dart-sdk/bin/snapshots/pub.dart.snapshot",
        "debugSdkLibraries": false,
        "debugExternalLibraries": true,
        "evaluateGettersInDebugViews": true,
        "debugServer": 59110,
        "debuggerType": 1
    }
[11:44:53 GMT-0700 (PDT)] [PubTest] [Info] Spawning /Users/xxxxxx/work-code/xxxxxxxxx/flutter/bin/cache/dart-sdk/bin/dart with args ["--enable-vm-service=0","--pause_isolates_on_start=true","/Users/xxxxxx/work-code/xxxxxxxxx/flutter/bin/cache/dart-sdk/bin/snapshots/pub.dart.snapshot","run","test","-r","json","-j1","test/views_test.dart","--name","^Views Text$"]
[11:44:53 GMT-0700 (PDT)] [PubTest] [Info] ..  in /Users/xxxxxx/work-code/xxxxxxxxx/xxxxxxx/view
[11:44:53 GMT-0700 (PDT)] [PubTest] [Info]     PID: 65552
[11:44:53 GMT-0700 (PDT)] [PubTest] [Info] <== Observatory listening on http://127.0.0.1:59119/W2gxxOZlKqE=/
[11:44:53 GMT-0700 (PDT)] [Observatory] [Info] Connecting to VM Service at http://127.0.0.1:59119/W2gxxOZlKqE=/ws
[11:44:53 GMT-0700 (PDT)] [Observatory] [Info] ==> {"id":"0","method":"streamListen","params":{"streamId":"Isolate"}}
[11:44:53 GMT-0700 (PDT)] [Observatory] [Info] ==> {"id":"1","method":"streamListen","params":{"streamId":"Extension"}}
[11:44:53 GMT-0700 (PDT)] [Observatory] [Info] ==> {"id":"2","method":"streamListen","params":{"streamId":"Debug"}}
[11:44:53 GMT-0700 (PDT)] [Observatory] [Info] ==> {"id":"3","method":"streamListen","params":{"streamId":"_Service"}}
[11:44:53 GMT-0700 (PDT)] [Observatory] [Info] ==> {"id":"4","method":"getVM"}
[11:44:54 GMT-0700 (PDT)] [Observatory] [Info] <== {"jsonrpc":"2.0","id":"0","result":{"type":"Success"}}
[11:44:54 GMT-0700 (PDT)] [Observatory] [Info] <== {"jsonrpc":"2.0","id":"1","result":{"type":"Success"}}
[11:44:54 GMT-0700 (PDT)] [Observatory] [Info] <== {"jsonrpc":"2.0","id":"2","result":{"type":"Success"}}
[11:44:54 GMT-0700 (PDT)] [Observatory] [Info] <== {"jsonrpc":"2.0","id":"3","result":{"type":"Success"}}
[11:44:54 GMT-0700 (PDT)] [Observatory] [Info] <== {"jsonrpc":"2.0", "result":{"type":"VM","name":"vm","architectureBits":64,"targetCPU":"x64","hostCPU":"Intel(R) Core(TM) i7-7660U CPU @ 2.50GHz","version":"2.3.0-dev.0.5.flutter-67df3ff878 (Sun May 5 15:43:29 2019 +0000) on \"macos_x64\"","_profilerMode":"Dart","_nativeZoneMemoryUsage":0,"pid":65615,"startTime":1557341093800,"_embedder":"Dart VM","_maxRSS":94949376,"_currentRSS":85987328,"isolates":[{"type":"@Isolate","fixedId":true,"id":"isolates\/98505576","name":"main","number":"98505576"}]},"id":"4"}
[11:44:54 GMT-0700 (PDT)] [Observatory] [Info] ==> {"id":"5","method":"getIsolate","params":{"isolateId":"isolates/98505576"}}
[11:44:54 GMT-0700 (PDT)] [Observatory] [Info] <== {"jsonrpc":"2.0", "result":{"type":"Isolate","fixedId":true,"id":"isolates\/98505576","name":"main","number":"98505576","_originNumber":"98505576","startTime":1557341093802,"_heaps":{"new":{"type":"HeapSpace","name":"new","vmName":"Scavenger","collections":0,"avgCollectionPeriodMillis":0.0,"used":524288,"capacity":2097152,"external":0,"time":0.0},"old":{"type":"HeapSpace","name":"old","vmName":"PageSpace","collections":0,"used":8625616,"capacity":9150464,"external":0,"time":0.0,"avgCollectionPeriodMillis":0.0}},"runnable":true,"livePorts":1,"pauseOnExit":false,"_isReloading":false,"pauseEvent":{"type":"Event","kind":"PauseStart","isolate":{"type":"@Isolate","fixedId":true,"id":"isolates\/98505576","name":"main","number":"98505576"},"timestamp":1557341093866},"rootLib":{"type":"@Library","fixedId":true,"id":"libraries\/@19227512","name":"","uri":"file:\/\/\/b\/s\/w\/ir\/k\/src\/third_party\/dart\/third_party\/pkg\/pub\/bin\/pub.dart"},"_numZoneHandles":10,"_numScopedHandles":46,"libraries":[{"type":"@Library","fixedId":true,"id":"libraries\/@0150898","name":"dart.core","uri":"dart:core"},{"type":"@Library","fixedId":true,"id":"libraries\/@1026248","name":"dart.isolate","uri":"dart:isolate"},{"type":"@Library","fixedId":true,"id":"libraries\/@2408521","name":"dart.mirrors","uri":"dart:mirrors"},{"type":"@Library","fixedId":true,"id":"libraries\/@3220832","name":"dart.collection","uri":"dart:collection"},{"type":"@Library","fixedId":true,"id":"libraries\/@4383715","name":"dart.developer","uri":"dart:developer"},{"type":"@Library","fixedId":true,"id":"libraries\/@5320332","name":"nativewrappers","uri":"dart:nativewrappers"},{"type":"@Library","fixedId":true,"id":"libraries\/@6027147","name":"dart.typed_data","uri":"dart:typed_data"},{"type":"@Library","fixedId":true,"id":"libraries\/@7050071","name":"dart.ffi","uri":"dart:ffi"},{"type":"@Library","fixedId":true,"id":"libraries\/@8048458","name":"dart.async","uri":"dart:async"},{"type":"@Library","fixedId":true,"id":…
[11:44:54 GMT-0700 (PDT)] [Observatory] [Info] ==> {"id":"6","method":"setExceptionPauseMode","params":{"isolateId":"isolates/98505576","mode":"None"}}
[11:44:54 GMT-0700 (PDT)] [Observatory] [Info] <== {"jsonrpc":"2.0","method":"streamNotify","params":{"streamId":"Debug","event":{"type":"Event","kind":"_DebuggerSettingsUpdate","isolate":{"type":"@Isolate","fixedId":true,"id":"isolates\/98505576","name":"main","number":"98505576"},"timestamp":1557341094018,"_debuggerSettings":{"_exceptions":"none"}}}}
[11:44:54 GMT-0700 (PDT)] [Observatory] [Info] <== {"jsonrpc":"2.0", "result":{"type":"Success"},"id":"6"}
[11:44:54 GMT-0700 (PDT)] [Observatory] [Info] ==> {"id":"7","method":"setExceptionPauseMode","params":{"isolateId":"isolates/98505576","mode":"None"}}
[11:44:54 GMT-0700 (PDT)] [Observatory] [Info] <== {"jsonrpc":"2.0","method":"streamNotify","params":{"streamId":"Debug","event":{"type":"Event","kind":"_DebuggerSettingsUpdate","isolate":{"type":"@Isolate","fixedId":true,"id":"isolates\/98505576","name":"main","number":"98505576"},"timestamp":1557341094025,"_debuggerSettings":{"_exceptions":"none"}}}}
[11:44:54 GMT-0700 (PDT)] [Observatory] [Info] <== {"jsonrpc":"2.0", "result":{"type":"Success"},"id":"7"}
[11:44:54 GMT-0700 (PDT)] [Observatory] [Info] ==> {"id":"8","method":"resume","params":{"isolateId":"isolates/98505576"}}
[11:44:54 GMT-0700 (PDT)] [Observatory] [Info] <== {"jsonrpc":"2.0","method":"streamNotify","params":{"streamId":"Debug","event":{"type":"Event","kind":"Resume","isolate":{"type":"@Isolate","fixedId":true,"id":"isolates\/98505576","name":"main","number":"98505576"},"timestamp":1557341094029}}}
[11:44:54 GMT-0700 (PDT)] [Observatory] [Info] <== {"jsonrpc":"2.0", "result":{"type":"Success"},"id":"8"}
[11:44:54 GMT-0700 (PDT)] [Observatory] [Info] <== {"jsonrpc":"2.0","method":"streamNotify","params":{"streamId":"Isolate","event":{"type":"Event","kind":"ServiceExtensionAdded","isolate":{"type":"@Isolate","fixedId":true,"id":"isolates\/98505576","name":"main","number":"98505576"},"timestamp":1557341094044,"extensionRPC":"ext.dart.io.getOpenFiles"}}}
[11:44:54 GMT-0700 (PDT)] [Observatory] [Info] <== {"jsonrpc":"2.0","method":"streamNotify","params":{"streamId":"Isolate","event":{"type":"Event","kind":"ServiceExtensionAdded","isolate":{"type":"@Isolate","fixedId":true,"id":"isolates\/98505576","name":"main","number":"98505576"},"timestamp":1557341094044,"extensionRPC":"ext.dart.io.getFileByID"}}}
[11:44:54 GMT-0700 (PDT)] [PubTest] [Error] The Flutter SDK is not available.
[11:44:54 GMT-0700 (PDT)] [General] [Error] [PubTest] The Flutter SDK is not available.
[11:44:54 GMT-0700 (PDT)] [PubTest] [Error] 
[11:44:54 GMT-0700 (PDT)] [General] [Error] [PubTest]
[11:44:54 GMT-0700 (PDT)] [Observatory] [Info] Observatory connection closed: 1006 ()
[11:44:54 GMT-0700 (PDT)] [Observatory] [Info] Process exited (1)
[11:44:54 GMT-0700 (PDT)] [Observatory] [Info] Disconnect requested!
[11:44:54 GMT-0700 (PDT)] [Observatory] [Info] TERM: Going to terminate with SIGINT...
[11:44:54 GMT-0700 (PDT)] [Observatory] [Info] TERM: Removing all stored data...
[11:44:54 GMT-0700 (PDT)] [Observatory] [Info] TERM: Waiting for process to finish...
[11:44:54 GMT-0700 (PDT)] [Observatory] [Info] TERM: Disconnecting...
[11:44:54 GMT-0700 (PDT)] [Analyzer] [Info] ==> {"id":"21","method":"analysis.getHover","params":{"file":"/Users/xxxxxx/work-code/xxxxxxxxx/xxxxxxx/view/test/views_test.dart","offset":598},"clientRequestTime":1557341094849}
[11:44:54 GMT-0700 (PDT)] [Analyzer] [Info] <== {"id":"21","result":{"hovers":[{"offset":593,"length":5,"staticType":"String"}]}}
Wed May 08 2019 [11:44:56 GMT-0700 (PDT)] Log file ended
```

**Comment by DanTup** [comment] 2019-05-08 19:22
Ah, ok - so it looks like we've detected your workspace as being in the Fuchsia tree (hopefully that's correct) so selected the Flutter SDK. However it seems like the version of `pub` inside a Flutter SDK might not work if invoked directly (instead, expecting to be called through `flutter packages`).

I'll do some testing when back at my main machine tomorrow, but if it's always the case that a Flutter-provided Dart SDK cannot have `pub` run directly, we can change to run through `flutter packages` (we already know we've selected a Flutter SDK here) .

I don't think there's an easy workaround (besides temporarily moving the project outside of the Fuchsia tree so it opens as a Dart project with a standard Dart SDK) but if I can get a fix I'll make a preview build you can use until it ships in a stable release.

**Comment by shyndman** [comment] 2019-05-08 23:40
Yes, I'm in the Fuchsia tree.

Thanks for looking into this.

**Comment by DanTup** [comment] 2019-05-09 10:05
Interestingly, in a small (non-Fuchsia) sample I don't see this behaviour. If I try to run non-Flutter tests through Flutter's version of Dart is just works:

```
Spawning /Users/dantup/Dev/Google/flutter/bin/cache/dart-sdk/bin/dart with args ["--enable-vm-service=0","--pause_isolates_on_start=true","/Users/dantup/Dev/Google/flutter/bin/cache/dart-sdk/bin/snapshots/pub.dart.snapshot","run","test","-r","json","-j1","test/one_test.dart","--name","^test$"]
..  in /Users/dantup/Desktop/Dart Sample
    PID: 11575
<== Observatory listening on http://127.0.0.1:50741/LMjBa4BlKEs=/
<== {"protocolVersion":"0.1.1","runnerVersion":"1.5.1+1","pid":11689,"type":"start","time":0}
<== {"suite":{"id":0,"platform":"vm","path":"test/one_test.dart"},"type":"suite","time":0}
<== {"test":{"id":1,"name":"loading test/one_test.dart","suiteID":0,"groupIDs":[],"metadata":{"skip":false,"skipReason":null},"line":null,"column":null,"url":null},"type":"testStart","time":1}
<== {"count":1,"type":"allSuites","time":4}
```

I'll see if I can find something in the Fuchsia tree that repros it.

**Comment by DanTup** [comment] 2019-05-09 10:15
Ok, I think this might be down to something in your `pubspec.yaml`/`.packages`. It seems that when `pub` runs, it checks the pubspec to see whether or not the required SDK is available (and by available, it means for Flutter you must be running via the `flutter` command).

Can you try running `pub run test test/views_test.dart` from the terminal, and confirm if you see the same thing?

If so, check whether the `.packages` file or `pubspec.yaml` might have anything else in it that would indicate that this is a Flutter project.

Otherwise, are you able to give me instructions to get the same thing set up locally? (You can grab me on chat/email dantup@ if easier or if you can't post here).

**Comment by shyndman** [comment] 2019-05-09 18:59
Confirmed that `pub run test` does not work.

It looks like I have a transitive dependency on flutter. It appears in my pubspec.lock and .packages.

**Comment by DanTup** [comment] 2019-05-13 10:53
@shyndman did you track this down? I saw a notification from a comment that I think you've deleted - not sure if you solved it or the comment was wrong. Feel free to grab me me in Hangouts or email (dantup@) if easier to debug that way.

**Comment by shyndman** [comment] 2019-05-14 22:52
Hi Dan,

I got it. `flutter_test` was being referred to in pubspecs it shouldn't have been. Once removed, `pub run test ...` works as expected, as does VSCode.

Thanks for your help.

**Comment by DanTup** [comment] 2019-05-15 06:44
Great, thanks for the update. I'll keep this open to investigate if we can handle this better (eg. detect a reference to flutter_test but not flutter in pubspec) and give a suitable error.

**Comment by DanTup** [comment] 2019-05-20 11:48
I actually can't reproduce this at all. The only way I can get it to fall back to the Pub test runner is by not having `sdk: flutter` in my pubspec. However I can't get Pub to complain about the missing SDK unless I do have it there.

I'll close this since it seems like an edge case, but if you have an easy repro for it, I would be interested in better understanding what was going on!

**Closed by DanTup** 2019-05-20 11:48 UTC
Labels: in flutter, in testing, is bug
