### ISSUE TITLE
[Analyzer] [Error] Unhandled exception UnimplementedError: TODO(paulberry)

### ISSUE THREAD

**Issue by JCKodel** [Dart-Code/Dart-Code#4407] opened 2023-02-26 22:04 UTC
**Describe the bug**
The Dart Analysis Server crashed 5 times in the last 3 minutes. The server will not be restarted.

**To Reproduce**
I was typing this class:

```dart
class _EvaWidgetsBindingObserver extends WidgetsBindingObserver {
  @override
  void didChangeAppLifecycleState(AppLifecycleState state) {
    switch (state) {
      case AppLifecycleState. // It crashes here
    }
  }
}
```

<details><summary>Log</summary>

```
[6:56:23 PM] [General] [Info] Searching for SDKs...
[6:56:23 PM] [General] [Info] Environment PATH:
[6:56:23 PM] [General] [Info]     /usr/local/bin
[6:56:23 PM] [General] [Info]     /usr/bin
[6:56:23 PM] [General] [Info]     /bin
[6:56:23 PM] [General] [Info]     /usr/sbin
[6:56:23 PM] [General] [Info]     /sbin
[6:56:23 PM] [General] [Info]     /Library/Apple/usr/bin
[6:56:23 PM] [General] [Info]     /usr/local/opt/ruby/bin
[6:56:23 PM] [General] [Info]     /Users/jckodel/fvm/default/bin
[6:56:23 PM] [General] [Info]     /Users/jckodel/Library/Android/sdk/platform-tools
[6:56:23 PM] [General] [Info]     /Users/jckodel/.pub-cache/bin
[6:56:23 PM] [General] [Info]     /Users/jckodel/fvm/versions/3.7.1/bin
[6:56:23 PM] [General] [Info] Took 50ms to search for projects (5 levels)
[6:56:23 PM] [General] [Info] Took 8ms to filter out excluded projects (0 exclusion rules)
[6:56:23 PM] [General] [Info] Found Flutter project at /Users/jckodel/Desktop/eva/packages/eva/example:
			Mobile? true
			Web? false
			Create Trigger? false
			Flutter Repo? false
[6:56:23 PM] [General] [Info] Searching for flutter
[6:56:23 PM] [General] [Info]     Looking for flutter in:
[6:56:23 PM] [General] [Info]         /Users/jckodel/Desktop/eva/packages/eva/example
[6:56:23 PM] [General] [Info]         /Users/jckodel/Desktop/eva/packages/eva/example/bin
[6:56:23 PM] [General] [Info]         /Users/jckodel/fvm/versions/3.8.0-10.1.pre/bin/
[6:56:23 PM] [General] [Info]         /Users/jckodel/Desktop/eva/packages/eva/example/.flutter
[6:56:23 PM] [General] [Info]         /Users/jckodel/Desktop/eva/packages/eva/example/.flutter/bin
[6:56:23 PM] [General] [Info]         /Users/jckodel/Desktop/eva/packages/eva/example/vendor/flutter
[6:56:23 PM] [General] [Info]         /Users/jckodel/Desktop/eva/packages/eva/example/vendor/flutter/bin
[6:56:23 PM] [General] [Info]         /Users/jckodel/flutter-sdk
[6:56:23 PM] [General] [Info]         /Users/jckodel/flutter-sdk/bin
[6:56:23 PM] [General] [Info]         /google/flutter
[6:56:23 PM] [General] [Info]         /google/flutter/bin
[6:56:23 PM] [General] [Info]         /usr/local/bin
[6:56:23 PM] [General] [Info]         /usr/bin
[6:56:23 PM] [General] [Info]         /bin
[6:56:23 PM] [General] [Info]         /usr/sbin
[6:56:23 PM] [General] [Info]         /sbin
[6:56:23 PM] [General] [Info]         /Library/Apple/usr/bin
[6:56:23 PM] [General] [Info]         /usr/local/opt/ruby/bin
[6:56:23 PM] [General] [Info]         /Users/jckodel/fvm/default/bin
[6:56:23 PM] [General] [Info]         /Users/jckodel/Library/Android/sdk/platform-tools
[6:56:23 PM] [General] [Info]         /Users/jckodel/Library/Android/sdk/platform-tools/bin
[6:56:23 PM] [General] [Info]         /Users/jckodel/.pub-cache/bin
[6:56:23 PM] [General] [Info]         /Users/jckodel/fvm/versions/3.7.1/bin
[6:56:23 PM] [General] [Info]     Found at:
[6:56:23 PM] [General] [Info]         /Users/jckodel/fvm/versions/3.8.0-10.1.pre/bin/
[6:56:23 PM] [General] [Info]         /Users/jckodel/fvm/default/bin
[6:56:23 PM] [General] [Info] Following symlink: /Users/jckodel/fvm/default/bin/flutter ==> /Users/jckodel/fvm/versions/3.8.0-10.1.pre/bin/flutter
[6:56:23 PM] [General] [Info]     Candidate paths to be post-filtered:
[6:56:23 PM] [General] [Info]         /Users/jckodel/fvm/versions/3.8.0-10.1.pre
[6:56:23 PM] [General] [Info]         /Users/jckodel/fvm/versions/3.8.0-10.1.pre
[6:56:23 PM] [General] [Info]     Found at /Users/jckodel/fvm/versions/3.8.0-10.1.pre
[6:56:23 PM] [General] [Info]     Returning SDK path /Users/jckodel/fvm/versions/3.8.0-10.1.pre for flutter
[6:56:23 PM] [General] [Info] Searching for dart
[6:56:23 PM] [General] [Info]     Looking for dart in:
[6:56:23 PM] [General] [Info]         /Users/jckodel/fvm/versions/3.8.0-10.1.pre/bin/cache/dart-sdk
[6:56:23 PM] [General] [Info]         /Users/jckodel/fvm/versions/3.8.0-10.1.pre/bin/cache/dart-sdk/bin
[6:56:23 PM] [General] [Info]         /usr/local/bin
[6:56:23 PM] [General] [Info]         /usr/bin
[6:56:23 PM] [General] [Info]         /bin
[6:56:23 PM] [General] [Info]         /usr/sbin
[6:56:23 PM] [General] [Info]         /sbin
[6:56:23 PM] [General] [Info]         /Library/Apple/usr/bin
[6:56:23 PM] [General] [Info]         /usr/local/opt/ruby/bin
[6:56:23 PM] [General] [Info]         /Users/jckodel/fvm/default/bin
[6:56:23 PM] [General] [Info]         /Users/jckodel/Library/Android/sdk/platform-tools
[6:56:23 PM] [General] [Info]         /Users/jckodel/Library/Android/sdk/platform-tools/bin
[6:56:23 PM] [General] [Info]         /Users/jckodel/.pub-cache/bin
[6:56:23 PM] [General] [Info]         /Users/jckodel/fvm/versions/3.7.1/bin
[6:56:23 PM] [General] [Info]         /Users/jckodel/fvm/versions/3.8.0-10.1.pre/bin/cache/dart-sdk
[6:56:23 PM] [General] [Info]         /Users/jckodel/fvm/versions/3.8.0-10.1.pre/bin/cache/dart-sdk/bin
[6:56:23 PM] [General] [Info]     Found at:
[6:56:23 PM] [General] [Info]         /Users/jckodel/fvm/versions/3.8.0-10.1.pre/bin/cache/dart-sdk/bin
[6:56:23 PM] [General] [Info]         /Users/jckodel/fvm/default/bin
[6:56:23 PM] [General] [Info]         /Users/jckodel/fvm/versions/3.8.0-10.1.pre/bin/cache/dart-sdk/bin
[6:56:23 PM] [General] [Info] Following symlink: /Users/jckodel/fvm/default/bin/dart ==> /Users/jckodel/fvm/versions/3.8.0-10.1.pre/bin/dart
[6:56:23 PM] [General] [Info]     Candidate paths to be post-filtered:
[6:56:23 PM] [General] [Info]         /Users/jckodel/fvm/versions/3.8.0-10.1.pre/bin/cache/dart-sdk
[6:56:23 PM] [General] [Info]         /Users/jckodel/fvm/versions/3.8.0-10.1.pre
[6:56:23 PM] [General] [Info]         /Users/jckodel/fvm/versions/3.8.0-10.1.pre/bin/cache/dart-sdk
[6:56:23 PM] [General] [Info]     Found at /Users/jckodel/fvm/versions/3.8.0-10.1.pre/bin/cache/dart-sdk
[6:56:23 PM] [General] [Info]     Returning SDK path /Users/jckodel/fvm/versions/3.8.0-10.1.pre/bin/cache/dart-sdk for dart
[6:56:23 PM] [General] [Info] Experiment random number is 67 for experiment 'sdkDaps'. Experiment is enabled for <= 10
[6:56:23 PM] [General] [Info] Experiment 'sdkDaps' does not apply and will not be activated
[6:56:23 PM] [General] [Info] !! PLEASE REVIEW THIS LOG FOR SENSITIVE INFORMATION BEFORE SHARING !!

Dart Code extension: 3.58.0
Flutter extension: 3.58.0 (not activated)

App: Visual Studio Code
Version: 1.75.1
Platform: mac

Workspace type: Flutter
Analyzer type: LSP
Multi-root?: false

Dart SDK:
    Loc: /Users/jckodel/fvm/versions/3.8.0-10.1.pre/bin/cache/dart-sdk
    Ver: 3.0.0-218.1.beta
Flutter SDK:
    Loc: /Users/jckodel/fvm/versions/3.8.0-10.1.pre
    Ver: 3.8.0-10.1.pre

HTTP_PROXY: undefined
NO_PROXY: undefin…
[6:56:23 PM] [FlutterDaemon] [Info] Spawning /Users/jckodel/fvm/versions/3.8.0-10.1.pre/bin/flutter with args ["daemon"]
[6:56:23 PM] [FlutterDaemon] [Info] ..  in /Users/jckodel/fvm/versions/3.8.0-10.1.pre
[6:56:23 PM] [FlutterDaemon] [Info] ..  with {"toolEnv":{"FLUTTER_HOST":"VSCode","PUB_ENVIRONMENT":"vscode.dart-code"}}
[6:56:23 PM] [FlutterDaemon] [Info]     PID: 22411
[6:56:23 PM] [FlutterDaemon] [Info] ==> [{"id":"1","method":"emulator.getEmulators"}]
[6:56:23 PM] [DevTools] [Info] Spawning /Users/jckodel/fvm/versions/3.8.0-10.1.pre/bin/cache/dart-sdk/bin/dart with args ["devtools","--machine","--try-ports","10","--allow-embedding"]
[6:56:23 PM] [DevTools] [Info] ..  with {"toolEnv":{"FLUTTER_HOST":"VSCode","PUB_ENVIRONMENT":"vscode.dart-code"}}
[6:56:23 PM] [DevTools] [Info]     PID: 22411
[6:56:23 PM] [Analyzer] [Info] Spawning /Users/jckodel/fvm/versions/3.8.0-10.1.pre/bin/cache/dart-sdk/bin/dart with args ["language-server","--protocol=lsp","--client-id=VS-Code","--client-version=3.58.0"]
[6:56:23 PM] [Analyzer] [Info]     PID: 22419
[6:56:23 PM] [General] [Info] Returning cached results for project search
[6:56:23 PM] [General] [Info] Activating Flutter extension for Flutter project...
[6:56:23 PM] [General] [Info] Extension:Startup timing: 114ms
[6:56:23 PM] [General] [Info] Version last used for Pub is 3.0.0-218.1.beta (3.0.0), current is 3.0.0-218.1.beta (3.0.0)
[6:56:23 PM] [General] [Info] Found 0 folders requiring "pub get" or "pub upgrade":
[6:56:23 PM] [Analyzer] [Info] ==> Content-Length: 6400
[6:56:23 PM] [Analyzer] [Info] ==> {"jsonrpc":"2.0","id":0,"method":"initialize","params":{"processId":22411,"clientInfo":{"name":"Visual Studio Code","version":"1.75.1"},"locale":"en-us","rootPath":"/Users/jckodel/Desktop/eva/packages/eva/example","rootUri":"file:///Users/jckodel/Desktop/eva/packages/eva/example","capabilities":{"workspace":{"applyEdit":true,"workspaceEdit":{"documentChanges":true,"resourceOperations":["create","rename","delete"],"failureHandling":"textOnlyTransactional","normalizesLineEndings":true,"changeA…
[6:56:23 PM] [DevTools] [Info] <== {"event":"server.started","method":"server.started","params":{"host":"127.0.0.1","port":9100,"pid":22418,"protocolVersion":"1.1.0"}}
[6:56:23 PM] [General] [Info] Loaded 20000 from vscode-userdata:/Users/jckodel/Library/Application%20Support/Code/User/globalStorage/dart-code.dart-code/package_cache.json
[6:56:23 PM] [Analyzer] [Info] <== Content-Length: 433
Content-Type: application/vscode-jsonrpc; charset=utf-8

{"id":0,"jsonrpc":"2.0","result":{"capabilities":{"executeCommandProvider":{"commands":["edit.sortMembers","edit.organizeImports","edit.fixAll","edit.sendWorkspaceEdit","refactor.perform","move_top_level_to_file"],"workDoneProgress":true},"workspace":{"workspaceFolders":{"changeNotifications":true,"supported":true}},"workspaceSymbolProvider":true},"serverInfo":{"name":"Dart SDK LSP Analysis Server","version":"3.0…
[6:56:23 PM] [General] [Info] !! PLEASE REVIEW THIS LOG FOR SENSITIVE INFORMATION BEFORE SHARING !!

Dart Code extension: 3.58.0
Flutter extension: 3.58.0 (activated)

App: Visual Studio Code
Version: 1.75.1
Platform: mac

Workspace type: Flutter
Analyzer type: LSP
Multi-root?: false

Dart SDK:
    Loc: /Users/jckodel/fvm/versions/3.8.0-10.1.pre/bin/cache/dart-sdk
    Ver: 3.0.0-218.1.beta
Flutter SDK:
    Loc: /Users/jckodel/fvm/versions/3.8.0-10.1.pre
    Ver: 3.8.0-10.1.pre

HTTP_PROXY: undefined
NO_PROXY: undefined
[6:56:23 PM] [Analyzer] [Info] ==> Content-Length: 86
[6:56:23 PM] [Analyzer] [Info] ==> {"jsonrpc":"2.0","method":"initialized","params":{},"clientRequestTime":1677448583892}
[6:56:23 PM] [General] [Info] Analyzer:Startup timing: 794ms
[6:56:23 PM] [FlutterDaemon] [Info] <== [{"event":"daemon.connected","params":{"version":"0.6.1","pid":22417}}]
[6:56:23 PM] [FlutterDaemon] [Info] ==> [{"id":"2","method":"device.enable"}]
[6:56:23 PM] [Analyzer] [Info] <== Content-Length: 186
Content-Type: application/vscode-jsonrpc; charset=utf-8
[6:56:23 PM] [Analyzer] [Info] <== {"id":1,"jsonrpc":"2.0","method":"workspace/configuration","params":{"items":[{"scopeUri":"file:///Users/jckodel/Desktop/eva/packages/eva/example","section":"dart"},{"section":"dart"}]}}
[6:56:23 PM] [Analyzer] [Info] ==> Content-Length: 6859
[6:56:23 PM] [Analyzer] [Info] ==> {"jsonrpc":"2.0","id":1,"result":[{"additionalAnalyzerFileExtensions":["drift"],"analysisExcludedFolders":[],"analyzeAngularTemplates":true,"analyzerAdditionalArgs":[],"analyzerDiagnosticsPort":null,"analyzerPath":null,"analyzerSshHost":null,"analyzerVmServicePort":null,"notifyAnalyzerErrors":true,"onlyAnalyzeProjectsWithOpenFiles":false,"showTodos":true,"useLegacyAnalyzerProtocol":false,"updateDevTools":true,"devToolsBrowser":"chrome","devToolsPort":null,"devToolsReuseWindows":true,"devTool…
[6:56:23 PM] [FlutterDaemon] [Info] <== [{"event":"daemon.logMessage","params":{"level":"status","message":"Starting device daemon..."}}]
[6:56:23 PM] [Analyzer] [Info] <== Content-Length: 5082
Content-Type: application/vscode-jsonrpc; charset=utf-8

{"id":2,"jsonrpc":"2.0","method":"client/registerCapability","params":{"registrations":[{"id":"0","method":"textDocument/didOpen","registerOptions":{"documentSelector":[{"language":"dart","scheme":"file"},{"language":"yaml","pattern":"**/pubspec.yaml","scheme":"file"},{"language":"yaml","pattern":"**/analysis_options.yaml","scheme":"file"},{"language":"yaml","pattern":"**/lib/fix_data.yaml","scheme":"file"}]}},{…
[6:56:24 PM] [Analyzer] [Info] ==> Content-Length: 72
[6:56:24 PM] [Analyzer] [Info] ==> {"jsonrpc":"2.0","id":2,"result":null,"clientRequestTime":1677448584014}
[6:56:24 PM] [Analyzer] [Info] ==> Content-Length: 2524
[6:56:24 PM] [Analyzer] [Info] ==> {"jsonrpc":"2.0","method":"textDocument/didOpen","params":{"textDocument":{"uri":"file:///Users/jckodel/Desktop/eva/packages/eva/example/lib/eva/eva.dart","languageId":"dart","version":1,"text":"import 'dart:isolate';\n\nimport 'package:flutter/widgets.dart';\n\nimport 'environment/environment.dart';\nimport 'events/eva_ready_event.dart';\nimport 'events/event.dart';\nimport 'log/log.dart';\n\nclass _EvaWidgetsBindingObserver extends WidgetsBindingObserver {\n  @override\n  void didChangeApp…
[6:56:24 PM] [Analyzer] [Info] ==> Content-Length: 205
[6:56:24 PM] [Analyzer] [Info] ==> {"jsonrpc":"2.0","id":1,"method":"textDocument/documentSymbol","params":{"textDocument":{"uri":"file:///Users/jckodel/Desktop/eva/packages/eva/example/lib/eva/eva.dart"}},"clientRequestTime":1677448584093}
[6:56:24 PM] [Analyzer] [Info] ==> Content-Length: 204
[6:56:24 PM] [Analyzer] [Info] ==> {"jsonrpc":"2.0","id":2,"method":"textDocument/documentColor","params":{"textDocument":{"uri":"file:///Users/jckodel/Desktop/eva/packages/eva/example/lib/eva/eva.dart"}},"clientRequestTime":1677448584094}
[6:56:24 PM] [Analyzer] [Info] <== Content-Length: 161
Content-Type: application/vscode-jsonrpc; charset=utf-8

{"id":1,"jsonrpc":"2.0","error":{"code":-32007,"data":"/Users/jckodel/Desktop/eva/packages/eva/example/lib/eva/eva.dart","message":"File is not being analyzed"}}Content-Length: 161
Content-Type: application/vscode-jsonrpc; charset=utf-8

{"id":2,"jsonrpc":"2.0","error":{"code":-32007,"data":"/Users/jckodel/Desktop/eva/packages/eva/example/lib/eva/eva.dart","message":"File is not being analyzed"}}
[6:56:24 PM] [Analyzer] [Info] ==> Content-Length: 275
[6:56:24 PM] [Analyzer] [Info] ==> {"jsonrpc":"2.0","id":3,"method":"textDocument/inlayHint","params":{"textDocument":{"uri":"file:///Users/jckodel/Desktop/eva/packages/eva/example/lib/eva/eva.dart"},"range":{"start":{"line":0,"character":0},"end":{"line":79,"character":0}}},"clientRequestTime":1677448584139}
[6:56:24 PM] [Analyzer] [Info] <== Content-Length: 161
Content-Type: application/vscode-jsonrpc; charset=utf-8
[6:56:24 PM] [Analyzer] [Info] <== {"id":3,"jsonrpc":"2.0","error":{"code":-32007,"data":"/Users/jckodel/Desktop/eva/packages/eva/example/lib/eva/eva.dart","message":"File is not being analyzed"}}
[6:56:24 PM] [Analyzer] [Info] ==> Content-Length: 324
[6:56:24 PM] [Analyzer] [Info] ==> {"jsonrpc":"2.0","id":4,"method":"textDocument/codeAction","params":{"textDocument":{"uri":"file:///Users/jckodel/Desktop/eva/packages/eva/example/lib/eva/eva.dart"},"range":{"start":{"line":11,"character":46},"end":{"line":11,"character":46}},"context":{"diagnostics":[],"triggerKind":2}},"clientRequestTime":1677448584187}
[6:56:24 PM] [Analyzer] [Info] ==> Content-Length: 98
[6:56:24 PM] [Analyzer] [Info] ==> {"jsonrpc":"2.0","method":"$/setTrace","params":{"value":"off"},"clientRequestTime":1677448584328}
[6:56:24 PM] [Analyzer] [Info] ==> Content-Length: 122
[6:56:24 PM] [Analyzer] [Info] ==> {"jsonrpc":"2.0","method":"workspace/didChangeConfiguration","params":{"settings":null},"clientRequestTime":1677448584328}
[6:56:24 PM] [Analyzer] [Info] ==> Content-Length: 203
[6:56:24 PM] [Analyzer] [Info] ==> {"jsonrpc":"2.0","id":5,"method":"textDocument/foldingRange","params":{"textDocument":{"uri":"file:///Users/jckodel/Desktop/eva/packages/eva/example/lib/eva/eva.dart"}},"clientRequestTime":1677448584328}
[6:56:24 PM] [Analyzer] [Info] ==> Content-Length: 98
[6:56:24 PM] [Analyzer] [Info] ==> {"jsonrpc":"2.0","method":"$/setTrace","params":{"value":"off"},"clientRequestTime":1677448584336}
[6:56:24 PM] [Analyzer] [Info] ==> Content-Length: 122
[6:56:24 PM] [Analyzer] [Info] ==> {"jsonrpc":"2.0","method":"workspace/didChangeConfiguration","params":{"settings":null},"clientRequestTime":1677448584336}
[6:56:24 PM] [Analyzer] [Info] ==> Content-Length: 96
[6:56:24 PM] [Analyzer] [Info] ==> {"jsonrpc":"2.0","method":"$/cancelRequest","params":{"id":4},"clientRequestTime":1677448584507}
[6:56:24 PM] [Analyzer] [Info] ==> Content-Length: 324
[6:56:24 PM] [Analyzer] [Info] ==> {"jsonrpc":"2.0","id":6,"method":"textDocument/codeAction","params":{"textDocument":{"uri":"file:///Users/jckodel/Desktop/eva/packages/eva/example/lib/eva/eva.dart"},"range":{"start":{"line":11,"character":46},"end":{"line":11,"character":46}},"context":{"diagnostics":[],"triggerKind":2}},"clientRequestTime":1677448584508}
[6:56:24 PM] [Analyzer] [Info] <== Content-Length: 195
Content-Type: application/vscode-jsonrpc; charset=utf-8
[6:56:24 PM] [FlutterDaemon] [Info] <== [{"id":"2"}]
[6:56:24 PM] [FlutterDaemon] [Info] <== [{"id":"1","result":[{"id":"apple_ios_simulator","name":"iOS Simulator","category":"mobile","platformType":"ios"},{"id":"Nexus5","name":"Nexus5","category":"mobile","platformType":"android"}]}]
[6:56:24 PM] [Analyzer] [Error] Unhandled exception:
UnimplementedError: TODO(paulberry)
#0      Parser.parsePrimaryPattern (package:_fe_analyzer_shared/src/parser/parser_impl.dart:9575:11)
#1      Parser.parsePattern (package:_fe_analyzer_shared/src/parser/parser_impl.dart:9380:13)
#2      Parser.parseSwitchBlock (package:_fe_analyzer_shared/src/parser/parser_impl.dart:8507:21)
#3      Parser.parseSwitchStatement (package:_fe_analyzer_shared/src/parser/parser_impl.dart:8456:13)
#4      Parser.parseStatementX (package:_fe_anal…
[6:56:25 PM] [Analyzer] [Info] Spawning /Users/jckodel/fvm/versions/3.8.0-10.1.pre/bin/cache/dart-sdk/bin/dart with args ["language-server","--protocol=lsp","--client-id=VS-Code","--client-version=3.58.0"]
[6:56:25 PM] [Analyzer] [Info]     PID: 22487
```
</details>

**Please complete the following information:**
 - Operating System and version: MacOS 12.6.2 (Intel)
 - VS Code version: 1.75.1
 - Dart extension version: 3.58.0
 - Dart/Flutter SDK version: Flutter 3.8.0-10.1.pre, Dart 3.0.0-218.1.beta
 - Target device (if the issue relates to Flutter debugging): (n/a)

analysis_options.yaml:

```yaml
include: package:flutter_lints/flutter.yaml

analyzer:
  language:
    strict-casts: true
    strict-raw-types: true
    strict-inference: true
  enable-experiment:
    - records
    - patterns
```

(not using these experiments yet).

> Bad bad paulberry. No cookies for you.

**Comment by DanTup** [comment] 2023-02-26 22:25
I guess this is coming from here:

https://github.com/dart-lang/sdk/blob/574e12d0f5416f0aa2f131fab26656e9a1caaad3/pkg/_fe_analyzer_shared/lib/src/parser/parser_impl.dart#L9788

I think it's probably just because this is a pre-release SDK and the patterns work is not yet complete. It's unfortunate this brings down the server though - I don't know if this is expected or the server should handle this in a better way. @bwilkerson @stereotype441 - thoughts?

**Comment by DanTup** [comment] 2023-02-27 18:22
@JCKodel out of interest, can you reproduce this in a shareable sample? I tried enabling those experiments and pasting your code in, but couldn't reproduce the a crash.

**Comment by JCKodel** [comment] 2023-02-27 20:15
> @JCKodel out of interest, can you reproduce this in a shareable sample? I tried enabling those experiments and pasting your code in, but couldn't reproduce the a crash.

Unfortunately no, that code no longer exists and I didn't commit that =(

I can send the current code to your e-mail or any other non-public environment and, maybe, if you paste this code on the top of that file, the error appears (there were 2 or 3 classes in the same .dart file, this was at the top of that file)

**Comment by stereotype441** [comment] 2023-02-27 20:19
@johnniwinther took over the parser work from me.  Johnni, do you know what the status is of this TODO?

**Comment by johnniwinther** [comment] 2023-02-28 08:11
That one fell through the cracks. I'll look into it.

**Comment by stereotype441** [comment] 2023-03-24 16:14
As of https://github.com/dart-lang/sdk/commit/8f6325d65035c98a819abb325a71bd643753c319 this issue is fixed.

@DanTup can you close this issue?  I don't have the proper permissions to do so myself.

**Comment by DanTup** [comment] 2023-03-24 17:16
@stereotype441 done, thanks!

**Closed by DanTup** 2023-03-24 17:16 UTC
Labels: is bug

**Comment by johnniwinther** [comment] 2023-04-11 07:51
This seems to be working on the bleeding edge.

**Comment by JCKodel** [comment] 2023-04-12 16:09
How can I test this?

Already tried to install Dart & Flutter pre-release plugins, but the same error is thrown.

**Comment by DanTup** [comment] 2023-04-12 16:47
The fix is in the SDK rather than the Dart-Code extension, so you'll need an updated Dart/Flutter SDK to test. The fix should certainly be in Flutter's `master` channel by now, though I'm not sure whether it'll be in the `beta` channel yet.

**Comment by JCKodel** [comment] 2023-04-12 18:57
On master, there is another issue:

```
[3:56:23 PM] [Analyzer] [Info] <== {"id":11,"jsonrpc":"2.0","error":{"code":-32013,"data":"...\\main.dart","message":"Analysis failed for file"}}
[3:56:23 PM] [Analyzer] [Error] Unhandled exception:
Bad state: No definition of type Null
#0      TypeProviderImpl._getClassElement (package:analyzer/src/dart/element/type_provider.dart:541:7)
#1      TypeProviderImpl._getType (package:analyzer/src/dart/element/type_provider.dart:549:19)
#2      TypeProviderImpl.nullType (package:analyzer/src/dart/element/type_provider.dart:370:26)
#3      TypeSystemImpl.nullNone (package:analyzer/src/dart/element/type_system.dart:106:35)
#4      new SubtypeHelper (package:analyzer/src/…
[3:56:23 PM] [Analyzer] [Info] Spawning C:\Users\root\fvm\versions\3.7.10\bin\cache\dart-sdk\bin\dart.exe with args ["language-server","--protocol=lsp","--client-id=VS-Code","--client-version=3.63.20230405"]
[3:56:24 PM] [Analyzer] [Info]     PID: 63892
[3:56:24 PM] [Analyzer] [Info] ==> Content-Length: 6431
[3:56:24 PM] [Analyzer] [Info] ==> {"jsonrpc":"2.0","id":0,"method":"initialize","params":
```

**Comment by DanTup** [comment] 2023-04-12 19:08
@JCKodel in your log it says `Spawning C:\Users\root\fvm\versions\3.7.10\bin\cache\...`, are you sure it's spawning the analysis server from `master`?

If so, could you file an issue at https://github.com/dart-lang/sdk with code that's triggering this? Thanks!

**Comment by JCKodel** [comment] 2023-04-12 19:27
Never mind, a full restart did the trick.

> though I'm not sure whether it'll be in the beta channel yet.

Is working only on master.
