### ISSUE TITLE
Function Snippet

### ISSUE THREAD

**Issue by danimtnzz** [Dart-Code/Dart-Code#4854] opened 2023-11-23 11:31 UTC
When i press Ctrl+space in VSC i don't receive the correct suggestion in terms of functions.

For example:
![image](https://github.com/Dart-Code/Dart-Code/assets/113720463/d8d4e06a-46e8-4809-a304-02fa83ac6574)
This is what i would like to have:
![image](https://github.com/Dart-Code/Dart-Code/assets/113720463/f1afd55a-09fd-4811-ab48-07eca81a348c)

I'm using the next relevant extensions: 
-Dart
v3.76.1
-Flutter
v3.76.0
-Awesome Flutter Snippets
v4.0.1
-Flutter Widget Snippets
v3.0.0

It would be very helpful to have this autocomplete to develop efficiently, Thanks!

**Comment by DanTup** [comment] 2023-11-23 11:49
Thanks for the report! This is a dupe of the pinned issue https://github.com/Dart-Code/Dart-Code/issues/4837 (and a cherry-pick request at https://github.com/dart-lang/sdk/issues/54112).

**Closed by DanTup** 2023-11-23 11:49 UTC
Labels: is bug

**Comment by U-MINDERS-TECH** [comment] 2023-11-24 12:12
have any solution plz share with me

**Comment by DanTup** [comment] 2023-11-24 14:30
@U-MINDERS-TECH I responded to you at https://github.com/Dart-Code/Dart-Code/issues/4850#issuecomment-1824177609

This is a bug in the Dart/Flutter SDKs. I have committed a fix but it has not been included in a release. I have opened an issue at https://github.com/dart-lang/sdk/issues/54112 for it to be evaluated for a hotfix release.

Unfortunately there is no workaround (except for downgrading SDK) and you'll need to type the function signature yourself until the fix is released in a new Dart/Flutter SDK.

**Comment by U-MINDERS-TECH** [comment] 2023-11-25 05:44
but android studio is working good

**Comment by quyenvsp** [comment] 2023-11-25 06:22
@U-MINDERS-TECH Android Studio not using LSP so it working good. But AS have problem with find References Usage. If you want quick solution then simple build Dart analysis_server yourself follow https://github.com/Dart-Code/Dart-Code/issues/4846#issuecomment-1824859053, else just wait new Flutter version release.
