### ISSUE TITLE
Debugger doesn't hit breakpoints when using flutter generators

### ISSUE THREAD

**Issue by jascodes** [Dart-Code/Dart-Code#1976] opened 2019-09-06 04:57 UTC
Is it me or anybody else getting issues with debbuger not attaching with latest version of dartcode. I have installed v1.2.1 and that works for me. Just curious anybody else facing this regression.

PS: I am on master channel

```
flutter doctor -v                                                       6.26   ✔   10:26    06.09.19 
[✓] Flutter (Channel master, v1.9.8-pre.83, on Linux, locale en_US.UTF-8)
    • Flutter version 1.9.8-pre.83 at /home/jas/fvm/master
    • Framework revision 3932ffb1cd (26 hours ago), 2019-09-04 23:13:16 -0400
    • Engine revision e7f9ef6aa0
    • Dart version 2.5.0 (build 2.5.0-dev.4.0 36985859e4)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /home/jas/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /home/jas/Android/Sdk
    • Java binary at: /snap/android-studio/78/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Linux toolchain - develop for Linux desktop
    • clang++ 8.0.0
    • GNU Make 4.2.1

[✓] Android Studio (version 3.5)
    • Android Studio at /snap/android-studio/78/android-studio
    • Flutter plugin version 38.2.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] Android Studio (version 3.4)
    • Android Studio at /snap/android-studio/77/android-studio
    • Flutter plugin version 38.2.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b16-5323222)

[✓] VS Code (version 1.36.0)
    • VS Code at /usr/share/code
    • Flutter extension version 3.4.1

[✓] Connected device (1 available)
    • Linux • Linux • linux-x64 • Linux

• No issues found!
```

**Comment by DanTup** [comment] 2019-09-09 08:31
> issues with debbuger not attaching

Could you provide some more info - do you mean using the `attach` functionality, or just launching an app and having the debugger break/step?

Can you reproduce the issue in a small example project you can share? Capturing the Observatory logs with [**Capture Logs**](https://dartcode.org/docs/logging/#capture-logs-command) when this happens may be useful too. Thanks!

**Comment by jascodes** [comment] 2019-09-09 11:26
I am sorry I meant debugger not breaking; didn't meant not attaching. It is attaching just don't break with latest version for me.

I am little swamped with work this week; I will try to get you sample and logs later this week.

Thx

**Comment by escamoteur** [comment] 2019-09-13 10:15
Are you setting the break point in your own or in sdk code?

**Comment by jascodes** [comment] 2019-09-13 11:43
@escamoteur own code

**Comment by szotp** [comment] 2019-10-09 08:51
I had this problem in project which used r_flutter builder. Perhaps `flutter generate` is causing this somehow. I'm sure this worked fine before so I will have to investigate.

**Comment by DanTup** [comment] 2019-10-09 11:42
Can anyone provide a repo and/or [a log](https://dartcode.org/docs/logging/#observatory)?

**Comment by szotp** [comment] 2019-10-09 16:26
[observatory_ok.log](https://github.com/Dart-Code/Dart-Code/files/3708401/observatory_ok.log)
[observatory_bad.log](https://github.com/Dart-Code/Dart-Code/files/3708402/observatory_bad.log)
[archive.zip](https://github.com/Dart-Code/Dart-Code/files/3708403/archive.zip)

I looked at logs and found difference in Event/BreakpointAdded, I have no idea what it means:
[Event_BreakpointAdded_bad.txt](https://github.com/Dart-Code/Dart-Code/files/3708425/Event_BreakpointAdded_bad.txt)
[Event_BreakpointAdded_ok.txt](https://github.com/Dart-Code/Dart-Code/files/3708426/Event_BreakpointAdded_ok.txt)

My `flutter doctor -v`:
```
[√] Flutter (Channel stable, v1.9.1+hotfix.4, on Microsoft Windows [Version 10.0.17763.775], locale pl-PL)
    • Flutter version 1.9.1+hotfix.4 at C:\Users\krzat\Documents\flutter
    • Framework revision cc949a8e8b (12 days ago), 2019-09-27 15:04:59 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\krzat\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 34.0.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

• No issues found!
```

**Comment by szotp** [comment] 2019-10-10 13:48
Ok case had json_widget builder removed.

Breakpoints stop working if app involves custom code generators.

**Comment by DanTup** [comment] 2019-10-10 13:57
@jonahwilliams do you have any ideas why using code generation could affect the VM resolving/pausing on breakpoints?

**Comment by jonahwilliams** [comment] 2019-10-10 14:33
If builders are being used we compile with a multiroot filesystem

**Comment by DanTup** [comment] 2019-10-10 15:51
I'm not entirely sure what that means 😄 Could it affect things like the paths of the scripts? (VS Code always uses file URIs for breakpoints, not package URIs)

**Comment by jonahwilliams** [comment] 2019-10-10 15:52
Yes, the might screw it up. We don't need to use the multiroot filesystem. It adds a lot of complexity to support a subset of builders that populate the .dart_tool cache instead of the regular source tree.

**Comment by DanTup** [comment] 2019-10-10 16:09
Ok, should I open a Flutter issue about changing it? Do we definitely not need to support those types of builders?

If there's a way we can test it out to verify that's the cause before doing the work, let me know!

**Comment by DanTup** [comment] 2019-10-10 16:27
> this makes sense but why it worked in older version of DartCode and still works in Android Studio plugin?

Dart-Code has previously sent package URIs in some cases in the past. In the current version as long as the SDK version is new enough (one known to fix some additional bugs) it will always send file URIs. It's possible that when this worked you were on a version of Dart-Code that didn't do this, or a version of the SDK that didn't have the fixes.

I think Android Studio/IntelliJ generally send package URIs. I think people tend not to use the debugger as much in AS/IntelliJ, so it's possible the issues using package URIs have come up less than they do with Dart-Code (https://github.com/Dart-Code/Dart-Code/issues/1443 was the most recent issue that came up that only occurred when using package URIs and was fine with file URIs).

> EDIT: The same problem, I guess multiroot is still used even if all builders output to the source.

Yeah, based on Jonah's comment it sounds like that's always the case. If it's simple for us to temporarily disable we could verify that's the issue, but I don't know much about this.

**Comment by szotp** [comment] 2019-12-05 07:46
Should this still have "awaiting info" label?

It seems to me that "flutter generate" feature has been kinda ignored by the Flutter team, maybe it would be better to remove it completely or put under some experimental flag to not confuse the users.

**Comment by DanTup** [comment] 2019-12-05 08:42
> Should this still have "awaiting info" label?

Sorry, it should not :)

I don't think anything is being deliberately ignored, but there's a lot features/issues and limited people/hours. Things with the highest impact tend to be dealt with first - sorry this one hasn't progressed.

I'm not familiar with `flutter generate` so this may need some time (or at least assistance) from @jonahwilliams. It may be worth moving to the Flutter repo so it has better visibility?

**Comment by szotp** [comment] 2019-12-07 10:06
I'm not sure about visibility on Flutter main repo, I have another issue there (https://github.com/flutter/flutter/issues/41808) but it was ignored completely.

I understand your point about Flutter team being busy, that's why it may be better idea to trim the code generation off completely until there is time to really focus on it.

**Comment by DanTup** [comment] 2019-12-09 16:42
I understand the frustration. I've added the `tool` label to that issue since it seemed like it should've had that (though that doesn't provide any guarantees about it being worked on). 

Removing the feature wouldn't be a good idea though since it would be a breaking change and there may be people using it (that would rather put up with these issues than not have it at all).

Out of interest - if your code throws an exception (instead of using a breakpoint), are you taken to the correct source location for the exception? If not, could you capture a log (that covers when the exception is thrown)?

**Comment by szotp** [comment] 2019-12-09 19:46
Thanks for comprehensive answer, I will just use different code generation method until improvements are made.

Regarding your question, exception jumps to correct location.

**Comment by DanTup** [comment] 2019-12-10 14:51
> Regarding your question, exception jumps to correct location.

Ok thanks - I thought if this failed, that maybe the mapping between package URI/paths could be wrong, but I guess not.

**Comment by DanTup** [comment] 2020-02-05 17:00
Since there's an issue open in Flutter for this now (and I believe the fix needs to be made in there), I'll close this one as a dupe (of https://github.com/flutter/flutter/issues/50198).

**Closed by DanTup** 2020-02-05 17:00 UTC
Labels: in debugger, is bug, upstream in dart / flutter
