### ISSUE TITLE
Code completion doesn't trigger automatically for imports/slashes/interpolation in LSP

### ISSUE THREAD

**Issue by tomasbaran** [Dart-Code/Dart-Code#3211] opened 2021-03-15 21:24 UTC
**Describe the bug**
It doesn't autocomplete package in VS Code. It's a pain in the butt now.

**To Reproduce**
1. write `import 'mate`

**Expected behavior**
`import 'package:flutter/material.dart';`

**Screenshots**

<img width="616" alt="Captura de pantalla 2021-03-15 a las 21 17 55" src="https://user-images.githubusercontent.com/25743901/111222808-401aef00-85d4-11eb-8e1c-a31b70ef144c.png">

**Versions (please complete the following information):**
 - VS Code version:  1.54.2
 - Dart extension version: Awesome Flutter Snippets: v2.0.4
 - Flutter (Channel beta, 2.0.1, on macOS 11.1 20C69 darwin-x64, locale es-ES)
 - Dart SDK version: 2.10.5 (stable) (Tue Jan 19 13:05:37 2021 +0100) on "macos_x64"

**Comment by DanTup** [comment] 2021-03-16 10:44
Thanks for the issue! This is a known limitation when using LSP that hasn't been resolved yet.

In case you're not away - you can _manually_ invoke completion with Cmd/Ctrl+Space which will open the list. The only thing missing is that it doesn't open automatically when pressing the `'`.

I'll keep this issue open to track supporting this in LSP.

**Comment by tomasbaran** [comment] 2021-03-16 10:46
Thanks @DanTup but how come this issue was NOT present before?

**Comment by tomasbaran** [comment] 2021-03-16 10:48
@DanTup Please, how can I manually invoke completion again? pressing cmd+space on Mac opens the macOS search Spotlight.

**Comment by DanTup** [comment] 2021-03-16 10:53
> Thanks @DanTup but how come this issue was NOT present before?

In the original code there are some hacks to make this work:

https://github.com/Dart-Code/Dart-Code/blob/master/src/extension/providers/dart_completion_item_provider.ts#L68-L81

We're in the process of moving to LSP for the language server, which isn't so easy to do something like that. It's possible to fix (and will be fixed), but it wasn't considered critical for the migration so hasn't been done yet.

> pressing cmd+space on Mac opens the macOS search Spotlight.

Sorry, I gave the wrong combo - it's Ctrl+Space even on Mac!

**Comment by tomasbaran** [comment] 2021-03-16 11:14
> Sorry, I gave the wrong combo - it's Ctrl+Space even on Mac!
My mac (I guess all do but maybe I'm wrong) have ctrl+space is set for changing keyboard language. Even when I undo this system shortcut, autocompletion still does NOT work. Any tips, please?
<img width="239" alt="Captura de pantalla 2021-03-16 a las 11 13 35" src="https://user-images.githubusercontent.com/25743901/111300149-a9d4e080-8648-11eb-9044-fa2d3fbb64ad.png">
<img width="803" alt="Captura de pantalla 2021-03-16 a las 11 13 47" src="https://user-images.githubusercontent.com/25743901/111300173-afcac180-8648-11eb-8bbf-c27c064baae6.png">

**Comment by DanTup** [comment] 2021-03-16 11:22
I don't know why it wouldn't work - it's VS Code functionality rather than Dart, but you can see/re-bind the shortcut in the VS Code Keyboard Shortcuts editor. (it's the top item here called "Trigger Suggest"):

<img width="1412" alt="Screenshot 2021-03-16 at 11 21 39" src="https://user-images.githubusercontent.com/1078012/111301246-e35a1b80-8649-11eb-9ea4-872d27519933.png">

Hope this helps!

**Comment by tomasbaran** [comment] 2021-03-16 11:29
Thanks. Maybe all I had to was restart the IDE after unselecting the system shortcut for changing keyboard language.

Cheers,

**Closed** 2021-04-20 17:24 UTC
Labels: in editor, in lsp/analysis server, is enhancement

**Comment by tomasbaran** [comment] 2021-06-07 11:36
@DanTup Is the issue fixed? If so, what do I have to do to make it work on my end? As far as I know I'm still not experiencing auto completion of `import`

**Comment by DanTup** [comment] 2021-06-09 12:53
@tomasbaran it depends on the exact context you're having issues with.

If the problem is that when you type a quote after `import ` or a `/` inside the path (note: type manually, and not have them included by a completion) then the fix is in the SDK, so you'll need an updated SDK for the fix (it's not in the current stable channel, but should be in the dev channels of Dart/Flutter).

If the problem is when you select the `import '';` snippet from the completion list, or you select a folder in the completion list, then that's fixed for the next version of Dart-Code (#3385).
