### ISSUE TITLE
a lot of orphan sleeping dart processes left after have closed vscode

### ISSUE THREAD

**Issue by cvgaviao** [Dart-Code/Dart-Code#2223] opened 2020-01-15 22:10 UTC
I'm using vscode with ubuntu 18.04 in order to develop with flutter.
Seems that every time I run debug/run, one or more dart processes a created and somehow some of them are being left behind after I close vscode.
I'm attaching a image that shows my machine's processes and some dart processes left behind from last time I closed vscode: 

![Screenshot from 2020-01-15 18-53-31](https://user-images.githubusercontent.com/251734/72475667-290f2000-37ca-11ea-8439-0d4671040ee8.png)

And below is the `status` of a running vscode:
```
[4599:0115/190350.366565:ERROR:sandbox_linux.cc(369)] InitializeSandbox() called with multiple threads in process gpu-process.
Version:          Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T15:04:31.999Z)
OS Version:       Linux x64 5.0.0-37-generic
CPUs:             Intel(R) Core(TM) i7-4500U CPU @ 1.80GHz (4 x 2869)
Memory (System):  15.55GB (3.68GB free)
Load (avg):       0, 0, 0
VM:               0%
Screen Reader:    no
Process Argv:     . --no-sandbox
GPU Status:       2d_canvas:                     enabled
                  flash_3d:                      enabled
                  flash_stage3d:                 enabled
                  flash_stage3d_baseline:        enabled
                  gpu_compositing:               enabled
                  metal:                         disabled_off
                  multiple_raster_threads:       enabled_on
                  oop_rasterization:             disabled_off
                  protected_video_decode:        unavailable_off
                  rasterization:                 disabled_software
                  skia_renderer:                 disabled_off
                  surface_control:               disabled_off
                  surface_synchronization:       enabled_on
                  video_decode:                  unavailable_off
                  viz_display_compositor:        enabled_on
                  viz_hit_test_surface_layer:    disabled_off
                  webgl:                         enabled
                  webgl2:                        enabled

CPU %	Mem MB	   PID	Process
    0	   127	  4183	code main
    0	    32	  4185	   zygote
    2	    80	  4207	   gpu-process
    1	   223	  4224	   window (budgethub_mobile - Visual Studio Code)
    8	   175	  4333	     extensionHost
    0	    48	  4448	       electron_node server.js 
    0	     0	  4496	       /bin/sh -c "/home/cvgaviao/opt/flutter_linux_v1.2.1-stable/flutter/bin/cache/dart-sdk/bin/dart" "/home/cvgaviao/opt/flutter_linux_v1.2.1-stable/flutter/bin/cache/dart-sdk/bin/snapshots/analysis_server.dart.snapshot" "--client-id=Dart-Code.dart-code" "--client-version=3.7.1"
    0	     0	  4499	       /bin/sh -c "/home/cvgaviao/opt/flutter_linux_v1.2.1-stable/flutter/bin/flutter" "daemon"
    0	     0	  4500	         bash /home/cvgaviao/opt/flutter_linux_v1.2.1-stable/flutter/bin/flutter daemon
    0	   127	  4519	           /home/cvgaviao/opt/flutter_linux_v1.2.1-stable/flutter/bin/cache/dart-sdk/bin/dart --packages=/home/cvgaviao/opt/flutter_linux_v1.2.1-stable/flutter/packages/flutter_tools/.packages /home/cvgaviao/opt/flutter_linux_v1.2.1-stable/flutter/bin/cache/flutter_tools.snapshot daemon
    0	    96	  4341	     watcherService
    0	    48	  4415	     searchService
    0	   127	  4413	   shared-process
    0	     0	  4616	     /bin/sh -c /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	     0	  4617	       /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=

Workspace Stats: 
|  Window (budgethub_mobile - Visual Studio Code)
|    Folder (budgethub_mobile): 2606 files
|      File types: class(683) dex(193) json(124) flat(124) xml(116) java(107)
|                  jar(52) ttf(40) png(26) txt(17)
|      Conf files: package.json(1)
```

**Comment by DanTup** [comment] 2020-01-16 14:53
@cvgaviao are you able to reproduce this reliably? How are you stopping the debug session?

If you could reproduce this while capturing a log, that would help!

- run **Dart: Capture Logs** from the command palette
- untick Analyzer but leave everything else ticked
- reproduce the issue
- click **Cancel** on the logging prompt

Ensure there's nothing sensitive in the log, then attach it or paste into a gist/etc. and post a link here and I'll have a look. Thanks!

**Comment by ahmedabdelsalam7716** [comment] 2020-01-21 05:47
I am facing issue similar which makes my terminal freezes and i ran out of solutions 

[3795:0121/074531.649426:ERROR:sandbox_linux.cc(369)] InitializeSandbox() called with multiple threads in process gpu-process.
Version:          Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T15:04:31.999Z)
OS Version:       Linux x64 4.17.0-041700rc4-generic
CPUs:             Intel(R) Core(TM) i3-3110M CPU @ 2.40GHz (4 x 1333)
Memory (System):  7.67GB (1.97GB free)
Load (avg):       2, 2, 2
VM:               0%
Screen Reader:    no
Process Argv:     --no-sandbox --unity-launch
GPU Status:       2d_canvas:                     enabled
                  flash_3d:                      enabled
                  flash_stage3d:                 enabled
                  flash_stage3d_baseline:        enabled
                  gpu_compositing:               enabled
                  metal:                         disabled_off
                  multiple_raster_threads:       enabled_on
                  oop_rasterization:             disabled_off
                  protected_video_decode:        unavailable_off
                  rasterization:                 disabled_software
                  skia_renderer:                 disabled_off
                  surface_control:               disabled_off
                  surface_synchronization:       enabled_on
                  video_decode:                  unavailable_off
                  viz_display_compositor:        enabled_on
                  viz_hit_test_surface_layer:    disabled_off
                  webgl:                         enabled
                  webgl2:                        enabled

CPU %   Mem MB     PID  Process
    0      126    3496  code main
    0       31    3499     zygote
    0       86    3520     gpu-process
    0      188    3538     window (automate_2.py - Untitled (Workspace) - Visual Studio Code)
    0      212    3600       extensionHost
    0       55    3634         electron_node server.js 
    0      126    3658         electron_node server.js 
    0      236    3706         /home/ubuntu/.vscode/extensions/ms-python.python-2020.1.58038/languageServer.0.5.30/Microsoft.Python.LanguageServer
    0       55    3618       watcherService
    0       63    3650       searchService
    0        0    3737       /bin/bash
    0        0    3754         bash /usr/bin/code --status
    0       55    3760           electron_node cli.js 
    0       94    3772             /usr/share/code/code --status --no-sandbox
    0       31    3774               zygote
    0       55    3795               gpu-process
    0      102    3574     shared-process
    0        0    3812       /bin/sh -c /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0        0    3813         /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=

Workspace Stats: 
|  Window (automate_2.py - Untitled (Workspace) - Visual Studio Code)
|    Folder (small_proj): 4 files
|      File types: py(2) json(1)
|      Conf files: settings.json(1)

**Comment by DanTup** [comment] 2020-01-21 12:01
@ahmedabdelsalam7716 if you can reproduce this, could you capture a log using the instructions from the comment above yours? Thanks!

**Comment by DanTup** [comment] 2020-04-21 10:29
If anyone is still seeing this and able to provide some logs using the instructions above, please let me know and I'll re-open this and investigate.

**Comment by svipas** [comment] 2020-07-08 14:34
I can reproduce this...

![Screen Shot 2020-07-08 at 17 33 23](https://user-images.githubusercontent.com/10441177/86931762-266e0180-c141-11ea-94b8-228102fa5632.png)

**Comment by DanTup** [comment] 2020-07-08 14:40
@svipas can you reproduce this reliably? Do you know what the steps are?

Could you confirm the version of Flutter/Dart you're using, and also check the output of `ps -x | grep dart` to see the full command lines for each process? Thanks!

**Comment by svipas** [comment] 2020-07-09 08:44
@DanTup Yes, I can.

Steps are very simple, just use `>Debug` from command palette by selecting and starting debugging or by attaching to flutter on device. No matter if your build fails or you successfully connected and disconnected manually.

### Versions

OS: macOS 10.15.5
VS Code: 1.46.1
Dart/Flutter extension: 3.12.2

Dart version: 

```
Dart VM version: 2.8.4 (stable) (Wed Jun 3 12:26:04 2020 +0200) on "macos_x64"
```

Flutter version:

```
Flutter 1.17.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 8af6b2f038 (9 days ago) • 2020-06-30 12:53:55 -0700
Engine • revision ee76268252
Tools • Dart 2.8.4
```

### Output from `ps -x | grep dart`

After using `>Debug: Select and Start Debugging` it failed to build because of my own issues and I see now 4 processes of Dart.

```
 4167 ??         0:05.46 /Users/svipas/flutter/bin/cache/dart-sdk/bin/dart /Users/svipas/flutter/bin/cache/dart-sdk/bin/snapshots/analysis_server.dart.snapshot --client-id=VS-Code --client-version=3.12.2
 4186 ??         0:01.35 /Users/svipas/flutter/bin/cache/dart-sdk/bin/dart --packages=/Users/svipas/flutter/packages/flutter_tools/.packages /Users/svipas/flutter/bin/cache/flutter_tools.snapshot daemon
 4644 ??         0:02.68 /Users/svipas/flutter/bin/cache/dart-sdk/bin/dart --packages=/Users/svipas/flutter/packages/flutter_tools/.packages /Users/svipas/flutter/bin/cache/flutter_tools.snapshot run --machine --target lib/main.dart -d BD61742B-79E2-4A2A-AF7E-95DBE215723E --track-widget-creation --dart-define=flutter.inspector.structuredErrors=true --start-paused --verbose
 4688 ??         0:08.55 /Users/svipas/flutter/bin/cache/dart-sdk/bin/dart /Users/svipas/flutter/bin/cache/artifacts/engine/darwin-x64/frontend_server.dart.snapshot --sdk-root /Users/svipas/flutter/bin/cache/artifacts/engine/common/flutter_patched_sdk/ --incremental --target=flutter --debugger-module-names -Ddart.developer.causal_async_stacks=true -Dflutter.inspector.structuredErrors=true --output-dill /var/folders/f3/mzpdhh0147g37618w5t4l4500000gn/T/flutter_tool.1p4nxG/app.dill --packages /Users/svipas/dev/mobile-v2/.packages -Ddart.vm.profile=false -Ddart.vm.product=false --bytecode-options=source-positions,local-var-info,debugger-stops,instance-field-initializers,keep-unreachable-code,avoid-closure-call-instructions --enable-asserts --track-widget-creation
 5064 ttys001    0:00.00 grep --color=auto --exclude-dir=.bzr --exclude-dir=CVS --exclude-dir=.git --exclude-dir=.hg --exclude-dir=.svn --exclude-dir=.idea --exclude-dir=.tox dart
```

### .vscode/launch.json

```
{
  // Use IntelliSense to learn about possible attributes.
  // Hover to view descriptions of existing attributes.
  // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Flutter: Attach to Device",
      "type": "dart",
      "request": "attach"
    },
    {
      "name": "Flutter",
      "request": "launch",
      "type": "dart",
      "args": ["--verbose"]
    },
    {
      // configuration type, request  and name. "launch" is used to deploy the app
      // to your device and start a debugging session.
      "type": "android",
      "request": "attach",
      "name": "Attach (Java, Kotlin)",

      // Location of the App source files. This value must point to the root of
      // your App source tree (containing AndroidManifest.xml).
      "appSrcRoot": "${workspaceRoot}/android/app/src/main",

      // Port number to connect to the local ADB (Android Debug Bridge) instance.
      // Default: 5037
      "adbPort": 5037,

      // Target Device ID (as indicated by 'adb devices').
      // Use this to specify which device is used for deployment
      // when multiple devices are connected.
      "targetDevice": "192.168.1.10:5555",

      // Set to true to output debugging logs for diagnostics.
      "trace": true,
      "processId": "${command:PickAndroidProcess}"
  }
  ]
}
```

Attaching to a Flutter device by using `>Debug: Attach to Flutter on Device` and disconnecting this time kills newly created processes, but old still are alive like mentioned above. Yesterday I was able to reproduce this even with attaching and disconnecting manually, seems now I can't so I don't know if this is reliable, but I can assure you if you're using `>Debug: Select and Start Debugging` and it fails it keeps those processes alive and you need manually to kill them.

**Comment by svipas** [comment] 2020-07-09 08:51
Some more logs which make sense to share I guess.

```
Dart Code extension: 3.12.2
Flutter extension: 3.12.2 (activated)

App: Visual Studio Code
Version: 1.46.1
Platform: mac

Workspace type: Flutter
Multi-root?: false

Dart SDK:
    Loc: /Users/svipas/flutter/bin/cache/dart-sdk
    Ver: 2.8.4
Flutter SDK:
    Loc: /Users/svipas/flutter
    Ver: 1.17.5

HTTP_PROXY: undefined
NO_PROXY: undefined

Thu Jul 09 2020 [11:47:16 GMT+0300 (Eastern European Summer Time)] Log file started
[11:47:25 AM] [General] [Info] Starting debug session...
[11:47:25 AM] [General] [Info]     workspace: /Users/svipas/dev/project
[11:47:25 AM] [General] [Info] Using found common entry point: /Users/svipas/dev/project/lib/main.dart
[11:47:25 AM] [General] [Info] Using workspace as cwd: /Users/svipas/dev/project
[11:47:25 AM] [General] [Info] Detected launch project as Flutter
[11:47:25 AM] [General] [Info] Using Flutter debug adapter for this session
[11:47:25 AM] [FlutterDaemon] [Info] ==> [{"id":"7","method":"daemon.getSupportedPlatforms","params":{"projectRoot":"/Users/svipas/dev/project"}}]
[11:47:25 AM] [FlutterDaemon] [Info] <== [{"id":"7","result":{"platforms":["ios","android"]}}]
[11:47:25 AM] [General] [Info] Checking for errors before launching
[11:47:25 AM] [General] [Info] Debug session starting...
    {
        "name": "Flutter",
        "request": "launch",
        "type": "dart",
        "args": [
            "--verbose"
        ],
        "program": "/Users/svipas/dev/project/lib/main.dart",
        "cwd": "/Users/svipas/dev/project",
        "dartVersion": "2.8.4",
        "toolEnv": {
            "FLUTTER_HOST": "VSCode",
            "PUB_ENVIRONMENT": "vscode.dart-code"
        },
        "sendLogsToClient": true,
        "globalFlutterArgs": [],
        "vmAdditionalArgs": [],
        "vmServicePort": 0,
        "dartPath": "/Users/svipas/flutter/bin/cache/dart-sdk/bin/dart",
        "maxLogLineLength": 2000,
        "pubPath": "/Users/svipas/flutter/bin/cache/dart-sdk/bin/pub",
        "pubSnapshotPath": "/Users/svipas/flutter/bin/cache/dart-sdk/bin/snapshots/pub.dart.snapshot",
        "debugSdkLibraries": false,
        "debugExternalLibraries": false,
        "showDartDeveloperLogs": true,
        "useFlutterStructuredErrors": true,
        "evaluateGettersInDebugViews": true,
        "evaluateToStringInDebugViews": true,
        "flutterVersion": "1.17.5",
        "forceFlutterVerboseMode": true,
        "flutterTrackWidgetCreation": true,
        "flutterMode": "debug",
        "flutterPlatform": "default",
        "flutterPath": "/Users/svipas/flutter/bin/flutter",
        "workspaceConfig": {},
        "deviceId": "BD61742B-79E2-4A2A-AF7E-95DBE215723E",
        "deviceName": "iPhone SE (2nd generation) (ios)",
        "showMemoryUsage": false,
        "debugServer": 50468,
        "debuggerType": 2
    }
[11:47:25 AM] [General] [Warn] Did not find session 06a11245-19c6-4706-8b78-98208257b299 to handle dart.progressStart. There were 0 sessions:
[11:47:25 AM] [General] [Warn] Event will be queued and processed when the session start event fires
[11:47:25 AM] [General] [Info] Processing delayed event dart.progressStart for session 06a11245-19c6-4706-8b78-98208257b299
[11:47:25 AM] [FlutterRun] [Info] [Flutter] Spawning /Users/svipas/flutter/bin/flutter with args ["run","--machine","--target","lib/main.dart","-d","BD61742B-79E2-4A2A-AF7E-95DBE215723E","--track-widget-creation","--dart-define=flutter.inspector.structuredErrors=true","--start-paused","--verbose"]

[11:47:47 AM] [FlutterRun] [Error] [Flutter] [ +227 ms] Could not find the built application bundle at build/ios/iphonesimulator/Runner.app.
[11:47:47 AM] [FlutterRun] [Error] [Flutter] [   +2 ms] Error launching application on iPhone SE (2nd generation).
[11:47:47 AM] [FlutterRun] [Info] [Flutter] <== [{"event":"app.stop","params":{"appId":"123"}}]
[11:47:47 AM] [FlutterRun] [Info] [Flutter] Process terminated! null, SIGTERM
[11:47:47 AM] [VmService] [Info] [Flutter] Process exited (sigterm)
[11:47:48 AM] [VmService] [Info] [Flutter] Disconnect requested!
[11:47:48 AM] [VmService] [Info] [Flutter] TERM: Requested to terminate with SIGINT...
[11:47:48 AM] [VmService] [Info] [Flutter] TERM: Did not need to terminate processes
[11:47:48 AM] [VmService] [Info] [Flutter] TERM: Removing all stored data...
[11:47:48 AM] [VmService] [Info] [Flutter] TERM: Waiting for process to finish...
[11:47:48 AM] [VmService] [Info] [Flutter] TERM: Disconnecting...
[11:47:48 AM] [General] [Info] Debugger:SessionDuration timing: 22622ms (Flutter)
Thu Jul 09 2020 [11:47:50 GMT+0300 (Eastern European Summer Time)] Log file ended
```

**Comment by DanTup** [comment] 2020-07-13 12:52
I believe the issue with Flutter not terminating after a build failure is https://github.com/flutter/flutter/issues/60613. It's been recently fixed in Flutter.

Can you reproduce for situations where there is *not* a build failure?

**Comment by svipas** [comment] 2020-07-13 13:16
I guess it can be closed because I can't repro without build failure this issue. You can close it and I will re-open if issue happens again. Thanks a lot!

**Comment by DanTup** [comment] 2020-07-13 13:17
sgtm, thanks!

**Closed by DanTup** 2020-07-13 13:17 UTC
Labels: awaiting info
