### ISSUE TITLE
Running the contributed command:'dart.changeSdk' failed.

### ISSUE THREAD

**Issue by jacehensley-wf** [Dart-Code/Dart-Code#697] opened 2018-03-15 22:18 UTC
When I click on the SDK version in the bottom left corner I get this error
```
Running the contributed command:'dart.changeSdk' failed.
```

```
"dart.lineLength": 120,
"dart.showTodos": false,
"dart.pubAdditionalArgs": ["--packages-dir"],
"dart.checkForSdkUpdates": false,
"dart.runPubGetOnPubspecChanges": false,
"dart.debugSdkLibraries": false,
"dart.debugExternalLibraries": false,
"dart.showLintNames": true,
"dart.sdkPaths": ["/usr/local/Cellar/dart/"],
```

VS Code Version: 1.21.1
Dart Code Version: 2.10.0

**Comment by DanTup** [comment] 2018-03-15 22:19
If you click Help -> Toggle Dev Tools is there a better error message/stack?

**Comment by jacehensley-wf** [comment] 2018-03-15 22:22
| e.onDidNotificationChange | @ | workbench.main.js:sourcemap:2207
-- | -- | -- | --
  | (anonymous) | @ | workbench.main.js:sourcemap:2206
  | e.fire | @ | workbench.main.js:sourcemap:165
  | e.notify | @ | workbench.main.js:sourcemap:2199
  | e.error | @ | workbench.main.js:sourcemap:3004
  | (anonymous) | @ | workbench.main.js:sourcemap:3557
  | done | @ | workbench.main.js:sourcemap:150
  | v | @ | workbench.main.js:sourcemap:145
  | enter | @ | workbench.main.js:sourcemap:148
  | _run | @ | workbench.main.js:sourcemap:150
  | _error | @ | workbench.main.js:sourcemap:149
  | e.resolveErr | @ | workbench.main.js:sourcemap:2779
  | e._receiveReplyErr | @ | workbench.main.js:sourcemap:2824
  | e._receiveOneMessage | @ | workbench.main.js:sourcemap:2823
  | (anonymous) | @ | workbench.main.js:sourcemap:2822
  | (anonymous) | @ | workbench.main.js:sourcemap:2824
  | e.fire | @ | workbench.main.js:sourcemap:165
  | (anonymous) | @ | workbench.main.js:sourcemap:288
  | emitOne | @ | events.js:96
  | emit | @ | events.js:191
  | readableAddChunk | @ | _stream_readable.js:178
  | Readable.push | @ | _stream_readable.js:136
  | onread | @ | net.js:560

**Comment by jacehensley-wf** [comment] 2018-03-15 22:28
Better: ![image](https://user-images.githubusercontent.com/12398382/37494297-749f41d8-2865-11e8-80b3-582e1fd955b6.png)

**Comment by DanTup** [comment] 2018-03-15 22:36
Hmm, none of that's our code :(

If you're able to clone the repo and run from source maybe you can figure out what the error is. Clone and open the folder in Code, put a breakpoint in `sdk/sdk_manager.ts` in `searchForSdks`, and hit F5 - it'll spawn a new instance of Code with the dev extension installed in it and then click the status bar, hit the breakpoint and then keep stepping till it errors.

The code walks through the SDKs it finds and builds a list sorted by the version. I noticed a crash here recently (fixed in https://github.com/Dart-Code/Dart-Code/commit/c751bba973ba03479c9f4d5177cdc99b6c025030#diff-e1495d267619047a7cca5cfe8f692729) caused by the `version` file containing more than just the version (lots of comments, for ex - in the Flutter repo). Maybe it's something related, failing to get the version (you could check the contents of `/usr/local/Cellar/dart/version` to see if that's likely).

**Comment by jacehensley-wf** [comment] 2018-03-15 22:39
Wonder if it has to do with the recent change of where notifications show up at?

**Comment by DanTup** [comment] 2018-03-15 23:02
Don't think so, that's a Code change but this will be my error. The call stacks have ashtrays been pretty bad for things invoked by Code (esp when async). Let me know if you get anywhere and if not I'll do more digging. If it's caused by your version for being bad, it might work for with the repo code as a result of the change I made.

**Comment by jacehensley-wf** [comment] 2018-03-15 23:33
Hmm `/usr/local/Cellar/dart/version` doesn't exist for me.

```bash
$ ls /usr/local/Cellar/dart/
1.22.1 1.23.0 1.24.0 1.24.1 1.24.2
```

**Comment by DanTup** [comment] 2018-03-16 07:44
Sorry, I meant the version folders inside each of them. Based on the numbers though, I presume they're fairly standard. Might have to put a breakpoint in and step through; I'm not sure I have any ideas :(

**Comment by jacehensley-wf** [comment] 2018-03-19 16:05
Sorry, didn't get a chance to run from source code. But I also don't see a `version` file.

```
$ ls /usr/local/Cellar/dart/1.22.1/
Chromium.app         Content Shell.app    INSTALL_RECEIPT.json LICENSE              README               bin                  libexec              osmesa.so            pnacl                snapshot-size.txt
```

**Comment by DanTup** [comment] 2018-03-19 16:25
@jacehensley-wf Is that a full SDK? I just grabbed 1.22.1 from [the website](https://www.dartlang.org/install/archive) and it did seem to include the version (though it's the Windows version).

![sdk](https://user-images.githubusercontent.com/1078012/37608313-1f94b24c-2b92-11e8-841e-fef427129c7b.png)

**Comment by DanTup** [comment] 2018-03-19 16:26
Is it possible you got the Dartium download, but not the SDK?

**Comment by jacehensley-wf** [comment] 2018-03-19 16:31
Hmm that's odd, this is what I did when I download using `brew`.

**Comment by jacehensley-wf** [comment] 2018-03-19 16:33
Oh I found it! 
![image](https://user-images.githubusercontent.com/12398382/37608740-8ffb31f8-2b58-11e8-97a9-fd6f41aff1f4.png)

**Comment by DanTup** [comment] 2018-03-19 17:22
Hmmm, that looks kinda weird. I don't really want to start looking in different places for the version (though I should make sure it doesn't crash if there's a bad/missing version).

If you install a recent SDK using `brew` is it still in this weird format?Your `dart` executable looks like a link too? :/

**Comment by jacehensley-wf** [comment] 2018-03-19 17:27
Yup, it's the same when I download Dart 2.0.0-dev.39.0

**Comment by DanTup** [comment] 2018-03-19 17:31
Weird :/ Based on [this code](https://github.com/dart-lang/homebrew-dart/blob/master/dart.rb) I think we can assume it'll be consistent and look in `libexec`. I'm surprised nobody has complained about anything not working here before. Does this mean you also don't see the SDK version number in the status bar?

**Comment by jacehensley-wf** [comment] 2018-03-19 17:35
The weird thing is that this totally worked before haha, I don't remember when it stopped working tho :(. But I do see the current SDK version in the status bar, it'll be whichever SDK version I have turned on via brew.

**Comment by DanTup** [comment] 2018-03-19 17:38
Ah, ok - that's probably handled by us following the symlink to get the real folder for Dart, and then going up a level to get the SDK folder. So that symlink you have in `bin` (which probably goes to `../libexec/bin/dart`?) will be why that works.

Actually, I think the same thing should work here - I saw symlink resolution code in there earlier... I'll investigate and fix before v2.11 ships.

**Comment by jacehensley-wf** [comment] 2018-03-19 17:39
Awesome, thanks!

**Closed** 2018-03-20 08:35 UTC
Labels: in editor, is bug

**Comment by DanTup** [comment] 2018-03-20 08:46
I repro'd by creating a symlink in a "fake sdk" folder and with this fix, it seems to come up fine.

<img width="992" alt="screen shot 2018-03-20 at 08 44 42" src="https://user-images.githubusercontent.com/1078012/37644280-325a6ad2-2c1b-11e8-93e6-22f54c655fd1.png">
<img width="652" alt="screen shot 2018-03-20 at 08 45 33" src="https://user-images.githubusercontent.com/1078012/37644282-3274c17a-2c1b-11e8-95b1-3bce58715e7f.png">

**Comment by DanTup** [comment] 2018-03-20 13:55
Please test with [v2.11.0 Beta 2](https://github.com/Dart-Code/Dart-Code/releases/tag/v2.11.0-beta.2) and let me know if you have any issues.
