### ISSUE TITLE
Debug not starting. No error message available

### ISSUE THREAD

**Issue by dominikheeb** [Dart-Code/Dart-Code#2782] opened 2020-09-10 07:12 UTC
Recently the Flutter and Dart Version stopped working on my vs code
I tried to reinstall vscode but it kept having the issue, also i tried to reinstall flutter but all didn't help yet.

The issue is: When i press start debug in vscode, it doesn't start doing anything.
Our launch configuration is:
```
{
         "name": "LOCAL",
         "type": "dart",
         "request": "launch",
         "program": "lib/main_local.dart",
         "args": [
              "--flavor",
              "local",
         ]
 },
```
The console which before contained log messages that the build is starting is now empty and when i open the extension log i just have this lines:

```
[9:01:15 AM] [General] [Info] Starting debug session...
[9:01:15 AM] [General] [Info]     workspace: **PROJECTFOLDER**
[9:01:15 AM] [General] [Info]     program  : lib/main_local.dart
[9:01:15 AM] [General] [Info] Converted program to absolute path: **PROJECTFOLDER**/lib/main_local.dart
[9:01:15 AM] [General] [Info] Using workspace as cwd: **PROJECTFOLDER**
[9:01:15 AM] [General] [Info] Detected launch project as Flutter
[9:01:15 AM] [General] [Info] Using Flutter debug adapter for this session
[9:01:15 AM] [General] [Info] Checking for errors before launching
[9:01:15 AM] [General] [Info] Debug session starting...
    {
        "name": “LOCAL”,
        "type": "dart",
        "request": "launch",
        "program": "**PROJECTFOLDER**/lib/main_local.dart",
        "args": [
            "--flavor",
            "local"
        ],
        "cwd": "**PROJECTFOLDER**",
        "dartVersion": "2.9.2",
        "toolEnv": {
            "FLUTTER_HOST": "VSCode",
            "PUB_ENVIRONMENT": "vscode.dart-code"
        },
        "sendLogsToClient": true,
        "vmAdditionalArgs": [],
        "vmServicePort": 0,
        "dartPath": "/Users/***/development/flutter/bin/cache/dart-sdk/bin/dart",
        "maxLogLineLength": 2000,
        "pubPath": "/Users/***/development/flutter/bin/cache/dart-sdk/bin/pub",
        "pubSnapshotPath": "/Users/***/development/flutter/bin/cache/dart-sdk/bin/snapshots/pub.dart.snapshot",
        "debugSdkLibraries": false,
        "debugExternalLibraries": false,
        "showDartDeveloperLogs": true,
        "evaluateGettersInDebugViews": true,
        "evaluateToStringInDebugViews": true,
        "globalFlutterArgs": [],
        "useFlutterStructuredErrors": true,
        "debugExtensionBackendProtocol": "ws",
        "flutterVersion": "1.20.3",
        "forceFlutterVerboseMode": false,
        "flutterTrackWidgetCreation": true,
        "flutterMode": "debug",
        "flutterPlatform": "default",
        "flutterPath": "/Users/***/development/flutter/bin/flutter",
        "workspaceConfig": {
            "useLsp": false
        },
        "deviceId": “***DEVICEID***”,
        "deviceName": “***DEVICENAME***”,
        "showMemoryUsage": false,
        "debuggerType": 2
    }
```

Flutter Doctor output:
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.20.3, on Mac OS X 10.15.6 19G2021, locale en-CH)
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    ✗ Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions.
[✓] Xcode - develop for iOS and macOS (Xcode 11.7)
[!] Android Studio (version 3.6)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.48.2)
[✓] Connected device (1 available)
```

Running the build in the terminal works.

**Comment by DanTup** [comment] 2020-09-10 11:16
The extension log doesn't contain everything for a debug session, so it's better to use [**Dart: Capture Logs**](https://dartcode.org/docs/logging/#capture-logs-command) (untick **Analysis Server** but leave everything else ticked and click OK), then reproduce the issue and then click **Cancel** on the logging notification to stop logging and open the log. The last lines of it will likely be the most interesting (it could be quite long since we run Flutter in verbose mode while capturing logs).

**Comment by dominikheeb** [comment] 2020-09-11 07:21
i tried to do that but in the log there is no new entry after `Debug session started` and the parameters i have sent in the first message. it seems to be blocked somehow.

**Comment by DanTup** [comment] 2020-09-14 09:23
@dominikheeb can you check if there are any errors listed in the VS Code console (Help -> Toggle Developer Tools -> Console)?

Also, does this happen in all projects, or just this one?

**Comment by dominikheeb** [comment] 2020-09-14 09:29
![Screenshot 2020-09-14 at 11 27 45](https://user-images.githubusercontent.com/10177284/93068932-5f64ae00-f67d-11ea-97fd-1fefc432d5b9.png)

This is what i have in the console. But they are already there when starting debug.
When i press start debug no additional line is printed.

**Comment by DanTup** [comment] 2020-09-14 09:39
Can you post a list of the other extensions you have installed, or try disabling everything except Dart + Flutter to see whether that changes anything?

Does it also happen with simple Dart projects? (You can use **Dart: New Project** to create a simple console app via Stagehand, or just open an empty folder with just a simple script inside `bin/` folder).

**Comment by dominikheeb** [comment] 2020-09-14 12:00
I already tried to reinstall vscode completely new therefore i only have flutter and dart installed.

Now i have tried it with some other project which used web technologies and for launch chrome debugger (i installed chrome extension just now for the test). With that extension it works.

**Comment by dominikheeb** [comment] 2020-09-15 07:02
Today morning it shortly worked but had an issue with the cocoapods not accessible. i fixed the issue according to https://github.com/flutter/flutter/issues/43079

After the first try it now stopped working, with the same issue again. Even when the other issue with the pods is fixed.

**Comment by DanTup** [comment] 2020-09-15 07:37
Can you check if it happens with simple Dart projects? (You can use **Dart: New Project** to create a simple console app via Stagehand, or just open an empty folder with just a simple script inside `bin/` folder). It may be easier to troubleshoot a simple Dart project than Flutter as there's less going on.

Can you also check which version of the Dart extension you have installed?

**Comment by dominikheeb** [comment] 2020-09-15 11:13
yes i have tried it with Dart: New Project. It did not help. The issue was the same.
I can reproduce now that when i startup vscode the first time it tries to start the debugger and the bars turn orange... there i have then an issue that the exension cannot find cocoapods even i have installed it and the same terminal call works for me
But after i reopen vscode it stopps working.

Dart Extension is 3.14.1

**Comment by DanTup** [comment] 2020-09-15 13:43
> I can reproduce now that when i startup vscode the first time it tries to start the debugger and the bars turn orange

It's starting the debugger without you doing anything? Or when you press F5?

> i have then an issue that the exension cannot find cocoapods

Are there two issues? One where sometimes the debug session doesn't start, and one where it starts but reports Cocoapods missing? If so, please open a separate issue for the Cocoapods issue to avoid confusing things in this one. This one can be for the debugger not starting.

In v3.14 of the extension there were some changes to how the debuggers launch. I'm going to make a build with some additional logging for you to try which might help track down what's going wrong. I'll post it back here with instructions shortly.

**Comment by DanTup** [comment] 2020-09-15 14:19
Please try this:

- Download the `vsix` file from https://github.com/Dart-Code/Dart-Code/releases/tag/v3.15.0-dev.2
- In VS Code, run the **Extensions: Install from VSIX** command and select the downloaded file
- Click **Reload** when prompted
- Open your Flutter project
- Run the **Dart: Capture Logs** command, untick **Analysis Server** but leave everything else ticked and click OK
- Try to run the project with `F5`
- Wait at least 30 seconds
- Click **Cancel** on the logging notification and attach the log here
- Also check Help -> Toggle Developer Tools -> Console again in VS Code, to ensure there are no useful errors recorded there

Thanks!

**Comment by dominikheeb** [comment] 2020-09-17 13:44
```
!! PLEASE REVIEW THIS LOG FOR SENSITIVE INFORMATION BEFORE SHARING !!

Dart Code extension: 3.15.0-dev.2
Flutter extension: 3.14.1 (activated)

App: Visual Studio Code
Version: 1.49.0
Platform: mac

Workspace type: Flutter
Analyzer type: DAS
Multi-root?: false

Dart SDK:
    Loc: /Users/***/development/flutter/bin/cache/dart-sdk
    Ver: 2.9.1
Flutter SDK:
    Loc: /Users/***/development/flutter
    Ver: 1.20.2

HTTP_PROXY: undefined
NO_PROXY: undefined

Thu Sep 17 2020 [15:37:30 GMT+0200 (Central European Summer Time)] Log file started
[3:37:36 PM] [General] [Info] Starting debug session...
[3:37:36 PM] [General] [Info]     workspace: /Users/***/Documents/Projects/**Project_folder**
[3:37:36 PM] [General] [Info]     program  : lib/main_dev.dart
[3:37:36 PM] [General] [Info] Converted program to absolute path: /Users/***/Documents/Projects/**Project_folder**/lib/main_dev.dart
[3:37:36 PM] [General] [Info] Using workspace as cwd: /Users/***/Documents/Projects/**Project_folder**
[3:37:36 PM] [General] [Info] Detected launch project as Flutter
[3:37:36 PM] [General] [Info] Using Flutter debug adapter for this session
[3:37:36 PM] [FlutterDaemon] [Info] ==> [{"id":"4","method":"daemon.getSupportedPlatforms","params":{"projectRoot":"/Users/***/Documents/Projects/**Project_folder**"}}]
[3:37:36 PM] [FlutterDaemon] [Info] <== [{"id":"4","result":{"platforms":["ios","android"]}}]
[3:37:36 PM] [FlutterDaemon] [Info] ==> [{"id":"5","method":"daemon.getSupportedPlatforms","params":{"projectRoot":"/Users/***/Documents/Projects/**Project_folder**"}}]
[3:37:36 PM] [FlutterDaemon] [Info] <== [{"id":"5","result":{"platforms":["ios","android"]}}]
[3:37:36 PM] [General] [Info] Checking for errors before launching
[3:37:36 PM] [General] [Info] Debug session starting...
    {
        "name": "iSA DEV",
        "type": "dart",
        "request": "launch",
        "program": "/Users/***/Documents/Projects/**Project_folder**/lib/main_dev.dart",
        "args": [
            "--flavor",
            "dev"
        ],
        "cwd": "/Users/***/Documents/Projects/**Project_folder**",
        "dartVersion": "2.9.1",
        "toolEnv": {
            "FLUTTER_HOST": "VSCode",
            "PUB_ENVIRONMENT": "vscode.dart-code"
        },
        "sendLogsToClient": true,
        "vmAdditionalArgs": [],
        "vmServicePort": 0,
        "dartPath": "/Users/***/development/flutter/bin/cache/dart-sdk/bin/dart",
        "maxLogLineLength": 2000,
        "pubPath": "/Users/***/development/flutter/bin/cache/dart-sdk/bin/pub",
        "pubSnapshotPath": "/Users/***/development/flutter/bin/cache/dart-sdk/bin/snapshots/pub.dart.snapshot",
        "debugSdkLibraries": false,
        "debugExternalLibraries": false,
        "showDartDeveloperLogs": true,
        "evaluateGettersInDebugViews": true,
        "evaluateToStringInDebugViews": true,
        "globalFlutterArgs": [],
        "useFlutterStructuredErrors": true,
        "debugExtensionBackendProtocol": "ws",
        "flutterVersion": "1.20.2",
        "forceFlutterVerboseMode": true,
        "flutterTrackWidgetCreation": true,
        "flutterMode": "debug",
        "flutterPlatform": "default",
        "flutterPath": "/Users/***/development/flutter/bin/flutter",
        "workspaceConfig": {
            "useLsp": false
        },
        "deviceId": "***SIMULATORID***",
        "deviceName": "iPad Pro (12.9-inch) (4th generation) (ios)",
        "showMemoryUsage": false,
        "debuggerType": 2
    }
[3:37:36 PM] [General] [Info] Using flutter debugger for Flutter
[3:37:36 PM] [General] [Info] Running debugger via node with /Users/***/.vscode/extensions/dart-code.dart-code-3.15.0-dev.2/out/dist/debug.js    flutter
Thu Sep 17 2020 [15:40:46 GMT+0200 (Central European Summer Time)] Log file ended

```

**Comment by dominikheeb** [comment] 2020-09-17 13:46
> It's starting the debugger without you doing anything? Or when you press F5?
When i press F5

Probably this are two issues and i will try to fix the other one later.

**Comment by dominikheeb** [comment] 2020-09-17 14:00
i am not sure if it helps but out of curiosity i ran the command node and then .load with the file mentioned on the last row of the log
`.load /Users/***/.vscode/extensions/dart-code.dart-code-3.15.0-dev.2/out/dist/debug.js`

The output ended with an error
```
Uncaught:
Error: Debugger type must be one of dart, dart_test, flutter, flutter_test, web, web_test but got undefined
    at Object.<anonymous> (REPL21:1:165839)
    at s (REPL21:1:124)
    at REPL21:1:923
```

**Comment by DanTup** [comment] 2020-09-23 17:24
Sorry for the delay!

```
Uncaught:
Error: Debugger type must be one of dart, dart_test, flutter, flutter_test, web, web_test but got undefined
    at Object.<anonymous> (REPL21:1:165839)
    at s (REPL21:1:124)
    at REPL21:1:923
```

This is definitely the source of the error, but I'm not sure what's happened. In your previous log, it shows:

```
[3:37:36 PM] [General] [Info] Running debugger via node with /Users/***/.vscode/extensions/dart-code.dart-code-3.15.0-dev.2/out/dist/debug.js    flutter
```

The `flutter` on the end is the arg that's being given to VS Code - so it's not clear why it didn't make it to the debug adapter.

I've made a new build that adds the process `argv` to the error you've included above:

https://github.com/Dart-Code/Dart-Code/releases/tag/v3.15.0-dev.3

If you can install that vsix and then reproduce the issue and get the error from that log, it might be clearer what's happening. I'd expect the `argv` to be:

- the path to node
- the path to the debug adapter
- the string "flutter"

However it seems like that might not be the case for you, though I'm not sure why,

**Comment by DanTup** [comment] 2020-09-25 09:37
> i am not sure if it helps but out of curiosity i ran the command node and then .load with the file mentioned on the last row of the log

Sorry - I mis-read this comment and thought this was in a VS Code error log. If you ran it manually, I would expect this error if you don't pass the argument through (which VS Code should be done).

There's another issue at #2819 that I wonder if may be the same as this.

**Comment by dominikheeb** [comment] 2020-09-29 06:22
Sorry i was not able to work on that bug for a few days
I tried it with the new extension (*-dev.3) and here is the log output

```
!! PLEASE REVIEW THIS LOG FOR SENSITIVE INFORMATION BEFORE SHARING !!

Dart Code extension: 3.15.0-dev.3
Flutter extension: 3.14.1 (activated)

App: Visual Studio Code
Version: 1.49.2
Platform: mac

Workspace type: Flutter
Analyzer type: DAS
Multi-root?: false

Dart SDK:
    Loc: /Users/***/development/flutter/bin/cache/dart-sdk
    Ver: 2.9.2
Flutter SDK:
    Loc: /Users/***/development/flutter
    Ver: 1.20.4

HTTP_PROXY: undefined
NO_PROXY: undefined

Tue Sep 29 2020 [08:17:09 GMT+0200 (Central European Summer Time)] Log file started
[8:17:10 AM] [General] [Info] Analyzer:FirstAnalysis timing: 12448ms
[8:17:14 AM] [General] [Info] Starting debug session...
[8:17:14 AM] [General] [Info]     workspace: /Users/***/Documents/Projects/***PROJECT***
[8:17:14 AM] [General] [Info]     program  : lib/main_dev.dart
[8:17:14 AM] [General] [Info] Converted program to absolute path: /Users/***/Documents/Projects/***PROJECT***/lib/main_dev.dart
[8:17:14 AM] [General] [Info] Using workspace as cwd: /Users/***/Documents/Projects/***PROJECT***
[8:17:14 AM] [General] [Info] Detected launch project as Flutter
[8:17:14 AM] [General] [Info] Using Flutter debug adapter for this session
[8:17:14 AM] [FlutterDaemon] [Info] ==> [{"id":"5","method":"daemon.getSupportedPlatforms","params":{"projectRoot":"/Users/***/Documents/Projects/***PROJECT***"}}]
[8:17:14 AM] [FlutterDaemon] [Info] <== [{"id":"5","result":{"platforms":["ios","android"]}}]
[8:17:14 AM] [FlutterDaemon] [Info] ==> [{"id":"6","method":"daemon.getSupportedPlatforms","params":{"projectRoot":"/Users/***/Documents/Projects/***PROJECT***"}}]
[8:17:14 AM] [FlutterDaemon] [Info] <== [{"id":"6","result":{"platforms":["ios","android"]}}]
[8:17:14 AM] [General] [Info] Checking for errors before launching
[8:17:14 AM] [General] [Info] Debug session starting...
    {
        "name": "*****",
        "type": "dart",
        "request": "launch",
        "program": "/Users/***/Documents/Projects/***PROJECT***/lib/main_dev.dart",
        "args": [
            "--flavor",
            "dev"
        ],
        "cwd": "/Users/***/Documents/Projects/***PROJECT***",
        "dartVersion": "2.9.2",
        "toolEnv": {
            "FLUTTER_HOST": "VSCode",
            "PUB_ENVIRONMENT": "vscode.dart-code"
        },
        "sendLogsToClient": true,
        "vmAdditionalArgs": [],
        "vmServicePort": 0,
        "dartPath": "/Users/***/development/flutter/bin/cache/dart-sdk/bin/dart",
        "maxLogLineLength": 2000,
        "pubPath": "/Users/***/development/flutter/bin/cache/dart-sdk/bin/pub",
        "pubSnapshotPath": "/Users/***/development/flutter/bin/cache/dart-sdk/bin/snapshots/pub.dart.snapshot",
        "debugSdkLibraries": false,
        "debugExternalLibraries": false,
        "showDartDeveloperLogs": true,
        "evaluateGettersInDebugViews": true,
        "evaluateToStringInDebugViews": true,
        "globalFlutterArgs": [],
        "useFlutterStructuredErrors": true,
        "debugExtensionBackendProtocol": "ws",
        "flutterVersion": "1.20.4",
        "forceFlutterVerboseMode": true,
        "flutterTrackWidgetCreation": true,
        "flutterMode": "debug",
        "flutterPlatform": "default",
        "flutterPath": "/Users/***/development/flutter/bin/flutter",
        "workspaceConfig": {
            "useLsp": false
        },
        "deviceId": "***SIM ID***",
        "deviceName": "iPad Pro (12.9-inch) (4th generation) (ios)",
        "showMemoryUsage": false,
        "debuggerType": 2
    }
[8:17:14 AM] [General] [Info] Using flutter debugger for Flutter
[8:17:14 AM] [General] [Info] Running debugger via node with /Users/***/.vscode/extensions/dart-code.dart-code-3.15.0-dev.3/out/dist/debug.js    flutter
Tue Sep 29 2020 [08:17:53 GMT+0200 (Central European Summer Time)] Log file ended
```
As it looks like it's the same output

Regarding the #2819: Looks for me like the same issue and there they also use MacOS.
I am also using mac with Version Catalina 10.15.6

**Comment by DanTup** [comment] 2020-09-29 08:31
Can you confirm that if you run:

```
node /Users/***/.vscode/extensions/dart-code.dart-code-3.15.0-dev.3/out/dist/debug.js flutter
```

That you do not get any errors, and the process does not immediately terminate?

I've opened a VS Code issue at https://github.com/microsoft/vscode/issues/107658 to try and get some pointers on tracking this down (VS Code is in charge of launching the process, so it's not something I can add additional logging to or debug).

It might be useful to see if this reproduces when running the Dart extension from source if you're able to test:

- Clone this repo
- Run `npm install` in the root folder
- Open in VS Code
- Press F5
- Wait for a second instance of VS Code to spawn (this is running from the built sources)
- Open a Flutter project in that second VS Code instance (it should say "Developer extension host" or similar in its title)
- Press F5 and see whether the debugger launches

**Comment by DanTup** [comment] 2020-09-29 08:39
Re-reading #2819, I don't think that's the same issue - that one does show the debug session started (though it appears to have stalled), whereas it seems like yours might not be even getting that far.

(I'm on the same version of macOS too, but still haven't been able to repro here)

**Comment by renanyoy** [comment] 2020-10-01 07:51
for me it happens sometime since few days, usually restarting vscode fix the problem

**Comment by dominikheeb** [comment] 2020-10-01 14:18
> for me it happens sometime since few days, usually restarting vscode fix the problem

Unfortunately for me restarting vscode or even restarting the macbook does not help
Only sometimes after a reboot it tries to start debug but then there is another issue which prevents the debug.

**Comment by DanTup** [comment] 2020-10-06 13:16
I've not ben able to reproduce this, so if anyone that can would be willing to test if it happens when running from source (see https://github.com/Dart-Code/Dart-Code/issues/2782#issuecomment-700538671 - as long as you have `npm` available it's relatively straight forward) that would make it much easier to debug.

Otherwise, I can to build a version with a dummy debug adapter that just logs when it is invoked, so we can see whether it's starting up or not.

**Comment by DanTup** [comment] 2020-10-06 13:30
@dominikheeb how are you capturing that output? Can you see the full command/arguments of the process?

**Comment by dominikheeb** [comment] 2020-10-06 14:47
I ran that command in zsh on the source path.
I understood your comment to try it out in terminal, or am i wrong :)

```
node /Users/***/.vscode/extensions/dart-code.dart-code-3.15.0/out/dist/debug.js flutter 
```

**Comment by DanTup** [comment] 2020-10-06 15:07
Got it - sorry, I thought you'd captured it from VS Code.

If manually running that command does not error, then that seems like it's probably working (it's waiting for a JSON command, which VS Code would normally send).

The question is whether VS Code is invoking this command when you try to start the debug session (if not, that seems like a VS code bug, but if it is, then it's like a bug in our debug adapter).

I'll build a version of the extension that starts logging immediately at debug-adapter startup soon and you can try that to see if it answers the question (otherwise in the meantime, you could rename that debug.js file out of the way and replace it with a simple node script that writes to a file, and see whether starting the debug session causes it to write to the file... the debug session will ofc fail, but it'll at least tell you that VS Code is running the script).

**Comment by DanTup** [comment] 2020-10-06 15:51
@dominikheeb could you try with the build from here?:

https://github.com/Dart-Code/Dart-Code/releases/tag/v3.16.0-dev.dalog.1

- Download the vsix
- Run the **Extensions: Install from VSIX** command in VS Code, and select the vsix file you downloaded
- Click the Reload button if necessary
- Reproduce the issue
- In a terminal run `ls $TMPDIR/ | grep dart-code-debug-adapter`

The debug adapter should generate a file each time it's launched, and one with `-error` on the end if there's an unhandled error. I'd be interested to know if any of those exist when you reproduce the issue.

Thanks!

**Comment by dominikheeb** [comment] 2020-10-21 09:18
Sorry i was in vacation, therefore i was not able to test it until now

The command returns no result

**Comment by DanTup** [comment] 2020-10-21 12:53
@dominikheeb thanks for checking - assuming you were definitely on the build above (and VS Code didn't auto-update it to the latest one, since there's a new version published since) then this seems to confirm that VS Code is not running the debug adapter (or, it's failing to start it and it's not giving a clear error). In that case it seems like we'll need assistance from VS Code (in https://github.com/microsoft/vscode/issues/107658).

**Comment by DanTup** [comment] 2020-11-12 07:53
Based on this [also affecting the TS language server](https://github.com/microsoft/vscode/issues/107658#issuecomment-714239038), I think there's something wrong with VS Code spawning Node processes, and I expect once that's understood/fixed this will start working too. I don't think there's anything to do in the Dart extension itself, so I'll close this one.

**Closed by DanTup** 2020-11-12 07:53 UTC
Labels: blocked on vs code / lsp / dap, in debugger, is bug
