### ISSUE TITLE
Disable addSdkToTerminalPath not working

### ISSUE THREAD

**Issue by quyenvsp** [Dart-Code/Dart-Code#4545] opened 2023-05-16 14:44 UTC
**Describe the bug**
When disable `addSdkToTerminalPath` it still add path to Integrated terminal.

**To Reproduce**
1. Setting `dart.addSdkToTerminalPath` to false
2. Close VSCode then open again (even restarted computer)
3. Run in Integrated terminal `which flutter`
4. See result, it still add default flutter location to Path

**Expected behavior**
Don't touch anything in PATH when `addSdkToTerminalPath` disabled.

**Screenshots**
Problem - it still select one version in many version at Sdk Paths then set to ahead $PATH
![problem](https://github.com/Dart-Code/Dart-Code/assets/35319492/61f1ea39-2e4e-4f49-a234-03ca1d14b589)

Normal - when not open Flutter project, it is correct $PATH which set in system variables
![normal](https://github.com/Dart-Code/Dart-Code/assets/35319492/e3d797b2-6a04-4f38-8e91-a7f2ea82f08d)

**Please complete the following information:**
 - Operating System and version: Windows 11
 - VS Code version: 1.78.2 (user setup)
 - Dart extension version: v3.64.0 (tried pre-release, same issue)
 - Dart/Flutter SDK version: Dart 3.0.0 / Flutter 3.10.0

**Comment by DanTup** [comment] 2023-05-16 14:57
I don't seem to be able to reproduce this. The code in the extension is definitely wrapped with a check for this setting:

https://github.com/Dart-Code/Dart-Code/blob/557630c30c14f30b7a050f9febd718de5076f7c5/src/extension/extension.ts#L197-L203

I notice that your paths are in a different format (you have a Windows path in your settings, but not in the `which` output) - are you using WSL or something?

Could you also try clicking the trashcan icon against the affected terminal and re-create it to see if that makes a difference? I think VS Code tries to reuse terminal sessions but I don't know what it persists for them.

**Comment by quyenvsp** [comment] 2023-05-16 15:35
Hi,

Thank so much for your quick response. I found a solution but these are more info maybe helpful other.

I current using windows 11 + fvm (with alias flutter = fvm flutter) + git bash for windows.

> I notice that your paths are in a different format

It is git bash, but I used Three dot > Clear terminal for clear data so it look like that.

> Could you also try clicking the trashcan icon

Yeah I tried on two computer but same error.

Solution is disable `addSdkToTerminalPath` first then disabled Flutter / Dart plugin then enable again. It working now but I will keep tracking it more.

**Comment by DanTup** [comment] 2023-05-16 15:57
Turns out I can repro this now. I'm not sure what I did wrong earlier - although I note that after restarting VS Code I _do_ need to click the trashcan to delete the terminal before any `PATH` change takes effect (so there's definitely some additional caching going on beyond this).

**Comment by DanTup** [comment] 2023-05-16 16:02
Fixed by d011b9a9.

**Closed by DanTup** 2023-05-16 16:02 UTC
Labels: is bug
