### ISSUE TITLE
Dart DevTools exited with code 255 in brand new flutter installation

### ISSUE THREAD

**Issue by pedromtcosta** [Dart-Code/Dart-Code#2434] opened 2020-05-06 20:16 UTC
I am seeing this error message when trying to open DevTools from Visual Studio Code:

![image](https://user-images.githubusercontent.com/20377169/81223631-97c8f100-8fe6-11ea-9396-0b4feaec1a62.png)

![image](https://user-images.githubusercontent.com/20377169/81223655-a3b4b300-8fe6-11ea-9ab1-b24884fbc4da.png)

I tried running `flutter pub global activate devtools` but this didn't fix the issue.
I also tried running `flutter pub global run devtools`, but then I see this other error:

> pub finished with exit code 65

I am not sure which other information is needed, so please let me know in case I need to provide anything else

**Comment by DanTup** [comment] 2020-05-06 21:42
Can you try running `pub global activate devtools` and if that completes without error, restart VS Code and try again. I suspect your pub cache may have a broken version of DevTools.

@mit-mit FYI, I've had quite a few reports lately where people seem to have copies of devtools in pub cache missing the pubspec.yaml and it needs to be reactivated (for ex. see #2398, #2128). I've implemented [a prompt](https://github.com/Dart-Code/Dart-Code/issues/2430#issuecomment-624703937) to help fix this in the next version, though it feels like there have been more reports in the last week or so than previous. I'm not sure what causes it (besides nuking the pub-cache, but I'm not sure if that's common).

**Comment by pedromtcosta** [comment] 2020-05-06 22:06
Is `pub global activate devtools` the same as `flutter pub global activate devtools`? I already tried the second, and it indeed completes without errors. If I try running without the `flutter `at the beginning, I get this error, presumably because I am missing something on my Path environment variable:

> The term 'pub' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

**Comment by rafaelcr** [comment] 2020-05-07 01:20
I was able to fix this same issue with the commands you referenced on the other threads @DanTup, however my path to `pub` was different:
```
/usr/local/flutter/bin/cache/dart-sdk/bin/pub
```
Thanks

**Comment by siva636** [comment] 2020-05-07 06:18
I also solved similar issue by running `pub global activate devtools`.

In my case pub is at ` /Applications/flutter/bin/cache/dart-sdk/bin/pub`

If you are still trying to locate `pub`, this post may be helpful:
https://stackoverflow.com/questions/50321966/where-is-darts-sdk-located-within-flutter-folder

**Comment by DanTup** [comment] 2020-05-07 06:27
> Is `pub global activate devtools` the same as `flutter pub global activate devtools`?

It depends how you installed Flutter, but if running `flutter pub` didn't fix it, I would expect `pub` to. `flutter pub` and `pub` may have different pub-cache folders, and VS Code always uses `pub` when running DevTools (because it can be launched from non-Flutter apps and we don't want to maintain two activated versions).

If `pub` isn't in your `PATH`, you'll need to provide the full path. That path may vary depending on where you've installed Flutter, but it's at `(flutter sdk)/bin/cache/dart-sdk/bin/pub`.

Please let me know if you still have issues launching in VS Code after running `pub global activate devtools` (not `flutter pub`). This will become easier [in the next version of VS Code](https://github.com/Dart-Code/Dart-Code/issues/2430#issuecomment-624703937).

If anyone knows why `pub` thinks they have DevTools installed but does not have a pubspec, I'd love to understand why this is happening so much lately. Have you manually deleted your pub cache folders or anything similar?

**Comment by DanTup** [comment] 2020-05-07 07:20
Ok, I've figured out what's happening.

The more recent failures to activate are not a missing pubspec as the previous reports were (I noticed now there's a different error code), but actually a bad release of DevTools this week (v0.2.4) which fails to load with an error.

The updated version of DevTools was published as version 0.2.4+1 but Dart-Code considers this version to be equal to 0.2.4 because it uses a standard semver library (which [differs slightly](https://pub.dev/packages/pub_semver) from pubs version handling) which means it isn't auto-updated before running (FYI @jacob314 - what I said yesterday about auto-updating was slightly incorrect because of this).

I'll try to improve the version check to more closely reflect how Pub works. In the meantime, the best fix for this is still to run `pub global activate devtools` (without a `flutter` prefix).

**Comment by siva636** [comment] 2020-05-07 08:44
What if the fixed version (in our case version 0.2.4+1) is not available yet and I have already upgraded to the bad version?
How can I downgrade my devtools to a previous working version?
@DanTup Please let me know whether it is possible.

**Comment by DanTup** [comment] 2020-05-07 08:49
> What if the fixed version (in our case version 0.2.4+1) is not available yet and I have already upgraded to the bad version?

The new version is already published on Pub, but if you're using a mirror or something that prevents you getting it, you should be able to downgrade to the previous version with `pub global activate devtools 0.2.3`.

**Comment by pedromtcosta** [comment] 2020-05-07 15:51
Running `pub global activate devtools` without `flutter` in the beginning fixed the issue for me.
Thank you very much for the help! :)

**Comment by DanTup** [comment] 2020-05-11 15:59
Closing this as fixed by https://github.com/Dart-Code/Dart-Code/issues/2430 and https://github.com/Dart-Code/Dart-Code/issues/2436 in the next version.

**Closed by DanTup** 2020-05-11 15:59 UTC
Labels: awaiting info

**Comment by yahu1031** [comment] 2020-10-03 19:02
@tdnghia98 I guess that's not on `Roaming` directory. It is on `Local` directory. And anyone can add path in this way `%USERPROFILE%\AppData\Local\Pub\Cache\bin` (copy and paste this)

**Comment by DanTup** [comment] 2020-10-04 11:38
For this seeing this issue recently, it's caused by not having Chrome installed and the DevTools server is trying to launch Chrome. There's an open issue at https://github.com/flutter/devtools/issues/2405 which I've opened a PR for.

**Comment by yahu1031** [comment] 2020-10-04 14:19
yeah I agree but till date I have used then in VSCode itself. but after flutter v 1.22 update i got this issue and then i installed Google Chrome. then it works.

**Comment by DanTup** [comment] 2020-10-04 16:50
The issue was introduced with a DevTools update that just happened to go out around the same time as the Flutter update. VS Code will have auto-updated your DevTools to the latest one and then hit this issue.

Installing Google Chrome is the only workaround I know of until the DevTools fix is available in a release.

**Comment by AsteriskZuo** [comment] 2021-02-01 05:42
I had the same problem. Try the following:    
1. Upgrade Flutter to 1.22.6    
2. Run the command `pub global activate devtools`   
3. Execute devtools in the terminal  
Resolved.

**Comment by Demoxing** [comment] 2021-12-22 09:49
I cant able to run the comment. It's showing me an error. 
`zsh: command not found: pub`
I am using flutter v2.5.3, and I can't update it for some reason. Someone, please tell me a fix for this error?

**Comment by DanTup** [comment] 2021-12-22 11:37
@Demoxing if you're using DevTools inside VS Code, you shouldn't need to run the commands manually from the terminal. If you do want to run them from the terminal, you need to ensure `pub` is on your `PATH` if using pub, or just use `flutter pub` instead.

If you upgrade to the latest version of Flutter, you can also just use `dart devtools` instead of going through `pub` (which is the preferred method now).

**Comment by jswolf19** [comment] 2021-12-23 03:15
@Demoxing you may be having this issue:

https://github.com/flutter/devtools/issues/3549#issuecomment-998961200

**Comment by Demoxing** [comment] 2021-12-23 03:18
> flutter/devtools#3549 (comment)

Exactly. But any idea why this issue is happening?

**Comment by iliyami** [comment] 2021-12-23 16:20
> 

I had the same issue and pub global activate devtools solved it.

**Comment by iliyami** [comment] 2021-12-23 16:21
> 

I had the same issue and pub global activate devtools solved it.

**Comment by DanTup** [comment] 2022-01-04 16:18
There was an issue with a recent version of DevTools. The version was retracted, but if you're not on the latest version of the Dart/Flutter SDKs, it does not understand package retraction (see https://github.com/flutter/devtools/issues/3549#issuecomment-1003962841) and installs that version anyway.

Until a new version of DevTools is published, the available fixes are:

- Update to the latest stable Dart/Flutter SDK
- [Disable the automatic updating of DevTools in VS Code](https://user-images.githubusercontent.com/1078012/147755389-8db3e5c2-c926-4fcb-9e8c-3533b370c156.png), then run `dart pub global activate devtools 2.8.0` then restart VS Code.

Let me know if you still have issues after this. Thanks!

**Comment by DanTup** [comment] 2022-01-04 18:47
A new version of DevTools has been published that fixes this, so it's no longer necessary to disable updates in the VS Code settings. Just run `dart pub global activate devtools` and leave the setting ticked and everything should be good.
