### ISSUE TITLE
Support launching flutter apps from sub-folders of workspace root

### ISSUE THREAD

**Issue by dwaindibbly** [Dart-Code/Dart-Code#385] opened 2017-07-23 13:30 UTC
When I try to do a flutter debug from something that looks like

```
Big Project\
| Client Project (flutter app)
```

which means the flutter app is in `${workspaceRoot}/client`

And I use `"cwd": "${workspaceRoot}/client"` in the configuration, it tells me `Unable to restart debugging. Please try ending the debug session and starting again.`

It happens even when I say it's in the absolute path!

Why does this happen?

Is it a bug?

**Comment by DanTup** [comment] 2017-07-23 13:48
Currently there are lots of assumptions that the opened folder is the project root, so I don't know if what you want will work properly.

The error you provided happens when the debug information passed to the debug adapter is missing the `program` option. This normally happens because you edited `launch.json` during a debug session and then clicked `Restart`, which is a VS Code bug ([discussed here](https://github.com/Microsoft/vscode/issues/28175#issuecomment-308417798)).

Do you see the same issue if you aren't editing the `launch.json` during a debug session? If so, you could try providing the `program` attribute set to the entry point (`${workspaceRoot}client/lib/main.dart`?).

I'm not sure whether supporting non-root folders is worthwhile when Code is currently adding support for multiple-folder workspaces:

https://code.visualstudio.com/updates/v1_14#_preview-multi-root-workspaces

I might hold off a while and see how that gets used. If all other integrations assume multiple projects will be handled using that, I'll probably do the same. However, if opening a "parent" folder still seems like a common thing to do, we should definitely support it too.

**Comment by dwaindibbly** [comment] 2017-07-23 14:07
I didn't edit the launch.json while debugging, all that happened was

1. Start debugging
2. Error

Immediately!

**Comment by DanTup** [comment] 2017-07-23 14:17
@dwaindibbly Aha; I think I see some problems... The project is not being detected as a Flutter project because there's no root `pubspec.yaml` file containing `sdk: flutter`. So this tries to use Dart debugging config (which normally has a `program`) and then the debugger finds the program missing and assumes it's because of the bug above.

I don't know how easily I can resolve this - there are some questions that are hard to answer when you open a folder containing multiple projects - for example, if there's both a Flutter and a Dart project inside it, which SDK do we use? The Flutter one or the Dart one? Have you come from another IDE which supports this that I can maybe get ideas from?

**Comment by dwaindibbly** [comment] 2017-07-23 14:33
I originate from vscode,

Anyways, i know how to choose it,

1. check **cwd** for **pubspec.yaml**
2. choose method!

**Comment by DanTup** [comment] 2017-07-23 15:27
It's not quite that simple; there's a lot of code that relies on knowing whether you're editing a flutter project (for example, which SDK to use for the analyzer, whether to show flutter commands in the palette, whether to launch the flutter daemon and present the device selection).

Having multiple projects complicates this, and I'm under the impression the Flutter-bundled SDK is different to the standard Dart one, so it might not be valid to start the analyzer using the Dart SDK for flutter projects; unfortunately I don't know a lot about the differences (@devoncarew - any notes on this? Is it possible now, or planned for the future that a single SDK will work for both Flutter and Dart? Is it safe to always take the Flutter version? Do other IDEs currently support Flutter + Dart projects in the same workspace root?).

I think I can work around a lot of these questions/issues by changing the `isFlutterProject` flag we have to `workspaceContainsFlutterProject` and map the paths based on the `cwd` passed to the debugger (if it's not already using that). Will need to review things that use this (eg. we disabled SdkManager for non-flutter projects, but it shouldn't be disabled if the workspace contains a single flutter project but also has Dart projects).

@devoncarew Actually, now we have an SDK Chooser, I'm wondering if we should just default to the first Flutter SDK we find and let the user override if they wish. Curious about other IDEs though!

**Comment by DanTup** [comment] 2017-07-23 15:31
I'll try to improve this for the next release.

**Comment by devoncarew** [comment] 2017-07-24 04:38
Some notes for how IntelliJ handles this (which may be useful techniques in general):
- it has a notion of a project and modules - the project is the container. Others IDEs I've worked with would have named this a workspace and projects
- IntelliJ launches one analysis server per project
- the sdk settings live off the modules, so you could have n different sdks set
- we choose the dart sdk from the first module as the one to load the analysis server from. This is somewhat arbitrary, but it's likely that all the modules will be related, so the user will be keeping the sdks ~in sync, and they have a workaround if sdk skew does become an issue (adjust how they've divided the project/module organization)

**Comment by devoncarew** [comment] 2017-07-24 04:39
Also, given that VSCode is a somewhat more ephemeral app than IntelliJ, it may also be reasonable to expect the user to launch an instance per project root.

**Comment by DanTup** [comment] 2017-07-31 10:33
I'm going to hold off doing anything here until VS Code's multi-root support is a bit more defined. I don't want to do work to start spawning multiple analyzers within a workspace manually if it might turn out that multi-root projects is the best way to open projects like this (which I will need to spawn multiple analyzers for).

For now, the workaround is to just open the Flutter project as the root and everything should work as expected. I appreciate this isn't ideal!

**Comment by dwaindibbly** [comment] 2017-08-01 11:31
well... at least the analyzer is fine! it's the same all the time after all :smiley:

**Comment by DanTup** [comment] 2017-11-26 20:36
I think this would be better handled by opening the flutter folder as a new folder in the workspace. I believe this works even if it's already a child of another folder.

I'll do some testing over the next week since I'm working on multi-root support.

**Comment by DanTup** [comment] 2017-12-09 16:43
I'm going to consider this a dupe of #453. The best way to handle this is to add the flutter project as a root - this way it gets its own debug config, etc.

In my testing, it works fine to have multiple folders open even when one is a descendant of the other; eg I can open:

- flutter
- flutter/examples/stocks

And I can run the Stocks app and debug as expected.

Once v2.6.0 ships with multi-root support, let me know if this doesn't work for you.

**Closed by DanTup** 2017-12-09 16:43 UTC
Labels: duplicate

**Comment by DanTup** [comment] 2018-01-04 19:42
Since this came up again today, I've opened #493 to look at helping users set things up better. I still think using multi-root support (and not walking down the tree) is the best way; but currently users don't know they should do this and the thing they expect to work (setting the cwd) doesn't.

**Comment by DanTup** [comment] 2018-03-03 11:12
FWIW, I'm revisiting this and plan to better support projects in sub-folders (see #493).
