### ISSUE TITLE
Debugging flutter tests fail if the descrription string has an interpolated value and a is composed of two concatenated strings

### ISSUE THREAD

**Issue by WorikQCI** [Dart-Code/Dart-Code#4250] opened 2022-11-06 20:03 UTC
**Describe the bug**
If the description of the test has an interpolated value and a is composed of two concatenated strings the test will not run

**To Reproduce**

Write a test like the following and try to run it by clicking the debug option 

![image](https://user-images.githubusercontent.com/95715668/200192354-9cb12fbd-05d4-4108-871d-6f1f2c294c73.png)

```
import 'package:test/test.dart';

void main() async {
  //
  int foo = 1;
  test("Start string $foo " "  end string", () async {
    expect(true, true);
  });
}
```

Get this result:

```
Connecting to VM Service at http://127.0.0.1:64510/Y0ktArhJg9g=/ws
No tests match regular expression "^Start string .* " "  end string( \(variant: .*\))?$".
Exited (1)
```
**Expected behavior**

I expect the test to run.

**Please complete the following information:**
 - Operating System and version:
   MacOS 12.6
 - VS Code version:
 
```
Version: 1.72.2 (Universal)
Commit: d045a5eda657f4d7b676dedbfa7aab8207f8a075
Date: 2022-10-12T22:16:30.254Z
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin arm64 21.6.0
Sandboxed: No
```

 - Dart extension version:
v3.52.1

 - Dart/Flutter SDK version:
`Dart SDK version: 2.18.4 (stable) (Tue Nov 1 15:15:07 2022 +0000) on "macos_arm64"`
 - Target device (if the issue relates to Flutter debugging):

**Comment by DanTup** [comment] 2022-11-07 10:43
Merging this into #4021 since that should fix a number of issues with non-trivial test names like this one.

**Comment by DanTup** [comment] 2023-04-18 15:58
Re-opening this for tracking to ensure this issue is fixed by the upcoming support for running tests by lines.

**Closed** 2023-04-19 17:56 UTC
Labels: is bug, in testing

**Comment by DanTup** [comment] 2023-04-19 18:03
In the next release (and the pre-release version just pushed today - v3.63.20240419), you can choose to have tests executed using their line numbers rather than their names. This fixes a number of issues including this one, caused by not always being able to statically compute the exact name of a test. 

![Test Invocation settings](https://user-images.githubusercontent.com/1078012/233161136-294c72e9-5a28-489b-bfc0-cd786636233c.png)

Please let me know if you find any issues with this functionality!

**Comment by WorikQCI** [comment] 2023-04-19 23:07
I have been away from VSCode so I have not been paying attention.

One obvious solution is to insist that test names are static.

IMO it is bad practice to put dynamic data there, and I no longer d it.  The test should have the same name each time it is run.

I hope this makes sense, as I say I am away from VSCode so you do not have my full attention!

thank you for all your work!

**Comment by DanTup** [comment] 2023-04-20 08:40
> One obvious solution is to insist that test names are static.
> IMO it is bad practice to put dynamic data there

Yeah, I think there has been discussion about a lint to enforce this. But there are a lot of tests out there today that do it and I don't think the test runner here should just be broken. There were a bunch of other related issues (not strictly about using variables in names, but just using some helper/wrapper functions that made it difficult to run tests) and the fix for them all was the same so it was worth handling :-)
