### ISSUE TITLE
Flutter apps won't debug

### ISSUE THREAD

**Issue by Mugiwara98** [Dart-Code/Dart-Code#2242] opened 2020-01-30 18:25 UTC
After I had factory reset my MacBook Air(2019) and reinstalled flutter my apps wont start/debug. When I start debugging, both the IOS and Android emulators would start, but after that the app doesn't launch, the debug console would be empty, and gradle assemble would never run. The debug banner would also disappear if I press restart. 
I've ran flutter doctor as well and no issues were shown 
i've also ran flutter clean within the application, but it didn't make a difference

<img width="1361" alt="Screen Shot 2020-01-30 at 1 19 40 PM" src="https://user-images.githubusercontent.com/57771801/73478162-8fb44200-4363-11ea-90ca-ea2d1e3537c8.png">
<img width="786" alt="Screen Shot 2020-01-30 at 1 20 04 PM" src="https://user-images.githubusercontent.com/57771801/73478167-92af3280-4363-11ea-99b1-063344524e39.png">

**Comment by DanTup** [comment] 2020-01-30 19:29
Does it work if you try `flutter run` from a terminal?

**Comment by Mugiwara98** [comment] 2020-01-30 19:57
> Does it work if you try `flutter run` from a terminal?

Yes it works with the iphone emulator, but not the android emulator. It would sit on assembling graddle and then move to "this is taking unexpectedly long" and not deploy.

**Comment by codmajik** [comment] 2020-01-31 04:40
I am also facing this issue

**Comment by DanTup** [comment] 2020-01-31 15:37
Please try running the **Dart: Capture Logs** command from the VS Code command palette (untick **Analysis Server** but leave everything else ticked) then reproduce the issue.

If it seems to be stuck, please leave it at least a few minutes, so if anything times out it will be visible in the logs.

After a few minutes of it being stuck, click **Cancel** on the logging dialog, and it'll open a log. Please check there's nothing sensitive in there and paste it into [a gist](https://gist.github.com/) or similar, with a link here. Thanks!

**Comment by Mugiwara98** [comment] 2020-01-31 18:58
> Please try running the **Dart: Capture Logs** command from the VS Code command palette (untick **Analysis Server** but leave everything else ticked) then reproduce the issue.
> 
> If it seems to be stuck, please leave it at least a few minutes, so if anything times out it will be visible in the logs.
> 
> After a few minutes of it being stuck, click **Cancel** on the logging dialog, and it'll open a log. Please check there's nothing sensitive in there and paste it into [a gist](https://gist.github.com/) or similar, with a link here. Thanks!

also for future situation, what kind of sensitive information would the logs produce?
https://gist.github.com/Mugiwara98/68c1b6f35ff6b3d26c26333620d5936d

**Comment by DanTup** [comment] 2020-01-31 19:03
> https://gist.github.com/Mugiwara98/68c1b6f35ff6b3d26c26333620d5936d

Is it possible you didn't have `Flutter Run` ticked when you collected this? There aren't any logs at all from it. If you definitely did, can you try clicking Help -> Toggle Developer Tools in VS Code, and then check the Console tab (after reproducing again) and see if there are any errors listed?

> also for future situation, what kind of sensitive information would the logs produce?

In this case, only really path names (which may be sensitive for some, but are usually fine). However if you leave **Analysis Server** ticked (which is useful when debugging editor/analysis server issues) then it may have source code from your open files.

**Comment by Mugiwara98** [comment] 2020-01-31 19:22
> > https://gist.github.com/Mugiwara98/68c1b6f35ff6b3d26c26333620d5936d
> 
> Is it possible you didn't have `Flutter Run` ticked when you collected this? There aren't any logs at all from it. If you definitely did, can you try clicking Help -> Toggle Developer Tools in VS Code, and then check the Console tab (after reproducing again) and see if there are any errors listed?
> 
> > also for future situation, what kind of sensitive information would the logs produce?
> 
> In this case, only really path names (which may be sensitive for some, but are usually fine). However if you leave **Analysis Server** ticked (which is useful when debugging editor/analysis server issues) then it may have source code from your open files.

Yup it was ticked. I preformed capture logs again and the output was the same, but this is what was logged in the developer tools console.

<img width="796" alt="Screen Shot 2020-01-31 at 2 19 26 PM" src="https://user-images.githubusercontent.com/57771801/73567778-1422c580-4435-11ea-94a1-0f2e2ccdd1dc.png">

**Comment by Mugiwara98** [comment] 2020-01-31 19:31
Here's also my second attempt with capture logging
https://gist.github.com/Mugiwara98/68c1b6f35ff6b3d26c26333620d5936d

**Comment by DanTup** [comment] 2020-02-13 17:24
Hmm, something seems wrong. Could you try running `Developer: Show Logs` in VS Code and go through each of the logs to see if there's any error message logged?

Also, it's a bit of a stab in the dark, but you could try uninstalling/reinstalling the extension in case something is corrupt in the debug adapter (it seems unlikely, but people have reported strange errors that they fixed by doing this before).

**Comment by Mugiwara98** [comment] 2020-02-18 22:37
Windows:
<img width="1083" alt="Screen Shot 2020-02-18 at 5 33 54 PM" src="https://user-images.githubusercontent.com/57771801/74784067-15e1eb00-5275-11ea-9071-0192ab1ce0f6.png">

Extension Host:
<img width="1113" alt="Screen Shot 2020-02-18 at 5 34 34 PM" src="https://user-images.githubusercontent.com/57771801/74784070-18444500-5275-11ea-85ab-3f0e12575f32.png">

**Comment by DanTup** [comment] 2020-02-24 11:42
Nothing obvious there. Did you try uninstall/reinstalling the Dart extension? (You may need to uninstall the Flutter extension first, then uninstall Dart, then re-install Flutter which will include Dart).

If that doesn't help, could you try disabling any other debug-related extensions (for example the Firefox one) just to make sure we're not conflicting with anything there.

This this happen for all projects (for example a new `flutter create` project)? Are you able to debug other types (non-Dart/Flutter) projects ok?

**Comment by DanTup** [comment] 2020-04-21 10:29
If you're still seeing this and are able to try the things above and it doesn't help, let me know and I'll re-open this and do some more investigation. Thanks!

**Closed by DanTup** 2020-04-21 10:29 UTC
Labels: awaiting info
