### ISSUE TITLE
add dart.sdkPath to PATH in vscode terminal.

### ISSUE THREAD

**Issue by bsutton** [Dart-Code/Dart-Code#4231] opened 2022-10-21 21:31 UTC
Don't know if this is even possible but...

Dart code lets you specify a project specific path to a flutter or dart version via:

dart.sdkPath
dart.flutterSdkPath

I use the vs-code terminal quite a lot for lots of actions, even 'dart pub get'.

It would be quite nice if either of the above settings were reflected in the terminals PATH so that running a cli dart command in the vs-code terminal would result in the correct version of dart being executed.

You can see here the mismatch:

![image](https://user-images.githubusercontent.com/900408/197291529-dca91454-e6bd-44e6-9a0c-9f3e15203fc0.png)

**Comment by DanTup** [comment] 2022-10-22 08:23
Yeah, this is unfortunate. We have an open issue about it at #737. I filed an issue with VS Code about having support for this (https://github.com/microsoft/vscode/issues/46696) and they added some functionality, but it does not work consistently across platforms (in particular, it's broken on a default macOS install - https://github.com/microsoft/vscode/issues/99878).

I don't want to ship different behaviour across platforms so I'm waiting for that to be fixed. There has been some work on better integrating the terminal in recent VS Code releases which I think might make it easier for them to fix, but I'm not certain.

(I'll close this as a dupe of #737, we can contiue any discussion there - thanks!).

**Closed by DanTup** 2022-10-22 08:23 UTC
Labels: is enhancement
