### ISSUE TITLE
The Dart Analyzer has Terminated [In VS Code & Android Studio]

### ISSUE THREAD

**Issue by zgramming** [Dart-Code/Dart-Code#2168] opened 2019-12-12 03:10 UTC
# Update
Because this , I can't hot reload with ctrl +s (save), although i already setting hot reload on save.
<img src="https://i.stack.imgur.com/Duj5B.png" height="400">

Dart Analyzer still running ...

<img src="https://i.stack.imgur.com/K4JQ5.png" height="">

After update the latest Dart SDK i got some problem with Dart Analyzer.
Every opened project the loading indicator of Analyzer still running , until when it's crash and give me log like this : 
## Log Analyzer 
```
Dart Code extension: 3.7.1
Flutter extension: 3.7.1 (not activated)
VS Code: 1.40.2
Platform: win
HTTP_PROXY: undefined
NO_PROXY: undefined

Thu Dec 12 2019 [10:02:13 GMT+0700 (Western Indonesia Time)] Log file started
[10:02:13 AM] [General] [Info] Searching for SDKs...
[10:02:13 AM] [General] [Info] Environment PATH:
[10:02:13 AM] [General] [Info]     C:\WINDOWS\system32
[10:02:13 AM] [General] [Info]     C:\WINDOWS
[10:02:13 AM] [General] [Info]     C:\WINDOWS\System32\Wbem
[10:02:13 AM] [General] [Info]     C:\WINDOWS\System32\WindowsPowerShell\v1.0\
[10:02:13 AM] [General] [Info]     C:\Program Files\Git\cmd
[10:02:13 AM] [General] [Info]     C:\Program Files\PowerShell\6\
[10:02:13 AM] [General] [Info]     C:\Program Files\Dart\dart-sdk\bin
[10:02:13 AM] [General] [Info]     C:\xampp\php
[10:02:13 AM] [General] [Info]     C:\ProgramData\ComposerSetup\bin
[10:02:13 AM] [General] [Info]     C:\WINDOWS\System32\OpenSSH\
[10:02:13 AM] [General] [Info]     C:\Users\user\AppData\Local\Programs\Microsoft VS Code\bin
[10:02:13 AM] [General] [Info]     C:\flutter\flutter\bin
[10:02:13 AM] [General] [Info]     C:\Users\user\AppData\Roaming\Composer\vendor\bin
[10:02:13 AM] [General] [Info]     C:\Users\user\AppData\Local\Microsoft\WindowsApps
[10:02:13 AM] [General] [Info]     C:\Program Files\Android\Android Studio\jre\bin
[10:02:13 AM] [General] [Info]     C:\Users\user\AppData\Roaming\Dashlane\6.1940.1.24013\bin\Firefox_Extension\{442718d9-475e-452a-b3e1-fb1ee16b8e9f}\components
[10:02:13 AM] [General] [Info]     C:\Users\user\AppData\Roaming\Dashlane\6.1940.1.24013\ucrt
[10:02:13 AM] [General] [Info]     C:\Users\user\AppData\Roaming\Dashlane\6.1940.1.24013\bin\Qt
[10:02:13 AM] [General] [Info]     C:\Users\user\AppData\Roaming\Dashlane\6.1940.1.24013\bin\Ssl
[10:02:13 AM] [General] [Info]     C:\Users\user\AppData\Local\Android\Sdk
[10:02:13 AM] [General] [Info] Found Flutter project at C:\Project Flutter\Udemy\great_place_app:
			Mobile? true
			Web? false
			Create Trigger? false
			Flutter Repo? false
[10:02:13 AM] [General] [Info] Searching for flutter.bat
[10:02:13 AM] [General] [Info]     Looking for flutter.bat in:
[10:02:13 AM] [General] [Info]         C:\Project Flutter\Udemy\great_place_app
[10:02:13 AM] [General] [Info]         C:\Project Flutter\Udemy\great_place_app\bin
[10:02:13 AM] [General] [Info]         C:\flutter\flutter\bin\
[10:02:13 AM] [General] [Info]         C:\Project Flutter\Udemy\great_place_app\.flutter
[10:02:13 AM] [General] [Info]         C:\Project Flutter\Udemy\great_place_app\.flutter\bin
[10:02:13 AM] [General] [Info]         C:\Project Flutter\Udemy\great_place_app\vendor\flutter
[10:02:13 AM] [General] [Info]         C:\Project Flutter\Udemy\great_place_app\vendor\flutter\bin
[10:02:13 AM] [General] [Info]         C:\WINDOWS\system32
[10:02:13 AM] [General] [Info]         C:\WINDOWS\system32\bin
[10:02:13 AM] [General] [Info]         C:\WINDOWS
[10:02:13 AM] [General] [Info]         C:\WINDOWS\bin
[10:02:13 AM] [General] [Info]         C:\WINDOWS\System32\Wbem
[10:02:13 AM] [General] [Info]         C:\WINDOWS\System32\Wbem\bin
[10:02:13 AM] [General] [Info]         C:\WINDOWS\System32\WindowsPowerShell\v1.0\
[10:02:13 AM] [General] [Info]         C:\WINDOWS\System32\WindowsPowerShell\v1.0\bin
[10:02:13 AM] [General] [Info]         C:\Program Files\Git\cmd
[10:02:13 AM] [General] [Info]         C:\Program Files\Git\cmd\bin
[10:02:13 AM] [General] [Info]         C:\Program Files\PowerShell\6\
[10:02:13 AM] [General] [Info]         C:\Program Files\PowerShell\6\bin
[10:02:13 AM] [General] [Info]         C:\Program Files\Dart\dart-sdk\bin
[10:02:13 AM] [General] [Info]         C:\xampp\php
[10:02:13 AM] [General] [Info]         C:\xampp\php\bin
[10:02:13 AM] [General] [Info]         C:\ProgramData\ComposerSetup\bin
[10:02:13 AM] [General] [Info]         C:\WINDOWS\System32\OpenSSH\
[10:02:13 AM] [General] [Info]         C:\WINDOWS\System32\OpenSSH\bin
[10:02:13 AM] [General] [Info]         C:\Users\user\AppData\Local\Programs\Microsoft VS Code\bin
[10:02:13 AM] [General] [Info]         C:\flutter\flutter\bin
[10:02:13 AM] [General] [Info]         C:\Users\user\AppData\Roaming\Composer\vendor\bin
[10:02:13 AM] [General] [Info]         C:\Users\user\AppData\Local\Microsoft\WindowsApps
[10:02:13 AM] [General] [Info]         C:\Users\user\AppData\Local\Microsoft\WindowsApps\bin
[10:02:13 AM] [General] [Info]         C:\Program Files\Android\Android Studio\jre\bin
[10:02:13 AM] [General] [Info]         C:\Users\user\AppData\Roaming\Dashlane\6.1940.1.24013\bin\Firefox_Extension\{442718d9-475e-452a-b3e1-fb1ee16b8e9f}\components
[10:02:13 AM] [General] [Info]         C:\Users\user\AppData\Roaming\Dashlane\6.1940.1.24013\bin\Firefox_Extension\{442718d9-475e-452a-b3e1-fb1ee16b8e9f}\components\bin
[10:02:13 AM] [General] [Info]         C:\Users\user\AppData\Roaming\Dashlane\6.1940.1.24013\ucrt
[10:02:13 AM] [General] [Info]         C:\Users\user\AppData\Roaming\Dashlane\6.1940.1.24013\ucrt\bin
[10:02:13 AM] [General] [Info]         C:\Users\user\AppData\Roaming\Dashlane\6.1940.1.24013\bin\Qt
[10:02:13 AM] [General] [Info]         C:\Users\user\AppData\Roaming\Dashlane\6.1940.1.24013\bin\Qt\bin
[10:02:13 AM] [General] [Info]         C:\Users\user\AppData\Roaming\Dashlane\6.1940.1.24013\bin\Ssl
[10:02:13 AM] [General] [Info]         C:\Users\user\AppData\Roaming\Dashlane\6.1940.1.24013\bin\Ssl\bin
[10:02:13 AM] [General] [Info]         C:\Users\user\AppData\Local\Android\Sdk
[10:02:13 AM] [General] [Info]         C:\Users\user\AppData\Local\Android\Sdk\bin
[10:02:13 AM] [General] [Info]     Found at:
[10:02:13 AM] [General] [Info]         C:\flutter\flutter\bin\
[10:02:13 AM] [General] [Info]         C:\flutter\flutter\bin
[10:02:13 AM] [General] [Info]     Candidate paths to be post-filtered:
[10:02:13 AM] [General] [Info]         C:\flutter\flutter
[10:02:13 AM] [General] [Info]         C:\flutter\flutter
[10:02:13 AM] [General] [Info]     Found at C:\flutter\flutter
[10:02:13 AM] [General] [Info]     Returning SDK path C:\flutter\flutter for flutter.bat
[10:02:13 AM] [General] [Info] Searching for dart.exe
[10:02:13 AM] [General] [Info]     Looking for dart.exe in:
[10:02:13 AM] [General] [Info]         C:\flutter\flutter\bin\cache\dart-sdk
[10:02:13 AM] [General] [Info]         C:\flutter\flutter\bin\cache\dart-sdk\bin
[10:02:13 AM] [General] [Info]         C:\WINDOWS\system32
[10:02:13 AM] [General] [Info]         C:\WINDOWS\system32\bin
[10:02:13 AM] [General] [Info]         C:\WINDOWS
[10:02:13 AM] [General] [Info]         C:\WINDOWS\bin
[10:02:13 AM] [General] [Info]         C:\WINDOWS\System32\Wbem
[10:02:13 AM] [General] [Info]         C:\WINDOWS\System32\Wbem\bin
[10:02:13 AM] [General] [Info]         C:\WINDOWS\System32\WindowsPowerShell\v1.0\
[10:02:13 AM] [General] [Info]         C:\WINDOWS\System32\WindowsPowerShell\v1.0\bin
[10:02:13 AM] [General] [Info]         C:\Program Files\Git\cmd
[10:02:13 AM] [General] [Info]         C:\Program Files\Git\cmd\bin
[10:02:13 AM] [General] [Info]         C:\Program Files\PowerShell\6\
[10:02:13 AM] [General] [Info]         C:\Program Files\PowerShell\6\bin
[10:02:13 AM] [General] [Info]         C:\Program Files\Dart\dart-sdk\bin
[10:02:13 AM] [General] [Info]         C:\xampp\php
[10:02:13 AM] [General] [Info]         C:\xampp\php\bin
[10:02:13 AM] [General] [Info]         C:\ProgramData\ComposerSetup\bin
[10:02:13 AM] [General] [Info]         C:\WINDOWS\System32\OpenSSH\
[10:02:13 AM] [General] [Info]         C:\WINDOWS\System32\OpenSSH\bin
[10:02:13 AM] [General] [Info]         C:\Users\user\AppData\Local\Programs\Microsoft VS Code\bin
[10:02:13 AM] [General] [Info]         C:\flutter\flutter\bin
[10:02:13 AM] [General] [Info]         C:\Users\user\AppData\Roaming\Composer\vendor\bin
[10:02:13 AM] [General] [Info]         C:\Users\user\AppData\Local\Microsoft\WindowsApps
[10:02:13 AM] [General] [Info]         C:\Users\user\AppData\Local\Microsoft\WindowsApps\bin
[10:02:13 AM] [General] [Info]         C:\Program Files\Android\Android Studio\jre\bin
[10:02:13 AM] [General] [Info]         C:\Users\user\AppData\Roaming\Dashlane\6.1940.1.24013\bin\Firefox_Extension\{442718d9-475e-452a-b3e1-fb1ee16b8e9f}\components
[10:02:13 AM] [General] [Info]         C:\Users\user\AppData\Roaming\Dashlane\6.1940.1.24013\bin\Firefox_Extension\{442718d9-475e-452a-b3e1-fb1ee16b8e9f}\components\bin
[10:02:13 AM] [General] [Info]         C:\Users\user\AppData\Roaming\Dashlane\6.1940.1.24013\ucrt
[10:02:13 AM] [General] [Info]         C:\Users\user\AppData\Roaming\Dashlane\6.1940.1.24013\ucrt\bin
[10:02:13 AM] [General] [Info]         C:\Users\user\AppData\Roaming\Dashlane\6.1940.1.24013\bin\Qt
[10:02:13 AM] [General] [Info]         C:\Users\user\AppData\Roaming\Dashlane\6.1940.1.24013\bin\Qt\bin
[10:02:13 AM] [General] [Info]         C:\Users\user\AppData\Roaming\Dashlane\6.1940.1.24013\bin\Ssl
[10:02:13 AM] [General] [Info]         C:\Users\user\AppData\Roaming\Dashlane\6.1940.1.24013\bin\Ssl\bin
[10:02:13 AM] [General] [Info]         C:\Users\user\AppData\Local\Android\Sdk
[10:02:13 AM] [General] [Info]         C:\Users\user\AppData\Local\Android\Sdk\bin
[10:02:13 AM] [General] [Info]         C:\flutter\flutter\bin\cache\dart-sdk
[10:02:13 AM] [General] [Info]         C:\flutter\flutter\bin\cache\dart-sdk\bin
[10:02:13 AM] [General] [Info]     Found at:
[10:02:13 AM] [General] [Info]         C:\flutter\flutter\bin\cache\dart-sdk\bin
[10:02:13 AM] [General] [Info]         C:\Program Files\Dart\dart-sdk\bin
[10:02:13 AM] [General] [Info]         C:\flutter\flutter\bin\cache\dart-sdk\bin
[10:02:13 AM] [General] [Info]     Candidate paths to be post-filtered:
[10:02:13 AM] [General] [Info]         C:\flutter\flutter\bin\cache\dart-sdk
[10:02:13 AM] [General] [Info]         C:\Program Files\Dart\dart-sdk
[10:02:13 AM] [General] [Info]         C:\flutter\flutter\bin\cache\dart-sdk
[10:02:13 AM] [General] [Info]     Found at C:\flutter\flutter\bin\cache\dart-sdk
[10:02:13 AM] [General] [Info]     Returning SDK path C:\flutter\flutter\bin\cache\dart-sdk for dart.exe
[10:02:13 AM] [General] [Info] Activating Flutter extension for Flutter project...
[10:02:13 AM] [General] [Info] Extension:Startup timing: 81ms
[10:02:14 AM] [General] [Info] Analyzer:Startup timing: 739ms
[10:02:19 AM] [General] [Info] Analyzer:FirstAnalysis timing: 3650ms
[10:02:20 AM] [General] [Info] Checking 1 projects for supported platforms
[10:02:20 AM] [General] [Info] Supported platforms for the workspace are ios, android
[10:03:13 AM] [General] [Info] Starting debug session...
[10:03:13 AM] [General] [Info]     workspace: C:\Project Flutter\Udemy\great_place_app
[10:03:13 AM] [General] [Info] Using found common entry point: C:\Project Flutter\Udemy\great_place_app\lib\main.dart
[10:03:13 AM] [General] [Info] Using workspace as cwd: C:\Project Flutter\Udemy\great_place_app
[10:03:13 AM] [General] [Info] Detected launch project as Flutter
[10:03:13 AM] [General] [Info] Using Flutter debug adapter for this session
[10:03:13 AM] [General] [Info] Checking for errors before launching
[10:03:13 AM] [General] [Info] Spawning a new flutter debugger
[10:03:13 AM] [General] [Info] Debug session starting...
    {
        "program": "C:\\Project Flutter\\Udemy\\great_place_app\\lib\\main.dart",
        "cwd": "C:\\Project Flutter\\Udemy\\great_place_app",
        "name": "Dart & Flutter",
        "type": "dart",
        "request": "launch",
        "args": [],
        "vmAdditionalArgs": [],
        "vmServicePort": 0,
        "dartPath": "C:\\flutter\\flutter\\bin\\cache\\dart-sdk\\bin\\dart.exe",
        "maxLogLineLength": 2000,
        "pubPath": "C:\\flutter\\flutter\\bin\\cache\\dart-sdk\\bin\\pub.bat",
        "pubSnapshotPath": "C:\\flutter\\flutter\\bin\\cache\\dart-sdk\\bin\\snapshots\\pub.dart.snapshot",
        "debugSdkLibraries": false,
        "debugExternalLibraries": true,
        "showDartDeveloperLogs": true,
        "useFlutterStructuredErrors": true,
        "debuggerHandlesPathsEverywhereForBreakpoints": true,
        "evaluateGettersInDebugViews": true,
        "previewDebuggerStepBack": false,
        "forceFlutterVerboseMode": false,
        "flutterTrackWidgetCreation": true,
        "flutterMode": "debug",
        "flutterPlatform": "default",
        "flutterPath": "C:\\flutter\\flutter\\bin\\flutter.bat",
        "deviceId": "1a96d23a9904",
        "deviceName": "Redmi Note 4 (android-arm64)",
        "showMemoryUsage": false,
        "debugServer": 56606,
        "debuggerType": 2
    }
[10:03:13 AM] [General] [Warn] Did not find session 266e14fa-fa72-45e2-acbe-bc1a86731997 to handle dart.launching. There were 0 sessions:
[10:03:13 AM] [General] [Warn] Event will be queued and processed when the session start event fires
[10:03:13 AM] [General] [Info] Processing delayed event dart.launching for session 266e14fa-fa72-45e2-acbe-bc1a86731997
[10:03:37 AM] [FlutterRun] [Error] [Dart & Flutter] Note: Some input files use unchecked or unsafe operations.
[10:03:37 AM] [FlutterRun] [Error] [Dart & Flutter] 
Note: Recompile with -Xlint:unchecked for details.
[10:03:38 AM] [FlutterRun] [Error] [Dart & Flutter] Note: C:\flutter\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider-1.4.5\android\src\main\java\io\flutter\plugins\pathprovider\PathProviderPlugin.java uses or overrides a deprecated API.
[10:03:38 AM] [FlutterRun] [Error] [Dart & Flutter] 
Note: Recompile with -Xlint:deprecation for details.
[10:04:38 AM] [General] [Info] Debugger:SessionDuration timing: 85009ms (Flutter)
[10:05:46 AM] [General] [Info] Starting debug session...
[10:05:46 AM] [General] [Info]     workspace: C:\Project Flutter\Udemy\great_place_app
[10:05:46 AM] [General] [Info] Using found common entry point: C:\Project Flutter\Udemy\great_place_app\lib\main.dart
[10:05:46 AM] [General] [Info] Using workspace as cwd: C:\Project Flutter\Udemy\great_place_app
[10:05:46 AM] [General] [Info] Detected launch project as Flutter
[10:05:46 AM] [General] [Info] Using Flutter debug adapter for this session
[10:05:46 AM] [General] [Info] Checking for errors before launching
[10:05:46 AM] [General] [Info] Debug session starting...
    {
        "program": "C:\\Project Flutter\\Udemy\\great_place_app\\lib\\main.dart",
        "cwd": "C:\\Project Flutter\\Udemy\\great_place_app",
        "name": "Dart & Flutter",
        "type": "dart",
        "request": "launch",
        "args": [],
        "vmAdditionalArgs": [],
        "vmServicePort": 0,
        "dartPath": "C:\\flutter\\flutter\\bin\\cache\\dart-sdk\\bin\\dart.exe",
        "maxLogLineLength": 2000,
        "pubPath": "C:\\flutter\\flutter\\bin\\cache\\dart-sdk\\bin\\pub.bat",
        "pubSnapshotPath": "C:\\flutter\\flutter\\bin\\cache\\dart-sdk\\bin\\snapshots\\pub.dart.snapshot",
        "debugSdkLibraries": false,
        "debugExternalLibraries": true,
        "showDartDeveloperLogs": true,
        "useFlutterStructuredErrors": true,
        "debuggerHandlesPathsEverywhereForBreakpoints": true,
        "evaluateGettersInDebugViews": true,
        "previewDebuggerStepBack": false,
        "forceFlutterVerboseMode": false,
        "flutterTrackWidgetCreation": true,
        "flutterMode": "debug",
        "flutterPlatform": "default",
        "flutterPath": "C:\\flutter\\flutter\\bin\\flutter.bat",
        "deviceId": "1a96d23a9904",
        "deviceName": "Redmi Note 4 (android-arm64)",
        "showMemoryUsage": false,
        "debugServer": 56606,
        "debuggerType": 2
    }
[10:05:46 AM] [General] [Warn] Did not find session bd605cf1-0b4b-4b1f-be85-a802dd590b6d to handle dart.launching. There were 0 sessions:
[10:05:46 AM] [General] [Warn] Event will be queued and processed when the session start event fires
[10:05:46 AM] [General] [Info] Processing delayed event dart.launching for session bd605cf1-0b4b-4b1f-be85-a802dd590b6d
[10:07:01 AM] [General] [Error] Cannot call write after a stream was destroyed
Error [ERR_STREAM_DESTROYED] [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
    at doWrite (_stream_writable.js:413:19)
    at writeOrBuffer (_stream_writable.js:401:5)
    at Socket.Writable.write (_stream_writable.js:301:11)
    at m.sendMessage (c:\Users\user\.vscode\extensions\dart-code.dart-code-3.7.1\out\dist\extension.js:1:45494)
    at m.sendMessage (c:\Users\user\.vscode\extensions\dart-code.dart-code-3.7.1\out\dist\extension.js:1:39135)
    at c:\Users\user\.vscode\extensions\dart-code.dart-code-3.7.1\out\dist\extension.js:1:45302
    at new Promise (<anonymous>)
    at m.sendRequest (c:\Users\user\.vscode\extensions\dart-code.dart-code-3.7.1\out\dist\extension.js:1:45114)
    at m.analysisSetPriorityFiles (c:\Users\user\.vscode\extensions\dart-code.dart-code-3.7.1\out\dist\extension.js:1:288866)
    at f.<anonymous> (c:\Users\user\.vscode\extensions\dart-code.dart-code-3.7.1\out\dist\extension.js:1:33822)
    at Generator.next (<anonymous>)
    at c:\Users\user\.vscode\extensions\dart-code.dart-code-3.7.1\out\dist\extension.js:1:32615
    at new Promise (<anonymous>)
    at r (c:\Users\user\.vscode\extensions\dart-code.dart-code-3.7.1\out\dist\extension.js:1:32360)
    at f.updatePriorityFiles (c:\Users\user\.vscode\extensions\dart-code.dart-code-3.7.1\out\dist\extension.js:1:33654)
    at c:\Users\user\.vscode\extensions\dart-code.dart-code-3.7.1\out\dist\extension.js:1:33188
    at l.fire (c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:47:207)
    at c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:625:348
    at l.fire (c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:47:207)
    at p.$acceptDocumentsAndEditorsDelta (c:\Users\u…

```

**Comment by DanTup** [comment] 2019-12-12 07:28
Could you try enabling the [analysis server log file](https://dartcode.org/docs/logging/#analyzer) and then reproduce the issue? It should capture more information about what's happening with the analysis server. Thanks!

**Comment by zgramming** [comment] 2019-12-12 07:56
@DanTup My problem is resolved after re-upgrade the flutter using `flutter upgrade --force`
and anyway how to enable [analysis server log ?](https://dartcode.org/docs/logging/#analyzer), because if the future this problem appear again, it's will be easy to reproduce the issue.
<img src="https://i.stack.imgur.com/DPDzh.png" height="400">

**Comment by m0nac0** [comment] 2019-12-12 08:59
I saw the same error today in VS Code after upgrading flutter to 1.12.13+hotfix.5 (stable) yesterday: The Dart Analyzer would continuously crash with the error message `Error [ERR_STREAM_DESTROYED] [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed` in the logs.

I resolved the problem by doing `flutter upgrade --force`

**Comment by DanTup** [comment] 2019-12-12 10:27
Instructions for enabling the log are [on this page](https://dartcode.org/docs/logging/#analyzer). `dart.analyzerLogFile` is a VS Code setting which you can type into the VS Code Settings json file, or use the VS Code Settings UI and search for "analyzer log file".

It sounds like the original Flutter upgrade may have not worked correctly (maybe there were files locked by the IDE during the upgrade?). If you do see it again, please let me know and we can do some more digging. In the meantime I'll close this since the issue seems resolved. Thanks!

**Closed by DanTup** 2019-12-12 10:27 UTC
Labels: awaiting info
