### ISSUE TITLE
Dart-code extension causes high HDD activity on Windows 10

### ISSUE THREAD

**Issue by andyduke** [Dart-Code/Dart-Code#3893] opened 2022-03-30 16:40 UTC
Dart-code extension causes high HDD activity on Windows 10.
![image](https://user-images.githubusercontent.com/52318/160885488-b6093fde-fec0-4a81-b712-0a2171c58fd2.png)

This is likely affected by Analysis Server, as when it is restarted, activity drops for a short time.
![image](https://user-images.githubusercontent.com/52318/160885916-5a8a9a3b-9ffa-4461-8391-213f9b36869a.png)

**Versions (please complete the following information):**
 - VS Code version: 1.65.2
 - Dart extension version: 3.36
 - Dart/Flutter SDK version: 2.16.2/2.10.4

**Flutter doctor:**
```
[√] Flutter (Channel stable, 2.10.4, on Microsoft Windows [Version 10.0.17134.1], locale ru-RU)
    • Flutter version 2.10.4 at D:\Flutter2Live\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c860cba910 (5 days ago), 2022-03-25 00:23:12 -0500
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at D:\Flutter2Live\android-sdk
    • Platform android-31, build-tools 29.0.2
    • ANDROID_HOME = D:\Flutter2Live\android-sdk
    • ANDROID_SDK_ROOT = D:\Flutter2Live\android-sdk
    • Java binary at: D:\Flutter2Live\jdk\bin\java
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_261-b12)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • CHROME_EXECUTABLE = D:\Chromiums\89\chrome.exe

[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[√] Connected device (2 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.17134.1]
    • Chrome (web)      • chrome  • web-javascript • unknown
    ! Device emulator-5554 is offline.

[√] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 2 categories.
```

**Comment by DanTup** [comment] 2022-03-30 16:46
@andyduke does this happen if you open a newly created Flutter project, or only a specific project?

Could you run `code --status` and post the full output while VS Code is open after this has occurred?

**Comment by andyduke** [comment] 2022-03-30 16:53
> @andyduke does this happen if you open a newly created Flutter project, or only a specific project?

This happens when opening any existing flutter or dart project.

---

> Could you run `code --status` and post the full output while VS Code is open after this has occurred?
```
Warning: 'disable-gpu-compositing' is not in the list of known options, but still passed to Electron/Chromium.

Version:          Code 1.65.2 (c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1, 2022-03-10T14:33:55.248Z)
OS Version:       Windows_NT x64 10.0.17134
CPUs:             Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz (8 x 2304)
Memory (System):  31.87GB (21.04GB free)
VM:               0%
Screen Reader:    no
Process Argv:     --disable-gpu --disable-gpu-compositing
GPU Status:       2d_canvas:                  unavailable_software
                  gpu_compositing:            disabled_software
                  multiple_raster_threads:    enabled_on
                  oop_rasterization:          disabled_off
                  opengl:                     disabled_off
                  rasterization:              disabled_software
                  skia_renderer:              enabled_on
                  video_decode:               disabled_software
                  vulkan:                     disabled_off
                  webgl:                      unavailable_software
                  webgl2:                     unavailable_software

CPU %   Mem MB     PID  Process
    0       90   11968  code main
    0       65    9248     shared-process
    0       34    9060       fileWatcher
    0       43   18548       ptyHost
    0        6   19948         winpty-process
    0        9   10492           console-window-host (Windows internal process)
    0       64   17712           C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
    0       22   13876     utility-network-service
    0      176   15912     window (styles.dart - markdown_ansi_renderer - VSCode тАв Flutter 2.0 Live)
    0       66   20008     extensionHost
    0        3   20228       C:\Windows\system32\cmd.exe /d /s /c ""D:\Flutter2Live\flutter\bin\cache\dart-sdk\bin\dart.exe" "language-server" "--client-id=VS-Code" "--client-version=3.36.0""
    0       11    8592         console-window-host (Windows internal process)
    0      412   22400         "D:\Flutter2Live\flutter\bin\cache\dart-sdk\bin\dart.exe"  "language-server" "--client-id=VS-Code" "--client-version=3.36.0"
    0      129   21288     gpu-process

Workspace Stats:
|  Window (styles.dart - markdown_ansi_renderer - VSCode тАв Flutter 2.0 Live)
|    Folder (markdown_ansi_renderer): 43 files
|      File types: dart(13) md(3) gitignore(2) json(2) yaml(2) dill(1)
|                  Ly9AZGFydD0yLjE1(1) packages(1) bak(1) lock(1)
|      Conf files: launch.json(1)
|      Launch Configs: dart(2)
```

**Comment by DanTup** [comment] 2022-03-30 17:13
@andyduke thanks! Does this remain high indefinitely, or just while "Analyzing" is shown in the status bar?

I haven't used Windows for some time so I'm not very familiar with these metrics - what's the difference between the blue/green on the chart, and what timeframe is this?

Is there any additional info on the Disk tab in Resource Monitor?

And out of interest, what sort of disk is this?

**Comment by andyduke** [comment] 2022-03-30 17:34
> @andyduke thanks! Does this remain high indefinitely, or just while "Analyzing" is shown in the status bar?

High activity persists all the time, even when the "Analyzing" message disappears from the status bar.

> I haven't used Windows for some time so I'm not very familiar with these metrics - what's the difference between the blue/green on the chart, and what timeframe is this?

The green graph is just disk activity and the blue graph is high activity.

> Is there any additional info on the Disk tab in Resource Monitor?

There is no additional information.

> And out of interest, what sort of disk is this?

It's a hard drive, not an SSD, which is why I hear the sound of the drive when using VSCode with Dart-Code.

**Comment by andyduke** [comment] 2022-04-01 15:22
@DanTup I found active writing to such files. Could this be the reason?
![image](https://user-images.githubusercontent.com/52318/161293543-742cb42d-8937-4dc7-bdd8-b5714ec4f0ba.png)

**Comment by DanTup** [comment] 2022-04-01 16:34
@andyduke it's normal for these files to be written during analysis and as you modify files. Once all libraries have been analyzed and data cached (including the SDK and all of your packages), it should stop (and for subsequent sessions, they should be reused).

If you're seeing this on a new project, could you try enabling the [analysis instrumentation log](https://dartcode.org/docs/logging/#analyzer-instrumentation), open a new Flutter project and leave it until "Analyzing..." has disappeared from the status bar, and then see whether anything is being written to the file while the disk access remains high? (note: interacting with the project in VS Code will cause more to be written, but I'm interested in whether it's writing anything while you're _not_ interacting with it).

**Comment by andyduke** [comment] 2022-04-01 16:37
> @andyduke it's normal for these files to be written during analysis and as you modify files. Once all libraries have been analyzed and data cached (including the SDK and all of your packages), it should stop (and for subsequent sessions, they should be reused).

Is it normal to write to these files when there is no analysis and I am not writing code in VSCode (window in the background)?

**Comment by DanTup** [comment] 2022-04-01 16:49
> Is it normal to write to these files when there is no analysis and I am not writing code in VSCode (window in the background)?

Generally, no - once analysis of all the existing files (including SDK and Pub packages your project references) have been analyzed.

**Comment by andyduke** [comment] 2022-04-01 17:14
> If you're seeing this on a new project, could you try enabling the [analysis instrumentation log](https://dartcode.org/docs/logging/#analyzer-instrumentation), open a new Flutter project and leave it until "Analyzing..." has disappeared from the status bar, and then see whether anything is being written to the file while the disk access remains high? (note: interacting with the project in VS Code will cause more to be written, but I'm interested in whether it's writing anything while you're _not_ interacting with it).

I found that the ".analysis-driver" folder is ~1Gb in size. After deleting it (it took some time), when launching VSCode and opening a new project, as well as my other projects, after the end of the analysis, the disk activity returns to normal.

**Comment by DanTup** [comment] 2022-04-04 10:52
> I found that the ".analysis-driver" folder is ~1Gb in size. After deleting it (it took some time), when launching VSCode and opening a new project, as well as my other projects, after the end of the analysis, the disk activity returns to normal.

@scheglov have you seen any other reports of this? I think this could be the background task that prunes this cache. This is a mechanical drive and I wonder if either the `Directory(cachePath).listSync(recursive: true)` or subsequently calling `statSync()` on each item is taking a long time here.

I wonder if there's value in only doing a subset of this work each time (for example just looking at one sub-folder at a time and scheduling them over some period?)

**Comment by scheglov** [comment] 2022-04-04 21:35
We had a few reports some time ago, also on Windows. Then it seemed that one giant directory with analysis results was slow, so we decided to shard it by the first two characters of the key (which is md5 based, and we expect bits to be distributed uniformly). Since then there were no more complains.

Indeed, we to recursive listing and stat every file. We could do changes that you suggested - list non-recursively, and stat with pauses. But I would be hesitant to do so based on a single report.

**Comment by DanTup** [comment] 2022-04-05 08:22
Sounds reasonable to me.

@andyduke if this comes up again, rather than just deleting the folder, if you rename it instead (to keep a copy), it might be interesting to run the code that the server runs when trying to clean the folder up in a simple standalone Dart script with some timings, to see how long each the operations is taking. Even if this may be specific to your machine/disk, it could be useful to have some numbers/data for future comparison.

I'll close this in the meantime as it seems the immediate issue is resolved and there's nothing actionable, but please let me know if it comes back and I can provide you a test script to capture some timings.

**Closed** 2022-04-05 08:23 UTC
Labels: is bug, awaiting info

**Comment by andyduke** [comment] 2022-04-13 12:27
@DanTup It came up again, I saved the ".analysis-driver" folder. What can I do to help understand what's going on?

**Comment by DanTup** [comment] 2022-05-27 16:38
@andyduke thanks, that's useful information.

It seems to be taking around 30 seconds to list the files and another 30 to collect the sizes/timestamps. In the case above, the total size was below the max so it didn't need to delete anything.

Out of interest, do you know much about the specs/type/age of drive? 30-60 seconds seems like a long time, though I don't have a mechanical drive here I could test with to see whether that's typical.

**Comment by andyduke** [comment] 2022-05-27 17:54
> Out of interest, do you know much about the specs/type/age of drive? 30-60 seconds seems like a long time, though I don't have a mechanical drive here I could test with to see whether that's typical.
Western Digital Blue 2 Тб WD20SPZX SATA, аge about 4 years.

**Comment by DanTup** [comment] 2022-05-30 12:43
@andyduke interesting - how many files were in the root of the `.analysis-driver` folder when you see the issue? I just checked mine and there's only a single file (`fbff5e4c2680eff8309f4a22cef5beea.resolved-temp-3660`), but maybe if there are a huge number it could be the issue that @scheglov noted above (which the sharding into folders is intended to fix, but maybe isn't covering all files?).

**Comment by andyduke** [comment] 2022-05-30 12:48
> @andyduke interesting - how many files were in the root of the `.analysis-driver` folder when you see the issue? I just checked mine and there's only a single file (`fbff5e4c2680eff8309f4a22cef5beea.resolved-temp-3660`), but maybe if there are a huge number it could be the issue that @scheglov noted above (which the sharding into folders is intended to fix, but maybe isn't covering all files?).

There are not many files in the `.analysis-driver` folder root: 20-75.

**Comment by DanTup** [comment] 2022-05-30 13:08
In that case, perhaps the files in the root are not the cause and it was just coincidence (or, whatever left them there also did something that triggers this).

@scheglov do you think it's worth trying to makes any changes here? Without a mechanical drive to test with, I have no idea whether this is typical or there's something specific on this setup that's causing this performance.
