### ISSUE TITLE
Underscore added after code completion

### ISSUE THREAD

**Issue by sethladd** [Dart-Code/Dart-Code#234] opened 2016-12-14 21:38 UTC
Notice the _ that was added after the plugin code completed Column():

![screen shot 2016-12-14 at 1 37 56 pm](https://cloud.githubusercontent.com/assets/5479/21202172/a23ea5ea-c202-11e6-9b52-25281a3ff83c.png)

**Comment by DanTup** [comment] 2016-12-14 23:05
Wow, that's weird. I haven't seen this before - does it happen to you in a small sample?

I presume you're on the latest stable version of Code? What SDK version is it? If you enable logging from the analyzer (`dart.analyzerLogFile` in your user settings - set it to a full path for a log file) can you check what was in the completion response? (I think we might truncate this which will probably make it useless).

**Comment by mikemimik** [comment] 2016-12-15 08:45
I didn't see this issue happen until I updated Code to version 1.8.0.

The completion response has an underscore in it.
```
[3:42:26 AM]: ==> {"id":"21","method":"analysis.updateContent","params":{"files":{"/Users/orion/Repos/flutter-projects/flutter_examples/form_example/lib/main.dart":{"type":"change","edits":[{"offset":2102,"length":4,"replacement":"Column()_","id":""}]}}}}
```

**Comment by DanTup** [comment] 2016-12-15 09:03
Ah, I didn't realise 1.8 was out yet. In that case it's probably related to #216. We currently use an internal API for completion that's being removed, though it was supposed to keep working for 2-3 versions :(

I'll take a look tonight/tomorrow. For now, disabling the `dart.insertArgumentPlaceholders` setting might fix it (though you might want to remember to switch back if you want that once I push a fix).

**Comment by mikemimik** [comment] 2016-12-15 09:05
Yeah I just found [this line of code](https://github.com/Dart-Code/Dart-Code/blob/ecf617fe3add90e097cf4ab49a99aaf604a96ec6/src/providers/dart_completion_item_provider.ts#L61) and [this other line of code](https://github.com/Dart-Code/Dart-Code/blob/ecf617fe3add90e097cf4ab49a99aaf604a96ec6/src/providers/dart_completion_item_provider.ts#L64), which seam to suggest that it's a vscode problem. It's not dealing with placeholders correctly.

**Comment by DanTup** [comment] 2016-12-15 09:07
Yeah, there's a new API for placeholders I need to migrate to (#216), but I didn't want to do it until 1.8 shipped and was led to believe the old syntax would continue working the same for a few versions :(

**Comment by mikemimik** [comment] 2016-12-15 09:11
Just caught up on all the info; https://github.com/Dart-Code/Dart-Code/issues/216#issuecomment-264475964 was a bit misleading. Let me know if there is anything I can do to assist.

**Comment by DanTup** [comment] 2016-12-15 09:13
Oh, hangon - the underscore is on the analyzer response? In that case this might be a Code issue? I'll investigate tonight.

**Comment by DanTup** [comment] 2016-12-15 09:21
Let my try that again (removed my misleading comments!).

The underscore you posted is in the data *to* the analyzer, after the completion has been committed, it's not the response. A previous response would have the completions in it, but it's probably truncated so you can't see it in the logs (we should really add a switch to disable this).

I'll do some digging tonight. I suspect an accidental change in Code as part of the new API has caused this, but I'll get a fix out one way or another in the next few days.

For now, disabling the dart.insertArgumentPlaceholders setting might fix it (though you might want to remember to switch back if you want that once I push a fix).

**Comment by DanTup** [comment] 2016-12-15 17:17
I think the issue is that the internal API used underscore as the final cursor position (see https://github.com/Microsoft/vscode/issues/6874#issuecomment-235606255) but in 1.8 it renders a real underscore.

**Comment by DanTup** [comment] 2016-12-15 18:00
@sethladd @mikemimik Please upgrade to v0.14.7 and let me know if this solves you're issue. I've completed #216 and made some tweaks to completion. If anything doesn't seem right (placeholders, cursor positions, tab order, etc.) please let me know and I'll try to fix as quickly as I can.

Note: Fixing this required marking the extension to use Code 1.8 (so I can use the new, not-broken API). This means on any machine you have Code on, you'll need to upgrade Code to 1.8 and then upgrade Dart Code.

**Closed by DanTup** 2016-12-15 18:00 UTC
Labels: bug

**Comment by mikemimik** [comment] 2016-12-15 18:59
0.14.7 seems to have solved everything. I'll let you know if anything wonky happens.

**Comment by DanTup** [comment] 2016-12-15 20:33
Excellent; thanks for confirming!

**Comment by sethladd** [comment] 2016-12-15 22:40
Thanks!
