### ISSUE TITLE
[flutter] super parameter + private widget triggers a warning

### ISSUE THREAD

**Issue by woprandi** [Dart-Code/Dart-Code#4680] opened 2023-08-09 09:02 UTC
**Describe the bug**
When we use the super parameter constructor  and a private widget name  we get a warning 

> 
>  A value for optional parameter 'key' isn't ever given.
> Try removing the unused parameter.

**To Reproduce**
1. Create stateless widget with private name (prefix `_`)
2. Enable super parameter (`use_super_parameters: true` in `analysis_options.yml`)

> 

**Expected behavior**
No warning

**Screenshots**
![image](https://github.com/Dart-Code/Dart-Code/assets/1449422/be791c5c-2a8f-4549-b928-58c7b6cfea89)

**Please complete the following information:**
 - Operating System and version: Fedora 38
 - VS Code version: 1.81.0
 - Dart extension version: v3.70.0
 - Dart/Flutter SDK version: 3.0.6 / 3.10.6

**Comment by DanTup** [comment] 2023-08-09 11:02
I think this is working is expected. Because the widget is private you're not passing `key` anywhere, the parameter is unnecessary and can be removed. The parameter is included when you create the widget because at that time it's unknown whether you will use it or not.

However, I'm not sure whether it's considered good practice to leave the key there (for potential future use), as that's probably what you'd do with a public widget even if you weren't using it at the time. It could be odd to treat this specially though.

@bwilkerson @jacob314 any thoughts about this?

**Comment by bwilkerson** [comment] 2023-08-09 14:54
Not surprisingly, this has been discussed in the sdk issue tracker, and there isn't any clear consensus. See https://github.com/dart-lang/sdk/issues/49025.

**Comment by DanTup** [comment] 2023-08-09 15:08
Ah, I should've searched for that (and think I saw related breakage). Closing this as a dupe of https://github.com/dart-lang/sdk/issues/49025 then, thanks!

**Closed by DanTup** 2023-08-09 15:08 UTC
Labels: is bug
