### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by demasu** [Dart-Code/Dart-Code#1813] opened 2019-06-21 20:02 UTC
- Issue Type: `Performance`
- Extension Name: `dart-code`
- Extension Version: `3.1.0`
- OS Version: `Darwin x64 18.6.0`
- VSCode version: `1.35.1`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load
[Dart-Code.dart-code-unresponsive.cpuprofile.txt](https://github.com/Dart-Code/Dart-Code/files/3315832/Dart-Code.dart-code-unresponsive.cpuprofile.txt)

**Comment by DanTup** [comment] 2019-06-24 12:01
Thanks for the profile! This appears to have occurred at activation, so I think it's a duplicate of https://github.com/Dart-Code/Dart-Code/issues/1628, though it does also show that scanning the projects might be a little slow.

That are significant changes for both of these in the upcoming release. You can try it out early from here if you want:

https://github.com/Dart-Code/Dart-Code/releases

If you still have issues with that build (or the stable release - the plan is to release at the end of this week) then please let me know and we can look further.

**Closed** 2019-06-24 12:02 UTC
Labels: duplicate
