### ISSUE TITLE
When pressing CMD + click on a package name in the pubspec.yaml it would be nice to be redirected to the respective pub page. Similar to go to definition.

### ISSUE THREAD

**Issue by HerrNiklasRaab** [Dart-Code/Dart-Code#3730] opened 2021-12-14 11:07 UTC

**Comment by HerrNiklasRaab** [comment] 2021-12-14 11:07
It's a feature off course, pressed the wrong button :)

**Comment by DanTup** [comment] 2021-12-15 15:49
I don't think we can do this on Cmd+Click, as that invokes "Go to Definition", which only allows us to provide source files/locations to jump to.

There's an open issue at #2785 about providing something along these lines, although I don't think there's a great API in VS Code we could use. CodeLens is probably the closest, but it would insert gaps between every line would would be quite jarring.

Perhaps Hovers would be better - eg. a tooltip with some information about the package and a hyperlink in it?

**Comment by DanTup** [comment] 2021-12-15 15:50
I'll close this as a dupe of #2785, feel free to add any additional ideas there.

**Closed by DanTup** 2021-12-15 15:50 UTC
Labels: is bug
