### ISSUE TITLE
Flutter debugging support

### ISSUE THREAD

**Issue by Skylled** [Dart-Code/Dart-Code#292] opened 2017-05-13 16:01 UTC
This is the next logical step for Flutter support, and possibly the hardest.
Bare minimum to satisfy:
- [ ] F5 hotkey support
- [ ] Hot reload
- [ ] Refresh

Reload and refresh are impossible if you just wire up a command, because channels don't accept input (right?)

Additional possibilities (to mimic the Flutter IntelliJ plugin):
- [ ] Device selection?
- [ ] Breakpoints
- [ ] Observatory shortcut

**Comment by DanTup** [comment] 2017-05-13 16:17
I'm not familiar enough with Flutter to have any advice here yet :( If I can get some time next weekend, I'll see if I can get Hello World running on my device so I have a better idea of how it hangs together.

> Reload and refresh are impossible if you just wire up a command, because channels don't accept input (right?)

Not sure what you mean here.. If we can run something in the background then commands can interact with it (same way the analyzer runs in BG and we send commands to it). When you deploy/run on a device is there a process that continues running or are they just short-lived commands?

I don't expect basic debugging support will be hard since there's already support for debugging CLI apps (same for breakpoints).

**Comment by Skylled** [comment] 2017-05-15 21:49
You use `flutter run` from the CLI, and it builds the app for the device, starts it, and displays all the logs. The process does keep running.
A hot refresh is done by pressing `r` and refresh is done by `shift-r`.

I'll look into VS Code's debugger system soon.

If it's as simple as you say, I might be able to rig something basic up quickly.

**Comment by DanTup** [comment] 2017-05-19 20:46
This is a dupe of #198. I've had a quick play with this today, I'll add some notes on that case.

**Closed by DanTup** 2017-05-19 20:46 UTC

**Comment by DanTup** [comment] 2017-06-11 15:10
It's not finished yet; but most of the stuff mentioned here is now implemented on the `flutter` branch as part of #198. Things are are missing:

- `Refresh` - not sure how this differs from `hot reload`?
- `Observatory shortcut` - I'm not all that familiar with the Observatory web app - what value is there in using this directly as a user (over the debugger integration)?

**Comment by DanTup** [comment] 2017-06-11 15:13
If `Refresh` meant `Full restart`, I'm hoping to make Dart Code fall back to that automatically if a hot reload fails (see https://github.com/flutter/flutter/issues/10620). If you want to force it, you can hit Stop then re-launch. I don't know if this will work best in practice so I'll be interested in feedback after building a beta version (ofc if you're comfortable running from the source, you're welcome to try this out and provide feedback now - just beware that debug stepping is broken - once you hit a breakpoint the process seems to lock up!).
