### ISSUE TITLE
Dart Formatter error

### ISSUE THREAD

**Issue by juniorkibirige** [Dart-Code/Dart-Code#3861] opened 2022-03-04 22:38 UTC
On attempting to format a dart document it returns an error in the VS Code Output window specifically under "LSP".
It was working a few days ago but just instantaneously started acting up. 

Don't know how to repro this, since it was working fine and now it just keeps happening, even had to uninstall and reinstall the plugin in vscode.

```
DartFormatter.formatSource (package:dart_style/src/dart_formatter.dart:178:7)
#1      generateEditsForFormatting (package:analysis_server/src/lsp/source_edits.dart:94:33)
#2      FormattingHandler.formatFile (package:analysis_server/src/lsp/handlers/handler_formatting.dart:35:12)
#3      FormattingHandler.handle.<anonymous closure> (package:analysis_server/src/lsp/handlers/handler_formatting.dart:52:14)
#4      ErrorOr.mapResult (package:analysis_server/lsp_protocol/protocol_special.dart:249:12)
#5      FormattingHandler.handle (package:analysis_server/src/lsp/handlers/handler_formatting.dart:46:17)
#6      MessageHandler.handleMessage (package:analysis_server/src/lsp/handlers/handlers.dart:137:12)
#7      ServerStateMessageHandler.handleMessage (package:analysis_server/src/lsp/handlers/handlers.dart:171:36)
#8      LspAnalysisServer.handleMessage.<anonymous closure> (package:analysis_server/src/lsp/lsp_analysis_server.dart:341:47)
#9      LspAnalysisServer.handleMessage.<anonymous closure> (package:analysis_server/src/lsp/lsp_analysis_server.dart:336:21)
#10     _rootRun (dart:async/zone.dart:1426:13)
#11     _CustomZone.run (dart:async/zone.dart:1328:19)
#12     _runZoned (dart:async/zone.dart:1861:10)
#13     runZonedGuarded (dart:async/zone.dart:1849:12)
#14     LspByteStreamServerChannel._readMessage (package:analysis_server/src/lsp/channel/lsp_byte_stream_channel.dart:85:16)
#15     LspByteStreamServerChannel.listen.<anonymous closure> (package:analysis_server/src/lsp/channel/lsp_byte_stream_channel.dart:54:24)
#16     _rootRunUnary (dart:async/zone.dart:1434:47)
#17     _CustomZone.runUnary (dart:async/zone.dart:1335:19)
#18     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
#19     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
#20     _DelayedData.perform (dart:async/stream_impl.dart:591:14)
#21     _StreamImplEvents.handleNext (dart:async/stream_impl.dart:706:11)
#22     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:663:7)
#23     _rootRun (dart:async/zone.dart:1418:47)
#24     _CustomZone.run (dart:async/zone.dart:1328:19)
#25     _CustomZone.runGuarded (dart:async/zone.dart:1236:7)
#26     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1276:23)
#27     _rootRun (dart:async/zone.dart:1426:13)
#28     _CustomZone.run (dart:async/zone.dart:1328:19)
#29     _CustomZone.runGuarded (dart:async/zone.dart:1236:7)
#30     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1276:23)
#31     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
#32     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
#33     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:122:13)
#34     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:193:5)
```

**Versions (please complete the following information):**
 - VS Code version: 1.65.0
 - Dart extension version: 3.37.20220303
 - Dart/Flutter SDK version: 2.16.1/2.10.2

**Comment by DanTup** [comment] 2022-03-07 12:05
@juniorkibirige are you able to share the specific code that's triggering this? There's a similar issue at https://github.com/dart-lang/sdk/issues/47020 but I don't know if it's the same cause.

**Comment by juniorkibirige** [comment] 2022-03-07 12:22
> @juniorkibirige are you able to share the specific code that's triggering this? There's a similar issue at https://github.com/dart-lang/sdk/issues/47020 but I don't know if it's the same cause. 

Can't share specific code now but the problem in the issue is the same

**Comment by DanTup** [comment] 2022-03-07 12:50
In that case I'll close this as a dupe of that one as it'll need fixing in the Dart parser. Thanks!

**Closed by DanTup** 2022-03-07 12:50 UTC
Labels: is bug, awaiting info
