### ISSUE TITLE
Hanging flutter_tester processes

### ISSUE THREAD

**Issue by AlexandreAndrade00** [Dart-Code/Dart-Code#5165] opened 2024-07-02 14:03 UTC
**Describe the bug**
The flutter_tester processes aren't terminated.

**To Reproduce**
1. Run multiple tests with breakpoints
2. Exit in the middle of the execution

**Expected behavior**
The flutter_tester processes are terminated

**Screenshots**
![image](https://github.com/Dart-Code/Dart-Code/assets/46357905/83a3babd-8d02-46e8-b7e4-b714db737eee)

```text
Dart Code extension: 3.90.0
Flutter extension: 3.90.0 (activated)

App: Code - OSS
App Host: desktop
Version: linux 1.90.0

Workspace type: Flutter (LSP)

Dart (3.3.1): /home/alexandre/fvm/versions/3.19.3/bin/cache/dart-sdk
Flutter (3.19.3): /home/alexandre/fvm/versions/3.19.3 (Linux (linux-x64/linux))

```

**Comment by DanTup** [comment] 2024-07-03 10:50
I can reproduce this in a newly-created Flutter app. Clicking Stop on the debug toolbar sends `terminate`, which we use to shutdown and we get an Exited event, then send `terminated`. We then get `disconnect` but it appears the process is already gone by then.

```
[11:47:26 AM] [DAP] [Info] ==> {"command":"terminate","arguments":{"restart":false},"type":"request","seq":16}
[11:47:26 AM] [DAP] [Info] <== {"seq":2136,"type":"event","body":{"output":"\nExited (-1).\n"},"event":"output"}
[11:47:26 AM] [DAP] [Info] <== {"seq":2137,"type":"event","body":{},"event":"terminated"}
[11:47:26 AM] [DAP] [Info] <== {"seq":2138,"type":"response","command":"terminate","request_seq":16,"success":true}
[11:47:26 AM] [DAP] [Info] ==> {"command":"disconnect","arguments":{"restart":false},"type":"request","seq":17}
[11:47:26 AM] [DAP] [Info] <== {"seq":2139,"type":"response","command":"disconnect","request_seq":17,"success":true}
```

**Comment by DanTup** [comment] 2024-07-03 10:58
This seems to be a `flutter test` issue. I've opened https://github.com/flutter/flutter/issues/151230 with steps to reproduce without VS Code or the debug adapter for investigation.

**Comment by DanTup** [comment] 2024-11-26 12:20
https://github.com/flutter/flutter/issues/151230 / https://github.com/flutter/flutter/issues/144222 has been resolved in Flutter and I can no longer reproduce orphaned flutter_tester processes (although I do see a slightly different issue - see https://github.com/flutter/flutter/issues/144008#issuecomment-2500634254).

Closing this on the assumption that this specific issue is resolved (on Flutter master), but please shout if you can still reproduce (and provide steps) on a version that includes https://github.com/flutter/flutter/pull/159115.

**Closed by DanTup** 2024-11-26 12:20 UTC
Labels: is bug, blocked on dart / flutter, in flutter, in testing
