### ISSUE TITLE
VSCode command 'flutter.createProject' not found

### ISSUE THREAD

**Issue by shariarrazm** [Dart-Code/Dart-Code#1733] opened 2019-05-21 13:30 UTC
I installed Dart, flutter and PATH but when i want to create new flutter project from command palette i have this error "command 'flutter.createProject' not found" Even if i open a ready project the syntax is not working

**Comment by DanTup** [comment] 2019-05-21 13:32
Dupe of #1732.

**Closed by DanTup** 2019-05-21 13:32 UTC

**Comment by shariarrazm** [comment] 2019-05-21 13:39
<img width="1095" alt="Screenshot 2019-05-21 at 15 38 07" src="https://user-images.githubusercontent.com/15120130/58100722-7b1d8880-7bde-11e9-9b81-addf29c2ed5a.png">

**Comment by DanTup** [comment] 2019-05-21 13:40
Please post in https://github.com/Dart-Code/Dart-Code/issues/1732 to avoid confusion :)
