### ISSUE TITLE
Selective Auto completion for imported Libraries

### ISSUE THREAD

**Issue by tensor-programming** [Dart-Code/Dart-Code#1723] opened 2019-05-20 08:27 UTC
During a recent live stream, I noticed that I was having some performance issues (Opened a separate issue on this one).  Due to an unrelated issue, I downgraded my flutter channel from dev to stable.  After doing this, I noticed that any imported libraries were not receiving auto completion anymore.  I went back up to dev after a day or two and I am still not receiving proper auto-completion for these imported libraries.  Sometimes this even happens with Flutter libraries like Foundation and Cupertino.  

I find that if I've already imported the library via pubspec and imported it into the file; I can close out of the editor and it will give me the expected auto-completion.  

This is a bit of a strange issue in that it seems to be very selective.  For instance, when I was working with the Android Alarm Manager library, typing in the object `AndroidAlarmManager` did not give me auto-completion, however I was able to get auto completion for the attached methods/named constructors.  Even typing in the object name again did not yield auto-completion either which again was a bit strange.  On the other hand, a library like the http library didn't have this problem.  I can provide a log if needed; tomorrow, I plan to sit down and do some heavy coding.

**Comment by DanTup** [comment] 2019-05-20 08:33
If you can [capture a log](https://dartcode.org/docs/logging/#capture-logs-command) and some screenshots when this happens, that would be great. If you can capture a copy of your project folder in exactly the state you saw the issue, that might help too.

One thing to note, is that the lines in the log file are cut quite short by default, so might not include all completions. If you can repro this reliably at some point, it's worth setting the [dart.maxLogLineLength](https://dartcode.org/docs/settings/#dartmaxloglinelength) setting much higher (just remember to set it back after, since it will result in much larger log files and increased disk activity).

**Comment by tensor-programming** [comment] 2019-05-20 09:05
I can show you the issue in VOD from my livestream.  I marked a few timestamps here and took a some screen captures as well: [VOD link](https://youtu.be/950jZeaqbdU).

- [Photo 1:](https://ibb.co/j6TpvtK) As mentioned above regarding the object `AndroidAlarmManager`.  Timestamp for this is around [15:50](https://youtu.be/950jZeaqbdU?t=950) in the video. 
- [Photo 2:](https://ibb.co/kQnD1Kc) Typing same object again and no auto completion.  
- [Photo 3](https://ibb.co/zSJ20Jm)  Different object from a different import.  All of the objects that I typed from this library had this issue.  Timestamp for this is roughly [56:42](https://youtu.be/950jZeaqbdU?t=3402)
- [Photo 4](https://ibb.co/Fnvbn8S) Best example from the photos since it also shows the suggested auto completion for this object.  In the image you can see that the choices are not the object that I am typing. 
Time stamps for these pieces are [57:40](https://youtu.be/950jZeaqbdU?t=3460), [58:18](https://youtu.be/950jZeaqbdU?t=3498) and [59:05](https://youtu.be/950jZeaqbdU?t=3545).  I am sure there a plenty of other examples in the livestream but I don't feel like looking at this moment.  

When I sit down to make create the log tomorrow, I'll also record a small private video showcasing the issues to show you guys more examples. If I am able to catch the other issue as well I will be sure to include it in the video.    

Sorry to keep troubling you with these issues.

**Comment by DanTup** [comment] 2019-05-20 09:14
> Sorry to keep troubling you with these issues.

It's no trouble at all - I appreciate you taking the time to report them - if there are bugs I definitely want to track them down so keep the issues coming :-)

It definitely seems something isn't working as expected in some of these screenshots/clips. When you next see this, I'd be interesting to know if closing the completion (`esc`) and then forcing it back open (`ctrl`+`space`) changes things. If not, does saving the file, then doing the same fix it? If not, does restarting VS Code fix it?

If none of those things fix it, it might make it easier for me to reproduce locally (for ex. if you can take a copy of the project).

An analysis server log with the line length increased to something huge should help here though, and the smaller the project you can reproduce it with the better (since that'll result in less log bloat).

**Comment by tensor-programming** [comment] 2019-05-20 18:14
I made a small 3 minute video showcasing the issues and also turned on the logger while doing this.  I am a bit sick so my voice is a little scratchy but I think the video is pretty self explanatory.  For this particular "showcase" I started VScode, and use the pallet to create a new flutter project.  Then I removed the counter logic and turned the `MyHomePage` widget into a stateless widget; that's it.   The Video Follows from there: [Video Here](https://youtu.be/Dm6dVrL8bC4).  

As I mention in the video, when I restart VSCode, the problem goes away if and only if the imports are made prior to the restart.  As you can also see in the video, I was initially mistaken in believing it only affected imported libraries.  Out of the gate, I have no `flutter material` auto completion. 

Here is the [log](https://github.com/tensor-programming/dart_code_autocompletion_error/blob/master/Dart-Code-Log-2019-04-01%2013-45-09.txt).  I also made a repo of the code from the video though I am not sure its really that helpful.  [Repo](https://github.com/tensor-programming/dart_code_autocompletion_error).  I put the log length to one million lines and will create one for the other issue later today.

**Comment by DanTup** [comment] 2019-05-21 10:02
@tensor-programming thank you very much for this, it illustrates the problem perfectly. I think it's related to the work done to include unimported symbols in code completion. As part of it, completions were moved into "suggestion sets" and cached on the client (even for those imported) and I suspect that they're not being stitched together properly.

You could try disabling this with `"dart.autoImportCompletions": false` in your VS Code settings, and I suspect the issue will go away.

I'll dig through the logs, though I think it might be missing some important information about the suggestion sets at startup. If you can easily reproduce this from opening VS Code, then setting the [ dart.analyzerLogFile](https://dartcode.org/docs/logging/#analyzer) will capture a log that includes startup (however it might get quite large if it takes you a while to reproduce it).

I could also make a build that has some additional diagnostic logging in, which you could run and then when the issue occurs, run a command that will collect information about the cached suggestion sets and how they were built, which might help identify what's up.

**Comment by DanTup** [comment] 2019-05-21 10:23
Don't worry about the log - I believe I've reproduced this using your repository and v1.6.0. I'm just digging and will let you know what I find shortly :-)

**Comment by DanTup** [comment] 2019-05-21 10:34
@bwilkerson @schegolv FYI... I'm still digging into this, but I think there might be a server bug. I opened the sample project given above twice and the first time I hit the same issue (many completion items are missing) and the second time it worked fine. I grabbed logs for both:

[analyzer_bad.txt](https://github.com/Dart-Code/Dart-Code/files/3202028/analyzer_bad.txt)
[analyzer_good.txt](https://github.com/Dart-Code/Dart-Code/files/3202029/analyzer_good.txt)

Both of them should be essentially the same but `analyzer_bad` shows only the Dart SDK libraries being sent in `availableSuggestions` whereas `analyzer_good` also shows all the Flutter packages being sent.

**Comment by DanTup** [comment] 2019-05-21 10:36
Actually, now I think about it - when I first opened the project - there was no `.packages` file and it asked me if I wanted to fetch packages. So at a guess, this might be due to not picking up changes to .packages (possibly similar to https://github.com/dart-lang/sdk/issues/30845 which I said I couldn't repro yesterday!)

**Comment by tensor-programming** [comment] 2019-05-21 11:20
@DanTup yes that seems about right.  

The original video was done simply from a new project that was generated via the VS Code command pallet.  There was no auto completion outside of the DartSDK (No flutter etc). Then importing shared_prefs didn't add the library to the set of auto completions either. Restarting the editor does fix the problem though so perhaps the analyzer goes out and rebuilds the .packages files on boot?

**Comment by DanTup** [comment] 2019-05-21 11:27
Great, sounds like the same issue then. Indeed, if the `.packages` file exists during the analyzer startup, then everything is fine. It's just not handling `.packages` changing (or being created) which is similar to what https://github.com/dart-lang/sdk/issues/30845 reports (though strangely I don't see that specific error now).

I've opened https://github.com/dart-lang/sdk/issues/37035 in the SDK repo detailing this.

**Comment by DanTup** [comment] 2019-05-21 11:29
> Edit: I just built a new project on my machine. There is a .packages file in this new project and yet I still get no autocompletion unless I restart the editor. Also, its worth noting that when I say no flutter, I mean no flutter/material or flutter/foundation etc.

When you create a new project using VS Code, the .packages file is created after the analyzer starts (we create an empty folder, open it in VS Code - triggering the analyzer to start, then run `flutter create` in the folder). This would explain why the Flutter packages don't work (same bug as above).

> There are still completions being pulled in from the sky-engine core packages.

Can you give an example of these? I suspect that these are from the `dart:` libraries? I believe those are always included (since they're part of the Dart SDK) regardless of .packages.

**Comment by tensor-programming** [comment] 2019-05-21 11:32
An example is the `StackOverflowError` which is from the `SkyEngine/Core/Errors.dart` file.  I am not sure if that's considered a part of the Dart SDK when using the Flutter SDK.   Also I noticed that If I manually disable the dart analyzer (task manager and end the dart processes) and re-enable it, I get the proper completions again.  Seems to be consistent with what you were saying.

**Comment by DanTup** [comment] 2019-05-21 11:49
> An example is the `StackOverflowError` which is from the `SkyEngine/lib/Core/Errors.dart` file. I am not sure if that's considered a part of the Dart SDK when using the Flutter SDK.

I'm not sure of the relationship between the two, but I think in this context they're basically the same. I think the analyzer is providing completions for the types in the Dart SDK always (`lib/core/errors.dart` exists in the Dart SDK too with the same classes).

> To summarize, it seems to be an issue of the Analyzer not properly updating the completions when the `.packages` file changes in any way if the Analyzer is already running. Importing a library does add it to the `.packages` file but it just doesn't receive completions.

Pretty much. It's running `pub get` which adds to `.packages` (it downloads the package to your pub cache, and then writes the pack into that file). The analyzer uses `.packages` to know where to find the source for each package.

Until the issue has a better fix, the two workarounds are:

1. Set `"dart.autoImportCompletions": false` in your settings - this will stop completions for unimported symbols, but as a side-effect it will fix imported ones
2. Whenever you hit this, run **Reload Window** from the VS Code palette. This is the fastest way to restart the analysis server (it will actually tear the whole extension down and restart it, but it's pretty fast - the slowest part will be analysis and that's the bit you need to trigger anyway).

Depending on how easy a fix in the SDK is, we could also consider "silently restarting" the extension whenever `pub get` has finished running which would avoid you having to manually reload the window (and it wouldn't visible reload the editor) but is slightly more aggressive since it'll happen even if you didn't really need it.

**Comment by scheglov** [comment] 2019-05-21 17:43
https://dart-review.googlesource.com/c/sdk/+/103320 will re-scan available libraries on `.packages` changes.

**Comment by DanTup** [comment] 2019-05-21 18:23
Awesome, thanks for the quick fix - I'll try it out tomorrow :-)

**Comment by tensor-programming** [comment] 2019-05-21 21:38
We nice.  Will have to check it out myself as well.

**Comment by DanTup** [comment] 2019-05-22 07:26
Trying the fix yourself right now is slightly complicated because you have to download a nightly Dart SDK and paste it over the one inside your Flutter SDK (which isn't really recommended because it could cause other issues). I did to it on Flutter `master` to verify the fix though, and it does work as expected :-)

Until the fix reaches whichever channel you're on you can keep using those workarounds (disable, or reload), or you could switch to the `master` channel (which essentially is the same as `"dart.autoImportCompletions": false` since the version we require to enable it was slightly newer than current stable).

I think the SDK rolls into Flutter fairly frequently, so I expect the fix will make `master` within a few days, and probably `dev` within a week or two. Once it hits master it'll be clear which version it's in (so it's easier to tell when it makes dev).

I'll close this since it's fixed, but feel free to ping if you have any questions (or open new issues if you have other problems). Thanks!

**Closed** 2019-05-22 07:26 UTC
Labels: fixed in dart / flutter

**Comment by tensor-programming** [comment] 2019-05-25 22:31
seems to be working on the dev branch with `1.6.3`.
