### ISSUE TITLE
Dart processes not terminated after closing VS code

### ISSUE THREAD

**Issue by bergwerf** [Dart-Code/Dart-Code#1140] opened 2018-08-04 15:25 UTC
I see a lot of Dart processes are still not terminated (and eating up memory) after I close VS code. They seem to be related to running individual tests via the PubTest runner.

EDIT: To be more explicit, after killing all of them I freed up something like 10GB

**Comment by DanTup** [comment] 2018-08-04 15:40
Could you run the `Dart: Capture Logs` command and select `Pub Test` and `Observatory` categories and try and repro and send me a log?

Can you also confirm:

- Are you terminating runs or letting them finish? Pub by default will allow the current run to complete, but hitting stop a second time should terminate it.
- What's the exact command lines of the processes left around?
- What version of VS Code, Dart Code, Dart VM and `test` package?

**Comment by bergwerf** [comment] 2018-08-04 15:59
Ok, minimal example repo:

```
name: simple_test
version: 0.0.1

dependencies:
  test: '>=1.0.0'
```

```
import 'package:test/test.dart';

main() {
  test('test', () {
    assert(1 == 2);
  });
}
```

I add a breakpoint on the assert. Then I click the new debug that appears over the test block. Then when it breaks I terminate the debugger (clicking the red square), and exit VS code. After that these processes are still not terminated (I guess they should already be terminated after terminating the debugger):

![image](https://user-images.githubusercontent.com/4458965/43678230-d3875572-980f-11e8-9603-47b1323547e9.png)

Logs:
[Dart-Code-Log-2018-07-06 17-55.txt](https://github.com/Dart-Code/Dart-Code/files/2259614/Dart-Code-Log-2018-07-06.17-55.txt)

**Comment by DanTup** [comment] 2018-08-04 16:37
> (I guess they should already be terminated after terminating the debugger):

There might be some edge cases here, though I don't know if it's what you're hitting. Pub by default wlil wait for the current test when we tell it to quit - we need to tell it again to abort that. That said, unless your tests are slow/hung, I'd expect them to still timeout and quit after that. Are you seeing them hang around for more than the timeout set for your tests (60 seconds default?).

There's nothing obvious in these logs, but I'll see if I can repro. I'm away next week though, so might not be until after.

**Comment by bergwerf** [comment] 2018-08-04 16:41
Ok.
I can try keeping them around for a few minutes, but I believe the 
things I was seeing earlier might have been from a week ago (when I was 
debugging something the associated file). There were also too many of 
them (maybe 10) to be terminated within 60 seconds.
For now I can get away with `pkill -f dart`, but I will have to 
remember doing that because it eats memory quite quickly. I don't know 
why I didn't recognize this earlier, perhaps it is linked to the pub 
runner (which I have only been using since two weeks).

**Comment by DanTup** [comment] 2018-08-04 16:46
Could you have been on an older version of the test package back then? I did have to add a new event to `test` to expose the `pid` at startup to help with cleanup issues. 

If they're not cleaning up after the timeout, my guess is that they've stopped on exceptions. Maybe we should charge the exception pause mode when we're trying to disconnect to prevent that just in case other things fail.

If it still repros, maybe try disabling pausing on exceptions and see if it goes away.

**Comment by bergwerf** [comment] 2018-08-04 16:53
I again see a bunch of processes from my other project that have been 
there for a few minutes. I am using test 1.3.0.
With the minimal example files, the processes are terminated when I 
continue the debugger instead of terminate. When I pause on an 
exception and then uncheck 'Unhandled exceptions', and terminate, the 
process keeps existing. If I run without pausing on exceptions (but 
still enabling the breakpoint), the process is still not terminated 
when I stop the debugger.
I think it should be quite easy to reproduce.

**Comment by DanTup** [comment] 2018-08-04 16:58
Cool, thanks for the info and testing, I'll see what I can find. I did do testing of this specifically, which is why we added PID to test. The CI also checks for no Dart processes at the end of runs, though I'm not sure if we have tests explicitly pausing and terminating. I'll try and repro when I'm back at PC with some spare minutes.

**Comment by DanTup** [comment] 2018-08-20 15:04
Looking at this again.. Still don't seem to be able to repro. In your log, it shows only one pub test process spawning, and says that it exited:

> Process exited with code null

Is it possible the log you got was from a time it didn't happened? Are you able to test again (and grab a log?). Ensure there are no dart process running at all before you start, then open VS Code, start logging, repro, then stop logging, close VS Code, then check if there are still processes hanging around and if so, send me the log (and a copy of what the processes are - with commands lines, if possible).

**Comment by DanTup** [comment] 2018-08-22 14:11
I wonder if those VMs are paused on some exceptions? When you have time, could you try finding a port that one of them is bound to, opening in your browser and checking what the status of the Isolates are (eg. are they paused on some asserts or something?)

**Comment by bergwerf** [comment] 2018-09-29 21:01
:S again Dart processes were taking up 13Gb today (was already wondering why YouTube videos were not smooth). I think because I did a bunch of debugging this afternoon. I quickly tried to reproduce it but apparently it is not that simple anymore (I had already killed all processes by the time I realized I should have inspected those).

I find it somewhat odd no-one is experiencing this. Perhaps it is a Debian/Ubuntu problem, or perhaps that are not that many people debugging Dart VM apps and not restarting their computer often.

Next time I notice processes hanging around I'll have a look at the opened ports.

**Comment by DanTup** [comment] 2018-09-30 20:56
I'm not sure why nobody else is seeing it - Linux is a small percentage (< 15%) of Dart Code users, but I suspect it may also be specific actions/ordering/whatever causing it, and many people don't use the debugger at all (a surprising number of people run `flutter run` in the terminal and never use the debugger!).

I have tried to repro a few times without success. However, I do currently have some tests flaking recently caused by some Dart processes being left over (I fail my builds when this happens now) which may be or may not be this, but I've not dug into it yet.

If you can get any more info, please do post back. I'm keen to get to the bottom of it too :-)

**Comment by bergwerf** [comment] 2018-12-19 13:10
@DanTup Unfortunately not. I have done some debugging lately and checked for unterminated processes but I haven't found any. If I do I will report back here.

**Comment by DanTup** [comment] 2018-12-19 13:38
Ok, I guess that sounds positive. I'll close this for now just because it doesn't seem like there's anything I can progress, but please do post back if you see it again, I'm keen to get to the bottom of it if it's still happening. Thanks!

**Closed by DanTup** 2018-12-19 13:38 UTC
Labels: awaiting info, in debugger, is bug
