### ISSUE TITLE
Consider sending breakpoint paths in multiple formats to work around `part` issue

### ISSUE THREAD

**Issue by mezoni** [Dart-Code/Dart-Code#1489] opened 2019-02-27 10:00 UTC
Source code of the project was sent to developers.

**Comment by DanTup** [comment] 2019-02-27 10:12
@mezoni Got it, thanks! I think I know what's going on. The other issue we were commenting on was actually split from another - there are two issues:

https://github.com/Dart-Code/Dart-Code/issues/1443
https://github.com/Dart-Code/Dart-Code/issues/1446

And there are matching SDK issues for each:

https://github.com/dart-lang/sdk/issues/35859
https://github.com/dart-lang/sdk/issues/35860

While your issue might not be related to the relative paths, I do think it's related to the `part of`s.

So, I think this issue is a dupe of https://github.com/Dart-Code/Dart-Code/issues/1443. The related SDK issue is being looked at, there was a comment just a few days ago.

I believe the issue is described in this comment here https://github.com/Dart-Code/Dart-Code/issues/1443#issuecomment-460544986. The reason it doesn't happen in IntelliJ is likely because it still sends the breakpoint paths in both formats - something that should be unnecessary and I'd prefer to avoid (however, it if seems like this isn't going to be fixed for some time in Dart, I may  concede to temporarily putting them back).

Let me know if you believe this is *not* a dupe of #1443/https://github.com/dart-lang/sdk/issues/35859 and why and I'll do more investigation, otherwise I'll close this as a dupe.

Thanks for your patience, and sorry for the confusion!

**Comment by mezoni** [comment] 2019-02-27 10:32
Sounds frighteningly: "Breakpoints aren't hit inside "part" files" because the most of the source code is in these 'part' files.
I can not make a decision and give you an answer.
It seems to me that the existing algorithm of work does not take into account something.

I cannot find in your code where you resolve unresolved breakpoints after VM paused. Or they all will be resolved by VM without additional communucation with the VM?
Maybe need to communicate with VM again to resolve all unresolved breakpoints after VM paused isolate after start or handle some event from VM when it notifies about that?

**Comment by mezoni** [comment] 2019-02-27 10:42
What will happen if you perform the test where you set some breakpoint that will always hit and at this moment you will reanalize the state of other breakpoints?
Eg. Ask VM about these breakpoints? Does they all was resolved by VM? Then analize your information about these breakpoints and verify this information by asking VM directly about each breakpoint.

**Comment by DanTup** [comment] 2019-02-27 10:57
> Sounds frighteningly: "Breakpoints aren't hit inside "part" files" because the most of the source code is in these 'part' files.

Sure, I agree this is a nasty bug, and it's been raised with the SDK and has had activity very recently, so appears like it's being worked on.

> I cannot find in your code where you resolve unresolved breakpoints after VM paused. Or they all will be resolved by VM without additional communucation with the VM?

I think there may be some confusion over what I meant by "breakpoint resolution" work. I was referring to communicating whether a breakpoint is resolved or not to VS Code (so it can show them greyed out when they're not resolved). Right now, we just pretend every breakpoint is immediately resolved (so they always appear as red). The work to improve this is on a branch.

> Maybe need to communicate with VM again to resolve all unresolved breakpoints after VM paused isolate after start or handle some event from VM when it notifies about that?

I'm not sure what this suggestion relates to. This bug (I believe) is the VM issue linked above. The resolution work is separate, and I understand how achieve it, I just need VS Code to play nicer with how we have to do it.

**Comment by mezoni** [comment] 2019-02-27 10:59
Can you perform similar (silent) test (with logs) at the  runtime for each breakpoint?

https://github.com/dart-lang/vm_service_client/blob/6a6d00c5922ef43bc3eab5ed0af8bda1fe294ed0/test/breakpoint_test.dart#L162

https://github.com/dart-lang/vm_service_client/blob/6a6d00c5922ef43bc3eab5ed0af8bda1fe294ed0/test/breakpoint_test.dart#L177

https://github.com/dart-lang/vm_service_client/blob/6a6d00c5922ef43bc3eab5ed0af8bda1fe294ed0/test/breakpoint_test.dart#L180

https://github.com/dart-lang/vm_service_client/blob/6a6d00c5922ef43bc3eab5ed0af8bda1fe294ed0/test/breakpoint_test.dart#L181

**Comment by DanTup** [comment] 2019-02-27 11:04
@mezoni I'm not sure I understand the question. What is it you'd like to achieve? If you're looking for a way to fix the issue with breakpoints not working in `part` files, then there is already an open SDK issue about fixing it.

If that fix is unlikely to come anytime soon, I may consider adding a workaround in the VS Code plugin, but I would like to give them a chance to fix it first, as putting the workaround back in VS Code causes other issues and complicates finishing the breakpoint resolution UI changes.

**Comment by mezoni** [comment] 2019-02-27 11:18
Thank you.
I just thought that this can be done forcibly (resolve the breakpoints as in the test) and then they (breakpoints) will be guaranteed to work.
Now I understood (or I suppose that maybe I understood) that the problem is much deeper and now nobody deals with the solution of this problem from the Dart SDK developers.
It is quite possible to explain why the plug-in developers for JetBrains chose a comprehensive, but at the same time, workable algorithm.

As for me, sometimes it much easier to get something to work (when you work with Dart SDK) is a way when you implement some workaround fix rather when you wait when it will be fixed it the Dart SDK.

**Comment by DanTup** [comment] 2019-02-27 11:39
> I just thought that this can be done forcibly (resolve the breakpoints as in the test) and then they (breakpoints) will be guaranteed to work.

The only way to guarantee they'll work today, is to send the breakpoint to the VM twice. Since depending on whether the file is loaded as a `part` or not, it will only match either the `file:///`uri, or the `package:` uri. The editor doesn't know which is correct, since we don't directly parse the script.

> It is quite possible to explain why the plug-in developers for JetBrains chose a comprehensive, but at the same time, workable algorithm.

IntelliJ sends the breakpoints multiple times. The VS Code plugin used to too. However it was removed because a) all the instances I'd found with `package:` uris not working had been fixed (though it's clear now I missed one with `part`s and b) it was causing other issues (like complicating the resolution UI work, and causing warnings in VS Code because of sending back more breakpoints that it expected).

> As for me, sometimes it much easier to get something to work (when you work with Dart SDK) is a way when you implement some workaround fix rather when you wait when it will be fixed it the Dart SDK.

I am the same - these plugins are full of little hacks to make things work better. I'm just reluctant to this hack back in when I had waited so long to remove it and it looks like a fix is underway in the SDK. As I said, if it seems like that won't arrive in a reasonable timeframe, I will consider re-adding the workaround (temporarily).

**Comment by DanTup** [comment] 2019-02-27 11:41
I've renamed this issue and will keep it open to revisit in a few weeks to see what the progress has been.

**Comment by mezoni** [comment] 2019-02-27 11:52
Thank you for your explanations and support.

**Comment by mezoni** [comment] 2019-02-27 12:03
If my memory serves me, the Dart developers have already paid enough attention to this problem.
This was not related to debugging, while it was related to the issue about why are used in the Dart VM different kinds for source file location specifications.
The problem was in that the they was noncomparable because was used at the same time different shemas of the URI's for the same resource locations (source code files).
As far I know, it was fixed as possible in many places at least in the area of which it was occured and has affect.
But this was a long time ago and ...it was related to Dart SDK reflection library (possibly).

**Comment by mezoni** [comment] 2019-02-27 13:19
![screen](https://user-images.githubusercontent.com/2311549/53492802-8c616800-3abb-11e9-902a-76102d8b89f0.png)

It works as described here: https://github.com/dart-lang/sdk/issues/35859#issuecomment-463096981
And debugger references the location as absolute file path. (file://)

http://127.0.0.1:8181/#/inspect?isolateId=isolates%2F373558474&objectId=libraries%2F%4020258282%2Fscripts%2Ffile%253A%252F%252F%252Fhome%252Fantonina%252Fprj%252Fpeg3%252Flib%252Fsrc%252Fexpressions%252Fexpressions.dart%2F1692f0f67a4---pos=10253

**Comment by mezoni** [comment] 2019-02-27 17:50
@DanTup Do you know that Observatory Debugger works well with such (so called) problematic breakpoints?
I found that you complained (on the Dart SDK issue tracker) that there is no necessary documentation (formats for breakpoints could be explicitly documented).
I agree with that the lack of the good documentation in most cases does not helps to make the work better.
But  another way to study the subjet is to study its implemetation.
After looking at the source code of Dart Observatory Debugger I found it does not have the problems with addding breakopints (possibly except the case when the same script are used by more than one library).
I can even say that there are no any problem with that how to correctly specify the source location.
If I understand corretly before to add breakpoint it is necessary to specify the script location.
To specify the correct script location it is necessary to load all isoloate libraries explicitly at each procedure of lookup the script if the library was not loaded yet before.

You can look at the source code of how to add breakpoint. Procedure of adding breakpoint can be implemented in few lines of code but the procedure of the parsing the debugger location (script location in our terms) is a very complex asynchronous procedure.

You can find here.

https://github.com/dart-lang/sdk/blob/5721d8af6d8755fa6f70f3951de2c451c57bf12f/runtime/observatory/lib/src/debugger/debugger_location.dart


It always precedes the procedure of adding breakpoint. Or, to be more correct, it is an important part of that procedure.

Even if the script name is known it is necessary to resolve the script.

```dart
// Parse script called from add breakpont
if (scriptName != null) {
      // Resolve the script.
      var scripts = await _lookupScript(debugger.isolate, scriptName);


static Future<List<Script>> _lookupScript(Isolate isolate, String name,
      {bool allowPrefix: false}) {
    var pending = <Future>[];
    for (var lib in isolate.libraries) {
      if (!lib.loaded) {
        pending.add(lib.load());
      }
    }
    return Future.wait(pending).then((_) {
      var matches = <Script>[];
      for (var lib in isolate.libraries) {
        for (var script in lib.scripts) {
          if (allowPrefix) {
            if (script.name.startsWith(name)) {
              matches.add(script);
            }
          } else {
            if (name == script.name) {
              matches.add(script);
            }
          }
        }
      }
      return matches;
    });
  }
```

Remember that Observatory Debugger is just a front end to VM service debugger but it performs by itself some additional work but not only call VM service with client specified script location without to precede the procedure which by hand (of cource, using the isolate) resolves the breakpoint location.

P.S
Of course, I can be mistaken because I do not have time to check it all in action.
And as you also know, it corectly works when the VM isolate starts (as in my test) without attached debugger and breakpoints was added after VM paused after start. Maybe problem only in that.

**Comment by mezoni** [comment] 2019-02-27 17:59
Below is a starting points to study.
Step by step.

https://github.com/dart-lang/sdk/blob/d560887ae5b2f6e6f44fb14bfce08d537f7acd76/runtime/observatory/lib/src/elements/debugger.dart#L741

https://github.com/dart-lang/sdk/blob/d560887ae5b2f6e6f44fb14bfce08d537f7acd76/runtime/observatory/lib/src/elements/debugger.dart#L750

https://github.com/dart-lang/sdk/blob/d560887ae5b2f6e6f44fb14bfce08d537f7acd76/runtime/observatory/lib/src/elements/debugger.dart#L765

https://github.com/dart-lang/sdk/blob/d560887ae5b2f6e6f44fb14bfce08d537f7acd76/runtime/observatory/lib/src/elements/debugger.dart#L772

Parse -> resolve -> lookup

https://github.com/dart-lang/sdk/blob/d560887ae5b2f6e6f44fb14bfce08d537f7acd76/runtime/observatory/lib/src/debugger/debugger_location.dart#L26

https://github.com/dart-lang/sdk/blob/d560887ae5b2f6e6f44fb14bfce08d537f7acd76/runtime/observatory/lib/src/debugger/debugger_location.dart#L35

https://github.com/dart-lang/sdk/blob/d560887ae5b2f6e6f44fb14bfce08d537f7acd76/runtime/observatory/lib/src/debugger/debugger_location.dart#L66

https://github.com/dart-lang/sdk/blob/d560887ae5b2f6e6f44fb14bfce08d537f7acd76/runtime/observatory/lib/src/debugger/debugger_location.dart#L91

https://github.com/dart-lang/sdk/blob/d560887ae5b2f6e6f44fb14bfce08d537f7acd76/runtime/observatory/lib/src/debugger/debugger_location.dart#L114

**Comment by DanTup** [comment] 2019-02-27 18:07
@mezoni I understand the issue, and I know that it works from Observatory and IntelliJ. I've explained why it works in IntelliJ and it'll work in Observatory because you're setting the breakpoint from the loaded script, so the URI is known and correct.

In VS Code, we must transmit the breakpoints before the application has started, which means no scripts are loaded, which means we have to "guess" which format to send the path in (or send it multiple times).

I've opened an issue in the SDK repo and it appears to be active. Fixing it there will make our "guess" correct more of the time. It doesn't make sense to put a workaround into the VS Code plugin if there is a fix on the way. Like I said, if the fix doesn't come soon, I will consider re-implementing a workaround here.

**Comment by mezoni** [comment] 2019-02-27 18:14
>> In VS Code, we must transmit the breakpoints before the application has started, which means no scripts are loaded, which means we have to "guess" which format to send the path in (or send it multiple times).

Yeah...
Could you please explain why is your way better? What is wrong with preloading scripts and add  breakpoints after VM paused? Is this can be a very hard work to load libraries?

**Comment by DanTup** [comment] 2019-02-27 18:37
> What is wrong with preloading scripts

As far as I am aware, there is no way for me to tell the VM service to preload the scripts. You can see it's API here:

https://github.com/dart-lang/sdk/blob/master/runtime/vm/service/service.md

**Comment by mezoni** [comment] 2019-02-27 19:04
Yes. I forget that your extension written in TypeScript language.
The only way to do this is to write a script in Dart language, which will be a wrapper to `vm_service_client` (your own service library).
You will start your own service script which will interact with Dart VM directly via `vm_service_client` which are much more powerfull than the Dart VM Service Protocol.

**Comment by mezoni** [comment] 2019-02-27 19:06
https://github.com/dart-lang/vm_service_client/blob/master/lib/src/library.dart#L47

```dart
 Future<VMLibrary> load() async =>
      new VMLibrary._(_scope, await _scope.loadObject(_id));
```

**Comment by DanTup** [comment] 2019-02-27 19:43
> Yes. I forget that your extension written in TypeScript language

The language isn't important. The IntelliJ debugger is written in Java, this one is TypeScript. They all talk to the VM via the (JSON) service protocol API.


> `vm_service_client` which are much more powerfull than the Dart VM Service Protocol.

The `vm_service_client` is simply a wrapper over the VM Service Protocol (it's description is "A Darty client for the VM service protocol"). Anything it can do, we can do here too. The `load` method you've posted is to load a `Library` instance from an `id` (it calls https://github.com/dart-lang/sdk/blob/master/runtime/vm/service/service.md#getobject).


I fear we're going in circles. I've said before, there are ways to work around this, but since a fix is being worked on in the VM, it doesn't make sense to implement a workaround here. If the VM does not get a fix soon, I'll consider adding a workaround.


Alternatively, if you believe there's a simple fix for this (that is not just a workaround) and would like to send a PR, I'd happily review it.

**Comment by DanTup** [comment] 2019-02-27 20:06
I've pushed a failing test in 7d529fee59b55cdf2208dcc1ea87749bb8431d46 which I believe should pass if #1443 is fixed.

**Comment by mezoni** [comment] 2019-02-28 17:33
I found the solution how to preload the 'part' files using VM protocol.
These part files (in terms of the vm protocol) are srcipts of library (parts of this library).
This explain why these breakpoint does not works.
Below is the (my own short) report about how it works by default (even if the libraries, so called VM objects, would be preloaded by calling function "load()").

```
Library: package:dart_temp/foo.dart
Scripts: 1
  package:dart_temp/foo.dart
```
Now after adding just a single line of code via vm protocol possible receive different information. 

```
Library: package:dart_temp/foo.dart
Scripts: 2
  file:///E:/prj/dart_temp/lib/src/foo.dart
  package:dart_temp/foo.dart
```

Do you feel difference?
Part file (file:///E:/prj/dart_temp/lib/src/foo.dart) was preloaded by the single line of code.

P.S.
I think that this behavior of the VM (VM service or VM debugger) can be considered as the feature of the Dart VM that possibly was not documented as the behavior that has some affects.

Do you want to try find this the solution by yourself?

It was not so hard (to find the solution) but I would like to note that once you tried to convince me not to do such experiment because it is useless (in your opinion) and and it won't work.

**Comment by mezoni** [comment] 2019-02-28 17:42
Source code of short test.

```dart
Future<void> report(VMRunnableIsolate isolate) async {
  for (var key in isolate.libraries.keys) {
    var library = await isolate.libraries[key].load();
    var libraryUri = library.uri;
    if (library.uri.path.contains('dart_temp')) {       
      print('Library: ${libraryUri}');
      print('Scripts: ${library.scripts.length}');
      for (var script in library.scripts) {
        print('  ${script.uri}');
      }
    }
  } 
}
```

**Comment by DanTup** [comment] 2019-02-28 17:44
@mezoni I'm afraid I don't understand what you're suggesting I should change. If you wish to try to fix this in a PR, I'm happy to assist and help. You can see how the communication with the VM service works by running the **Dart: Capture Logs** command and then ticking the **Debugger** option. You'll see all of the calls to the VM including the ones to `addBreakpointWithScriptUri`.

> I think that this behavior of the VM (VM service or VM debugger) can be considered as the feature of the Dart VM

I do not believe it is a feature of the VM that you have to send breakpoints with paths formatted differently depending on whether the file is included with `part`. The editor does not parse any Dart code and therefore does not know how the file is included.

**Comment by DanTup** [comment] 2019-02-28 17:46
> Source code of short test

Your code requires that the isolate has been created and the scripts loaded. At the time that we need to send the breakpoints to the VM, this is not guaranteed. We need to send the breakpoints potentially before any isolates are created.

**Comment by mezoni** [comment] 2019-02-28 17:59
Problem in that how you add breakpoints.
With the current implementation of the Dart VM your algorithm does not take into account some features of that how Dart VM works.
Your actions are not enough. I can't even understand why the developers didn't warn you about this.

>> Your code requires that the isolate has been created and the scripts loaded. At the time that we need to send the breakpoints to the VM, this is not guaranteed. We need to send the breakpoints potentially before any isolates are created.

Oh. Currently this is imposible because it wil not works as you wish.
Or you should ask Dart SDK developers about some new feature especially for you.
Or you need to decide another solution.

>> We need to send the breakpoints potentially before any isolates are created.

But why need this? I know that you use `addBreakpointWithScriptUri` which means that you use `scriptUri` instead of `scriptId` which required for `scriptId`.
With `addBreakpointWithScriptUri` it also will works but sometimes it may not work because I already explaned the reason.

**Comment by DanTup** [comment] 2019-02-28 18:08
> Oh. Currently this is imposible because it wil not works as you wish.
> Or you should ask Dart SDK developers about some new feature especially for you.

I'm not sure how you came to that conclusion. If https://github.com/dart-lang/sdk/issues/35859 is resolved, then I believe this issue is solved.

> > We need to send the breakpoints potentially before any isolates are created.
> But why need this?

Sorry, I described this badly. Isolates may not have been created at the time that we currently send breakpoints. We could delay sending them until the isolate loads, but I don't believe there's any guarantee that the scripts have all been loaded (new isolates may spawn later and as I understand it, Dart supports deferred loading of scripts).

> With `addBreakpointWithScriptUri` it also will works but sometimes it may not work because I already explaned the reason.

It sometimes doesn't work because the URI is incorrect. That's what https://github.com/dart-lang/sdk/issues/35859 is all about. It is the best fix for this problem.

Anyway, I fear we're going in circles. If you believe this is easy to fix, I'm happy to review and assist with a PR. Otherwise, I'm going to see whether the VM issue is fixed soon (https://github.com/dart-lang/sdk/issues/36023 has been tagged as P1, so I expect it may be fixed soon) before investing time in a workaround.

**Comment by mezoni** [comment] 2019-02-28 18:08
>> I do not believe it is a feature of the VM that you have to send breakpoints with paths formatted differently depending on whether the file is included with `part`.

Yeah. :-)
The feature not in  ` that you have to send breakpoints with paths formatted differently depending on whether the file is included with `part`.`
Oh. This is not relevant at all. It has no sense (how path was formatted) in current contect of our current disscusion.
The main thing in that how VM runs and what action need to perform to get it ready to work as you expected.
:-)

**Comment by mezoni** [comment] 2019-02-28 18:17
>> Anyway, I fear we're going in circles. If you believe this is easy to fix,

You cannot understand me. :-(
**The main thing in that how VM runs and what action need to perform to get it ready to work as you expected.**
Currently you still doesn't understand why VM is not ready to accept your requests to add breakpoints.
To be more  correct, VM will accept them but they will not work due the reason which I expalined.

```
Library: package:dart_temp/foo.dart
Scripts: 1
  package:dart_temp/foo.dart
```

Now after adding just a single line of code via vm protocol possible receive different information.

```
Library: package:dart_temp/foo.dart
Scripts: 2
  file:///E:/prj/dart_temp/lib/src/foo.dart
  package:dart_temp/foo.dart
```
Because part files can remains unresolved the whole time that VM runs.
VM never will pause on the files.

**Comment by mezoni** [comment] 2019-02-28 18:22
You should like to warm up the VM, at least some part of the VM that need you for to get ready the VM to work with your current algorithm (addBreakpointWithScriptUri).
Wow. This is a thick hint.

**Comment by mezoni** [comment] 2019-02-28 18:29
I want you to understand and find the solution yourself.
That will be your great merit.
What good is it if I tell you how to do this?

You yourself must strive for this.
Well, or at least to ask the developers about it.
In essence, this is a workaround, since it is not documented.
But I think Dart developers took this into account when they was implemented their own web debugger whic also work the same way as your debugger.

**Comment by mezoni** [comment] 2019-02-28 21:09
It works.

```dart
import 'dart:async';
import 'dart:convert';
import 'dart:io';

import 'package:async/async.dart';
import 'package:path/path.dart' as _path;
import 'package:vm_service_client/vm_service_client.dart';

Future<void> main() async {
  var cwd = Directory.current.path;
  var script = _path.join(cwd, 'test', 'test.dart');
  var client = await runAndConnect(script);
  var isolate = (await client.getVM()).isolates.first;
  isolate.stdout.transform(lines).listen((line) {
    print(line);
  });

  isolate.onExit.then((_) {
    print('onExit');
  });

  isolate.onBreakpointAdded.listen((VMBreakpoint bp) {
    print('onBreakpointAdded:');
    print('  ${bp.location}');
  });

  isolate.onPauseOrResume.listen((event) async {    
    if (event is VMPauseBreakpointEvent) {
      print('  BP: ${event.breakpoints.first} #${event.breakpoints.first.number}');
      Timer(Duration.zero, () async {
        await isolate.resume();        
      });
    }
  });
  
  await isolate.waitUntilPaused();
  var breakpoints = <VMBreakpoint>[];  
  await warmUp(isolate); // <============= this is workaround
  var library =
      await findLibrary(isolate, Uri.parse('package:dart_temp/foo.dart'));
  var uri = Uri.file(_path.join(cwd, 'lib', 'src', 'foo.dart'));
  //
  addBreakpoint(library, uri, breakpoints, 5);
  addBreakpoint(library, uri, breakpoints, 6);
  //
  await isolate.resume();
}

Future<void> addBreakpoint(VMLibrary library, Uri uri,
    List<VMBreakpoint> breakpoints, int line) async {
  VMScriptRef script;
  for (script in library.scripts) {
    if (script.uri.path == uri.path) {
      break;
    }
  }

  if (script == null) {
    return null;
  }

  var breakpoint = await script.addBreakpoint(line);
  breakpoints.add(breakpoint);
  return breakpoint;
}

Future<void> warmUp(VMIsolateRef isolate) async {
  //  Skipped
}

Future<VMLibrary> findLibrary(VMIsolateRef isolate, Uri uri) async {
  var runnableIsolate = await isolate.loadRunnable();
  for (var key in runnableIsolate.libraries.keys) {
    var library = await runnableIsolate.libraries[key].load();
    if (library.uri == uri) {
      return library;
    }
  }

  return null;
}

final lines = new StreamTransformer(
    (Stream<List<int>> stream, bool cancelOnError) => const LineSplitter()
        .bind(utf8.decoder.bind(stream))
        .listen(null, cancelOnError: cancelOnError));

Future<VMServiceClient> runAndConnect(String script) async {
  var args = [
    '--pause-isolates-on-start',
    '--pause-isolates-on-exit',
    '--enable-vm-service=0',
  ];
  args.add(script);
  var process = await Process.start(Platform.resolvedExecutable, args);  
  var stdout = new StreamQueue(process.stdout.transform<String>(lines));
  var line = await stdout.next;

  // Start executing main().
  process.stdin.writeln();

  var match = new RegExp('Observatory listening on (.*)').firstMatch(line);  
  var client = new VMServiceClient.connect(match[1]);
  client.done.then((_) {
    process.kill();
  });

  return client;
}

```

Result:

```
onBreakpointAdded:
  file:///E:/prj/dart_temp/lib/src/foo.dart at 5
onBreakpointAdded:
  file:///E:/prj/dart_temp/lib/src/foo.dart at 6
  BP: breakpoint #1 in file:///E:/prj/dart_temp/lib/src/foo.dart #1
==> 0
  BP: breakpoint #2 in file:///E:/prj/dart_temp/lib/src/foo.dart #2
==> i0
  BP: breakpoint #1 in file:///E:/prj/dart_temp/lib/src/foo.dart #1
==> 1
  BP: breakpoint #2 in file:///E:/prj/dart_temp/lib/src/foo.dart #2
==> i1
  BP: breakpoint #1 in file:///E:/prj/dart_temp/lib/src/foo.dart #1
==> 2
  BP: breakpoint #2 in file:///E:/prj/dart_temp/lib/src/foo.dart #2
==> i2
  BP: breakpoint #1 in file:///E:/prj/dart_temp/lib/src/foo.dart #1
==> 3
  BP: breakpoint #2 in file:///E:/prj/dart_temp/lib/src/foo.dart #2
==> i3
```

Part file

```dart
part of '../foo.dart';

foo() {
  for (var i = 0; i <= 3; i++) {
    print('==> $i');
    print('==> i$i');
  }  
}
```

P.S.

I do not presume to state that my method is unique and correct, but it works.

**Comment by mezoni** [comment] 2019-02-28 21:17
It was a very big hint.
After this hint, the Dart SDK developers can find a solution in 3 minutes.
:-)

**Comment by mezoni** [comment] 2019-02-28 21:29
The `findLibrary` should be slightly simplified.

```dart
Future<VMLibrary> findLibrary(VMIsolateRef isolate, Uri uri) async {
  var runnableIsolate = await isolate.loadRunnable();
  for (var key in runnableIsolate.libraries.keys) {
    var library = await runnableIsolate.libraries[key];
    if (library.uri == uri) {
      return await library.load();
    }
  }

  return null;
}
```

**Comment by mezoni** [comment] 2019-03-01 05:27
If I have free time, I will redo your breakpoint service.
Now your current implementation is fundamentally different from the one for which the current implementation of this service in a virtual machine is designed.
You rely on the fact that the virtual machine will do all the work for you, but this is wrong.
This service in a viral machine is essentially designed to facilitate the implementation of this service on a remote client.
The implementation of this service on a remote client is very simple, and is quite clearly regulated by how this service is arranged on the host.
At the same time, the lack of complete documentation on this interaction regulation makes it difficult to implement correct mutual relations.
At the moment, I suppose that I figured out why the virtual machine rejects certain ways of referencing the source files.
**I also understood why the virtual machine uses the different ways of referencing the source files.**
This is the main reason for the mistakes of developers of debuggers associated with the lack of a full understanding of why the virtual machine chooses one or another ways of referencing the source files.
This leads to the fact that the developers, not understanding the essence and principle of operation of the virtual machine debugger service, try to interact with this service blindly or, so to speak, for good luck.
To get the effect, developers are starting to add breakpoints for good luck, using all possible ways of referencing the source files which they can imagine as possible.
This is a misconception and a common mistake, because the virtual machine never chooses this or that way of referencing the source file by chance.
It performs this operation strictly according to the regulations, in accordance with the source text of the entire application.
This explains why under different conditions, the same source files are referenced differently.
**A clear understanding of this principle and adherence to this principle is an integral part of the correct implementation of the breakpoint service on the remote client.**
Your current implementation is fundamentally wrong. I agree that it will work, but it will never interact with the viral machine as it is expected by the virtual machine.
It is not fault tolerant because it is based on a lack of understanding of what should really be.
It lacks many of the much-needed internal services to ensure correct interaction with remote debugger.
For example, can you acquaint me with such your service as the calculation and resolution of the source file referencing schema which will be used by the virtual machine depending full path to this source code starting from the root library of one or another isolate?
Yes, I agree that this requires certain calculations and not complicated procedures for analyzing the source code (only its individual sections), but it is not difficult and, moreover, it can be cached or tracked changes in the file system.
This can be bypassed, but at the same time guarantee close to 99% fault tolerance to the service of breakpoints, but there must be another service on the client, which will be based on a simple, but at the same time sufficiently reliable way of matching the links generated by the virtual machine and those that the client would like to use if the remote client would choose a simplified way of refferencing source files.
**You should understand that the source code is not only the source file, but it is primarily a section of application code that can be referenced in various ways. For example, a compiler.**

Sorry, but I have run out of time ...

**Comment by mezoni** [comment] 2019-03-01 05:31
Small typo:
>> For example, a compiler.

For example, by compiler when it compiles these source files.

**Comment by mezoni** [comment] 2019-03-01 06:45
I like your extensions and I don’t like the approach of the Dart developers to this issue. Their direct responsibility is to provide you with maximum assistance, providing the necessary documentation and advice.
Please do not consider this criticism as a means of disrespect.
It was just an attempt to direct you, as a developer, in the right direction.
I do not want to offer you a ready-made solution (the source code of the service of breakpoints on the remote client), despite the fact that it is a rather simple task.
Your client communicates with the virtual machine correctly, but it does not take into account how the virtual machine perceives the source code and its location during the execution of the isolate.
You must increase your level of knowledge in this direction.
It is very easy to understand. I realized this in an instant, when I started debugging my simple debugger.
For this, it is not even necessary to study the source code.
It is enough to analyze the data (from protocol responses) that the host sends in response to your requests.
Or, to be more precise, just try to understand why this is so, but not otherwise.

With this approach (with the lack of the required documenation), there will always be a reasonable explanation and understanding of what is happening.
Sometimes you can invent the same thing, not looking inside inside the system, but only analyzing the work of the system and asking yourself a lot of questions and setting yourself the task of finding answers to them without fail.
This is called finding a solution to a problem by studying the behavior of an system, with the suggestion that the system works optimally, correctly  and nothing happens by chance.

**Comment by mezoni** [comment] 2019-03-01 13:07
A minor problem I discovered was that the protocol emulation was not fully implemented in your extension.
Your current implementation does not allow you to apply the "evaluate" function to VM service objects.
Because in your implementation they don't store important information received from VM service calls.
I can say that are exists in state "out of scope" which prevent to evaluate them.
I have not figured it out yet, but the reason is that it is not possible to manipulate these objects remotely.
I think that need store more (raw) reflection information about them.
I wiil look later which information is missing.

It seems to me something from this.
```json
{"type":"@Class","fixedId":true,"id":"classes\/14","name":"Library"},
```

**Comment by mezoni** [comment] 2019-03-02 12:46
Now your extension works as expected. No problems with breakpoints.
Because Dart VM also works as it should.
But I need to make some changes to my implementation.

Current problems:
- I don't know TypeScript (I did not like it)
- I need continue to study your work
![vscode](https://user-images.githubusercontent.com/2311549/53681978-bb254b80-3d12-11e9-9efd-30d45f14176a.png)

P.S.
Most of the time was spent exploring your implementation.

**Comment by mezoni** [comment] 2019-03-02 12:48
Debugging TypeScript asynchronous code is not a pleasant experience.

**Comment by mezoni** [comment] 2019-03-02 13:09
The new implementation takes into account all possible ways of addressing source code, that is, it can set two breakpoints on the same line. Later I will explain to you why this can happen. I will send you one interesting test and you will see what happens when you debug your extension by running this test.
And, at the same time, a new implementation NEVER sets extra breakpoints (that is, two instead of one).

**Comment by mezoni** [comment] 2019-03-02 17:24
I sent the pull request.
Sorry, but I forget to perform the last test on linux file system.

**Comment by DanTup** [comment] 2019-03-21 08:46
The VM issue has been resolved, and I've tested fix. Breakpoints in `part` files are now hit with no changes to Dart Code :-)

If you need the fix now, you could use a [nightly build](https://gsdview.appspot.com/dart-archive/channels/be/raw/latest/sdk/) until the change reaches a dev/stable builds.

If you find any other issues (including missed breakpoints), please do let me know. Thanks for your effort and patience! :)

**Closed by DanTup** 2019-03-21 08:46 UTC
Labels: is discussion / feedback
