### ISSUE TITLE
Using LSP causes VS Code/computer to freeze

### ISSUE THREAD

**Issue by praxa-enzo** [Dart-Code/Dart-Code#4587] opened 2023-06-14 09:56 UTC
**Describe the bug**
When I have LSP turned off (the default option) visual code freezes completely, together with the rest of my computer. My memory usage is completely full. I tried to exclude directories, files etc. but nothing worked until I turned on LSP. Now I don´t have any problems anymore. 

**Please complete the following information:**
 - Operating System and version: Ubuntu 22.04.2
 - VS Code version: 1.78.2
 - Dart extension version: 3.66.0
 - Dart/Flutter SDK version: Dart: 2.19.6; Flutter: 3.7.11
 - Target device (if the issue relates to Flutter debugging):

**Comment by DanTup** [comment] 2023-06-14 09:59
> When I have LSP turned off (the default option) visual code freezes completely

Can you clarify what you mean by turning LSP off? What settings are you changing, to what state? LSP is the default (and has been for a long time). The only way to turn LSP off is to switch to the legacy protocol (which is not recommended).

**Comment by praxa-enzo** [comment] 2023-06-14 10:02
I have to set the below setting in order for it to work properly:
![image](https://github.com/Dart-Code/Dart-Code/assets/110832124/047fe2cb-010c-4f25-940d-64e9299fe69a)

**Comment by DanTup** [comment] 2023-06-14 10:06
You have to tick the option to fix it? If so, that's disabling LSP so it sounds like the issue is _with_ LSP. That is certainly a problem that needs solving.

Does this issue reproduce in a brand new Flutter sample project? If you run the **Flutter: New Project** command to create a new project, then _untick_ the Legacy Protocol tickbox and restart VS Code, does it still trigger the issue?

If so, could you try capturing a log file (in the new sample project) by:

- Open the sample project
- Running the **Preferences: Open Workspace Settings (JSON)** command from the command palette
- Pasting inside the JSON braces:
    ```
    "dart.analyzerInstrumentationLogFile": "logs/analyzer.instrum.txt",
    ```
- Save the settings file (this will automatically restart the language server)
- Wait for the issue to occur
- Provide the log file (after ensuring it contains nothing sensitive)

You can attach the log here, in a Gist, or email to me at logs@dartcode.org.

Thanks!

**Comment by praxamarnix** [comment] 2023-06-15 10:39
I work together with Enzo and I am encountering the same issues as Enzo, but enabling the legacy analyzer doesn't help for me under windows. My performance monitor indicates that visual studio code (dart.exe) is taking almost 8GB of RAM.

Restarting the analysis server reduces the dart executable back to 2GB and then it starts to add up again, even when not touching any code.

I will see if I can reproduce it in a brand new project as you describe.

Operating System and version: Windows 11
- VS Code version: 1.79.1
- Dart extension version: 3.66.0
- Dart/Flutter SDK version: Dart: 3.0.3; Flutter: 3.10.4

![image](https://github.com/Dart-Code/Dart-Code/assets/114977711/1b74848c-b401-4b36-b841-ab540a7c98d7)

**Comment by praxamarnix** [comment] 2023-06-15 11:23
A new project does not seem to have the issue as described above. I also tried to replace the analysis_options.yaml with ours, and I tried to add `lints: 2.0.1` and `dart_code_metrics: 5.7.2`, but the fresh project is still stable.

Would you like to see a log of our project? Or are there other things we can try out to pinpoint the issue?

**Comment by praxa-enzo** [comment] 2023-06-15 11:30
I created a new flutter project and unticked the box but then the problems didn't occur. 
The weird thing is that when I got back to my own project (without LSP) the problem didn't occur again (for now at least).

**Comment by praxa-enzo** [comment] 2023-06-15 12:37
Nevermind, it happened again. It seems to be happening right after I open a file from the dart library itself.

**Comment by DanTup** [comment] 2023-06-15 14:08
Can you try capturing a log file as described above. It may contain parts of your source file so please do not share it if it contains anything sensitive - but you could look through it and see if there are any obvious errors reported (or if it seems like it may be stuck in some kind of loop).

If there's any way you can duplicate your project and strip it back to a repro you can share, that would certainly help (or might even identify what's triggering the issue while doing so).

**Comment by praxamarnix** [comment] 2023-06-16 07:05
Here are the log and status as requested. For me this issue happens all the time. I start VS code with the workspace open, no files open, and it just heaps memory usage within a minute or so. LSP or legacy doesn't matter.

[analyzer.instrum.txt](https://github.com/Dart-Code/Dart-Code/files/11767261/analyzer.instrum.txt)
[code status.txt](https://github.com/Dart-Code/Dart-Code/files/11767262/code.status.txt)

```
Version:          Code 1.79.2 (695af097c7bd098fbf017ce3ac85e09bbc5dda06, 2023-06-14T08:57:04.379Z)
OS Version:       Windows_NT x64 10.0.22621
CPUs:             12th Gen Intel(R) Core(TM) i7-1270P (16 x 2496)
Memory (System):  15.67GB (0.74GB free)
VM:               0%
Screen Reader:    no
Process Argv:     --crash-reporter-id 2bd88cc8-62f5-4138-80e7-35c543f920d8
GPU Status:       2d_canvas:                              enabled
                  canvas_oop_rasterization:               disabled_off
                  direct_rendering_display_compositor:    disabled_off_ok
                  gpu_compositing:                        enabled
                  multiple_raster_threads:                enabled_on
                  opengl:                                 enabled_on
                  rasterization:                          enabled
                  raw_draw:                               disabled_off_ok
                  video_decode:                           enabled
                  video_encode:                           enabled
                  vulkan:                                 disabled_off
                  webgl:                                  enabled
                  webgl2:                                 enabled
                  webgpu:                                 enabled

CPU %   Mem MB     PID  Process
    0       95   21484  code main
    0      204    6752  window [1] (firmware_support.dart - <product> (Workspace) - Visual Studio Code)
    0      137   11268     gpu-process
    0       27   13480     crashpad-handler
    0       71   15344  fileWatcher [1]
    0       83   17320  extensionHost [1]
    0        4    9760       C:\Windows\system32\cmd.exe /d /s /c ""C:\Users\<myname>\Source\flutter\bin\cache\dart-sdk\bin\dart.exe" "language-server" "--protocol=lsp" "--client-id=VS-Code" "--client-version=3.66.0" "--instrumentation-log-file=C:\Users\<myname>\Source\Repos\<product>\.github\logs\analyzer.instrum.txt""
    6     3544   14184         "C:\Users\<myname>\Source\flutter\bin\cache\dart-sdk\bin\dart.exe"  "language-server" "--protocol=lsp" "--client-id=VS-Code" "--client-version=3.66.0" "--instrumentation-log-file=C:\Users\<myname>\Source\Repos\<product>\.github\logs\analyzer.instrum.txt"
    0       10   27048         console-window-host (Windows internal process)
    0       87   17384       electron-nodejs ("C:\Program Files\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node "c:\Program Files\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\node\jsonServerMain" --node-ipc --clientProcessId=17320)
    0      100   21140       electron-nodejs ("C:\Program Files\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node c:\Users\<myname>\.vscode\extensions\streetsidesoftware.code-spell-checker-2.20.5\packages\_server\dist\main.js --node-ipc --clientProcessId=17320)
    0        4   23072       C:\Windows\system32\cmd.exe /d /s /c ""C:\Users\<myname>\Source\flutter\bin\cache\dart-sdk\bin\dart.exe" "devtools" "--machine" "--try-ports" "10" "--allow-embedding" "--port" "9100""
    0       10   10172         console-window-host (Windows internal process)
    0       83   18344         "C:\Users\<myname>\Source\flutter\bin\cache\dart-sdk\bin\dart.exe"  "devtools" "--machine" "--try-ports" "10" "--allow-embedding" "--port" "9100"
    0        7   27424       C:\Windows\system32\cmd.exe /d /s /c ""C:\Users\<myname>\Source\flutter\bin\flutter.bat" "daemon""
    0       75   22956         electron-nodejs (config.js )
    0       10   26108         console-window-host (Windows internal process)
    0       53   17644  ptyHost
    0        5    8360       "C:\Program Files\Git\bin\bash.exe" --login -i
    0       11   27804         "C:\Program Files\Git\bin\..\usr\bin\bash.exe" --login -i
    0        7   28136       console-window-host (Windows internal process)
    0       61   22480  shared-process
    0       42   26132     utility-network-service

Workspace Stats:
|  Window (firmware_support.dart - <product> (Workspace) - Visual Studio Code)
|    Folder (scripts): 23 files
|      File types: sh(20) py(2) jar(1)
|      Conf files:
|    Folder (virtual-client): 9 files
|      File types: db(3) py(2) gitattributes(1) md(1) txt(1)
|      Conf files:
|    Folder (.github): 10 files
|      File types: md(2) yml(2) txt(1) 1(1) 2(1)
|      Conf files:
|    Folder (auth): 13 files
|      File types: dart(5) json(1) metadata(1) md(1) lock(1) yaml(1)
|      Conf files:
|    Folder (model): 19 files
|      File types: dart(11) json(1) gitignore(1) lock(1) yaml(1) md(1)
|      Conf files:
|    Folder (environment): 18 files
|      File types: secret(3) dev(1) prod(1) git(1) gitignore(1) kbx(1) kbx~(1)
|                  gpg(1) cfg(1) txt(1)
|      Conf files:
|    Folder (certificate): 22 files
|      File types: txt(4) crt(4) pfx(1) cer(1) csr(1) key(1) ca-bundle(1)
|                  p7b(1) secret(1) md(1)
|      Conf files:
|    Folder (device-client): 109 files
|      File types: dart(37) json(18) md(3) dill(2) puml(2) yaml(2) 0(2)
|                  packageLocations(1) sum(1) deps(1)
|      Conf files:
|    Folder (middleware): 129 files
|      File types: dart(53) json(17) md(3) txt(3) dill(2) bin(2) yaml(2)
|                  packageLocations(1) sum(1) deps(1)
|      Conf files:
|    Folder (cli): 115 files
|      File types: dart(34) json(18) log(7) yaml(3) py(3) dill(2) md(2)
|                  packageLocations(1) sum(1) deps(1)
|      Conf files: launch.json(1) tasks.json(1)
|      Launch Configs: dart(4)
|    Folder (shared): 121 files
|      File types: dart(31) json(16) log(15) yaml(8) dill(2) part(2) md(2)
|                  packageLocations(1) sum(1) deps(1)
|      Conf files:
|    Folder (api): 211 files
|      File types: py(42) mustache(32) json(26) md(26) dart(18) gitignore(4)
|                  txt(4) yml(3) yaml(3) funcignore(2)
|      Conf files: package.json(1)
|    Folder (dashboard): 1041 files
|      File types: dart(146) tlog(130) png(52) ttf(51) svg(45) h(39) obj(29)
|                  json(27) log(23) stamp(20)
|      Conf files: cmake(10) sln(4) launch.json(1) tasks.json(1)
|      Launch Configs: dart(2)
```

**Comment by DanTup** [comment] 2023-06-16 11:05
I don't know if it's related to your issue, but there are some exceptions in the log you attached:

```
1686897955881:PluginEx:Could not resolve "package::dart_code_metrics/dart_code_metrics.dart" in C::\Users\<MYNAME>\Source\Repos\<product>\api.:
#0      PluginManager.recordPluginFailure (package::analysis_server/src/plugin/plugin_manager.dart::489::7)
#1      PluginWatcher.addedDriver (package::analysis_server/src/plugin/plugin_watcher.dart::52::17)
#2      AnalysisDriverScheduler.add (package::analyzer/src/dart/analysis/driver.dart::2026::22)
#3      new AnalysisDriver (package::analyzer/src/dart/analysis/driver.dart::300::16)
```

It looks like this happens for a number of projects. It would be interested to track down the cause of that to figure out a) if fixing that solves the problem, and b) if so, whether that allows me to reproduce the issue and figure out what's happening.

I presume you're using dart_code_metrics - is it possible that it's only referenced in some of your projects and not others pubspecs?

(FYI @incendial in case you've seen this and might know what causes it)

**Comment by DanTup** [comment] 2023-06-16 11:13
Interestingly I also see a bunch of empty diagnostics being produced for files that don't look interesting:

```
1686898020901:PluginNoti:{"event"::"analysis.errors","params"::{"file"::"C::\\Users\\<MYNAME>\\Source\\Repos\\<product>\\dashboard\\build\\windows\\runner\\cmake_install.cmake","errors"::[]}}:file::///C::/Users/<MYNAME>/AppData/Local/.dartServer/.plugin_manager/02390d8d7036500dce28308531345f8f/analyzer_plugin/bin/plugin.dart::
1686898020901:Res:{"jsonrpc"::"2.0","method"::"textDocument/publishDiagnostics","params"::{"diagnostics"::[],"uri"::"file::///C::/Users/<MYNAME>/Source/Repos/<product>/dashboard/build/windows/runner/cmake_install.cmake"}}
1686898020928:PluginNoti:{"event"::"analysis.errors","params"::{"file"::"C::\\Users\\<MYNAME>\\Source\\Repos\\<product>\\dashboard\\build\\windows\\runner\\dashboard.dir\\Debug\\dashboard.exe.recipe","errors"::[]}}:file::///C::/Users/<MYNAME>/AppData/Local/.dartServer/.plugin_manager/02390d8d7036500dce28308531345f8f/analyzer_plugin/bin/plugin.dart::
1686898020929:Res:{"jsonrpc"::"2.0","method"::"textDocument/publishDiagnostics","params"::{"diagnostics"::[],"uri"::"file::///C::/Users/<MYNAME>/Source/Repos/<product>/dashboard/build/windows/runner/dashboard.dir/Debug/dashboard.exe.recipe"}}
```

I don't think that should cause any real issues itself, but it is adding extra traffic between the server and VS Code, and might be causing VS Code to do some extra work that might not help. @incendial I think these might be coming from DCM since they're preceded by plugin notifications - is it something that could be skipped?

**Comment by praxa-enzo** [comment] 2023-06-16 11:37
> I don't know if it's related to your issue, but there are some exceptions in the log you attached:
> 
> ```
> 1686897955881:PluginEx:Could not resolve "package::dart_code_metrics/dart_code_metrics.dart" in C::\Users\<MYNAME>\Source\Repos\<product>\api.:
> #0      PluginManager.recordPluginFailure (package::analysis_server/src/plugin/plugin_manager.dart::489::7)
> #1      PluginWatcher.addedDriver (package::analysis_server/src/plugin/plugin_watcher.dart::52::17)
> #2      AnalysisDriverScheduler.add (package::analyzer/src/dart/analysis/driver.dart::2026::22)
> #3      new AnalysisDriver (package::analyzer/src/dart/analysis/driver.dart::300::16)
> ```
> 
> It looks like this happens for a number of projects. It would be interested to track down the cause of that to figure out a) if fixing that solves the problem, and b) if so, whether that allows me to reproduce the issue and figure out what's happening.
> 
> I presume you're using dart_code_metrics - is it possible that it's only referenced in some of your projects and not others pubspecs?
> 
> (FYI @incendial in case you've seen this and might know what causes it)

I saw that one of the dart projects in our multi-root workspace was missing dart_code_metrics. I added it but after a few minutes the dart analysis tools still shut down.

I added the log.
[analyzer.instrum.txt](https://github.com/Dart-Code/Dart-Code/files/11769746/analyzer.instrum.txt)

**Comment by praxamarnix** [comment] 2023-06-16 13:04
I figured out that removing dart code metrics completely resolves the instability issues. I also found that dart code metrics is no longer a an analyzer plugin https://dcm.dev/blog/2023/06/06/announcing-dcm-free-version-sunset/.

We will remove dart code metrics for now and buy a license for their new version that is a standalone application. The error mainly came from our analysis_options.yaml that had this line:

```yaml
analyzer:
  plugins:
    - dart_code_metrics
```

**Comment by DanTup** [comment] 2023-06-16 13:18
Great, glad you found a solution. I haven't tried it out, but I've heard that the standalone version of DCM performs much better. The current analysis server plugin system is experimental and unsupported and there are discussions about redesigning it (because of these kinds of scalability issues).

I'll close this because I don't think there's anything to do (or at least, the issue is just known issues with performance of analyzer plugins).

Of course, if you do run into issues again when there aren't any analyzer plugins enabled, please do let me know!

**Closed by DanTup** 2023-06-16 13:18 UTC
Labels: is bug, awaiting info
