### ISSUE TITLE
Just installed Flutter 0.4.4. Now vscode won't debug main.dart "The Dart Analyzer could not be started. ..."

### ISSUE THREAD

**Issue by JoeCodeswell** [Dart-Code/Dart-Code#965] opened 2018-05-30 20:09 UTC
Whenever i hit F5 to debug main.dart, VS code repeatedly shows a dialog saying "The Dart Analyzer could not be started. Please set the `dart.analyzerLog` option and review the log file for errors."

![clipboard01](https://user-images.githubusercontent.com/3194021/40744657-2214a7a6-640a-11e8-8eee-4f0790079496.jpg)

I have added analysis_options.yaml to the project in the same dir as pubspec.yaml
here is analysis_options.yaml

[analysis_options.yaml.txt](https://github.com/Dart-Code/Dart-Code/files/2055479/analysis_options.yaml.txt)

Everything was WORKING GREAT before Flutter 4.4

Thanks for the help in advance.
Love and peace,
Joe Dorocak

**Comment by DanTup** [comment] 2018-05-30 20:31
@JoeCodeswell Can you run `flutter doctor` from the terminal and then try again? I had a similar issue today which I think is caused by Flutter having not downloaded the Dart SDK (so it doesn't have the analyzer snapshot or something).

LMK if that works, and I'll see if I can handle this better.

**Comment by JoeCodeswell** [comment] 2018-05-30 23:32
Hi @DanTup,
After my above report: 

1.  I renamed flutter to be flutter_0.4.4 & flutter_0.3.2 to be flutter ---> I SUCCESSFULLY debugged my main.dart.. 
2. I renamed flutter to be flutter_0.3.2 & renamed  flutter_0.4.4 to be flutter ---> SAME PROBLEM "The Dart Analyzer could not be started..."
3. Here is the flutter doctor result ---> puzzling!
![clipboard01](https://user-images.githubusercontent.com/3194021/40752959-b2e8a4dc-6426-11e8-837d-648426fa5a50.jpg)

Thanks for the help, Dan. I'll go back to 0.3.2 until you figure this out.
Love and peace,
Joe Dorocak

**Comment by DanTup** [comment] 2018-05-31 13:27
Hmmm, I think something is wrong with your download with Flutter. Could you try downloading it again to a new folder and then see if `flutter doctor` works from inside the `flutter_console.bat` that's included?

**Comment by JoeCodeswell** [comment] 2018-05-31 15:31
Hi Dan,
I just:

1. navigated to https://flutter.io/setup-windows/
2. downloaded flutter_windows_v0.4.4-beta.zip
3. winzip extract PRODUCED ERROR:

![clipboard01](https://user-images.githubusercontent.com/3194021/40791521-92c3f4be-64ac-11e8-94ed-01dafda8320d.jpg)

Here is the WinZiolog. Scroll to the end to see the error.
[winzipLog.txt](https://github.com/Dart-Code/Dart-Code/files/2058851/winzipLog.txt)

I haven't done anything else yet.
Love and peace,
Joe Dorocak

**Comment by DanTup** [comment] 2018-06-01 10:15
@JoeCodeswell I think this is a Flutter issue rather than Dart Code. Can you re-raise this at https://github.com/flutter/flutter and ping me on the issue, and if nobody else gets to it before I do, I'll do some testing on Windows on Monday.

**Comment by DanTup** [comment] 2018-06-01 10:18
Also - could you try reviewing the Windows permissions on the new Flutter folder and the `flutter_console.bat` file and ensure they're the same as the old one?

**Comment by DanTup** [comment] 2018-06-04 15:26
If you want to try a different zip, you could grab a `dev` version from here to test (you don't have to use it, but it'd verify if something is bad with the zip):

https://flutter.io/sdk-archive/#windows

**Comment by DanTup** [comment] 2018-07-26 09:20
Closing this since I don't think there's anything to fix in Dart Code, something is wrong with Flutter. IF you're still having the issue I'd encourage you to open an issue in flutter/flutter though.

**Closed by DanTup** 2018-07-26 09:20 UTC
Labels: upstream in dart / flutter

**Comment by JoeCodeswell** [comment] 2018-07-27 16:09
Thanks, Dan.
Love and peace,
Joe
