### ISSUE TITLE
Enable to Skip Framework Files when Debugging in VS Code

### ISSUE THREAD

**Issue by tomasbaran** [Dart-Code/Dart-Code#4641] opened 2023-07-13 18:10 UTC
**Is your feature request related to a problem? Please describe.**
I can't believe I'm requesting this in 2023. You guys are a phenomenal team and I have a huge respect and admiration. With that being said, this is such a basic feature.

You can see many people asking for it:
- https://stackoverflow.com/questions/47556495/how-do-i-skip-external-code-when-debugging-in-vs-code 
- https://stackoverflow.com/questions/57589509/flutter-android-studio-debugger-skip-framework-files/73364737#73364737
- https://stackoverflow.com/questions/62491529/how-do-i-skip-files-when-debugging-in-vs-code 
- https://stackoverflow.com/questions/62489336/how-do-i-skip-external-files-when-debugging-a-flutter-app-in-vs-code 

**Describe the solution you'd like**
When I step over (F10), it always goes into framework files. I'm interested only in my code debugging, since that's where 99.9% of my bugs are located. I don't care about framework—it makes the debugger unusable.

**Describe alternatives you've considered**
I have set up in my settings.json the following:
```
	"dart.debugExternalLibraries": false,
	"dart.debugSdkLibraries": false,
```
however, it looks like `dart.debugExternalLibraries` is deprecated —  why? What is the alternative?
I have also tried: 
- `"justMyCode": true`
- `"skipFiles": [
  "flutter/**"
]`
- `"exceptionBreakpoints": [
  {
    "label": "All Exceptions",
    "enabled": false
  }
]`
- `"flutterTrackWidgetCreation": false,`
in launch.json. None of them work in Flutter/Dart.
**Additional context**
It is exceptionally needed and the most basic tool for debugging right after print/log. Please, make this feature ASAP but also give me some alternatives in the meantime, please. It's really difficult and unpleasant to debug without it.

**Comment by tomasbaran** [comment] 2023-07-13 18:12
@DanTup  I see you were trying to add this functionality in 2016: https://github.com/Dart-Code/Dart-Code/issues/135. Even the majority of people wanted to have `justMyCode` by default, which I completely agree. What happened? Now, not only is not allow by default, but it's not possible at all.

**Comment by DanTup** [comment] 2023-07-13 18:19
`"dart.debugExternalLibraries"` was renamed to `"dart.debugExternalPackageLibraries"` some time ago because it wasn't very obvious what it meant.

The default is still "just my code" (both of those settings are `false` by default), but you may be prompted to enable debugging framework/SDK if you try adding breakpoints in them. You can toggle the settings by clicking on the bottom left status bar.

If the status bar shows "Debug my code" without "+ sdk + packages" and the debugger is not doing as you expect, please provide an example/screenshot showing where it's breaking, as it might be that you're hitting another bug. Specifically:

> When I step over (F10), it always goes into framework files.

I'm not sure exactly what behaviour you're seeing, but `F10` should never step _in_ to anything, it should step over. Is this not what you're seeing?



> I can't believe I'm requesting this in 2023. You guys are a phenomenal team and I have a huge respect and admiration. With that being said, this is such a basic feature.

I'm happy to investigate your issues, but please be considerate when posting here. I debug "just my code" every day. Something may not be working as intended, but that might just be a bug we can fix - the feature is not missing :-)

**Comment by tomasbaran** [comment] 2023-07-13 19:16
Oh, what a relief then @DanTup. I was really scared it was not allowed. The reason it was not working for me then was renaming it to: `"dart.debugExternalPackageLibraries"`. I'll keep monitoring it. Big thanks @DanTup You just made my day.

**Comment by DanTup** [comment] 2023-07-14 08:49
Closing this as it sounds like everything is working as expected then, but please let me know if that's not the case.

**Closed by DanTup** 2023-07-14 08:49 UTC
Labels: is enhancement, awaiting info
