### ISSUE TITLE
Enable ability to debug on all connected devices.

### ISSUE THREAD

**Issue by babernethy** [Dart-Code/Dart-Code#855] opened 2018-04-30 12:25 UTC
An amazing feature (for development and demos) is the ability to run/hot-reload/debug on multiple devices (even across iOS and Android) simultaneously.

This is the equivalent of ...

`flutter run -d all
`

Dart Code makes it really easy to switch between devices - it could be even greater to be able to debug on all connected devices.

This isn't just good for iOS/Android cross-debug/demo - but also can be used for one phone, one tablet (see how your adaptive designs work) or one emulator portrait and one landscape (test different aspect ratios) - and since state is maintained you can have one device in a "logged in" state and another "anonymous (pre-authentication)", etc.  Imagine even more than two running (if you have the CPU/memory or decent USB bus ...)

**Comment by DanTup** [comment] 2018-04-30 14:30
Do you really mean debugging here, or just launching and reloading? We have #622 open about supporting launching/reloading but the plan was to not allow debugging for simplicity (you'd potentially have multiple apps from multiple devices hitting breakpoints all at the same time which could become confusing).

**Comment by babernethy** [comment] 2018-04-30 16:27
Running from VSC IDE on all devices would be really nice - we can do this in the VSC Terminal window with "flutter run -d all" right now (and do).  

I am not sure what the level of effort/work would be to add the debugging capability as well.  If the actions being debugged were user-initiated, it would be pretty easy to track which activity hit which breakpoint.  If the actions were timing/event/action based, then debugging on multiple devices, understandably, would become unruly.

p.s. Thanks for the great tools, and quick response - really liking the capabilities and now using DartCode over IntelliJ for most tasks ...

**Comment by DanTup** [comment] 2018-04-30 16:46
>  If the actions being debugged were user-initiated, it would be pretty easy to track which activity hit which breakpoint. If the actions were timing/event/action based, then debugging on multiple devices, understandably, would become unruly.

I'm not sure which actions you consider user-initiated. The "without debugging" support would likely only support start/stop/hot reload/full restart. Everything else I think is complicated (hitting breakpoints, using the variables/watch window, the debug console, etc.).

I don't think it's impossible - Code supports showing multiple threads; so in theory we could just show all threads from all devices and prefix them in some way. I'm not sure whether it's worthwhile though (it could be high cost to implement, quite complicated for users that are only interested in hot-reload across multiple devices and I'm not sure if how much it'd be used).

Is there actually anything outside of start/stop/hot reload/restart you're particularly interested in? Are you wanting to use breakpoints, watch window, debug console, etc?

> p.s. Thanks for the great tools, and quick response

Np! Glad you like it and hope it's working well for you 😃

**Comment by DanTup** [comment] 2018-05-19 10:34
Closing this as a dupe of #622, however I'm still interested to know if you're after more.

> Is there actually anything outside of start/stop/hot reload/restart you're particularly interested in?

**Closed by DanTup** 2018-05-19 10:34 UTC
Labels: awaiting info
