### ISSUE TITLE
Flutter gutter icons to not show for widgets inside conditional expressions

### ISSUE THREAD

**Issue by PhoenixLeeSin** [Dart-Code/Dart-Code#3196] opened 2021-03-11 07:33 UTC
newer to flutter ans VS, in my mac it can show flutter icons when write code, but it can not show in left ... 
I searched a lot of information but didn’t find the answer

flutter : Flutter 1.22.5 • channel stable
dart:     2.10.4 (stable)
VS: 1.54.1

Any suggestions are appreciated~~

![71615447716_ pic](https://user-images.githubusercontent.com/20637153/110751476-dd95bc00-827e-11eb-865f-64e2d65a2575.jpg)
![81615447761_ pic](https://user-images.githubusercontent.com/20637153/110751508-e6868d80-827e-11eb-9ef8-96bc4218176d.jpg)

**Comment by DanTup** [comment] 2021-03-11 09:35
I've not been able to repro this, the same icon shows up here:

<img width="609" alt="Screenshot 2021-03-11 at 09 34 03" src="https://user-images.githubusercontent.com/1078012/110766353-f9806a00-824c-11eb-84d5-23d999b94239.png">

If you paste the following simple code into your file somewhere, does it show there?

```dart
const a = const Icon(Icons.keyboard_arrow_up);
```

Does it not show up in _any_ files or just some specific ones?

**Comment by PhoenixLeeSin** [comment] 2021-03-12 08:43
@DanTup  
in my project  it not show up in any files  but it show correctly code is  const a = const Icon(Icons.keyboard_arrow_up);

**Comment by DanTup** [comment] 2021-03-15 16:03
@PhoenixLeeSin are you able to trim your file down to something small you can share that still shows the problem? Perhaps with the same code I can reproduce it.

**Comment by PhoenixLeeSin** [comment] 2021-03-16 01:18
@DanTup   oh.....when i init a new flutter project, icons shows in left!!!!
![image](https://user-images.githubusercontent.com/20637153/111241600-725e3800-8638-11eb-919c-8df339087da3.png)
 i do not konw why....

**Comment by DanTup** [comment] 2021-03-16 13:44
@PhoenixLeeSin can you try copying _exactly_ the same code (ideally the whole file) into the small test project, and see if the same occurs there?

**Comment by PhoenixLeeSin** [comment] 2021-03-17 00:15
@DanTup  thank u reply, when i copy the whole file it occurs error..
It’s a small mistake, but it does make me uncomfortable sometimes
whole file :
```
import 'package:flutter/material.dart';

class ScalableBox extends StatefulWidget {
  final List<Row> visibleSpans;
  final List<Row> unVisibleSpans;

  const ScalableBox({Key key, this.visibleSpans, this.unVisibleSpans})
      : super(key: key);
  @override
  _ScalableBoxState createState() => _ScalableBoxState();
}

class _ScalableBoxState extends State<ScalableBox> {
  bool _isMore = true;
  @override
  Widget build(BuildContext context) {
    return Container(
      padding: EdgeInsets.fromLTRB(10, 0, 0, 10),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: <Widget>[
          widget.visibleSpans.length >= 1
              ? widget.visibleSpans[0]
              : Container(),
          widget.visibleSpans.length >= 2
              ? widget.visibleSpans[1]
              : Container(),
          widget.visibleSpans.length >= 3
              ? widget.visibleSpans[2]
              : Container(),
          Offstage(
            offstage: _isMore,
            child: Column(
              children: widget.unVisibleSpans,
            ),
          ),
          widget.unVisibleSpans.length > 0
              ? Container(
                  child: GestureDetector(
                    onTap: () {
                      setState(() {
                        _isMore = !_isMore;
                      });
                    },
                    child: _isMore
                        ? Row(
                            mainAxisAlignment: MainAxisAlignment.center,
                            crossAxisAlignment: CrossAxisAlignment.center,
                            children: <Widget>[
                              Text(
                                '展开',
                                style: TextStyle(color: Colors.blue),
                              ),
                              Icon(
                                Icons.keyboard_arrow_down,
                                color: Colors.blue,
                                size: 16,
                              )
                            ],
                          )
                        : Row(
                            mainAxisAlignment: MainAxisAlignment.center,
                            crossAxisAlignment: CrossAxisAlignment.center,
                            children: <Widget>[
                              Text(
                                '收起',
                                style: TextStyle(
                                  color: Colors.blue,
                                ),
                              ),
                              Icon(
                                Icons.keyboard_arrow_up,
                                color: Colors.blue,
                                size: 16,
                              )
                            ],
                          ),
                  ),
                )
              : Container(),
        ],
      ),
    );
  }
}

**Comment by DanTup** [comment] 2021-03-17 16:59
@PhoenixLeeSin thanks! I was able to trim this down and it looks like it might be caused by the ternary operator:

<img width="502" alt="Screenshot 2021-03-17 at 16 58 42" src="https://user-images.githubusercontent.com/1078012/111506936-0cf66e00-8742-11eb-88c8-1aff99c45f01.png">

I'll see if I can find a way to handle this. Thanks!

**Comment by PhoenixLeeSin** [comment] 2021-03-18 00:45
Thanks u  Reply~

**Comment by DanTup** [comment] 2021-03-23 14:59
@bwilkerson this fails because I'm using the Flutter Outline data to locate icons, and for code with conditionals the then/else expressions are flat. This code:

```dart
return Container(
  child: true ? Icon(Icons.keyboard_arrow_down) : Container(),
);
```

Produces an outline like:

```js
"children": [
	{
		"element": {
			"range": /*...*/,
			"name": "Icon(Icons.keyboard_arrow_down)",
			"kind": "CONSTRUCTOR_INVOCATION"
		},
		"range": /*...*/,
		"codeRange": /*...*/
	}
]
```

I had a look at handling this, and have a possible fix here (which supports conditionals both in `child` expressions and in widget lists):

https://dart-review.googlesource.com/c/sdk/+/192688/

Although I don't know if it's the correct/best fix. The conditional is not shown in the tree, so it looks a bit like a flat list even when some pair of the child nodes could be exclusive. Perhaps an additional node could be inserted, although it would add more to the tree (if/else in collections do not currently do that, they're just flattened, so this does match them).

![Screenshot 2021-03-23 at 14 57 15](https://user-images.githubusercontent.com/1078012/112167058-1707e900-8be8-11eb-9254-0b719ad781f4.png)

WDYT?

**Comment by bwilkerson** [comment] 2021-03-23 15:41
I remember asking the question about `if` and `for` elements in the flutter outline when we were first implementing support for them, and I seem to remember that we decided to use a flat representation because we didn't have a good answer for the question of what to do when one branch would be represented in the outline and the other wouldn't.

I think that the solution in the referenced CL lgtm.

**Comment by DanTup** [comment] 2021-03-24 15:16
This is fixed by https://github.com/dart-lang/sdk/commit/387e9d9ab2cd991663df8781d4fd914c194960da. The fix ships in the Dart SDK (not the VS Code extension), so will show up only once you're on a newer SDK that includes that change.

**Closed by DanTup** 2021-03-24 15:16 UTC
Labels: in editor, in flutter, is bug
