### ISSUE TITLE
Can not show any error message when Xcode build script return nonzero

### ISSUE THREAD

**Issue by CyrilHu** [Dart-Code/Dart-Code#2741] opened 2020-08-26 07:36 UTC
I debug with F5 to launch a debugger session when I have a pubspec.yaml problem.
I can't find any useful message from the console
<img width="578" alt="image" src="https://user-images.githubusercontent.com/1403754/91274015-47012200-e7a8-11ea-8fcf-7863567e9dc3.png">

but if I run `flutter run` in terminal, the output has exact error message 
<img width="606" alt="image" src="https://user-images.githubusercontent.com/1403754/91274258-9e9f8d80-e7a8-11ea-8eea-99444bb53347.png">

I struggle for several hours to find this error message. 
I was not aware of that the flutter vscode plugin will ignore this error message.

flutter doctor -v
```
[✓] Flutter (Channel stable, 1.20.2, on Mac OS X 10.15.6 19G73, locale zh-Hans-CN)
    • Flutter version 1.20.2 at /Users/cyril/Git/flutter
    • Framework revision bbfbf1770c (13 天前), 2020-08-13 08:33:09 -0700
    • Engine revision 9d5b21729f
    • Dart version 2.9.1

 
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/cyril/Library/Android/sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    ✗ Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[!] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.48.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.13.2

[✓] Connected device (2 available)
    • iPhone 11 (mobile)                           • FBF4F61A-4CD8-42CA-9DA7-2F8A7A5825FC • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-6 (simulator)
    • iPad Pro (11-inch) (2nd generation) (mobile) • C73D8B61-4236-40CE-A0D1-7E2503514C7F • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-6 (simulator)

! Doctor found issues in 2 categories.
```

**Comment by DanTup** [comment] 2020-08-26 08:38
Thanks for the report! I think this is a dupe of https://github.com/flutter/flutter/issues/33582 and was recently fixed by https://github.com/flutter/flutter/pull/63815.

**Closed by DanTup** 2020-08-26 08:38 UTC
