### ISSUE TITLE
Autocomplete is deleteing next phrase after, you click on suggestion

### ISSUE THREAD

**Issue by HerrNiklasRaab** [Dart-Code/Dart-Code#2327] opened 2020-03-30 12:13 UTC
Is this a bug?

https://imgur.com/L3fVLHV

**Comment by DanTup** [comment] 2020-03-30 12:20
It's not, it's intended - however it's not the behaviour everyone wants and has come up before (see https://github.com/Dart-Code/Dart-Code/issues/1991).

VS Code has added a new API to allow you to control this (Enter vs Shift+Enter), however we do not yet support it (we need to do some work to tell VS Code how to handle each of those cases).

I'll close this as a dupe of that one. It's assigned for the next milestone (after the current one, which I just made a beta release for) so hopefully it'll be available then (though no promises). Thanks!

**Closed** 2020-03-30 12:20 UTC
Labels: duplicate
