### ISSUE TITLE
How to fix find error for dart:html in VSCode?

### ISSUE THREAD

**Issue by db29github** [Dart-Code/Dart-Code#1783] opened 2019-06-07 14:10 UTC
Hi, I raised the issue with the same name as I posted to Stackoverflow (https://stackoverflow.com/questions/56375637/how-to-fix-find-error-for-darthtml-in-vscode) 
For additional information my analyzerInstrumentation log in attachment.
[analyzerInstrum20190607.zip](https://github.com/Dart-Code/Dart-Code/files/3266254/analyzerInstrum20190607.zip)

**Comment by DanTup** [comment] 2019-06-09 09:57
Just to be clear - is the error shown in the Problems window in VS Code, or only when you run?

If only when you run, could you try:

- Run the **Dart: Capture Logs** command from the VS Code command palette
- Leave everything ticked
- Run the program to generate the error
- Click **Stop Logging** in the logging notification (it may have collapsed into the bell icon in the status bar)
- Attach the log here

Thanks!

**Comment by db29github** [comment] 2019-06-09 16:28
Hello!

No, it’s not shown in Problems window (in attachment you’ll see a “problem 1” but that caused by the dead code fragment not by the import clause).

I try to recreate situation on my other PC, and error present. I has Flutter installed on it but on VSCode I only use Dart and Code Runner extensions and point it on DartSDK folder under Flutter installation. Any issues with other import not happened yet. For instance I add “import 'dart:async';” and it not caused error.

So, I think it‘ ll be useful if you may try my code on yours environment and attached all project as is. All requested LOGs in ISSUE_LOG folder.
[WRK03t.zip](https://github.com/Dart-Code/Dart-Code/files/3269740/WRK03t.zip)


Thank you in advance for any suggestion.

**Comment by DanTup** [comment] 2019-06-09 19:42
You're using Flutter's version of the Dart SDK here, which is a cut-down version. It didn't use to include `dart:html`, however I'm not sure whether that changed as part of the web work.

Can you confirm which version of Flutter you're using?

The easiest thing for now would be to use a [real Dart SDK](https://dart.dev/tools/sdk) for this if you're not working on a Flutter project.

**Comment by db29github** [comment] 2019-06-09 20:13
I'm sorry for little bit confused you. That my second PC with different configuration i.e. has Flutter installed. But problem still present and not dependent on Flutter or only Dart installed. Tomorrow I can provide logs from "only Dart installed" PC. 
I suppose that something wrong with project creation or VSCode configuration. As I wrote previously dart code compiled to JS correctly from command line on both PCs.

**Comment by DanTup** [comment] 2019-06-09 20:16
A log from the Dart-only PC would help. For the PC using a Flutter SDK, this is somewhat expected (though I think may be fixed in newer versions of Flutter - I'm not sure if the stable version though).

The log you attached this time didn't contain all of the info, so please check you followed the steps above exactly (leave everything ticked in the log category list and click ok, then press F5 to run, and then after you see the error, click Stop Logging). Thanks!

**Comment by db29github** [comment] 2019-06-10 07:19
[Dart-Code.log.zip](https://github.com/Dart-Code/Dart-Code/files/3270982/Dart-Code.log.zip)
That LOG from Dart-only PC. 
Problem persist, and in OUTPUT window error message

_main.dart:1:8: Error: Not found: 'dart:html'
import 'dart:html';_

**Comment by DanTup** [comment] 2019-06-10 07:25
How are you running the project? The log file is still empty. You should run by pressing `F5`. If your file is not at `bin/main.dart` it may create a `launch.json` file and you'll need to set `program` to be the path to the Dart script.

**Comment by DanTup** [comment] 2019-06-10 07:26
Sorry, I'm really not thinking straight here. `dart:html` is only available when running in a browser, not on the VM. Are you trying to run this as a web project, or a command line project?

**Comment by db29github** [comment] 2019-06-10 07:43
That LOG by run "F5":
[Dart-Code-Log-2019-05-01 10-36-24.txt](https://github.com/Dart-Code/Dart-Code/files/3271035/Dart-Code-Log-2019-05-01.10-36-24.txt)

Error present in OUTPUT window
main.dart:1:8: Error: Not found: 'dart:html'
import 'dart:html';
...

[analyzerInstrum20190610_02.zip](https://github.com/Dart-Code/Dart-Code/files/3271046/analyzerInstrum20190610_02.zip)

**Comment by DanTup** [comment] 2019-06-10 07:45
`dart:html` is only available in the browser. This is the error you get if you try to run code that uses it on the VM (instead of the browser). This is expected.

If you need to run your code outside of the browser (eg. in the VM as a CLI app or via Fluter) you cannot use `dart:html`. If you only want to use it in the browser but VS Code is trying to run your code in the VM, you'll need to set up some VS Code tasks/launch configs to run build_runner, similar to the Dart DevTools project:

https://github.com/flutter/devtools/tree/master/packages/devtools/.vscode

Let me know if this doesn't make sense!

**Comment by db29github** [comment] 2019-06-10 07:52
Thank you, I try to explore your advice.

Really I need only create an JS for web page, and each time I try to debug it I see a bunch of errors in VSCode OUTPUT window.  

### **[Running] dart "d:\Dart\WRK03t\main.dart"
main.dart:1:8: Error: Not found: 'dart:html'
import 'dart:html';
       ^
main.dart:8:19: Error: Method not found: 'TableElement'.
var myTable = new TableElement()
                  ^^^^^^^^^^^^
main.dart:14:7: Error: 'TableRowElement' isn't a type.
List <TableRowElement> tabLine = new List();
      ^^^^^^^^^^^^^^^
main.dart:32:1: Error: Getter not found: 'document'.
document.body.children.add(myTable);
^^^^^^^^
main.dart:35:14: Error: Method not found: 'ParagraphElement'.
var p2 = new ParagraphElement()
             ^^^^^^^^^^^^^^^^
main.dart:39:3: Error: Getter not found: 'document'.
  document.body.children.add(p2);
  ^^^^^^^^**

**Comment by DanTup** [comment] 2019-06-10 07:59
This is because the code is running on the VM. You need to tell VS Code to run something to compile the app.

Please try this:

- Install the "Debugger for Chrome" extension from Microsoft
- Run the **Debug: Open launch.json** command from the VS Code command palette (if prompted to select between Chrome/Dart/etc., pick anything).
- Replace the contents of the file with:
```js
{
	"version": "0.2.0",
	"configurations": [
		{
			"type": "chrome",
			"request": "launch",
			"name": "Serve and launch in browser",
			"url": "http://localhost:8080",
			"webRoot": "${workspaceFolder}/web",
			"preLaunchTask": "pub: build_runner serve"
		}
	]
}
```

Now when you press `F5`, it should compile your app and launch it in Chrome. It will keep the server running, so when you make changes they will recompile in the background automatically (if you don't want this, you can change `serve` to `build` in the last line of the `launch.json`).

**Comment by DanTup** [comment] 2019-06-19 07:17
@db29github did you managed to resolve this? Did my comment make sense? Thanks!

**Comment by db29github** [comment] 2019-06-19 08:17
thank you for advice. I actually stuck on server authentication. It asks login password, but any of my local user not suitable.

**Comment by DanTup** [comment] 2019-06-19 08:27
Ok, that doesn't sound like a VS Code extension issue so I'll close this issue.

For your problem I'd suggest trying in one of the Dart Gitter rooms at https://gitter.im/dart-lang/home or StackOverflow (I don't really know enough to help troubleshoot unfortunately).

Thanks!

**Closed by DanTup** 2019-06-19 08:27 UTC
Labels: awaiting info

**Comment by ViNaYvINi123** [comment] 2020-11-23 08:26
#18     new Future.sync (dart:async/future.dart:223:31)
#19     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:123:19)
#20     _rootRun (dart:async/zone.dart:1190:13)
#21     _CustomZone.run (dart:async/zone.dart:1093:19)
#22     _runZoned (dart:async/zone.dart:1630:10)
#23     runZoned (dart:async/zone.dart:1550:10)
#24     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:122:12)
#25     IncrementalCompiler.computeDelta (package:front_end/src/fasta/incremental_compiler.dart:206:20)
#26     IncrementalCompiler.compile (package:vm/incremental_compiler.dart:69:46)
#27     FrontendCompiler.compile.<anonymous closure> (package:frontend_server/frontend_server.dart:524:59)
#28     new Future.<anonymous closure> (dart:async/future.dart:175:37)
#29     _rootRun (dart:async/zone.dart:1182:47)
#30     _CustomZone.run (dart:async/zone.dart:1093:19)
#31     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
#32     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
#33     _rootRun (dart:async/zone.dart:1190:13)
#34     _CustomZone.run (dart:async/zone.dart:1093:19)
#35     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:1021:23)
#36     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
#37     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:397:19)
#38     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:428:5)
#39     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
the Dart compiler exited unexpectedly.
the Dart compiler exited unexpectedly.
Exited (1)
  
I Cannot able to  compile the dart code above shows the result of dart compiler

**Comment by ViNaYvINi123** [comment] 2020-11-23 08:27
flutter also not updating .......   please help me ...........

**Comment by ViNaYvINi123** [comment] 2020-11-23 08:29
![Uploading Screenshot (3).png…]()

**Comment by DanTup** [comment] 2020-11-23 10:43
@ViNaYvINi123 please file another issue instead of commenting on the end of a closed one, and if possible, include a code sample that reproduces the issue. Thanks!
