### ISSUE TITLE
Allow running a Flutter app from a project subfolder

### ISSUE THREAD

**Issue by pulyaevskiy** [Dart-Code/Dart-Code#637] opened 2018-03-02 05:52 UTC
For projects implementing Flutter widgets (or plugins) it is very common to have an example app in `example/` folder. Like here:

https://github.com/pulyaevskiy/parallax-image

Currently it doesn't seem possible to run such apps in vscode. I tried modifying `launch.json` to have `"program": "example/lib/main.dart"` but it still fails with following error:

```
Launching example/lib/main.dart on iPhone 7 Plus in debug mode...
No application found for TargetPlatform.ios.
Is your project missing an ios/Runner/Info.plist?
Consider running "flutter create ." to create one.
Exited (sigterm)
```

**Comment by DanTup** [comment] 2018-03-02 07:25
I think this is a dupe of #493 (also: #581, #385). You should add the flutter project as a "root" in VS Code to indicate that it's a project (otherwise we'd have to scan the whole tree guessing which folders are intended to be projects).

I think we need to improve something here, but I think we should steer people towards multi-root support rather than re-implementing what it does within a single open folder.

**Closed** 2018-03-02 07:25 UTC
Labels: duplicate

**Comment by pulyaevskiy** [comment] 2018-03-02 18:37
> You should add the flutter project as a "root" in VS Code to indicate that it's a project 

But it's not _the_ project. Note that this is a convention that Pub uses to detect examples so it shows `example/lib/main.dart` in Example tab here:
https://pub.dartlang.org/packages/parallax_image#-example-tab-

Also, strictly speaking this is not a multi-root project, it has one root. Adding subfolder as a second root is kind of confusing and unnecessary from a user's point of view.

By the way, I just tried to do this and added `example` subfolder as second root. It still failed to locate `lib/main.dart` when I hit `F5`. But I forced VSCode to create `launch.json` for me which was put in the first root folder (`parallax_image/.vscode/launch.json`). Then I manually moved it to the example folder "root" (`parallax_image/example/.vscode/launch.json`) and it worked. Hitting `F5` now launches my example.

**Comment by DanTup** [comment] 2018-03-03 10:54
Ok, let's continue discussion in #493 which I've renamed. I think I'm convinced we need to handle this better with the `example` thing (though I still think it's likely to cause some other issues 😞).

**Comment by DanTup** [comment] 2018-03-03 11:06
> By the way, I just tried to do this and added example subfolder as second root. It still failed to locate lib/main.dart when I hit F5

My first guess is that you already had a launch.json somewhere so the debug config was set to it. The launch.json-less launching only works when you have no selected debug configuration. For multiple projects you'll likely need to have launch.jsons.

See my latest comment on the related case though.

**Comment by junaid1460** [comment] 2021-07-26 03:43
```
  "cwd": "yourdirecory"
```
?
