### ISSUE TITLE
Dart analyzer terminates frequently

### ISSUE THREAD

**Issue by rydmike** [Dart-Code/Dart-Code#2805] opened 2020-09-18 11:39 UTC
## Dart analyzer terminates frequently

The Dart analyzer terminates unexpectedly and very often. 

Log example:

```
[2:19:53 PM] [Analyzer] [Info] ==> {"id":"659","method":"edit.getFixes","params":{"file":"C:\\Users\\mryds\\OneDrive\\code\\flutter\\_mr\\flexfold_demo\\lib\\app\\screens\\setup\\settings_visibility.dart","offset":0},"clientRequestTime":1600427993963}
[2:19:53 PM] [Analyzer] [Info] ==> {"id":"660","method":"edit.getAssists","params":{"file":"C:\\Users\\mryds\\OneDrive\\code\\flutter\\_mr\\flexfold_demo\\lib\\app\\screens\\setup\\settings_visibility.dart","length":0,"offset":0},"clientRequestTime":1600427993967}
[2:19:53 PM] [Analyzer] [Info] ==> {"id":"661","method":"edit.getAvailableRefactorings","params":{"file":"C:\\Users\\mryds\\OneDrive\\code\\flutter\\_mr\\flexfold_demo\\lib\\app\\screens\\setup\\settings_visibility.dart","length":0,"offset":0},"clientRequestTime":1600427993970}
[2:19:53 PM] [Analyzer] [Info] ==> {"id":"662","method":"analysis.setPriorityFiles","params":{"files":["C:\\Users\\mryds\\OneDrive\\code\\flutter\\_mr\\flexfold_demo\\lib\\app\\screens\\setup\\settings_breakpoints.dart","C:\\Users\\mryds\\OneDrive\\code\\flutter\\_mr\\flexfold_demo\\lib\\app\\screens\\setup\\settings_visibility.dart"]},"clientRequestTime":1600427993982}
[2:19:53 PM] [Analyzer] [Info] ==> {"id":"663","method":"analysis.updateContent","params":{"files":{"C:\\Users\\mryds\\OneDrive\\code\\flutter\\_mr\\flexfold_demo\\lib\\app\\screens\\setup\\settings_visibility.dart":{"edits":[{"offset":0,"length":0,"replacement":"","id":""}],"type":"change"}}},"clientRequestTime":1600427993993}
[2:19:54 PM] [General] [Error] Cannot call write after a stream was destroyed
Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
	at doWrite (_stream_writable.js:431:19)
	at writeOrBuffer (_stream_writable.js:419:5)
	at Socket.Writable.write (_stream_writable.js:309:11)
	at b.sendMessage (c:\Users\mryds\.vscode\extensions\dart-code.dart-code-3.14.1\out\dist\extension.js:1:130828)
	at b.sendMessage (c:\Users\mryds\.vscode\extensions\dart-code.dart-code-3.14.1\out\dist\extension.js:1:158470)
	at c:\Use…
[2:19:54 PM] [General] [Error] Cannot call write after a stream was destroyed
Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
	at doWrite (_stream_writable.js:431:19)
	at writeOrBuffer (_stream_writable.js:419:5)
	at Socket.Writable.write (_stream_writable.js:309:11)
	at b.sendMessage (c:\Users\mryds\.vscode\extensions\dart-code.dart-code-3.14.1\out\dist\extension.js:1:130828)
	at b.sendMessage (c:\Users\mryds\.vscode\extensions\dart-code.dart-code-3.14.1\out\dist\extension.js:1:158470)
	at c:\Use…
[2:19:54 PM] [General] [Error] Cannot call write after a stream was destroyed
Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
	at doWrite (_stream_writable.js:431:19)
	at writeOrBuffer (_stream_writable.js:419:5)
	at Socket.Writable.write (_stream_writable.js:309:11)
	at b.sendMessage (c:\Users\mryds\.vscode\extensions\dart-code.dart-code-3.14.1\out\dist\extension.js:1:130828)
	at b.sendMessage (c:\Users\mryds\.vscode\extensions\dart-code.dart-code-3.14.1\out\dist\extension.js:1:158470)
	at c:\Use…
[2:19:54 PM] [Analyzer] [Info] ==> {"id":"664","method":"analysis.updateContent","params":{"files":{"C:\\Users\\mryds\\OneDrive\\code\\flutter\\_mr\\flexfold_demo\\lib\\app\\screens\\setup\\settings_visibility.dart":{"edits":[{"offset":0,"length":0,"replacement":"","id":""}],"type":"change"}}},"clientRequestTime":1600427994014}
[2:19:54 PM] [Analyzer] [Info] ==> {"id":"665","method":"edit.getFixes","params":{"file":"C:\\Users\\mryds\\OneDrive\\code\\flutter\\_mr\\flexfold_demo\\lib\\app\\screens\\setup\\settings_visibility.dart","offset":6978},"clientRequestTime":1600427994506}
[2:19:54 PM] [Analyzer] [Info] ==> {"id":"666","method":"edit.getAssists","params":{"file":"C:\\Users\\mryds\\OneDrive\\code\\flutter\\_mr\\flexfold_demo\\lib\\app\\screens\\setup\\settings_visibility.dart","length":0,"offset":6978},"clientRequestTime":1600427994512}
[2:19:54 PM] [Analyzer] [Info] ==> {"id":"667","method":"edit.getAvailableRefactorings","params":{"file":"C:\\Users\\mryds\\OneDrive\\code\\flutter\\_mr\\flexfold_demo\\lib\\app\\screens\\setup\\settings_visibility.dart","length":0,"offset":6978},"clientRequestTime":1600427994515}

```

## Step to reproduce

This is still a place holder. I will edit and add more info later.

At the moment I'm not exactly sure when it happens, but it happens quite often, multiple times per day (or even hour). I will have to try different use cases to see if I can isolate if there is some specific condition that triggers it. It might be that it only happens when I use master channel and debug run Flutter Window builds, but since that is what I do 80% of the time, I need to check separately and see if it also happens on other (stable and beta) channels with normal device and web builds.

## Versions

 - VS Code version:
![image](https://user-images.githubusercontent.com/39990307/93592593-1b461600-f9bb-11ea-870f-058318d115f0.png)
 - Dart extension version: v3.14.1
 - Dart/Flutter SDK version: Flutter Channel master, 1.22.0-10.0.pre.202

**Comment by DanTup** [comment] 2020-09-22 06:49
Is there more in the log than you posted here? It would be useful to see further back (to see what the server last responded to - the log above only includes requests to the server that were never responded to).

Do you know of anything you may be doing around the time it happens? For example is it always shortly after running a debug session or `flutter clean`?

**Comment by DanTup** [comment] 2020-09-22 06:51
If happening after cleaning/launching a debug session, I suspect this may be https://github.com/dart-lang/sdk/issues/40348#issuecomment-689468824 which was recently re-fixed but isn't in the current stable Flutter release.

**Comment by rydmike** [comment] 2020-09-24 03:43
Sorry for the reply delay, been using "the other IDE" for a while to avoid this. :grin: 
Tomorrow I will switch to Code again with a larger project and see if I can still observe this with the latest versions of Flutter on each channel.

**Comment by DanTup** [comment] 2020-09-24 09:12
I think the beta channel will have this fix now, so you could just try with that. If it's all sorted there then it should be included in the next Flutter stable release.

**Comment by DanTup** [comment] 2020-09-24 09:13
I'll close this as I'm pretty certain this is it, but if you can still repro on beta we can reopen and dig into it. Thanks!

**Comment by rydmike** [comment] 2020-09-25 00:26
Thanks @DanTup I have been using Code again extensively today and did **not** see this issue anymore at all on Flutter dev and master channels. Closing it was a good call! 👍 

I have not dropped down to beta and stable channels today to check there too, but if the fix is not there yet, it will roll to them eventually as well. I used to live on Flutter master channel most of the time to be able to build with Windows as a target, but since yesterday I can now live a bit safer on dev channel! Hooray! 🍾 

And thanks again for this fix 💙 it was a bit frustrating as the analyzer really was terminating very frequently.

**Comment by DanTup** [comment] 2020-09-25 09:25
Great, glad to hear!

**Comment by rydmike** [comment] 2020-09-27 20:33
@DanTup 

FYI, looks like my VS-Code Dart Analyzer terminations are back, here are bunch of logs it spit out related to the analyzer has terminated error messages, multiple of them within a short time:

[dart-code-startup-log-9aa9.txt](https://github.com/Dart-Code/Dart-Code/files/5289028/dart-code-startup-log-9aa9.txt)
[log-c01d.txt](https://github.com/Dart-Code/Dart-Code/files/5289029/log-c01d.txt)
[log-8102.txt](https://github.com/Dart-Code/Dart-Code/files/5289030/log-8102.txt)
[log-3296.txt](https://github.com/Dart-Code/Dart-Code/files/5289031/log-3296.txt)
[log-273b.txt](https://github.com/Dart-Code/Dart-Code/files/5289032/log-273b.txt)
[log-ba44.txt](https://github.com/Dart-Code/Dart-Code/files/5289033/log-ba44.txt)

these just happened on Flutter Channel master, 1.22.0-10.0.pre.380.

With
![image](https://user-images.githubusercontent.com/39990307/94375067-932de200-0119-11eb-9a72-c0052595b146.png)

**Comment by DanTup** [comment] 2020-09-28 11:27
I'll see if I can repro. In the meantime, could you:

- Set the [dart.analyzerLogFile setting](https://dartcode.org/docs/logging/#analyzer) so that the analyzer is always logged. The next time you see it, grab a copy of that log file (it will be large as it'll contain all analysis server traffic, but it should include the `stderr` stream, which might include an error/stack if it's not a complete crash)
- Enable Windows crash dumps so if/when it happens again if it's a VM crash, someone on the VM team might be able to take a look (<I'll edit in instructions for this when I switch back to Windows...>)

**Comment by DanTup** [comment] 2020-09-28 13:24
I haven't been able to repro this on Windows yet using the latest Flutter master (running `flutter_gallery` on a physical Android device), so a log/crash log as mentioned above may help.

FYI @aam - this *might* be a similar issue with the watcher to discussed previously. It's Windows, and the analyzer VM appears to be crashing around the time a Flutter debug session is being started (which matches what we've seen before - the Flutter build is triggering the watchers in the analysis server and crashing).

**Comment by DanTup** [comment] 2020-10-13 07:19
Closing this as a dupe of https://github.com/Dart-Code/Dart-Code/issues/2814 / https://github.com/dart-lang/sdk/issues/40348, since I'm certain it's the same issue.

**Closed by DanTup** 2020-10-13 07:19 UTC
Labels: is bug
