### ISSUE TITLE
Default/automatic launch configs is missing/incorrect if project is nested inside a folder

### ISSUE THREAD

**Issue by trimmdavid** [Dart-Code/Dart-Code#2365] opened 2020-04-18 14:13 UTC
i keep on having this problem  : Your launch config references a program that does not exist. If you have problems launching, check the "program" field in your ".vscode/launch.json" file.

**Comment by DanTup** [comment] 2020-04-18 14:18
Can you try:

- Run the **Dart: Capture Logs** command (untick Analysis Server, but leave everything else ticked)
- Try to run your app
- Click **Cancel** on the logging prompt to stop logging and open the log file
- Attach the log file here (make sure there's nothing sensitive in it first)

Thanks!

**Comment by trimmdavid** [comment] 2020-04-18 14:27
Hello,
Thanks for the quick response, but i dont really understand what you mean
by- capture logs . I am very new to dart , i dont know much.

**Comment by DanTup** [comment] 2020-04-18 14:35
Sorry, I should've been clearer! :-)

- Open the VS Code command palette by pressing Ctrl+Shift+P (or on macOS, Cmd+Shift+P)
- Type "capture logs" to filter the command list, and select the **Dart: Capture Logs** option
- Untick **Analysis Server** (those logs aren't relevant here) and click **OK**

This will start capturing logs from the extension (a notification will be shown in the bottom right corner that they're being captured).

- Try to launch your app so that you get the original error message from above
- Click **Cancel** on the logging notification to stop logging, and open the log file
- Check the log file doesn't include anything sensitive (it may have path/filenames and other things from your project depending on how long you were capturing)
- Save the log file and attach it here

Let me know if anything isn't clear. Thanks!

**Comment by trimmdavid** [comment] 2020-04-19 07:13
Good day ,
Thanks once again for the reply ,. this is what i got


!! PLEASE REVIEW THIS LOG FOR SENSITIVE INFORMATION BEFORE SHARING !!

Dart Code extension: 3.9.1
Flutter extension: 3.9.1 (not activated)
VS Code: 1.44.2
Platform: win
Workspace type: Flutter
Multi-root?: false
Dart SDK:
    Loc: C:\flutter\bin\cache\dart-sdk
    Ver: 2.7.2
Flutter SDK:
    Loc: C:\flutter
    Ver: 1.12.13+hotfix.9
HTTP_PROXY: undefined
NO_PROXY: undefined

Sun Apr 19 2020 [14:05:24 GMT+0700 (Krasnoyarsk Standard Time)] Log file
started
[2:06:45 PM] [General] [Info] Starting debug session...
[2:06:45 PM] [General] [Info]     workspace:
C:\Users\Ekundayo\Desktop\fredses_apk
[2:06:45 PM] [General] [Info]     program  : bin/main.dart
[2:06:45 PM] [General] [Info] Converted program to absolute path:
C:\Users\Ekundayo\Desktop\fredses_apk\bin\main.dart
[2:06:45 PM] [General] [Info] Using workspace as cwd:
C:\Users\Ekundayo\Desktop\fredses_apk
[2:06:45 PM] [General] [Warn] Launch config references non-existant file
C:\Users\Ekundayo\Desktop\fredses_apk\bin\main.dart
[2:06:45 PM] [General] [Info] Detected launch project as Dart
[2:06:45 PM] [General] [Info] Using Dart debug adapter for this session
[2:06:45 PM] [General] [Info] Checking for errors before launching
[2:06:45 PM] [General] [Info] Debug session starting...
    {
        "name": "Dart",
        "program":
"C:\\Users\\Ekundayo\\Desktop\\fredses_apk\\bin\\main.dart",
        "request": "launch",
        "type": "dart",
        "cwd": "C:\\Users\\Ekundayo\\Desktop\\fredses_apk",
        "toolEnv": {
            "FLUTTER_HOST": "VSCode",
            "PUB_ENVIRONMENT": "vscode.dart-code"
        },
        "sendLogsToClient": true,
        "globalFlutterArgs": [],
        "args": [],
        "vmAdditionalArgs": [],
        "vmServicePort": 0,
        "dartPath": "C:\\flutter\\bin\\cache\\dart-sdk\\bin\\dart.exe",
        "maxLogLineLength": 2000,
        "pubPath": "C:\\flutter\\bin\\cache\\dart-sdk\\bin\\pub.bat",
        "pubSnapshotPath":
"C:\\flutter\\bin\\cache\\dart-sdk\\bin\\snapshots\\pub.dart.snapshot",
        "debugSdkLibraries": false,
        "debugExternalLibraries": true,
        "showDartDeveloperLogs": true,
        "useFlutterStructuredErrors": true,
        "debuggerHandlesPathsEverywhereForBreakpoints": true,
        "evaluateGettersInDebugViews": true,
        "previewToStringInDebugViews": false,
        "useWriteServiceInfo": true,
        "debugServer": 60045,
        "debuggerType": 0
    }
[2:06:46 PM] [Observatory] [Info] [Dart] Spawning
C:\flutter\bin\cache\dart-sdk\bin\dart.exe with args
["--enable-vm-service=0","--pause_isolates_on_start=true","--write-service-info=file:///C:/Users/Ekundayo/AppData/Local/Temp/dart-vm-service-566e.json","-DSILENT_OBSERVATORY=true","--enable-asserts","bin\\main.dart"]
[2:06:46 PM] [Observatory] [Info] [Dart] ..  in
C:\Users\Ekundayo\Desktop\fredses_apk
[2:06:46 PM] [Observatory] [Info] [Dart]     PID: 12144
[2:06:51 PM] [Observatory] [Info] [Dart] Initialising debugger for ws://
127.0.0.1:65512/Ay03k8HCkVs=/ws
[2:06:51 PM] [Observatory] [Info] [Dart] Connecting to VM Service at ws://
127.0.0.1:65512/Ay03k8HCkVs=/ws
[2:06:52 PM] [Observatory] [Info] [Dart] ==>
{"id":"0","method":"getVersion"}
[2:06:53 PM] [Observatory] [Info] [Dart] <== {"jsonrpc":"2.0",
"result":{"type":"Version","major":3,"minor":28,"_privateMajor":0,"_privateMinor":0},"id":"0"}
[2:06:53 PM] [Observatory] [Info] [Dart] ==> {"id":"1","method":"getVM"}
[2:06:53 PM] [Observatory] [Info] [Dart] <== {"jsonrpc":"2.0",
"result":{"type":"VM","name":"vm","architectureBits":64,"hostCPU":"
Intel(R) Core(TM) i5-3230M CPU @
2.60GHz","operatingSystem":"windows","targetCPU":"x64","version":"2.7.2
(Mon Mar 23 22:11:27 2020 +0100) on
\"windows_x64\"","_profilerMode":"Dart","_nativeZoneMemoryUsage":0,"pid":16452,"startTime":1587280009406,"_embedder":"Dart
VM","_maxRSS":196661248,"_currentRSS":196657152,"isolates":[{"type":"@Isolate","id":"isolates\/315640367711283","name":"main","number":"315640367711283"}],"isolateGroups":[{"type":"@IsolateGroup","id":"isolateGroups\/3151245658533916060","name":"isolate_group","number":"3151245658533916060"},{"type":"@IsolateGroup","id":"isolateGroups\/5036809515278577970","name":"isolate_group","number":"5036809515278577970"},{"type":"@IsolateGroup","id":"isolateGroups\/11525209995569407607","name":"isolate_group","number":"11525209995569407607"},{"type":"@IsolateGroup","id":"isolateGroups\/9388559274354461664","name":"isolate_group","number":"9388559274354461664"}]},"id":"1"}
[2:06:53 PM] [Observatory] [Info] [Dart] ==>
{"id":"2","method":"streamListen","params":{"streamId":"Isolate"}}
[2:06:53 PM] [Observatory] [Info] [Dart] ==>
{"id":"3","method":"streamListen","params":{"streamId":"Extension"}}
[2:06:53 PM] [Observatory] [Info] [Dart] ==>
{"id":"4","method":"streamListen","params":{"streamId":"Debug"}}
[2:06:53 PM] [Observatory] [Info] [Dart] ==>
{"id":"5","method":"streamListen","params":{"streamId":"Service"}}
[2:06:53 PM] [Observatory] [Info] [Dart] ==>
{"id":"6","method":"streamListen","params":{"streamId":"Logging"}}
[2:06:53 PM] [Observatory] [Info] [Dart] ==>
{"id":"7","method":"getIsolate","params":{"isolateId":"isolates/315640367711283"}}
[2:06:53 PM] [Observatory] [Info] [Dart] <==
{"jsonrpc":"2.0","id":"2","result":{"type":"Success"}}
[2:06:53 PM] [Observatory] [Info] [Dart] <==
{"jsonrpc":"2.0","id":"3","result":{"type":"Success"}}
[2:06:53 PM] [Observatory] [Info] [Dart] <==
{"jsonrpc":"2.0","id":"4","result":{"type":"Success"}}
[2:06:53 PM] [Observatory] [Info] [Dart] <==
{"jsonrpc":"2.0","id":"5","result":{"type":"Success"}}
[2:06:53 PM] [Observatory] [Info] [Dart] <==
{"jsonrpc":"2.0","id":"6","result":{"type":"Success"}}
[2:06:54 PM] [Observatory] [Info] [Dart] <==
{"jsonrpc":"2.0","method":"streamNotify","params":{"streamId":"Isolate","event":{"type":"Event","kind":"IsolateExit","isolate":{"type":"@Isolate","id":"isolates\/315640367711283","name":"main","number":"315640367711283"},"timestamp":1587280014117}}}
[2:06:54 PM] [Observatory] [Info] [Dart] Observatory connection closed:
1005 ()
[2:06:59 PM] [Observatory] [Info] [Dart] Disconnect requested!
[2:06:59 PM] [Observatory] [Info] [Dart] TERM: Requested to terminate with
SIGINT...
[2:06:59 PM] [Observatory] [Info] [Dart] TERM: Terminating processes...
[2:06:59 PM] [Observatory] [Info] [Dart] TERM: Terminating related process
16452 with SIGINT...
[2:06:59 PM] [Observatory] [Info] [Dart] TERM: Terminating main process
with SIGINT...
[2:06:59 PM] [Observatory] [Info] [Dart] TERM: Removing all stored data...
[2:06:59 PM] [Observatory] [Info] [Dart] TERM: Waiting for process to
finish...
[2:06:59 PM] [Observatory] [Info] [Dart] Process exited (1)
[2:06:59 PM] [Observatory] [Info] [Dart] TERM: Disconnecting...
[2:06:59 PM] [General] [Info] Debugger:SessionDuration timing: 13365ms
(Dart)
[2:07:07 PM] [General] [Info] Starting debug session...
[2:07:07 PM] [General] [Info]     workspace:
C:\Users\Ekundayo\Desktop\fredses_apk
[2:07:07 PM] [General] [Info]     program  : bin/main.dart
[2:07:07 PM] [General] [Info] Converted program to absolute path:
C:\Users\Ekundayo\Desktop\fredses_apk\bin\main.dart
[2:07:07 PM] [General] [Info] Using workspace as cwd:
C:\Users\Ekundayo\Desktop\fredses_apk
[2:07:07 PM] [General] [Warn] Launch config references non-existant file
C:\Users\Ekundayo\Desktop\fredses_apk\bin\main.dart
[2:07:07 PM] [General] [Info] Detected launch project as Dart
[2:07:07 PM] [General] [Info] Using Dart debug adapter for this session
[2:07:07 PM] [General] [Info] Checking for errors before launching
[2:07:07 PM] [General] [Info] Debug session starting...
    {
        "name": "Dart",
        "program":
"C:\\Users\\Ekundayo\\Desktop\\fredses_apk\\bin\\main.dart",
        "request": "launch",
        "type": "dart",
        "cwd": "C:\\Users\\Ekundayo\\Desktop\\fredses_apk",
        "toolEnv": {
            "FLUTTER_HOST": "VSCode",
            "PUB_ENVIRONMENT": "vscode.dart-code"
        },
        "sendLogsToClient": true,
        "globalFlutterArgs": [],
        "args": [],
        "vmAdditionalArgs": [],
        "vmServicePort": 0,
        "dartPath": "C:\\flutter\\bin\\cache\\dart-sdk\\bin\\dart.exe",
        "maxLogLineLength": 2000,
        "pubPath": "C:\\flutter\\bin\\cache\\dart-sdk\\bin\\pub.bat",
        "pubSnapshotPath":
"C:\\flutter\\bin\\cache\\dart-sdk\\bin\\snapshots\\pub.dart.snapshot",
        "debugSdkLibraries": false,
        "debugExternalLibraries": true,
        "showDartDeveloperLogs": true,
        "useFlutterStructuredErrors": true,
        "debuggerHandlesPathsEverywhereForBreakpoints": true,
        "evaluateGettersInDebugViews": true,
        "previewToStringInDebugViews": false,
        "useWriteServiceInfo": true,
        "debugServer": 60045,
        "debuggerType": 0
    }
[2:07:08 PM] [Observatory] [Info] [Dart] Spawning
C:\flutter\bin\cache\dart-sdk\bin\dart.exe with args
["--enable-vm-service=0","--pause_isolates_on_start=true","--write-service-info=file:///C:/Users/Ekundayo/AppData/Local/Temp/dart-vm-service-5405.json","-DSILENT_OBSERVATORY=true","--enable-asserts","bin\\main.dart"]
[2:07:08 PM] [Observatory] [Info] [Dart] ..  in
C:\Users\Ekundayo\Desktop\fredses_apk
[2:07:08 PM] [Observatory] [Info] [Dart]     PID: 18016
[2:07:10 PM] [Observatory] [Info] [Dart] Initialising debugger for ws://
127.0.0.1:49152/a37dOWildik=/ws
[2:07:10 PM] [Observatory] [Info] [Dart] Connecting to VM Service at ws://
127.0.0.1:49152/a37dOWildik=/ws
[2:07:11 PM] [Observatory] [Info] [Dart] ==>
{"id":"0","method":"getVersion"}
[2:07:11 PM] [Observatory] [Info] [Dart] <== {"jsonrpc":"2.0",
"result":{"type":"Version","major":3,"minor":28,"_privateMajor":0,"_privateMinor":0},"id":"0"}
[2:07:11 PM] [Observatory] [Info] [Dart] ==> {"id":"1","method":"getVM"}
[2:07:11 PM] [Observatory] [Info] [Dart] <== {"jsonrpc":"2.0",
"result":{"type":"VM","name":"vm","architectureBits":64,"hostCPU":"
Intel(R) Core(TM) i5-3230M CPU @
2.60GHz","operatingSystem":"windows","targetCPU":"x64","version":"2.7.2
(Mon Mar 23 22:11:27 2020 +0100) on
\"windows_x64\"","_profilerMode":"Dart","_nativeZoneMemoryUsage":0,"pid":11208,"startTime":1587280028593,"_embedder":"Dart
VM","_maxRSS":204513280,"_currentRSS":204509184,"isolates":[{"type":"@Isolate","id":"isolates\/1767369391692067","name":"main","number":"1767369391692067"}],"isolateGroups":[{"type":"@IsolateGroup","id":"isolateGroups\/17152143887431477114","name":"isolate_group","number":"17152143887431477114"},{"type":"@IsolateGroup","id":"isolateGroups\/368378634050564530","name":"isolate_group","number":"368378634050564530"},{"type":"@IsolateGroup","id":"isolateGroups\/10628802018320681979","name":"isolate_group","number":"10628802018320681979"},{"type":"@IsolateGroup","id":"isolateGroups\/4116673186035954439","name":"isolate_group","number":"4116673186035954439"}]},"id":"1"}
[2:07:11 PM] [Observatory] [Info] [Dart] ==>
{"id":"2","method":"streamListen","params":{"streamId":"Isolate"}}
[2:07:11 PM] [Observatory] [Info] [Dart] ==>
{"id":"3","method":"streamListen","params":{"streamId":"Extension"}}
[2:07:11 PM] [Observatory] [Info] [Dart] ==>
{"id":"4","method":"streamListen","params":{"streamId":"Debug"}}
[2:07:11 PM] [Observatory] [Info] [Dart] ==>
{"id":"5","method":"streamListen","params":{"streamId":"Service"}}
[2:07:11 PM] [Observatory] [Info] [Dart] ==>
{"id":"6","method":"streamListen","params":{"streamId":"Logging"}}
[2:07:11 PM] [Observatory] [Info] [Dart] ==>
{"id":"7","method":"getIsolate","params":{"isolateId":"isolates/1767369391692067"}}
[2:07:11 PM] [Observatory] [Info] [Dart] <==
{"jsonrpc":"2.0","id":"2","result":{"type":"Success"}}
[2:07:11 PM] [Observatory] [Info] [Dart] <==
{"jsonrpc":"2.0","id":"3","result":{"type":"Success"}}
[2:07:11 PM] [Observatory] [Info] [Dart] <==
{"jsonrpc":"2.0","id":"4","result":{"type":"Success"}}
[2:07:11 PM] [Observatory] [Info] [Dart] <==
{"jsonrpc":"2.0","id":"5","result":{"type":"Success"}}
[2:07:11 PM] [Observatory] [Info] [Dart] <==
{"jsonrpc":"2.0","id":"6","result":{"type":"Success"}}
[2:07:12 PM] [Observatory] [Info] [Dart] <==
{"jsonrpc":"2.0","method":"streamNotify","params":{"streamId":"Isolate","event":{"type":"Event","kind":"IsolateExit","isolate":{"type":"@Isolate","id":"isolates\/1767369391692067","name":"main","number":"1767369391692067"},"timestamp":1587280032444}}}
[2:07:12 PM] [Observatory] [Info] [Dart] Observatory connection closed:
1005 ()
[2:07:17 PM] [Observatory] [Info] [Dart] Disconnect requested!
[2:07:17 PM] [Observatory] [Info] [Dart] TERM: Requested to terminate with
SIGINT...
[2:07:17 PM] [Observatory] [Info] [Dart] TERM: Terminating processes...
[2:07:17 PM] [Observatory] [Info] [Dart] TERM: Terminating related process
11208 with SIGINT...
[2:07:17 PM] [Observatory] [Info] [Dart] TERM: Terminating main process
with SIGINT...
[2:07:17 PM] [Observatory] [Info] [Dart] TERM: Removing all stored data...
[2:07:17 PM] [Observatory] [Info] [Dart] TERM: Waiting for process to
finish...
[2:07:17 PM] [Observatory] [Info] [Dart] Process exited (1)
[2:07:17 PM] [Observatory] [Info] [Dart] TERM: Disconnecting...
[2:07:17 PM] [General] [Info] Debugger:SessionDuration timing: 9451ms (Dart)
Sun Apr 19 2020 [14:08:31 GMT+0700 (Krasnoyarsk Standard Time)] Log file
ended

**Comment by DanTup** [comment] 2020-04-19 07:54
It looks like in your `.vscode/launch.json` file, you have:

```
"program":"bin/main.dart"
```

However this file doesn't exist in your project. If it's a Flutter project, this should be `"lib/main.dart"`(or, if you've not customised the launch.json, you can just delete the file altogether).

I'm not sure how you ended up with this file with the wrong value though - `bin/main.dart` is the default value for a (non-Flutter) Dart project. Did you create this file and select the "Dart" template, or has it been created automatically?

**Comment by trimmdavid** [comment] 2020-05-06 09:07
Good day, I',m back with almost same problem. I cant debug, its saying
Your launch config references a program that does not exist. If you have
problems launching, check the "program" field in your ".vscode/launch.json"
file.

**Comment by DanTup** [comment] 2020-05-06 09:39
@trimmdavid this happens if your launch.json has a `program` field that is not on your disk. Please capture a log by:

- Run the **Dart: Capture Logs** command
- Leave everything ticked and click OK
- Try to start your app so that the error appears
- Click **Cancel** on the logging notification to stop logging, and open the log file
- Copy the log file here

Thanks!

**Comment by muhammad-hamza-shahid** [comment] 2020-05-15 12:44
Hi Dan unluckily I am also facing the same problem, every thing was going fine and suddenly it stopped working and this alert started to appear at bottom right corner of my screen saying 

"Your launch config references a program that does not exist. If you have problems launching, check the "program" field in your ".vscode/launch.json" file."

 kindly help me out in this problem.

**Comment by muhammad-hamza-shahid** [comment] 2020-05-15 14:55
The above problem is solved, actually I keep on tracking with github so I have the previous working commit of this project, when I checked that out this line:

"program":"bin/main.dart" 

It was not their and I didn't made any changes in this file aswell, so I deleted this line and and saved my project and when I reopened it every thing worked fine again like it was working before this error. 
Remember I have tried this thing before but I was not closing the editor but when I restarted my editor this alert went of and it started working fine again.

**Comment by fabiansalamo** [comment] 2020-05-31 16:51
Hello, I had this isuue. I solved it by deleting the launch.js file and creating a new config using vs code.

**Comment by DanTup** [comment] 2020-06-01 08:23
You shouldn't really need a launch.json for simple cases, it should just work without. Some actions in VS Code will trigger creation of a `launch.json` though. If anyone can reproduce a situation where a `launch.json` is created and populated incorrectly with `bin/main.dart` (which is the default for a Dart project, but not Flutter), please let me know!

**Comment by Ell28** [comment] 2020-06-03 07:37
If there are other projects/folders on your vscode workspace, check and correct their ".vscode/launch.json" file configs. Or just remove those projects from the workspace.

**Comment by jaerts** [comment] 2020-07-01 07:50
Thanks,  deleting the launch.js file and without creating a new config solved my debug/run problem.
The problem started after a flutter and dart update.

**Comment by DanTup** [comment] 2020-07-01 11:05
It sounds like a `launch.json` is being created automatically with incorrect values in it. If anyone is able to reproduce this (and figure out exactly what they did that triggered this - it might be pressing F5 with certain files open, or when the open folder in VS Code is not directly the project root, etc.), please let me know so I can try to get to the bottom of this. Thanks!

**Comment by danielbee** [comment] 2020-07-31 10:13
Hi Dan, 
I ran into this and think i now know reproduceable steps. 
It comes down to the workspace the user has in vscode. 
**If the user's root folder is their flutter project, the flow works as expected.** 
As seen here:
![image](https://user-images.githubusercontent.com/25937879/89022693-552f6000-d31a-11ea-8683-c80e9a6f3e6d.png)
This is what i see when i hit F5 on a main.dart without a launch.json, with a workspace that has flutter project as the root folder. 

I know that I have an issue which necessitates the use of args on flutter run, which is why i get refused to connect. 
            `"args": ["--web-port", "8080", "--web-hostname","127.0.0.1"]`
As an aside, it took me so long to find that out. This should be a check in flutter doctor. 

If a user, like me, encounters an issue, a natural thing to do would be to hit that glowing orange settings cog in order to 
> Configure or Fix launch.Json

I do this and select flutter and dart environment. 
It creates a launch.json, but doesn't have the 'program' field in there. 


however, if the user is in a larger workspace, when we create the launch.json after hitting F5 from our main.dart followed by the Cog icon; we get the following contents:
```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Dart",
            "program": "bin/main.dart",
            "request": "launch",
            "type": "dart"
        }
    ]
}
```

Compare this to the 'working' in the less complicated directory structure. 
```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Flutter",
            "request": "launch",
            "type": "dart"
        }
    ]
}
```
Note, there's actually a "name" change too.. 

You've previously mentioned that in a larger workspace, there can be multiple flutter projects, so the flow that creates the launch.json doesn't know where to go. 

I see multiple solutions here (without understanding diffculty to implement.)
- I hit F5 from the main.dart i actually care about. There should be awareness to have this context create a launch.json for that specific file, ie `"program" : "{$workspace_root}/path/to/file/i/just/tried/to/run/main.dart" `
- Ensure that there's a comment on creation: 
`            "program": "bin/main.dart", // Please change this to a path to your main.dart from the workspace root folder`
- Or simply scan through the entire workspace and create multiple launch configs, one for each flutter project. Each config should have a name "Flutter_<flutter_proj_name>"
- A new CTRL+P option to "Debug from this flutter project", which sets up launch.json.
- Or all of the above. 

I don't use multi-root workspaces, which I think you've mentioned can work.

Let me know if this makes sense and you can also reproduce it.

**Comment by DanTup** [comment] 2020-08-03 13:36
> I know that I have an issue which necessitates the use of args on flutter run, which is why i get refused to connect.
> `"args": ["--web-port", "8080", "--web-hostname","127.0.0.1"]`
> As an aside, it took me so long to find that out. This should be a check in flutter doctor.

I'm not sure why using those args would cause this error - please file a bug about that, I believe that should still "just work".

> however, if the user is in a larger workspace, when we create the launch.json after hitting F5 from our main.dart followed by the Cog icon; we get the following contents:

Ah, interesting. Can you confirm what your workspace looks like? Have you opened a folder that contains multiple projects, or is it a multi-root workspace with multiple projects?

> I hit `F5` from the main.dart i actually care about. There should be awareness to have this context create a launch.json for that specific file, ie "program" : "{$workspace_root}/path/to/file/i/just/tried/to/run/main.dart"

Generally if we can infer the file, I'd prefer *not* to create a `launch.json` at all. It should only be created when you need to customise something (or want to force a specific `program` regardless of the open file/project).

> A new CTRL+P option to "Debug from this flutter project", which sets up launch.json.

I think this might now be covered by the [automatic launch configs](https://dartcode.org/releases/v3-13/#improved-debug-discoverability)?

**Comment by DanTup** [comment] 2020-08-03 13:42
@danielbee I tried to reproduce what's in your screenshot above, but when I don't have a `launch.json` the debug side bar shows this welcome view:

<img width="463" alt="Screenshot 2020-08-03 at 14 41 14" src="https://user-images.githubusercontent.com/1078012/89189116-73ee5a80-d597-11ea-9cf0-36ab2bec98c1.png">

How did you get to the the dropdown/cog icon you have without a launch.json?

**Comment by danielbee** [comment] 2020-08-04 18:13
Hi @DanTup, 
Many thanks for getting back to me. 

My workspace is set-up like this: (A single folder with multiple projects in sub-directories - Compera_app and compera_test are both flutter projects)
![image](https://user-images.githubusercontent.com/25937879/89328194-eb4de800-d684-11ea-9bba-21b559cac9cf.png)

**After** I hit F5 from my main.dart, i see the following: 
![image](https://user-images.githubusercontent.com/25937879/89328306-1cc6b380-d685-11ea-866b-f77123e806c9.png)

Note, I only see the cog after I have hit F5, and during debug. As soon as I close the chrome window or stop (Shift + F5) the application, The debugging screen reverts to what you've shown. 



> I'm not sure why using those args would cause this error - please file a bug about that, I believe that should still "just work".

Apologies, the opposite is true. **Without** those args, i get refused to connect. I think my laptop has some organisation/firewall that restricts connections through specific ports. When i don't force the port to be a specific value, dart seems to just give a random port, which doesn't work for me. 



> Generally if we can infer the file, I'd prefer _not_ to create a `launch.json` at all. It should only be created when you need to customise something (or want to force a specific `program` regardless of the open file/project).

When I am given the option to create the launch.json (with the cog shown), i'm already in a debug of a running project; so i'd expect the launch.json to map the program field to the application that is currently being run. 

I agree that ideally, we don't need any launch.json. However, In my instance i **need** to create one to work around organisation security and provide launch-specific args.

**Comment by danielbee** [comment] 2020-08-04 18:29
> > A new CTRL+P option to "Debug from this flutter project", which sets up launch.json.
> 
> I think this might now be covered by the [automatic launch configs](https://dartcode.org/releases/v3-13/#improved-debug-discoverability)?

I think this part is what is at fault. 
![image](https://user-images.githubusercontent.com/25937879/89330586-649b0a00-d688-11ea-83e5-b3e3dd4a737d.png)
If I click 'Create a launch.json file' then I get a launch.json that has the error: 
```
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Dart",
            "program": "bin/main.dart",
            "request": "launch",
            "type": "dart"
        }
    ]
}
```

If I click show all automatic debug configs: 
![image](https://user-images.githubusercontent.com/25937879/89330747-9f9d3d80-d688-11ea-9203-654286ae98dd.png)
Then after clicking dart & flutter:
![image](https://user-images.githubusercontent.com/25937879/89330845-be033900-d688-11ea-8b4e-4d78143cee6e.png)
There are no configurations listed.

**Comment by DanTup** [comment] 2020-08-05 09:32
> My workspace is set-up like this: 

Thanks - I can repro. The issue here is that your Flutter project is in a sub-folder, so when VS code asks us for the `launch.json` contents, it's not clear what we should provide (the root folder is neither a Dart or Flutter project). While we could scan the workspace in this case and find your Flutter project, it's also possible we'd find multiple projects. If we return multiple configs here, VS Code would add *all* of them to the file.

I'll see if maybe we can take some hints from the current open file, so at least in the case where there's an open file (like in your screenshot) we should find something.

> Apologies, the opposite is true. Without those args, i get refused to connect. I think my laptop has some organisation/firewall that restricts connections through specific ports. When i don't force the port to be a specific value, dart seems to just give a random port, which doesn't work for me.

Ah, got it. That makes sense now!

**Comment by DanTup** [comment] 2020-08-05 10:28
Ok, I think I've come up with a reasonable solution for this. For the "Create launch.config", we'll now locate the project roots and create a launch config for each one. In the example above there was only one, but here's an example where the folder had a Dart project and two Flutter projects in it:

![Screenshot 2020-08-05 at 11 26 04](https://user-images.githubusercontent.com/1078012/89402379-a8d0ed80-d70e-11ea-8de7-8764ccf575e4.png)

Similarly, for the "Automatic launch configs" we'll now scan each of those project roots, rather than just the main workspace root and also include options for Dart web and Test:

![Screenshot 2020-08-05 at 11 25 54](https://user-images.githubusercontent.com/1078012/89402433-bbe3bd80-d70e-11ea-839d-bc2b7ea1af9f.png)

**Closed** 2020-08-05 10:29 UTC
Labels: in debugger, in flutter, is bug

**Comment by erayhamurlu** [comment] 2021-04-01 05:39
Go .vscode folder open launch.json and
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "projectname",
            "request": "launch",
            "type": "dart"
        }
    ]
}

**Comment by ranadhaval123** [comment] 2021-04-19 10:04
> Can you try:
> 
> * Run the **Dart: Capture Logs** command (untick Analysis Server, but leave everything else ticked)
> * Try to run your app
> * Click **Cancel** on the logging prompt to stop logging and open the log file
> * Attach the log file here (make sure there's nothing sensitive in it first)
> 
> Thanks!



> @trimmdavid this happens if your launch.json has a `program` field that is not on your disk. Please capture a log by:
> 
> * Run the **Dart: Capture Logs** command
> * Leave everything ticked and click OK
> * Try to start your app so that the error appears
> * Click **Cancel** on the logging notification to stop logging, and open the log file
> * Copy the log file here
> 
> Thanks!

![flutter error](https://user-images.githubusercontent.com/82793313/115218767-84923100-a124-11eb-8934-8e89fbe5653b.jpg)
sir i am facing problem in which  configuration "flutter_first_application" launch.jason missing

**Comment by DanTup** [comment] 2021-04-19 17:55
@ranadhaval123 please file a new issue, and include the exact steps that led you to that error. Thanks!

**Comment by Azurik52** [comment] 2024-08-31 07:51
if any of the solutions above didn't help, try to change launch program config like this.
```
"program" : "Users/smth/your/way/to/file"
```  
Only this helped me
