### ISSUE TITLE
Hot Restart doesn't resume debugger state vol. 2

### ISSUE THREAD

**Issue by szotp** [Dart-Code/Dart-Code#2345] opened 2020-04-10 06:26 UTC
Related: #1994

Hot restarts hangs and requires cold restart if debugger is paused on one breakpoint and there is another breakpoint later in the execution path. I have discovered this when debugging itemBuilder in flutter, but here is a minimal example:

```dart
import 'package:flutter/material.dart';

void main() {
  foo();
  foo();
  runApp(SizedBox());
}

void foo() {
  // put breakpoint here
  print('foo');
}
```
Reproduction:
1. Open the example in VSCode
2. Put breakpoint on the print.
3. Run app (I used iOS simulator
4. Wait until breakpoint is reached.
5. Press hot restart.

Expected:
Hot restart is performed, breakpoint reached again.

Got:
hot restart freezes, pressing hot restart does nothing, cold restart is required.
Note: Does not happen 100% of the time - I suspect that adding more foo() calls would guarantee it.

If you put a breakpoint where the comment is, you would have normally two break events that require continuuing. If you attempt a restart while paused in the first event, the restart will hang. Presumably pressing hot restart automatically continues current breakpoint, but doesn't check if there is another breakpoint to be reached. Maybe it would be enough to internally detach breakpoints before restart and attach them afterwards.

Tested on stable
```
[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Mac OS X 10.15.2 19C57, locale en-GB)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
[!] Android Studio (version 3.6)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.44.0)
[✓] Connected device (1 available)
```

And master
```
[✓] Flutter (Channel master, v1.18.0-5.0.pre.46, on Mac OS X 10.15.2 19C57, locale en-GB)
```

I could not reproduce this in pure dart.

**Comment by DanTup** [comment] 2020-04-13 10:18
@jonahwilliams @bkonyi not sure where this is going wrong, but it seems like the VM never responds to the `getStack` requests here when it hits the breakpoint after the restart:

```
[10:57:32 AM] [FlutterRun] ==> [{"id":"1","method":"app.restart","params":{"appId":"c9084463-0518-4ea3-b7b2-039c64735b96","fullRestart":true,"pause":true,"reason":"manual"}}]
[10:57:32 AM] [FlutterRun] <== [{"event":"app.progress","params":{"appId":"c9084463-0518-4ea3-b7b2-039c64735b96","id":"2","progressId":"hot.restart","message":"Performing hot restart..."}}]
[10:57:32 AM] [FlutterRun] <== [{"event":"app.progress","params":{"appId":"c9084463-0518-4ea3-b7b2-039c64735b96","id":"3","progressId":null,"message":"Syncing files to device iPhone 11 Pro Max..."}}]
[10:57:33 AM] [FlutterRun] <== [{"event":"app.progress","params":{"appId":"c9084463-0518-4ea3-b7b2-039c64735b96","id":"3","progressId":null,"finished":true}}]
[10:57:33 AM] [Observatory] <== {"jsonrpc":"2.0","method":"streamNotify","params":{"streamId":"Debug","event":{"type":"Event","kind":"Resume","isolate":{"type":"@Isolate","id":"isolates\/1932830368228639","name":"main","number":"1932830368228639"},"timestamp":1586771853521,"topFrame":{"type":"Frame","kind":"Regular","location":{"type":"SourceLocation","script":{"type":"@Script","fixedId":true,"id":"libraries\/@493193931\/scripts\/package%3Atest_breakpoint_hot_restart%2Fmain.dart\/17172f8be2c","uri":"package:test_breakpoint_hot_restart\/main.dart","_kind":"kernel"},"tokenPos":138},"function":{"type":"@Function","fixedId":true,"id":"classes\/4072\/functions\/foo","name":"foo","owner":{"type":"@Library","fixedId":true,"id":"libraries\/@493193931","name":"","uri":"package:test_breakpoint_hot_restart\/main.dart"},"_kind":"RegularFunction","static":true,"const":false,"_intrinsic":false,"_native":false},"code":{"type":"@Code","fixedId":true,"id":"code\/22be98de5-1090b2990","name":"[Unoptimized] foo","kind":"Dart","_optimized":false,"_intrinsic":false,"_native":false},"vars":[],"index":0}}}}
[10:57:33 AM] [Observatory] <== {"jsonrpc":"2.0","method":"streamNotify","params":{"streamId":"Debug","event":{"type":"Event","kind":"PauseBreakpoint","isolate":{"type":"@Isolate","id":"isolates\/1932830368228639","name":"main","number":"1932830368228639"},"timestamp":1586771853523,"pauseBreakpoints":[{"type":"Breakpoint","fixedId":true,"id":"breakpoints\/1","breakpointNumber":1,"resolved":true,"location":{"type":"SourceLocation","script":{"type":"@Script","fixedId":true,"id":"libraries\/@493193931\/scripts\/package%3Atest_breakpoint_hot_restart%2Fmain.dart\/17172f8be2c","uri":"package:test_breakpoint_hot_restart\/main.dart","_kind":"kernel"},"tokenPos":138}}],"topFrame":{"type":"Frame","kind":"Regular","location":{"type":"SourceLocation","script":{"type":"@Script","fixedId":true,"id":"libraries\/@493193931\/scripts\/package%3Atest_breakpoint_hot_restart%2Fmain.dart\/17172f8be2c","uri":"package:test_breakpoint_hot_restart\/main.dart","_kind":"kernel"},"tokenPos":138},"function":{"type":"@Function","fixedId":true,"id":"classes\/4072\/functions\/foo","name":"foo","owner":{"type":"@Library","fixedId":true,"id":"libraries\/@493193931","name":"","uri":"package:test_breakpoint_hot_restart\/main.dart"},"_kind":"RegularFunction","static":true,"const":false,"_intrinsic":false,"_native":false},"code":{"type":"@Code","fixedId":true,"id":"code\/22be98de5-1090b2990","name":"[Unoptimized] foo","kind":"Dart","_optimized":false,"_intrinsic":false,"_native":false},"vars":[],"index":0}}}}
[10:57:33 AM] [FlutterRun] <== flutter: foo
[10:57:33 AM] [Observatory] ==> {"id":"512","method":"getStack","params":{"isolateId":"isolates/1932830368228639"}}
[10:57:33 AM] [Observatory] ==> {"id":"513","method":"getStack","params":{"isolateId":"isolates/1932830368228639"}}

// (no responses here so VS Code sits waiting and doesn't update the UI correctly)
```

Is this likely a Dart issue or a Flutter issue?

**Comment by DanTup** [comment] 2020-05-20 11:20
> Remove the stale label or

> github-actions bot added stale and removed stale labels 34 minutes ago

🤔

**Comment by bkonyi** [comment] 2020-05-27 21:44
Sorry for the delay on this Danny, must have gotten buried in my inbox. Is this still something we're seeing?

**Comment by DanTup** [comment] 2020-05-28 09:01
@bkonyi no probs! (the comment above wasn't at you, it was the weird behaviour of the bot 😄)

But yes, we still see this using the most recent master. Note that the breakpoints are before `runApp` so I'm not surprised that hot *reload* wouldn't work, but in this case it's hot *restart* that's failing too.

**Comment by szotp** [comment] 2020-07-08 06:28
This is a very annoying problem, would be nice to fix it instead of ignoring.

**Comment by DanTup** [comment] 2020-07-08 11:48
Sorry, this shouldn't have been closed - I left a tag on it and hadn't caught up with my notifications since it was closed.

@bkonyi I re-tested this on latest master today and it still repros. I think this "Loading..." here in Android Studio is the same thing there too:

<img width="342" alt="Screenshot 2020-07-08 at 12 47 14" src="https://user-images.githubusercontent.com/1078012/86915065-42f64380-c119-11ea-84ea-2bab0dc805f3.png">

**Comment by bkonyi** [comment] 2020-07-16 17:59
Sorry for the delay on this, I've been pretty swamped lately. I'll see if I can take a look tomorrow / early next week.

**Comment by bkonyi** [comment] 2020-07-20 22:38
Confirmed I can reproduce, even using Observatory, so this doesn't appear to the a Dart Code issue. I've filed an issue against Flutter to track this there.

**Comment by DanTup** [comment] 2020-07-21 07:49
Thanks, I'll close this in favour of https://github.com/flutter/flutter/issues/61906 then.

**Closed by DanTup** 2020-07-21 07:49 UTC
Labels: upstream in dart / flutter
