### ISSUE TITLE
I have just created one project in VS studio for flutter, and i'm getting error

### ISSUE THREAD

**Issue by MohiniThakkar1995** [Dart-Code/Dart-Code#2977] opened 2020-12-03 10:01 UTC

**Comment by DanTup** [comment] 2020-12-03 10:03
Can you provide more details of the error you're seeing (perhaps a screenshot)?

**Comment by DanTup** [comment] 2020-12-03 10:05
Presumably a dupe of #2978.

**Closed by DanTup** 2020-12-03 10:05 UTC
Labels: awaiting info
