### ISSUE TITLE
Flutter inspector widget tree shows only the root element when debugging through VS Code

### ISSUE THREAD

**Issue by jlvlg** [Dart-Code/Dart-Code#4172] opened 2022-09-23 08:48 UTC
Whenever I try to debug a flutter project through VS Code built-in debugger and I open the flutter DevTools, the widget tree inspector shows only the root element, no matter how many components there are in my app.
It works normally when using IntelliJ or when running "flutter run" through the command line.

1. flutter create bug
2. flutter pub get
3. Open project on VS Code
4. Press F5 or manually run VS Code debugger
5. Open DevTools and the flutter inspector either as a tab on VS Code or on the browser

![image](https://user-images.githubusercontent.com/89718602/191924172-fe114caa-0f84-42d3-a42d-658a696d5dce.png)
![image](https://user-images.githubusercontent.com/89718602/191924325-26dc0a82-a24f-413f-b325-c948474589c7.png)

**Please complete the following information:**
 - Operating System and version: Kubuntu 22.04.1 LTS x86_64
 - VS Code version: 1.71.2
 - Dart extension version: 3.48.4
 - Flutter SDK version: 3.3.2
 - Dart SDK version: 2.18.1
 - DevTools version: 2.15.0
 - Target device: The bug happens regardless of the target device

**Comment by jlvlg** [comment] 2022-09-24 00:05
It also worked when running on Windows 10. It seems to be tied to my Linux install specifically

**Comment by DanTup** [comment] 2022-09-24 16:06
@jlvlg does this occur only when the app is running on Linux (as the target), or do you see the same if you run on Android (for example) from Linux?

Could you try capturing a log in the case where it fails? (ideally using an Android device/emulator, so if it's Linux specific we know it's related to the host and not the target)

- Run the [**Dart: Capture Debugging Logs** command](https://dartcode.org/docs/logging/#capture-debugging-logs)
- Reproduce the issue
- Click **Cancel** on the logging notification to stop logging and open the log
- Remove anything sensitive from the log
- Attach the log here (or in a gist)

Thanks!

**Comment by jlvlg** [comment] 2022-09-24 16:30
> does this occur only when the app is running on Linux (as the target), or do you see the same if you run on Android (for example) from Linux?

It happens when my host is on Linux. I have tried to run both physical and emulated android devices, the behavior is the same regardless of the target device.

> Attach the log here (or in a gist)

This is running on a physical device
[https://gist.github.com/jlvlg/3c11414957e30fe74e0b3b352ecaf70c](https://gist.github.com/jlvlg/3c11414957e30fe74e0b3b352ecaf70c)

**Comment by jlvlg** [comment] 2022-09-24 16:32
It could be something wrong with my machine, but it works when I'm using IntelliJ or when I run `flutter run` on the terminal. It's just when trying to use VS Code built-in debugger

**Comment by jlvlg** [comment] 2022-09-24 16:33
I've noticed it also doesn't communicate well with the devtools at all on my computer. I set a couple breakpoints on VS Code, they appear on the DevTools debugger tab, but it just skips them. It only works if I set them through the DevTools GUI

**Comment by DanTup** [comment] 2022-09-24 16:42
I suspect those two things are the same issue. I think it's a path mismatch. In your log file I see two different paths:

```
/home/user/Documents/Programming/bug
/media/HDD/Documents/Programming/bug
```

I'm guessing the first is a symlink to the second?

If you try opening the folder `/media/HDD/Documents/Programming/bug` in VS Code instead of the first, does everything start working? If so, it's likely the issue described in https://github.com/dart-lang/sdk/issues/49309. I have some possible ideas for fixing this, though haven't gotten around to testing them yet.

**Comment by jlvlg** [comment] 2022-09-24 17:22
Everything indeed starts working when I open the folder through the actual path. Interesting, huh.
I've seen some people around with similar issues regarding the devtools, I wonder if it's caused by the same thing. It seems like it's been a bug for quite some time.
Should we mark the issue as closed?  Technically the bug isn't solved (nor it will be for some time probably) but you did find a solution to the problem.

**Comment by DanTup** [comment] 2022-09-26 08:53
Thanks for confirming. Let's close this as a dupe of #4172 then since it seems like the same problem. I do believe this issue has been around forever, although it would be nice to solve. I think on other platforms VS Code is resolving the symlinks when you open the folder, so this doesn't occur, but for some reason on Linux it does not (as a result, this can't be reproduced on a MacBook even deliberately trying to open symlinks 😞).

**Closed by DanTup** 2022-09-26 08:53 UTC
Labels: is bug, awaiting info
