### ISSUE TITLE
flutter doctor is ok, but vscode is no device, Android Studio can also detected.

### ISSUE THREAD

**Issue by caybear** [Dart-Code/Dart-Code#5070] opened 2024-04-13 01:33 UTC
![1712971155690](https://github.com/Dart-Code/Dart-Code/assets/5482663/6ab61abc-826a-4479-9f03-2eb2c9b5e1ae)

**Comment by DanTup** [comment] 2024-04-13 08:32
Can you enable the [flutter device daemon log](https://dartcode.org/docs/logging/#flutter-daemon) and attach a copy here after restarting VS Code and having the device not show up? Thanks!

**Comment by caybear** [comment] 2024-04-13 09:48
!! ⚠️ PLEASE REVIEW THIS LOG FOR SENSITIVE INFORMATION BEFORE SHARING ⚠️ !!
Dart Code extension: 3.86.0
Flutter extension: 3.86.0 (not activated)

App: Visual Studio Code
App Host: desktop
Version: win 1.87.2


Logging Categories:
    FlutterDaemon

Sat Apr 13 2024 [17:42:28 GMT+0800 (China Standard Time)] Log file started
[5:42:28 PM] [FlutterDaemon] [Info] Spawning D:\flutter\flutter\bin\flutter.bat with args ["daemon"]
[5:42:28 PM] [FlutterDaemon] [Info] ..  in D:\flutter\flutter
[5:42:28 PM] [FlutterDaemon] [Info] ..  with {"toolEnv":{"FLUTTER_HOST":"VSCode","PUB_ENVIRONMENT":"vscode.dart-code","FLUTTER_ROOT":"D:\\flutter\\flutter"}}
[5:42:28 PM] [FlutterDaemon] [Info]     PID: 3868
[5:42:29 PM] [FlutterDaemon] [Info] <== [{"event":"daemon.connected","params":{"version":"0.6.1","pid":13872}}]
[5:42:29 PM] [FlutterDaemon] [Info] ==> [{"id":"1","method":"device.enable"}]
[5:42:29 PM] [FlutterDaemon] [Info] ==> [{"id":"2","method":"emulator.getEmulators"}]
[5:42:29 PM] [FlutterDaemon] [Info] ==> [{"id":"3","method":"daemon.getSupportedPlatforms","params":{"projectRoot":"D:\\github.com\\funcapp"}}]
[5:42:30 PM] [FlutterDaemon] [Info] <== [{"event":"daemon.logMessage","params":{"level":"warning","message":"Flutter assets will be downloaded from https://storage.flutter-io.cn. Make sure you trust this source!"}}]
[5:42:30 PM] [FlutterDaemon] [Info] <== [{"event":"daemon.logMessage","params":{"level":"status","message":"Starting device daemon..."}}]

**Comment by caybear** [comment] 2024-04-13 10:17
Dart Code extension: 3.86.0
Flutter extension: 3.86.0 (not activated)

App: Visual Studio Code
App Host: desktop
Version: win 1.87.2


Logging Categories:
    FlutterDaemon

Sat Apr 13 2024 [17:42:28 GMT+0800 (China Standard Time)] Log file started
[5:42:28 PM] [FlutterDaemon] [Info] Spawning D:\flutter\flutter\bin\flutter.bat with args ["daemon"]
[5:42:28 PM] [FlutterDaemon] [Info] ..  in D:\flutter\flutter
[5:42:28 PM] [FlutterDaemon] [Info] ..  with {"toolEnv":{"FLUTTER_HOST":"VSCode","PUB_ENVIRONMENT":"vscode.dart-code","FLUTTER_ROOT":"D:\\flutter\\flutter"}}
[5:42:28 PM] [FlutterDaemon] [Info]     PID: 3868
[5:42:29 PM] [FlutterDaemon] [Info] <== [{"event":"daemon.connected","params":{"version":"0.6.1","pid":13872}}]
[5:42:29 PM] [FlutterDaemon] [Info] ==> [{"id":"1","method":"device.enable"}]
[5:42:29 PM] [FlutterDaemon] [Info] ==> [{"id":"2","method":"emulator.getEmulators"}]
[5:42:29 PM] [FlutterDaemon] [Info] ==> [{"id":"3","method":"daemon.getSupportedPlatforms","params":{"projectRoot":"D:\\github.com\\funcapp"}}]
[5:42:30 PM] [FlutterDaemon] [Info] <== [{"event":"daemon.logMessage","params":{"level":"warning","message":"Flutter assets will be downloaded from https://storage.flutter-io.cn. Make sure you trust this source!"}}]
[5:42:30 PM] [FlutterDaemon] [Info] <== [{"event":"daemon.logMessage","params":{"level":"status","message":"Starting device daemon..."}}]

**Comment by DanTup** [comment] 2024-04-15 09:34
Thanks - it's not clear to me what's wrong, but I wonder if you're seeing the same issue described in https://github.com/Dart-Code/Dart-Code/issues/4840

In that issue, it seems that the `flutter` tool sees `stdin` close and no longer gets any input from VS Code. I've not been able to reproduce and debug this yet, but some of the other users in that thread have been debugging a little.

**Comment by caybear** [comment] 2024-04-15 17:14
Yes. It seems like they have same issue #4840

**Comment by DanTup** [comment] 2024-04-16 10:08
@caybear just to confirm - do you have this problem in Android Studio, or only VS Code? The OP in #4840 appears to see the same issue in Android Studio so I wonder if it's the same issue.

Can you also confirm that if it does work in Android Studio that you are using the exact same Flutter SDK (and don't have two different Flutter SDKs)?

**Comment by caybear** [comment] 2024-04-16 14:22
My PC only has one Flutter SDK, this problem only in VS Code, I am currently working on Android studio and it runs well

**Comment by caybear** [comment] 2024-04-16 14:28
![image](https://github.com/Dart-Code/Dart-Code/assets/5482663/b8fec369-0c5a-403f-9fe5-fc008f2e9b20)

**Comment by caybear** [comment] 2024-04-16 14:29
My PC only has one Flutter SDK, this problem only in VS Code, I am currently working on Android studio and it runs well

![image](https://github.com/Dart-Code/Dart-Code/assets/5482663/49d8dcd3-e91a-4da5-a248-2f0566386cf4)

**Comment by Pliavi** [comment] 2024-04-16 22:56
It's happening the same to me, no Chrome device.
Only in VSCode
I found out that looks like that VSCode is executing something in the wrong environment(???), cause I tried `flutter doctor` in sh, bash and zsh, and it's everything green, good.

<details><summary>TEXT LOG</summary>
<p>

```sh
sh-5.2$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.19.5, on Manjaro Linux 6.6.26-1-MANJARO, locale pt_BR.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.2)
[✓] Connected device (1 available)
[✓] Network resources

• No issues found!
sh-5.2$ exit
exit
``` 

</p>
</details> 

![image](https://github.com/Dart-Code/Dart-Code/assets/5985423/207facf5-562b-4ce4-b30a-b4426892088d)

But if I use the command `Flutter: Run Flutter Doctor`, it shows 3 warnings: no flutter binary on path, no chrome path and no devices
<details><summary>TEXT LOG</summary>
<p>

```sh
[flutter] flutter doctor -v
[!] Flutter (Channel stable, 3.19.5, on Manjaro Linux 6.6.26-1-MANJARO, locale pt_BR.UTF-8)
    • Flutter version 3.19.5 on channel stable at /home/pliavi/flutter
    ! The flutter binary is not on your path. Consider adding /home/pliavi/flutter/bin to your path.
    ! Warning: `dart` on your path resolves to /opt/dart-sdk-dev/bin/dart, which is not inside your current Flutter SDK checkout at /home/pliavi/flutter. Consider adding /home/pliavi/flutter/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 300451adae (3 weeks ago), 2024-03-27 21:54:07 -0500
    • Engine revision e76c956498
    • Dart version 3.3.3
    • DevTools version 2.31.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /home/pliavi/Android/Sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /opt/android-studio/jbr/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)
    • All Android licenses accepted.

[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Android Studio (version 2023.2)
    • Android Studio at /opt/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)

[!] Connected device
    ! No devices available

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 3 categories.
exit code 0
``` 

</p>
</details> 

![image](https://github.com/Dart-Code/Dart-Code/assets/5985423/cf215d43-64a2-4d07-979f-437b666ee426)

**Comment by caybear** [comment] 2024-04-16 23:06
It's broken. I seem to remember that It used to work.  It's been a while.
![image](https://github.com/Dart-Code/Dart-Code/assets/5482663/01db98f9-7e39-40df-9520-b290197543ca)

**Comment by caybear** [comment] 2024-04-16 23:08
It's broken.
I seem to remember that It used to work. It's been a while.
![image](https://github.com/Dart-Code/Dart-Code/assets/5482663/2ec55aa1-af08-40a2-bbb4-b281b23d52a1)

**Comment by DanTup** [comment] 2024-04-17 10:33
@caybear thanks for testing - in that case I do think you're seeing the same as https://github.com/Dart-Code/Dart-Code/issues/4840, so let's close this as a dupe of that.

@Pliavi I think your issue is different to this one. My guess is that you're setting your `PATH` environment variable (and maybe `CHROME_EXECUTABLE`?) in a way that is applied to terminals (for example in a terminal startup script) but then launching VS Code in a way that does not inherit that `PATH` environment variable. 

I suspect if you launch Code from the terminal then run the Flutter Doctor command in VS Code, it'll be clean. You need to either set the environment variables in a way that VS Code inherits them (how you do this may be distro-specific) or you can try using `dart.env` to set some (see https://github.com/Dart-Code/Dart-Code/issues/4227#issuecomment-1284433725 for an example setting `CHROME_EXECUTABLE`).

If that doesn't help, please file a new issue with the details. Thanks!

**Closed by DanTup** 2024-04-17 10:33 UTC
Labels: is bug, awaiting info
