### ISSUE TITLE
New Flutter Sidebar is not visible

### ISSUE THREAD

**Issue by kenzieschmoll** [Dart-Code/Dart-Code#4806] opened 2023-10-20 18:02 UTC
**Describe the bug**
New Flutter Sidebar is not visible. I opened devtools/, detools/packages/devtools, and gallery and all showed the Flutter outline but not the new Flutter sidebar. 

I tried both the pre-release version of the dart-code plugin and the latest stable (both of which should include the flutter sidebar).

<details>

<summary><strong>Workspace Environment</strong></summary>

```text
Dart Code extension: 3.75.20231009
Flutter extension: 3.75.20231002 (activated)

App: Visual Studio Code
App Host: desktop
Version: mac 1.83.1

Workspace type: Dart, Flutter (LSP)

Dart (3.3.0-45.0.dev): /Users/kenzieschmoll/develop/flutter/bin/cache/dart-sdk
Flutter (3.16.0-14.0.pre.19): /Users/kenzieschmoll/develop/flutter (Chrome (web-javascript/web))

```

</details>

**Comment by DanTup** [comment] 2023-10-23 09:08
Can't figure this out, but I wonder if it's showing up somewhere in the wrong place (a user recently reported Test Results was docked in a bottom panel but they hadn't moved it).

It's possible to snap it inside something like the Terminal panel where you won't even see it as a heading on the bottom panel.

Can you try running this command:

![image](https://github.com/Dart-Code/Dart-Code/assets/1078012/32812483-2110-4eef-89f5-4413a28f6c04)

It might have a different prefix (like "Terminal" or something) if it's docked somewhere else. If the command isn't visible, the Sidebar probably isn't being registered correctly. If the command is visible, it's probably showing up somewhere unexpected (and once you find it you can right-click and choose "Reset Location" to put it back).

**Comment by kenzieschmoll** [comment] 2023-10-23 17:13
this worked to find it
<img width="616" alt="Screenshot 2023-10-23 at 10 12 09 AM" src="https://github.com/Dart-Code/Dart-Code/assets/43759233/0f9f76e3-eaeb-4669-90f7-7f6ea4051856">
Looks like I have two Flutter sidebars (see this highlighted flutter icon and the bottom sidebar icon). I would imagine that is a bug right?
<img width="388" alt="Screenshot 2023-10-23 at 10 12 23 AM" src="https://github.com/Dart-Code/Dart-Code/assets/43759233/0bacbac9-fc02-4cc5-a3b2-addaf7769dde">

**Comment by DanTup** [comment] 2023-10-23 17:15
@kenzieschmoll ah, that explains it. That's not a bug, you can drag the two panels (sidebar + outline) into their own sections on the sidebar. Perhaps if you'd moved the Outline around at any point in the past it would've caused it to be disconnected from the original container (which is where the new sidebar now shows up).

You can right-click on them and choose Reset to put them back into their original containers (you could also drag one onto the other, but without being sure which one is the extension-defined container and which one is the "popped out one" you might see the same quirk in future if we add another panel).

**Comment by kenzieschmoll** [comment] 2023-10-23 17:19
Ah, got it. Thanks! I'm also noticing the IDE theme is not being respected by the sidebar, is there a way to see what the url is of the sidebar panel that is being rendered by DevTools?

**Comment by DanTup** [comment] 2023-10-23 17:27
You can click Help -> Toggle Developer Tools to open the Chrome DevTools then use the inspection button to select the iframe.

Seems I can repro this... The URL looks like:

http://127.0.0.1:9100/vsCodeFlutterPanel?theme=light&backgroundColor=%23f3f3f3&foregroundColor=%236f6f6f&fontSize=14

I'm not sure what's wrong, I was sure I'd tested this before (and also wired up the dummy environment to handle it too). Want me to file a new issue and take a look?

**Comment by DanTup** [comment] 2023-10-23 17:28
Actually, something is happening with the theme because I get a darker background when I have light theme selected than when I have dark theme selected. So maybe the issue is a selection of colours somewhere.

**Comment by kenzieschmoll** [comment] 2023-10-23 17:32
> I'm not sure what's wrong, I was sure I'd tested this before (and also wired up the dummy environment to handle it too). Want me to file a new issue and take a look?

That would be great - thanks Danny.

**Comment by DanTup** [comment] 2023-10-24 13:16
I've filed https://github.com/flutter/devtools/issues/6580 about the theme. Closing this one as I think it's working as intended (unfortunately I don't think there's much we can do about this quirk besides assigning unique icons to all sections so it's clearer what's what if they are separated in this way).

**Closed by DanTup** 2023-10-24 13:16 UTC
Labels: is bug, awaiting info
