### ISSUE TITLE
Higher order functions always autocomplete to anonymous closures

### ISSUE THREAD

**Issue by gaaclarke** [Dart-Code/Dart-Code#3509] opened 2021-08-02 17:11 UTC
## Seen behavior:
Given the following code:
```dart
String _commaJoin(String x, String y) => '$x, $y';

void foo() {
  final List<String> bar = <String>['Hello', 'world'];
  bar.re**CURSOR HERE**
}
```

If I select 'reduce()' from the suggestions it will autocomplete `bar.reduce((value, element) => null)` highlighting `null`.

## What I expected

What I actually wanted was `bar.reduce(_commaJoin)`.  It's a bit of a hassle to delete the closure.  In this case no autocomplete of the argument would be better, or a dropdown list of functions in the current context that match the needed signature like so:

```
┌─────────────┐
│ Lambda      │
│ _commaJoin  │
└─────────────┘

**Comment by DanTup** [comment] 2021-08-12 16:23
@bwilkerson @pq I think this was done for https://github.com/dart-lang/sdk/issues/40202. It's included in the default arg string for the method, so we can't easily tell it apart from other argument placeholders:

https://github.com/dart-lang/sdk/blob/9db372e6f46964ab5c63b253869020e89b51fe26/pkg/analysis_server/lib/src/services/completion/dart/utilities.dart#L55-L84

I'm not sure of a way to improve it without undoing https://github.com/dart-lang/sdk/issues/40202 (and moving the lambda to the completion list) but I suspect that would feel like a regression to many. I thought including `reduce()` in the completion list twice might work, but that breaks down when there's more than one `Function` argument since you might want a lambda for one but not for another.

Any thoughts? (If there's no an easy/obvious fix, we can move this to the SDK repo for discussion).

**Comment by bwilkerson** [comment] 2021-08-12 16:30
As far as I'm aware we have only two options: either we always fill in closures for function-valued parameters or we never do. I don't know how to determine which is the better default. Moving this issue to the SDK repo seems reasonable (I'm fairly sure any change would be in the analysis server).

**Comment by DanTup** [comment] 2021-08-12 16:41
Yeah, I suspect in most cases it _is_ used (whether necessary or not) - although it also feels like it may be more effort to remove it when not needed than add it from completion if it was missing (at least if the completion automatically triggered and it was top when you got to that tabstop).

@gaaclarke do you want to file this at https://github.com/dart-lang/sdk since that's where any change would likely be made.

I'm not sure that it helps _much_, but if you're on a recent build of the SDK (not stable), you may be able to use the **Expand Selection** command (twice?) (which has the awkward binding of `Shift` + `Cmd` + `Ctrl` + `->` on macOS) to expand from having `null` selected to having `(a, b) => null` selected. It might be slightly better than using `Shift`+`Ctrl`+`<-` because that drops `null` out of the selection.

**Comment by DanTup** [comment] 2021-08-13 12:11
@gaaclarke just copying the above is fine, those triaging issues in the Dart repo will know what to do with it - though feel free to post the link back here (@bwilkerson who commented above is on the Dart Team and works on the analyzer).

And FWIW it's certainly not an issue to raise issues here first if you're unsure where they belong - there's a fairly blurry line between what comes from server/extension, and for some smaller (or LSP) issues I'll work on fixes too. Thanks!

**Comment by DanTup** [comment] 2021-08-24 13:18
Closing this in favour of an SDK issue - @gaaclarke if/when you've opened one, please ping the link back here for anyone that comes across this one looking for an answer. Thanks!

**Closed by DanTup** 2021-08-24 13:18 UTC

**Comment by gaaclarke** [comment] 2021-08-24 16:06
Filed at https://github.com/dart-lang/sdk/issues/46979
