### ISSUE TITLE
Reload during breakpoint

### ISSUE THREAD

**Issue by csga5000** [Dart-Code/Dart-Code#756] opened 2018-03-31 19:12 UTC
While admittedly I think this is also an issue if you're using the command line, it's annoying either way, and made worse by auto-load on file save.

If you have a breakpoint that was hit, then change a file and hit "save" (or just manually hit the reload button) your reload will never finish and your breakpoint cannot be continued.  This forces you to restart the app.

Even just dis-allowing reloads during breakpoints (perhaps with a helpful error) could make this much nicer.  Or even more minimal, disable or suspend on save reloads during breakpoint.

**Comment by DanTup** [comment] 2018-03-31 19:48
> While admittedly I think this is also an issue if you're using the command line

I'm curious, how are you hitting breakpoints running from the command line?

> If you have a breakpoint that was hit, then change a file and hit "save" (or just manually hit the reload button) your reload will never finish and your breakpoint cannot be continued. This forces you to restart the app.

I'd say this is a bug. If we can't make continuing work normally, I think we should resume before sending the reload. I'll do some testing and see what I can do.

**Comment by csga5000** [comment] 2018-03-31 20:01
The flutter command line?  Using the dart observatory and "debugger();".

**Comment by DanTup** [comment] 2018-04-02 06:49
Ah, gotcha - I didn't realise people were using Observatory directly (it seems hard to use IMO) so I just wondered if there was something else I was unaware of.

I'll do some digging into this before we move it anywhere to make sure we fully understand the cause (it's very possible it's a simple fix in Dart Code).

**Comment by csga5000** [comment] 2018-04-02 06:59
It's not too bad, when you do flutter run you can just control click the link, and debug from there.  But the biggest issues are it's more work to place breakpoints (you have to import dart: developer, and then add debugger(); everywhere), and stepping into functions or code is a hit trickier.  But a little while ago, for iOS, the vscode dart debugger had these issues:
1. The one this issue is on
2. Sometimes I would get an error when running the program that it couldn't connect to the dart vm or something.  Had to restart vscode to fix.
3. Difficult command R 

Now that one or two of those are already fixed I'm definitely not going to be using the command line.

**Comment by DanTup** [comment] 2018-04-02 07:34
Ok, seems like this is a flutter issue. We send the reload to `flutter run` and then observatory seems unresponsive, not responding to resume commands.

I found this in the Flutter issue tracker: https://github.com/flutter/flutter/issues/13396

**Comment by DanTup** [comment] 2018-05-03 17:08
Closing this as I don't think there's anything to do here, there's an issue open in Flutter about this and once it's fixed there, it'll come through here without any additional effort.

**Closed by DanTup** 2018-05-03 17:08 UTC
Labels: upstream in dart / flutter

**Comment by DanTup** [comment] 2018-05-20 08:40
Seems like this may be fixed in master: https://github.com/flutter/flutter/issues/17434#issuecomment-390264682

**Comment by csga5000** [comment] 2018-05-21 19:28
Sweet, thanks Dan
