### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by nahuel989** [Dart-Code/Dart-Code#1675] opened 2019-05-01 23:59 UTC
- Issue Type: `Performance`
- Extension Name: `dart-code`
- Extension Version: `2.26.1`
- OS Version: `Windows_NT x64 10.0.17134`
- VSCode version: `1.33.0`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\Alumno\Dart-Code.dart-code-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by DanTup** [comment] 2019-05-02 07:34
@nahuel989 are you able to attach the file referenced in your message?

> ⚠️ Make sure to attach this file from your home-directory:
> ⚠️C:\Users\Alumno\Dart-Code.dart-code-unresponsive.cpuprofile.txt

Thanks!

**Comment by DanTup** [comment] 2019-05-09 10:16
With no profile I can't investigate this, but I'm fairly sure it'll be a dupe of #1628.

**Closed by DanTup** 2019-05-09 10:16 UTC
Labels: awaiting info
