### ISSUE TITLE
print not reaching debug console

### ISSUE THREAD

**Issue by lukepighetti** [Dart-Code/Dart-Code#2044] opened 2019-10-09 15:32 UTC
For some reason I'm not getting any print statements in my debug console. This issue appears to have come up sometime in the last week. Can anyone else reproduce?

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, v1.10.14, on Mac OS X 10.14.6 18G87, locale en-US)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
[✓] Android Studio (version 3.1)
[✓] VS Code (version 1.38.1)
[✓] Connected device (2 available)

• No issues found!
```

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Example',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: _Body(),
    );
  }
}

class _Body extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    print("print build");
    debugPrint("debugPrint build");

    return Material(
      child: Center(
        child: RaisedButton(
          child: Text("Weee"),
          onPressed: () {
            print("print onPressed");
            debugPrint("debugPrint onPressed");
          },
        ),
      ),
    );
  }
}

```

```
Launching lib/main.dart on Luke's iPhone in debug mode...
Signing iOS app for device deployment using developer identity: "iPhone Developer: Luke Pighetti (xxx)"
Xcode build done.                                           13.2s
```

**Comment by DanTup** [comment] 2019-10-09 15:46
This seems to be an open issue in Flutter:

https://github.com/flutter/flutter/issues/41133

There are some possible workaround in that thread, but it sounds like a fix is being worked on. I'll close this as a dupe of that. Sorry for the inconvenience!

**Closed by DanTup** 2019-10-09 15:46 UTC
