### ISSUE TITLE
Highligh issue with another textmate grammar 

### ISSUE THREAD

**Issue by woprandi** [Dart-Code/Dart-Code#5121] opened 2024-05-27 12:10 UTC
**Describe the bug**
I'm working on this extension : https://marketplace.visualstudio.com/items?itemName=GraphQL.vscode-graphql to add support to syntax hightlight inside Dart source code. 
The port is straightforward (Draft PR here : https://github.com/graphql/graphiql/pull/3612). 
Without extension it works but with the Dart extension the hightlight stops to  work after few seconds. I guess there are a kind of conflict between grammars (https://github.com/Dart-Code/Dart-Code/blob/master/syntaxes/dart.json and https://github.com/graphql/graphiql/pull/3612/files#diff-1a844416b43dcd649c939cc179b8a5157efd1860392a397657656fdbd6e9168d) but I don't know which and I'm not an expert
I found set settings ` "editor.semanticHighlighting.enabled": false` "fixes" the issue but I guess I'll get some behavior changes elsewhere (and I don't know if it's legitimate)

**To Reproduce**
1. Clone my fork https://github.com/woprandi/graphiql/tree/main
2. `cd vscode-graphql-syntax`
3. `yarn && yarn vsce:package`
4. Install `vscode-graphql-syntax-1.3.6.vsix`
5. Open `tests/__fixtures__/test.dart`, graphql block highlight should works
7. Install Dart extension
8. Highlighting will disappears like the video 

**Expected behavior**
Hightlighting works 

**Screenshots**

[test.webm](https://github.com/Dart-Code/Dart-Code/assets/1449422/0e25c709-794d-43b4-823e-ba9b296c8e70)

![image](https://github.com/Dart-Code/Dart-Code/assets/1449422/4ce03c4f-08d4-4ac0-adc3-741f245be5d6)
Without Dart extension

![image](https://github.com/Dart-Code/Dart-Code/assets/1449422/f680a3df-32a4-43fb-b8d7-1d80f0c59114)
With Dart extension

**Please complete the following information:**

You can run the **Dart: Collect Diagnostic Information** command from the VS Code command palette (`F1`) to easily capture this information or provide it manually.

 - Operating System and version: Fedora 40
 - VS Code version: 1.89.1
 - Dart extension version: 3.88.1
 - Dart/Flutter SDK version: 3.4.1
 - Target device (if the issue relates to Flutter debugging):

**Comment by DanTup** [comment] 2024-05-28 10:12
> I found set settings  `"editor.semanticHighlighting.enabled": false` "fixes" the issue

The reason for this is that there are two ways VS Code uses to provide syntax highlighting. When you first open the file, it is coloured using the textmate grammar. Textmate grammars do not have semantic information (for example they can't tell the difference between a reference to a property or a method because it may be defined in another file) so VS Code also supports "semantic tokens" which are provided by the language server (and therefore have more information) and _override_ the textmate grammar.

More info on semantic tokens in VS Code can be found at https://code.visualstudio.com/api/language-extensions/semantic-highlight-guide

So the problem here is that the semantic tokens are being provided by the Dart language server and overriding everything in the textmate grammar.

Unfortunately VS Code does not support embedded languages when semantic tokens are enabled - I've filed an issue about that in the past at https://github.com/microsoft/vscode/issues/163292 because this has come up before (actually [also for GraphQL](https://github.com/Dart-Code/Dart-Code/issues/4212)).

I'll close this as a dupe of https://github.com/Dart-Code/Dart-Code/issues/4212 (you can add your 👍 there and also on the VS Code issue at https://github.com/microsoft/vscode/issues/163292), although right now I don't have a great solution besides waiting for VS Code to add support.

**Closed** 2024-05-28 10:12 UTC
Labels: duplicate
