### ISSUE TITLE
defaultTargetPlatform on Flutter missing highlight

### ISSUE THREAD

**Issue by terlord1** [Dart-Code/Dart-Code#523] opened 2018-02-02 19:17 UTC
```dart
class FriendlychatApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
      title: "Friendlychat",
      theme: defaultTargetPlatform == TargetPlatform.iOS
        ? kIOSTheme
        : kDefaultTheme,
      home: new ChatScreen(),
    );
  }
}
```

**Comment by DanTup** [comment] 2018-02-02 19:54
I'm not sure exactly what the expected behaviour is here. When you say highlight, do you mean the colour? Can you provide a screenshot and explanation of what you expect to see?

I pasted your code in and `defaultTargetPlatform` is white, which seems to be the same as for other variables and getters?

<img width="432" alt="screen shot 2018-02-02 at 19 53 22" src="https://user-images.githubusercontent.com/1078012/35752137-c4c5a77a-0852-11e8-892c-b960810931e7.png">

That said; the current syntax highlighting is definitely not perfect - we're limited to regex-based highlighting right now (see https://github.com/Microsoft/vscode/issues/585 and https://github.com/Dart-Code/Dart-Code/issues/311).

**Comment by terlord1** [comment] 2018-02-03 03:14
Oh well thank you. You are doing a very good job with the extension, it
really helped me a lot with my development and speed.

**Comment by DanTup** [comment] 2018-02-03 17:24
Glad you like it!

I'm closing this as a dupe of the above linked cases since I think it's really a request for using the analysis servers highlighting, but shout if I've misunderstood and you think there's something I can do here.

**Closed by DanTup** 2018-02-03 17:24 UTC
