### ISSUE TITLE
Dart formatter freezing

### ISSUE THREAD

**Issue by JCKodel** [Dart-Code/Dart-Code#2341] opened 2020-04-08 15:00 UTC
![image](https://user-images.githubusercontent.com/379339/78799358-654cb980-7990-11ea-8482-a69e954f7873.png)

Everytime I try to save a .dart file, this window appears and won't go away (the file is not saved, and it keeps waiting forever)

<details><summary>Log</summary>

```
!! PLEASE REVIEW THIS LOG FOR SENSITIVE INFORMATION BEFORE SHARING !!

Dart Code extension: 3.9.1
Flutter extension: 3.9.1 (not activated)
VS Code: 1.43.2
Platform: win
Workspace type: Flutter
Multi-root?: false
Dart SDK:
    Loc: C:\Flutter\bin\cache\dart-sdk
    Ver: 2.7.2
Flutter SDK:
    Loc: C:\Flutter
    Ver: 1.12.13+hotfix.9
HTTP_PROXY: undefined
NO_PROXY: undefined

Wed Apr 08 2020 [12:02:57 GMT-0300 (Horário Padrão de Brasília)] Log file started
[12:03:01] [Analyzer] [Info] ==> {"id":"24","method":"analysis.updateContent","params":{"files":{"C:\\Projects\\MedConf\\Frontend\\lib\\data\\database.dart":{"edits":[{"id":"","length":0,"offset":847,"replacement":"\r\n"}],"type":"change"}}},"clientRequestTime":1586358181456}
[12:03:02] [Analyzer] [Info] ==> {"id":"25","method":"analysis.updateContent","params":{"files":{"C:\\Projects\\MedConf\\Frontend\\lib\\data\\database.dart":{"edits":[{"id":"","length":2,"offset":849,"replacement":""}],"type":"change"}}},"clientRequestTime":1586358182296}
[12:03:02] [Analyzer] [Info] ==> {"id":"26","method":"edit.format","params":{"file":"C:\\Projects\\MedConf\\Frontend\\lib\\data\\database.dart","lineLength":150,"selectionLength":0,"selectionOffset":0},"clientRequestTime":1586358182614}
Wed Apr 08 2020 [12:03:11 GMT-0300 (Horário Padrão de Brasília)] Log file ended
```

</details>

**Comment by DanTup** [comment] 2020-04-08 15:04
Could you capture a log?

- Run **Dart: Capture Logs**
- Leave everything ticked
- Save the file to repro the issue
- Wait for 30s (to make sure nothing relevant is missed from the log)
- Click **Cancel** on the logging notification to stop
- Ensure the log contains nothing sensitive, and provide it here

It's also worth opening the dev tools (Help -> Toggle Developer Tools) to see if there are any relevant errors listed there.

Thanks!

**Comment by DanTup** [comment] 2020-04-08 15:06
Thanks for adding the log! It looks like the server never responded to the edit request. If you reproduce this (while logging again), and while it's "stuck" hoer the mouse over a few types in the editor, does the log contain responses to the `hover` requests?

Also - do you know when this started? Did it match up with updating any of VS Code / Extensions / Flutter?

**Comment by JCKodel** [comment] 2020-04-08 15:09
> Thanks for adding the log! It looks like the server never responded to the edit request. If you reproduce this (while logging again), and while it's "stuck" hoer the mouse over a few types in the editor, does the log contain responses to the `hover` requests?
> 
Yes.

```
[12:07:37] [Analyzer] [Info] <== {"event":"completion.availableSuggestions","params":{"changedLibraries":[],"removedLibraries":[]}}
[12:07:42] [Analyzer] [Info] ==> {"id":"17","method":"edit.getFixes","params":{"file":"C:\\Projects\\MedConf\\Frontend\\lib\\data\\database.dart","offset":1421},"clientRequestTime":1586358462004}
[12:07:42] [Analyzer] [Info] ==> {"id":"18","method":"edit.getAssists","params":{"file":"C:\\Projects\\MedConf\\Frontend\\lib\\data\\database.dart","length":0,"offset":1421},"clientRequestTime":1586358462004}
[12:07:42] [Analyzer] [Info] ==> {"id":"19","method":"edit.getAvailableRefactorings","params":{"file":"C:\\Projects\\MedConf\\Frontend\\lib\\data\\database.dart","length":0,"offset":1421},"clientRequestTime":1586358462004}
[12:07:42] [Analyzer] [Info] ==> {"id":"20","method":"analysis.getHover","params":{"file":"C:\\Projects\\MedConf\\Frontend\\lib\\data\\database.dart","offset":1421},"clientRequestTime":1586358462082}
Wed Apr 08 2020 [12:07:44 GMT-0300 (Horário Padrão de Brasília)] Log file ended
```

> Also - do you know when this started? Did it match up with updating any of VS Code / Extensions / Flutter?
I worked yesterday without any issue. Just turn my machine on now and opened VSCode, this happened at first save. No updates (all updates were already installed days ago - everything is kept up to date).

**Comment by DanTup** [comment] 2020-04-08 15:12
The snippet included above only shows the *request* for `getHover`, but not the response. Did the response definitely show up?

Does it happen in a trivial project (for ex. if you do **Flutter: New Project**) too?

**Comment by DanTup** [comment] 2020-04-08 15:28
I'm trying on Windows with v1.12.13+hotfix.9 of Flutter, v1.43.2 of VS Code and v3.9.1 of the extension (all same as above) but not able to repro. I'm not sure whether it's specific to your project, or something else (I'm testing with a freshly created **Flutter: New Project** project).

Could you try enabling the analysis server instrumentation log (https://dartcode.org/docs/logging/#analyzer-instrumentation) and also confirm if you have analysis server options/flags set in your user settings (things starting `dart.analyzer`) that might be different to mine?

**Comment by JCKodel** [comment] 2020-04-08 15:28
> The snippet included above only shows the _request_ for `getHover`, but not the response. Did the response definitely show up?
> 
Nop. That's it.

> Does it happen in a trivial project (for ex. if you do **Flutter: New Project**) too?

On a new project the window appears for 1 second, then it saves. Which is odd, because my machine has 32Gb RAM, 4Ghz CPU and a Samsung EVO 980 with almost 0.5Tb/sec write speed.

After the first saving, the performance is nominal (no popup appears and formatting is done instantly).

In the new project, when I close VSCode, all instances of dart.exe are killed. On the buggy project, 2 dart.exe instances remains loaded (one of them uses 3% cpu for about 5 seconds, go 12% (100% of the core), then exits.

**Comment by DanTup** [comment] 2020-04-08 15:37
I just realised, in the original log, there are two requests sent before the format that also did not complete - so the issue may not be as a result of the format - the server may have already stopped responding, but format is the only operation that triggers a notification when it's not responding.

If you can capture the instrumentation log mentioned above, that might show what the last thing the server was doing before it stopped was (info on any flags/settings you may have set may help too).

Thanks!

**Comment by JCKodel** [comment] 2020-04-08 15:54
I deleted the .dart_tool from the project and the behavior is now similar to the new project: the window appears, then it closes after 1, 2 seconds (don't know why the lag, tough)

I noticed that the analyzer was not operational as well (after the .dart_tool deletion, errors were reported on the problems window, as expected).

Reopening the project makes dart use 2 cores, 1.2Gb of RAM and takes about 5 to 6 seconds to analyzer starting working

![image](https://user-images.githubusercontent.com/379339/78803500-75b36300-7995-11ea-97ed-76ad9fb06bb7.png)

Only CPU and RAM usage are high, disk always 0%.

> Could you try enabling the analysis server instrumentation log (https://dartcode.org/docs/logging/#analyzer-instrumentation) and also confirm if you have analysis server options/flags set in your user settings (things starting `dart.analyzer`) that might be different to mine?

There are no user settings for this project (nothing really different from a new project, except the using of https://github.com/simolus3/moor/, which have code generation).

I tried to attach the logs here, but they are too big. One of them (dart instrumentation) freezes Chrome and lags Notepad++ (it has about 20Mb). I never see anything scratch Notepad++ 😮 Perhaps the lag resides here?

Here are the logs: http://code.art.br/logs.zip (the instrumentation log is causing problems).

**Comment by DanTup** [comment] 2020-04-08 16:28
In your log it has `--enable-completion-model`. I remember there were previously some issues that lead to that being disabling by default. Can you try removing it and see if the problem stops?

@devoncarew @bwilkerson - is this still known to be a problem (I can't find any issue specifically tracking it) or is it expected fixed?

**Comment by DanTup** [comment] 2020-04-08 16:30
Maybe https://github.com/flutter/flutter-intellij/issues/4143 is tracking it? (I had been looking in the SDK repo)

**Comment by JCKodel** [comment] 2020-04-08 16:35
> In your log it has `--enable-completion-model`. I remember there were previously some issues that lead to that being disabling by default. Can you try removing it and see if the problem stops?
> 

Guess this setting was due the "Dart analyzer has stopped" (never fixed, but occurred last often in the last updates).

Turned this option off and still it takes 18, 20 seconds for the analyzer to kick in (usually this would take 4, 5 seconds).

Same happens with Android Studio (16, 17 seconds lag, then the analyzer starts working).

**Comment by JCKodel** [comment] 2020-04-08 16:43
After deleting Flutter, Pub Cache, etc. VS seems stable (I'm really not sure if those 15, 20 seconds is normal or if it was faster before). Anyway, at least I can work now.

**Comment by bwilkerson** [comment] 2020-04-08 16:55
Yes, unfortunately, there are still issues with it. In the latest published version that flag has been disable (that is, the presence or absence of the flag has no effect).

**Comment by DanTup** [comment] 2020-04-08 17:04
@bwilkerson got it, thanks for confirming!

@JCKodel if you capture an instrumentation log of the slow startup, it might help identify where the time is being spent (whether it's normal may depend on things like the size of your project - I think the project you mentioned above also has an analysis server plugin too, so that may add some to the startup too, I'm not sure).

**Comment by JCKodel** [comment] 2020-04-08 17:15
@DanTup http://code.art.br/newlog.zip

I've configured the logs, removed the moor analyzer plugin, closed VSCode, delete the logs, then I started VSCode, waited for dart.exe to stabilize to 0% cpu, then closed VSCode.

**Comment by DanTup** [comment] 2020-04-08 17:32
Thanks! I think the plugin is still loaded based on the logs as there are errors being reported for `moor` files:

```
94:PluginNoti:{"event"::"analysis.errors","params"::{"file"::"/C::/Projects/MedConf/Frontend/lib/data/sql/settings.moor","errors"::[{...
```

I checked the timestamps anyway - the full log is approx 30 seconds. I trimmed the timestamps down to seconds (the first line is at 60, so the other times should have 60 subtracted to get time since start) and the biggest gaps in the logs are as follows:

Before the first `isAnalayzing:true` status update (this happens about 9 seconds after the previous logged line, 18 seconds after the `server.connected` event):

```
// Server connected event was at 60
60:Noti:{"event"::"server.connected","params"::{"version"::"1.27.4","pid"::20980}}
// ...
69:Req:{"id"::"12","method"::"analysis.updateContent","params"::{"files"::{"C::\\Projects\\MedConf\\Frontend\\lib\\main.dart"::{"edits"::[{"offset"::0,"length"::0,"replacement"::"","id"::""}],"type"::"change"}}},"clientRequestTime"::1586365860962}
69:Res:{"id"::"12","result"::{}}
69:Req:{"id"::"13","method"::"completion.setSubscriptions","params"::{"subscriptions"::["AVAILABLE_SUGGESTION_SETS"]},"clientRequestTime"::1586365860963}
69:Noti:{"event"::"completion.availableSuggestions","params"::{"changedLibraries"::[],"removedLibraries"::[]}}
69:Res:{"id"::"13"}
69:Req:{"id"::"14","method"::"analysis.updateContent","params"::{"files"::{"C::\\Projects\\MedConf\\Frontend\\lib\\main.dart"::{"edits"::[{"offset"::0,"length"::0,"replacement"::"","id"::""}],"type"::"change"}}},"clientRequestTime"::1586365860964}
69:Res:{"id"::"14","result"::{}}
69:Noti:{"event"::"completion.availableSuggestions","params"::{"changedLibraries"::[],"removedLibraries"::[]}}
78:Noti:{"event"::"server.status","params"::{"analysis"::{"isAnalyzing"::true}}}
```

I'm not sure what's happening there, it could be synchronous scanning of the workspace folder.

Then there's also a sizable gap (around 7 seconds) between some PluginRes and PluginNoti lines:

```
82:Noti:{"event"::"server.status","params"::{"analysis"::{"isAnalyzing"::false}}}
83:PluginReq:{"id"::"0","method"::"plugin.versionCheck","params"::{"byteStorePath"::"C::\\Users\\jckod\\AppData\\Local\\.dartServer\\.analysis-driver","sdkPath"::"C::\\Flutter\\bin\\cache\\dart-sdk","version"::"1.0.0-alpha.0"}}:file::///C::/Users/jckod/AppData/Local/.dartServer/.plugin_manager/e43d9ae98e588508fa738bc23429df4f/analyzer_plugin/bin/plugin.dart::
83:PluginRes:{"id"::"0","requestTime"::1586365883911,"result"::{"isCompatible"::true,"name"::"Moor plugin","version"::"2.0.0-alpha.0","contactInfo"::"Create an issue at https:://github.com/simolus3/moor/","interestingFiles"::["*.moor"]}}:file::///C::/Users/jckod/AppData/Local/.dartServer/.plugin_manager/e43d9ae98e588508fa738bc23429df4f/analyzer_plugin/bin/plugin.dart::
83:PluginReq:{"id"::"1","method"::"analysis.setContextRoots","params"::{"roots"::[{"root"::"C::\\Projects\\MedConf\\Frontend","exclude"::[],"optionsFile"::"C::\\Projects\\MedConf\\Frontend\\analysis_options.yaml"}]}}:file::///C::/Users/jckod/AppData/Local/.dartServer/.plugin_manager/e43d9ae98e588508fa738bc23429df4f/analyzer_plugin/bin/plugin.dart::
83:PluginReq:{"id"::"2","method"::"analysis.setSubscriptions","params"::{"subscriptions"::{"OUTLINE"::["C::\\Projects\\MedConf\\Frontend\\lib\\main.dart"],"FOLDING"::["C::\\Projects\\MedConf\\Frontend\\lib\\main.dart"],"OCCURRENCES"::["C::\\Projects\\MedConf\\Frontend\\lib\\main.dart"]}}}:file::///C::/Users/jckod/AppData/Local/.dartServer/.plugin_manager/e43d9ae98e588508fa738bc23429df4f/analyzer_plugin/bin/plugin.dart::
83:PluginReq:{"id"::"3","method"::"analysis.updateContent","params"::{//...
83:PluginReq:{"id"::"4","method"::"analysis.setPriorityFiles","params"::{"files"::["C::\\Projects\\MedConf\\Frontend\\lib\\main.dart"]}}:file::///C::/Users/jckod/AppData/Local/.dartServer/.plugin_manager/e43d9ae98e588508fa738bc23429df4f/analyzer_plugin/bin/plugin.dart::
85:PluginRes:{"id"::"1","requestTime"::1586365883926}:file::///C::/Users/jckod/AppData/Local/.dartServer/.plugin_manager/e43d9ae98e588508fa738bc23429df4f/analyzer_plugin/bin/plugin.dart::
85:PluginRes:{"id"::"2","requestTime"::1586365885843}:file::///C::/Users/jckod/AppData/Local/.dartServer/.plugin_manager/e43d9ae98e588508fa738bc23429df4f/analyzer_plugin/bin/plugin.dart::
85:PluginRes:{"id"::"3","requestTime"::1586365885849}:file::///C::/Users/jckod/AppData/Local/.dartServer/.plugin_manager/e43d9ae98e588508fa738bc23429df4f/analyzer_plugin/bin/plugin.dart::
85:PluginRes:{"id"::"4","requestTime"::1586365885850}:file::///C::/Users/jckod/AppData/Local/.dartServer/.plugin_manager/e43d9ae98e588508fa738bc23429df4f/analyzer_plugin/bin/plugin.dart::
92:PluginNoti:{"event"::"analysis.errors","params"::{"file"::"/C::/Projects/MedConf/Frontend/lib/main.dart","errors"::[]}}:file::///C::/Users/jckod/AppData/Local/.dartServer/.plugin_manager/e43d9ae98e588508fa738bc23429df4f/analyzer_plugin/bin/plugin.dart::
```

However I don't know enough about what's happening there to know if the plugin is busy, or these are unrelated events (@bwilkerson or @simolus3 may be more familiar with plugins, and this specific plugin). It could be worth figuring out why it wasn't actually disabled and testing without it to see whether it makes any difference.

**Comment by JCKodel** [comment] 2020-04-08 17:40
> Thanks! I think the plugin is still loaded based on the logs as there are errors being reported for `moor` files:
> 

That's odd. The moor plugin doesn't exist in settins.json (nor I have a user or project settings - all I do is in the main settings.json).

The only .moor specific option in unrelated:

```json
"files.associations": {
  "**/*.moor": "sql"
},
```

There is a task in .vscode/tasks.json that would run a build_runner watch on folderOpen, but this doesn't work (with or without `"runOn": "folderOpen"`, the task is not run at startup, nor the lag is resolved.

```json
{
	// See https://go.microsoft.com/fwlink/?LinkId=733558
	// for the documentation about the tasks.json format
	"version": "2.0.0",
	"tasks": [
		{
			"label": "Models Watch",
			"type": "shell",
			"command": "flutter packages pub run build_runner watch --delete-conflicting-outputs",
			"isBackground": true,
			"runOptions": {
				"instanceLimit": 1,
				"runOn": "folderOpen"
			}
		}
	]
}
```

I don't have a clue why .moor files are being scanned by Dart Analyzer.

**Comment by DanTup** [comment] 2020-04-08 17:55
> I don't have a clue why .moor files are being scanned by Dart Analyzer.

I'm not sure how this is set up, but I believe @simolus3 works on that plugin, so he may know the correct way to enable/disable it.

**Comment by JCKodel** [comment] 2020-04-08 17:57
> > I don't have a clue why .moor files are being scanned by Dart Analyzer.
> 
> I'm not sure how this is set up, but I believe @simolus3 works on that plugin, so he may know the correct way to enable/disable it.

@DanTup I've updated my comment above. The plugin was being enabled in the analysis_options.yaml.

**Comment by simolus3** [comment] 2020-04-08 18:36
Yeah, AFAIK plugins are loaded solely based on the `analysis_options.yaml` file, the editor doesn't have much to say here.

It's quite weird that the plugin sends notifications for Dart files at all - it should only do that for `.moor` files. I'll look into that, but I think it's safe to say that this is a moor bug and not the fault of Dart Code or the analysis server.

**Comment by DanTup** [comment] 2020-04-09 12:31
The new log seems much better - it's 13 seconds total, and includes preloading all of the completions for quite a number of Dart packages (symbols for packages are pre-loaded into the editor to make completion faster now that it includes unimported symbols.. if you disable `dart.autoImportCompletions` you might see some additional gains there, but won't get the auto-import completions).

> It's quite weird that the plugin sends notifications for Dart files at all - it should only do that for .moor files

I think this may have been misunderstood - in the logs above, the plugin was only getting `.moor` files (as far as I saw), and the lines about `.dart` files were just in the general startup. So there might not be anything wrong there.

I agree there's probably nothing wrong in VS Code here, so I'll close this issue - but feel free to comment back (or open new issues) if does look like there's anything wrong here. Thanks!

**Closed by DanTup** 2020-04-09 12:31 UTC
Labels: awaiting info

**Comment by hongfeiyang** [comment] 2021-03-03 07:19
I am having this issue with the newest vs code dart extension as of today. It freezes frequently, especially when my code contains generic types.

**Comment by DanTup** [comment] 2021-03-03 10:47
@hongfeiyang can you file a new issue and if possible include a code example that triggers it? If you haven't already enabled the LSP Preview, I would recommend trying that to see if it resolves the issue too. Thanks!

**Comment by joelhoelting** [comment] 2021-03-05 01:28
@DanTup

I know this issue is closed but I was also having this issue but I may have a helpful insight. The issue had something to do with having a large workspace in VS Code. I got an error saying "Cannot watch files in a large workspace" (I am paraphrasing because i am having trouble reproducing). Opening the Flutter app in its own workspace solved the problem for me.

**Comment by DanTup** [comment] 2021-03-08 11:57
@joelhoelting do you know if you had LSP enabled when you saw this? How frequently do you see it?

Can you also confirm whether you were on the latest Flutter version (2.0)?

**Comment by DanTup** [comment] 2021-03-09 10:05
@joelhoelting LSP stands for [Language Server Protocol](https://microsoft.github.io/language-server-protocol/). It's now enabled for some people by default. You can tell if it's on for you by hovering over the Dart version in the status bar and see whether it says "LSP" or "DAS" in the tooltip. LSP will soon replace DAS for everyone.

If you're able to reasonable reliably reproduce this, I'd definitely be interested in getting a log file to understand what's happening. It's possible it's related to a performance issue I recently fixed (that did not make the Flutter stable branch) that would trigger some expensive synchronous work in the server after opening new files of Ctrl+hovering symbols in the editor. A log might help confirm that.

**Comment by ThiagoMaia1** [comment] 2021-03-10 12:59
I've cloned the repository on which the error ocurred, and copied each file I had modified at a time. When I copied the code from a file that had the content below the error immediately occurs (even before I save or anything). I would have liked to go part by part, but as soon as I pasted it, the error hapenned and it seems like the whole repository is contaminated. I can't do anything because the error keeps hapenning. Commenting out the code doesn't solve. I think I'm going to have to clone the repository again.

`import 'package:flutter/material.dart';
import 'dart:math' as Math;

class StarRatings extends StatelessWidget {
  final double discountRate;

  const StarRatings({this.discountRate});

  @override
  Widget build(BuildContext context) {
    double height = 50;
    return ClipPath(
      clipper: StarClipper(numberOfPoints: 5, thickness: 0.1),
      // child: AspectRatio(
      // aspectRatio: 1,
      child: Container(
        width: height,
        height: height,
        color: Colors.yellow[800],
      ),
      // ),
    );
  }
}

// class StarClipper extends CustomClipper<Path> {
//   @override
//   getClip(Size size) {
//     var curv = size.width / 11;
//     var angle = 18.0;
//     var angle2 = 36.0;
//     double toRad(double deg) {
//       return Math.pi * (deg / 180);
//     }

//     var rad = toRad(angle);
//     var sin = Math.sin(rad);
//     var cos = Math.cos(rad);
//     var rad2 = toRad(angle2);
//     var sin2 = Math.sin(rad2);
//     var cos2 = Math.cos(rad2);
//     var diagonal = size.width;
//     var basisT = diagonal / (1 + 1 / sin);
//     var sideT = basisT / (2 * sin);
//     var heightT = sideT * cos;
//     var path = Path();

//     path.moveTo(diagonal / 2, 0);
//     path.relativeLineTo(basisT / 2, heightT);
//     path.relativeLineTo(sideT, 0);
//     path.relativeLineTo(-(sideT - sin * basisT), cos * basisT);
//     path.relativeLineTo(sin * sideT, sideT * cos);
//     path.relativeLineTo(-sideT * cos2, -sideT * sin2);
//     path.relativeLineTo(-sideT * cos2, sideT * sin2);
//     path.relativeLineTo(sin * sideT, -sideT * cos);
//     path.relativeLineTo(-(sideT - sin * basisT), -cos * basisT);
//     path.relativeLineTo(sideT, 0);
//     path.relativeLineTo(basisT / 2, -heightT);
//     path.close();
//     return path;
//   }

//   @override
//   bool shouldReclip(covariant CustomClipper oldClipper) {
//     return false;
//   }
// }

class StarClipper extends CustomClipper<Path> {
  /// The number of points of the star
  final int numberOfPoints;
  final double thickness;

  StarClipper({this.numberOfPoints, this.thickness});

  @override
  Path getClip(Size size) {
    double width = size.width;
    double bigRadius = width/2;
    double radius = width/2 * thickness;
    double degreesPerStep = _degToRad(360 / numberOfPoints);

    var path = Path();

    double max = 2 * Math.pi;

    path.moveTo(width, width/2);

    for (double step = 0; step < max; step += degreesPerStep) {
      path.lineTo(width/2 + bigRadius * Math.cos(step),
          width/2 + bigRadius * Math.sin(step));
      path.lineTo(width/2 + radius * Math.cos(step + degreesPerStep / 2),
          width/2 + radius * Math.sin(step + degreesPerStep / 2));
    }
    
    path.close();
    return path;
  }

  num _degToRad(num deg) => deg * (Math.pi / 180.0);

  @override
  bool shouldReclip(CustomClipper<Path> oldClipper) {
    StarClipper oldie = oldClipper as StarClipper;
    return numberOfPoints != oldie.numberOfPoints or thickness != oldie.thickness;
  }
}
`

**Comment by DanTup** [comment] 2021-03-10 15:42
@ThiagoMaia1 it looks like you're hitting https://github.com/dart-lang/sdk/issues/44785, which has been fixed but the fix was probably made after Flutter 2.0 was branched. I would expect it to be resolved in a future Flutter/Dart SDK release. Sorry for the inconvenience!

**Comment by ThiagoMaia1** [comment] 2021-03-10 16:19
Ok, thanks! No problem

**Comment by tronin** [comment] 2021-03-19 06:35
`killall dart`

**Comment by netgfx** [comment] 2021-04-21 08:55
Is this merged on the latest release yet, because I get the mentioned freeze and infinite save occasionally

**Comment by DanTup** [comment] 2021-04-21 09:04
@netgfx I think the original issue mentioned at the top was in an analyzer plugin, though there have been a few different issues mentioned throughout. There's an open issue about the formatter taking a long time (which may or may not be the formatters fault - it may also be the server being busy and not _starting_ to format for a while either) here:

https://github.com/Dart-Code/Dart-Code/issues/3270

There are some fixes that ma improved this that have _not_ yet reached the Flutter stable channel, however I'd definitely be interested in logs even from stable to try and confirm exactly what's going on. If you could enable the [analysis server log](https://dartcode.org/docs/logging/#analyzer) and grab a copy next time you see this (note: it will include parts of your source files), please let me know (in the https://github.com/Dart-Code/Dart-Code/issues/3270 thread) and I can give you some notes on what to look for to extract relevant parts of the log (or if you can repro using a public project and can share the whole log, you can send it to logs@dartcode.org).

Thanks!

**Comment by jonataslaw** [comment] 2021-05-25 00:22
Since I upgraded to Flutter 2.2 the problem has worsened. I'm getting this for all of my big projects

**Comment by hiteshgarg002** [comment] 2021-05-25 07:53
Since Flutter v2.2, this issue is frequently occurring which is very annoying, I am having to restart the VS Code many a times.

**Comment by DanTup** [comment] 2021-05-25 11:28
Please see [my comment above](https://github.com/Dart-Code/Dart-Code/issues/2341#issuecomment-823904614). I'm very interested in some logs of this happening. If you're seeing it a lot, please consider enabling the logs (note: the logs will include parts of your source code so be careful posting them if your codebase is sensitive).

**Comment by DanTup** [comment] 2021-05-25 11:29
Also - please continue this discussion in https://github.com/Dart-Code/Dart-Code/issues/3270, as that's an open issue about this problem. I'll lock this one to keep the discussion in the open issue.
