### ISSUE TITLE
App stuck when using debugger

### ISSUE THREAD

**Issue by chirastefan** [Dart-Code/Dart-Code#4958] opened 2024-01-24 23:54 UTC
**Describe the bug**
Starting the project with a debugger and using a breakpoint crashes the app after a few seconds. Everything gets stuck and if I try to do a hot reload/restart it gets stuck in the performing hot restart state.

I cannot give access to the codebase, but I have some logs captured with "Capture extension logs" and "Capture logs" actions that I can share privately.

**Screenshots**
<img width="484" alt="Screenshot 2024-01-25 at 01 50 51" src="https://github.com/Dart-Code/Dart-Code/assets/16649178/90839ecf-c9eb-4e33-8898-d891067b540b">

 - Operating System and version:
 - VS Code version:
Version: 1.85.2 (Universal)
Commit: 8b3775030ed1a69b13e4f4c628c612102e30a681
Date: 2024-01-18T06:40:32.531Z
Electron: 25.9.7
ElectronBuildId: 26354273
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin arm64 23.2.0
 - Flutter extension version: 3.80.0
 - Dart extension version: 3.80.0
 - Dart/Flutter SDK version: 
Flutter 3.16.8 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 67457e669f (8 days ago) • 2024-01-16 16:22:29 -0800
Engine • revision 6e2ea58a5c
Tools • Dart 3.2.5 • DevTools 2.28.5
 - Target device (if the issue relates to Flutter debugging): ios Simulator

Flutter doctor command has everything checked.

**Comment by DanTup** [comment] 2024-01-25 10:37
Based on the report and that you're on an ARM Mac, I believe this is a duplicate of https://github.com/Dart-Code/Dart-Code/issues/4926.

The issue is a deadlock in the VM when modifying breakpoints and has recently been fixed via https://github.com/dart-lang/sdk/issues/54650.

There's a hotfix request at https://github.com/dart-lang/sdk/issues/54699 that was recently closed, so I expect that will soon be rolled into Flutter and a hotfix made to the Flutter stable channel. I believe these are usually done weekly, so it could appear this week or next week.

If you think this isn't the same issue, please let me know!

**Closed by DanTup** 2024-01-25 10:37 UTC
Labels: is bug

**Comment by chirastefan** [comment] 2024-01-25 20:39
> Based on the report and that you're on an ARM Mac, I believe this is a duplicate of #4926.
> 
> The issue is a deadlock in the VM when modifying breakpoints and has recently been fixed via [dart-lang/sdk#54650](https://github.com/dart-lang/sdk/issues/54650).
> 
> There's a hotfix request at [dart-lang/sdk#54699](https://github.com/dart-lang/sdk/issues/54699) that was recently closed, so I expect that will soon be rolled into Flutter and a hotfix made to the Flutter stable channel. I believe these are usually done weekly, so it could appear this week or next week.
> 
> If you think this isn't the same issue, please let me know!

Most probably this is related to that issue.

**Comment by DanTup** [comment] 2024-01-25 21:02
Looks like this [has made it](https://github.com/flutter/flutter/wiki/Hotfixes-to-the-Stable-Channel#3169-january-25-2024) to the Flutter stable channel. Please run `flutter upgrade` and ensure you get 3.16.9 and let me know if you're still seeing the issue.

**Comment by chirastefan** [comment] 2024-01-25 22:15
it doesn't seem to happen anymore

**Comment by DanTup** [comment] 2024-01-27 12:08
Great, thanks for confirming! :)

**Comment by simplenotezy** [comment] 2024-02-08 13:05
I have been struggling with frequent "Flutter: Hot restarting..." errors for past 1-2 years of development

After upgrading the debugging experience defiently seems more responsive and smoother - so really good job here.

I just experienced my first crash since yesterday after updating - it happened without using breakpoints though. I also don't recall breakpoints being the main reason behind the freezes, although they defiantly don't help it.

I am open to provide any info I can to narrow this issue down further, since I believe it seriously hinders productivity.

https://github.com/flutter/flutter/issues/142983#issuecomment-1931516158

**Comment by DanTup** [comment] 2024-02-08 14:39
@simplenotezy can you test whether this still occurs on the latest stable SDK (your linked issue is the previous stable) and if so open a new issue. If you're able to reproduce this on any public/open source project, please include details (it's much easier to track down issues when I can use the same project). Thanks!

**Comment by simplenotezy** [comment] 2024-02-10 12:37
Hey @DanTup - I've opened an issue. I can privately add you to our project, if you think it could help tracking down this bug

**Comment by simplenotezy** [comment] 2024-02-19 20:55
It's by the way worth mentioning that the error also occurs if you simply save your file quickly - not necessarily press the "Hot restart" button. I think that's actually why I experience it often; because I am often quick to save my file multiple times within a few seconds, possibly a disorder inherited back from FTP days.

**Comment by Jesse-Abruzzo** [comment] 2024-07-31 17:54
Im having the same issue. It crashes in the web_entrypoint.dart file. it breaks there. if i conitnue it, it freezes and never recovers. everytime. happened after i updated to 3.22.3

**Comment by DanTup** [comment] 2024-07-31 18:15
@Jesse-Abruzzo please open a new issue with the details. First try to reproduce in a newly created project (so it's easy for me to test with the same thing). You can capture a debugging log using the steps below (but be aware it may contain parts of source code from your project - another reason to repro in a clean one):

- Run the [**Dart: Capture Debugging Logs** command](https://dartcode.org/docs/logging/#capture-debugging-logs)
- Reproduce the issue
- Click **Cancel** on the logging notification to stop logging and open the log
- Remove anything sensitive from the log
- Attach the log to the new issue or email to me at logs@dartcode.org and include the new issue number.
