### ISSUE TITLE
Create missing override(s) quickfix not showing for empty classes.

### ISSUE THREAD

**Issue by pitriq** [Dart-Code/Dart-Code#4184] opened 2022-09-27 13:54 UTC
**Describe the bug**

When creating an empty class that `extends` another one, the "Create n missing override(s)" quickfix is not appearing. In fact vscode says there are no quickfixes available at all. Once I write a single character inside the class, quickfixes start showing up.

This does not happen when using `implements`.

I'm not sure whether this is an extension or a language server issue. Feel free to close this and refer me to the correct repo.

**To Reproduce**

1. Create an empty class that extends another class that has abstract methods.
2. Press `cmd+.` anywhere in the class name.

**Expected behavior**

It should display the appropriate quickfixes.

**Screenshots**

![image](https://user-images.githubusercontent.com/8726539/192542377-3f388fd3-47da-4429-99da-e500b085994e.png)
![image](https://user-images.githubusercontent.com/8726539/192542418-614ce56c-0fb0-4e05-bb86-731e491f8813.png)
![image](https://user-images.githubusercontent.com/8726539/192542438-058944ed-09ed-4363-9d32-49868d48ef75.png)
![image](https://user-images.githubusercontent.com/8726539/192542466-11862cab-a6fa-4598-bad2-2ff3d0ab04bf.png)

**Please complete the following information:**
 - Operating System and version: macOS 12.6
 - VS Code version: 1.71.2
 - Dart extension version: v3.49.20220926
 - Dart/Flutter SDK version: dart 2.18.1, Flutter 3.3.2 stable

These are the the logs of pressing `cmd+.` on the empty class' name, captured with **Dart: Capture Analysis Server Logs**.

<details>
<summary>Details</summary>

!! PLEASE REVIEW THIS LOG FOR SENSITIVE INFORMATION BEFORE SHARING !!

Dart Code extension: 3.49.20220926
Flutter extension: 3.48.0 (activated)

App: Visual Studio Code
Version: 1.71.2
Platform: mac

Workspace type: Flutter
Analyzer type: LSP
Multi-root?: true

Dart SDK:
    Loc: LOCATION
    Ver: 2.18.1
Flutter SDK:
    Loc: LOCATION
    Ver: 3.3.2

HTTP_PROXY: undefined
NO_PROXY: undefined

Logging Categories:
    General, Analyzer, CommandProcesses

Tue Sep 27 2022 [10:19:46 GMT-0300 (Argentina Standard Time)] Log file started
[10:19:57 AM] [Analyzer] [Info] ==> Content-Length: 742
[10:19:57 AM] [Analyzer] [Info] ==> {"jsonrpc":"2.0","id":49,"method":"textDocument/codeAction","params":{"textDocument":{"uri":"FILE_URI"},"range":{"start":{"line":2,"character":8},"end":{"line":2,"character":8}},"context":{"diagnostics":[{"range":{"start":{"line":2,"character":6},"end":{"line":2,"character":9}},"message":"Missing concrete implementations of 'CustomPainter.paint' and 'CustomPainter.shouldRepaint'.\nTry implementing the missing methods, or make the class abstract.","code":"non_abstract_class_inherits_abstract_member","codeDescription":{"href":"file:///diagnostics/non_abstract_class_inherits_abstract_member"},"severity":1,"source":"dart"}],"triggerKind":1}},"clientRequestTime":1664284797019}
[10:19:57 AM] [Analyzer] [Info] <== Content-Length: 126
Content-Type: application/vscode-jsonrpc; charset=utf-8
[10:19:57 AM] [Analyzer] [Info] <== {"id":49,"jsonrpc":"2.0","error":{"code":-32001,"message":"An error occurred while handling textDocument/codeAction request"}}
[10:19:57 AM] [Analyzer] [Info] <== Content-Length: 2800
Content-Type: application/vscode-jsonrpc; charset=utf-8

{"jsonrpc":"2.0","method":"window/logMessage","params":{"message":"An error occurred while handling textDocument/codeAction request: RangeError (end): Invalid value: Not in inclusive range 27..232: 26\n#0      RangeError.checkValidRange (dart:core/errors.dart:363:9)\n#1      _StringBase.substring (dart:core-patch/string_patch.dart:400:27)\n#2      SnippetBuilderExtensions.appendPlaceholders (package:analysis_server/src/lsp/snippets.dart:332:23)\n#3      _buildSnippetString (package:analysis_server/src/lsp/snippets.dart:135:7)\n#4      buildSnippetStringForEditGroups (package:analysis_server/src/lsp/snippets.dart:26:5)\n#5      snippetTextEditFromEditGroups (package:analysis_server/src/lsp/mapping.dart:928:14)\n#6      toSnippetTextEdits (package:analysis_server/src/lsp/mapping.dart:1508:22)\n#7      createWorkspaceEdit (package:analysis_server/src/lsp/mapping.dart:150:24)\n#8      CodeActionHandler._createFixAction (package:analysis_server/src/lsp/handlers/handler_code_actions.dart:226:13)\n#9      CodeActionHandler._getFixActions.<anonymous closure> (package:analysis_server/src/lsp/handlers/handler_code_actions.dart:423:30)\n#10     MappedListIterable.elementAt (dart:_internal/iterable.dart:413:31)\n#11     ListIterator.moveNext (dart:_internal/iterable.dart:342:26)\n#12     List.addAll (dart:core-patch/growable_array.dart:319:13)\n#13     CodeActionHandler._getFixActions (package:analysis_server/src/lsp/handlers/handler_code_actions.dart:421:23)\n<asynchronous suspension>\n#14     OperationPerformanceImpl.runAsync (package:analyzer/src/util/performance/operation_performance.dart:164:18)\n<asynchronous suspension>\n#15     Future.wait.<anonymous closure> (dart:async/future.dart:522:21)\n<asynchronous suspension>\n#16     CodeActionHandler._getCodeActions (package:analysis_server/src/lsp/handlers/handler_code_actions.dart:350:21)\n<asynchronous suspension>\n#17     OperationPerforma…
Tue Sep 27 2022 [10:20:02 GMT-0300 (Argentina Standard Time)] Log file ended

</details>

**Comment by DanTup** [comment] 2022-09-28 13:16
Thanks, I can reproduce this. Something seems odd with the edits being produced, there's a selection from 0-27 in the edit, which covers the range `"\n  @override\n  void paint(C"` which doesn't make sense, and the `C` at the end clashes with an edit group for `Canvas`.

```js
{
	"message": "Create 2 missing overrides",
	"edits": [
		{
			"file": "/Users/danny/Dev/TestStuff/flutter_counter/lib/dc4184.dart",
			"fileStamp": 0,
			"edits": [
				{
					"offset": 74,
					"length": 0,
					"replacement": "\n  @override\n  void paint(Canvas canvas, Size size) {\n    // TODO: implement paint\n  }\n\n  @override\n  bool shouldRepaint(covariant CustomPainter oldDelegate) {\n    // TODO: implement shouldRepaint\n    throw UnimplementedError();\n  }\n"
				}
			]
		}
	],
	"linkedEditGroups": [
		{
			"positions": [
				{
					"file": "/Users/danny/Dev/TestStuff/flutter_counter/lib/dc4184.dart",
					"offset": 100
				}
			],
			"length": 6,
			"suggestions": [
				{
					"value": "Canvas",
					"kind": "TYPE"
				},
				{
					"value": "Object",
					"kind": "TYPE"
				}
			]
		},
		{
			"positions": [
				{
					"file": "/Users/danny/Dev/TestStuff/flutter_counter/lib/dc4184.dart",
					"offset": 107
				}
			],
			"length": 6,
			"suggestions": []
		},
		{
			"positions": [
				{
					"file": "/Users/danny/Dev/TestStuff/flutter_counter/lib/dc4184.dart",
					"offset": 115
				}
			],
			"length": 4,
			"suggestions": [
				{
					"value": "Size",
					"kind": "TYPE"
				},
				{
					"value": "OffsetBase",
					"kind": "TYPE"
				},
				{
					"value": "Object",
					"kind": "TYPE"
				}
			]
		},
		{
			"positions": [
				{
					"file": "/Users/danny/Dev/TestStuff/flutter_counter/lib/dc4184.dart",
					"offset": 120
				}
			],
			"length": 4,
			"suggestions": []
		},
		{
			"positions": [
				{
					"file": "/Users/danny/Dev/TestStuff/flutter_counter/lib/dc4184.dart",
					"offset": 205
				}
			],
			"length": 13,
			"suggestions": [
				{
					"value": "CustomPainter",
					"kind": "TYPE"
				},
				{
					"value": "Listenable",
					"kind": "TYPE"
				},
				{
					"value": "Object",
					"kind": "TYPE"
				}
			]
		},
		{
			"positions": [
				{
					"file": "/Users/danny/Dev/TestStuff/flutter_counter/lib/dc4184.dart",
					"offset": 219
				}
			],
			"length": 11,
			"suggestions": []
		}
	],
	"selection": {
		"file": "/Users/danny/Dev/TestStuff/flutter_counter/lib/dc4184.dart",
		"offset": 74
	},
	"selectionLength": 27,
	"id": "dart.fix.create.missingOverrides"
}
```

**Comment by pitriq** [comment] 2022-09-28 14:30
Oh ok, so this is a problem with `CustomPainter` in particular. Maybe I should rename the issue.

Thanks for looking into it :)

**Comment by DanTup** [comment] 2022-09-28 14:37
@pitriq it's not specific to `CustomPainter`, but depending on the exact names or the overrides being produced, it may/may not be triggered. In some cases, it will work, but the selected text will be incorrect. In this case, the selected text clashes with an edit group and that causes an exception.

I've tracked down the cause (and found a few similar related issues) and just working on some tests. The issue is in the Dart SDK, so the fix will ultimately ship with an SDK update rather than a Dart-Code update.

**Comment by DanTup** [comment] 2022-09-29 08:48
Fixed by https://github.com/dart-lang/sdk/commit/d97c3e8702b4e07349e0816452ff5ec47914ef3e. Will ship in a future Dart SDK.

**Closed by DanTup** 2022-09-29 08:48 UTC
Labels: is bug, in editor, in lsp/analysis server
