### ISSUE TITLE
Warnings/Lints appear in Problems view when reviewing commit changes.

### ISSUE THREAD

**Issue by Skylled** [Dart-Code/Dart-Code#901] opened 2018-05-14 23:35 UTC
This is a hard one to summarize for title.

I fixed a bunch of deprecation warnings in my code today, and when I was reviewing my changes for commit, the warnings re-appeared while I had the comparison view open.

Close the comparison view and the warnings disappear.

[Screenshot](https://imgur.com/Eg9Uxm8)

This seems to indicate that the analyzer is getting a hold of the unchanged code from Git.

**Comment by DanTup** [comment] 2018-05-15 06:38
That is weird! I can't repro here, I committed broken code, fixed it, saved, then opened the diff; and the error did not come back. Could you capture an [analysis server log](https://dartcode.org/docs/logging/#analyzer) so we can see what's happening?

**Comment by Skylled** [comment] 2018-05-15 13:33
Here are the logs starting from opening the editor in a normal state, opening the diff, and closing the diff again.
https://pastebin.com/HrW0qBpm

**Comment by DanTup** [comment] 2018-05-15 14:57
So, the log shows that when you opened the diff, we sent the contents of the old version of the file (I assume it's that) over to the server and said that's what the content is like (so obviously, the server sent errors).

Without reproducing, it's hard to know whether there's anything in the events that would allow us to detect this (I'm also curious why I don't see it!).

If you'd like to dig into this; you could put a breakpoint in FileChangeHandler (file_change_handler.ts) in the onDidChangeTextDocument and onDidOpenTextDocument methods and see which one is firing and whether there's any obvious difference between the git one and the new one.

Btw, are you in Stable or Insiders? And do you have any extensions that might affect things?

**Comment by DanTup** [comment] 2018-05-15 15:09
Ok, debugged this more. For me, the reason that the events of opening the diff don't get transmitted is that in `onDidOpenTextDocument` we have:

```ts
if (!util.isAnalyzable(document))
    return;
```

Inside that function we ensure the document's `scheme` is `file` (it's not for git diff docs, it's `git`).

So, I'm wondering why this isn't happening for you.. You could open the dev tools and put a breakpoint inside `isAnalyzable` to see why it doesn't bail  out for one of the two events when you open the diff (you could test from source, but if something has changed since the version you have, you not be able to repro it).

**Comment by DanTup** [comment] 2018-05-15 15:10
Aha, that check didn't used to exist! :(

**Comment by DanTup** [comment] 2018-05-15 15:13
https://code.visualstudio.com/updates/v1_23#_filesystem-providers

> Watch out: TextDocument.isUntitled
> 
> Due to the addition of FileSystem Providers, we have adjusted the semantics of `TextDocument.isUntitled` to be true only for newly created documents (using the untitled scheme). Before, all documents not from disk were treated as untitled. This change might alter the behavior of your extension, especially if it assumes that documents that aren't untitled are stored on disk.

I think that change is the cause. If so, that's a fairly subtle way to call out what seems to be a big breaking change - previously these git Windows may have returned `true` for `isUntitled` and now they don't.

It's fixed by the fix for #874 by coincidence. I'll building a beta of v2.13 soon so you can test out if it's resolved.

**Comment by DanTup** [comment] 2018-05-17 06:41
Fixed in 71cb24beefde97881773f5fffd165a55e5aa9edc

**Closed by DanTup** 2018-05-17 06:41 UTC
Labels: in editor, is bug

**Comment by Skylled** [comment] 2018-05-17 13:03
Thanks, Danny! Glad it was a convenient fix.
