### ISSUE TITLE
Auto Hot Reload Flutter on VSCode

### ISSUE THREAD

**Issue by callmejm** [Dart-Code/Dart-Code#2859] opened 2020-10-08 17:02 UTC
**Describe the bug**
when save file , vscode not auto hot reload flutter, this function I checked is from dart/flutter, think not from vscode 

**Versions (please complete the following information):**
 - VS Code version: 1.49.3
 - Dart extension version: 3.15.0
 - Dart/Flutter SDK version: 3.15.0

**Comment by DanTup** [comment] 2020-10-08 17:30
Thanks for the report! A few questions:

- How are you launching the app? From the terminal, or the Run menu / pressing `F5`?
- What type of device are you running the app on? Is it a mobile/desktop or web?
- When you save, do you see "x libraries reloaded" written to the Debug Console?

**Comment by callmejm** [comment] 2020-10-09 04:05
> Thanks for the report! A few questions:
> 
> * How are you launching the app? From the terminal, or the Run menu / pressing `F5`?
> * What type of device are you running the app on? Is it a mobile/desktop or web?
> * When you save, do you see "x libraries reloaded" written to the Debug Console?

Hi, thank for reply

1. I using the right panel, a play button with a bug icon named Run (Ctrl+Shift+D)
2. I using android simulator Pixel 2 API 29 (android-x86) and also device VCE L22 (android-arm64) / only mobile development
3. Nothing written to the console

**Comment by callmejm** [comment] 2020-10-11 07:54
any update ？

**Comment by DanTup** [comment] 2020-10-12 11:21
Could you try capturing a log:

- Run the **Dart: Capture Logs** command from the VS Code command palette
- Untick **Analysis Server** but leave everything else ticked
- Reproduce the issue, saving a few times
- Click **Cancel** on the logging notification to stop logging and open the log file
- Paste the log into a [gist](https://gist.github.com/) (ensuring it contains nothing sensitive)

Also, can you ensure this setting is enabled:

<img width="1017" alt="Screenshot 2020-10-12 at 12 21 45" src="https://user-images.githubusercontent.com/1078012/95741054-8070ec80-0c85-11eb-85d7-fe2873de467b.png">

Thanks!

**Comment by callmejm** [comment] 2020-10-12 17:06
@DanTup https://gist.github.com/callmejm/fd1cbc389ac893214621fcdafb77f0c2 is this the log ?

**Comment by DanTup** [comment] 2020-10-12 17:11
@callmejm that log appears to be empty (the last two lines have nothing between them). Did you reproduce the issue while the log was running (while the notification is visible, before clicking Cancel)?

**Comment by callmejm** [comment] 2020-10-12 17:15
@DanTup yes, I saw a dialog show up on bottom right corner, then I click multiple time to save edited file, but nothing happen on reload

**Comment by DanTup** [comment] 2020-10-12 17:16
Could you try starting the log file before you run the application?

So:

- Start capturing logs
- Run the application
- Make some changes and click save
- Stop the log

Thanks!

**Comment by callmejm** [comment] 2020-10-12 17:17
@DanTup try it on simulator or actual device ?

**Comment by DanTup** [comment] 2020-10-12 17:21
Either should be fine, it should work the same for both.

**Comment by callmejm** [comment] 2020-10-12 17:29
@DanTup this is the result https://gist.github.com/callmejm/fd340d74c0500f2d2f2dea42a4eb702c

**Comment by callmejm** [comment] 2020-10-12 17:33
@DanTup this is the result https://gist.github.com/callmejm/3797804be1f843fa726020a234b8b451

**Comment by DanTup** [comment] 2020-10-12 17:33
@callmejm that link seems to be a 404 for me.

**Comment by DanTup** [comment] 2020-10-12 17:40
I think you're seeing the issue described here:

https://github.com/Dart-Code/Dart-Code/issues/2775

I think it's been fixed since, but your Flutter version is slightly out of date. Can you try running `flutter upgrade` to see if that fixes it, and if not, confirm which Flutter channel you're on? Thanks!

**Comment by callmejm** [comment] 2020-10-13 01:59
@DanTup my another pc running 1.22.0-10.0.pre.65 are able to save hot reload

**Comment by DanTup** [comment] 2020-10-13 06:40
@callmejm that's a different version to you're using here (1.22.0-10.0.pre.221). Can you confirm which Flutter channel you're on, and try either a newer version, or the same version from your other machine? I believe this is the issue linked above and is likely fixed in Flutter. Thanks!

**Comment by callmejm** [comment] 2020-10-13 13:05
@DanTup thank for the guide , I remove current flutter sdk and download a stable version `1.22.1` , now can save with hot reload !
![image](https://user-images.githubusercontent.com/6957533/95864348-dc2b9a80-0d97-11eb-9820-d76a1dbb83b4.png)

**Closed** 2020-10-13 13:16 UTC
Labels: awaiting info, is bug
