### ISSUE TITLE
Unverified breakpoints in specific file

### ISSUE THREAD

**Issue by NicolasDionB** [Dart-Code/Dart-Code#2221] opened 2020-01-15 15:21 UTC
I have a Flutter project and have been debuging it for a while now using VSCode. I just found recently that, in a specific file, all my breakpoints are marked "Unverified" when I start debugging my project from VSCode.

My file is imported same as all the others, nothing special. I have a core class which instantiates my managers, like so:

```dart
import 'package:bloc/bloc.dart';
import 'package:meta/meta.dart';

import 'package:live_app/managers/chat/chat_manager.dart';
import 'package:live_app/managers/user/user_manager.dart';

class BaseCore extends Bloc<CoreBaseEvent, CoreBaseState> {
  UserManager _userManager;
  IUserManager get userManager => _userManager;

  ChatManager _chatManager;
  IChatManager get chatManager => _chatManager;

  BaseCore() {
    _userManager = UserManager(_hubConnection);
    _chatManager = ChatManager(_hubConnection, EHubPacketType.VROOMCHAT, _userManager);
  }

  // ...
```

I can place a breakpoint in my `UserManager` and it works, while placing one in my `ChatManager` doesn't. Any idea?

I'm using VSCode 1.41.1 on Windows 10, with Dart-Code extension 3.7.1.

**Comment by DanTup** [comment] 2020-01-15 15:27
Could you capture a log (as described at https://github.com/Dart-Code/Dart-Code/issues/2220#issuecomment-574702901) while reproducing this? You should start logging *before* running the app, since breakpoints are sent at the start of the debug session. Thanks!

**Comment by NicolasDionB** [comment] 2020-01-15 18:07
@DanTup I have to start _Dart: Capture Logs_ before so start debugging in order to get relevant information in that case. The log itself is about 2500 long but I found this trace which seems to be related:

```
...
[11 h 43 min 50 s] [Observatory] [Info] [Dart & Flutter] UnimplementedError
#0      ChromeProxyService.setLibraryDebuggable (package:dwds/src/services/chrome_proxy_service.dart:450:5)
#1      VmServerConnection._delegateRequest (package:vm_service/vm_service.dart:1124:51)
<asynchronous suspension>
#2      _rootRunUnary (dart:async/zone.dart:1132:38)
#3      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#4      _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#5      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#6      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#7      _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:132:11)
#8      _MapStream._handleData (dart:async/stream_pipe.dart:232:10)
#9      _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:164:13)
#10     _rootRunUnary (dart:async/zone.dart:1132:38)
#11     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#12     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#13     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#14     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#15     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:764:19)
#16     _StreamController._add (dart:async/stream_controller.dart:640:7)
#17     _StreamController.add (dart:async/stream_controller.dart:586:5)
#18     new WebSocketImpl.fromSocket.<anonymous closure> (package:web_socket_channel/src/copy/web_socket_impl.dart:719:21)
#19     _rootRunUnary (dart:async/zone.dart:1132:38)
#20     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#21     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#22     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#23     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#24     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#25     _EventSinkWrapper.add (dart…
[11 h 43 min 50 s] [Observatory] [Info] [Dart & Flutter] ==> {"id":"1145","method":"addBreakpointWithScriptUri","params":{"isolateId":"1","scriptUri":"file:///D:/Dev_Git/ClientApps/live_app/lib/managers/chat/chat_manager.dart","line":113}}
...
```

Do you still need the full log?

**Comment by DanTup** [comment] 2020-01-16 15:01
@NicolasDionB that specific error is expected - right now the debug proxy doesn't support `setLibraryDebuggable`, but this should not affect breakpoints (it's used to enable/prevent stepping into specific libraries, but libraries are debuggable by default).

The full log may still be helpful (if you don't want to share it publicly, you could email it to me - logs@dartcode.org), or if you can trim the project down to something you can share so I could try to repro myself, that may make it easier to debug.

**Comment by NicolasDionB** [comment] 2020-01-16 18:25
@DanTup I tried posting it here but it's too long so I emailed it to you. Hope it will help.

**Comment by DanTup** [comment] 2020-01-21 16:12
Sorry for the delay. I took a look in the log and it seems like the proxy is rejecting the breakpoint:

```
[13 h 19 min 10 s] [Observatory] [Info] [Dart & Flutter] ==> {"id":"1151","method":"addBreakpointWithScriptUri","params":{"isolateId":"1","scriptUri":"file:///D:/Dev_Git/ClientApps/live_app/lib/managers/chat/chat_manager.dart","line":194}}
[13 h 19 min 10 s] [Observatory] [Info] [Dart & Flutter] <== {"jsonrpc":"2.0","error":{"code":102,"data":null,"message":"The VM is unable to add a breakpoint at the specified line or function"},"id":"1151"}
[13 h 19 min 10 s] [Observatory] [Error] [Dart & Flutter] The VM is unable to add a breakpoint at the specified line or function
```

This comes from here:

https://github.com/dart-lang/webdev/blob/0ebfb41b3c70d2b9a2476a563af77c9fcc3bf5fb/dwds/lib/src/debugging/debugger.dart#L608

Based on the comment, it sounds like this is when a breakpoint can't be added on that exact line - but from your description it sounds like it doesn't work on any lines? If you add breakpoints to the few surrounding lines in that file, do any of them work?

If not, is there any way you could take a copy of this project and strip it down to something you're able to share? @alan-knight is there a good way to debug something like this? My guess is that `locationsForDart` isn't working as expected, but I don't know if there's an easy way to inspect the data it's using to try and map paths.

**Comment by NicolasDionB** [comment] 2020-01-21 16:30
@DanTup Thanks for investigation. Indeed I tried to add breakpoints to different location (variable declaration, method declaration, if/else statements, etc.) and nothing worked. It did work in some other file, which is odd. Stripping the project would be difficult. Maybe it is some kind of conflict with other files? I have no idea to be honest!

**Comment by DanTup** [comment] 2020-01-22 11:41
I'm not sure either - it may need input for the webdev devs (it may be worth opening an issue at https://github.com/dart-lang/webdev the info above and a link back here for better visibility). It may be difficult to track down without a repro though - I'm guessing it doesn't occur in a clean `flutter create` project?

**Comment by NicolasDionB** [comment] 2020-01-22 13:26
Indeed it doesn't occur in a new `flutter create` project. It might have something to do with the fact that we rely on conditional imports, such as this one, elsewhere in the project:

```dart
import 'package:live_app/util/webrtc/webrtc.dart' if (dart.library.html) 'package:live_app/util/webrtc/webrtc_web.dart';
```

The `ChatManager` class itself does not use such imports but I'm thinking that maybe it kind of breaks positionning of breakpoint themself?

**Comment by DanTup** [comment] 2020-01-22 15:29
It's possible, but I don't know enough about it. If it is that, maybe it could be repro'd in a new project you could share? (it's probably worth noting that on the webdev issue, in case it is relevant).

**Comment by NicolasDionB** [comment] 2020-01-22 16:21
@DanTup I have a trimmed version of the code, can I send it to you? It's not working in any way but it is compiling and I have the problem with the breakpoints in `chat_manager.dart`.

**Comment by NicolasDionB** [comment] 2020-01-22 16:24
Also I tried with removing my conditional imports and I get the same result so it has nothing to do with that.

**Comment by DanTup** [comment] 2020-01-22 18:15
@NicolasDionB yep, you can send to logs@dartcode.org if you don't want to post publicly (though please still ensure there's nothing secret/sensitive in there and trim any `build`/`.dart_tool` folders etc).

**Comment by DanTup** [comment] 2020-01-27 17:59
I did some digging into this and posted a possible fix in https://github.com/dart-lang/webdev/issues/874 so closing this one as I don't think there's anything to do in the VS Code extension.

**Closed by DanTup** 2020-01-27 17:59 UTC
Labels: upstream in dart / flutter

**Comment by NicolasDionB** [comment] 2020-01-28 13:22
@DanTup Thank you so much for your investigation! You guys work together often? Really effective. Thanks again!

**Comment by NicolasDionB** [comment] 2020-01-30 00:49
Webdev distribution is included in Flutter SDK right? Any idea when it's going to be available in Flutter SDK? Thanks!

**Comment by DanTup** [comment] 2020-01-30 16:40
> Webdev distribution is included in Flutter SDK right? 

dwds is, yep (it's a package that's part of webdev, but Flutter doesn't depend on the whole of webdev). There are two things that need to happen for this to show up in Flutter:

- A new dwds Pub package release
- Flutter updates its dependencies

I'm not sure when there plan for the next release is, though I have another PR in progress I'd like to land before asking for one, but it needs a little feedback first.

**Comment by NicolasDionB** [comment] 2020-01-30 16:42
That's all good. Thanks again for your time!
