### ISSUE TITLE
Support --flavor argument in the debugger

### ISSUE THREAD

**Issue by lukef** [Dart-Code/Dart-Code#535] opened 2018-02-08 02:45 UTC
`flutter run` accepts `--flavor` for Android product flavors and Xcode schemes. If you're using one of the aforementioned, debugging will fail with the following error (Android):

```
The Gradle project does not define a task suitable for the requested build.
The android/app/build.gradle file defines product flavors: <list of flavor options>
You must specify a --flavor option to select one of them.
```

For context, this is the flag description:

```
--flavor                       Build a custom app flavor as defined by platform-specific build setup.
                                   Supports the use of product flavors in Android Gradle scripts.
                                   Supports the use of custom Xcode schemes.
```

**Comment by DanTup** [comment] 2018-02-08 09:27
I'm unfamiliar with this functionality - is there a sample app anywhere that uses it I can use to repro and test the change? Or is it simple for me to modify one of the projects? (@devoncarew)

**Comment by devoncarew** [comment] 2018-02-08 15:38
I don't have a sample project for this myself; @lukef may?

Here's how we expose it in IntelliJ:

<img width="736" alt="screen shot 2018-02-08 at 7 33 32 am" src="https://user-images.githubusercontent.com/1269969/35981606-82ee8be2-0ca2-11e8-8fd4-10fbcbe045c5.png">

It's a free-form text field; if there's something in there, then we pass `--flavor=xxx` in via flutter run, else we don't pass the flag. Since these are defined in gradle (or ios) files, we don't try and to any validation of the flavor param client side.

**Comment by DanTup** [comment] 2018-02-08 15:42
Sounds simple enough; though I'd prefer if I could confirm it definitely works before shipping and announcing it's supported. We do have some other options that are more generic (`pubAdditionalArgs`?), so we could also do something like that and allow you to put whatever you want in (this would be useful if people might extend this with their own switches, though since `flutter run --help` explicitly lists `flavor` I guess this is a well-known thing and not user-defined).

**Comment by DanTup** [comment] 2018-02-08 15:44
Will aim to do this in v2.9; seems simple and sounds like it could stop people being able to use F5.

**Comment by DanTup** [comment] 2018-02-12 10:43
Ok, I think maybe the existing `args` already supports this. I just set my `launch.json` like this:

```js
{
	"name": "Flutter",
	"request": "launch",
	"type": "flutter",
	"args": [
		"--flavor",
		"red"
	]
}
```

When I hit F5, I get this in the debug console:

```
The Gradle project does not define a task suitable for the requested build.
The android/app/build.gradle file does not define any custom product flavors.
You cannot use the --flavor option.
```

So, I don't think we need to do anything here. We could add an additional `flavor` setting, but I don't know how much value there is in it. Any opinions?

**Comment by devoncarew** [comment] 2018-02-12 15:54
Using the existing args sgtm. Perhaps there are some 'using dart-code' docs we could update?

**Comment by lukef** [comment] 2018-02-12 17:08
Does VS Code have any provision to do this on a project basis? I know it wont be a fail for apps that don't need it but it could be a problem if you use flavors and work on multiple projects. Its probably a separate issue but just throwing it out there.

**Comment by DanTup** [comment] 2018-02-12 17:13
@devoncarew 

> Perhaps there are some 'using dart-code' docs we could update?

Not currently; though I'd really like to address this soon. Even the readme is rather lacking (in terms of helping a new user get started). Maybe this would fit nice on a FAQ page?

@lukef 

> Does VS Code have any provision to do this on a project basis?

Yep, the snippet I posted is from the `.vscode\launch.json` file which lives inside your project (FWIW, it actually is a fail for apps that don't need it - the fail with a similar message!).

Let me know if you can't get it working (there's a [Gitter chat](https://gitter.im/dart-code/Dart-Code) that might be easier for troubleshooting).

**Comment by DanTup** [comment] 2018-02-13 11:59
I've opened #557 about better docs/faq so gonna WontFix this. If anyone disagrees, shout!

**Closed by DanTup** 2018-02-13 11:59 UTC
Labels: in flutter, is enhancement

**Comment by searchy2** [comment] 2019-05-20 16:44
This article helped me solve the problem of build variants. https://cogitas.net/creating-flavors-of-a-flutter-app/

I was stuck for a bit because Flutter isn't very specific about Gradle build errors. The build error I received was `Gradle task assembleDebug failed with exit code 1`. 

The problem is that I was not adding the build variants to Flutter/build.gradle AND app/build.gradle.
The build variants need to be added to both to work correctly.

**Comment by krupalbhardiya** [comment] 2020-01-27 12:53
@DanTup  , please need this bug fixed. some projects do require debugging in multi-flavor apps.

**Comment by DanTup** [comment] 2020-01-27 15:06
@krupalbhardiya as far as I can tell, there is no bug here - you can use flavours by specifying them in the launch config `args` property (see https://github.com/Dart-Code/Dart-Code/issues/535#issuecomment-364886303). If you're having problems, please open a new issue with specific details of what's happening. Thanks!
