### ISSUE TITLE
DevTools doesn't launch Chrome on Windows

### ISSUE THREAD

**Issue by kenzieschmoll** [Dart-Code/Dart-Code#3964] opened 2022-05-16 17:08 UTC
Copying issue over from: https://github.com/flutter/devtools/issues/4051

from @johnpryan: "On Windows, DevTools doesn't show up when I run the "Open DevTools" command from the command palette if there isn't a browser running."

**Comment by DanTup** [comment] 2022-05-16 17:16
@johnpryan apologies - I missed the report of this in the DevTools repo.

I actually saw a similar issue just yesterday - the first load worked fine, but subsequent launches do not. Is that the same behaviour you're seeing?

I haven't dug into it yet, but I feel like something is going wrong in the DevTools server that tracks open browsers, and it's trying to reuse an existing window even after it's been closed.

**Comment by johnpryan** [comment] 2022-05-16 21:49
For me, it was only working if I already had Chrome open, but I can try to reproduce now that there's a new version of the SDK

**Comment by DanTup** [comment] 2022-05-17 10:37
@johnpryan odd, that sounds a bit different to what I was seeing (which is that if you've closed an existing DevTools browser tab, VS Code will no longer launch any for that debug session). I've filed https://github.com/Dart-Code/Dart-Code/issues/3966 to look into my issue.

Could you confirm if running `dart devtools` shows the same behaviour (eg. does it launch a browser window if there isn't already one open?)

If it does not show the same behaviour, could you try the following:

- run your debug session
- run the **Dart: Capture Debug Logs** command
- untick everything except **DevTools** and **Debugger VM Service** and click **OK**
- reproduce the issue (both successful, an unsuccessful launches)
- click **Cancel** on the logging notification to stop logging and open the log file
- attach the log here (or email to `logs@dartcode.org`)

**Comment by DanTup** [comment] 2022-05-30 15:09
@johnpryan can you still repro this? Are you able to capture a log (see above)?

If setting `"dart.devToolsBrowser": "default",` in your VS Code user settings seems to fix the issue, I suspect it's the same as https://github.com/Dart-Code/Dart-Code/issues/3966 (this will force us to launch your default browser from VS Code instead of trying to go through the DevTools server to launch Chrome, which sidesteps the issue).

**Comment by johnpryan** [comment] 2022-06-21 22:36
I can't reproduce this anymore, Chrome is launching for me.

**Comment by DanTup** [comment] 2022-06-22 09:38
Thanks for checking - I'll close this for now then. If it does come back, please let me know (and try to capture logs described in https://github.com/Dart-Code/Dart-Code/issues/3964#issuecomment-1128706602). Thanks!

**Closed by DanTup** 2022-06-22 09:38 UTC
Labels: is bug, awaiting info, in commands, in devtools
