### ISSUE TITLE
devTools 

### ISSUE THREAD

**Issue by shirlin520** [Dart-Code/Dart-Code#1921] opened 2019-08-12 02:04 UTC
Issue Type: <b>Bug</b>

devtools service failed to register

Extension version: 3.3.0
VS Code version: Code 1.37.0 (036a6b1d3ac84e5ca96a17a44e63a87971f8fcc8, 2019-08-08T01:22:37.660Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz (4 x 2300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 3|
|Memory (System)|8.00GB (0.60GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by DanTup** [comment] 2019-08-15 13:52
Can you confirm which version of DevTools you have installed by running `pub global list`?

**Comment by DanTup** [comment] 2019-08-19 10:51
Dupe of #1882.

**Closed by DanTup** 2019-08-19 10:51 UTC
Labels: awaiting info
