### ISSUE TITLE
Fatal error when build directory is added

### ISSUE THREAD

**Issue by bergwerf** [Dart-Code/Dart-Code#2455] opened 2020-05-13 12:59 UTC
`webdev build` writes output into a build directory. Apparently the plugin also analyzes that directory and runs into an issue. I don't know the mechanics behind this and if it can be fixed in the plugin, but it kills the analyzer at startup unless the build directory is deleted which is rather annoying. Here is the log:
```

### Request

Server was responding to request: `analysis.setAnalysisRoots`

### Versions

- Visual Studio Code v1.45.0
- Dart Code v3.10.1
- Flutter SDK v1.12.13+hotfix.9

### Analyzer Info

The analyzer was launched using the arguments:

- /usr/lib/dart/bin/snapshots/analysis_server.dart.snapshot
- --client-id=VS-Code
- --client-version=3.10.1

### Exception

FormatException: The resolved 'packageUri' must be inside the rootUri, actualy 'file:///' is not in 'file:///home/herman/repos/bergwerf/cruzzle2/build/packages/_fe_analyzer_shared/', for the package '_fe_analyzer_shared'.
{"configVersion":2,"packages":[{"name":"_fe_analyzer_shared","rootUri":"../...

#0      _PackageConfigJsonParser._parsePackage (package:analyzer/src/context/package_config_json.dart:199:9)
#1      _PackageConfigJsonParser._parsePackages (package:analyzer/src/context/package_config_json.dart:243:9)
#2      _PackageConfigJsonParser.parse (package:analyzer/src/context/package_config_json.dart:116:7)
#3      parsePackageConfigJson (package:analyzer/src/context/package_config_json.dart:13:49)
#4      parsePackageConfigJsonFile (package:analyzer/src/context/packages.dart:73:20)
#5      parsePackagesFile (package:analyzer/src/context/packages.dart:128:14)
#6      ContextManagerImpl._computeFolderDisposition (package:analysis_server/src/context_manager.dart:949:24)
#7      ContextManagerImpl._createContext (package:analysis_server/src/context_manager.dart:990:9)
#8      ContextManagerImpl._createContexts (package:analysis_server/src/context_manager.dart:1081:16)
#9      ContextManagerImpl._createContexts (package:analysis_server/src/context_manager.dart:1089:13)
#10     ContextManagerImpl.setRoots (package:analysis_server/src/context_manager.dart:644:9)
#11     AnalysisServer.setAnalysisRoots (package:analysis_server/src/analysis_server.dart:481:22)
#12     AnalysisDomainHandler.setAnalysisRoots (package:analysis_server/src/domain_analysis.dart:357:14)
#13     AnalysisDomainHandler.handleRequest (package:analysis_server/src/domain_analysis.dart:296:16)
#14     AnalysisServer.handleRequest.<anonymous closure>.<anonymous closure> (package:analysis_server/src/analysis_server.dart:319:40)
#15     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:256:15)
#16     AnalysisServer.handleRequest.<anonymous closure> (package:analysis_server/src/analysis_server.dart:315:50)
#17     _rootRun (dart:async/zone.dart:1184:13)
#18     _CustomZone.run (dart:async/zone.dart:1077:19)
#19     _runZoned (dart:async/zone.dart:1619:10)
#20     runZonedGuarded (dart:async/zone.dart:1608:12)
#21     AnalysisServer.handleRequest (package:analysis_server/src/analysis_server.dart:314:5)
#22     ByteStreamServerChannel._readRequest.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:171:16)
#23     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:256:15)
#24     ByteStreamServerChannel._readRequest (package:analysis_server/src/channel/byte_stream_channel.dart:161:47)
#25     ByteStreamServerChannel.listen.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:106:26)
#26     _rootRunUnary (dart:async/zone.dart:1192:38)
#27     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#28     _CustomZone.runUnaryGuarded (dart:async/zone.dart:987:7)
#29     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#30     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:266:7)
#31     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:70:11)
#32     _EventSinkWrapper.add (dart:async/stream_transformers.dart:17:11)
#33     _StringAdapterSink.add (dart:convert/string_conversion.dart:238:11)
#34     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:152:13)
#35     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:127:5)
#36     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:165:5)
#37     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:122:24)
#38     _rootRunUnary (dart:async/zone.dart:1192:38)
#39     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#40     _CustomZone.runUnaryGuarded (dart:async/zone.dart:987:7)
#41     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#42     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:266:7)
#43     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:70:11)
#44     _EventSinkWrapper.add (dart:async/stream_transformers.dart:17:11)
#45     _StringAdapterSink.add (dart:convert/string_conversion.dart:238:11)
#46     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:243:7)
#47     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:314:20)
#48     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:307:5)
#49     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:74:18)
#50     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:122:24)
#51     _rootRunUnary (dart:async/zone.dart:1192:38)
#52     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#53     _CustomZone.runUnaryGuarded (dart:async/zone.dart:987:7)
#54     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#55     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:266:7)
#56     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:779:19)
#57     _StreamController._add (dart:async/stream_controller.dart:655:7)
#58     _StreamController.add (dart:async/stream_controller.dart:597:5)
#59     _Socket._onData (dart:io-patch/socket_patch.dart:1982:41)
#60     _rootRunUnary (dart:async/zone.dart:1196:13)
#61     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#62     _CustomZone.runUnaryGuarded (dart:async/zone.dart:987:7)
#63     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#64     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:266:7)
#65     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:779:19)
#66     _StreamController._add (dart:async/stream_controller.dart:655:7)
#67     _StreamController.add (dart:async/stream_controller.dart:597:5)
#68     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1527:33)
#69     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1019:14)
#70     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#71     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#72     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#73     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
```

**Comment by DanTup** [comment] 2020-05-13 14:20
I can't reproduce this (I created a new angular app with stagehand, ran `webdev build` then restarted the analyzer), but suspect it might be down to some specific files in the `build` folder. Can you repro with a project you can share (ideally including the build folder as it is when you see this), and also could you enable the [analysis server log](https://dartcode.org/docs/logging/#analyzer) to capture the folders being sent as analysis roots?

Thanks!

**Comment by bergwerf** [comment] 2020-05-13 14:34
analyzer log: https://pastebin.com/CKJGuVyh
whole project: https://www.transfernow.net/f3S5d9052020
It is open-source so its not so confidential.

**Comment by DanTup** [comment] 2020-05-13 14:50
@bergwerf thanks, I can repro the crash.

@bwilkerson @devoncarew I believe this crash occurs because there's a file at `build/.dart_tool/package_config.json` that contains entries like:

```js
{
	"name": "_fe_analyzer_shared",
	"rootUri": "../packages/_fe_analyzer_shared",
	"packageUri": "",
	"languageVersion": "2.2"
},
```

I think the empty string at `packageUri` is resulting in a path of `file:///` which is then considered outside of the root. It's not clear to me if the issue is in the server or whether this file is bad. The [design docs for package_config.json](https://github.com/dart-lang/language/blob/master/accepted/future-releases/language-versioning/package-config-file-v2.md) say `packageUri` is "optional" but it's not clear if an empty string is expected to be treated the same as missing.

The file suggests it was generated by pub:

```
"generator": "pub",
"generatorVersion": "2.8.1"
```

**Comment by DanTup** [comment] 2020-05-13 14:58
Oh, this has been raised here:

https://github.com/dart-lang/pub/issues/2482

and fixed very recently here:

https://github.com/dart-lang/sdk/commit/8963497d5529f1d48a5dd60a22367d83b28c05f2

I'll close this as a dupe of https://github.com/dart-lang/pub/issues/2482 - you can follow there for updates and if you're able to use recent [nightly Dart SDK](http://gsdview.appspot.com/dart-archive/channels/be/raw/latest/sdk/), it may have the fix.

**Closed** 2020-05-13 14:58 UTC
Labels: fixed in dart / flutter
