### ISSUE TITLE
Cannot create avd after recent update ?

### ISSUE THREAD

**Issue by udithv** [Dart-Code/Dart-Code#1878] opened 2019-07-18 14:07 UTC
Recently updated the dart extension for vscode. Can't seem to create a new avd after the update. 

it says:

```
Error: avd not created

```

at the bottom right corner of the editor.

debug console and output are empty.

**Comment by DanTup** [comment] 2019-07-18 14:26
Can you provide a screenshot of where you're seeing this? Is it where you normally see a device name?

Can you also try running `flutter devices` from the terminal and post the output of that? Thanks!

**Comment by udithv** [comment] 2019-07-26 14:26
It's in Visual studio code..When I try creating a device after clicking on "No Devices" at the bottom left of the editor and clicking on "Create new emulator".

```
No devices detected.

Run 'flutter emulators' to list and start any available device emulators.

Or, if you expected your device to be detected, please run "flutter doctor" to diagnose potential issues, or visit
https://flutter.dev/setup/ for troubleshooting tips.
```

This is expected as no devices is action. However I can create a avd in android studio and use it launch an application. The issue is not being able to create an avd from vscode as before.

**Comment by DanTup** [comment] 2019-07-26 20:36
Can you provide a screenshot of where you're seeing this output and the *exact* steps you took? I understand it's in VS Code, but I'm a little confused about how there would be output saying "No devices detected" during emulator creation. A video/GIF would be useful.

Also - if you can run the **Dart: Capture Logs** command in VS Code, then try creating the emulator, and then click **Stop Logging** and attach the logs, that may help. Thanks!

**Comment by DanTup** [comment] 2019-08-22 10:00
Closing this since there's not enough info to investigate. Please let me know if this is still an issue and you can provide the info above.

It's also worth reviewing https://github.com/Dart-Code/Dart-Code/issues/1919 where there were similar emulator issues caused by having multiple Android SDKs.

**Closed by DanTup** 2019-08-22 10:00 UTC
Labels: awaiting info
