### ISSUE TITLE
StdinExceptions occurring with starting/restarting flutter apps

### ISSUE THREAD

**Issue by mjohnsullivan** [Dart-Code/Dart-Code#767] opened 2018-04-02 16:21 UTC
I'm getting an StdinException whenever I try to fully restart an app in DartCode. It also has started happening when I try to launch the app from within the IDE. Using flutter run from the command line works as expected. I've attached a screenshot to show the exception in VSCode.

<img width="1284" alt="screen shot 2018-04-02 at 9 16 45 am" src="https://user-images.githubusercontent.com/102488/38204282-2d1f7eea-3657-11e8-9d6a-7abebc1fb355.png">

**Comment by mjohnsullivan** [comment] 2018-04-02 16:22
FYI: this happens when the app is running, and not when the app's paused.

**Comment by DanTup** [comment] 2018-04-02 16:45
@mjohnsullivan What's the code you're calling in `main` on line 52? Is it just a print?

I found this in the Dart SDK repo, but sounds like it's Windows only and looks like you're on macOS :(

https://github.com/dart-lang/sdk/issues/28599

Do you know when it started happening? We did change how we spawn things recently to fix an issue with spaces in path names, I wonder if it might be related (that was [6 days ago](https://github.com/Dart-Code/Dart-Code/releases/tag/v2.11.1)).

**Comment by mjohnsullivan** [comment] 2018-04-02 17:30
I see the problem now you point that out. The project has both a Dart cmd line script and a Flutter project. For some reason, both F5 and running from debug menu appears to be trying to run bin/main.dart by default, which is the cmd line app. I've created a config:

{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Flutter",
            "type": "dart",
            "request": "launch",
            "program": "${workspaceFolder}/lib/main.dart"
        }
    ]
}

And when I run from the debug menu I get:

Launching lib/main.dart on iPhone X in debug mode...

However, it still appears to be trying to execute bin/main.dart and failing there.

**Comment by DanTup** [comment] 2018-04-02 17:53
> Launching lib/main.dart on iPhone X in debug mode...
> 
> However, it still appears to be trying to execute bin/main.dart and failing there.

The "Launching lib/main.dart" text is coming from `flutter run`, so it definitely shouldn't be trying to run `bin/main.dart` when you see that. Is it possible you could enable Flutter Run and Observatory logging, reproduce the issue and then attach or email me the logs?

https://dartcode.org/docs/logging/#flutter-run
https://dartcode.org/docs/logging/#observatory

Note: in the absence of a launch.json, we'll try to guess what to run based on your current open file, whether we find a lib/main.dart, a bin/main.dart etc.. If you've created a launch.json it should always use that.

**Comment by DanTup** [comment] 2018-04-13 15:33
@mjohnsullivan Are you still having these issues? Are you able to get some logs as detailed above?

**Comment by DanTup** [comment] 2018-04-27 14:05
@mjohnsullivan I'm closing this because I think this has been fixed with the bug mentioned above. If you still have issues though, let me know!

**Closed by DanTup** 2018-04-27 14:05 UTC
Labels: awaiting info, in debugger, is bug
