### ISSUE TITLE
VSCode stuck in Select a device to use

### ISSUE THREAD

**Issue by dmcpacks** [Dart-Code/Dart-Code#5050] opened 2024-03-27 21:07 UTC
**Describe the bug**
When pressing the "No Device" button, the popup states "select a device to use" with a loading bar below it. I am unable to select a device.

**To Reproduce**
1. Create a new project
2. Click on 'No Device'

**Expected behavior**
A selection menu to select the android emulator.

**Screenshots**
![image](https://github.com/Dart-Code/Dart-Code/assets/78316535/a351e0ee-70e7-4413-a956-2100e47a9707)

**Please complete the following information:**

You can run the **Dart: Collect Diagnostic Information** command from the VS Code command palette (`F1`) to easily capture this information or provide it manually.

<details>

<summary><strong>Workspace Environment</strong></summary>

```text
Dart Code extension: 3.84.0
Flutter extension: 3.84.0 (activated)

App: Visual Studio Code
App Host: desktop
Version: win 1.86.1

Workspace type: Flutter (LSP)

Dart (3.3.2): C:\Users\USER\Desktop\flutter\flutter\bin\cache\dart-sdk
Flutter (3.19.4): C:\Users\USER\Desktop\flutter\flutter (No device)

```

</details>

<details>

<summary><strong>Output from 'dart info'</strong></summary>

`C:\Users\USER\Desktop\flutter\flutter\bin\cache\dart-sdk\bin\dart.exe info`

If providing this information as part of reporting a bug, please review the information
below to ensure it only contains things you're comfortable posting publicly.

#### General info

- Dart 3.3.2 (stable) (Tue Mar 19 20:44:48 2024 +0000) on "windows_x64"
- on windows / "Windows 10 Pro" 10.0 (Build 22631)
- locale is en-US

#### Project info

- sdk constraint: '>=3.3.2 <4.0.0'
- dependencies: flutter
- dev_dependencies: flutter_lints, flutter_test

#### Process info

| Memory | CPU | Elapsed time | Command line |
| -----: | --: | -----------: | ------------ |
| 371 MB |  -- |              | dart.exe     |
|  96 MB |  -- |              | dart.exe     |
|  84 MB |  -- |              | dart.exe     |
|  96 MB |  -- |              | dart.exe     |

</details>

<details>

<summary><strong>Output from 'flutter doctor'</strong></summary>

`C:\Users\USER\Desktop\flutter\flutter\bin\flutter.bat doctor -v`

```text
[!] Flutter (Channel stable, 3.19.4, on Microsoft Windows [Version 10.0.22631.3007], locale en-US)
    • Flutter version 3.19.4 on channel stable at C:\Users\USER\Desktop\flutter\flutter
    ! Upstream repository unknown source is not a standard remote.
      Set environment variable "FLUTTER_GIT_URL" to unknown source to dismiss this error.
    • Framework revision 68bfaea224 (7 days ago), 2024-03-20 15:36:31 -0700
    • Engine revision a5c24f538d
    • Dart version 3.3.2
    • DevTools version 2.31.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\USER\AppData\Local\Android\sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-b2043.56-10550314)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[!] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.8.3)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.8.34330.188
    X Visual Studio is missing necessary components. Please re-run the Visual Studio installer for the "Desktop development with C++" workload, and include these components:
        MSVC v142 - VS 2019 C++ x64/x86 build tools
         - If there are multiple build tool versions available, install the latest
        C++ CMake tools for Windows
        Windows 10 SDK

[√] Android Studio (version 2023.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-b2043.56-10550314)

[√] IntelliJ IDEA Community Edition (version 2022.1)
    • IntelliJ at C:\Users\USER\AppData\Local\JetBrains\Toolbox\apps\IDEA-C\ch-0\221.5921.22
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] IntelliJ IDEA Community Edition (version 2022.2)
    • IntelliJ at C:\Users\USER\AppData\Local\JetBrains\Toolbox\apps\IDEA-C\ch-0\222.3345.118
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] VS Code (version 1.86.1)
    • VS Code at C:\Users\USER\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.84.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22631.3007]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 123.0.6312.86
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 122.0.2365.80

[√] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.
```

**Comment by DanTup** [comment] 2024-03-28 10:43
Could you click Help -> Toggle Developer Tools in VS Code and click the Console tab to see if there are any errors listed?

And could you also try enabling the Flutter Daemon log (see https://dartcode.org/docs/logging/#flutter-daemon) to see what it's logging when this happens?

Thanks!

**Comment by dmcpacks** [comment] 2024-03-28 17:55
Only saw this
  ERR File is not being analyzed: Error: File is not being analyzed
	at handleResponse (c:\Users\USER\.vscode\extensions\dart-code.dart-code-3.84.0\out\dist\extension.js:31486:48)
	at handleMessage (c:\Users\USER\.vscode\extensions\dart-code.dart-code-3.84.0\out\dist\extension.js:31266:13)
	at processMessageQueue (c:\Users\USER\.vscode\extensions\dart-code.dart-code-3.84.0\out\dist\extension.js:31283:17)
	at Immediate.<anonymous> (c:\Users\USER\.vscode\extensions\dart-code.dart-code-3.84.0\out\dist\extension.js:31255:13)
	at process.processImmediate (node:internal/timers:476:21)
![image](https://github.com/Dart-Code/Dart-Code/assets/78316535/bbb4f8fc-1515-4b32-81d8-43dbaa5aa6c3)

**Comment by XanderD99** [comment] 2024-03-28 20:35
I am seeing the same error, but for me, the analyzer just keeps running and intellisense  stops working

**Comment by dkozenkov** [comment] 2024-04-05 06:48
> Could you click Help -> Toggle Developer Tools in VS Code and click the Console tab to see if there are any errors listed?
> 
> And could you also try enabling the Flutter Daemon log (see https://dartcode.org/docs/logging/#flutter-daemon) to see what it's logging when this happens?
> 
> Thanks!

Hello, Danny!
I have exactly the same problem.
I am sending the information you requested in attached files.
The terminal command "flutter devices" successfully returns a list of devices.
And I can run the application on the desired device from the terminal, but not from VSCode.

```
PS C:\temp\3\flutter_application_1> flutter devices
3 connected devices:

Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19045.4239]
Chrome (web)      • chrome  • web-javascript • Google Chrome 123.0.6312.106 
Edge (web)        • edge    • web-javascript • Microsoft Edge 120.0.2210.144
```

[flutter_doctor.txt](https://github.com/Dart-Code/Dart-Code/files/14881010/flutter_doctor.txt)
![2024-04-05_10-42-37](https://github.com/Dart-Code/Dart-Code/assets/38919183/b92b746f-6d82-46a8-bb77-31287b5c4610)
[flutter_log.txt](https://github.com/Dart-Code/Dart-Code/files/14880853/flutter_log.txt)

**Comment by DanTup** [comment] 2024-04-17 11:40
Sorry for the delay, I missed this.

@dmcpacks thanks for the console log - I don't think that's related to this issue. I think you you (and @dkozenkov from the logs above) are seeing the issue described in https://github.com/Dart-Code/Dart-Code/issues/4840 / https://github.com/flutter/flutter/issues/143625, where the Flutter daemon stops working.

I'm interested to know whether this issue started recently (for example after upgrading a Flutter SDK), or whether it's always been this way.

@XanderD99 if you're seeing issues with the analyzer and code completion not working, please file another issue with more details as I don't think it's related to the devices list (but it's possible you're _also_ seeing this).

**Comment by dmcpacks** [comment] 2024-05-08 18:24
@DanTup Sorry for the wait, this is my first time using flutter. Fresh install. Also the flutter daemon seems to be working since I'm able to create new projects without any issues. The issue is also present in the new project.

**Comment by DanTup** [comment] 2024-05-09 08:59
@dmcpacks creating new projects doesn't use the Flutter device daemon so I don't think that indicates it's not a daemon issue. Are you able to enable the daemon log (see [this comment] above](https://github.com/Dart-Code/Dart-Code/issues/5050#issuecomment-2024889117)) and grab a copy after reproducing the issue?

**Comment by dmcpacks** [comment] 2024-05-15 01:24
Here's the log, noticed it says "Flutter extension: 3.88.0 (not activated)" even though the extension is enabled, do you know why this could be?

[flutterDaemon.txt](https://github.com/Dart-Code/Dart-Code/files/15315151/flutterDaemon.txt)

**Comment by DanTup** [comment] 2024-05-15 10:34
> noticed it says "Flutter extension: 3.88.0 (not activated)" even though the extension is enabled, do you know why this could be?

That's probably just that the Dart extension started this log file prior to the Flutter extension activating. It's nothing to worry about, most of the functionality is in the Dart extension and the Flutter extension will automatically activate if/when required.

From the log, it does look like this could be the same as https://github.com/Dart-Code/Dart-Code/issues/4840 / https://github.com/flutter/flutter/issues/143625. I don't fully understand the cause of that issue (it seems like the stdin stream used to communicate between VS Code and the `flutter` tool appears to close and the tool doesn't receive the messages being sent by VS Code).

Unfortunately I currently don't know of a workaround for this issue.

Do you know if this has ever worked in the past, or as far as you know has it always been this way?

**Comment by dmcpacks** [comment] 2024-05-15 15:03
As far as I know it has always been this way. I'll try using one of my old Macs in the meantime

**Comment by DanTup** [comment] 2024-05-20 13:55
@dmcpacks could you run `where.exe git` and `git version` in a PowerShell/terminal window and post the output?

There were some comments in https://github.com/Dart-Code/Dart-Code/issues/4840 about git version (and/or git from msys) and I'm trying to figure out if there may be a pattern here (so far I've still not been able to reproduce the issue).

**Comment by dmcpacks** [comment] 2024-05-22 17:25
Here are the results

PS C:\Users\USER> where.exe git
C:\Users\USER\git
c:\devkitPro\msys2\usr\bin\git.exe
C:\Program Files\Git\cmd\git.exe
PS C:\Users\USER> git version
git version 2.43.0

**Comment by dmcpacks** [comment] 2024-05-22 17:39
FIxed the issue, entered system variables and moved devkitpros git below the default windows git and now it works. Not closing with comment incase you'd like more data from my system.

**Comment by DanTup** [comment] 2024-05-22 18:55
Thanks for confirming. I guess devkitpro's version of Git has the same problem as the msys2 version.

I'll close this as a dupe of https://github.com/Dart-Code/Dart-Code/issues/4840 / https://github.com/flutter/flutter/issues/143625. Thanks!

**Closed by DanTup** 2024-05-22 18:55 UTC
Labels: is bug, awaiting info

**Comment by DanTup** [comment] 2024-05-22 18:58
>  I guess devkitpro's version of Git has the same problem as the msys2 version.

I just noticed that the devkitpro path includes "msys2", so it looks like devkitpro is just including the msys2 version, which explains why the behaviour is the same.

**Comment by andynvt** [comment] 2025-01-25 02:59
same issue here

![Image](https://github.com/user-attachments/assets/74c3b367-dccf-4569-8ddc-077509307abe)

```log
 ERR File is not being analyzed: Error: File is not being analyzed
    at handleResponse (/Users/andy/.vscode/extensions/dart-code.dart-code-3.102.0/out/dist/extension.js:34034:48)
    at handleMessage (/Users/andy/.vscode/extensions/dart-code.dart-code-3.102.0/out/dist/extension.js:33814:13)
    at processMessageQueue (/Users/andy/.vscode/extensions/dart-code.dart-code-3.102.0/out/dist/extension.js:33831:17)
    at Immediate.<anonymous> (/Users/andy/.vscode/extensions/dart-code.dart-code-3.102.0/out/dist/extension.js:33803:13)
    at processImmediate (node:internal/timers:483:21)
```
