### ISSUE TITLE
Dart: Run all tests interrupts after first test with Exited (sigint)

### ISSUE THREAD

**Issue by IgorKoshnarov** [Dart-Code/Dart-Code#2198] opened 2020-01-04 17:37 UTC
Hi, I try to run all my tests using Dart: Run all tests command but after running first test it interrupts and outputs into the Debug Console "**Exited (sigint)**".

When I run "flutter test" from console all tests are run.

OS: Windows 10,

VSCode Version: 1.41.1 (user setup)
Commit: 26076a4de974ead31f97692a0d32f90d735645c0
Date: 2019-12-18T14:58:56.166Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18362,

Dart code extension version: 3.7.1,

Flutter: is fully installed. (Channel stable, v1.12.13+hotfix.5, on Microsoft Windows [Version 10.0.18362.535], locale en-US)

My launch.json file looks like this:
```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Run all tests",
            "type": "dart",
            "request": "launch",
            "program": "./test/"
        },
        {
            "name": "Flutter",
            "request": "launch",
            "type": "dart"
        }
    ]
}
```

The only issue I've found is in the VSCode's Log (Window), it looks like this:
```
[2020-01-04 19:13:30.109] [renderer1] [error] Error: WebSocket is not open: readyState 0 (CONNECTING)
	at D.send (c:\Users\imdes\.vscode\extensions\dart-code.dart-code-3.7.1\out\dist\extension.js:1:186807)
	at t.ObservatoryConnection.callMethod (c:\Users\imdes\.vscode\extensions\dart-code.dart-code-3.7.1\out\dist\extension.js:1:317134)
	at t.ObservatoryConnection.setExceptionPauseMode (c:\Users\imdes\.vscode\extensions\dart-code.dart-code-3.7.1\out\dist\extension.js:1:315879)
	at t.ThreadManager.setExceptionPauseMode (c:\Users\imdes\.vscode\extensions\dart-code.dart-code-3.7.1\out\dist\extension.js:1:327056)
	at a.setExceptionBreakPointsRequest (c:\Users\imdes\.vscode\extensions\dart-code.dart-code-3.7.1\out\dist\extension.js:1:126371)
	at a.dispatchRequest (c:\Users\imdes\.vscode\extensions\dart-code.dart-code-3.7.1\out\dist\extension.js:1:152917)
	at a._handleData (c:\Users\imdes\.vscode\extensions\dart-code.dart-code-3.7.1\out\dist\extension.js:1:311447)
	at Socket.<anonymous> (c:\Users\imdes\.vscode\extensions\dart-code.dart-code-3.7.1\out\dist\extension.js:1:309957)
	at Socket.emit (events.js:200:13)
	at addChunk (_stream_readable.js:294:12)
	at readableAddChunk (_stream_readable.js:275:11)
	at Socket.Readable.push (_stream_readable.js:210:10)
	at TCP.onStreamRead (internal/stream_base_commons.js:166:17): Error: Error: WebSocket is not open: readyState 0 (CONNECTING)
	at D.send (c:\Users\imdes\.vscode\extensions\dart-code.dart-code-3.7.1\out\dist\extension.js:1:186807)
	at t.ObservatoryConnection.callMethod (c:\Users\imdes\.vscode\extensions\dart-code.dart-code-3.7.1\out\dist\extension.js:1:317134)
	at t.ObservatoryConnection.setExceptionPauseMode (c:\Users\imdes\.vscode\extensions\dart-code.dart-code-3.7.1\out\dist\extension.js:1:315879)
	at t.ThreadManager.setExceptionPauseMode (c:\Users\imdes\.vscode\extensions\dart-code.dart-code-3.7.1\out\dist\extension.js:1:327056)
	at a.setExceptionBreakPointsRequest (c:\Users\imdes\.vscode\extensions\dart-code.dart-code-3.7.1\out\dist\extension.js:1:126371)
	at a.dispatchRequest (c:\Users\imdes\.vscode\extensions\dart-code.dart-code-3.7.1\out\dist\extension.js:1:152917)
	at a._handleData (c:\Users\imdes\.vscode\extensions\dart-code.dart-code-3.7.1\out\dist\extension.js:1:311447)
	at Socket.<anonymous> (c:\Users\imdes\.vscode\extensions\dart-code.dart-code-3.7.1\out\dist\extension.js:1:309957)
	at Socket.emit (events.js:200:13)
	at addChunk (_stream_readable.js:294:12)
	at readableAddChunk (_stream_readable.js:275:11)
	at Socket.Readable.push (_stream_readable.js:210:10)
	at TCP.onStreamRead (internal/stream_base_commons.js:166:17)
    at t.RawDebugSession.handleErrorResponse (file:///C:/Users/imdes/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2821:819)
    at file:///C:/Users/imdes/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2821:250
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
    at async R.sendExceptionBreakpoints (file:///C:/Users/imdes/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5115:114)
    at async Y.sendToOneOrAllSessions (file:///C:/Users/imdes/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5146:591)
    at async Y.sendAllBreakpoints (file:///C:/Users/imdes/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5145:633)
    at async file:///C:/Users/imdes/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5120:850
```

**Comment by DanTup** [comment] 2020-01-16 15:51
@IgorKoshnarov are you running the tests using **Dart: Run All Tests** or using a `launch.json` config? I can reproduce an issue using `launch.json` (see https://github.com/Dart-Code/Dart-Code/issues/2082), but since **Run All Tests** runs without the debugger, it seems to work ok for me.

If you can repro with the command, could you capture a log (using `**Dart: Capture Logs** and keping everything ticked *except for* Analyzer)? Thanks!

**Comment by IgorKoshnarov** [comment] 2020-01-16 17:34
What I did was clicking on the debug icon in the left panel of vscode and then choosing the "Run all tests" option for "DEBUG AND RUN". It uses my launch.json file I believe. I thought it's the same as running "Dart: Run all tests" command but now I see it's not the case.

I've just run the "Dart: Run all tests" command and all tests had been completed.

Thanks for the response!

**Comment by DanTup** [comment] 2020-01-16 17:40
Ah, great - in that case it's just a dupe of https://github.com/Dart-Code/Dart-Code/issues/2082. A workaround (if you want to be able to use the launch.json config) is to add `"noDebug": true` to the launch config, which will disable the debugger (it's only in debug mode this happens). Of course, this means you won't have a debugger (but that's the case for **Dart: Run All Tests** too).

I'll close this as a dupe, but https://github.com/Dart-Code/Dart-Code/issues/2082 will stay open in the hope we can find a way to make that work.

**Closed by DanTup** 2020-01-16 17:40 UTC
Labels: awaiting info, in debugger, in testing, is bug
