### ISSUE TITLE
Hot reloading is not indicated in vscode

### ISSUE THREAD

**Issue by edgarfroes** [Dart-Code/Dart-Code#2628] opened 2020-07-10 02:47 UTC
_Copied from https://github.com/flutter/flutter/issues/60439, as I'm having the same problem:_

From today 6/8/2020 the hotreloading process is not showing in the notification bar,I did not updated the flutter sdk,but a few hours before the issue ive seen a notification about "Dart sdk has been updated".
completely uninstalled and recreated a new project but the issue remains same,Only when the hotlreload is finished its logged in console "Reloaded 0 of 495 libraries in 167ms."

**Flutter Doctor Output**

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.17.3, on Microsoft Windows [Version 6.1.7601], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[√] Android Studio (version 3.6)
[√] VS Code (version 1.46.1)
```

Expected Progress indication for hotreload is..
![image](https://user-images.githubusercontent.com/4291391/87110886-75e62780-c23e-11ea-8271-b2d916407b95.png)

**Comment by DanTup** [comment] 2020-07-13 09:45
Thanks for the report! This is a dupe of #2597. 

We switched to using the debug-adapter-protocol messages in a recent version, however VS Code does not support showing them as large notifications (instead, they appear on the left only in the status bar). Please add a 👍  to https://github.com/microsoft/vscode/issues/101791 which is a request for VS Code to handle this better. Thanks!

**Closed** 2020-07-13 09:45 UTC
Labels: duplicate
