### ISSUE TITLE
Allow overriding the number of cores "flutter test" runs with

### ISSUE THREAD

**Issue by HerrNiklasRaab** [Dart-Code/Dart-Code#2957] opened 2020-11-13 12:22 UTC
The flutter test command has the option "-j" which specifies how many concurrent test process can run. This option defaults to "6".

When I run the tests without "-j" 359 tests take 1:06, when I run the tests with "-j 8" the tests complete in 1:00. So my question is, when I run the test via the command "Dart: Run all tests", how many concurrencies are used? And if the default value is used, is there a way to change it?

**Comment by DanTup** [comment] 2020-11-13 15:28
As far as I can see, we're not passing the `-j` arg at all to `flutter test` (see https://github.com/Dart-Code/Dart-Code/blob/master/src/debug/flutter_test_debug_impl.ts - though if you run **Dart: Capture Debugging Logs** you'll be able to see the exact command that's being run).

We do pass [`-j 1` when running *Dart* tests though](https://github.com/Dart-Code/Dart-Code/blob/33fbe6f3078a44181c10aa541e1980ee76f3b985/src/debug/dart_test_debug_impl.ts#L57), however apparently I didn't document the reasons for this properly. It might've just been because the experience was weird hitting breakpoints in multiple tests together, or there might've been something that didn't work correctly.

In any case - if something doesn't seem to be working as well as it could, capture a log/give repro instructions and we can see if we can improve it. Thanks!

**Comment by HerrNiklasRaab** [comment] 2020-11-13 15:40
Hey @DanTup,

Thanks for responding. When I run the tests from the console with the -j 16 argument, they are about 10% faster on my machine, due to leveraging all the kernels (for example 20 core machine).

I thought it might be possible to enable this performance improvement also, when running the tests from VSCode.

Might be worth to introduce a setting where you can specify how many concurrencies are used when running the tests.

So this issue is less about reporting a bug. More a feature request. Do you need logs of something specific?

What do you think about that?

Best,

Niklas

**Comment by DanTup** [comment] 2020-11-13 16:16
Oh sorry, I think I misunderstood. You want to override the Flutter default because it's not optimal? I think it deliberately doesn't use all the cores, to allow or other processes to run.

I think the recently-added (but not yet shipped) `dart.flutterTestAdditionalArgs` setting might be what you want - you could add `["-j", "8"]` to it?

https://github.com/Dart-Code/Dart-Code/pull/2916

I plan to make a preview build early next week, so you could try it out?

**Comment by HerrNiklasRaab** [comment] 2020-11-13 18:41
That's what I was searching for yes :). 

Once you have a preview version ready, let me know. I will test it.

**Comment by DanTup** [comment] 2020-11-16 16:55
There's a build to try at https://github.com/Dart-Code/Dart-Code/releases/tag/v3.17.0-alpha.2.

If you have any issues with it, please let me know!

**Comment by DanTup** [comment] 2020-11-16 16:57
Closing as a dupe of #2915 (on the assumption it works - we can revisit if not).

**Closed by DanTup** 2020-11-16 16:57 UTC
Labels: duplicate
