### ISSUE TITLE
Missing suggestions for files prefixed with `_` and a `part` directive

### ISSUE THREAD

**Issue by jellynoone** [Dart-Code/Dart-Code#3902] opened 2022-04-03 12:19 UTC
**Describe the bug**
If a file is created and its name starts with `_` and there is a `part` directive in the file. Any symbols defined in it are not available as suggestions in other parts of the program.

What makes this even more confusing is that if the file is renamed to something else the symbols become available and when renamed back they sometimes remain other times not. And if the file name is prefixed with `__` then the symbols are available as well.

**To Reproduce**
1. Download the zip with the source.
2. Go to `consumer.dart`
3. Start changing `void` return type to `CompiledEntry`
4. Observe only 3 suggestions when there should be 4

*Note:* The reason I included the different declarations of `CompiledEntry` is, so that it is observable when symbols become available and when not.

**Expected behavior**
I expect there to be 4 suggestions instead of 3. Or specifically I expect symbols in a file with a `part` directive and a prefix `_` to be suggested in other files.

**Versions (please complete the following information):**
 - VS Code version: `1.67.0-insider`
 - Dart extension version: `v3.36.0`
 - Dart/Flutter SDK version: `Dart SDK version: 2.16.2 (stable) (Tue Mar 22 13:15:13 2022 +0100) on "macos_x64"`

**Additional:**
It might be that there is a Dart convention here at play because of the `_` but since a file without a `part` directive and the same prefix works just fine, I don't think that's the case.

I think symbols are actually available because analysis recognizes them after adding the proper `import` and because if you typed out the type manually, quick fix `import` suggestion is correctly recommended.

[bug.zip](https://github.com/Dart-Code/Dart-Code/files/8404487/bug.zip)

**Comment by jellynoone** [comment] 2022-04-03 12:22
I also think this issue exists for quite some time, but I always thought it was already noticed and didn't bother to check, until it bothered me too much.

**Comment by DanTup** [comment] 2022-04-04 10:23
I don't seem to be able to repro this. I'm on macOS and tried with both SDK 2.16.1 and the latest nightly (2.17.0-edge...).

<img width="620" alt="Screenshot 2022-04-04 at 11 20 27" src="https://user-images.githubusercontent.com/1078012/161524619-b7250a1a-9260-4ebd-be4a-a24cda04da23.png">

I wonder whether there might be some invalid summary files - if you close VS Code and move/rename/delete the `~/.dartServer` folder, does the issue go away? (note: your initial analysises may be slower after you clear this folder while the summaries are rebuilt).

**Comment by jellynoone** [comment] 2022-04-04 12:41
Your right this fixed the issue!

I thought simply initializing a clean project would work the same way.


After some additional testing, however, I was able to reproduce the issue again and it was triggered by renaming. 

*Steps:*
1. Create files named `a.dart` and `consumer.dart`
2. In `a.dart` write `class A {}`
3. In `consumer.dart` write `void name() {}`
4. Begin changing `void` to `A`. Notice there is a suggestion. ***Important:** don't import class `A`*
5. In`a.dart` add `part '_a.impl.dart';`
6. Create '_a.impl.dart' file through code action
7. Rename `a.dart` to `_a.dart` (sometimes this step is required other times the bug corrects itself this step is performed)
8. In `consumer.dart` start typing `A` notice no suggestion

However, after even more additional testing with clearing the .dartServer file again. I somehow failed to reproduce it. I will keep an eye out in the upcoming days to see if I can find the exact sequence of steps which I guess corrupted the cache, which I assume is the problem here.

Just as a side note do you recommend clearing the .dartServer every once and in while?

**Comment by DanTup** [comment] 2022-04-04 13:36
> I thought simply initializing a clean project would work the same way.

I would've expected so too, as I would expect the project paths would form part of the cache keys. I'm not too familiar with that though, @scheglov may know for sure.

> Just as a side note do you recommend clearing the `.dartServer` every once and in while?

You shouldn't need to, it should be managed automatically. However it's always possible something goes wrong that results in bad results (there's a similar report at https://github.com/Dart-Code/Dart-Code/issues/3890 where it seems like something in that folder may have become out of sync with the actual file contents).

Generally if clearing that folder ever fixes anything, there may be a bug that needs fixing, so it's worth filing issues (https://github.com/dart-lang/sdk is the best place) if you keep seeing this.

If you're able to get steps that can reproduce this reliably, please do let me know.

**Comment by scheglov** [comment] 2022-04-04 20:54
We don't use file paths in cache keys, but we use URIs and API signatures (based on the parts of the file content that are visible from outside of the file, for example excluding method bodies).

**Comment by DanTup** [comment] 2022-04-05 11:06
Ah got it. So it is possible that if a summary file had gotten out of sync, it could occur in a new project if it had the same package name + surface area (for example if the project was copy/pasted)?

Given clearing `.dartServer` fixed the issue, I think this is likely a similar issue to #3890 (that is, something in that folder seems to be out of sync) so I'll close it as a dupe of that. I have a question but I'll post it on that one.

**Closed** 2022-04-05 11:07 UTC
Labels: is bug, awaiting info
