### ISSUE TITLE
VSCode often freezes when "Analyzing"

### ISSUE THREAD

**Issue by Ovyerus** [Dart-Code/Dart-Code#1433] opened 2019-01-29 06:34 UTC
Not sure why this happens, but for some reason every time the plugin analyzes the code (whenever the "Analyzing" section appears on the bottom status bar), my entire VSCode freezes up for several seconds, while the rest of my system seems to be working just fine. This issue appears to get amplified when debugging a Flutter app using vsc's debug feature, with freezes occurring much more frequently.

**Comment by Ovyerus** [comment] 2019-01-29 07:55
Windows 7 (Q6600 @ 2.4GHz, 8GB RAM)
VSCode 1.31.0-insider (`acc7365` at time of writing)
Dart Code 2.22
Dart 2.1.0
Flutter 1.0.0

**Comment by Ovyerus** [comment] 2019-01-29 08:17
![vscode process explorer during freeze](https://erisaaa.is-a-good-waifu.com/c7ab1f.png)
Analyzer log: [url snipped; very long](https://gist.githubusercontent.com/Ovyerus/b75931774787193d286bfd3481eb7095/raw/c03dc9709c336586f49870cfcd8306d158d20a72/dart-code-analyzer.log)
Started debugging and froze once near the end (around line 1500, 2000 I think (`Navigator.pushNamed` or `MaterialPageRoute`)

**Comment by Ovyerus** [comment] 2019-01-29 08:33
The screenshot is just cropped vertically due to blank space (and I forgot I was doing something silly with my screenshotter so there was also something else obstructing a bit of the image, but it was just Git + the watcher and search services, all of which were using practically nothing).

I'll take a look with reproing and all that, it's a bit weird that the window is taking the CPU as this seems to only be happening when I'm doing stuff with Dart..

**Comment by DanTup** [comment] 2019-01-29 08:55
>  it's a bit weird that the window is taking the CPU as this seems to only be happening when I'm doing stuff with Dart

It's possible the issue is triggered by Dart, even if the issue is in Code. It's hard for me to debug what's going on in VS Code though (and arguable even a badly-behaved extension shouldn't be able to kill Code like this - it's in another process for isolation) so it'll need some investigation by the Code devs. That's why I asked to be CC'd, so if they find that it's caused by something bad here, I can change it.

It could also just be that there's something else unique about your Dart project(s) compared to others that trigger it. You could try disabling the Dart extension and then navigating the same files to see if it makes a difference, but it's definitely still work testing in VS Code Stable and opening an issue with them.

**Comment by DanTup** [comment] 2019-02-28 12:12
@athomas this sounds a little like what you reported to me yesterday. If you still see it and have some time, I would love to try and get to the bottom of it. I'd also be interested to know if there's anything in the developer console when it happens - VS Code has added some warnings recently when there are detected perf issues.

**Comment by DanTup** [comment] 2019-03-25 17:51
@Ovyerus @dcov @athomas Is anyone still seeing this and able to help do some digging? It'd be really useful to get a CPU profile or something while it's happening.

**Comment by athomas** [comment] 2019-03-25 19:45
I've upgraded to a newer version of Dart (2.2ish), that did improve things quite a bit.

I've now tried to remove the ~/.dartServer folder:
Analyzing started 20:18. At 20:23 vscode was "hanging" (the spinning icon next to "Analyzing..." was still moving, clicks taking ~20s to take effect, OSX popping up "The window is no longer responding" dialog, a single dart process fighting with a "Code Helper" for most of the CPU, the dart is using ~4GB of memory). At 20:33 it finished analyzing, Code Helper still pinning a CPU core, but fans stopped but dart is still using 4GB of memory and UI is till sluggish. At 20:44 it became fully responsive again.

I will try to get CPU profile next.

**Comment by DanTup** [comment] 2019-03-26 12:00
I believe @athomas's hang is a result of a huge number of errors. I've opened https://github.com/Microsoft/vscode/issues/71165 with VS Code about this.

I don't know if this covers the issues reported by @Ovyerus and @dcov though. If either of you can still reproduce issues and they're not when you have thousands of errors in the Problems view, please do let me know - it'd be good to get some CPU profiling traces.

**Comment by DanTup** [comment] 2019-03-27 11:03
Since @athomas's issue is now fixed (with https://github.com/Microsoft/vscode/issues/71165) that there haven't been any other responses with information, I'm going to consider this fixed by https://github.com/Microsoft/vscode/issues/71165. If anyone is still seeing issues and can reproduce them in VS Code Insiders (updated to todays or later) or Stable once the next version of VS Code goes out (probably in 1-2 weeks), please to post back or open a new issue. Thanks!

**Closed by DanTup** 2019-03-27 11:03 UTC
Labels: awaiting info

**Comment by Ovyerus** [comment] 2019-03-29 12:45
Wasn't able to test this out for a while, but it seems to be fixed now. 👍

**Comment by vandong9** [comment] 2020-09-21 03:47
I still get this error on Version: 1.48.2, Commit: a0479759d6e9ea56afa657e454193f72aef85bd0
I code flutter with dart, when using Either of Dartz

**Comment by DanTup** [comment] 2020-09-21 08:40
@vandong9 could you open a new issue with exact details of what you're seeing? If possible also include a screenshot of VS Code's "Process Explorer" (Help -> Open Process Explorer). Thanks!

**Comment by gloryluu** [comment] 2020-10-16 04:07
![Screen Shot 2020-10-16 at 11 04 52](https://user-images.githubusercontent.com/10140561/96211835-8e817e80-0f9f-11eb-8176-4062f0033ac9.png)

I have encountered with this issue since flutter 1.22. Analyzing process takes a long time with high amount cpu. :/

**Comment by DanTup** [comment] 2020-10-16 09:19
@gloryluu there's an open issue that might be the same thing at https://github.com/Dart-Code/Dart-Code/issues/2865.

Could you try the things at https://github.com/Dart-Code/Dart-Code/issues/2865#issuecomment-709371833 and follow up in that issue? Thanks!
