### ISSUE TITLE
Breakpoints don't work until after reload on macOS + iOS Simulator

### ISSUE THREAD

**Issue by mit-mit** [Dart-Code/Dart-Code#357] opened 2017-07-07 12:06 UTC
While testing [beta5](https://github.com/Dart-Code/Dart-Code/releases/tag/v1.5.0-beta.flutter5):

1. `flutter create testapp`
1. `cd testapp`
1. `code .`
1. add breakpoint in line 59 (`_counter++;`)
1. Hit `F5`
1. Press `+` button in app => nothing happened
1. Tried to add a few more breakpoints + hit Restart => nothing happened
1. Tried to add a few more breakpoints + change a widget + hit Restart => this error:

```
Lost connection to device.
Runner(23447,0x70000c83c000) malloc: *** error for object 0x600000059bc0: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
```

**Comment by mit-mit** [comment] 2017-07-07 12:09
And then after that, restarted the app, changed another string, hit restart, and now breakpoints are triggering! It seems something doesn't quite work on the first breakpoint sync?

**Comment by DanTup** [comment] 2017-07-07 12:16
@mit-mit Thanks for testing! Could you try a few things for me?

1. Set `dart.flutterRunLogFile` and `dart.observatoryLogFile` to paths for logging (currently, the folders must exist, the files do not) to enable blogging of comms with flutter and observatory
2. After launching the app when the breakpoints don't work (before reloading or trying to fix), open the `flutter run` log file and find the port number for Observatory and connect to it in your browser and find the path that the VM believe the files live in

My guess is that there's a mismatch in the paths that Dart Code got from your local machine and what the VM thinks (similar to #336, though that was post-reload that was wrong).

If you can provide me the path that Dart Code actually sent (this will be in the `addBreakpoint` calls in the Observatory log) and what the VM thinks (you can get this from Observatory in the browser) and it's different I can figure out how to change.

**Comment by DanTup** [comment] 2017-07-07 14:35
Also - I think the error you posted may be a bug in Flutter/Dart; I don't think Dart Code should be able to cause that even if it tried!

I'd still like to know if you can repro this though; it's possible the breakpoint misses are unrelated to the error posted and something I can fix.

**Comment by DanTup** [comment] 2017-07-14 14:01
@mit-mit I'm up and running on Mac OS now and I can't repro this. However, I do have some similar issues (intermittent crashes) which I think are unrelated to Dart Code, eg.:

<img width="1114" alt="screen shot 2017-07-14 at 15 00 28" src="https://user-images.githubusercontent.com/1078012/28215249-35e0323e-68a5-11e7-8eab-a838d5e5a37c.png">

I don't think this is a Dart Code issue so I'm going to raise at flutter.

Gonna close this since I can't repro and you haven't confirmed if you're still seeing it, but feel free to shout if you think there's still something wrong here.

**Comment by DanTup** [comment] 2017-07-17 11:29
@mit-mit Thanks for investigating! I've managed to get up and running on Mac OS now but so far only with Android; I'm hoping to get iOS emulator working this week so I'll investigate again.

There is an issue with Flutter on iOS (#358) which I presume you're not hitting; I don't think it's related since you'd see a frozen black screen.

If I'm unable to repro, I might ask if you could enable `dart.flutterRunLogFile` and `dart.observatoryLogFile` (see [CONTRIBUTING.md#enable-logging](https://github.com/Dart-Code/Dart-Code/blob/master/CONTRIBUTING.md#enable-logging)) and repro and attach the logs.

**Comment by mit-mit** [comment] 2017-07-17 11:42
Certainly, attached! The first two include the first six repro steps leading to the not working breakpoint. 
[flutterRunLogFile1.txt](https://github.com/Dart-Code/Dart-Code/files/1152414/flutterRunLogFile1.txt)
[observatoryLogFile1.txt](https://github.com/Dart-Code/Dart-Code/files/1152413/observatoryLogFile1.txt)

The second two files include the last three with the reload.
[observatoryLogFile2.txt](https://github.com/Dart-Code/Dart-Code/files/1152416/observatoryLogFile2.txt)
[flutterRunLogFile2.txt](https://github.com/Dart-Code/Dart-Code/files/1152415/flutterRunLogFile2.txt)

**Comment by DanTup** [comment] 2017-07-18 20:48
Ok; up and running with iOS Simulator now and I can reproduce!

```text
"baseUri":"file:///Users/danny/Library/Developer/CoreSimulator/Devices/C76BB178-2046-4302-B25B-0A747ECAA276/data/Containers/Data/Application/CCFE1472-7C21-4A5B-B733-022D49ADEEEB/tmp/test_breakpointskIQNRi/test_breakpoints/"
```

```text
"rootLib":{"type":"@Library","fixedId":true,"id":"libraries\/@16174969","name":"","uri":"\/Users\/danny\/Dev\/Testing\/test_breakpoints\/lib\/main.dart"}
```

```text
[9:37:50 PM]: ==> {"id":"443","method":"addBreakpointWithScriptUri","params":{"isolateId":"isolates/887577740","scriptUri":"file:///Users/danny/Dev/Testing/test_breakpoints/lib/main.dart","line":59}}
```

Looks like the problem is that I'm sending `file:///` for the script URI, but the VM doesn't have it. Similar to https://github.com/flutter/flutter/issues/11040 there seems to be some confusion about the format of URIs :(

The workaround for the above issue seems to not trigger here because of [this if statement](https://github.com/Dart-Code/Dart-Code/blob/2936aa9cea1c0b14ffddea4d259a5565cf3facbf/src/debug/flutter_debug_impl.ts#L80).. Probably the last two lines of that if condition need dropping outside the `if` so that they always apply, not just in the case of the remapped paths.

Out of time for tonight, but I'll see if I can get this fixed on Thursday. Thanks for the hep tracking it down and providing repro steps! :-)

**Closed** 2017-07-18 20:57 UTC
Labels: in debugger, in flutter, is bug

**Comment by DanTup** [comment] 2017-07-18 20:58
Couldn't go without at least testing it! Slight refactor and it's working fine for me. Hope to push a new release out on Thurs. In the meantime, a workaround is to just hit Hot Reload immediately after launching (sorry that doesn't help with breakpoints in startup code!).

**Comment by DanTup** [comment] 2017-07-19 18:03
@mit-mit I've pushed out v2.2.0 with this fix in; please update and let me know if it resolves your issues!

**Comment by mit-mit** [comment] 2017-07-20 12:38
Works great in v2.2.0; thanks much!

**Comment by DanTup** [comment] 2017-07-20 18:56
Great; thanks for confirming!
