### ISSUE TITLE
Import relative path autocompletion is not working

### ISSUE THREAD

**Issue by hythl0day** [Dart-Code/Dart-Code#3461] opened 2021-07-05 02:14 UTC
After recent updates of the dart-code extension, I found the Import path autocompletion is not working. It is working for packages and sub-folders though, however when I type relative paths like '../xxxx', nothing shows up. And it works just fine before the updates.

![image](https://user-images.githubusercontent.com/2274141/124408792-96758e80-dd79-11eb-88a5-932edbd85961.png)

![image](https://user-images.githubusercontent.com/2274141/124408850-b7d67a80-dd79-11eb-9d1c-2ca2353f6820.png)

**Versions (please complete the following information):**
 - VS Code version: 1.57.1
 - Dart extension version: 3.24.1
 - Dart/Flutter SDK version: 2.13.4

**Comment by DanTup** [comment] 2021-07-05 10:13
Can you give a specific example of exactly what you're typing when this doesn't work? I tried typing `./` into an import though that seemed to work correctly:

<img width="343" alt="Screenshot 2021-07-05 at 11 12 02" src="https://user-images.githubusercontent.com/1078012/124455797-e1939f80-dd81-11eb-889d-1a88c2de25cf.png">

Thanks!

**Comment by DanTup** [comment] 2021-07-05 10:14
Sorry, I mis-read. I can reproduce it not showing anything for `../`... I'll take a look.

**Comment by DanTup** [comment] 2021-07-05 10:22
Actually, my case of `../` not working was because I was directly inside the `lib` folder, and the completion does not suggest paths that would go outside of the lib folder. If I try in a nested folder, the paths show up fine:

<img width="395" alt="Screenshot 2021-07-05 at 11 21 05" src="https://user-images.githubusercontent.com/1078012/124456974-37b51280-dd83-11eb-854b-78721c8567a2.png">

So can you provide a small example project where the imports are not showing up as you'd expect? Thanks!

**Comment by hythl0day** [comment] 2021-07-05 10:52
> So can you provide a small example project where the imports are not showing up as you'd expect? Thanks!

I am having this issue in all of my projects. However I'm not sure if it's related to my VSCode setting or some other extension...

**Comment by hythl0day** [comment] 2021-07-05 13:41
I found out that the keyboard shortcut "ctrl + space" is working just fine, it's just that it won't popup automatically now....

**Comment by DanTup** [comment] 2021-07-05 16:53
@hythl0day thanks for confirming. There are two related issues, both recently fixed:

- Completion doesn't automatically trigger when selecting the "import '';" snippet or a folder from the completion. This was fixed in the last Dart extension update as part of #3385.
- Completion doesn't automatically trigger when typing `/` and some other characters in certain contexts. This was fixed as part of #3211, however the fix is in the SDK so it won't show up until a future SDK release

I believe the second one is the issue you're seeing now. I didn't see it because I was using a pre-release SDK which includes the fix.

The reason the behaviour seemed to change recently is that the second issue was in the LSP server and in the last Dart update, more people were moved over to the LSP implementation (this is a new protocol for the language server that will soon be the default for everyone).

So in the short-term, I would use Ctrl+Space when you need it - but after the next (non-hotfix) stable SDK releases it'll start triggering automatically again. Sorry for the inconvenience!

**Closed** 2021-07-05 16:53 UTC
Labels: duplicate
