### ISSUE TITLE
VsCode quick action "Wrap with Widget" not  working as expected for Flutter 3.0.

### ISSUE THREAD

**Issue by JasperEssien2** [Dart-Code/Dart-Code#3956] opened 2022-05-12 19:37 UTC
**Describe the bug**
After updating my flutter version, The quick action "Wrap with widget" does not work as intended on VsCode. 

**To Reproduce**
1. Update Flutter to 3.0
2. Try wrapping a widget using "Wrap with Widget" quick action.

**Expected behavior**
It wraps the widget with the code below
It wraps a widget with the code below.

```dart
 ${1:widget}(
        ${2:child}: SomeWidget(),
      )
```

**Please complete the following information:**
 - Operating System and version: macOS Monterey v12.2.1 m1
 - VS Code version: Version: 1.58.2
 - Dart extension version: v3.25.1
 - Dart/Flutter SDK version: *Flutter*:  Channel stable, 3.0.0. **Dart:** 2.17.0

**Comment by DanTup** [comment] 2022-05-12 20:08
> Dart extension version: v3.25.1

v3.25.1 is quite an old version of the extension. If you upgrade to the latest version (v3.40.0) the issue should be resolved (it was fixed in #3877, included in v3.38.0).

Please let me know if you're still seeing the issue on the latest version. Thanks!

**Closed** 2022-05-12 20:09 UTC
Labels: duplicate

**Comment by Pablo-hub44** [comment] 2022-06-22 22:15
not works for me 
sdk 3.0.2
dart v3.4320
flutter v3.42
SO Windows 11

**Comment by DanTup** [comment] 2022-06-23 09:11
@Pablo-hub44 please file a new issue with clear screenshots and sample code that illustrates the issue. I have tested with Flutter v3.0.3 and the latest Dart/Flutter extensions and am unable to reproduce the original issue reported here:

![Jun-23-2022 10-09-32](https://user-images.githubusercontent.com/1078012/175262762-48c7122b-a3fc-4924-9b5a-ec488175722b.gif)

**Comment by mhmetglrq** [comment] 2022-06-26 15:15
> not works for me sdk 3.0.2 dart v3.4320 flutter v3.42 SO Windows 11

I switch  Dart version  pre-release to release version and its working now

**Comment by DanTup** [comment] 2022-06-28 11:18
@RobertsFerreira I'm unable to reproduce this using v3.43.20220621 of the extension. Could you file a new issue and include a log file:

- Set up the project with your sample code. Ensure your cursor is _not_ at the location where you will apply the refactor.
- Run the **Dart: Capture Analysis Logs** command from the command palette (`F1`)
- Move your cursor back to `AppWidget` and then invoke the lightbulb menu, and select Wrap with Widget
- After the invalid code is created, click **Cancel** on the logging notification to stop logging and open the log file

Please file a new issue and include the log. Thanks!

**Comment by DanTup** [comment] 2022-06-28 11:19
@mhmetglrq if you're seeing this on the pre-release version of the extension, could you also perform the steps above to get a log? Thanks!
