### ISSUE TITLE
Create Android emulator makes incorrect assumptions for Apple m1 macs

### ISSUE THREAD

**Issue by guidezpl** [Dart-Code/Dart-Code#4492] opened 2023-04-13 13:16 UTC
**Describe the bug**
On m1 macs, the emulator created uses an x86_64 image, which at least for me, crashes on launch. 

**To Reproduce**
2. Click on 'Create Android emulator'
3. Try to open emulator
4. Nothing happens, Android Studio logs show
```
2023-04-13 12:41:00,223 [51285920]   INFO - Emulator: flutter emulator - PANIC: Avd's CPU Architecture 'x86_64' is not supported by the QEMU2 emulator on aarch64 host.
```

**Expected behavior**
Android emulators can launch on m1 macs

**Screenshots**
<img width="372" alt="image" src="https://user-images.githubusercontent.com/6655696/231769515-1b98a8ef-efaa-4e46-b149-53fdae90895d.png">

The emulator above crashes, the one below (created manually) doesn't. 
<img width="795" alt="image" src="https://user-images.githubusercontent.com/6655696/231769612-e4b7ffd0-582b-4d66-80ec-17a64db395e1.png">

**Please complete the following information:**
 - Operating System and version: macOS 13.3 22E5219e darwin-arm64
 - VS Code version: 1.77.3
 - Dart extension version: v3.62.0
 - Dart/Flutter SDK version: 3.10.0-3.0.pre.44
 - Target device (if the issue relates to Flutter debugging):

**Comment by DanTup** [comment] 2023-04-17 18:03
Can you post the output of running:

```
avdmanager create avd -n temp 
```

If avdmanager isn't available on PATH, you can run `flutter config --machine` to find your Android SDK root, then append `cmdline-tools/latest/bin/avdmanager`, for example:

```
/Users/danny/Library/Android/sdk/cmdline-tools/latest/bin/avdmanager create avd -n temp
```

And if you don't have JAVA_HOME configured, you can run `flutter doctor -v` to find where your Java is, drop `bin/java` off the end and set it for the command, for example:

```
JAVA_HOME=/Applications/Android\ Studio.app/Contents/jre/Contents/Home/ /Users/danny/Library/Android/sdk/cmdline-tools/latest/bin/avdmanager create avd -n temp
```

Thanks!

**Comment by guidezpl** [comment] 2023-04-18 07:07
```
avdmanager create avd -n temp
Error: Package path (-k) not specified. Valid system image paths are:
system-images;android-33;google_apis;arm64-v8a
system-images;android-UpsideDownCake;google_apis;arm64-v8a
system-images;android-33;google_apis_playstore;x86_64
null
```

**Comment by DanTup** [comment] 2023-04-18 08:53
So I guess the issue is here in Flutter:

https://github.com/flutter/flutter/blob/3ba249a6b37cf9f81ed4ac4ec320ef981ab9c3e1/packages/flutter_tools/lib/src/emulator.dart#L210

It runs that command and then looks for the highest android version that contains `"system-images"` and `"google_apis_playstore"`. In your case, this is picking the x86 image.

One simple fix for your machine is to uninstall that image and install an arm playstore version. It might be worth a change in Flutter to better understand the architectures in these names though, so it can prefer (or only pick) those that match?

**Comment by guidezpl** [comment] 2023-04-18 10:15
So this seems to be a tools issue, since Android seems to have switched back to named versions and the highest numbered version won't be the latest one.

**Comment by DanTup** [comment] 2023-04-18 10:22
Oh yeah, I didn't even notice that. Yeah, it seems like that sorting in Flutter will need changing to take that into account too (conveniently I think the names are alphabetical... although I don't know what happens after Android Zucchini Cake! 😄

Do you want a file an issue in flutter/flutter and post the link back here?

**Comment by guidezpl** [comment] 2023-04-20 10:52
Filed https://github.com/flutter/flutter/issues/125198

**Comment by DanTup** [comment] 2023-04-20 11:04
Thanks! Isn't there also a separate issue that it's picking up images from the wrong architecture? (although I wonder whether it's common to have a different architecture installed - do you know how you got yours?).

(closing this since I think all the work is in Flutter).

**Closed by DanTup** 2023-04-20 11:04 UTC
Labels: is bug, awaiting info
