### ISSUE TITLE
Autocomplete behaves weirdly when no match is found

### ISSUE THREAD

**Issue by FMorschel** [Dart-Code/Dart-Code#5293] opened 2024-09-30 15:41 UTC
See the following code

```dart
import 'dart:math' as math;

class C {
  void foo(int value) {
    value.test
  }

  void bar() {
    math.testa
  }
}
```

There is a difference when you start from the beginning or when you start at the end of the word:

https://github.com/user-attachments/assets/efe145b2-0622-445b-a952-80b9cd41fc5e

**Comment by DanTup** [comment] 2024-09-30 16:04
Thanks - I had a look at this, and it seems like there are two different things happening here in the top/bottom examples. The first example comes from VS Code trying to handle typos. When you invoke completion at the end of `test`, the server does _not_ return `toStringAsExponential` because it does not contain the letters `t`, `e`, `s`, `t` in that order.

However, when you invoke at the start, the server _does_ include it (because there's no prefix, or just a `t`). In that case, when you press `right`, the filtering is done entirely by VS Code on the client side. It's "clever" and does some handling of typos, so it _does_ allow `toStringAsExponential` because two letters are transposed and it considers that a possibly typo:

![Screenshot 2024-09-30 164941](https://github.com/user-attachments/assets/a49e2c38-6dc1-48c3-978a-510b6b6b4db8)

The second example is similar.. If you invoke completion at the end, the server (correctly IMO) filters the items out, but for some reason VS Code when filtering itself does not - even though there are _several_ characters not in `testa` that are not in `tan()`. I checked the server response to ensure we didn't have a bogus `filterText` that included these characters, but we do not (we do not have any `filterText` for this item):

```ts
{
	"detail": "(num radians) → double",
	"documentation": {
		"kind": "markdown",
		"value": "Converts [radians] to a [double] and returns the tangent of the value.\n\nThe tangent function is equivalent to `sin(radians)/cos(radians)` and may be\ninfinite (positive or negative) when `cos(radians)` is equal to zero.\nIf [radians] is not a finite number, the result is NaN."
	},
	"insertTextFormat": 2,
	"kind": 3,
	"label": "tan",
	"labelDetails": {
		"detail": "(…) → double"
	},
	"sortText": "9499",
	"textEditText": "tan(${0:radians})"
}
```

So, I think the first one is probably working as intended (and is a consequence of differences in fuzzy filtering between VS Code / Dart), and the second one I'm not sure about - it may be worth filing with VS Code to see if they can provide an explanation (or confirm it's a bug). Feel free to CC me if you do file this so I can help explain if useful.

**Comment by DanTup** [comment] 2024-10-03 09:39
Closing this as I believe it's working as expected, or if there's an issue with the second example it's a VS Code issue.

While these issues might not occur if the filtering in VS Code and the Dart server matched perfectly, that's not currently a goal - each client might have slightly different rules for filtering, so in cases where you can trigger the filtering to occur on either side, there will always be a chance of some slight differences in what you see.

**Closed by DanTup** 2024-10-03 09:39 UTC
Labels: is bug
