### ISSUE TITLE
Request textDocument/codeAction failed.   Message: Invalid file path

### ISSUE THREAD

**Issue by aminsamad** [Dart-Code/Dart-Code#3530] opened 2021-08-13 13:51 UTC
Hello, when I open dart file show this error how can I resolve this problem ? 

[Error - 4:44:58 PM] Request textDocument/documentSymbol failed.
  Message: Invalid file path
  Code: -32003 
c:\Users\Sherdll Store\youtube_apii\lib\main.dart
[Error - 4:44:58 PM] Request textDocument/codeAction failed.
  Message: Invalid file path
  Code: -32003

**Comment by joshprzybyszewski-wf** [comment] 2021-08-18 15:53
I am also seeing this, and I think it's related to conversation [here](https://github.com/dart-lang/language/issues/1470)

**Comment by DanTup** [comment] 2021-08-24 13:39
Can you confirm if you're opening your project folder in VS Code, or just loose files?

An [analysis server log](https://dartcode.org/docs/logging/#analyzer) (with anything sensitive removed) may be helpful too. Thanks!

**Comment by DanTup** [comment] 2021-08-30 15:41
Is anyone able to provide the log file described above, or a repro projects/steps (and SDK versions being used) for me to try? Thanks!

**Comment by sandbox-apps** [comment] 2021-09-09 04:28
Im experiencing this after updating to flutter 2.5 and dart 2.14

**Comment by arnoutvandervorst** [comment] 2021-09-09 06:49
Same, upgraded to Flutter 2.5 and Dart 2.14, did a flutter clean.

[Error - 8:45:12 AM] Request textDocument/documentSymbol failed.
  Message: Invalid file path
  Code: -32003 
/Users/arnoutvandervorst/Projects/newme_app/lib/main.dart
[Error - 8:49:06 AM] Request textDocument/codeAction failed.
  Message: Invalid file path
  Code: -32003 
/Users/arnoutvandervorst/Projects/newme_app/lib/main.dart

**Comment by arnoutvandervorst** [comment] 2021-09-09 06:57
Server analysis log file:
https://www.dropbox.com/s/c815h4kxonorsf9/analyzer.txt?dl=0

**Comment by DanTup** [comment] 2021-09-09 08:53
Thanks for the log! Unfortunately it doesn't reveal much. Can anyone reproduce this on a project they can share? I've seen errors like this when there have been errors in the parsing of files (for example a previous one was if a file contained the work `or` instead of `||` the parsing would fail and lead to this error) but I'm not sure if something like that is occurring here.

If it only occurs in one project, could you try taking a copy of it and trimming it down to the minimum that still triggers it that you may be able to share? Thanks!

**Comment by arnoutvandervorst** [comment] 2021-09-09 09:40
Weird thing is: when I switch to Android Studio (urgh!), exactly the same happens, but that one uses a different plugin right? Can't run my build_runner, cannot build, cannot analyze 1 single file....pretty much stuck and not sure where to look. Just upgraded to Flutter 2.5 and Dart 2.14 as my app is not in production yet, straight afterward nothing works...

**Comment by DanTup** [comment] 2021-09-09 09:46
> Weird thing is: when I switch to Android Studio (urgh!), exactly the same happens, 

I presume you mean the same behaviour, rather than the same error message? The error message above is LSP-specific which Android Studio does not use. However, both editors use the same _language server_ so if you're hitting a parser failure or similar, then I would expect it to fail in both editors (as the fix would be in the parser in the SDK).

If it's invalid code triggering this (like the previous example I noted, where the word "or" in place of "||" would trigger it) then fixing that invalid code should get you back up and running (although the issue still needs fixing in the parser). In that case, the best thing to do may be to take a copy of the file in the error message and put it in a new project, then try to remove code until you track down exactly which code is triggering the issue (you may need to reload as you make changes). It's possible you'll have an error listed in approximately the area of the invalid code that might help pinpoint where it is.

Otherwise, if you can reduce the project to something you can share (that still triggers the issue), I'm happy to try to pinpoint the issue. Thanks!

**Comment by arnoutvandervorst** [comment] 2021-09-09 09:50
Hmmm yes but literally every file I open generates the error message, not just 1 file where I might have syntax issues. Every file generates: 

/Users/arnoutvandervorst/Projects/newme_app/lib/providers/common.dart
[Error - 11:46:08 AM] Request textDocument/documentSymbol failed.
  Message: Invalid file path
  Code: -32003 
/Users/arnoutvandervorst/Projects/newme_app/lib/model/reward.dart
[Error - 11:49:07 AM] Request textDocument/codeAction failed.
  Message: Invalid file path
  Code: -32003 
/Users/arnoutvandervorst/Projects/newme_app/lib/model/reward.dart

And so on...always the codeAction + documentSymbol failure.

**Comment by DanTup** [comment] 2021-09-09 09:53
Do you see any errors listed in the Problems window at all? If so, I would try with that file first - copy it to a new project and see if it triggers the issue.

Also - it occurs to me that the analysis instrumentation log (this is slightly different to the one noted above) might capture more info:

https://dartcode.org/docs/logging/#analyzer-instrumentation

Again, this may includes parts of your source code so you might want to just extract the error message from the log (if it's there). You can email logs to me at logs@dartcode.org but do not send anything sensitive.

Otherwise, if you can trim your project down to something you can share, I'm happy to take a look.

**Comment by arnoutvandervorst** [comment] 2021-09-09 10:27
The instrumentation logging contains the same message I get when running the build_runner to generate code:

1631182843704:Ex:Analysis failed:: /Users/arnoutvandervorst/Projects/newme_app/test/widget_test.dart context:: exception_20210909_122043_559
Invalid argument(s):: Unexpectedly not indexed:: Notifier extends StateNotifier<State>
#0      _LocalElementIndexer.[] (package::analyzer/src/summary2/bundle_writer.dart::944::10)

Same message for every file I open, logging goes mental on this issue. Must be something introduced in Dart 2.14 in combination with the StateNotifier package that causes this...

**Comment by DanTup** [comment] 2021-09-09 10:50
@arnoutvandervorst thanks - that's exactly the sort of error I was hoping for. Could you file an issue at https://github.com/dart-lang/sdk/issues with a description of this issue and include both errors (the "Invalid file path" and the "Analysis failed" one from your last comment above). This seems like an analysis server bug but this code isn't something I'm familiar with. Please post the URL back here. Thanks!

**Comment by arnoutvandervorst** [comment] 2021-09-09 14:05
https://github.com/dart-lang/sdk/issues/47171

**Comment by arnoutvandervorst** [comment] 2021-09-09 14:07
I have another project which works fine, no issues at all, and I use the StateNotifier there as well...really curious what this issue is.

**Comment by sandbox-apps** [comment] 2021-09-09 14:13
Yes right all my files has popping this error messages everywhere. Be it in widget view or widget view model. So I cant really trace where. It has also stops me from coding. I cant even use autocomplete and formatting. It feels like a notepad with just literally almost every on focus on editor pops it up

**Comment by DanTup** [comment] 2021-09-09 15:58
For anyone seeing this, please follows the comments at https://github.com/dart-lang/sdk/issues/47171#issuecomment-916202395 asking some questions about the code (and also for a repro).

**Comment by DanTup** [comment] 2021-09-09 22:22
Looks like the issue is understood and being fixed in the SDK, so closing this in favour of https://github.com/dart-lang/sdk/issues/47171. Thanks!

**Closed by DanTup** 2021-09-09 22:22 UTC
Labels: is bug, awaiting info
