### ISSUE TITLE
hello guys.  Am having a problem with my flutter app, when ever i write or open my project and run the app, in the emulator it keeps showing the old code...not the new code....

### ISSUE THREAD

**Issue by victoredede21** [Dart-Code/Dart-Code#1220] opened 2018-09-22 10:16 UTC

**Comment by DanTup** [comment] 2018-09-22 16:10
What version of Flutter are you using? Could you try capturing a `Flutter Run` log (see https://dartcode.org/docs/logging/#capture-logs-command). Also, can you reproduce by running `flutter run` from the terminal in your projects folder? If so, please try `flutter run -v` and capture the output.

Based on the description, I think maybe it's the same as https://github.com/flutter/flutter/issues/16604 though.

**Comment by DanTup** [comment] 2018-09-24 07:27
I don't *think* it's Dard-Code related; we don't really deal with any of the building/cleaning, we just call the commands in flutter. I've never been able to reproduce to try and troubleshoot here though.

I don't know whether the bug is in the engine or not, but the flutter/flutter issue tracker is used for all flutter issues, including the engine.

**Comment by titonton** [comment] 2018-10-01 21:18
Typically i would have to build the application and it would run with the updated code. It's been doing the same for me as well.

**Comment by DanTup** [comment] 2018-10-02 07:04
I think these reports are a dupe of https://github.com/flutter/flutter/issues/16604. I'll close this as a dupe of that to avoid splitting discussion across multiple cases, but happy to re-open if there's anything to suggest there may be a Dart Code issue.

**Closed by DanTup** 2018-10-02 07:04 UTC
Labels: awaiting info
