### ISSUE TITLE
Test status indicator is duplicated

### ISSUE THREAD

**Issue by incendial** [Dart-Code/Dart-Code#4384] opened 2023-02-13 12:54 UTC
**Describe the bug**
Noticed that the test status indicator (play button or spinner) got duplicated for the whole line length of the test.

**To Reproduce**
No steps. This is a new test file and I noticed that it's too much of the visual noise.

**Expected behavior**
Only one indicator.

**Screenshots**
<img width="210" alt="Screenshot 2023-02-13 at 16 51 53" src="https://user-images.githubusercontent.com/21116742/218463125-d1592b86-5b21-4ab3-a71e-3e38c60d3b68.png">

https://user-images.githubusercontent.com/21116742/218462875-3a10062e-ade6-42a3-83c7-b535e246f00e.mov

**Please complete the following information:**
 - Operating System and version: macOS 12.6
 - VS Code version: 1.75.1
 - Dart extension version: 3.58
 - Dart/Flutter SDK version: Dart SDK version: 2.19.0 (stable) (Mon Jan 23 11:29:09 2023 -0800) on "macos_x64"
 - Target device (if the issue relates to Flutter debugging): -

**Comment by DanTup** [comment] 2023-02-14 16:41
I'm not able to reproduce this. Can you reproduce in a new file? Are there any specific steps?

**Comment by incendial** [comment] 2023-02-15 10:10
Unfortunately, no, I don't have any steps either. Feel free to close this one if without the steps it's useless. If I see this again I'll get back.

**Comment by DanTup** [comment] 2023-02-15 11:10
If you see it again, could you also get a screenshot of what the Test Explorer tree looks like for this file?

I'll leave this open for now with the awaiting-info tag. If you see it again post back, and otherwise the bot will close it in ~30 days. Thanks!

**Comment by incendial** [comment] 2023-03-12 09:53
Got this problem again
<img width="676" alt="Screenshot 2023-03-12 at 13 53 08" src="https://user-images.githubusercontent.com/21116742/224537190-2c74859f-6113-49d7-98ca-92656bd535cd.png">

**Comment by incendial** [comment] 2023-03-12 09:53
Test explorer:
<img width="311" alt="Screenshot 2023-03-12 at 13 53 33" src="https://user-images.githubusercontent.com/21116742/224537211-d666e1c9-786b-4769-a93f-79015cb48092.png">

**Comment by incendial** [comment] 2023-03-12 10:04
As you can see, I'm waiting for the icon to appear before writing the body.

https://user-images.githubusercontent.com/21116742/224537754-36dc6f0e-687c-4dc9-99b1-eee0ff4c40ea.mov

**Comment by DanTup** [comment] 2023-03-13 10:06
@incendial I can repro with those steps, thank you!

**Comment by DanTup** [comment] 2023-03-13 11:38
I think this might be entirely a VS Code issue. I was able to adapt their sample to have the full issue (not just duplicated icons, but them not disappearing on the next update - which is what we're seeing here). I've added some notes to https://github.com/microsoft/vscode/issues/176951#issuecomment-1465983379.

Hopefully once that issue is fixed there, it'll be good here. I'll keep this issue open to track it until it's resolved though.

**Comment by incendial** [comment] 2023-03-13 11:44
Interesting that no one else had spotted it 😅. Thank you!

> I think this might be entirely a VS Code issue.

Interesting that I had never had it with TS, for example 🤔.

**Comment by DanTup** [comment] 2023-03-13 12:04
I think it depends on some specifics:

1. The "range" of the test covers the whole line, so VS Code will "expand" it when you're pressing `<enter>` inside it
2. We update the existing test (don't remove/add a new one) when you make changes
3. We compute exactly the same range when we update the test as the one that VS Code expanded to (which I think is causing VS code to short-cut some work, which doesn't re-generate the icons)

So for example the sample test provider they had always truncated the test at the end of the first line, so although the issue showed up briefly when you pressed `<enter>`, the update "fixed" it by replacing the test range which triggers VS Code replacing the duplicated icons.

(there's a lot of assumptions there though, we'll see what they say when it's looked at :-))

**Comment by DanTup** [comment] 2023-06-13 13:38
This was fixed in the latest VS Code.

**Closed by DanTup** 2023-06-13 13:38 UTC
Labels: is bug, in editor, in testing
