### ISSUE TITLE
Dart process without dart code

### ISSUE THREAD

**Issue by neuberoliveira** [Dart-Code/Dart-Code#1699] opened 2019-05-09 14:05 UTC
Everytime vscode start i can see in Activity Monitor that a dart process start running, even on a JS or PHP project without any dart file open in editor.

My question is if this is the expected behavior or i can do something to stop this auto start. Its not to heavy, about 200mb but looks like a bug too me.

thanks.

**Comment by DanTup** [comment] 2019-05-09 14:32
Indeed, that does sound like a bug. Can you confirm that if you run the "Show running processes" comamnd in VS Code, it shows the Dart extension listed?

We tell VS Code when it should activate the extension, and our current rules are listed here:

https://github.com/Dart-Code/Dart-Code/blob/c1722c9b53d6f2dc0226e2dde30fb44c0df7d1b9/package.json#L33-L48

There's nothing obvious in there I can see that could be misunderstood (and I can't repro this - if I open something without Dart files, the extension doesn't activate).

Can you try opening a non-Dart project, then running the **Developer: Show Logs** command in VS Code, and then selecting **Extension Host** and then select the output (`Cmd+A`/`Ctrl+A`) from the Output pane at the bottom, and pasting it here? It should include an activation reason like this:

> [2019-05-09 15:30:41.240] [exthost] [info] ExtensionService#_doActivateExtension Dart-Code.dart-code {"startup":false,"activationEvent":"onLanguage:dart"}

Thanks!

**Comment by neuberoliveira** [comment] 2019-05-10 13:59
so embarrassing, today the dart process wont start :(

```
"workspaceContains:**/pubspec.yaml", 
"workspaceContains:**/*.dart",
```

Maybe this can activate the extension if i had opened some of these files recently? I mean sometimes i need to give a look at an dart file while in a PHP project for example, could these files remain in some kind of recent files/cache on workspace and then trigger the extension to start on next launch?

I will try this later, thanks

**Comment by DanTup** [comment] 2019-05-10 14:51
If you open those files while working on another project, it would activate the extension. The extension would likely remain active for that open folder until it was closed (or another folder opened in its place). It should not, however, result in the extension activating for any other session.

Is it possible you still had the same session open where you had previously opened the pubspec or a Dart file when you saw it?

**Comment by neuberoliveira** [comment] 2019-05-10 15:05
i i open a dart file on a project then switch to another project (with project manager extension) this count as same session? and then trigger dart start??

**Comment by DanTup** [comment] 2019-05-10 15:48
I don't know how the project manager extension works, but if it's causing the extension host to be restarted, then the old Dart process should disappear, and no new one should appear. If it's not causing the extension host to restart, then the old process will remain active.

VS Code doesn't unload extensions when the activation events are no longer applicable though (for example if you open a Dart project then delete all the Dart files, it will remain active).

**Comment by neuberoliveira** [comment] 2019-05-10 17:08
@DanTup now that i was paying more attention it seems a bit random to me.

i do some tests, opening projects (project manager ext) closing vscode entirely, reopen again...... and in one of these the dart cames up, interesting it was on a ReactNative project with no dart file on dir nor on the workspace/opened in editor.

```
[2019-05-10 13:47:12.018] [exthost] [info] extension host started
[2019-05-10 13:47:12.038] [exthost] [info] ExtensionService#_doActivateExtension vscode.debug-auto-launch {"startup":true,"activationEvent":"*"}
[2019-05-10 13:47:12.038] [exthost] [info] ExtensionService#loadCommonJSModule /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/debug-auto-launch/dist/extension
[2019-05-10 13:47:12.058] [exthost] [info] ExtensionService#_doActivateExtension vscode.emmet {"startup":true,"activationEvent":"*"}
[2019-05-10 13:47:12.058] [exthost] [info] ExtensionService#loadCommonJSModule /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/emmet/dist/extension
[2019-05-10 13:47:12.118] [exthost] [info] ExtensionService#_doActivateExtension vscode.git {"startup":true,"activationEvent":"*"}
[2019-05-10 13:47:12.118] [exthost] [info] ExtensionService#loadCommonJSModule /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/git/dist/main
[2019-05-10 13:47:12.266] [exthost] [info] ExtensionService#_doActivateExtension vscode.merge-conflict {"startup":true,"activationEvent":"*"}
[2019-05-10 13:47:12.266] [exthost] [info] ExtensionService#loadCommonJSModule /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/merge-conflict/dist/extension
[2019-05-10 13:47:12.335] [exthost] [info] ExtensionService#_doActivateExtension 2gua.rainbow-brackets {"startup":true,"activationEvent":"*"}
[2019-05-10 13:47:12.336] [exthost] [info] ExtensionService#loadCommonJSModule /Users/neuber/.vscode/extensions/2gua.rainbow-brackets-0.0.6/out/src/extension
[2019-05-10 13:47:12.400] [exthost] [info] ExtensionService#_doActivateExtension alefragnani.Bookmarks {"startup":true,"activationEvent":"*"}
[2019-05-10 13:47:12.400] [exthost] [info] ExtensionService#loadCommonJSModule /Users/neuber/.vscode/extensions/alefragnani.bookmarks-10.4.3/dist/extension
[2019-05-10 13:47:12.515] [exthost] [info] ExtensionService#_doActivateExtension alefragnani.project-manager {"startup":true,"activationEvent":"*"}
[2019-05-10 13:47:12.515] [exthost] [info] ExtensionService#loadCommonJSModule /Users/neuber/.vscode/extensions/alefragnani.project-manager-10.5.1/dist/extension
[2019-05-10 13:47:12.552] [exthost] [info] ExtensionService#_doActivateExtension Equinusocio.vsc-material-theme {"startup":true,"activationEvent":"*"}
[2019-05-10 13:47:12.552] [exthost] [info] ExtensionService#loadCommonJSModule /Users/neuber/.vscode/extensions/equinusocio.vsc-material-theme-2.8.2/out/src/material.theme.config
[2019-05-10 13:47:12.659] [exthost] [info] ExtensionService#_doActivateExtension ms-vscode.sublime-keybindings {"startup":true,"activationEvent":"*"}
[2019-05-10 13:47:12.659] [exthost] [info] ExtensionService#loadCommonJSModule /Users/neuber/.vscode/extensions/ms-vscode.sublime-keybindings-4.0.0/out/extension
[2019-05-10 13:47:12.860] [exthost] [info] ExtensionService#_doActivateExtension PKief.material-icon-theme {"startup":true,"activationEvent":"*"}
[2019-05-10 13:47:12.860] [exthost] [info] ExtensionService#loadCommonJSModule /Users/neuber/.vscode/extensions/pkief.material-icon-theme-3.7.0/dist/extension
[2019-05-10 13:47:12.920] [exthost] [info] ExtensionService#_doActivateExtension waderyan.gitblame {"startup":true,"activationEvent":"*"}
[2019-05-10 13:47:12.920] [exthost] [info] ExtensionService#loadCommonJSModule /Users/neuber/.vscode/extensions/waderyan.gitblame-2.7.0/out/src/index
[2019-05-10 13:47:13.132] [exthost] [info] ExtensionService#_doActivateExtension WakaTime.vscode-wakatime {"startup":true,"activationEvent":"*"}
[2019-05-10 13:47:13.132] [exthost] [info] ExtensionService#loadCommonJSModule /Users/neuber/.vscode/extensions/wakatime.vscode-wakatime-2.1.0/dist/extension
[2019-05-10 13:47:13.244] [exthost] [info] eager extensions activated
[2019-05-10 13:48:34.759] [exthost] [info] extension host started
[2019-05-10 13:48:34.779] [exthost] [info] ExtensionService#_doActivateExtension vscode.typescript-language-features {"startup":false,"activationEvent":"onLanguage:javascript"}
[2019-05-10 13:48:34.779] [exthost] [info] ExtensionService#loadCommonJSModule /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/typescript-language-features/dist/extension
[2019-05-10 13:48:35.563] [exthost] [info] ExtensionService#_doActivateExtension flowtype.flow-for-vscode {"startup":false,"activationEvent":"onLanguage:javascript"}
[2019-05-10 13:48:35.563] [exthost] [info] ExtensionService#loadCommonJSModule /Users/neuber/.vscode/extensions/flowtype.flow-for-vscode-1.1.1/build/index.js
[2019-05-10 13:48:35.816] [exthost] [info] ExtensionService#_doActivateExtension vscode.debug-auto-launch {"startup":true,"activationEvent":"*"}
[2019-05-10 13:48:35.816] [exthost] [info] ExtensionService#loadCommonJSModule /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/debug-auto-launch/dist/extension
[2019-05-10 13:48:35.817] [exthost] [info] ExtensionService#_doActivateExtension vscode.emmet {"startup":true,"activationEvent":"*"}
[2019-05-10 13:48:35.817] [exthost] [info] ExtensionService#loadCommonJSModule /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/emmet/dist/extension
[2019-05-10 13:48:35.821] [exthost] [info] ExtensionService#_doActivateExtension vscode.git {"startup":true,"activationEvent":"*"}
[2019-05-10 13:48:35.821] [exthost] [info] ExtensionService#loadCommonJSModule /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/git/dist/main
[2019-05-10 13:48:35.838] [exthost] [info] ExtensionService#_doActivateExtension vscode.merge-conflict {"startup":true,"activationEvent":"*"}
[2019-05-10 13:48:35.838] [exthost] [info] ExtensionService#loadCommonJSModule /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/merge-conflict/dist/extension
[2019-05-10 13:48:35.840] [exthost] [info] ExtensionService#_doActivateExtension 2gua.rainbow-brackets {"startup":true,"activationEvent":"*"}
[2019-05-10 13:48:35.840] [exthost] [info] ExtensionService#loadCommonJSModule /Users/neuber/.vscode/extensions/2gua.rainbow-brackets-0.0.6/out/src/extension
[2019-05-10 13:48:35.840] [exthost] [info] ExtensionService#_doActivateExtension alefragnani.Bookmarks {"startup":true,"activationEvent":"*"}
[2019-05-10 13:48:35.840] [exthost] [info] ExtensionService#loadCommonJSModule /Users/neuber/.vscode/extensions/alefragnani.bookmarks-10.4.3/dist/extension
[2019-05-10 13:48:35.842] [exthost] [info] ExtensionService#_doActivateExtension alefragnani.project-manager {"startup":true,"activationEvent":"*"}
[2019-05-10 13:48:35.842] [exthost] [info] ExtensionService#loadCommonJSModule /Users/neuber/.vscode/extensions/alefragnani.project-manager-10.5.1/dist/extension
[2019-05-10 13:48:35.846] [exthost] [info] ExtensionService#_doActivateExtension Equinusocio.vsc-material-theme {"startup":true,"activationEvent":"*"}
[2019-05-10 13:48:35.846] [exthost] [info] ExtensionService#loadCommonJSModule /Users/neuber/.vscode/extensions/equinusocio.vsc-material-theme-2.8.2/out/src/material.theme.config
[2019-05-10 13:48:35.851] [exthost] [info] ExtensionService#_doActivateExtension ms-vscode.sublime-keybindings {"startup":true,"activationEvent":"*"}
[2019-05-10 13:48:35.851] [exthost] [info] ExtensionService#loadCommonJSModule /Users/neuber/.vscode/extensions/ms-vscode.sublime-keybindings-4.0.0/out/extension
[2019-05-10 13:48:35.854] [exthost] [info] ExtensionService#_doActivateExtension PKief.material-icon-theme {"startup":true,"activationEvent":"*"}
[2019-05-10 13:48:35.854] [exthost] [info] ExtensionService#loadCommonJSModule /Users/neuber/.vscode/extensions/pkief.material-icon-theme-3.7.0/dist/extension
[2019-05-10 13:48:35.858] [exthost] [info] ExtensionService#_doActivateExtension waderyan.gitblame {"startup":true,"activationEvent":"*"}
[2019-05-10 13:48:35.858] [exthost] [info] ExtensionService#loadCommonJSModule /Users/neuber/.vscode/extensions/waderyan.gitblame-2.7.0/out/src/index
[2019-05-10 13:48:35.870] [exthost] [info] ExtensionService#_doActivateExtension WakaTime.vscode-wakatime {"startup":true,"activationEvent":"*"}
[2019-05-10 13:48:35.870] [exthost] [info] ExtensionService#loadCommonJSModule /Users/neuber/.vscode/extensions/wakatime.vscode-wakatime-2.1.0/dist/extension
[2019-05-10 13:48:54.467] [exthost] [info] ExtensionService#_doActivateExtension Dart-Code.dart-code {"startup":true,"activationEvent":"workspaceContainsTimeout:**/pubspec.yaml,**/*.dart"}
[2019-05-10 13:48:54.467] [exthost] [info] ExtensionService#loadCommonJSModule /Users/neuber/.vscode/extensions/dart-code.dart-code-3.0.1/out/src/extension
[2019-05-10 13:49:06.827] [exthost] [info] eager extensions activated
```

close it if you want, if i found a pattern or more details i come back here.

thanks again

**Comment by DanTup** [comment] 2019-05-10 17:38
Aha, I think this log explains it:

> [2019-05-10 13:48:54.467] [exthost] [info] ExtensionService#_doActivateExtension Dart-Code.dart-code {"startup":true,"activationEvent":"workspaceContainsTimeout:**/pubspec.yaml,**/*.dart"}

This says "workspaceContainsTimeout" and not "workspaceContains"!

From reading some of the VS Code source, it seems like if an extension declares a "workspaceContains" activation event but there's a timeout while searching to see if your workspace contains it, it might just activate anyway. @roblourens - since your name is on some related commits, maybe you can confirm this?

If that's true, then I guess the workspace you've opened is too slow to scan (possibly because it's really big, or the disk access is slow)?

**Comment by roblourens** [comment] 2019-05-10 17:41
Yes, that's right. The intent is to block expensive long-running searches in very large workspaces.

**Comment by neuberoliveira** [comment] 2019-05-10 17:49
>  is too slow to scan (possibly because it's really big, or the disk access is slow)

Possibly both rsrs and sometimes i have docker(for mac) and a ios simulator opened, so this combination could slow the scan even more.

So, its the expected behavior right?

If theres something else i can help just ask.

thanks.

**Comment by DanTup** [comment] 2019-05-11 08:36
@roblourens thanks - is there any way a user or extension can control this (for ex. choosing not to activate in the extension in this case)? Then it could just activate if they actually opened a .dart file? Or can we control how many levels down it'll look (if the dart/pubspec files aren't in the root folder or one or two levels down, it'd also be fine not to activate until they open a dart file).

**Comment by DanTup** [comment] 2019-05-13 08:48
@neuberoliveira it sounds like this is expected behaviour, though if VS Code has any way to control this I'm happy to try and improve it. While the Dart extension could scan the whole tree and not spawn the analysis server if there's no Dart, it seems weird to do when VS Code has specifically chosen not to do it for performance reasons (it would probably be better for the timeout in VS Code to be customisable than that).

As a workaround, if there are common workspaces you open, you could disable the Dart extension for those workspaces. This should prevent VS Code looking to activate it at all.

<img width="368" alt="Screenshot 2019-05-13 at 9 33 24 am" src="https://user-images.githubusercontent.com/1078012/57607077-2c2e7e00-7562-11e9-839f-5a53cf487753.png">

I don't think there's anything I can do here, so I'll close this - but I have opened https://github.com/microsoft/vscode/issues/73656 to see if the Code team have any better ideas for handling this or may be able to provide some more control of this.

Do shout if you have any other issues/questions!

**Closed by DanTup** 2019-05-13 08:48 UTC
Labels: awaiting info, is bug
