### ISSUE TITLE
Error: Not found: 'dart:ui' when trying to run a Flutter project

### ISSUE THREAD

**Issue by noordawod** [Dart-Code/Dart-Code#3834] opened 2022-02-17 08:05 UTC
Trying to run a Flutter project in VS Code yields many errors like this: `Error: Not found: 'dart:ui'`.

From looking at other issues (#2038, #1827) I understand that this is caused by trying to run a Dart project rather than a Flutter project. Well, I believe this is not the case in my project since the status bar does show Flutter and its version, in addition to selection of an emulator. The doctor also reports no issues whatsoever.

**To Reproduce**

I cannot share my code with the community (closed source), but the project opens and runs fine in both Android Studio and IntelliJ IDEA. The top-level directory contains a `pubspec.yaml` with a line reading `sdk: "flutter"`.

**Expected behavior**
The project runs as a Flutter project.

**Screenshots**

![Screenshot_2022-02-17_08-52-14](https://user-images.githubusercontent.com/4129640/154431995-b25ccfc9-cac5-414d-b625-68f3f769573f.png)

![Screenshot_2022-02-17_08-53-30](https://user-images.githubusercontent.com/4129640/154431999-d6280d86-497e-458e-80e9-a705af5e8cdc.png)

![Screenshot_2022-02-17_09-02-17](https://user-images.githubusercontent.com/4129640/154432003-0856dc1f-cd9f-41d9-b83b-9b4139063b90.png)

**Versions (please complete the following information):**
 - VS Code version: 1.64.2
 - Dart extension version: 3.34.0
 - Dart/Flutter SDK version: Flutter 2.11.0-0.0.pre.582 • channel master • Dart 2.17.0 (build 2.17.0-105.0.dev)

**Comment by DanTup** [comment] 2022-02-17 08:08
Are you able to make a small project in the same structure that triggers this that you can share?

Could you try capturing debugging logs while reproducing this?

- Run the [**Dart: Capture Debugging Logs** command](https://dartcode.org/docs/logging/#capture-debugging-logs)
- Reproduce the issue
- Click **Cancel** on the logging notification to stop logging and open the log
- Remove anything sensitive from the log
- Attach the log here (or in a gist)

Thanks!

**Comment by noordawod** [comment] 2022-02-17 08:18
From the log: `[9:12:04 AM] [General] [Info] Project (/path/to/workspace/app/lib/googledevel.dart) not recognised as Flutter or Web, will use Dart debugger`. I don't get why it's not being detected as Flutter, when 5 other subdirectories alongside it (`admin`, `core`, `ui`, `ui_mobile`, `db`) are detected as Flutter projects.

The structure of the workspace:

```
/path/to/workspace
|__ admin/
|     |__ pubspec.yaml
|     |__ lib/
|__ app/
|     |__ pubspec.yaml
|     |__ lib/
|__ core/
|     |__ pubspec.yaml
|     |__ lib/
|__ db/
|     |__ pubspec.yaml
|     |__ lib/
|__ ui/
|     |__ pubspec.yaml
|     |__ lib/
|__ ui_mobile/
      |__ pubspec.yaml
      |__ lib/
```

All of them are Flutter projects. Only the `app/` subdirectory is not detected as a Flutter project... I'm baffled.

**Comment by noordawod** [comment] 2022-02-17 08:20
`.vscode/launch.json` looks like so:

```json
{
	"configurations": [
		{
			"name": "App (Devel)",
			"type": "dart",
			"request": "launch",
			"cwd": "app/",
			"program": "lib/devel.dart",
			"args": [
				"--no-sound-null-safety",
				"--enable-experiment=non-nullable",
				"--enable-experiment=nonfunction-type-aliases",
				"--enable-experiment=constructor-tearoffs"
			]
		}
	]
}
```

**Comment by noordawod** [comment] 2022-02-17 08:22
I'll try to recreate the folder structure in a separate project... I guess it may be a bug afterall in the plugin, so happy to help.

**Comment by DanTup** [comment] 2022-02-17 09:53
> [9:12:04 AM] [General] [Info] Project (/path/to/workspace/app/lib/googledevel.dart) not recognised as Flutter or Web, will use Dart debugger

Are you able to share the log (here or emailing me at logs@dartcode.org)? The path there is supposed to be a project folder, so having `lib/googledevel.dart` on the end looks odd. Could you also share the `pubspec.yaml` for the `app` project?

**Comment by DanTup** [comment] 2022-02-17 09:56
Sorry, I was mistaken - we log the `program` not the project folder. But we use the `debugConfig.cwd` to check for Flutter:

https://github.com/Dart-Code/Dart-Code/blob/2f9483a71327ca010434a985b109bea7f99e8985/src/extension/providers/debug_config_provider.ts#L315

The detection of the SDK is a regex, so if your formatting is different here, perhaps that would do it:

https://github.com/Dart-Code/Dart-Code/blob/2f9483a71327ca010434a985b109bea7f99e8985/src/extension/sdk/utils.ts#L430-L436

**Comment by noordawod** [comment] 2022-02-17 10:30
> > [9:12:04 AM] [General] [Info] Project (/path/to/workspace/app/lib/googledevel.dart) not recognised as Flutter or Web, will use Dart debugger
> 
> Are you able to share the log (here or emailing me at [logs@dartcode.org](mailto:logs@dartcode.org))? The path there is supposed to be a project folder, so having `lib/googledevel.dart` on the end looks odd. Could you also share the `pubspec.yaml` for the `app` project?

Basically, I specify a different template file to run (`flutter run -t ...`) and that's what you saw there, the `lib/googledevel.dart`). I referred to it earlier as `lib/devel.dart` mistakenly.

Anyway, I'll send you the log soon.

**Comment by noordawod** [comment] 2022-02-17 10:39
pubspec.yaml for the app project (strippe down) is below:

```yaml
name: "flutter_app"

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
# Remove this line if you wish to publish to pub.dev
publish_to: "none"

version: "1.0.0"

environment:
  sdk: ">=2.16.0 <3.0.0"
  flutter: ">=2.10.0"

dependencies:
  # List of all deps comes here...

  flutter:
    sdk: "flutter"

  flutter_localizations:
    sdk: "flutter"

dev_dependencies:
  analyzer: "3.2.0"
  build_runner: "2.1.7"
  flutter_lints: "1.0.4"

flutter:
  generate: true
  uses-material-design: false
  assets:
    - "res/"
```

**Comment by DanTup** [comment] 2022-02-17 10:40
Thanks! At a glance, I think it's because of the quotes in `    sdk: "flutter"`. I'll improve the regex to handle these better, but if you can remove them in the meantime it should solve your issue.

**Comment by DanTup** [comment] 2022-02-17 10:53
Done! This will be included in the next release, thanks!

**Closed** 2022-02-17 10:53 UTC
Labels: is bug, in flutter

**Comment by noordawod** [comment] 2022-02-17 13:05
Brilliant, so quick and precise. Love it! Usually, when is the release cycle?

**Comment by DanTup** [comment] 2022-02-17 13:23
Releases are usually monthly (and usually in the first week of the month). There are often pre-release versions in the last week or so of a month too (see https://dartcode.org/releases/v3-32/#v3320-2022-01-02).

**Comment by DanTup** [comment] 2022-03-03 15:52
If you hadn't already noticed, this shipped in the stable release a few days ago.

**Comment by juank27** [comment] 2022-08-23 02:06
if you have the code runner extension installed, you may end up with that extension and not the flutter one.

**Comment by DanTup** [comment] 2022-08-23 09:39
Yeah, using Code Runner can result in this same error because it just runs "dart my_file.dart" and doesn't understand Flutter. I filed an issue to see if Code Runner's buttons could be hidden for Dart when the Dart extension is installed https://github.com/formulahendry/vscode-code-runner/issues/674 although it's had no response yet.

**Comment by Chetan34123456** [comment] 2022-09-17 04:57
I have the same error. Can anyone help me to solve this error as I am a beginner in Flutter development ?

**Comment by DanTup** [comment] 2022-09-17 08:05
@Chetan34123456 the two most common cases of this are:

1. Project is not detected as a Flutter project. You can tell if this is the case because it was show a Dart SDK version ("Dart x.y.z") in the status bar, or the words "Dart from Flutter". If it shows "Flutter x.y.z" in the status bar, then this is not the problem. If this is the problem, it's usually caused by not opening the Flutter projects folder correctly, or not having Flutter correctly referenced in the `pubspec.yaml`.
2. Clicking the Run buttons contributed by the Code Runner extension. Code Runner does not understand Flutter projects and tries to run everything with Dart. If this is the problem you should just launch the app using `F5` or the "other" run button, or the Run menu.

If it's neither of these, please run the **Dart: Capture Debugging Logs** command from the command palette (`F1`), try to run the app (to generate the error), then click **Cancel** on the logging notification to stop logging and open the log file, then file a new issue with the log attached.

Note: The log will contain parts of your source, so best to repro in a clean project (created with the **Flutter: New Project** command).

**Comment by Maxby225** [comment] 2023-04-15 14:29
bonjour cher tous j ai essayé de comprendre vos propos mais éllasse les termes que vous employé sont beaucoup trop techique pour moi , pouvez vous l expliqué à un debutant

**Comment by clebemachado** [comment] 2023-05-27 18:45
Ok, I'm running a dart project instead of flutter, is there a way around this?

**Comment by DanTup** [comment] 2023-05-27 20:42
@clebemachado You can't use `dart:ui` in Dart projects, as it's part of Flutter - see https://github.com/dart-lang/sdk/issues/50854#issuecomment-1366596944.

**Comment by deemKhlaed** [comment] 2023-08-02 13:43
@DanTup hi , I still have the same problem 
could you plz help me
`
name: projectName
description: A new Flutter project.

publish_to: 'none' 
 
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true
`

**Comment by nitinyeranale** [comment] 2023-10-19 08:34
/C:/flutter/packages/flutter/lib/src/material/arc.dart:6:8: Error: Dart library 'dart:ui' is not available on this platform.
import 'dart:ui' show lerpDouble;

Please suggest the answer

**Comment by YusufBabali** [comment] 2024-02-09 19:42
![Ekran görüntüsü 2024-02-09 223830](https://github.com/Dart-Code/Dart-Code/assets/70307919/b0c791fa-b5a7-4e49-867e-10a307e8f2cb)

Hi Mr.
I add my problem as a ss. 
when I run my code by the f5 button problem it works but i couldn't run it from the terminal as seen on SS by writing " dart lib/main.dart "
It's not a problem for now but I feel it going to in further steps.

**Comment by DanTup** [comment] 2024-02-09 19:54
> but i couldn't run it from the terminal as seen on SS by writing " dart lib/main.dart "

This is expected behaviour. Flutter apps are run with `flutter run` not `dart`. Only Dart (non-Flutter) apps can be run with `dart`.

I would recommend using F5/Ctrl+F5 in VS Code though, as you'll get more functionality (such as the debugger) compared to running from the terminal.

**Comment by YusufBabali** [comment] 2024-02-09 20:00
Thank you Mr @DanTup . Your response speed is incredible.

**Comment by Boutheinaikram** [comment] 2024-05-21 15:13
Basically i have issues but i think my problem is my friend give code source which has old version of dart and flutter than i have on my pc so that's cause problem in pubspec.yaml but when i do any change in yaml folder ,the code won't execute like i don't which line attributes that i should change  (sorry for my bad english)

**Comment by DanTup** [comment] 2024-05-21 15:46
@Boutheinaikram I don't think an old version of Dart/Flutter should cause this error, but please open a new issue with a screenshot showing _all of VS Code_ and any error messages so I can take a look. Thanks!

**Comment by Boutheinaikram** [comment] 2024-05-21 17:01
![Screenshot 2024-05-21 174941](https://github.com/Dart-Code/Dart-Code/assets/95092785/56435d63-c35f-4fdc-af97-28cf50eb8086)
![Screenshot 2024-05-21 175016](https://github.com/Dart-Code/Dart-Code/assets/95092785/aa8fdc34-13e5-4f25-8791-1048a7f49644)
![Screenshot 2024-05-21 175456](https://github.com/Dart-Code/Dart-Code/assets/95092785/c8ee1ce9-f14a-4f2a-af19-7067a59a93f4)

![Screenshot 2024-05-21 175550](https://github.com/Dart-Code/Dart-Code/assets/95092785/b965fb04-690b-4800-a754-ee5356475f99)
![Screenshot 2024-05-21 175614](https://github.com/Dart-Code/Dart-Code/assets/95092785/791e609a-af33-4612-b294-c4a086361d0f)


> @Boutheinaikram I don't think an old version of Dart/Flutter should cause this error, but please open a new issue with a screenshot showing _all of VS Code_ and any error messages so I can take a look. Thanks!

here's all the screenshot of all errors and output thanks in advance

**Comment by DanTup** [comment] 2024-05-22 11:22
@Boutheinaikram based on the screenshot, I think you may be running using the Code Runner extension? See my comment above at https://github.com/Dart-Code/Dart-Code/issues/3834#issuecomment-1250025510

The Code Runner extension does not understand Flutter and will try to run Flutter apps using `dart` instead of `flutter`. I would recommend disabling the Code Runner extension in any Dart/Flutter workspaces and using the options from the Dart/Flutter extensions instead.

There's an issue at https://github.com/formulahendry/vscode-code-runner/issues/674 asking for Code Runner to hides it buttons for Dart/Flutter but it unfortunately has not received any response.

**Comment by Boutheinaikram** [comment] 2024-05-22 18:45
i try all ur step but the problem is same and actualy i use android studio to execute ,my friend coded the app in an older version of Dart (3.3.0), and it worked perfectly. However her pc broke, so she transferred her app to my pc. I installed the latest version of dart (3.4.0) and flutter (3.2.0). When I tried to execute it in Android Studio, it didn't work because there was a problem with dart:ui. I thought the issue might be due to the code not being compatible with the versions I have on my pc. So
 I tried to modify the pubspec.yaml file because it had sdk: '>=2.19.6 <3.0.0'. I changed it to sdk: '>=3.0.6 <4.0.0', but it still didn't work. I made sure that the path is correct and everything is clear, but I still don't know where the problem is. here's the error in android studio 

![Screenshot 2024-05-22 190407](https://github.com/Dart-Code/Dart-Code/assets/95092785/72b4297c-593a-4e1c-a3c2-5c99a2a05aeb)

**Comment by DanTup** [comment] 2024-05-22 18:53
@Boutheinaikram the error in your latest screenshot is a different error.

The error shown in your earlier post from VS Code looks like a problem caused by using Code Runner (or something else that's using `dart` to run a Flutter app).

The error in your latest screenshot is indeed because of version changes - the code is trying to use `ThemeData.backgroundColor` but that was [deprecated in Flutter 3.3 and removed in Flutter 3.19](https://docs.flutter.dev/release/breaking-changes/3-19-deprecations#themedata). You will need to update the code to make it compatible with the latest versions of Flutter or switch back to an older Flutter SDK. You might be able to use `dart fix` to update some of these (see https://docs.flutter.dev/tools/flutter-fix).

There are a number of places listed at https://flutter.dev/community#community-grid that may be better suited for general Flutter coding questions/help.
