### ISSUE TITLE
Unable to sync files to device 

### ISSUE THREAD

**Issue by pueffl** [Dart-Code/Dart-Code#2275] opened 2020-02-27 12:39 UTC
Issue Type: <b>Bug</b>

Since about 2 days I am no longer able to debug an application on the android emulator. As I haven't changed anything in the project settings and because everything works fine when I do the same thing in Android Studio, I assume it's a problem with the dart extension, at least it just hangs with:

Syncing files to device Android SDK built for X86...

The only thing I have done so far is updating Android Studio/Android SDK so maybe there are some incompatibilities. But as I just get the message and nothing else, I've no clue what's going on.

If you need any further information, just ask :-)

Extension version: 3.8.1
VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:50:36.977Z)
OS version: Linux x64 5.5.5-200.fc31.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 3900)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|30.89GB (11.31GB free)|
|Process Argv|--no-sandbox --unity-launch|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by DanTup** [comment] 2020-02-27 12:44
Thanks for the report! It sounds like you're running into an issue in Flutter/Dart SDK on Linux kernels >= 5.5:

https://github.com/flutter/flutter/issues/49185

The issue is fixed in `master` and it [sounds like there may be a hotfix to stable](https://github.com/flutter/flutter/issues/49185#issuecomment-591651604).

**Closed** 2020-02-27 12:44 UTC
Labels: duplicate
