### ISSUE TITLE
flutter excpetions not logs in debug console on vscode

### ISSUE THREAD

**Issue by heshesh2010** [Dart-Code/Dart-Code#5026] opened 2024-03-07 14:30 UTC
Hi , 

when I got any errors or exceptions like null values or widgets issues , I see the vs code debug console not print any errors , but mobile screen turned to red and print error there , so before some last updates I was able to get the error logs and can figure out the bug by clicking on exception line and navigate to the buggy code 

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.19.2, on macOS 14.3.1 23D60 darwin-x64, locale en-EG)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] VS Code (version 1.87.0)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!

**Comment by DanTup** [comment] 2024-03-07 14:40
Can you provide a screenshot of VS Code when the exception has occurred with the Debug Console and status bar completely visible?

Can you also confirm how you are starting the application (what button/link/menu you're using)?

I just tested, and when I get exceptions first the debugger pauses, and if I step over the exception I then see the output in the debug console:

![image](https://github.com/Dart-Code/Dart-Code/assets/1078012/877832b6-51cd-47a7-ac42-82b255347759)

Detailed steps (and perhaps a code sample if it may be specific to this exception) would help. Thanks!

**Comment by heshesh2010** [comment] 2024-03-07 15:18
> Can you provide a screenshot of VS Code when the exception has occurred with the Debug Console and status bar completely visible?
> 
> Can you also confirm how you are starting the application (what button/link/menu you're using)?
> 
> I just tested, and when I get exceptions first the debugger pauses, and if I step over the exception I then see the output in the debug console:
> 
> ![image](https://private-user-images.githubusercontent.com/1078012/310917278-877832b6-51cd-47a7-ac42-82b255347759.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk4MjQ5MjEsIm5iZiI6MTcwOTgyNDYyMSwicGF0aCI6Ii8xMDc4MDEyLzMxMDkxNzI3OC04Nzc4MzJiNi01MWNkLTQ3YTctYWM0Mi04MmIyNTUzNDc3NTkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMDdUMTUxNzAxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzI5MDgyMGY3MWY4NDRhMmM2ZDk0YTgxZDE4NTNiYzNjNmUxNThmZDQ4MTE0NjM0OWViODlmMzBmYjNkMGFlYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.CdT6H7AnnZvHz5_C6IqKZQY3Eg73fvPpixL8DMQIZRk)
> 
> Detailed steps (and perhaps a code sample if it may be specific to this exception) would help. Thanks!

see this screenshot 
![Screenshot 2024-03-07 at 5 16 24 PM](https://github.com/Dart-Code/Dart-Code/assets/16393042/7b585f63-e14c-4172-86cc-224b35d8296d)

it's only pauses when I check all exceptions in break points vscode tap , but when I unchecked it there is no error printed in vs code debug console .

I hit play button and i'm sure running debug mode .

**Comment by heshesh2010** [comment] 2024-03-07 15:27
@DanTup here is another screenshot
![Screenshot 2024-03-07 at 5 16 24 PM](https://github.com/Dart-Code/Dart-Code/assets/16393042/3cdc876b-352d-4174-bc9a-47c03d667d83)

**Comment by DanTup** [comment] 2024-03-07 15:38
Are you able to extract a small repro that triggers this issue that you can share (or reproduce the same issue in a new project)?

I'm not sure what's happening - the red background does suggest Flutter caught the exception, however it's not clear to me a) why there is no yellow text or b) why there's no error output.

I can't see the Debug toolbar in your second screenshot but I presume the app is not paused at this point? (eg. the debug toolbar shows a pause button, not a play button)

**Comment by heshesh2010** [comment] 2024-03-07 18:39
> Are you able to extract a small repro that triggers this issue that you can share (or reproduce the same issue in a new project)?
> 
> I'm not sure what's happening - the red background does suggest Flutter caught the exception, however it's not clear to me a) why there is no yellow text or b) why there's no error output.
> 
> I can't see the Debug toolbar in your second screenshot but I presume the app is not paused at this point? (eg. the debug toolbar shows a pause button, not a play button)

I tested new empty project with some exceptions in layout widget and it's logs working , but in my project it's still not logs any error I don't know why , I have attached new screen shot to see the debug toolbar 

![Screenshot 2024-03-07 at 8 39 21 PM](https://github.com/Dart-Code/Dart-Code/assets/16393042/f51fefdd-0339-41a1-9c88-057bbcc99de5)

**Comment by DanTup** [comment] 2024-03-07 18:48
Thanks - is there any way you can extract a repro from your project - for example making a copy of it and then just removing as much as possible until you have something you can share but still triggers the issue? It's possible while doing that you'll find the difference between this and the new test project too.

**Comment by heshesh2010** [comment] 2024-03-07 19:33
> Thanks - is there any way you can extract a repro from your project - for example making a copy of it and then just removing as much as possible until you have something you can share but still triggers the issue? It's possible while doing that you'll find the difference between this and the new test project too.

I got it , this cuz firebase FirebaseCrashlytics plugin was blocking logs 

I was using this code in main.dart

`
  // Pass all uncaught "fatal" errors from the framework to Crashlytics
  FlutterError.onError = FirebaseCrashlytics.instance.recordFlutterFatalError;
  FlutterError.onError = (errorDetails) {
    if (!kDebugMode)
      FirebaseCrashlytics.instance.recordFlutterFatalError(errorDetails);
  };
  // Pass all uncaught asynchronous errors that aren't handled by the Flutter framework to Crashlytics
  PlatformDispatcher.instance.onError = (error, stack) {
    if (!kDebugMode)
      FirebaseCrashlytics.instance.recordError(error, stack, fatal: true);
    return true;
  };`

after removing the plugin and this code , errors now logs in console as expected

**Comment by DanTup** [comment] 2024-03-07 19:37
Ah, I see. Seems like this is working as intended if you're replacing the error handler then.

I'll close this, but let me know if you think there's still something wrong.

**Closed by DanTup** 2024-03-07 19:37 UTC
Labels: is bug, awaiting info
