### ISSUE TITLE
Unable to break in certain files, while running widget test

### ISSUE THREAD

**Issue by HerrNiklasRaab** [Dart-Code/Dart-Code#2461] opened 2020-05-15 16:35 UTC
I am unable to break on breakpoints in certain files. As you can see in the video, I am able to debug those parts where hitting a breakpoint is impossible.

Yesterday I was able to break on those breakpoints, so it might be a cache issue of some sort. I don't know.

Video: https://imgur.com/bmeeU92
Logs: [Dart-Code-Log-2020-04-05 18-27-20.txt.zip](https://github.com/Dart-Code/Dart-Code/files/4635713/Dart-Code-Log-2020-04-05.18-27-20.txt.zip)

**EDIT:**

I have sent a reproducible example to: logs@dartcode.org

Steps to reproduce:
- Set a breakpoint at: "fazua_toolbox_app/lib/widgets/questionnaire_lib/questionnaire_bloc.dart" (L ine 42)
- Execute test "can only advance via button to next page when input is valid" in "fazua_toolbox_app/test/widget_tests/questionnaire_test.dart"

This way, the breakpoint will not hit.

Optional steps:
- Set a breakpoint at: "fazua_toolbox_app/lib/widgets/questionnaire_lib/questionnaire.dart" (Line 41). This is the last position, where the breakpoint will hit, but you still can step into the area, where hitting a breakpoint is impossible.

Further digging:
- We can reproduce on Linux/macOS (didn't tried windows)
- We can reproduce on different machines
- Does only occur when running widget test, does work when running the whole app.
- I also tried to restart my computer.

Flutter doctor:

> Doctor summary (to see all details, run flutter doctor -v):
> [✓] Flutter (Channel stable, v1.17.0, on Mac OS X 10.15.4 19E287, locale de-DE)
>  
> [✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
> [✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
> [✓] Android Studio (version 3.6)
> [✓] VS Code (version 1.45.1)
> [!] Connected device
>     ! No devices available
> 
> ! Doctor found issues in 1 category.

**Comment by DanTup** [comment] 2020-05-18 11:15
I can repro this - and the VM responds like this:

```js
<== {
	"jsonrpc": "2.0",
	"error": {
		"code": 102,
		"message": "Cannot add breakpoint",
		"data": {
			"request": {
				"method": "addBreakpointWithScriptUri",
				"params": {
					"isolateId": "isolates\/3679656534191903",
					"scriptUri": "file:\/\/\/Users\/danny\/Desktop\/Downloads\/fazua_toolbox_hide_show_pages\/fazua_toolbox_app\/lib\/widgets\/questionnaire_lib\/questionnaire_bloc.dart",
					"line": "42"
				}
			},
			"details": "addBreakpointWithScriptUri: Cannot add breakpoint at line '42'"
		}
	},
	"id": "1361"
}
```

I'm unable to repro in a small sample which I created that generally looks the same, but I can repro in Android Studio.

If I try to set the breakpoint using Observatory using `package:` URIs and file paths, I get this:

```
$ break package:fazua_toolbox/widgets/questionnaire_lib/questionnaire_bloc.dart:42
Script 'package:fazua_toolbox/widgets/questionnaire_lib/questionnaire_bloc.dart' is ambiguous
$ break file:///Users/danny/Desktop/Downloads/fazua_toolbox_hide_show_pages/fazua_toolbox_app/lib/widgets/questionnaire_lib/questionnaire_bloc.dart:42
Function 'file:///Users/danny/Desktop/Downloads/fazua_toolbox_hide_show_pages/fazua_toolbox_app/lib/widgets/questionnaire_lib/questionnaire_bloc.dart:42' not found
$ break /Users/danny/Desktop/Downloads/fazua_toolbox_hide_show_pages/fazua_toolbox_app/lib/widgets/questionnaire_lib/questionnaire_bloc.dart:42
Script '/Users/danny/Desktop/Downloads/fazua_toolbox_hide_show_pages/fazua_toolbox_app/lib/widgets/questionnaire_lib/questionnaire_bloc.dart' not found
```

@zichangg @bkonyi any ideas what might cause this? My instinct was that maybe the path was being imported with both file:// and package: schemes (since the ambiguous error seems to happen when the lookup finds more than one script), however I can't see any imports containing "lib", and I would've expected the file path breakpoints above to work. I couldn't find any way on Observatory to list all scripts.

**Comment by DanTup** [comment] 2020-05-18 11:24
I got the scripts list and it is listed twice:

```
{
	"type": "@Script",
	"fixedId": true,
	"id": "libraries\/@23474256\/scripts\/package%3Afazua_toolbox%2Fwidgets%2Fquestionnaire_lib%2Fquestionnaire_bloc.dart\/1722782b696",
	"uri": "package:fazua_toolbox\/widgets\/questionnaire_lib\/questionnaire_bloc.dart",
	"_kind": "kernel"
},
{
	"type": "@Script",
	"fixedId": true,
	"id": "libraries\/@27439137\/scripts\/package%3Afazua_toolbox%2Fwidgets%2Fquestionnaire_lib%2Fquestionnaire_bloc.dart\/1722782b664",
	"uri": "package:fazua_toolbox\/widgets\/questionnaire_lib\/questionnaire_bloc.dart",
	"_kind": "kernel"
},
```

The library ref for the first entry is the one with the same filename, however the library ID in the second instance is `test\/widget_tests\/test_util.dart`. That file does import this script like this:

```
import 'package:fazua_toolbox/widgets/questionnaire_lib/questionnaire_bloc.dart';
```

However I'm not sure why this would result in the script being loaded a second time with the test libraries ID in the script ID.

**Comment by HerrNiklasRaab** [comment] 2020-06-04 07:31
Hey @zichangg @bkonyi, any idea?

**Comment by DanTup** [comment] 2020-10-27 11:50
This seems to be an upstream issue and there's an open issue in Flutter about it at https://github.com/flutter/flutter/issues/66832 so closing this as a dupe of that. We can re-open this if it turns out to need changes here.

**Closed** 2020-10-27 11:50 UTC
Labels: upstream in dart / flutter

**Comment by easazade** [comment] 2022-01-09 06:15
if you're still experiencing this in 2022 maybe changing the file name would help you. in my case i had a file named `s.dart` changed its name to `s_class.dart` and it fixed it
