### ISSUE TITLE
Flutter debug in emulator stuck in Syncing files to device Android SDK

### ISSUE THREAD

**Issue by svarog0** [Dart-Code/Dart-Code#2264] opened 2020-02-21 12:07 UTC
Using vscode on Manjaro Linux when i hit the F5 key the launch of my app is stuck at:

![image](https://user-images.githubusercontent.com/30514498/75030888-b6e5c700-546a-11ea-98c5-c9a435c83b58.png)

But when i execute -> flutter run in a terminal the app launchs with no problem.

This is my flutter doctor info:

[svarog@nidavellir clima]$ flutter doctor -v
[✓] Flutter (Channel dev, v1.15.3, on Linux, locale es_MX.UTF-8)
    • Flutter version 1.15.3 at /home/svarog/flutter
    • Framework revision 67826bdce5 (hace 11 días), 2020-02-10 14:59:32 -0800
    • Engine revision 6158f03ef5
    • Dart version 2.8.0 (build 2.8.0-dev.8.0 514a8d4c84)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /home/svarog/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = google-chrome-stable

[✓] Android Studio (version 3.5)
    • Android Studio at /opt/android-studio
    • Flutter plugin version 43.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] Connected device (3 available)
    • Android SDK built for x86 • emulator-5554 • android-x86    • Android 10 (API 29) (emulator)
    • Chrome                    • chrome        • web-javascript • Google Chrome 80.0.3987.116
    • Web Server                • web-server    • web-javascript • Flutter Tools

• No issues found!
[svarog@nidavellir clima]$ 

Also if i use Android Studio I don't have this problem.

**Comment by DanTup** [comment] 2020-02-21 14:04
Does it happen if you use `Debug -> Run without Debugging`? Or only when debugging? Does it happen only with this specific app, or also a clean `flutter create` app?

Could you capture a log (using the [**Dart: Capture Logs**](https://dartcode.org/docs/logging/#capture-logs-command) command). You can untick the **Analysis Server** option, but leave the others ticked. Make sure there's nothing sensitive in the log and provide a link to a gist or similar.

Thanks!

**Comment by svarog0** [comment] 2020-02-22 12:40
Hi, I've done what you mention with just F5 (Start Debugging) an this is the result:

![image](https://user-images.githubusercontent.com/30514498/75092464-54113000-553d-11ea-8dc4-fcad22129986.png)

[Dart-Code-Log-2020-01-06 06-33-05.txt](https://github.com/Dart-Code/Dart-Code/files/4239353/Dart-Code-Log-2020-01-06.06-33-05.txt)

And with the Ctrl+F5 (Start without Debugging) happens the same, this is the log:

![image](https://user-images.githubusercontent.com/30514498/75092529-00ebad00-553e-11ea-9a12-932e66ff1088.png)


And in both cases the emulator screen keeps blank:

![image](https://user-images.githubusercontent.com/30514498/75092540-27a9e380-553e-11ea-8d47-11fcc2e02cf3.png)

I'll appreciate any help you can provide me.

Thanks!

**Comment by DanTup** [comment] 2020-02-24 11:28
I think you might be hitting an issue in Flutter when running on recent Linux kernels:

https://github.com/flutter/flutter/issues/49185

From the most recent comments, it seems like there is a fix in the works, and it may be back-ported to the stable channel once merged.

Let me know if this seems likely, and I'll close this as a dupe of that. Thanks!

**Comment by ararage** [comment] 2020-02-29 03:55
The same problem  with Fedora 31

Linux Info
```
$ cat /etc/os-release 
NAME=Fedora
VERSION="31 (Workstation Edition)"
ID=fedora
VERSION_ID=31
VERSION_CODENAME=""
PLATFORM_ID="platform:f31"
PRETTY_NAME="Fedora 31 (Workstation Edition)"
ANSI_COLOR="0;34"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:31"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f31/system-administrators-guide/"
SUPPORT_URL="https://fedoraproject.org/wiki/Communicating_and_getting_help"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=31
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=31
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
VARIANT="Workstation Edition"
VARIANT_ID=workstation
```
Flutter Doctor

```
$flutter doctor -v    
[✓] Flutter (Channel unknown, v1.12.13+hotfix.8, on Linux, locale en_US.UTF-8)
    • Flutter version 1.12.13+hotfix.8 at /opt/flutter
    • Framework revision 0b8abb4724 (2 weeks ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /home/ararage_safe/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-R, build-tools 29.0.2
    • ANDROID_HOME = /home/ararage_safe/Android/Sdk
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Android Studio (version 3.5)
    • Android Studio at /opt/android-studio
    • Flutter plugin version 41.0.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.42.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.8.1

[✓] Connected device (1 available)
    • AOSP on IA Emulator • emulator-5556 • android-x86 • Android 9 (API 28)
      (emulator)

• No issues found!
```

![Screenshot from 2020-02-28 21-53-25](https://user-images.githubusercontent.com/7683853/75600434-003ea380-5a75-11ea-8e86-bbc258aae6c4.png)

**Comment by DanTup** [comment] 2020-02-29 11:40
I believe all of these are the issue linked in https://github.com/Dart-Code/Dart-Code/issues/2264#issuecomment-590277155. If you're seeing issues and are not on a recent Linux Kernel, then please file a new issue - otherwise please subscribe to the Flutter issue linked above. Thanks!

**Closed by DanTup** 2020-02-29 11:40 UTC
Labels: awaiting info

**Comment by JohnGalt1717** [comment] 2024-05-11 20:59
I'm getting similar on Windows.

**Comment by DanTup** [comment] 2024-05-13 13:35
@JohnGalt1717 could you file a new issue and include details/screenshots of what you're seeing, and the full output of running the **Flutter: Run Flutter Doctor** command from VS Code?

Thanks!
