### ISSUE TITLE
Race condition when using multiple isolates

### ISSUE THREAD

**Issue by anthonymoretti** [Dart-Code/Dart-Code#5252] opened 2024-09-06 13:45 UTC
**Describe the bug**
Breakpoints don't work with multiple isolates unless a post-frame callback is used.
Related to #5220.

**To Reproduce**
1. Run the code sample on macOS.
2. Set a breakpoint on `Widget build(BuildContext context) {`.
3. Click FAB.

**Expected behavior**
Program breaks on breakpoint after each push of the FAB.

<details open><summary><strong>Code sample</strong></summary>

```dart
import 'dart:isolate';

import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

void _isolateEntryPoint(Map<String, Object?> message) {
  final sendPort = message['sendPort'] as SendPort;
  Isolate.exit(sendPort, null);
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Isolates bug',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const MyHomePage(title: 'Isolates bug'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  final _receivePort = ReceivePort();
  var _receivePortIsListening = false;

  void _spawnIsolate() {
    if (!_receivePortIsListening) {
      _receivePort.listen(_onIsolateData);
      _receivePortIsListening = true;
    }

    Isolate.spawn(_isolateEntryPoint, {'sendPort': _receivePort.sendPort});
  }

  void _onIsolateData(message) {
    debugPrint('Isolate has completed.');

    setState(() {});

    // Run this line (break points won't work):
    _compute();

    // Or

    // Run this line (break points will work):
    // WidgetsBinding.instance.addPostFrameCallback((_) => _compute());
  }

  void _compute() {
    compute(
      (message) => debugPrint(message['key']),
      {'key': 'Compute function has completed.'},
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        title: Text(widget.title),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _spawnIsolate,
        child: const Icon(Icons.play_arrow_outlined),
      ),
    );
  }
}
```

</details>

<details>

<summary><strong>Workspace Environment</strong></summary>

```text
Dart Code extension: 3.96.0
Flutter extension: 3.96.0 (activated)

App: Visual Studio Code
App Host: desktop
Version: mac 1.93.0

Workspace type: Flutter (LSP)
Workspace name: bug_2024_09_06

Dart (3.5.2): /Users/anthonymoretti/Development/flutter/bin/cache/dart-sdk
Flutter (3.24.2): /Users/anthonymoretti/Development/flutter (macOS (darwin/macos))

```

</details>

<details>

<summary><strong>Output from 'dart info'</strong></summary>

`/Users/anthonymoretti/Development/flutter/bin/cache/dart-sdk/bin/dart info`

If providing this information as part of reporting a bug, please review the information
below to ensure it only contains things you're comfortable posting publicly.

#### General info

- Dart 3.5.2 (stable) (Wed Aug 28 10:01:20 2024 +0000) on "macos_x64"
- on macos / Version 14.6.1 (Build 23G93)
- locale is en-US

#### Project info

- sdk constraint: '^3.5.2'
- dependencies: cupertino_icons, flutter
- dev_dependencies: flutter_lints, flutter_test

#### Process info

| Memory |  CPU | Elapsed time | Command line                                                                    |
| -----: | ---: | -----------: | ------------------------------------------------------------------------------- |
|  61 MB | 0.0% |     01:03:09 | dart devtools --machine --allow-embedding --dtd-uri ws:<path>/XYlfE2vKxdxYN94m  |
| 707 MB | 0.0% |     01:03:09 | dart language-server --protocol=lsp --client-id=VS-Code --client-version=3.96.0 |
|  73 MB | 0.0% |     01:03:09 | dart tooling-daemon --machine                                                   |
|  80 MB | 0.0% |     01:03:09 | flutter_tools.snapshot daemon                                                   |

</details>

<details>

<summary><strong>Output from 'flutter doctor'</strong></summary>

`/Users/anthonymoretti/Development/flutter/bin/flutter doctor -v`

```text
[✓] Flutter (Channel stable, 3.24.2, on macOS 14.6.1 23G93 darwin-x64, locale en-US)
    • Flutter version 3.24.2 on channel stable at /Users/anthonymoretti/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4cf269e36d (3 days ago), 2024-09-03 14:30:00 -0700
    • Engine revision a6bd3f1de1
    • Dart version 3.5.2
    • DevTools version 2.37.2

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/to/macos-android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15F31d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/to/macos-android-setup for detailed instructions).

[✓] VS Code (version 1.93.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.94.0

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.
```

</details>

**Comment by DanTup** [comment] 2024-09-09 11:55
I can reproduce this, and there are two issues I see intermittently, but unfortunately they appear to be issues in VS Code that will need fixing there.

The first issue is the one previously discussed that's filed at https://github.com/microsoft/vscode/issues/224832, where the state of threads gets corrupted when there are multiple threads starting/stopping. Here's an example reproducing the issue, where it looks like execution is immediately resumed after hitting the breakpoint:

https://github.com/user-attachments/assets/d1c85291-e6c4-4bf7-a2f2-d273f857ad90

Checking the DAP logs, thread 1 is paused and VS Code asks for a StackTrace, but we never tell VS Code the thread has exited or resumed:

![image](https://github.com/user-attachments/assets/a4e183f7-4ef5-4cb0-8b00-2141f7c336c3)



The second issue I only saw once and haven't been able to repro, but what I saw was that the main thread does still appear as paused in the call stack view - however, the start/exit of the additional thread seems to cause it to become unselected, so you end up with a paused thread but it's not obvious it's paused unless you click on it again in the call stack. I'm not sure if this is caused by the first issue or not, but it's difficult to debug without reproducing. I think once the first issue is fixed, this issue will either disappear, or it'll be much easier to get a log in which case I can try reproduce in a mock debug adapter and file another VS Code issue for that.

I'll keep this issue open as a reminder to test that second issue once the initial issue is fixed in VS Code. There's not much else we can do for now - but I'd encourage adding 👍 to https://github.com/microsoft/vscode/issues/224832.

Thanks!

**Closed** 2024-11-12 12:33 UTC
Labels: is bug, in debugger

**Comment by DanTup** [comment] 2024-11-12 14:04
This turned out not to be a VS Code bug, but a difference between the the default value in the DAP spec versus VS Code.

I have a fix open in the SDK (https://dart-review.googlesource.com/c/sdk/+/394301) but have applied a workaround here to cover until it ships in an SDK release (b1323dea11bd0bedc6dfac0de894f0425e43cd20).

I've pushed a pre-release version of the extension (version v3.101.**20241112**) if you want to try out this fix before it makes a stable extension release:

<img width="703" alt="Dart pre-release versions" src="https://user-images.githubusercontent.com/1078012/218796750-90a70b0b-4957-468c-8eb4-688095cde112.png">
