### ISSUE TITLE
Flutter dart memory leak on mac os

### ISSUE THREAD

**Issue by sooxt98** [Dart-Code/Dart-Code#2996] opened 2020-12-09 12:21 UTC
I think its related to this plugin, maybe i enable LSP that my dart server doesn't support 
https://github.com/dart-lang/sdk/issues/44413

**Comment by DanTup** [comment] 2020-12-09 14:21
Thanks for the report! If you enable LSP for a Dart language server that doesn't support it, it would fail to start with an error. I don't think it's that - although it's worth trying to disable LSP and performing the same steps and seeing whether you're seeing different memory usage when LSP is enabled (if so, that may be a bug in the LSP server).

It's not clear from the other issue which Dart process is using the memory so I'd recommend running the command noted (`ps aux | grep -i dart` - this does work on a Mac) and posting the output there. I suspect the process will be the `analysis_server.dart.snapshot` process mentioned there.

If the issue is in the analysis/LSP server, that code all lives in the dart-lang/sdk repo, so that's the best place to continue the discussion, so I'll close this one as a dupe of that and I'll keep an eye on that issue in case I can help out if the issue is specific to the LSP server.

As a first step, please post the output of `ps aux | grep -i dart` to https://github.com/dart-lang/sdk/issues/44413 while the memory usage is high. Thanks!

**Closed by DanTup** 2020-12-09 14:21 UTC
Labels: is bug
