### ISSUE TITLE
Hot Reload option missing in debugging mode on Flutter master

### ISSUE THREAD

**Issue by seanmc86** [Dart-Code/Dart-Code#2775] opened 2020-09-07 09:45 UTC
VSCode Version: 1.48.2
Dart Code Version: 3.14.0
OS: MacOS

Hot Reload option is not showing in either the Command Palette or the Debug Toolbar when running in debugging mode. Only Hot Restart is available via the Toolbar.

![Screenshot 2020-09-07 at 10 37 36](https://user-images.githubusercontent.com/26269961/92373974-0930c180-f0f7-11ea-988f-96332f04f3ba.png)

If I run via command line:

> flutter run --flavor dev

... then I can hot reload as expected via the 'r' key.

![Screenshot 2020-09-07 at 10 42 48](https://user-images.githubusercontent.com/26269961/92373960-03d37700-f0f7-11ea-8712-74345a7c5304.png)

My launch.json:

```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Flutter Dev",
            "type": "dart",
            "request": "launch",
            "args": [
                "--flavor",
                "dev",
            ]
        }
}
```

[Dart-Code-Log-2020-08-01 10-49-57.txt](https://github.com/Dart-Code/Dart-Code/files/5182446/Dart-Code-Log-2020-08-01.10-49-57.txt)

**Comment by DanTup** [comment] 2020-09-07 11:47
I've not been able to reproduce this on Flutter master or stable. Is there anything that might be unusual about your project? Can you repro it on a new project created with **Flutter: New Project**?

A log file may be useful that includes all of the Flutter and VM Service traffic. Run the **Dart: Capture Logs** command and leave everything ticked except analysis server, then run the app and wait for it to fully load, before clicking **Cancel** on the logging notification and attaching the log. Thanks!

**Comment by seanmc86** [comment] 2020-09-07 12:26
> Is there anything that might be unusual about your project? 
Can't say I'd know what would qualify it as unusual, I wouldn't think so? It's an Android/iOS app with a fairly standard dependency structure, with flavors.

> Can you repro it on a new project created with **Flutter: New Project**?
Yes, I get the same result.

> A log file may be useful that includes all of the Flutter and VM Service traffic. 
Attached sample from the new project.

[Dart-Code-Log-2020-08-01 13-22-58.txt](https://github.com/Dart-Code/Dart-Code/files/5183063/Dart-Code-Log-2020-08-01.13-22-58.txt)

**Comment by DanTup** [comment] 2020-09-07 13:10
Thanks!

Your log doesn't include the service extensions loading, which is why this isn't showing up. My log shows them loading after subscribing:

```
[2:01:47 PM] [VmService] [Info] [Flutter (iPhone SE (2nd generation))] <== {"jsonrpc":"2.0", "result":{"type":"Version","major":3,"minor":38,"_privateMajor":0,"_privateMinor":0},"id":"0"}
[2:01:47 PM] [VmService] [Info] [Flutter (iPhone SE (2nd generation))] ==> {"id":"1","jsonrpc":"2.0","method":"streamListen","params":{"streamId":"Isolate"}}
[2:01:47 PM] [VmService] [Info] [Flutter (iPhone SE (2nd generation))] ==> {"id":"2","jsonrpc":"2.0","method":"streamListen","params":{"streamId":"Extension"}}
[2:01:47 PM] [VmService] [Info] [Flutter (iPhone SE (2nd generation))] ==> {"id":"3","jsonrpc":"2.0","method":"streamListen","params":{"streamId":"Debug"}}
[2:01:47 PM] [VmService] [Info] [Flutter (iPhone SE (2nd generation))] ==> {"id":"4","jsonrpc":"2.0","method":"streamListen","params":{"streamId":"Service"}}
[2:01:47 PM] [VmService] [Info] [Flutter (iPhone SE (2nd generation))] <== {"jsonrpc":"2.0","id":"1","result":{"type":"Success"}}
[2:01:47 PM] [VmService] [Info] [Flutter (iPhone SE (2nd generation))] <== {"jsonrpc":"2.0","method":"streamNotify","params":{"streamId":"Service","event":{"type":"Event","kind":"ServiceRegistered","timestamp":1599483707087,"service":"reloadSources","method":"s0.reloadSources","alias":"Flutter Tools"}}}
[2:01:47 PM] [VmService] [Info] [Flutter (iPhone SE (2nd generation))] <== {"jsonrpc":"2.0","method":"streamNotify","params":{"streamId":"Service","event":{"type":"Event","kind":"ServiceRegistered","timestamp":1599483707087,"service":"reloadMethod","method":"s0.reloadMethod","alias":"Flutter Tools"}}}
[2:01:47 PM] [VmService] [Info] [Flutter (iPhone SE (2nd generation))] <== {"jsonrpc":"2.0","method":"streamNotify","params":{"streamId":"Service","event":{"type":"Event","kind":"ServiceRegistered","timestamp":1599483707087,"service":"hotRestart","method":"s0.hotRestart","alias":"Flutter Tools"}}}
[2:01:47 PM] [VmService] [Info] [Flutter (iPhone SE (2nd generation))] <== {"jsonrpc":"2.0","method":"streamNotify","params":{"streamId":"Service","event":{"type":"Event","kind":"ServiceRegistered","timestamp":1599483707087,"service":"flutterVersion","method":"s0.flutterVersion","alias":"Flutter Tools"}}}
[2:01:47 PM] [VmService] [Info] [Flutter (iPhone SE (2nd generation))] <== {"jsonrpc":"2.0","method":"streamNotify","params":{"streamId":"Service","event":{"type":"Event","kind":"ServiceRegistered","timestamp":1599483707087,"service":"compileExpression","method":"s0.compileExpression","alias":"Flutter Tools"}}}
[2:01:47 PM] [VmService] [Info] [Flutter (iPhone SE (2nd generation))] <== {"jsonrpc":"2.0","method":"streamNotify","params":{"streamId":"Service","event":{"type":"Event","kind":"ServiceRegistered","timestamp":1599483707087,"service":"flutterMemoryInfo","method":"s0.flutterMemoryInfo","alias":"Flutter Tools"}}}
[2:01:47 PM] [VmService] [Info] [Flutter (iPhone SE (2nd generation))] <== {"jsonrpc":"2.0","method":"streamNotify","params":{"streamId":"Service","event":{"type":"Event","kind":"ServiceRegistered","timestamp":1599483707087,"service":"flutterGetSkSL","method":"s0.flutterGetSkSL","alias":"Flutter Tools"}}}
```

I thought this might be a race (eg. they load before we subscribe), but since in my log they show up before the VM service responds to the subscription, I think it's deliberately sending the loaded extensions as part of subscribing (and [this code/comment](https://github.com/dart-lang/sdk/blob/07cd62af19a340172506d9039a789a0085374087/pkg/vm_service/lib/src/service_extension_registry.dart#L53)might be describing that).

@seanmc86 if you load DevTools using the command in VS Code, is the hot reload button available there? I think it uses the same thing to determine whether it's available.

@devoncarew @jonahwilliams do you know of any reasons the tools service extensions (`reloadSources`, `hotRestart`) might not show up (or might not be registered)?

**Comment by seanmc86** [comment] 2020-09-07 13:50
> @seanmc86 if you load DevTools using the command in VS Code, is the hot reload button available there? I think it uses the same thing to determine whether it's available.

If I try open the web version via the Command Palette, nothing happens. Manually connecting to the debug session works, but then I do not see the hot reload button there either:

![Screenshot 2020-09-07 at 14 48 02](https://user-images.githubusercontent.com/26269961/92394434-72293100-f119-11ea-87e5-a60df5f4a02d.png)

**Comment by DanTup** [comment] 2020-09-07 14:23
@seanmc86 can you confirm exactly what commit of Flutter you're on with `flutter --version` and also run `git status` in your Flutter SDK folder to ensure there are no modifications so I can try the exact version here. I can see some code paths that would result in using the "cold" runner, but it doesn't seem like any should apply here.

Thanks!

**Comment by seanmc86** [comment] 2020-09-07 14:43
> $ flutter --version
> Flutter 1.22.0-10.0.pre.87 • channel master • ssh://git@github.com/flutter/flutter.git
> Framework • revision 4732a214a7 (3 days ago) • 2020-09-04 21:05:02 -0400
> Engine • revision ac8b9c4c52
> Tools • Dart 2.10.0 (build 2.10.0-86.0.dev)

> Macs-MacBook-Pro:flutter sean$ git status
> On branch master
> Your branch is up to date with 'origin/master'.
> 
> nothing to commit, working tree clean

**Comment by DanTup** [comment] 2020-09-07 15:32
Same version here. Do you have Android Studio/IntelliJ installed - if so, are you able to check whether it happens if you launch it from there? Have you recently run in release/profile mode? Could you also try renaming the `build` and `.dart_tool` folders out of the way and see if that changes anything?

**Comment by seanmc86** [comment] 2020-09-07 15:47
I can confirm that renaming the folders fixes the issue in VSCode. Android Studio debugging worked with hot reload prior to this.

**Comment by DanTup** [comment] 2020-09-07 16:23
> I can confirm that renaming the folders fixes the issue in VSCode

Aha - had you previously run in profile or debug mode? Perhaps something wasn't invalidated by changing the mode and was preventing it from running with hot reload support (I think that's not available in profile/release mode). If you can reproduce this, please file an issue at https://github.com/flutter/flutter/ with steps.

**Comment by seanmc86** [comment] 2020-09-08 07:13
> Aha - had you previously run in profile or debug mode?

Yes, though I'm not using a physical iPhone either - I'm running profile/release on an Android phone as well as debug on Android/iOS simulators.

I'll try to reproduce it. Thanks for the help!

**Comment by DanTup** [comment] 2020-09-08 12:37
Cool - I'll close this as I don't think there's anything wrong in Dart-Code here, but please do file an issue in Flutter if you can repro.

(FYI @jonahwilliams - it seems like running a debug build after profile/release might not sometimes result in tools VM services like `reloadSources` not being registered).

**Comment by seanmc86** [comment] 2020-09-17 07:39
This is happening again @DanTup, even after removing `build` and `.dart-tools` folders this time.

Logs: 
[Dart-Code-Log-2020-08-04 08-35-12.txt](https://github.com/Dart-Code/Dart-Code/files/5237111/Dart-Code-Log-2020-08-04.08-35-12.txt)

> $ flutter --version
> Flutter 1.22.0-10.0.pre.221 • channel master • ssh://git@github.com/flutter/flutter.git
> Framework • revision fa646339d6 (7 hours ago) • 2020-09-16 17:47:04 -0700
> Engine • revision 933f811d94
> Tools • Dart 2.10.0 (build 2.10.0-135.0.dev)

> $ git status
> On branch master
> Your branch is up to date with 'origin/master'.
> 
> nothing to commit, working tree clean

**Comment by DanTup** [comment] 2020-09-17 10:41
I can reproduce this today too. I think it may be related to some DDS changes being tested (https://github.com/dart-lang/sdk/commit/c3da025eaa2affb44c2912808ebdb105668d9aed). I think DDS has been enabled/disabled a few times recently, so this might also explain the original cause (though it doesn't entirely explain that `flutter clean` seemed to fix it).

Re-opening this until we know for sure what the cause is.

**Comment by DanTup** [comment] 2020-09-18 12:02
This has been fixed by https://github.com/dart-lang/sdk/commit/b5f688e938983f0a3a81413460d103b3c744d026 which has rolled into Flutter's master branch now. If you're still seeing this after updating to latest version and restarting VS Code, please let me know.

**Closed by DanTup** 2020-09-18 12:02 UTC
Labels: in flutter, is bug, upstream in dart / flutter

**Comment by callmejm** [comment] 2020-10-12 03:10
please help https://github.com/Dart-Code/Dart-Code/issues/2859 , I have issue for this, I currently using latest 1.50.0 still facing this issue

**Comment by tajultonim** [comment] 2024-03-20 17:51
Same problem

**Comment by DanTup** [comment] 2024-03-20 19:17
@tajultonim please file a new issue with full details. It's likely a different cause to this (unless you're on a very old version of Flutter) as this issue was solved a long time ago.

**Comment by tajultonim** [comment] 2024-03-21 13:27
Yeah it was solved when I restarted everything. I don't know why it happened but I'm not facing it anymore. Thanks for the reply tho.
