### ISSUE TITLE
Terminating test does not wait for current test to complete

### ISSUE THREAD

**Issue by BootBlock** [Dart-Code/Dart-Code#2538] opened 2020-06-09 16:46 UTC
```
[17:42:09] [PubTest] [Info] [Dart] <== {"test":{"id":3,"name":"description","suiteID":0,"groupIDs":[2],"metadata":{"skip":false,"skipReason":null},"line":4,"column":3,"url":"file:///P:/Source/GitHub/DartTest/test/debug_test.dart"},"type":"testStart","time":1470}
[17:42:12] [Observatory] [Info] [Dart] Termination requested!
[17:42:12] [Observatory] [Info] [Dart] TERM: Requested to terminate with SIGINT...
[17:42:12] [Observatory] [Info] [Dart] TERM: Terminating processes...
[17:42:12] [Observatory] [Info] [Dart] TERM: Terminating related process 9464 with SIGINT...
[17:42:12] [Observatory] [Info] [Dart] TERM: Terminating related process 9464 with SIGINT...
[17:42:12] [Observatory] [Info] [Dart] TERM: Terminating main process with SIGINT...
[17:42:12] [Observatory] [Info] [Dart] TERM: Disabling break-on-exception and removing all breakpoints
[17:42:12] [Observatory] [Info] [Dart] ==> {"id":"1782","jsonrpc":"2.0","method":"setExceptionPauseMode","params":{"isolateId":"isolates/2990214838472951","mode":"None"}}
[17:42:12] [Observatory] [Info] [Dart] ==> {"id":"1783","jsonrpc":"2.0","method":"setExceptionPauseMode","params":{"isolateId":"isolates/871716458231723","mode":"None"}}
[17:42:12] [Observatory] [Info] [Dart] ==> {"id":"1784","jsonrpc":"2.0","method":"setExceptionPauseMode","params":{"isolateId":"isolates/1591548709772999","mode":"None"}}
[17:42:12] [PubTest] [Info] [Dart] Process terminated! 1, null
[17:42:12] [Observatory] [Info] [Dart] Process exited (1)
[17:42:12] [Observatory] [Info] [Dart] Observatory connection closed: 1006 ()
[17:42:12] [Observatory] [Info] [Dart] TERM: Unpausing all threads...
[17:42:12] [Observatory] [Info] [Dart] TERM: Removing all stored data...
[17:42:12] [Observatory] [Info] [Dart] TERM: Waiting for process to finish...
[17:42:12] [Observatory] [Info] [Dart] TERM: Disconnecting...
[17:42:12] [Observatory] [Info] [Dart] Disconnect requested!
[17:42:12] [Observatory] [Info] [Dart] TERM: Requested to terminate with SIGINT...
[17:42:12] [Observatory] [Info] [Dart] TERM: Did not need to terminate processes
[17:42:12] [Observatory] [Info] [Dart] TERM: Removing all stored data...
[17:42:12] [Observatory] [Info] [Dart] TERM: Waiting for process to finish...
[17:42:12] [Observatory] [Info] [Dart] TERM: Disconnecting...
[17:42:12] [General] [Info] Debugger:SessionDuration timing: 6206ms (PubTest)
```

**Comment by DanTup** [comment] 2020-06-09 20:15
I *think* this doesn't work on Windows because the signal handling doesn't work.

However, by what might be a huge coincidence, it doesn't work for me either on macOS - but I think this is because of https://github.com/dart-lang/sdk/issues/42092.

**Comment by DanTup** [comment] 2020-07-07 09:30
This is now working for me in the latest nightly build (http://gsdview.appspot.com/dart-archive/channels/be/raw/latest/sdk/), so we should check this on Windows too.

**Comment by BootBlock** [comment] 2020-08-28 12:44
This still doesn't appear to work on Windows using the latest nightly build.

**Comment by DanTup** [comment] 2020-09-07 15:16
I can repro this, yet it works fine from the terminal. I've opened https://github.com/dart-lang/test/issues/1333 as I can reproduce in a Dart script without Dart-Code, so I don't think it's a bug here.

**Comment by DanTup** [comment] 2020-09-07 15:16
Closing as an upstream bug as I don't think there's anything to do here - though we can re-open if it turns out we need a workaround.

**Closed by DanTup** 2020-09-07 15:16 UTC
Labels: upstream in dart / flutter
