### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by AntonioAndradeGomes** [Dart-Code/Dart-Code#1706] opened 2019-05-14 16:14 UTC
- Issue Type: `Performance`
- Extension Name: `dart-code`
- Extension Version: `3.0.2`
- OS Version: `Windows_NT x64 10.0.17763`
- VSCode version: `1.33.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\gomes\Dart-Code.dart-code-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by DanTup** [comment] 2019-05-14 16:28
> ⚠️ Make sure to attach this file from your home-directory:

Are you able to attach the tile referenced in your issue?

I suspect this is a dupe of https://github.com/Dart-Code/Dart-Code/issues/1628 but it's hard to say without the CPU profile.

**Closed** 2019-06-11 13:39 UTC
Labels: awaiting info
