### ISSUE TITLE
Running web apps on Chrome OS doesn't work (due to hostname mismatch penguin.linux.test?)

### ISSUE THREAD

**Issue by Skylled** [Dart-Code/Dart-Code#2229] opened 2020-01-23 02:54 UTC
I'm getting started with my first proper Flutter Web project, developing from my Chromebook, and I saw the handy setting "Use Known Chrome OS Ports." However, the setting doesn't seem to automatically apply that same port range to the Flutter Web launch config.

I've configured my launch.json to match the one shown in #1769, but I figured I'd raise the suggestion that if Dart Code can already detect that I'm on Chrome OS and adjust DevTools and Observatory accordingly, automatically applying that to Flutter Web's launch config could be valuable.

**Comment by DanTup** [comment] 2020-01-23 16:03
Unfortunately I no longer have access to a Pixelbook to test this, but IIRC when I original added this it was not required for the web app as the Chrome OS browser would automatically redirect the incoming request to localhost over to a hostname that was mapped to the container (pengiun?).

When happens if you don't set the port and launch the app? What do you see in the web browser opens?

FWIW, this setting will be removed soon - Chrome OS will automatically expose ports from the container (done in https://bugs.chromium.org/p/chromium/issues/detail?id=848063, though I'm not sure when it will hit stable).

**Comment by DanTup** [comment] 2020-01-23 16:05
Oh, based on https://chromereleases.googleblog.com/2020/01/stable-channel-update-for-chrome-os_22.html it seems like 79 is already stable and that issue is tagged 79. So in theory none of the special port use should be required? 🤷‍♂️

**Comment by Skylled** [comment] 2020-01-23 16:25
I'm on 79 Stable and am not seeing that behavior, but I'll double check on my device running 81 Canary later today.

**Comment by DanTup** [comment] 2020-01-23 16:34
Cool, do let me know. I'll try and figure out if there's an easy way I can get a compatible device here to test again too.

**Comment by Skylled** [comment] 2020-01-25 20:03
Looks like you were correct and that the behavior is indeed live in Chrome OS 79. The issue actually seems to be that a browser tab is being opened to the url `penguin.linux.test:40071` instead of `localhost:40071`, but I don't believe that behavior is handled by Dart Code in any way.

Closing.

**Comment by DanTup** [comment] 2020-01-25 20:35
> The issue actually seems to be that a browser tab is being opened to the url `penguin.linux.test:40071` instead of `localhost:40071`

Yeah, that's what I was seeing - however I don't think it caused any issues (I'm sure everything worked end-to-end). Is this causing issues for you?

If the web server doesn't respond to that hostname, it might be fixed by https://github.com/dart-lang/webdev/pull/858 (I still have a little work to get all of these changes through to Flutter though). I'm not sure why I didn't hit that before though. I'll be bringing [my branch](https://github.com/DanTup/flutter/tree/custom-dwds) up to date next week so you could test it out with that to see if that fixes everything (it's a bit out of date atm).

Seems like the Chromebook I have here won't run Linux so I can't easily test - but I would like this to work. If you're happy to test things, I'm happy to try and make fixes where I can.

**Comment by DanTup** [comment] 2020-01-25 20:36
If it is the hostname, you might also be able to test with `["--web-host", "penguin.linux.test"]` in the `args` of a `launch.json` that would tell Flutter to bind to that hostname.

**Comment by Skylled** [comment] 2020-01-25 20:42
Setting the `--web-host` as you suggested results in the following, seemingly regardless of the ports I've tried.
`SocketException: Failed to create server socket (OS Error: Cannot assign requested address, errno = 99), address = penguin.linux.test, port = 8008`

The solution I've landed on is to set the host to `127.0.0.1`. I'm guessing that something on the Crostini side (as opposed to anything in Dart/Flutter/DC control) is translating an intent to open a linux web link on `localhost` into `penguin.linux.test`.

Will keep an eye out for that next update to see if/how behavior changes.

**Comment by DanTup** [comment] 2020-01-27 15:51
> is translating an intent to open a linux web link on `localhost` into `penguin.linux.test`.

Yep, that's my understanding too. It meant if a process in the container tried to open something local in a browser using `localhost` it would get mapped over to the containers hostname. I think it may be superfluous now though.

Another temp fix is probably to use `--web-port` with a port that's exposed by default (which is excluded from the mapping - per https://crbug.com/890506).

I'll re-open this as a reminder that this is broken and let you know when I merge the other changes for you to test. Thanks!

**Comment by DanTup** [comment] 2020-05-07 13:40
@Skylled using latest Flutter master, do you still see issues here? If so, does adding `"--web-hostname`", "any"` to your launch args fix it?

**Comment by Skylled** [comment] 2020-05-12 17:44
Current setup:
```
[✓] Flutter (Channel master, 1.19.0-1.0.pre.49, on Linux, locale en_US.UTF-8)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Chrome - develop for the web
[!] Android Studio (version 3.5)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.44.0)
[✓] Connected device (3 available)
```

Chrome OS Version 84.0.4136.1 (Official Build) dev (64-bit)
I haven't upgraded to Buster yet, if that matters.

Ran Flutter with "Web Server" as selected device and no "launch.json" file in the project. This opened a tab in Chrome for `http://penguin.linux.test:39125/` to which Chrome says "penguin.linux.test refused to connect."

Ran again with a launch.json with the args you mentioned. This time things actually connect to the host, but a different, unrelated issue occurs. Despite the page "loading" (the HTML portion loads successfully), the Flutter code never runs. In the bottom right, "Syncing files to device Web Server" stays on screen permanently, and the debug console output merely shows the following:

```
Launching lib/main.dart on Web Server in debug mode...
Waiting for connection from Dart debug extension at http://localhost:42045
```

Here's the output from also running with `-v`: https://pastebin.com/GpTK3E1U

This probably needs to be opened as a separate issue, though.

**Comment by DanTup** [comment] 2020-05-13 09:13
> Chrome OS Version 84.0.4136.1 (Official Build) dev (64-bit)
> I haven't upgraded to Buster yet, if that matters.

I'm not sure tbh. I'm not very familiar with the Chrome OS stuff.

> Ran again with a launch.json with the args you mentioned. This time things actually connect to the host, but a different, unrelated issue occurs

It looks like here it ran on the "Web Server" device, which is slightly different and requires use of the [Dart Debug extension](https://chrome.google.com/webstore/detail/dart-debug-extension/eljbmlghnomdjgdjmbdekegdkbabckhm). Does Chrome show up in the device selector? If so, try that. If not, I think that's a bug in Flutter we should fix.

That said, I wonder if it's worth filing a bug about the hostname being rewritten. With https://bugs.chromium.org/p/chromium/issues/detail?id=848063, it seems like all ports are now exposed, and therefore https://bugs.chromium.org/p/chromium/issues/detail?id=890506 should probably be extended to cover them all (eg. don't map any)? (It looks the author of that change is @Narflex - perhaps he has an opinion on whether that makes sense?).

**Comment by Skylled** [comment] 2020-05-13 14:29
Chrome does appear, but only because I manually installed the Linux version of Chrome in the Linux VM.

I'll try the Dart Debug Extension today. This is the first I'm hearing of it.

**Comment by DanTup** [comment] 2020-05-13 14:41
> Chrome does appear, but only because I manually installed the Linux version of Chrome in the Linux VM

Yeah, that's required to run without the debug extension (and was the only way [when first available](https://dartcode.org/docs/chrome-os-setup/#web)). I think Chrome used to be selected first, but it's not now (I've opened https://github.com/Dart-Code/Dart-Code/issues/2453).

The reason for needing Linux Chrome or the Dart Debug extension is that we need to connect to the Chrome debugger in order to control it. By launching Chrome ourselves (which we can do with the Linux version of Chrome but not the Chrome OS one) we can use pass switches to expose the debug protocol. Otherwise, using the Dart Debug extension allows us to proxy the debugger requests over a connection to the extension (and it drives the debugger directly).

Either way should roughly work the same. On a non-ChromeOS device, using Chrome is probably nicer. When remoting (container, WSL, Docker, VS Codespaces, GitPod etc.) there's no option to launch Chrome so it needs to be done using the extension. For ChromeOS you could use either - it's a toss-up between the slightly-weird-looking Linux Chrome, or the slightly worse UX of the Dart Debug extension (getting a white page and having to click the button).

**Comment by maks** [comment] 2020-10-07 04:46
Just wanted to chime in to say that I'm walking down this path now too.
What I've found is that if you are on ChromeOS M85 [there is a bug](https://bugs.chromium.org/p/chromium/issues/detail?id=1081354) with doing `xdg-open http://localhost:port` being translated into `penguin.linux.test` which does not work with Flutter web, so you need to manually enter your flutter web apps `localhost:port` into a host ChromeOS browser tab.

Debugging my app with this launch conf seems to work:

```
 {
            "name": "Debug App (dev)",
            "program": "lib/main_dev.dart",
            "request": "launch",
            "type": "dart",
            "args": [
                "--dart-define=FLUTTER_WEB_USE_SKIA=true",
                "--web-port",
                "8081"
            ]
        },
```

though in VSC debug console I do see:

```
Launching lib/main_dev.dart on Web Server in debug mode...
Waiting for connection from Dart debug extension at http://localhost:8081
```

not sure if thats expected behaviour?
My app is crashing at the moment (due to other issues) so I haven't been able to test yet if the debugger in VSC is actualyl connecting and will let me set breakpoints etc.

**Comment by DanTup** [comment] 2020-10-07 10:29
@maks there are two ways to run web apps:

1. Using the Chrome device (this requires you install the Linux version of Chrome in the container)
2. Using the Web-Server device and the [Dart Debug extension](https://chrome.google.com/webstore/detail/dart-debug-extension/eljbmlghnomdjgdjmbdekegdkbabckhm) (when the white page opens and you see the message you included above, you must click the Dart Debug extensions button to connect the debugger).

I believe both of them should work on ChromeOS (at least with the bug you linked above fixed). If you have issues with them, please let me know.

Otherwise I think this issue may be solved as of M86 with the fix linked above?

**Comment by maks** [comment] 2020-10-07 23:02
legend @DanTup !!
> Using the Web-Server device and the Dart Debug extension (when the white page opens and you see the message you included above, you must click the Dart Debug extensions button to connect the debugger).

That was the important bit I had completely missed! Did not at all realise that I needed to click on the debug extension icon once the webpage loaded with blank page. Looking back on the video for the extension on its Chrome webstore listing I do see that it shows clicking the icon, but that is so easy to miss I think it really deserves a call out, maybe in the DartCode  docs or faq under the ChromeOS section? I can do a PR for that on the weekend if you think its a good idea @DanTup ?

I can confirm it works like a charm now! Using the ChromeOS browser with Dart Debug Extension installed and following ☝️  I can set and hit breakpoints and see output in VSC Debug console, so yes I think this issue can be closed now or maybe closed once M86 reaches stable channel and I can confirm that the fix for the localhost-penguintest url mapping is fixed too.

**Comment by DanTup** [comment] 2020-10-08 07:00
Great, glad it works!

The best fix is for the white page to include a message (there's an issue open at https://github.com/flutter/flutter/issues/48803). A close alternative would be to add additional text to the "Waiting for" message. There's supposed to be a progress message (see https://github.com/Dart-Code/Dart-Code/blob/75a9a6c382326ef9ceb3f6a1413dee27d124242b/src/debug/flutter_debug_impl.ts#L175-L179), but I haven't seen that lately so I think it may be broken. I'll take a look, and try to fix + tag some additional text onto there.

> I think this issue can be closed now or maybe closed once M86 reaches stable channel and I can confirm that the fix for the localhost-penguintest url mapping is fixed too.

Ah, I thought that had already been released. Happy to keep this open until it's stable and confirmed.

**Comment by DanTup** [comment] 2020-10-08 09:54
Since it doesn't seem like the DAP protocol will be updated soon, I've fixed #2597 and tweaked the text slightly, so now you'll see this:

![Screenshot 2020-10-08 at 10 52 00](https://user-images.githubusercontent.com/1078012/95443472-851b6500-0954-11eb-9229-d99d28e50637.png)

Please let me know if you're able to confirm the other issue described above is fixed when M86 is released, and I'll close this. Thanks!

**Comment by maks** [comment] 2020-10-08 10:58
Brilliant thanks @DanTup ! I think that makes the developer experience much better and directly tells the developer what they need to do. I actually remembered I have a second Chromebook that is on beta channel running M86, so I'll get my VSC and flutter web dev environment updated on there and confirm the hostname fix shortly.

**Comment by maks** [comment] 2020-10-08 11:25
@DanTup I just checked this on a Pixelbook running M86 and can confirm that the mapping issue is also fixed, using `xdg-open http://localhost:8765` for example opens that in the host ChromeOS browser as is without the mapping to penguin.linux.test and the port is made automatically available to the host browser without needing any mapping, so should be fine to close this issue now.

**Comment by DanTup** [comment] 2020-10-08 12:12
Excellent - thanks for your help!

**Closed by DanTup** 2020-10-08 12:12 UTC
Labels: awaiting info, on chromeos, upstream in other
