### ISSUE TITLE
Exclude in analysis_options.yaml does not stop Dartcode showing errors

### ISSUE THREAD

**Issue by maks** [Dart-Code/Dart-Code#2569] opened 2020-06-18 07:24 UTC
If I have a file with analyzer errors and I have in my analysis_options.yaml an exclude for the offending file, eg.
```
exclude:
    - lib//*.g.dart
    - lib//*.freezed.dart
```
when I open that file in VSCode, Dartcode shows errors for it in Problems tab (see screenshot below), while running "flutter analyze" does not show any issues.

![Screenshot 2020-06-18 at 16 49 42](https://user-images.githubusercontent.com/71999/84989915-be527e00-b187-11ea-9805-fa673a9434dc.png)

An added wrinkle which maybe is a separate bug in the (new?) analyzer is that the reason I have the `exclude:` in the first place is that without it BOTH Dartcode and `flutter analyze` command do not seem to be respecting the ignore comment in the generated file for that error, eg. in the screenshot you can see that it has: `// ignore_for_file: implicit_dynamic_parameter` 

Dartcode version is: 3.11.0
```
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 1.20.0-1.0.pre.91, on Linux, locale en_US.UTF-8)
```

**Comment by maks** [comment] 2020-06-18 07:50
Ok well at least I've found out [the reason for the `ignore` comment not being enough to stop the analyzer complaining ](https://github.com/dart-lang/sdk/issues/42373) but the main issue around the exclude not affecting Dartcode remains.

**Comment by DanTup** [comment] 2020-06-22 13:21
The analysis_options issue appears to be https://github.com/dart-lang/sdk/issues/36064. The issue is that although the file is ignored during initial analysis, once you open the file it becomes analyzed (which is reasonable, I think). However when you close the file, the errors are not removed.

I'll close this as a dupe of that one. Thanks!

**Closed by DanTup** 2020-06-22 13:21 UTC
