### ISSUE TITLE
[Feature Request]: Ignore exception and continue

### ISSUE THREAD

**Issue by JCKodel** [Dart-Code/Dart-Code#2670] opened 2020-07-24 19:37 UTC
When breakpoints is configurated to [X] All Exceptions and [X] Uncaught Exceptions, the continue button is kinda annoying, because often exceptions are stacked one after another (so we must hit continue button several times or temporarly disable both breakpoint options just to get the app running again, then reselect the breakpoints options again).

It would be nice if when the debugger is paused on an exception, there is a button such as ignore and continue (this will ignore all exceptions for about 1 second).

Or...

Some option to show exceptions in VSCode error notifications (no matter if exception breakpoints are on or off). Clicking on such notifications shows the details (message + stack trace).

One of the most annoying side effects of "paused in exception" is that if we save something, most of the times we're forced to stop and rebuild from scratch, because hot reload will often break in this state.

The idea here is to be able to see exceptions without pausing on them.

**Comment by DanTup** [comment] 2020-07-27 10:18
I think this request may be similar to #2388. There was [a suggestion](https://github.com/Dart-Code/Dart-Code/issues/2388#issuecomment-625671024) of not breaking on the same exception each time it is rethrown.

> a button such as ignore and continue (this will ignore all exceptions for about 1 second).

I'm not a fan of something like this that is time-based, and the time will no doubt be "wrong" for some cases (or be impacted by the speed of the code/your computer/etc.).

> Some option to show exceptions in VSCode error notifications (no matter if exception breakpoints are on or off). Clicking on such notifications shows the details (message + stack trace).

It might be hard to show a reasonable stack after the fact, but logging them might be possible. However this sounds a lot like what should happen with Flutter anyway - the framework catches the exceptions and logs them, but doesn't pause (if you don't have pause-on-all-exceptions ticked).

Generally, I think the best experience is to *not* tick "Pause on caught exceptions" and to only pause on uncaught exceptions (though I know the VM's detection of this isn't perfect). Would this not work more like you're requesting without any changes?

**Comment by JCKodel** [comment] 2020-07-27 16:12
> It might be hard to show a reasonable stack after the fact...
Not needed, since the exception itself is logged in the debug window.
The idea here is just not pause on exceptions but be visually alerted that something did happen (then, I would manually go to debug window and scroll to the exception, it's pretty detailed there).

> Generally, I think the best experience is to _not_ tick "Pause on caught exceptions" and to only pause on uncaught exceptions (though I know the VM's detection of this isn't perfect). Would this not work more like you're requesting without any changes?
In the past that worked like a must. Nowadays caught exceptions are thrown most of the time, specially in isolates.

**Comment by JCKodel** [comment] 2020-07-28 23:58
Here's one annoying example:

```dart
 Future<void> _reloadInterstitialAd() async {
    try {
      await _interstitialAd.load();
    } on PlatformException catch (e) {
      print("### INTERSTITIALAD ###: NOT_LOADED: ${e.message}");

      if (e.code == "load_failed_ad") {
        _interstitialAd.dispose().then((_) {
          _interstitialAd = null;
          _initializeInterstitial();
        }).catchError((e) => print("### INTERSTITIALAD ###: NOT_LOADED: ${e}"));
      }
    } catch (_) {
      print("### INTERSTITIALAD ###: NOT_LOADED: ${_}");
    }
  }
```

My debugger config:

![image](https://user-images.githubusercontent.com/379339/88740858-8dfde800-d114-11ea-8f28-0bcebb1d3528.png)

The `_interstitialAd.dispose()` triggers a break (no matter if I use `await _interstitialAd.dispose()` or `_interstitialAd.catchError`. VSCode always break in this line. And this exception occurs once every 3 or 5 seconds (because I'm testing with a new AdMob that doesn't load ads yet).

The error is:
```
E/flutter (24887): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: 'package:firebase_admob/firebase_admob.dart': Failed assertion: line 249 pos 12: '_allAds[id] != null': is not true.
[38;5;244mE/flutter (24887): #0      _AssertionError._doThrowNew  (dart:core-patch/errors_patch.dart:40:39)[39;49m
[38;5;244mE/flutter (24887): #1      _AssertionError._throwNew  (dart:core-patch/errors_patch.dart:36:5)[39;49m
[38;5;248mE/flutter (24887): #2      MobileAd.dispose[39;49m
[38;5;248mE/flutter (24887): #3      _BusinessModelStoreBase._reloadInterstitialAd[39;49m
E/flutter (24887): <asynchronous suspension>
[38;5;248mE/flutter (24887): #4      _BusinessModelStoreBase._reloadAds[39;49m
[38;5;244mE/flutter (24887): #5      _AsyncAwaitCompleter.start  (dart:async-patch/async_patch.dart:43:6)[39;49m
[38;5;248mE/flutter (24887): #6      _BusinessModelStoreBase._reloadAds[39;49m
[38;5;248mE/flutter (24887): #7      _BusinessModelStoreBase._initializeInterstitial.<anonymous closure>[39;49m
[38;5;244mE/flutter (24887): #8      _asyncThenWrapperHelper.<anonymous closure>  (dart:async-patch/async_patch.dart:71:64)[39;49m
[38;5;244mE/flutter (24887): #9      _rootRunUnary  (dart:async/zone.dart:1132:38)[39;49m
[38;5;244mE/flutter (24887): #10     _CustomZone.runUnary  (dart:async/zone.dart:1029:19)[39;49m
[38;5;244mE/flutter (24887): #11     _FutureListener.handleValue  (dart:async/future_impl.dart:137:18)[39;49m
[38;5;244mE/flutter (24887): #12     Future._propagateToListeners.handleValueCallback  (dart:async/future_impl.dart:678:45)[39;49m
[38;5;244mE/flutter (24887): #13     Future._propagateToListeners  (dart:async/future_impl.dart:707:32)[39;49m
[38;5;244mE/flutter (24887): #14     Future._complete  (dart:async/future_impl.dart:512:7)[39;49m
[38;5;244mE/flutter (24887): #15     new Future.delayed.<anonymous closure>  (dart:async/future.dart:313:16)[39;49m
[38;5;244mE/flutter (24887): #16     _rootRun  (dart:async/zone.dart:1120:38)[39;49m
[38;5;244mE/flutter (24887): #17     _CustomZone.run  (dart:async/zone.dart:1021:19)[39;49m
[38;5;244mE/flutter (24887): #18     _CustomZone.runGuarded  (dart:async/zone.dart:923:7)[39;49m
[38;5;244mE/flutter (24887): #19     _CustomZone.bindCallbackGuarded.<anonymous closure>  (dart:async/zone.dart:963:23)[39;49m
[38;5;244mE/flutter (24887): #20     _rootRun  (dart:async/zone.dart:1124:13)[39;49m
[38;5;244mE/flutter (24887): #21     _CustomZone.run  (dart:async/zone.dart:1021:19)[39;49m
[38;5;244mE/flutter (24887): #22     _CustomZone.bindCallback.<anonymous closure>  (dart:async/zone.dart:947:23)[39;49m
[38;5;244mE/flutter (24887): #23     Timer._createTimer.<anonymous closure>  (dart:async-patch/timer_patch.dart:21:15)[39;49m
[38;5;244mE/flutter (24887): #24     _Timer._runTimers  (dart:isolate-patch/timer_impl.dart:382:19)[39;49m
[38;5;244mE/flutter (24887): #25     _Timer._handleMessage  (dart:isolate-patch/timer_impl.dart:416:5)[39;49m
[38;5;244mE/flutter (24887): #26     _RawReceivePortImpl._handleMessage  (dart:isolate-patch/isolate_patch.dart:172:12)[39;49m
E/flutter (24887):
I/Ads     (24887): This request is sent from a test device.
```

Now I'm trying to fix another bug and I can't use the debugger because it is annoying stopping in caught exceptions >.<

**Comment by DanTup** [comment] 2020-07-29 08:58
Thanks for the info. I  think the main issue here is that the VM's "pause on uncaught exceptions" is sometimes unreliable.

Out of interest, if you untick that open too, what behaviour do you see? Are uncaught exceptions not written to the output by default already?

**Comment by DanTup** [comment] 2020-07-29 09:09
I tried this out in a Flutter app, throwing an exception from an async method (that wasn't awaited), and the exception did show up in the debug console:

<img width="785" alt="Screenshot 2020-07-29 at 10 08 11" src="https://user-images.githubusercontent.com/1078012/88780826-727df600-d183-11ea-9cf1-9b1a2750ea8a.png">

So I think this might do what you're requesting, unless you have examples of where the exceptions are not logged.

I think the main issue though is really that pausing on "Uncaught exceptions" is not completely reliable in the VM (and may break multiple times for the same exception), which there are open issues about.

**Comment by JCKodel** [comment] 2020-07-29 18:58
Yes, the exception is displayed on the Debug Console. The problem with debug console is that MS refuses to implement a filter on this window (notice: filter, not search!). When you have admob banners on the screen, this window receives a LOT of spam messages each second, so it is pretty much useless.

That's why I'm asking for a notification =) A simple error notification with the exception message would be awesome. Would be better if clicking this notification would open the Debug Console and scrolling it to the log you show above. Would be a lot better if clicking this notification would open the exception where it happened, with this kind of popup:

![image](https://user-images.githubusercontent.com/379339/88841229-05368900-d1b4-11ea-93ee-096111a2c834.png)

Everything is just because Debug Console is useless due to log spam from different sources. As MS seems relutant to implement a regex filter (as Android Studio has), there is no other option.

If DartCode could create a new "Dart Console" panel, with filter, showing only Dart output on it, filterable by Info/Warning/Error, that would be also awesome!

**Comment by DanTup** [comment] 2020-08-03 13:54
> If DartCode could create a new "Dart Console" panel, with filter, showing only Dart output on it, filterable by Info/Warning/Error, that would be also awesome!

We can add Output panels, but we aren't able to add filters to the UI to easily switch between them. There is a Logging page in DevTools that might help, but I'm not completely familiar with it's functionality.

Are you able to give a specific example of an error that is annoying to debug without these (and what I need to do to set admob or something spammy up)? If I can reproduce the exact setup, it might be easier for me to come up with ideas to improve things. Thanks!

**Comment by JCKodel** [comment] 2020-08-03 21:51
Dio (http) exceptions requires multiple "continue".

For AdMob, just follow the instructions of https://pub.dev/packages/firebase_admob and add a banner at the bottom of the app (for real devices, you must use a test device id, it will appear on the logs - for emulator, they're always test).

**Comment by DanTup** [comment] 2020-08-04 11:15
I wasn't able to get the ads working, though that's probably the least important part. I reproduced an error by doing this:

```dart
@override
void initState() async {
  super.initState();

  try {
    final response = await Dio().get("http://example.org/not-a-real-page");
    print(response);
  } catch (e) {
    print(e);
  }
}
```

However this only breaks once, and only requires a single continue (it doesn't jump to any code when it does, so I've opened https://github.com/Dart-Code/Dart-Code/issues/2699 to improve that). I think the reason it's breaking at all, is because [dio is using `.catchError()`](https://github.com/flutterchina/dio/blob/f1485e6ff77a77fefd1f1ed99df409d628e2e4d7/dio/lib/src/dio.dart#L883-L910) which means there's no `catch` block in the stack when the exception is thrown (which is unfortunately a known limitation).

I think if dio was changed to use await/try/catch that might fix this issue, as the exceptions would have proper stacks (which would cause the debugger to break in the correct location when in "debug just my code", and hopefully allow the VM to see the exception is caught).

I think changing the debugger behaviour here might be tricky. I'm leaning towards the real issue being the spammy output, and it would be better if that can be fixed (there's an open issue at https://github.com/flutter/flutter/issues/42849 about fixing this at source, though I don't know what's involved).

**Comment by JCKodel** [comment] 2020-08-04 23:26
There are some odd behaviors as well. For example: if I set VSCode to catch only uncaught exceptions, try to login with Google SignIn, but cancel the Google Account dialog, the debugger breaks nowhere (it just pauses), no exception is logged in the output dialog.

That's the code:
```dart
 try {
      account = await google.signIn();

      if (account == null) {
        Logger.failure("Google Sign In: User aborted");
        setState(() => _isBusy = false);
        return;
      }
...
    } on PlatformException catch (e) {
      Logger.exception("Google SignIn", e);
      setState(() => _isBusy = false);
      return _showErrorMessage(e, account.email, "G");
    }
```

Basically:
[X] All Exceptions
[X] Uncaught Exceptions
This pauses VSCode 3 times and there is absolutelly nothing in the log, except my WARNING (that means: the catch didn't run, the execution just continued).

With
[ ] All Exceptions
[X] Uncaught Exceptions

VSCode pauses with this exception:
![image](https://user-images.githubusercontent.com/379339/89354970-91ebb600-d690-11ea-860b-4ff2c6bcdae3.png)
Again, I have to hit continue 3 times and the catch IS NOT executed.

To check out this behavior, use firebase_auth with google_sign_in, initiate a Google Sign In, but cancel the Google dialog (by hitting back).

**Comment by JCKodel** [comment] 2020-08-05 00:19
This is the kind of spam I'm talking about (this app has a banner in its footer, but I can't turn this banner on in development mode because this kind of spam would be 100% of the time).

https://youtu.be/zR_Qa8uyZEE or https://vimeo.com/user120832289/review/444725169/ddd8d8501c

(it may take some time for them to process the video. Notice the output window while the ad is running (sometimes it seems frozen, but it is not... it's just scrolling really fast with the same log).

Google won't do a thing to solve it (by removing the spammy log from Google AdMob).
Microsoft won't do a thing to solve it (they refuse to implement a decent output window).
You must not do a thing, because it is not your fault =)

**Comment by DanTup** [comment] 2020-08-05 10:59
> There are some odd behaviors as well. For example: if I set VSCode to catch only uncaught exceptions, try to login with Google SignIn, but cancel the Google Account dialog, the debugger breaks nowhere (it just pauses), no exception is logged in the output dialog.

I think that's #2699. If you look at the call stack on the left, it probably shows "Paused on exception" but because there's none of your code in the stack (and you're set to debug-just-my-code) it doesn't know where to jump to. We need to fix that somehow (probably focussing the top frame when there is no user code in the stack).

> Basically:
> [X] All Exceptions
> [X] Uncaught Exceptions
> This pauses VSCode 3 times and there is absolutelly nothing in the log, except my WARNING (that means: the catch didn't run, the execution just continued).

When you break on "all exceptions", it's normal for the debugger to break on exceptions that are handled (and therefore no logs, or your catch block runs). Generally I wouldn't recommend ticking that option unless you're specifically trying to debug something where an error may be occurring but being caught in SDK/package code.

> With
> [ ] All Exceptions
> [X] Uncaught Exceptions
> 
> VSCode pauses with this exception:

I think there's something weird going on with this specific instance - there are open issues at https://github.com/flutter/flutter/issues/44431/https://github.com/dart-lang/sdk/issues/37953. It might be that they're using `catchError()` that can cause the debugger to break on caught exceptions, as the VM can't tell from the stack that the error is caught. That's a nasty edge case I don't think there's a good fix for (besides avoiding `catchError()` and using `try`/`await`/`catch` - though in this case that's something that'd need doing in the plugin).


> And, by the way, I do understand that this involves behavior from Dart, Flutter and VSCode. That's why I'm asking for tools, not fixes, to help us. At the end of the day, we just want to have tools that makes our lifes easier (they don't need to be perfect, VSCode is far from it, but we accept it).

I completely understand this - but, building features to work around issues isn't as good as trying to solve those issues (especially if users need to know/understand the workarounds).

For the dio case - I think that switching to try/catch/finally might resolve a lot of the issues - the VM should not break if there's a `catch` block in the stack. Fixing it there might eliminate this problem entirely for a lot of people, and without any workaround.

> Google won't do a thing to solve it (by removing the spammy log from Google AdMob).
> Microsoft won't do a thing to solve it (they refuse to implement a decent output window).
> You must not do a thing, because it is not your fault =)

I'm not against doing things to make this better - but my preference is always to fix underlying issues before resorting to workarounds or hacks. I think if https://github.com/flutter/flutter/issues/42849 could be addressed and also more code used `catch` instead of `.catchError()` a lot of this frustration would go away.

I'll see if I can find someone to discuss both of those with, and if it seems like either won't be fixed anytime soon, we can evaluate the possible workarounds (for example I'd much rather implement some filter to hide "known spam" from the debug console that could be toggled on/off, than to mess around trying to do clever things when the debugger breaks).

(If I don't post back within a week, feel free to ping here!)

**Comment by DanTup** [comment] 2020-08-05 16:29
#2701 is similar to this, and proposes something like Node's `skipFiles`. I don't think that's a bad idea if we can't come up with something better, though I think maybe it could just be automatic based on the debug settings (eg. skip packages and SDK based on the debug-my-code setting).

**Comment by JCKodel** [comment] 2020-08-06 09:46
Another annoyance: sometimes, when an exception is thrown, VSCode pauses on the offending line, then continue will show the same exception, but upper in the stack trace (last time it did navigate 3 files, showing the same exception in different stack trace positions: original caller -> some method -> exception).

This is annoying because you can't change the source code while the debug is paused (I mean: you can, but if you do, it's almost certain that hot reload will stop working and you will have to stop and recompile from the start).

**Comment by DanTup** [comment] 2020-08-06 10:13
@JCKodel I think that might be what's described in https://github.com/Dart-Code/Dart-Code/issues/2388, where the debugger seems to pause multiple times for the same exception on each `await`?

**Comment by JCKodel** [comment] 2020-08-06 10:22
> @JCKodel I think that might be what's described in #2388, where the debugger seems to pause multiple times for the same exception on each `await`?

I think it is.

**Comment by DanTup** [comment] 2020-10-13 09:29
There's been a lot of discussion in this issue and it's not really clear to me now what this issue is representing. The initial request of ignoring exceptions for some period of time I don't think is a good option (that period of time would be arbitrary and likely be the "wrong" value for some.. for example 1 second might not be long if you have conditional breakpoints in the code that's running that could significantly slow it down).

I think some of the points are addressed above, and I think one of the most frustrating issues is that exceptions that we would consider "caught" and not detected as such by the VM (there's an open issue about this at https://github.com/dart-lang/sdk/issues/37953). I think that is better addressed in the SDK with some discussion there (since the issue affects Android Studio too, and it should be solved in a way that works for all).

I suggest we close this issue and open more specific issues for any issues that are not already covered?

**Closed** 2020-11-09 12:29 UTC
Labels: awaiting info, in debugger, is enhancement
