### ISSUE TITLE
QuickFix is stuttering

### ISSUE THREAD

**Issue by JCKodel** [Dart-Code/Dart-Code#2544] opened 2020-06-10 23:01 UTC
I'm implementing a class that must override two methods:

```dart
class _IconWheelCustomPainter extends CustomPainter {}
```

With the cursor over _IconWheelCustomPainter, I choose the option "Create 2 missing override(s)":
![image](https://user-images.githubusercontent.com/379339/84327133-fdb01780-ab54-11ea-89ce-d141371d41ce.png)

That's the current result:
![image](https://user-images.githubusercontent.com/379339/84327174-11f41480-ab55-11ea-803f-33127bf582a8.png)

Generated code:
```dart
class _IconWheelCustomPainter extends CustomPainter {
  @override
  void paint(Canvas canva canva canvas, Si Si Size size) {
      // TODO: implement paint
    }
  
    @override
    bool shouldRepa(Canvas canvan canvas, Sigate) {
    // TODO: implement shouldRepaint
    throw UnimplementedError();
  }
}
```

That's what should be generated:

```dart
class _IconWheelCustomPainter extends CustomPainter {
  @override
  void paint(Canvas canvas, Size size) {
    // TODO: implement paint
  }

  @override
  bool shouldRepaint(covariant CustomPainter oldDelegate) {
    // TODO: implement shouldRepaint
    throw UnimplementedError();
  }
}
```

**Comment by DanTup** [comment] 2020-06-11 10:30
Thanks for the report! This is an issue in the analysis server and there's an open issue at https://github.com/dart-lang/sdk/issues/41147 so I'll close this as a dupe of that.

**Closed by DanTup** 2020-06-11 10:30 UTC
