### ISSUE TITLE
Debug console shows less progress status than command line

### ISSUE THREAD

**Issue by xster** [Dart-Code/Dart-Code#572] opened 2018-02-15 02:18 UTC
Connect an iOS device, F5. There's less progress output printed than doing `flutter run` from the command line.

**Comment by DanTup** [comment] 2018-02-15 11:51
Ok, so I ran `flutter run` from the command line for an iOS device and only got this:

```text
Dannys-MacBook:hello_world danny$ flutter run
Launching lib/main.dart on iPhone X in debug mode...
Running Xcode build...                               16.2s
Syncing files to device iPhone X...                   1.5s

🔥  To hot reload your app on the fly, press "r". To restart the app entirely, press "R".
An Observatory debugger and profiler on iPhone X is available at: http://127.0.0.1:8100/
For a more detailed help message, press "h". To quit, press "q".

Application finished.
Dannys-MacBook:hello_world danny$ 
```

When I run from VS Code, I only see:

```text
Launching lib/main.dart on iPhone X in debug mode...
```

However, the text appears on the status bar as it runs. We get two types of text back from `flutter run --machine`, there's normal output (which we route to the debug window) and then "progress" which we show in the status bar. I believe it was designed to work this way to reduce the spam in the output window in editors.

@devoncarew can you clarify? Should more of this stuff be going to the console?

**Comment by devoncarew** [comment] 2018-02-15 14:57
This is intended behavior. IDEs have a better place to show progress then CLI tools do, so we try and map to their indeterminate progress mechanisms. And, the instructions printed when an app finishes starting up and more appropriate for the cli tool.

You could experiment with printing the status text when an indeterminate job starts, to see how that looks. It wouldn't include the cli spinner, but would still use the IDE UI for displaying progress.

**Comment by DanTup** [comment] 2018-02-15 15:27
Personally I think it's better as-is, especially when #571 is complete (we now show a spinner in status bar for many actions; though the debugging one is currently blocked on a Code bug). @xster if I can get a workaround in for that early next week I'll push an updated beta for you to try and you can see how it feels with the status bar more animated?

**Comment by xster** [comment] 2018-02-15 22:48
Sure. Will do. Since the build is getting longer and longer on larger projects, I'm trying to show more signals to the user https://github.com/flutter/flutter/pull/14715 so we don't end up with big 20s blocks where the user can't figure out what's going on.

**Comment by DanTup** [comment] 2018-02-21 15:29
@xster Just tidying up issues... Do you think it's reasonable to call this a dupe of #593 and/or if any changes are needed to what comes to the console we should open an issue in flutter? Besides the spinner (#593) I don't thin it's something to fix in Dart Code?

**Comment by DanTup** [comment] 2018-03-05 17:33
@xster Ping! Lmk if you think there's still more to do on the Dart Code side for this.

**Comment by xster** [comment] 2018-03-06 22:12
Just to confirm, we're talking about this prompt right? 

![screen shot 2018-03-06 at 2 11 26 pm](https://user-images.githubusercontent.com/156888/37061437-5e8462c6-2148-11e8-93f3-6baf3b4a6d15.png)

I think it's ok as is

**Comment by DanTup** [comment] 2018-03-07 10:06
@xster Yep!

I've opened https://github.com/Microsoft/vscode/issues/45191 because the spinner isn't being inverted to black for light themes.

Ok, gonna close this, but feel free to shout if you think we need to look at this again (or raise in Flutter if you think it's API-related).

**Closed by DanTup** 2018-03-07 10:06 UTC
Labels: awaiting info, in debugger, in flutter, is enhancement
