### ISSUE TITLE
Renaming files triggers `uri_does_not_exist`

### ISSUE THREAD

**Issue by FMorschel** [Dart-Code/Dart-Code#5269] opened 2024-09-16 12:59 UTC
**Describe the bug**
When renaming files I got `uri_does_not_exist` in the line modified by the refactoring.

**To Reproduce**
1. Create a new empty project
2. Add file `a.dart`
3. Add import to main.dart
4. Rename `a.dart` to `c.dart`
5. Immediately click on `main.dart` (I believe)
6. See that on `main.dart` you get the `uri_does_not_exist` lint on the line that now is `c.dart`

Here is the zip with all logs: [temp.zip](https://github.com/user-attachments/files/17013446/temp.zip) (`main.dart` in this case is `temp.dart`).

**Expected behavior**
No errors.

**Please complete the following information:**

<details>

<summary><strong>Workspace Environment</strong></summary>

```text
Dart Code extension: 3.97.20240902
Flutter extension: 3.97.20240902 (activated)

App: Visual Studio Code
App Host: desktop
Version: win 1.93.1

Workspace type: Dart (LSP)
Workspace name: temp

Dart (3.5.3): C:\Users\felip_0vh5fa6\.puro\shared\caches\36335019a8eab588c3c2ea783c618d90505be233\dart-sdk
Flutter (3.24.3): C:\Users\felip_0vh5fa6\.puro\envs\stable\flutter (No device)

```

</details>

<details>

<summary><strong>Output from 'dart info'</strong></summary>

`C:\Users\felip_0vh5fa6\.puro\shared\caches\36335019a8eab588c3c2ea783c618d90505be233\dart-sdk\bin\dart.exe info`

If providing this information as part of reporting a bug, please review the information
below to ensure it only contains things you're comfortable posting publicly.

#### General info

- Dart 3.5.3 (stable) (Wed Sep 11 16:22:47 2024 +0000) on "windows_x64"
- on windows / "Windows 10 Pro" 10.0 (Build 22631)
- locale is pt-BR

#### Project info

- sdk constraint: '^3.6.0-175.0.dev'
- dependencies: args
- dev_dependencies: lints, test

#### Process info

| Memory | CPU | Elapsed time | Command line |
| -----: | --: | -----------: | ------------ |
|   0 MB |  -- |              | dart.exe     |
|   0 MB |  -- |              | dart.exe     |
|   0 MB |  -- |              | dart.exe     |
|   0 MB |  -- |              | dart.exe     |
|   0 MB |  -- |              | dart.exe     |
|   0 MB |  -- |              | dart.exe     |
|   0 MB |  -- |              | dart.exe     |

</details>

**Comment by DanTup** [comment] 2024-09-16 15:11
Thanks, I've been through the log and filtered it to just the important events and something does look wrong here.

[repro_instrum_filtered.txt](https://github.com/user-attachments/files/17015360/repro_instrum_filtered.txt)

The operation is done, undone, and redone in the log. The second time everything looks good, but the first time there is a stale `uri_does_not_exist` that should've become an `unused_import`.

The only obvious difference is that in the broken case, the file was opened by VS Code _prior_ to the watch event being processed. I don't know if this is the trigger, but it is something to try and reproduce in a test.

```
# VS Code opens c.dart
13:09:24.286,Req,{"jsonrpc":"2.0","method":"textDocument/didOpen","params":{"textDocument":{"uri":"file:///C%3A/Users/felip_0vh5fa6/Documents/Projects/dart/temp/bin/c.dart","languageId":"dart","version":1,"text":""}},"clientRequestTime":1726488564278}

# The rename happens on disk
13:09:24.293,Watch,<unknown>,C:\Users\felip_0vh5fa6\Documents\Projects\dart\temp\bin\c.dart,add
13:09:24.293,Watch,<unknown>,C:\Users\felip_0vh5fa6\Documents\Projects\dart\temp\bin\a.dart,remove

####### We resend uri_does_not_exist even though the file does exist.. It's possible we haven't processed it yet, but it appears that we never correct the issue.
13:09:24.426,Res,{"jsonrpc":"2.0","method":"textDocument/publishDiagnostics","params":{"diagnostics":[{"code":"uri_does_not_exist","codeDescription":{"href":"https://dart.dev/diagnostics/uri_does_not_exist"},"message":"Target of URI doesn't exist: 'c.dart'.\nTry creating the file referenced by the URI, or try using a URI for a file that does exist.","range":{"end":{"character":15,"line":2},"start":{"character":7,"line":2}},"severity":1,"source":"dart"},{"code":"unused_import","codeDescription":{"href":"https://dart.dev/diagnostics/unused_import"},"message":"Unused import: 'b.dart'.\nTry removing the import directive.","range":{"end":{"character":15,"line":3},"start":{"character":7,"line":3}},"severity":2,"source":"dart"}],"uri":"file:///C:/Users/felip_0vh5fa6/Documents/Projects/dart/temp/bin/temp.dart"}}
```

**Comment by DanTup** [comment] 2024-10-28 15:53
I managed to repro this today by undoing and redoing using exactly the steps above. Not sure if important, but I didn't save `main.dart` after adding the initial import.

**Comment by FMorschel** [comment] 2024-10-28 16:06
> Not sure if important, but I didn't save `main.dart` after adding the initial import.

I do have auto-save set to 1 second so I don't think that would make a difference, but good to track.

**Comment by DanTup** [comment] 2024-10-28 16:12
Yeah, I don't think it matters. I think I've repro'd in a test, and I think it might be the same issue as https://github.com/dart-lang/sdk/issues/55318 and so an easier way to reproduce is:

- add "import 'foo.dart';" to a file
- now create "foo.dart"

The `uri_does_not_exist` error doesn't go away. I think it may be because creating the file `foo.dart` does not invalidate any files that had an unresolved import for `foo.dart`.

**Comment by DanTup** [comment] 2024-10-28 19:12
Fixed by https://github.com/dart-lang/sdk/commit/12d9554c5be7e55d112e56a4f90b1c8580bdbef1. The change is in the analysis server so ships with a future Dart/Flutter SDK.

**Closed by DanTup** 2024-10-28 19:12 UTC
Labels: is bug, in editor, in lsp/analysis server
