### ISSUE TITLE
Dartdoc tooltips are not rendered as expected

### ISSUE THREAD

**Issue by jacehensley-wf** [Dart-Code/Dart-Code#41] opened 2016-08-06 19:29 UTC
Currently the tooltips stack the doc comment and type, one right after the other. I think it would be easier to read if there was an extra new line between them.

Also It would be nice if the doc comments were formatted via markdown.

**Comment by DanTup** [comment] 2016-08-06 19:45
@devoncarew recently made a bunch of changes that I think covers this. I might push another build to the marketplace tomorrow if I get some time to finish a few more things.

Thanks for the feedback!

**Comment by DanTup** [comment] 2016-08-06 19:45
See #26 for details/screenshot.

**Comment by jacehensley-wf** [comment] 2016-08-06 19:56
Awesome!

**Comment by DanTup** [comment] 2016-08-06 19:58
I guess this can be considered a dupe then. Do post back if after the update you think it needs more attention!

**Comment by jacehensley-wf** [comment] 2016-08-08 16:24
I noticed the update to the tooltip and it is much better I would like it to keep newlines and indentation if possible.

![imge](http://g.recordit.co/75VBQvw2TP.gif)

**Comment by DanTup** [comment] 2016-08-08 16:59
The blank lines are being removed by Code :( I've raised https://github.com/Microsoft/vscode/issues/10311 to see what MS say.

The other issue I think is by design; the analysis service doesn't return the indented line; I think because it assumes that's a code sample which shouldn't appear in a hover tooltip.

**Comment by DanTup** [comment] 2016-08-08 17:11
The blank lines are being removed by Code :( I've raised https://github.com/Microsoft/vscode/issues/10311 to see what MS say.

The other issue I suspect is by design but I've [posted in the Analysis Server group](https://groups.google.com/a/dartlang.org/forum/#!topic/analyzer-discuss/hrcdRUCY2iA) seeking clarification.

**Comment by DanTup** [comment] 2016-08-09 16:59
Microsoft have fixed the blank lines disappearing for the next version (presumably in next insiders release too, but I'm not sure how often that updates, I don't use it yet).

Still awaiting a response from the other issue; it seems like it might be a cache invalidation issue or something in the Dart analysis service so I'm hoping Google can confirm or suggest what I might be doing wrong.

**Comment by DanTup** [comment] 2016-08-11 11:26
MS have fixed the newlines vanishing and Google have fixed the issues causing tooltips to sometimes show stale data. These will be in future (hopefully next) updates to VS Code and the Dart SDK :-)

**Comment by DanTup** [comment] 2016-08-19 10:36
Probably makes sense to keep external issues open until they're dealt with to avoid duplicates being opened (and as a reminder there's something we want to do that is waiting on something else).

Both the issues involved here are fixed but there hasn't been a new Code or SDK release yet.

**Comment by DanTup** [comment] 2016-08-28 12:00
Test this with in Insiders with 1.19 SDK, it's better, but still not right:

![Tooltip](https://cloud.githubusercontent.com/assets/1078012/18033515/533b7b40-6d1f-11e6-9c0b-a1a89fb4aece.png)

Will need to investigate again.

**Comment by DanTup** [comment] 2016-08-28 12:11
I think the problem is that Code doesn't know the indented blocks are Dart.

**Comment by DanTup** [comment] 2016-08-28 12:17
We can fix this by sending code blocks as `MarkedString`s with the language set, or rewriting the blocks to by fenced with triple-backticks and a language.

**Comment by DanTup** [comment] 2016-08-28 12:26
Re-purpoising this; I think there's quite a lot we need to improve:

```
/// _italic_ **bold**.
///
/// And some `inline code`.
///
/// * List item 1
/// * List item 2
///
///     * Indented list item
///
/// Code blocks are supported
///
///     final name = "Danny";
///     print(name);
///
/// Links can be:
///
/// * http://www.just-a-bare-url.com
/// * [with the URL inline](http://google.com)
/// * [or separated out][ref link]
///
/// [ref link]: http://google.com
///
/// # A Header
///
/// ## A subheader
///
/// ### A subsubheader
///
/// #### If you need this many levels of headers, you're doing it wrong
```

![Tooltip](https://cloud.githubusercontent.com/assets/1078012/18033671/f8af50bc-6d22-11e6-8294-0de203619775.png)

**Comment by DanTup** [comment] 2016-08-28 12:32
I think the fix for this has introduced far more spacing than intended; I think we're waiting on https://github.com/Microsoft/vscode/issues/10311 again for now.

**Comment by DanTup** [comment] 2016-08-29 07:31
The issue in code is actually only affecting lists; the other stuff we can already fix (but we'll need to detect code blocks to mark them up as Dart).

**Comment by DanTup** [comment] 2016-08-31 19:19
This is back with MS; two reasons:

1. Insiders appears to be dropping newlines again: https://github.com/Microsoft/vscode/issues/10311#issuecomment-243850395
2. Request for allowing us to provide a default language for code blocks: https://github.com/Microsoft/vscode/issues/11331

**Comment by DanTup** [comment] 2016-09-08 17:54
Considering this done now. MS intend to ship VS Code 1.5 today and 1.19 SDK is already out.

Hovers are going to get an overhaul soon (in Code, and then Dart Code) so things will improve further in a future version.

**Closed by DanTup** 2016-09-08 17:54 UTC
Labels: bug, fixed externally: dart 1.19, fixed externally: vs code 1.5
