### ISSUE TITLE
Autocompletion for @override

### ISSUE THREAD

**Issue by colinskow** [Dart-Code/Dart-Code#4103] opened 2022-08-12 21:49 UTC
**Is your feature request related to a problem? Please describe.**
I frequently write `@override` functions, and after I hit enter it auto-completes to something else. I have to hit escape, then enter to avoid changing it. This gets annoying.

**Describe the solution you'd like**
When I would like to be able to type `@ov` enter to get `@override`.

**Comment by DanTup** [comment] 2022-08-22 17:57
Are you able to give an example of some code (and a screenshot) where the wrong thing is completed? I tested in a few places, but `override` always seemed to be at the top:

<img width="434" alt="Screenshot 2022-08-22 at 18 56 43" src="https://user-images.githubusercontent.com/1078012/185987646-381115e7-c710-4f1e-802b-0f4732ed118a.png">

**Comment by colinskow** [comment] 2022-08-22 23:41
It seems to work fine if I write the function first and then add `@override` above, but if the function below doesn't exist yet it doesn't show.

![override](https://user-images.githubusercontent.com/5303269/186038305-6e305f96-0659-40af-bf62-6db76dc2550f.png)

**Comment by DanTup** [comment] 2022-08-23 10:40
Thanks! Closing this as a dupe of #3182 (which I've re-opened, because it was assumed to be a dupe of something else, which is was not).

**Closed by DanTup** 2022-08-23 10:40 UTC
Labels: is bug, in editor, in lsp/analysis server
