### ISSUE TITLE
How should I disable dart formatter for a single file?

### ISSUE THREAD

**Issue by nehal076** [Dart-Code/Dart-Code#3703] opened 2021-12-02 05:21 UTC
I want to keep my code like this (just for 1 file)

![image](https://user-images.githubusercontent.com/32421196/144362454-2772df25-c644-4028-8aa9-135f9981fa9c.png)

but after formatting it goes like this..

![image](https://user-images.githubusercontent.com/32421196/144362667-2e393ce6-09a9-46aa-8e66-c796c3ef4608.png)

Any solution for this issue? 
I'm using VSCode

**Comment by DanTup** [comment] 2021-12-02 10:22
There's not currently a solution for this. Pre-LSP there was a `doNotFormat` option but it's not currently supported by LSP (#3586).

One option would be to disable format-on-save and just run the format command manually (and not for this file), but I appreciate that's not ideal.

I'll close this as a dupe of #3586 though, as I think the fix is the same. Thanks!

**Closed** 2021-12-02 10:22 UTC
Labels: duplicate, is question

**Comment by wiremoons** [comment] 2023-12-03 08:23
I found this (and similar) issues as I wanted to disable formatting for one line of code. The reason being is the Dart LSP formatter takes this code:

```dart
final List<String> symbols = ["+", "@", "\\", "/", "*", "#", "\$", "&", "%"];                                                            
final List<String> digits = ["0", "1", "2", "3", "4", "5", "6", "7", "8", "9"]; 
```
and changes it to
```dart
 final List<String> symbols = ["+", "@", "\\", "/", "*", "#", "\$", "&", "%"];                                                                   
 final List<String> digits = [                                                                                                                   
    "0",                                                                                                                                          
    "1",                                                                                                                                          
    "2",                                                                                                                                          
    "3",                                                                                                                                          
    "4",                                                                                                                                          
    "5",                                                                                                                                          
    "6",                                                                                                                                          
    "7",                                                                                                                                          
    "8",                                                                                                                                          
    "9"                                                                                                                                           
  ];  
```
It is odd behaviour (in my view at least) to format across so may lines, and also have different treatment for the two lists.

Being able to wrap the lists with a hint/command for the LSP, to stop this from being altered would be very useful. Perhaps something like:
```dart
@formatter: off
final List<String> symbols = ["+", "@", "\\", "/", "*", "#", "\$", "&", "%"];                                                            
final List<String> digits = ["0", "1", "2", "3", "4", "5", "6", "7", "8", "9"];
@formatter: on

```

**Comment by pro100svitlo** [comment] 2024-11-22 09:27
This is bizarre 🤯 
we are ending 2024 and there are still no options to disable formating for some specific lines or file...

**Comment by DanTup** [comment] 2024-11-22 10:48
@parlough see the issue linked in my comment above yours - this has been implemented but hasn't yet shipped in a stable release.

**Comment by maincraft-io** [comment] 2024-12-24 12:56
> I found this (and similar) issues as I wanted to disable formatting for one line of code. The reason being is the Dart LSP formatter takes this code:
> 
> ```dart
> final List<String> symbols = ["+", "@", "\\", "/", "*", "#", "\$", "&", "%"];                                                            
> final List<String> digits = ["0", "1", "2", "3", "4", "5", "6", "7", "8", "9"]; 
> ```
> 
> and changes it to
> 
> ```dart
>  final List<String> symbols = ["+", "@", "\\", "/", "*", "#", "\$", "&", "%"];                                                                   
>  final List<String> digits = [                                                                                                                   
>     "0",                                                                                                                                          
>     "1",                                                                                                                                          
>     "2",                                                                                                                                          
>     "3",                                                                                                                                          
>     "4",                                                                                                                                          
>     "5",                                                                                                                                          
>     "6",                                                                                                                                          
>     "7",                                                                                                                                          
>     "8",                                                                                                                                          
>     "9"                                                                                                                                           
>   ];  
> ```
> 
> It is odd behaviour (in my view at least) to format across so may lines, and also have different treatment for the two lists.
> 
> Being able to wrap the lists with a hint/command for the LSP, to stop this from being altered would be very useful. Perhaps something like:
> 
> ```dart
> @formatter: off
> final List<String> symbols = ["+", "@", "\\", "/", "*", "#", "\$", "&", "%"];                                                            
> final List<String> digits = ["0", "1", "2", "3", "4", "5", "6", "7", "8", "9"];
> @formatter: on
> ```

Same problem

**Comment by Safwen-Saafi** [comment] 2025-04-17 17:08
in your vscode project create this file in here .vscode/settings.json
inside it paste this:

{
    "editor.formatOnSave": false,
    "[dart]": {
        "editor.formatOnSave": false
    }
}


that's it, you are good to go !
