### ISSUE TITLE
Breakpoints are not honoured correctly when debugging Flutter apps in Chrome.

### ISSUE THREAD

**Issue by robert-ovens** [Dart-Code/Dart-Code#3914] opened 2022-04-06 19:45 UTC
**Describe the bug**

The problem occurs when debugging Flutter Web in Chrome. Breakpoints cause the execution to pause, but do not show the stack trace or highlight the line of code where the breakpoint is set.

**To Reproduce**
1. `flutter create reproduce_debug_problem`
1. Open the app in VS Code
2. Set the device to be "Chrome web"
3. Set a breakpoint at line 55 `setState(() {`
4. Debug the app
5. Click the counter incrementer button
6. Execution halts, but the Call Stack pane does not contain the call stack. Line 55 is not highlighted.

**Expected behavior**
1. The execution to halt
2. The call stack to be displayed in the Call Stack pane
3. The breakpoint to be highlighted 

**Versions (please complete the following information):**
 - VS Code version:
 ```
Version: 1.66.0
Commit: e18005f0f1b33c29e81d732535d8c0e47cafb0b5
Date: 2022-03-30T05:50:41.156Z
Electron: 17.2.0
Chromium: 98.0.4758.109
Node.js: 16.13.0
V8: 9.8.177.11-electron.0
OS: Linux x64 5.13.0-39-generic
```
 - Dart extension version:
 `v3.38.0`
 - Flutter extension version:
 `v3.38.1`
 - Dart/Flutter SDK version:
```
[✓] Flutter (Channel stable, 2.10.4, on Ubuntu 21.10 5.13.0-39-generic, locale en_AU.UTF-8)
    • Flutter version 2.10.4 at /home/robert/snap/flutter/common/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c860cba910 (13 days ago), 2022-03-25 00:23:12 -0500
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /home/robert/Android/Sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /usr/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.14.1+1-Ubuntu-0ubuntu1.21.10)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] VS Code (version 1.66.0)
    • VS Code at /usr/share/code
    • Flutter extension version 3.38.1

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 100.0.4896.75

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```

**Comment by DanTup** [comment] 2022-04-06 22:34
Thanks for the report! I believe this is a dupe of https://github.com/Dart-Code/Dart-Code/issues/3911. The issue is that Chrome v100 deprecated an API that dwds (a debug proxy Flutter uses to make debugging Chrome behave like debugging the Dart VM) was using.

A fix is being worked on via https://github.com/dart-lang/webdev/issues/1557 (I believe the fix has been made, but it's not been released yet). Once that fix goes out (in a Flutter SDK), things should just start working, with no changes required in the VS Code extension.

**Closed by DanTup** 2022-04-06 22:34 UTC
Labels: is bug
