### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by nyasha** [Dart-Code/Dart-Code#1701] opened 2019-05-10 11:25 UTC
- Issue Type: `Performance`
- Extension Name: `dart-code`
- Extension Version: `3.0.1`
- OS Version: `Windows_NT x64 6.1.7601`
- VSCode version: `1.33.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\nchasakara\Dart-Code.dart-code-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by DanTup** [comment] 2019-05-13 06:36
> Make sure to attach this file from your home-directory:

You didn't include the file mentioned in the message. Are you able to attach it? My guess is that this is a dupe of #1628 but I can't be sure without the file.

**Closed** 2019-06-11 13:39 UTC
Labels: awaiting info
