### ISSUE TITLE
Flutter VSC Plugin – Support automatic hot reload on multiple devices

### ISSUE THREAD

**Issue by lukepighetti** [Dart-Code/Dart-Code#1046] opened 2018-06-29 13:31 UTC
I understand that debug in VSC can really only be on one device, but I believe all other features can run on all device simultaneously without problem. 

Especially since you can do this already with `flutter run -d all`.

 The only difference is that `flutter run -d all` does not appear to listen for file changes, which VSC plugin does. 

Thank you.

**Comment by DanTup** [comment] 2018-07-02 12:12
> I understand that debug in VSC can really only be on one device

VSC actually supports multiple concurrent debug sessions :-)


> Especially since you can do this already with `flutter run -d all`

I had the same thought as you; and even [implemented this in a branch](https://github.com/Dart-Code/Dart-Code/tree/flutter-run-all-devices) - but unfortunately when running `flutter run` in the API mode (which tooling needs to use to get JSON output), `-d all` is not supported:

```
dantup-macbookpro:stocks dantup$ flutter run --machine -d all
--machine does not support -d all.
```

So, supporting this is a bit more complicated; but something I want to do, but we have some issues with running some operations (like hot reload) concurrently - for ex. https://github.com/flutter/flutter/issues/18566 (which I've begun work on trying to handle in https://github.com/flutter/flutter/pull/18838).

The main issue for this feature is https://github.com/Dart-Code/Dart-Code/issues/728; it's worth subscribing to that. Once implemented, I hope we will support full debugging functionality (including, expression evaluation, etc.) - though you'll also be able to run "without debugging".

I'll close this as I think it's essentially a dupe of https://github.com/Dart-Code/Dart-Code/issues/728 but shout if you think differently :-)

**Closed by DanTup** 2018-07-02 12:12 UTC
