### ISSUE TITLE
Expected to link dart:core and dart:async together: [dart:core/iterable.dart, dart:core]

### ISSUE THREAD

**Issue by erabti** [Dart-Code/Dart-Code#4579] opened 2023-06-09 16:50 UTC
**Describe the bug**
The dart analyzer suddenly terminates.

**To Reproduce**
Not sure, sometimes it does it randomly, this time when I was replacing strings.

**Analyzer Log Error**
```
Bad state: Expected to link dart:core and dart:async together: [dart:core/iterable.dart, dart:core]
#0      LinkedElementFactory.removeLibraries (package:analyzer/src/summary2/linked_element_factory.dart:260:9)
#1      LibraryContext.remove (package:analyzer/src/dart/analysis/library_context.dart:265:20)
#2      AnalysisDriver._removePotentiallyAffectedLibraries (package:analyzer/src/dart/analysis/driver.dart:1711:22)
#3      AnalysisDriver._applyPendingFileChanges (package:…
```
Full Log: [log-3778.txt](https://github.com/Dart-Code/Dart-Code/files/11708498/log-3778.txt)

**Please complete the following information:**
 - Operating System and version: MacOS 13.4
 - VS Code version: 1.78.2
 - Dart extension version: v3.66.0
 - Dart/Flutter SDK version: Flutter 3.10.2, Dart 3.0.2

**Comment by DanTup** [comment] 2023-06-09 16:55
Can you reliably reproduce this? The error in the log is this:

```
[7:47:06 PM] [Analyzer] [Error] Unhandled exception:
Bad state: Expected to link dart:core and dart:async together: [dart:core/iterable.dart, dart:core]
#0      LinkedElementFactory.removeLibraries (package:analyzer/src/summary2/linked_element_factory.dart:260:9)
#1      LibraryContext.remove (package:analyzer/src/dart/analysis/library_context.dart:265:20)
#2      AnalysisDriver._removePotentiallyAffectedLibraries (package:analyzer/src/dart/analysis/driver.dart:1711:22)
#3      AnalysisDriver._applyPendingFileChanges (package:…
```

There's an open issue about this at https://github.com/dart-lang/sdk/issues/51142 so I'll close this as a dupe. If you're able to reliable reproduce this, please post on that issue. Thanks!

**Closed by DanTup** 2023-06-09 16:55 UTC
Labels: is bug
