### ISSUE TITLE
Right click "run" support for tests and binaries

### ISSUE THREAD

**Issue by matanlurey** [Dart-Code/Dart-Code#196] opened 2016-10-17 19:57 UTC
Would be nice :)

**Comment by DanTup** [comment] 2016-10-18 16:43
We have #87 open for some sort of test integration; but currently Code doesn't really have any hooks (we can't just add arbitrary functionality in Code).

As for running binaries, pressing F5 should work; is there a particular reason you want it on a right-click menu? (eg. is it to make it easier to swap the startup script?)

**Comment by matanlurey** [comment] 2016-10-18 17:29
That's fair enough. I've been mostly running

`pub run test <my/file/name.dart>`, but it would be nice for a hook/shortcut.

**Comment by DanTup** [comment] 2016-10-18 17:33
You could manually add an option for this to the json files in the `.vscode` folder for now; though I'm hoping I can automate that in future (see https://github.com/Microsoft/vscode/issues/10742).

**Comment by DanTup** [comment] 2016-11-18 14:40
I think this case is effectively a dupe of #87, https://github.com/Microsoft/vscode/issues/10742 and https://github.com/Microsoft/vscode/issues/15179.

Generally, the code team want to expose APIs for things that are common across languages so that they'll work the same for each language, so I don't think there's really anything actionable here.

I do have commands for `pub run test` on a branch, but I've been avoiding merging it due to https://github.com/Microsoft/vscode/issues/10401 (it'll appear for all projects, not just Dart) :(

If you think there's anything that isn't covered by those other cases, do shout!

**Closed by DanTup** 2016-11-18 14:40 UTC
