### ISSUE TITLE
After last update the bottom right status popup not existed any more

### ISSUE THREAD

**Issue by AlaaEldeenYsr** [Dart-Code/Dart-Code#2601] opened 2020-07-02 11:53 UTC
After dart code extension auto update to latest version, That bottom right popup which shows debug current status on hot reload doesn't get display any more? Could you please tell me how to retrieve it back ?
![image](https://user-images.githubusercontent.com/52201392/86355505-0b941c80-bc6b-11ea-803d-7849e0f77ea4.png)

**Comment by DanTup** [comment] 2020-07-02 12:34
This progress notification has moved to the status bar (bottom left). If you click on it, it will expand into a larger notification.

This was part of a change to start using standard messages from the debug-adapter-protocol for better compatibility with other editors. Unfortunately VS code doesn't give the option to show these types of progress messages in a larger notification (something I've mentioned in https://github.com/microsoft/vscode/issues/101405#issuecomment-652358374).

If you're not seeing these messages in the lower left status bar (and are on the latest version - v3.12.1), please let me know!

**Comment by AlaaEldeenYsr** [comment] 2020-07-03 05:26
Yes i can see it in the lower left status bar. But really the old progress notification was better, It was more visible and more noticeable. If there is any possibility in the future to provide an option for something like this again, that would be good. Thank you master @DanTup

**Comment by DanTup** [comment] 2020-07-06 13:04
This would need to be handled by VS Code - please add a 👍  here:

https://github.com/microsoft/vscode/issues/101791

**Comment by DanTup** [comment] 2020-07-06 13:05
I'll close this as a dupe of #2597, which I'll keep open as a reminder about this.

**Closed by DanTup** 2020-07-06 13:05 UTC
