### ISSUE TITLE
feature request: move class to separate file

### ISSUE THREAD

**Issue by jeiea** [Dart-Code/Dart-Code#4461] opened 2023-03-26 14:41 UTC
**Is your feature request related to a problem? Please describe.**
I often find myself reusing private widgets (e.g. _SomeButton) later on and think that moving them into a separate file would be more efficient. Currently, doing so is repetitive and tedious.

**Describe the solution you'd like**
I suggest adding a code action called "Move to 'some_button.dart'" which would move the class under the cursor into a separate file in the same directory. It would be helpful if this feature could also address import statements.

**Describe alternatives you've considered**
Nothing.

**Comment by DanTup** [comment] 2023-03-26 18:15
Closing this as a dupe of #1831.

This action is in-progress as part of a new refactoring system (that'll hopefully make additional refactors easy to implement in future). It handles imports and also allows you to move multiple items at once (and to pick an existing or new file to move to).

It's currently behind a flag (and the version in the latest stable release is quite incomplete - latest `master`/bleeding-edge builds are more complete), info at https://github.com/dart-lang/sdk/issues/30310#issuecomment-1438147738.

**Closed** 2023-03-26 18:15 UTC
Labels: duplicate
