### ISSUE TITLE
Run Dart web apps

### ISSUE THREAD

**Issue by marcojakob** [Dart-Code/Dart-Code#167] opened 2016-09-04 23:41 UTC
Running a web application directly from the IDE would be great: pub serve, opening Dartium or another browser, maybe even debugging the web application.

May be related to: https://github.com/Dart-Code/Dart-Code/issues/68

I'm evaluating the use of Dart-Code for people getting started with programming (education, schools). It is important that starting web applications is as easy as possible.

**Comment by DanTup** [comment] 2016-09-05 19:11
This is really a dupe of #68. My plan was to just go straight for DDC but I'm having second thoughts for a few reasons, such as:

1. DDC isn't ready yet
1. DDC doesn't seem to do incremental compilation; we'd need to provide that
1. Debugging is less friendly in JS than Dartium

So, I might look at trying to do something else in the meantime. I'd really love to have a good web app story for v1.

So, I encourage you to add your thoughts to #68. What would you prefer? How much set up can you have done in advance (eg. setting up Dartium, etc.)?

**Closed** 2016-09-05 19:18 UTC
Labels: duplicate
