### ISSUE TITLE
Vscode shortcuts running slow

### ISSUE THREAD

**Issue by AhmetMelihSerter** [Dart-Code/Dart-Code#3386] opened 2021-06-05 14:05 UTC
**Describe the bug**
Vscode shortcuts running slow.

**To Reproduce**
1. Opens quickly when pressing the yellow bulb. 💡
2. `ctrl`  `.` it runs slow when i press the shortcut.

**Expected behavior**
Press the yellow light bulb and all the options appear immediately but take a long time to press the shortcut.

**Screenshots**
![Vscode Hatasi](https://user-images.githubusercontent.com/23049819/120893964-8e152100-c61e-11eb-9e4c-cfb4b7e2bc96.gif)

**Versions (please complete the following information):**
 - VS Code version: 1.56.2
 - Dart extension version: 3.23.0
 - Dart/Flutter SDK version: 2.0.4

**Comment by DanTup** [comment] 2021-06-09 12:50
I believe you're hitting an issue that was fixed in Flutter v2.2 (https://github.com/dart-lang/sdk/commit/e8d53cff924214ea8dd20b36bb82f7d2dde7a131). The problem is that your mouse cursor was over a symbol when you pressed `Ctrl` which caused VS Code to try to open the referenced file (to render a preview in the tooltip) and that was incorrectly triggering some expensive work in the server.

If you still see the same issue after upgrading to Flutter v2.2 and restarting VS Code, please shout and we can capture a log and do some debugging. Thanks!

**Closed** 2021-06-09 12:51 UTC
Labels: fixed in dart / flutter
