### ISSUE TITLE
Hot reload + other debugging functionality stopped working in VS Code 1.49

### ISSUE THREAD

**Issue by MuhammamdArslanKhan** [Dart-Code/Dart-Code#2786] opened 2020-09-11 12:24 UTC
Debugger and without debugger both not working in the latest VScode 1.49. it just works with the commands.
And it doesn't show any logs in console.
`flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel unknown, v1.17.3, on Microsoft Windows [Version 10.0.19041.508], locale en-US)
 
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[√] Chrome - develop for the web
[√] Android Studio (version 4.0)
[√] VS Code, 64-bit edition (version 1.49.0)
[√] Connected device (3 available)
`

**Comment by DanTup** [comment] 2020-09-14 08:59
Can you try capturing logs using the [capture logs command](https://dartcode.org/docs/logging/#capture-logs-command) - you can untick **Analysis Server** but leave everything else ticked. Thanks!

**Comment by Proberts** [comment] 2020-09-17 10:01
I'm having the same problem but it didn't start in 1.49 until I ran 'flutter upgrade' yesterday. The hot reload button has disappeared from the tool bar. I can't force hot-reload with CTRL-F5. If I 'flutter run' in the terminal I can hot reload with 'r'. 

I've verified avd and images are up to date in Android Studio.
I've uninstalled and re-installed Dart and Flutter for vscode, and also disabled then re-enabled "Hot Reload On Save"

```
[✓] Flutter (Channel master, 1.22.0-10.0.pre.221, on Linux, locale en_US.UTF-8)
    • Flutter version 1.22.0-10.0.pre.221 at /devel/BestBud/mobileapp/flutter/flutter
    • Framework revision fa646339d6 (9 hours ago), 2020-09-16 17:47:04 -0700
    • Engine revision 933f811d94
    • Dart version 2.10.0 (build 2.10.0-135.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /home/proberts/Android/Sdk
    • Platform android-29, build-tools 30.0.1
    • Java binary at: /devel/BestBud/mobileapp/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Android Studio (version 4.0)
    • Android Studio at /devel/BestBud/mobileapp/android-studio
    • Flutter plugin version 48.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.49.0)
    • VS Code at /usr/share/code
    • Flutter extension version 3.14.1

[✓] Connected device (1 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86 • Android 7.0 (API 24)
      (emulator)

• No issues found!

```

Here's a link to the capture logs output:  [log.out](https://drive.google.com/file/d/1PMlJBMQRfqDztKkYidDxk-fzPLPSDmPS/view?usp=sharing)

I launch the app using debugging in vscode. Wait for everything to initialize. 

1. Make a change to a widget color.
2. Save the file.
3. Wait a moment.
4. Press CTRL-F5.
5. Wait a moment.
6. Repeat with another color change.

**Comment by DanTup** [comment] 2020-09-17 10:42
I can repro this, and I believe it's the same as #2775. Will close this as a dupe of that.

**Closed by DanTup** 2020-09-17 10:42 UTC
Labels: awaiting info

**Comment by Proberts** [comment] 2020-09-18 08:04
Post to help any fellow flutter noobs experiencing this problem:  Switching to 'flutter channel dev' restores hot reload in vscode ('stable' seems to remove a lot of stuff). If, like me, you installed flutter following a tutorial that used git clone, you're probably using a branch don't want to be using for development (master). [Flutter Channels](https://github.com/flutter/flutter/wiki/Flutter-build-release-channels)

**Comment by DanTup** [comment] 2020-09-18 12:03
This should be fixed with https://github.com/dart-lang/sdk/commit/b5f688e938983f0a3a81413460d103b3c744d026 which has rolled into Flutter's master branch now. If you still see the issue on the latest code, please add comments to #2775. Thanks!
