### ISSUE TITLE
Debugging web apps gives error in VSCode but works in command line

### ISSUE THREAD

**Issue by easeccy** [Dart-Code/Dart-Code#3111] opened 2021-01-31 20:40 UTC
Debuggin in VSCode and Intellij using Dart Code extension gives following error:

`HttpException: , uri = http://localhost:33563/devtools/page/F2A7CE745E670DB19D98E6168DB65787`

Running `flutter run` command in terminal works. This only happens with web debugging, Android works fine.

Output for `flutter doctor --verbose`:
```
[✓] Flutter (Channel beta, 1.25.0-8.3.pre, on Linux, locale en_US.UTF-8)
    • Flutter version 1.25.0-8.3.pre at /home/enes/flutter
    • Framework revision 5d36f2e7f5 (2 weeks ago), 2021-01-14 15:57:49 -0800
    • Engine revision 7a8f8ca02c
    • Dart version 2.12.0 (build 2.12.0-133.7.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /home/enes/Android/Sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /home/enes/Android/Sdk
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /opt/android-studio
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 88.0.4324.96

• No issues found!
```

**Comment by DanTup** [comment] 2021-02-01 11:21
> HttpException: , uri = http://localhost:33563/devtools/page/F2A7CE745E670DB19D98E6168DB65787

Do you have any more information from the error than this (for example a stack trace)?

Can you reproduce the issue with a new project created with `flutter create` or does it only occur in a specific project?

If it's also occurring in IntelliJ it might not be a Dart Code issue (Dart Code is only for VS Code) and may be in Flutter.

**Comment by easeccy** [comment] 2021-02-01 11:50
It happens newly created and existing projects. Here is my `launch.json`:
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "debug",
            "request": "launch",
            "type": "dart",
            "args": ["--verbose"]
        }
    ]
}
```

Here is the debug console output:

```
[  +73 ms] executing: [/home/enes/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +33 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 5d36f2e7f5387b6c751449258ade8e4e6edf99be
[        ] executing: [/home/enes/flutter/] git tag --points-at 5d36f2e7f5387b6c751449258ade8e4e6edf99be
[  +14 ms] Exit code 0 from: git tag --points-at 5d36f2e7f5387b6c751449258ade8e4e6edf99be
[        ] 1.25.0-8.3.pre
[  +42 ms] executing: [/home/enes/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[   +4 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/beta
[        ] executing: [/home/enes/flutter/] git ls-remote --get-url origin
[   +4 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +41 ms] executing: [/home/enes/flutter/] git rev-parse --abbrev-ref HEAD
[   +5 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] beta
[  +64 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +82 ms] executing: /home/enes/Android/Sdk/platform-tools/adb devices -l
[  +16 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +59 ms] executing: /home/enes/Android/Sdk/platform-tools/adb devices -l
[  +18 ms] Skipping pub get: version match.
[ +104 ms] Found plugin integration_test at /home/enes/flutter/packages/integration_test/
[ +118 ms] Found plugin integration_test at /home/enes/flutter/packages/integration_test/
[   +4 ms] Generating /home/enes/Desktop/Dart/web_test_app/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[  +91 ms] List of devices attached
[   +2 ms] List of devices attached
[  +90 ms] Launching lib/main.dart on Chrome in debug mode...
 lib/main.dart
[ +164 ms] Updating assets
[ +177 ms] Found plugin integration_test at /home/enes/flutter/packages/integration_test/
[  +42 ms] Found plugin integration_test at /home/enes/flutter/packages/integration_test/
[  +68 ms] <- reset
[   +9 ms] /home/enes/flutter/bin/cache/dart-sdk/bin/dart --disable-dart-dev /home/enes/flutter/bin/cache/artifacts/engine/linux-x64/frontend_server.dart.snapshot --sdk-root /home/enes/flutter/bin/cache/flutter_web_sdk/ --incremental --target=dartdevc --debugger-module-names --experimental-emit-debug-metadata -Dflutter.inspector.structuredErrors=true -DFLUTTER_WEB_AUTO_DETECT=true --output-dill /tmp/flutter_tools.ABMNVY/flutter_tool.IABVCH/app.dill --libraries-spec file:///home/enes/flutter/bin/cache/flutter_web_sdk/libraries.json --packages /home/enes/Desktop/Dart/web_test_app/.dart_tool/package_config.json -Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts --track-widget-creation --filesystem-root /tmp/flutter_tools.ABMNVY/flutter_tools.BCVKCE --filesystem-scheme org-dartlang-app --initialize-from-dill build/f58ed05f7a6fba8f3451773989665e4b.cache.dill.track.dill --platform file:///home/enes/flutter/bin/cache/flutter_web_sdk/kernel/flutter_ddc_sdk.dill --no-sound-null-safety
[38;5;248m[   +8 ms] <- compile org-dartlang-app:/web_entrypoint.dart[39;49m
[+17725 ms] Synced 28.6MB.
[        ] <- accept
[        ] Caching compiled dill
[ +142 ms] Using Google Chrome 88.0.4324.96
[ +236 ms] [CHROME]:
[   +1 ms] [CHROME]:DevTools listening on ws://127.0.0.1:43565/devtools/browser/006d6472-2046-459b-bf48-cf48baf112b7
HttpException: , uri = http://localhost:43565/devtools/page/60F8A0D3720A79A39EB3FCEAA67942AE
Exited (sigterm)
[   +5 ms]
[38;5;248m#0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)[39;49m
[38;5;248m#1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:492:9)[39;49m
           [38;5;244m<asynchronous suspension>[39;49m
[38;5;248m#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1134:12)[39;49m
           [38;5;244m<asynchronous suspension>[39;49m
[38;5;248m#3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:986:27)[39;49m
           [38;5;244m<asynchronous suspension>[39;49m
[38;5;248m#4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)[39;49m
           [38;5;244m<asynchronous suspension>[39;49m
[38;5;248m#5      AppContext.run (package:flutter_tools/src/base/context.dart:149:12)[39;49m
           [38;5;244m<asynchronous suspension>[39;49m
[38;5;244m#6      CommandRunner.runCommand[39;49m
 package:args/command_runner.dart
           [38;5;244m<asynchronous suspension>[39;49m
[38;5;248m#7      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:274:9)[39;49m
           [38;5;244m<asynchronous suspension>[39;49m
[38;5;248m#8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)[39;49m
           [38;5;244m<asynchronous suspension>[39;49m
[38;5;248m#9      AppContext.run (package:flutter_tools/src/base/context.dart:149:12)[39;49m
           [38;5;244m<asynchronous suspension>[39;49m
[38;5;248m#10     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:230:5)[39;49m
           [38;5;244m<asynchronous suspension>[39;49m
[38;5;248m#11     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:63:9)[39;49m
           [38;5;244m<asynchronous suspension>[39;49m
[38;5;248m#12     run.<anonymous closure> (package:flutter_tools/runner.dart:61:12)[39;49m
           [38;5;244m<asynchronous suspension>[39;49m
[38;5;248m#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)[39;49m
           [38;5;244m<asynchronous suspension>[39;49m
[38;5;248m#14     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)[39;49m
           [38;5;244m<asynchronous suspension>[39;49m
[38;5;248m#15     runInContext (package:flutter_tools/src/context_runner.dart:70:10)[39;49m
           [38;5;244m<asynchronous suspension>[39;49m
[38;5;248m#16     main (package:flutter_tools/executable.dart:88:3)[39;49m
           [38;5;244m<asynchronous suspension>[39;49m

```

**Comment by DanTup** [comment] 2021-02-01 12:10
Thanks - are you able to capture a log using the **Dart: Capture Debugging Logs** command, as that will include more (such as the full arguments used to spawn Flutter) that might help understand what's happening (or at least, reproduce outside of VS Code to make it easier to report in Flutter). Thanks!

**Comment by easeccy** [comment] 2021-02-01 12:26
Debugging logs:

```
Dart Code extension: 3.19.1
Flutter extension: 3.19.0 (activated)

App: Visual Studio Code
Version: 1.52.1
Platform: linux

Workspace type: Flutter
Analyzer type: LSP
Multi-root?: false

Dart SDK:
    Loc: /home/enes/flutter/bin/cache/dart-sdk
    Ver: 2.12.0-133.7.beta
Flutter SDK:
    Loc: /home/enes/flutter
    Ver: 1.25.0-8.3.pre

HTTP_PROXY: undefined
NO_PROXY: undefined

Logging Categories:
    General, CommandProcesses, VmService, DevTools, FlutterDaemon, FlutterRun, FlutterTest, PubTest, WebDaemon

Mon Feb 01 2021 [15:24:09 GMT+0300 (GMT+03:00)] Log file started
[3:24:10 PM] [General] [Info] Starting debug session...
[3:24:10 PM] [General] [Info]     workspace: /home/enes/Desktop/Dart/web_test_app
[3:24:10 PM] [General] [Info] Using found common entry point: /home/enes/Desktop/Dart/web_test_app/lib/main.dart
[3:24:10 PM] [General] [Info] Using workspace as cwd: /home/enes/Desktop/Dart/web_test_app
[3:24:10 PM] [General] [Info] Detected launch project as Flutter
[3:24:10 PM] [General] [Info] Using Flutter debug adapter for this session
[3:24:10 PM] [FlutterDaemon] [Info] ==> [{"id":"10","method":"daemon.getSupportedPlatforms","params":{"projectRoot":"/home/enes/Desktop/Dart/web_test_app"}}]
[3:24:10 PM] [FlutterDaemon] [Info] <== [{"id":"10","result":{"platforms":["ios","android","web"]}}]
[3:24:10 PM] [FlutterDaemon] [Info] ==> [{"id":"11","method":"daemon.getSupportedPlatforms","params":{"projectRoot":"/home/enes/Desktop/Dart/web_test_app"}}]
[3:24:10 PM] [FlutterDaemon] [Info] <== [{"id":"11","result":{"platforms":["ios","android","web"]}}]
[3:24:10 PM] [General] [Info] Checking for errors before launching
[3:24:10 PM] [General] [Info] Debug session starting...
    {
        "name": "debug",
        "request": "launch",
        "type": "dart",
        "args": [
            "--verbose",
            "--web-renderer=auto"
        ],
        "__configurationTarget": 5,
        "program": "/home/enes/Desktop/Dart/web_test_app/lib/main.dart",
        "cwd": "/home/enes/Desktop/Dart/web_test_app",
        "toolEnv": {
            "FLUTTER_HOST": "VSCode",
            "PUB_ENVIRONMENT": "vscode.dart-code"
        },
        "sendLogsToClient": true,
        "vmAdditionalArgs": [],
        "vmServicePort": 0,
        "dartSdkPath": "/home/enes/flutter/bin/cache/dart-sdk",
        "maxLogLineLength": 2000,
        "debugSdkLibraries": false,
        "debugExternalLibraries": false,
        "showDartDeveloperLogs": true,
        "evaluateGettersInDebugViews": true,
        "evaluateToStringInDebugViews": true,
        "flutterSdkPath": "/home/enes/flutter",
        "globalFlutterArgs": [],
        "useFlutterStructuredErrors": true,
        "useInspectorNotificationsForWidgetErrors": true,
        "debugExtensionBackendProtocol": "ws",
        "forceFlutterVerboseMode": true,
        "flutterTrackWidgetCreation": true,
        "flutterMode": "debug",
        "flutterPlatform": "default",
        "workspaceConfig": {
            "useLsp": true
        },
        "deviceId": "chrome",
        "deviceName": "Chrome (web-javascript)",
        "showMemoryUsage": false,
        "debuggerType": 2
    }
[3:24:10 PM] [General] [Info] Using flutter debugger for Flutter
[3:24:10 PM] [General] [Info] Running debugger via node with /home/enes/.vscode/extensions/dart-code.dart-code-3.19.1/out/dist/debug.js    flutter
[3:24:10 PM] [General] [Warn] Did not find session 97b7109b-f59f-4574-aa77-116934e584f9 to handle dart.progressStart. There were 0 sessions:
[3:24:10 PM] [General] [Warn] Event will be queued and processed when the session start event fires
[3:24:10 PM] [General] [Info] Processing delayed event dart.progressStart for session 97b7109b-f59f-4574-aa77-116934e584f9
[3:24:10 PM] [FlutterRun] [Info] [debug] Spawning /home/enes/flutter/bin/flutter with args ["run","--machine","--target","lib/main.dart","-d","chrome","--dart-define=flutter.inspector.structuredErrors=true","--start-paused","--web-server-debug-protocol","ws","--web-server-debug-backend-protocol","ws","--web-allow-expose-url","--verbose","--web-renderer=auto"]
[3:24:10 PM] [FlutterRun] [Info] [debug] ..  in /home/enes/Desktop/Dart/web_test_app
[3:24:10 PM] [FlutterRun] [Info] [debug] ..  with {"toolEnv":{"FLUTTER_HOST":"VSCode","PUB_ENVIRONMENT":"vscode.dart-code"}}
[3:24:10 PM] [FlutterRun] [Info] [debug]     PID: 33001
[3:24:10 PM] [FlutterRun] [Info] [debug] <== [  +78 ms] executing: [/home/enes/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[3:24:10 PM] [FlutterRun] [Info] [debug] <== [  +38 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[3:24:10 PM] [FlutterRun] [Info] [debug] <== [        ] 5d36f2e7f5387b6c751449258ade8e4e6edf99be
[3:24:10 PM] [FlutterRun] [Info] [debug] <== [        ] executing: [/home/enes/flutter/] git tag --points-at 5d36f2e7f5387b6c751449258ade8e4e6edf99be
[3:24:10 PM] [FlutterRun] [Info] [debug] <== [  +17 ms] Exit code 0 from: git tag --points-at 5d36f2e7f5387b6c751449258ade8e4e6edf99be
[3:24:10 PM] [FlutterRun] [Info] [debug] <== [        ] 1.25.0-8.3.pre
[3:24:10 PM] [FlutterRun] [Info] [debug] <== [  +46 ms] executing: [/home/enes/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[3:24:10 PM] [FlutterRun] [Info] [debug] <== [   +5 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[3:24:10 PM] [FlutterRun] [Info] [debug] <== [        ] origin/beta
[3:24:10 PM] [FlutterRun] [Info] [debug] <== [        ] executing: [/home/enes/flutter/] git ls-remote --get-url origin
[3:24:10 PM] [FlutterRun] [Info] [debug] <== [   +6 ms] Exit code 0 from: git ls-remote --get-url origin
[3:24:10 PM] [FlutterRun] [Info] [debug] <== [        ] https://github.com/flutter/flutter.git
[3:24:10 PM] [FlutterRun] [Info] [debug] <== [  +47 ms] executing: [/home/enes/flutter/] git rev-parse --abbrev-ref HEAD
[3:24:10 PM] [FlutterRun] [Info] [debug] <== [   +5 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[3:24:10 PM] [FlutterRun] [Info] [debug] <== [        ] beta
[3:24:10 PM] [FlutterRun] [Info] [debug] <== [  +46 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[3:24:10 PM] [FlutterRun] [Info] [debug] <== [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[3:24:10 PM] [FlutterRun] [Info] [debug] <== [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[3:24:10 PM] [FlutterRun] [Info] [debug] <== [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[3:24:10 PM] [FlutterRun] [Info] [debug] <== [   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[3:24:10 PM] [FlutterRun] [Info] [debug] <== [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[3:24:10 PM] [FlutterRun] [Info] [debug] <== [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[3:24:10 PM] [FlutterRun] [Info] [debug] <== [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[3:24:10 PM] [FlutterRun] [Info] [debug] <== [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[3:24:10 PM] [FlutterRun] [Info] [debug] <== [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[3:24:10 PM] [FlutterRun] [Info] [debug] <== [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[3:24:10 PM] [FlutterRun] [Info] [debug] <== [  +49 ms] executing: /home/enes/Android/Sdk/platform-tools/adb devices -l
[3:24:10 PM] [FlutterRun] [Info] [debug] <== [  +19 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[3:24:10 PM] [FlutterRun] [Info] [debug] <== [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[3:24:10 PM] [FlutterRun] [Info] [debug] <== [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[3:24:10 PM] [FlutterRun] [Info] [debug] <== [   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[3:24:10 PM] [FlutterRun] [Info] [debug] <== [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[3:24:10 PM] [FlutterRun] [Info] [debug] <== [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[3:24:10 PM] [FlutterRun] [Info] [debug] <== [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[3:24:10 PM] [FlutterRun] [Info] [debug] <== [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[3:24:10 PM] [FlutterRun] [Info] [debug] <== [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[3:24:10 PM] [FlutterRun] [Info] [debug] <== [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[3:24:10 PM] [FlutterRun] [Info] [debug] <== [  +68 ms] executing: /home/enes/Android/Sdk/platform-tools/adb devices -l
[3:24:10 PM] [FlutterRun] [Info] [debug] <== [  +19 ms] Skipping pub get: version match.
[3:24:10 PM] [FlutterRun] [Info] [debug] <== [ +102 ms] Found plugin integration_test at /home/enes/flutter/packages/integration_test/
[3:24:11 PM] [FlutterRun] [Info] [debug] <== [ +139 ms] Found plugin integration_test at /home/enes/flutter/packages/integration_test/
[3:24:11 PM] [FlutterRun] [Info] [debug] <== [   +6 ms] Generating /home/enes/Desktop/Dart/web_test_app/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[3:24:11 PM] [FlutterRun] [Info] [debug] <== [ +102 ms] List of devices attached
[3:24:11 PM] [FlutterRun] [Info] [debug] <== [   +2 ms] List of devices attached
[3:24:11 PM] [FlutterRun] [Info] [debug] <== [{"event":"daemon.connected","params":{"version":"0.6.0","pid":33025}}]
[3:24:11 PM] [FlutterRun] [Info] [debug] <== [{"event":"app.start","params":{"appId":"090ebd2f-784f-4358-b757-dcea7cb783ba","deviceId":"chrome","directory":"/home/enes/Desktop/Dart/web_test_app","supportsRestart":true,"launchMode":"run"}}]
[3:24:11 PM] [FlutterRun] [Info] [debug] <== [  +92 ms] Launching lib/main.dart on Chrome in debug mode...
[3:24:11 PM] [FlutterRun] [Info] [debug] <== [{"method":"app.exposeUrl","params":{"url":"ws://127.0.0.1:34539/$debug"},"id":"1"}]
[3:24:11 PM] [General] [Info] Exposing URL: ws://127.0.0.1:34539/%24debug
[3:24:11 PM] [General] [Info] Mapping URL: http://127.0.0.1:34539/%24debug
[3:24:11 PM] [General] [Info] Mapped URL: http://127.0.0.1:34539/%24debug
[3:24:11 PM] [General] [Info] Final URI: ws://127.0.0.1:34539/$debug
[3:24:11 PM] [General] [Info] Final URL: ws://127.0.0.1:34539/$debug
[3:24:11 PM] [FlutterRun] [Info] [debug] ==> [{"id":"1","result":{"url":"ws://127.0.0.1:34539/$debug"}}]
[3:24:11 PM] [FlutterRun] [Info] [debug] <== [ +137 ms] Updating assets
[3:24:11 PM] [FlutterRun] [Info] [debug] <== [{"event":"app.progress","params":{"appId":"090ebd2f-784f-4358-b757-dcea7cb783ba","id":"0","progressId":null,"message":"Waiting for connection from debug service on Chrome...","finished":false}}]
[3:24:11 PM] [FlutterRun] [Info] [debug] <== [ +155 ms] Found plugin integration_test at /home/enes/flutter/packages/integration_test/
[3:24:11 PM] [FlutterRun] [Info] [debug] <== [  +37 ms] Found plugin integration_test at /home/enes/flutter/packages/integration_test/
[3:24:11 PM] [FlutterRun] [Info] [debug] <== [  +71 ms] <- reset
[3:24:11 PM] [FlutterRun] [Info] [debug] <== [   +7 ms] /home/enes/flutter/bin/cache/dart-sdk/bin/dart --disable-dart-dev /home/enes/flutter/bin/cache/artifacts/engine/linux-x64/frontend_server.dart.snapshot --sdk-root /home/enes/flutter/bin/cache/flutter_web_sdk/ --incremental --target=dartdevc --debugger-module-names --experimental-emit-debug-metadata -Dflutter.inspector.structuredErrors=true -DFLUTTER_WEB_AUTO_DETECT=true --output-dill /tmp/flutter_tools.WNPFXM/flutter_tool.JACBAE/app.dill --libraries-spec file:///home/enes/flutter/bin/cache/flutter_web_sdk/libraries.json --packages /home/enes/Desktop/Dart/web_test_app/.dart_tool/package_config.json -Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts --track-widget-creation --filesystem-root /tmp/flutter_tools.WNPFXM/flutter_tools.NAHBVG --filesystem-scheme org-dartlang-app --initialize-from-dill build/f58ed05f7a6fba8f3451773989665e4b.cache.dill.track.dill --platform file:///home/enes/flutter/bin/cache/flutter_web_sdk/kernel/flutter_ddc_sdk.dill --no-sound-null-safety
[3:24:11 PM] [FlutterRun] [Info] [debug] <== [   +9 ms] <- compile org-dartlang-app:/web_entrypoint.dart
[3:24:30 PM] [FlutterRun] [Info] [debug] <== [{"event":"app.progress","params":{"appId":"090ebd2f-784f-4358-b757-dcea7cb783ba","id":"0","progressId":null,"finished":true}}]
[3:24:30 PM] [FlutterRun] [Info] [debug] <== [+18653 ms] Synced 28.6MB.
[3:24:30 PM] [FlutterRun] [Info] [debug] <== [        ] <- accept
[3:24:30 PM] [FlutterRun] [Info] [debug] <== [        ] Caching compiled dill
[3:24:30 PM] [FlutterRun] [Info] [debug] <== [ +125 ms] Using Google Chrome 88.0.4324.96
[3:24:30 PM] [FlutterRun] [Info] [debug] <== [ +326 ms] [CHROME]:
[3:24:30 PM] [FlutterRun] [Info] [debug] <== [   +2 ms] [CHROME]:DevTools listening on ws://127.0.0.1:33283/devtools/browser/02c0d104-9009-490e-af12-e938a8f3cb19
[3:24:31 PM] [FlutterRun] [Info] [debug] <== [{"event":"app.webLaunchUrl","params":{"url":"http://localhost:44589","launched":true}}]
[3:24:31 PM] [FlutterRun] [Info] [debug] <== [{"event":"app.stop","params":{"appId":"090ebd2f-784f-4358-b757-dcea7cb783ba","error":"HttpException: , uri = http://localhost:33283/devtools/page/AF4E2AA3F7A66CFAFB45CB39496872B5","trace":""}}]
[3:24:31 PM] [FlutterRun] [Info] [debug] Process terminated! null, SIGTERM
[3:24:31 PM] [VmService] [Info] [debug] Process exited (sigterm)
[3:24:31 PM] [VmService] [Info] [debug] Disconnect requested!
[3:24:31 PM] [VmService] [Info] [debug] TERM: Requested to terminate with SIGINT...
[3:24:31 PM] [VmService] [Info] [debug] TERM: Did not need to terminate processes
[3:24:31 PM] [VmService] [Info] [debug] TERM: Removing all stored data...
[3:24:31 PM] [VmService] [Info] [debug] TERM: Waiting for process to finish...
[3:24:31 PM] [VmService] [Info] [debug] TERM: Disconnecting...
[3:24:32 PM] [General] [Info] Debugger:SessionDuration timing: 21916ms (Flutter)
Mon Feb 01 2021 [15:24:36 GMT+0300 (GMT+03:00)] Log file ended

```

**Comment by DanTup** [comment] 2021-02-01 12:32
Can you try running the same command from the log from the terminal?

```
/home/enes/flutter/bin/flutter run --machine --target lib/main.dart -d chrome --dart-define=flutter.inspector.structuredErrors=true --start-paused --web-server-debug-protocol ws --web-server-debug-backend-protocol ws --web-allow-expose-url --verbose --web-renderer=auto
```

If you can reproduce the issue from the terminal with that command, try removing some of the arguments to see if you can find out which one is triggering the difference from running `flutter run`. If it doesn't occur from an external terminal, please try the VS Code built-in terminal.

Thanks!

**Comment by easeccy** [comment] 2021-02-01 13:27
`--start-paused` causes app to start with a blank screen and stuck.

`--web-allow-expose-url` causes web app to fail start debugging on Chrome.

Other arguments don't cause problems.

**Comment by DanTup** [comment] 2021-02-02 11:08
It looks like there's an open issue in Flutter about this. I don't think it's specific to the VS Code extension (the report there occurs from the command line - although I'm not sure what's different in your environment that it works there).

https://github.com/flutter/flutter/issues/73743

I'll close this as a dupe of that, and add a note about this being seen here too. Thanks!

**Closed** 2021-02-02 11:09 UTC
Labels: awaiting info, is bug
