### ISSUE TITLE
Breakpoints are missed if path casing mismatches between rootLib and breakpoint uri

### ISSUE THREAD

**Issue by TomasLinhart** [Dart-Code/Dart-Code#586] opened 2018-02-17 12:37 UTC
If I put a breakpoint in my file, it does not stop at it.

I have a folder with two files: `main.dart` and `launch.json`.

In `main.dart` I have:

```dart
main() {
  print("hello world");
}
```
And  I have put a breakpoint on the print.

In my `launch.json`, I have:

```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Dart command line",
            "program": "${workspaceRoot}/main.dart",
            "request": "launch",
            "type": "dart-cli"
        }
    ]
}
```
When I press F5, it runs the app and I see `hello world` in DEBUG CONSOLE.

I use Visual Studio Code 1.20.1 and Dart-Code 2.8.2, and Dart is 1.24.3. I have Windows 10.

And this is my [observatory.log](https://github.com/Dart-Code/Dart-Code/files/1733656/observatory.log).

**Comment by DanTup** [comment] 2018-02-17 13:05
We seem to be sending the breakpoint only once with a URI that looks bad.

```text
"rootLib":{"type":"@Library","fixedId":true,"id":"libraries\/@15204831","name":"","uri":"file:\/\/\/C:\/HelloDart\/main.dart"}

{"id":"18","method":"addBreakpointWithScriptUri","params":{"isolateId":"isolates/805765220","scriptUri":"/c:/HelloDart/main.dart","line":2}}
```

There was some refactoring around this a couple of releases back but it was supposed to improve things not make them worse! Should be an easy fix though.

**Comment by DanTup** [comment] 2018-02-19 09:34
Ok, scratch the above - this is actually caused by the drive letter casing being different. The VM treats `file:\/\/\/C:\/HelloDart\/main.dart` and `/c:/HelloDart/main.dart` differently. I have a workaround that I might use, but I'm gonna investigate why the paths (which both came from Code) have different casing.

```ts
if (isWin) {
	// Flip the casing of the drive letter since it's often different and the VM doesn't
	// consider then the same.
	uris.slice().forEach((uri) => {
		if (uri.startsWith("/") && uri.substring(1, 2) === uri.substring(1, 2).toLowerCase())
			uris.push("/" + uri.substring(1, 2).toUpperCase() + uri.substring(2));
		if (uri.startsWith("/") && uri.substring(1, 2) === uri.substring(1, 2).toUpperCase())
			uris.push("/" + uri.substring(1, 2).toLowerCase() + uri.substring(2));
	});
}
```

**Comment by DanTup** [comment] 2018-02-19 09:57
I'm committing my workaround as a fix for this for now, though I've raised cases with Code and the Dart VM as they might be able to provide better fixes:

https://github.com/Microsoft/vscode/issues/43959
https://github.com/dart-lang/sdk/issues/32222

**Closed** 2018-02-19 10:09 UTC
Labels: in debugger, is bug, on windows

**Comment by TomasLinhart** [comment] 2018-02-19 10:16
Thank you for figuring out the issue and fixing it!

**Comment by DanTup** [comment] 2018-02-19 14:17
Ugh, so it turns out this changed in Code very recently! I was certain it all worked when I tested it only a few weeks ago; good to know I wasn't going mad.

Related: https://github.com/Microsoft/vscode/issues/43959
Changeset that changed it: https://github.com/Microsoft/vscode/commit/0d66fa01479613b4782cbd974267d2108c096ea8
