### ISSUE TITLE
Annoying white thing after autocomplete kills autocomplete

### ISSUE THREAD

**Issue by lukepighetti** [Dart-Code/Dart-Code#1193] opened 2018-09-04 13:20 UTC
I honestly have no idea what this is called or if it has anything to do with Dart-Code. 

If I autocomplete something and hit `enter` or `tab` there is this trailing white selection that will not allow any more autocompletes unless I hit escape. I am finding it to be quite frustrating. 

Is there any known way to resolve this? I have to hit escape after every use of autocomplete.

After autocomplete + `enter` or `tab`

<img width="562" alt="screen shot 2018-09-04 at 9 18 38 am" src="https://user-images.githubusercontent.com/666539/45033810-b44ba380-b023-11e8-8611-bc07c555ec93.png">

After hitting `escape` (no other actions)

<img width="618" alt="screen shot 2018-09-04 at 9 18 43 am" src="https://user-images.githubusercontent.com/666539/45033822-c0376580-b023-11e8-9a03-233dccbb203a.png">

**Comment by DanTup** [comment] 2018-09-04 13:48
I think this is a dupe of https://github.com/Dart-Code/Dart-Code/issues/1173, and may be a VS Code issue: https://github.com/Dart-Code/Dart-Code/issues/1173

I so far haven't found a way to fix/workaround it so it may be worth adding comments/:+1: to the VS Code case to see if we can make it more visible.

**Comment by lukepighetti** [comment] 2018-09-04 14:40
Will do, thanks!

**Comment by DanTup** [comment] 2018-10-16 09:37
Closing this as a dupe of https://github.com/Dart-Code/Dart-Code/issues/1173 which I'm hoping to find a workaround for - though I've also added another comment to the VS Code issue to see if we can get some help - it feels broken enough that I'm surprised the issue hasn't gotten more attention.

**Closed by DanTup** 2018-10-16 09:37 UTC
