### ISSUE TITLE
Analysis server gets stuck in a loop when typing `List<Map<>>`

### ISSUE THREAD

**Issue by jhayg12** [Dart-Code/Dart-Code#2557] opened 2020-06-16 00:31 UTC
Hi there, I have this problem when trying to declare a getter function the  `List<Map<String, Object>>` seems not being recognized by the Dart Formatter on my VSCode so when I typed something inside of the getter function like the `List` widget the Dart Formatter does not even provide a autocomplete like the `generate` constructor (the screenshot below I've just typed it manually), I even tried updating the VSCode also hoping it will fix the issue but still don't work.

Cheers,

Jayson

![image](https://user-images.githubusercontent.com/33854581/84718511-52b3b980-afab-11ea-8f10-444d823bc58f.png)

![image](https://user-images.githubusercontent.com/33854581/84718597-8bec2980-afab-11ea-8b6b-b2c272342c67.png)

![image](https://user-images.githubusercontent.com/33854581/84718625-a2928080-afab-11ea-8690-22453c2cca2e.png)

![image](https://user-images.githubusercontent.com/33854581/84718645-b4742380-afab-11ea-822c-7bc2f08965ae.png)

**Comment by DanTup** [comment] 2020-06-16 08:04
I can't reproduce this - are you able to paste the file contents here, and also include a screenshot of the Problems view that shows what the errors it's showing are? Thanks!

**Comment by jhayg12** [comment] 2020-06-17 08:12
Hi @DanTup 

Here's the code snippet for it:

```
import 'package:flutter/material.dart';

class Chart extends StatelessWidget {

  List<Map<String, Object>> get groupedTransactionValues {
    return List.generate(7, (index) {
      return {'day': 'T', 'amount': 99.99}
    });
  }

  @override
  Widget build(BuildContext context) {
    return Card(
      margin: EdgeInsets.all(20),
      elevation: 6,
      child: Row(
        children: <Widget>[],
      ),
    );
  }
}
```
and here's the screenshot of the problems tab:

![image](https://user-images.githubusercontent.com/33854581/84872982-25533280-b0b5-11ea-8def-3fba5833ca79.png)

**Comment by DanTup** [comment] 2020-06-17 10:37
It seems like the editor state may be out of sync with the server. I'm still unable to repro with the file above (though note there's a missing semicolon on the end of `return {'day': 'T', 'amount': 99.99}`).

If you can reproduce this after restarting VS Code, could you capture a log?

- Close the file
- Restart VS Code
- Start capturing logs with **Dart: Capture Logs**
- Open the file and reproduce the issue
- Click **Cancel** on the Logging notification to stop logging and open the log

**Comment by jhayg12** [comment] 2020-06-17 11:13
I've added the semicolon and capture the logs please see below details:

```
!! PLEASE REVIEW THIS LOG FOR SENSITIVE INFORMATION BEFORE SHARING !!

Dart Code extension: 3.11.0
Flutter extension: 3.11.0 (not activated)

App: Visual Studio Code
Version: 1.46.0
Platform: win

Workspace type: Flutter
Multi-root?: false

Dart SDK:
    Loc: C:\src\flutter\bin\cache\dart-sdk
    Ver: 2.8.4
Flutter SDK:
    Loc: C:\src\flutter
    Ver: 1.17.3

HTTP_PROXY: undefined
NO_PROXY: undefined

Wed Jun 17 2020 [19:09:02 GMT+0800 (Philippine Standard Time)] Log file started
[7:09:06 pm] [Analyzer] [Info] ==> {"id":"232","method":"edit.getFixes","params":{"file":"E:\\flutter_projects\\expense_tracker\\lib\\widgets\\chart.dart","offset":238},"clientRequestTime":1592392146880}
[7:09:06 pm] [Analyzer] [Info] ==> {"id":"233","method":"edit.getAssists","params":{"file":"E:\\flutter_projects\\expense_tracker\\lib\\widgets\\chart.dart","length":0,"offset":238},"clientRequestTime":1592392146881}
[7:09:06 pm] [Analyzer] [Info] ==> {"id":"234","method":"edit.getAvailableRefactorings","params":{"file":"E:\\flutter_projects\\expense_tracker\\lib\\widgets\\chart.dart","length":0,"offset":238},"clientRequestTime":1592392146881}
[7:09:07 pm] [Analyzer] [Info] ==> {"id":"235","method":"edit.getFixes","params":{"file":"E:\\flutter_projects\\expense_tracker\\lib\\widgets\\chart.dart","offset":233},"clientRequestTime":1592392147277}
[7:09:07 pm] [Analyzer] [Info] ==> {"id":"236","method":"edit.getAssists","params":{"file":"E:\\flutter_projects\\expense_tracker\\lib\\widgets\\chart.dart","length":0,"offset":233},"clientRequestTime":1592392147277}
[7:09:07 pm] [Analyzer] [Info] ==> {"id":"237","method":"edit.getAvailableRefactorings","params":{"file":"E:\\flutter_projects\\expense_tracker\\lib\\widgets\\chart.dart","length":0,"offset":233},"clientRequestTime":1592392147278}
[7:09:07 pm] [Analyzer] [Info] ==> {"id":"238","method":"edit.format","params":{"file":"E:\\flutter_projects\\expense_tracker\\lib\\widgets\\chart.dart","lineLength":80,"selectionLength":0,"selectionOffset":0},"clientRequestTime":1592392147481}
[7:09:09 pm] [Analyzer] [Info] ==> {"id":"239","method":"edit.getFixes","params":{"file":"E:\\flutter_projects\\expense_tracker\\lib\\widgets\\chart.dart","offset":233},"clientRequestTime":1592392149400}
[7:09:09 pm] [Analyzer] [Info] ==> {"id":"240","method":"edit.getAssists","params":{"file":"E:\\flutter_projects\\expense_tracker\\lib\\widgets\\chart.dart","length":0,"offset":233},"clientRequestTime":1592392149400}
[7:09:09 pm] [Analyzer] [Info] ==> {"id":"241","method":"edit.getAvailableRefactorings","params":{"file":"E:\\flutter_projects\\expense_tracker\\lib\\widgets\\chart.dart","length":0,"offset":233},"clientRequestTime":1592392149401}
[7:09:10 pm] [Analyzer] [Info] ==> {"id":"242","method":"edit.getFixes","params":{"file":"E:\\flutter_projects\\expense_tracker\\lib\\widgets\\chart.dart","offset":224},"clientRequestTime":1592392150193}
[7:09:10 pm] [Analyzer] [Info] ==> {"id":"243","method":"edit.getAssists","params":{"file":"E:\\flutter_projects\\expense_tracker\\lib\\widgets\\chart.dart","length":0,"offset":224},"clientRequestTime":1592392150194}
[7:09:10 pm] [Analyzer] [Info] ==> {"id":"244","method":"edit.getAvailableRefactorings","params":{"file":"E:\\flutter_projects\\expense_tracker\\lib\\widgets\\chart.dart","length":0,"offset":224},"clientRequestTime":1592392150194}
[7:09:10 pm] [Analyzer] [Info] ==> {"id":"245","method":"edit.getFixes","params":{"file":"E:\\flutter_projects\\expense_tracker\\lib\\widgets\\chart.dart","offset":233},"clientRequestTime":1592392150825}
[7:09:10 pm] [Analyzer] [Info] ==> {"id":"246","method":"edit.getAssists","params":{"file":"E:\\flutter_projects\\expense_tracker\\lib\\widgets\\chart.dart","length":0,"offset":233},"clientRequestTime":1592392150826}
[7:09:10 pm] [Analyzer] [Info] ==> {"id":"247","method":"edit.getAvailableRefactorings","params":{"file":"E:\\flutter_projects\\expense_tracker\\lib\\widgets\\chart.dart","length":0,"offset":233},"clientRequestTime":1592392150826}
Wed Jun 17 2020 [19:09:23 GMT+0800 (Philippine Standard Time)] Log file ended
```

**Comment by DanTup** [comment] 2020-06-17 11:32
It looks like the analysis server is not responding at all. Could you try using the [dart.analyerLogFile](https://dartcode.org/docs/logging/#analyzer) setting to capture a full log of what's going on with the server?

- Add that VS Code user setting to point to a log file path
- Reproduce the issue
- Attach a copy of that log file

Note: The log file may include parts of the source code you're editing.

**Comment by jhayg12** [comment] 2020-06-17 12:07
On my first attempt right after I've added the path for the analyzer file it works as expected no errors were found.
[analyzer.txt](https://github.com/Dart-Code/Dart-Code/files/4792265/analyzer.txt)

But when I tried it again it errors again.
[analyzer.txt](https://github.com/Dart-Code/Dart-Code/files/4792319/analyzer.txt)

**Comment by DanTup** [comment] 2020-06-17 13:28
Thanks! From the log I was able to repro this. It happens when you were typing and had this:

```dart
List<Map<>>
```

This causes the server to get stuck in a loop. It looks like there's already an open issue tracking this at https://github.com/dart-lang/sdk/issues/42229 so I'll close this as a dupe of that.

**Closed** 2020-06-17 13:30 UTC
Labels: upstream in dart / flutter
