### ISSUE TITLE
Multiple tests execution

### ISSUE THREAD

**Issue by grafovdenis** [Dart-Code/Dart-Code#4150] opened 2022-09-07 11:20 UTC
**Describe the bug**
Once you're trying to run test, which description contains variable or type used in other test, multiple tests would be executed.
This could be annoying if you're using some kind of BLoC/Redux actions, which types may be located in multiple test descriptions.

Simular issue in `/test` repo: https://github.com/dart-lang/test/issues/1760.
There we found out, that the plugin [could interprete](https://github.com/dart-lang/test/issues/1760#issuecomment-1238381218) expressions like `'is $Object'` incorrectly.

**To Reproduce**
Run `'is $Object'` test.

```dart
import 'package:test/test.dart';

class MyObj {
  final number = 10;

  bool foo() => true;
}

void main() {
  group('$MyObj', () {
    late MyObj myObj;

    setUp(() {
      myObj = MyObj();
    });

    test('is $Object', () {
      expect(myObj, isA<Object>());
    });

    test('foo returns true and is an $Object', () {
      expect(myObj.foo(), isTrue);

      expect(myObj, isA<Object>());
    });

    test('number equals 10', () {
      expect(myObj.number, equals(10));
    });
  });
}
```

**Expected behavior**
Running `'is $Object'` test, via IDE would execute only selected test.

**Screenshots**
<img width="645" alt="image" src="https://user-images.githubusercontent.com/20505376/188862970-fbac166c-df2f-4e71-8e37-88bd4f8bf70a.png">
It seems like plugin runs test like this.
<img width="785" alt="image" src="https://user-images.githubusercontent.com/20505376/188863524-d2c4222c-92de-48fd-9734-32950c659e4e.png">
Where `$Object` is an empty env. Which means, that we try to run test with `'is '` description, which also suits for the second test.

**Please complete the following information:**
 - Operating System and version: macOS 12.3.1 (21E258)
 - VS Code version: 1.71.0
 - Dart extension version: v3.48.2
 - Dart/Flutter SDK version: 2.17.3

**Comment by DanTup** [comment] 2022-09-07 13:24
There are some known limitations in this area. When we run tests, we cannot use the literal name in the source if it contains variables:

```
% dart test test/dartcode4150_test.dart --plain-name "^\$MyObj is \$Object$"
No tests ran.                                                                                                                                                                                
No tests match "^$MyObj is $Object$".
```

We also cannot tell what `$MyObj` or `$Object` are to substitute their values, since they could be dynamic:

```dart
  final foo = DateTime.now().millisecond;
  group('$foo', () {
```

So right now, any variable is simple substitute with the regular expression pattern `.*` so it will match any value at runtime. This results in the behaviour that you see.

There are plans to improve this though, there were some changes made to `package:test` that will allow us to run tests by their line number. If we switch to this, we will be able to more accurately pinpoint a test to be run without relying on names that we can't compute the exact values for. That's being tracked in #4021, so I'll close this as a dupe of that. You can subscribe there for updates.

Thanks!

**Comment by DanTup** [comment] 2023-04-18 15:58
Re-opening this for tracking to ensure this issue is fixed by the upcoming support for running tests by lines.

**Closed** 2023-04-19 17:56 UTC
Labels: is enhancement, in testing

**Comment by DanTup** [comment] 2023-04-19 18:03
In the next release (and the pre-release version just pushed today - v3.63.20240419), you can choose to have tests executed using their line numbers rather than their names. This fixes a number of issues including this one, caused by not always being able to statically compute the exact name of a test. 

![Test Invocation settings](https://user-images.githubusercontent.com/1078012/233161136-294c72e9-5a28-489b-bfc0-cd786636233c.png)

Please let me know if you find any issues with this functionality!
