### ISSUE TITLE
"Service protocol connection closed" when writing anonymous function into debug console while paused on breakpoint

### ISSUE THREAD

**Issue by ristiisa** [Dart-Code/Dart-Code#2392] opened 2020-04-23 12:10 UTC
I'm experiencing an issue under macOS. When the execution is paused on a breakpoint and I use an anonymous function in debug console the debug session is closed.

`(()=>1)()` works
`[1, 2, 3].map((e)=>e)` crash

```
[1, 2, 3].map(print)
[+18736 ms] Notification from VM: {streamId: Stdout, event: {type: Event, kind: WriteEvent, isolate: {type: @Isolate, id: isolates/46763897351023, name: main, number: 46763897351023}, timestamp: 1587643517854, bytes: Zmx1dHRlcjogMQ==}}
MappedListIterable ((null, null, null))
[   +2 ms] Notification from VM: {streamId: Stdout, event: {type: Event, kind: WriteEvent, isolate: {type: @Isolate, id: isolates/46763897351023, name: main, number: 46763897351023}, timestamp: 1587643517854, bytes: Cg==}}
[        ] Notification from VM: {streamId: Stdout, event: {type: Event, kind: WriteEvent, isolate: {type: @Isolate, id: isolates/46763897351023, name: main, number: 46763897351023}, timestamp: 1587643517854, bytes: Zmx1dHRlcjogMg==}}
[        ] Notification from VM: {streamId: Stdout, event: {type: Event, kind: WriteEvent, isolate: {type: @Isolate, id: isolates/46763897351023, name: main, number: 46763897351023}, timestamp: 1587643517854, bytes: Cg==}}
[        ] Notification from VM: {streamId: Stdout, event: {type: Event, kind: WriteEvent, isolate: {type: @Isolate, id: isolates/46763897351023, name: main, number: 46763897351023}, timestamp: 1587643517854, bytes: Zmx1dHRlcjogMw==}}
[        ] Notification from VM: {streamId: Stdout, event: {type: Event, kind: WriteEvent, isolate: {type: @Isolate, id: isolates/46763897351023, name: main, number: 46763897351023}, timestamp: 1587643517854, bytes: Cg==}}
[        ] flutter: 1
[   +1 ms] flutter: 2
[        ] flutter: 3
(()=>1)()
1
[1, 2, 3].map((e)=>e)
[+58599 ms] Service protocol connection closed.
[        ] Lost connection to device.
[   +1 ms] DevFS: Deleting filesystem on the device (file:///private/var/mobile/Containers/Data/Application/25FDCE81-E96B-4A1C-B39C-28E263E5F709/tmp/blankdzIk3q/blank/)
[        ] Sending to VM service: _deleteDevFS({fsName: blank})
[ +257 ms] Ignored error while cleaning up DevFS: TimeoutException after 0:00:00.250000: Future not completed
Exited (sigterm)
Canceled
```

```flutter doctor -v
[✓] Flutter (Channel stable, v1.12.13+hotfix.9, on Mac OS X 10.15.3 19D76, locale en-EE)
    • Flutter version 1.12.13+hotfix.9 at /Users/silver/flutter
    • Framework revision f139b11009 (3 weeks ago), 2020-03-30 13:57:30 -0700
    • Engine revision af51afceb8
    • Dart version 2.7.2

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/setup/#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, set ANDROID_HOME to that location.
      You may also want to add it to your PATH environment variable.


[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.9.1

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/setup/#android-setup for detailed instructions).

[✓] VS Code (version 1.44.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.9.1

[✓] Connected device (1 available)
    • Ingmar’s iPhone • 00008030-000269E13EBA802E • ios • iOS 13.3.1

! Doctor found issues in 2 categories.
```

**Comment by DanTup** [comment] 2020-04-23 14:02
In a simple Flutter app, I can't reproduce this here:

![Screenshot 2020-04-23 at 15 01 13](https://user-images.githubusercontent.com/1078012/80107668-4b57cd00-8573-11ea-85bf-a5061c730d00.png)

- Does it reproduce across any app (eg. if you create a new one with `**Flutter: New Project**)?
- Does it repro if you run a simple Dart script (no Flutter)
- Does it repro if you (temporarily) switch to the Flutter master channel?

**Comment by salarelv** [comment] 2020-04-23 17:36
I got the following error:
(()=>1)()
1
[1, 2, 3].map((e)=>e)

===== CRASH =====
si_signo=Segmentation fault: 11(11), si_code=1, si_addr=0xfffffffd12948308
version=2.5.0 (Fri Sep 6 20:10:36 2019 +0200) on "macos_x64"
thread=9995, isolate=main(0x7ff41b80a400)
  pc 0x000000010ecbcdb3 fp 0x0000700003b7a410 dart::kernel::MetadataHelper::ScanMetadataMappings()
  pc 0x000000010ecbcfc5 fp 0x0000700003b7a460 dart::kernel::MetadataHelper::GetNextMetadataPayloadOffset(long)
  pc 0x000000010ecbdc91 fp 0x0000700003b7a4b0 dart::kernel::ProcedureAttributesMetadataHelper::GetProcedureAttributes(long)
  pc 0x000000010ecc6519 fp 0x0000700003b7a620 dart::kernel::ScopeBuilder::BuildScopes()
  pc 0x000000010ea9ff05 fp 0x0000700003b7a880 dart::ParsedFunction::EnsureKernelScopes()
  pc 0x000000010ec925ce fp 0x0000700003b7a8c0 dart::kernel::StreamingFlowGraphBuilder::ParseKernelASTFunction()
  pc 0x000000010ec9215d fp 0x0000700003b7aae0 dart::kernel::StreamingFlowGraphBuilder::BuildGraph()
  pc 0x000000010eca6dd3 fp 0x0000700003b7ad70 dart::kernel::FlowGraphBuilder::BuildGraph()
  pc 0x000000010ecd5f14 fp 0x0000700003b7af60 dart::DartCompilationPipeline::BuildFlowGraph(dart::Zone*, dart::ParsedFunction*, dart::ZoneGrowableArray<dart::ICData const*>*, long, bool)
  pc 0x000000010ecd7547 fp 0x0000700003b7b570 dart::CompileParsedFunctionHelper::Compile(dart::CompilationPipeline*)
  pc 0x000000010ecd880b fp 0x0000700003b7b750 dart::CompileFunctionHelper(dart::CompilationPipeline*, dart::Function const&, bool, long)
  pc 0x000000010ecd81ec fp 0x0000700003b7b800 dart::Compiler::CompileFunction(dart::Thread*, dart::Function const&)
  pc 0x000000010ecd64bc fp 0x0000700003b7b8b0 dart::DRT_CompileFunction(dart::NativeArguments)
  pc 0x0000000110601108 fp 0x0000700003b7b8f8 Unknown symbol
  pc 0x0000000110601184 fp 0x0000700003b7b928 Unknown symbol
  pc 0x000000011488a8fa fp 0x0000700003b7b968 Unknown symbol
  pc 0x000000011488a744 fp 0x0000700003b7b9a8 Unknown symbol
  pc 0x000000011488a545 fp 0x0000700003b7b9e8 Unknown symbol
  pc 0x00000001148b0382 fp 0x0000700003b7ba40 Unknown symbol
  pc 0x00000001148aeaa7 fp 0x0000700003b7bac0 Unknown symbol
  pc 0x00000001148ae04e fp 0x0000700003b7bb58 Unknown symbol
  pc 0x00000001148adafe fp 0x0000700003b7bba0 Unknown symbol
  pc 0x000000011060166c fp 0x0000700003b7bc08 Unknown symbol
  pc 0x000000010e986f91 fp 0x0000700003b7bcc0 dart::DartEntry::InvokeFunction(dart::Function const&, dart::Array const&, dart::Array const&, unsigned long)
  pc 0x000000010ea5f55f fp 0x0000700003b7bd10 dart::InvokeInstanceFunction(dart::Instance const&, dart::Function const&, dart::String const&, dart::Array const&, dart::Array const&, bool, dart::TypeArguments const&)
  pc 0x000000010ea5fd4b fp 0x0000700003b7bda0 dart::Instance::Invoke(dart::String const&, dart::Array const&, dart::Array const&, bool, bool) const
  pc 0x000000010eb19917 fp 0x0000700003b7be50 dart::Invoke(dart::Thread*, dart::JSONStream*)
  pc 0x000000010eb0f39b fp 0x0000700003b7bfc0 dart::Service::InvokeMethod(dart::Isolate*, dart::Array const&, bool)
  pc 0x000000010eb0f9c7 fp 0x0000700003b7c000 dart::Service::HandleIsolateMessage(dart::Isolate*, dart::Array const&)
  pc 0x000000010e9c46bf fp 0x0000700003b7c210 dart::IsolateMessageHandler::HandleMessage(std::__1::unique_ptr<dart::Message, std::__1::default_delete<dart::Message> >)
  pc 0x000000010e9f6a2e fp 0x0000700003b7c280 dart::MessageHandler::HandleMessages(dart::MonitorLocker*, bool, bool)
  pc 0x000000010e9f6de4 fp 0x0000700003b7c2c0 dart::MessageHandler::HandleOOBMessages()
  pc 0x000000010ed75cad fp 0x0000700003b7c360 Dart_HandleServiceMessages
  pc 0x000000010e9cb556 fp 0x0000700003b7c3b0 dart::Isolate::PauseEventHandler()
  pc 0x000000010e98dfaf fp 0x0000700003b7c550 dart::Debugger::Pause(dart::ServiceEvent*)
  pc 0x000000010e99ad10 fp 0x0000700003b7c680 dart::Debugger::SignalPausedEvent(dart::ActivationFrame*, dart::Breakpoint*)
  pc 0x000000010e99b8b6 fp 0x0000700003b7c700 dart::Debugger::PauseBreakpoint()
  pc 0x000000010eaffa1d fp 0x0000700003b7c890 dart::DRT_BreakpointRuntimeHandler(dart::NativeArguments)
  pc 0x0000000110601108 fp 0x0000700003b7c8d0 Unknown symbol
  pc 0x00000001106021a2 fp 0x0000700003b7c908 Unknown symbol
  pc 0x00000001148ad444 fp 0x0000700003b7c950 Unknown symbol
  pc 0x00000001148ad2eb fp 0x0000700003b7c990 Unknown symbol
  pc 0x00000001148ad157 fp 0x0000700003b7c9c8 Unknown symbol
  pc 0x00000001148ac37f fp 0x0000700003b7ca10 Unknown symbol
  pc 0x000000011488a8fa fp 0x0000700003b7ca50 Unknown symbol
  pc 0x00000001148ac04e fp 0x0000700003b7ca88 Unknown symbol
  pc 0x000000011060166c fp 0x0000700003b7caf8 Unknown symbol
  pc 0x000000010e986f91 fp 0x0000700003b7cbb0 dart::DartEntry::InvokeFunction(dart::Function const&, dart::Array const&, dart::Array const&, unsigned long)
  pc 0x000000010e98a280 fp 0x0000700003b7cc10 dart::DartLibraryCalls::HandleMessage(dart::Object const&, dart::Instance const&)
  pc 0x000000010e9c4523 fp 0x0000700003b7ce20 dart::IsolateMessageHandler::HandleMessage(std::__1::unique_ptr<dart::Message, std::__1::default_delete<dart::Message> >)
  pc 0x000000010e9f68cd fp 0x0000700003b7ce90 dart::MessageHandler::HandleMessages(dart::MonitorLocker*, bool, bool)
  pc 0x000000010e9f70a6 fp 0x0000700003b7cf00 dart::MessageHandler::TaskCallback()
  pc 0x000000010eb4629d fp 0x0000700003b7cf30 dart::ThreadPool::Worker::Loop()
  pc 0x000000010eb460f0 fp 0x0000700003b7cf70 dart::ThreadPool::Worker::Main(unsigned long)
  pc 0x000000010ea9e9e1 fp 0x0000700003b7cfb0 dart::ThreadStart(void*)
  pc 0x00007fff72c9fe65 fp 0x0000700003b7cfd0 _pthread_start
  pc 0x00007fff72c9b83b fp 0x0000700003b7cff0 thread_start
-- End of DumpStackTrace
Exited (sigabrt)
Canceled

---------------------

Taavis-Air:temp taavi$ flutter doctor -v
[✓] Flutter (Channel stable, v1.9.1+hotfix.6, on Mac OS X 10.15.3 19D76, locale en-EE)
    • Flutter version 1.9.1+hotfix.6 at /Users/taavi/flutter
    • Framework revision 68587a0916 (7 months ago), 2019-09-13 19:46:58 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/setup/#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, set ANDROID_HOME to that location.
      You may also want to add it to your PATH environment variable.


 
[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.8.4

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/setup/#android-setup for detailed instructions).

[✓] VS Code (version 1.43.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.9.1

**Comment by ristiisa** [comment] 2020-04-24 12:31
> * Does it reproduce across any app (eg. if you create a new one with `**Flutter: New Project**)?
Yes

> * Does it repro if you (temporarily) switch to the Flutter master channel?
No. It does not repro at master 1.18.0-7.0.pre.46

**Comment by DanTup** [comment] 2020-05-04 16:32
If this isn't happening on master, it may have been fixed. You could try the beta or dev channels if you don't want to use master, as the fix (if fixed) may have made it there.

I did find a (still open) VM issue about it here:

https://github.com/dart-lang/sdk/issues/41043

I'll close this as a dupe of that, since it's a VM issue and not related to the VS Code extension. Thanks!

**Closed by DanTup** 2020-05-04 16:32 UTC
Labels: awaiting info
