### ISSUE TITLE
Adopt SnippetString API

### ISSUE THREAD

**Issue by jrieken** [Dart-Code/Dart-Code#216] opened 2016-11-17 13:26 UTC
With the December release VS Code will have real API to define a CompletionItem that is inserted as snippet, for details see https://github.com/Microsoft/vscode/issues/3210. 

In short, we now support a subset of the more common TextMate syntax: `$1`, `$2` etc define tabstops, `${1:value}` and `${2:this is${3:nested}}` placeholders, and `$0` is for the final tabstop. 

The API for this is contained in a new type [`SnippetString`](https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts#L2035). It can be used as the `insertText` of a [CompletionItem](https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts#L2364).

During a transition phase we will still support the internal, unspecified snippet syntax your extension is using but eventually remove it (roughly 2 or 3 milestones from now).

**Comment by DanTup** [comment] 2016-11-17 13:35
Great, thanks for the heads up!

**Comment by DanTup** [comment] 2016-12-02 11:08
@jrieken Can you confirm when this will be in the stable build? You said in December release here, though https://github.com/Microsoft/vscode/issues/3210 is in the November milestone. Thanks!

**Comment by jrieken** [comment] 2016-12-02 15:11
Confirmed

**Comment by DanTup** [comment] 2016-12-15 09:06
@jrieken 

> During a transition phase we will still support the internal, unspecified snippet syntax your extension is using but eventually remove it (roughly 2 or 3 milestones from now).

I've had a report that the old behaviour is now resulting in underscores (see #234), so I don't think this continued working the way you expected?

It's probably not worth changing anything, I'll try and migrate to this tonight/tomorrow and push out a fix that requires 1.8. It does mean anyone upgrading to Code 1.8 will get a bad experience until they then also update Dart Code.

**Comment by DanTup** [comment] 2016-12-15 09:17
@jrieken Scratch that - our completion text has an underscore in it! Possibly something changed in 1.8 that made it appear (at least, it's reported to only have started in 1.8) but since it's in the string, this seems like our bug (or the Dart analyzers). I'll dig into it tonight, you can ignore this :-)

**Comment by DanTup** [comment] 2016-12-15 09:19
(ugh, re-posting this as I mis-interpreted the comment in the other case)...

@jrieken

> During a transition phase we will still support the internal, unspecified snippet syntax your extension is using but eventually remove it (roughly 2 or 3 milestones from now).

I've had a report that the old behaviour is now resulting in underscores (see #234), so I don't think this continued working the way you expected?

It's probably not worth changing anything, I'll try and migrate to this tonight/tomorrow and push out a fix that requires 1.8. It does mean anyone upgrading to Code 1.8 will get a bad experience until they then also update Dart Code.

**Comment by DanTup** [comment] 2016-12-15 17:17
I think the issue is that the internal API used underscore as the final cursor position (see https://github.com/Microsoft/vscode/issues/6874#issuecomment-235606255) but in 1.8 it renders a real underscore.

**Closed** 2016-12-15 17:56 UTC
Labels: refactor / technical
