### ISSUE TITLE
Closing tag labels appear before code folds

### ISSUE THREAD

**Issue by Skylled** [Dart-Code/Dart-Code#430] opened 2017-10-05 14:42 UTC
When folding a code section that contains a closing tag, the label is added to the front of the fold.

Interestingly, the label is clickable and unfolds the section.

My personal expectation is to have the tag hidden until I decide to unfold.

![Screenshot](https://user-images.githubusercontent.com/1078012/31816001-820f0ea4-b586-11e7-9467-bd832cc41250.png)

**Comment by DanTup** [comment] 2017-10-20 10:07
Sorry, thought I'd added a note on here!

I think this might not be fixable until MS re-do how decorations work (https://github.com/Microsoft/vscode/issues/34441) but I'll have a look.

**Comment by DanTup** [comment] 2017-11-17 12:39
I believe this was fixed in Code (https://github.com/Microsoft/vscode/pull/36410). I can't reproduce it in the latest; but let me know if you can!

**Closed by DanTup** 2017-11-17 12:39 UTC
Labels: in editor, is bug
