### ISSUE TITLE
Typedef (Callback) autocomplete

### ISSUE THREAD

**Issue by nizwar** [Dart-Code/Dart-Code#2240] opened 2020-01-30 12:43 UTC
Greeting sir,
can you make it posible? make typedef completion, i think it'll help peoples alot.
I know this question already asked on #1526, #1551 and i still can't find / you still don't figure the solution.

<a href="https://s5.gifyu.com/images/ezgif-6-f642eb04677f.gif"><img src="https://s5.gifyu.com/images/ezgif-6-f642eb04677f.gif"  /></a>
typedef completion is work when you add @required into constructor, and i think you can make it posible too right? (without @required)

**Comment by DanTup** [comment] 2020-02-24 15:51
As far as I can tell, this is a dupe of #1526 which I've just posted a comment on (as it seems to be in-progress directly in the Dart SDK). Thanks!

**Closed by DanTup** 2020-02-24 15:51 UTC
