### ISSUE TITLE
Trigger hot-reload and dartanalyzer on flutter sources change

### ISSUE THREAD

**Issue by rrousselGit** [Dart-Code/Dart-Code#680] opened 2018-03-10 21:59 UTC
I discovered the other day that *hot reload* works even when editing flutter sources from another project.
That's really cool for contribution. But Dart Code doesn't handle it nicely for now.

Few things are missing :

- when having `hotReloadOnSave` to true, modifying flutter sources should trigger a hot reload.
- dartanalyzer doesn't run on flutter source when opening an external project.
- dartanalyzer within the opened project doesn't detect flutter changes ; unless window is reloaded.
- breakpoints inside flutter works ; but pressing f10 return to the project instead of just going by one line.

With these fixed we'd have a super cool contributing workflow.

**Comment by DanTup** [comment] 2018-03-10 22:09
> when having `hotReloadOnSave` to true, modifying flutter sources should trigger a hot reload.

Can you clarify what you mean by "modifying flutter sources"? Are you modifying files from packages in the pubcache? (If so, I don't think that's a great workflow?)

> dartanalyzer doesn't run on flutter source when opening an external project.

What do you mean by "opening an external project"?

> dartanalyzer within the opened project doesn't detect flutter changes ; unless window is reloaded.

Again, I"m not sure what this means

> breakpoints inside flutter works ; but pressing f10 return to the project instead of just going by one line.

So what happened here? You F12'd into Flutter code and put a breakpoint in it, but when you step it jumps back out to user code? I suspect this may be related to having `dart.debugSdkLibraries` and `dart.debugExternalLibraries` set to false (the default), however I would expect once you were already inside them it should step normally. If you can confirm that's the problem I can do some digging.

**Comment by Phrohdoh** [comment] 2018-03-10 22:59
> when editing flutter sources from another project.

To me this sounds like changes made to the widgets defined in `flutter` proper such as `Text` (which I noticed a few days ago that you can hot-reload in which is amazing).

**Comment by rrousselGit** [comment] 2018-03-10 23:15
Sorry I was unclear.

When pressing f12 on a class coming from flutter sdk, we  open and edit the actual sources (cloned from github, not pubcache).
We can edit them, and triggering hot reload will use the edited sources.

Vscode also detect that we worked on flutter and propose to commit them (which is fine) : 

<img width="1084" alt="screen shot 2018-03-10 at 11 44 17 pm" src="https://user-images.githubusercontent.com/20165741/37247554-2075aa3a-24bd-11e8-822c-654409f13365.png">


____


Hum I'm not sure. I tested it on a temporary laptop in a different OS (windows).
After testing it on my current computer (mac) with debugSdk/external to both true and false I got :

> - when having hotReloadOnSave to true, modifying flutter sources should trigger a hot reload.

This works both with settings being true and false.
But didn't work on my other computer, windows problem ? (can't try for now)

> - dartanalyzer within the opened project doesn't detect flutter changes ; unless window is reloaded.

This one was about creating new classes or adding field to flutter and not seing them in the external projects until we reload vscode.

Same here, on mac I can see the added content correctly. Works both with settings being true or false. Another windows problem ?


> dartanalyzer doesn't run on flutter source when opening an external project.

When f12 to flutter code ; writing invalid code won't highlight it in red. But it seems autocomplete works.


> breakpoints inside flutter works ; but pressing f10 return to the project instead of just going by one line.

This one works with settings to true.
If you have them to false, pressing `Step over` will exit flutter sources.

**Comment by rrousselGit** [comment] 2018-03-10 23:17
I'll investigate for these possible windows problem as soon as I can.

In the end, on my current computer the only remaining issue is about analyzing flutter sources.

**Comment by DanTup** [comment] 2018-03-11 08:50
Oh, I understand better now - but why are you editing Flutter sources? Are you planning on contributing/committing the changes, or just doing it for debugging purposes?

The best thing to do if you want to modify Flutter sources is add it as a new workspace folder (File -> Add Folder to Workspace). That will cause it to be analyzed fully and all functionality should work. Normally we don't treat files "outside your workspace" as being files we care about (this is deliberate and I don't think we should change it, since the user can opt-in to it by adding workspace folders).

> This one works with settings to true.
> If you have them to false, pressing Step over will exit flutter sources.

Hmmm, I think I would consider this a bug, but I don't know if the VM team will agree! Can you raise as a separate issue? It's a little hard to track lots of different things in a single issue.

Same goes for the other things above, I think it'd be best to split these out into an issue per issue/feature so we can better understand what's to do (and prioritise/etc.).

**Comment by DanTup** [comment] 2018-04-27 14:03
@rrousselGit Are you able to answer some of the questions above to help us decide what to do?

**Comment by rrousselGit** [comment] 2018-04-27 14:39
Oh, yeah. Sorry I forgot

>  Are you planning on contributing/committing the changes ?

That's the idea.  I used the "workspace" as a workaround. 

Although I think `Dart Code` should handle edits inside Flutter folder without workspaces. As the reason we are using workspaces for mono-repo don't really apply to flutter sdk.

**Comment by DanTup** [comment] 2018-04-27 15:12
I must say I'm confused about what the issue is or what you're requesting.

If you've got a workspace open that has the flutter repo in it and your own app, then making changes to the flutter code I would expect to trigger hot reload. If it doesn't, I'll take that as a bug. If you're modifying flutter sources externally to the editor that is running the debug session (eg. you have to separate Code windows open, one flutter, one the running app) then that won't work, and I don't think we should make it.

Does that help? :D

**Comment by rrousselGit** [comment] 2018-04-27 15:29
The issue was about me expecting ` If you're modifying flutter sources externally to the editor that is running the debug session` to work.
And I followed your advice about using workspace as workaround.


My message earlier was me disagreeing on the ` I don't think we should make it.` about not using workspaces to edit flutter sources.


We don't want to add Flutter to the current workspace. As workspaces can be commited to share settings/extensions. 
While using a workspace for mono-repo is fine, adding flutter to the workspace would only work for **one** developper. 


So IMO, flutter-sdk should be an exception that doesn't require a workspace.

**Comment by DanTup** [comment] 2018-04-27 15:38
In order to support it from being edited externally, we'd need to set up file system watchers on all the packages, and it feels a bit weird (and very specific to your workflow).

> We don't want to add Flutter to the current workspace. As workspaces can be commited to share settings/extensions.
> While using a workspace for mono-repo is fine, adding flutter to the workspace would only work for one developper.

I don't entirely understand these two lines; they seem to contradict. You could create a `.code-workspace` file that has shared settings/extensions and has your project + Flutter and commit it if you want. If you don't, each dev can add Flutter into their work. Why don't you want to do that? It's easy to set up (File -> Add Folder To Workspace, browse to Flutter) and if I understand correctly, solves your problem (there are other advantages to having it in a single workspace too, like not having multiple analyzers running scanning the same files in Flutter).

**Comment by DanTup** [comment] 2018-04-27 16:07
That's all valid; however I think it is better fixed in Code. I previously opened an issue about having multiple settings files, but it was closed :(

https://github.com/Microsoft/vscode/issues/38902

However there are some similar issues still open:

https://github.com/Microsoft/vscode/issues/17634
https://github.com/Microsoft/vscode/issues/15909

And another option would be being able to use variables in the workspace file (maybe https://github.com/Microsoft/vscode/issues/2809 would solve it, but maybe that's just about settings).

I think your use case is very valid, but solving it how you're asking still leaves other issues - for example if you use the SDK Switcher we'll write the path into the workspace settings, so you'll already end up with paths you can't commit.

A possible workaround, though not ideal, is to symlink flutter into the same path on each machine, so you can add it to the workspace file.

**Comment by DanTup** [comment] 2018-05-19 10:37
Closing this as I think the solution is to add the flutter folder to your workspace if you want it to be tracked for reloading. Implementing it by watching all files would be technically complicated (and probably fragile) and I think it's a very uncommon use-case to not want to do this.

I do think Code could do better here though, and the issues linked above are probably the best way to resolve that. You should 👍 those issues to help them along!

**Closed by DanTup** 2018-05-19 10:37 UTC
Labels: awaiting info
