### ISSUE TITLE
Ghost analysis issues

### ISSUE THREAD

**Issue by JCKodel** [Dart-Code/Dart-Code#2381] opened 2020-04-21 22:30 UTC
I don't know if is a dart, dart-code or vscode issue, but the dart analyzer option `prefer_const_constructors` not always works.

For instance: `Icon(Icons.home)` should require const, but analyzer won't mark it (that one could be an analyzer bug).

Now, this example:

In my problems window SOMETIMES, it shows some problems:
![image](https://user-images.githubusercontent.com/379339/79920194-21cd6300-8406-11ea-881a-a7ef5bd9346c.png)

When I click on one of this problems, the editor opens, the error is highlighted with a blue snake underline for about half second, then the problem magically disappears (i.e.: analyzer seems to stop considering this a violation).

There are times, though, that the error remains, it's kinda intermittent. Notice that I NEVER leave this kind of error behind: if the editor mark it, I fix it right away. But sometimes the editor won't tell me nothing and the issue just appears after I reopen the project.

**Comment by DanTup** [comment] 2020-04-22 08:06
Are you able to reproduce this with the [analysis server log](https://dartcode.org/docs/logging/#analyzer) enabled? For the error to disappear when you open the file, it suggests it wasn't analyzed until we made it a "priority file" - but that makes me wonder how the error appeared in the first place.

Can you also check if there are any errors listed in the dev tools (Help -> Show Developer Tools)?

What's the structure of your open workspace look like? Is it s multi-root workspace? Are all the files in question inside the workspace (eg. not referenced as `path: ` dependencies from outside)? And do you only have one instance of VS Code open for these projects?

**Comment by JCKodel** [comment] 2020-04-24 00:34
This is the log (I opened the project, the error was shown in the problems output window, then I double click it, it opened the file with warning and the warning disappeared, then I fixed the warning (adding the const keyword)

Details: https://gist.github.com/JCKodel/96aa3bae71b1e473ad6a81563848608b

There are no errors in Developer Tools.

Nothing fancy on the project structure: just a plain Flutter project, no multi-root, all files are within my project (altough they are all imported as relative, i.e.: `include '../../some_file.dart';`)

Remember I told you this is a nasty bug? I try to record it and it suddenly working. ¬¬ In this video: https://youtu.be/c58JR_qEX8k you can see 3 yellow files (those files were bugged: the message was shown, I double click the message, the message was gone). After turning log on and trying to record, it just works normally >.< 

After turning the log off and restarting VSCode, now the error just don't appear anymore (not even if I open the file: the prefer_const_constructor simply doesn't work). 

I don't know what triggers the VSCode to correctly report those violations (even if it disappears just after I open the file).

**Comment by JCKodel** [comment] 2020-04-24 00:59
Aha! Busted on tape!

[Nasty bug recorded on tape](https://youtu.be/b4rYwBiFscQ)

**Comment by DanTup** [comment] 2020-05-04 17:36
@JCKodel sorry for the delay in responding! This log does seem strange, I can see the errors coming from the server, and then mysteriously being removed. Is it possible you could capture an [analysis server instrumentation log](https://dartcode.org/docs/logging/#analyzer-instrumentation)? That one is logged by the server and might include more information about what the server is doing during this period.

**Comment by JCKodel** [comment] 2020-05-05 05:18
> @JCKodel sorry for the delay in responding! This log does seem strange, I can see the errors coming from the server, and then mysteriously being removed. Is it possible you could capture an [analysis server instrumentation log](https://dartcode.org/docs/logging/#analyzer-instrumentation)? That one is logged by the server and might include more information about what the server is doing during this period.

I'll try as soon I see the bug again.

**Comment by DanTup** [comment] 2020-05-05 10:29
Ok, I looked again and remembered I'd seen complaints about this lint before. I found this:

https://github.com/dart-lang/sdk/issues/36866

Do you see it with any other lints, or could it be that?

**Comment by DanTup** [comment] 2020-05-05 10:32
Also this:

https://github.com/dart-lang/linter/issues/1744

> We fixed an issue in analyzer that might be causing this one, but we cannot be sure, because we were not able to reproduce this one.
> https://github.com/dart-lang/sdk/commit/532f43dcb2499a532e53e1afdd43a89b0ad83bf1

That fix in in the v2.9.0 (currently pre-release) SDKs, so it may be worth seeing if the problem goes away with those.

**Comment by DanTup** [comment] 2020-10-01 07:28
@JCKodel are you still seeing this issue in >= v2.9.0 that inculdes the fix mentiond above?

**Comment by DanTup** [comment] 2020-10-27 11:52
Closing this as a suspected dupe of the issues mentioned above. If you still see it in an SDK that includes those changes, please shout!

**Closed** 2020-10-27 11:52 UTC
Labels: fixed in dart / flutter
