### ISSUE TITLE
VSCode Dart/Flutter not showing syntax errors or context specific code suggestions

### ISSUE THREAD

**Issue by marJanssen** [Dart-Code/Dart-Code#3089] opened 2021-01-22 14:26 UTC
Syntax errors are not showing anymore and I am not getting context specific code suggestions (Ctrl + Space) e.g. Constructor Parameter (Only standard code templates are shown).  

- I created a new Project to make sure it's not my project that is broken.
- I open the main.dart from the Counter Example Project.
- Press Ctrl + Space in MyHomePage Constructor to see code suggestions.
- e.g. Delete bracket to break code to see .

```
Dart Code extension: 3.18.1
Flutter extension: 3.18.1 (activated)

App: Visual Studio Code
Version: 1.52.1
Platform: linux

Workspace type: Flutter
Analyzer type: DAS
Multi-root?: false

Dart SDK:
    Loc: /home/myusername/Projects/flutter/sdk/flutter/bin/cache/dart-sdk
    Ver: 2.10.4
Flutter SDK:
    Loc: /home/myusername/Projects/flutter/sdk/flutter
    Ver: 1.22.5
```

In the Dart Extension Log I can also see some communication going on. When I produce a syntax error the formatter registers a error. I am guessing it is not correct that this three lists are always empty? "fixes":[], "assists":[], "kinds":[]

```
...
[1:35:55 PM] [Analyzer] [Info] <== {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
[1:35:55 PM] [Analyzer] [Info] <== {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":0,"uri":"package:fediverse_client/main.dart","items":[{"label":"MyHomePage","declaringLibraryUri":"package:fediverse_client/main.dart","element":{"kind":"CLASS","name":"MyHomePage","location":{"file":"/home/mario/Projects/flutter/fediverse_client/fediverse_client/lib/main.dart","offset":1248,"length":0,"startLine":34,"startColumn":7},"flags":0},"relevanceTags":["ElementKind.CLASS","package:fediverse_client/main.dart::MyHomePage","MyHomePage"]},{"label":"MyHomePage","declaringLibraryUri":"package:fediverse_client/main.dart","element":{"kind":"CONSTRUCTOR","name":"","location":{"file":"/home/mario/Projects/flutter/fediverse_client/fediverse_client/lib/main.dart","offset":1286,"length":0,"startLine":35,"startColumn":3},"flags":0,"parameters":"({Key key, this.title})","returnType":"MyHomePage"},"parameterNames":["key","title"],"parameterTypes":["Key",""],"relevanceTags":["ElementKind.CONSTRUCTOR","package:fediverse_client/main.dart::MyHomePage",""],"requiredParameterCount":0},{"label":"MyApp","declaringLibraryUri":"package:fediverse_client/main.dart","element":{"kind":"CLASS","name":"MyApp","location":{"file":"/home/mario/Projects/flutter/fediverse_client/fediverse_client/lib/main.dart","offset":82,"length":0,"startLine":7,"startColumn":7},"flags":0},"relevanceTags":["ElementKind.CLASS","package:fediverse_client/main.dart::MyApp","MyApp"]},{"label":"MyApp","declaringLibraryUri":"package:fediverse_client/main.dart","element":{"kind":"CONSTRUCTOR","name":"","location":{"file":"/home/mario/Projects/flutter/fediverse_client/fediverse_client/lib/main.dart","offset":-1,"length":0,"startLine":0,"startColumn":0},"flags":0,"parameters":"()","returnType":"MyApp"},"parameterNames":[],"parameterTypes":[],"relevanceTags":["ElementKind.CONSTRUCTOR","package:fediverse_client/main.dart::MyApp",""],"requiredParameterCount":0},{"label":"main","declaringLibraryUri":"package:fediverse_client/main.dart","elem…
[1:35:55 PM] [Analyzer] [Info] <== {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
[1:35:55 PM] [Analyzer] [Info] ==> {"id":"138","method":"edit.getFixes","params":{"file":"/home/mario/Projects/flutter/fediverse_client/fediverse_client/lib/main.dart","offset":71},"clientRequestTime":1611146155285}
[1:35:55 PM] [Analyzer] [Info] ==> {"id":"139","method":"edit.getAssists","params":{"file":"/home/mario/Projects/flutter/fediverse_client/fediverse_client/lib/main.dart","length":0,"offset":71},"clientRequestTime":1611146155286}
[1:35:55 PM] [Analyzer] [Info] ==> {"id":"140","method":"edit.getAvailableRefactorings","params":{"file":"/home/mario/Projects/flutter/fediverse_client/fediverse_client/lib/main.dart","length":0,"offset":71},"clientRequestTime":1611146155286}
[1:35:55 PM] [Analyzer] [Info] <== {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
[1:35:55 PM] [Analyzer] [Info] <== {"id":"138","result":{"fixes":[]}}
[1:35:55 PM] [Analyzer] [Info] <== {"id":"139","result":{"assists":[]}}
[1:35:55 PM] [Analyzer] [Info] <== {"id":"140","result":{"kinds":[]}}
[1:35:55 PM] [Analyzer] [Info] <== {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
[1:35:56 PM] [Analyzer] [Info] ==> {"id":"141","method":"edit.format","params":{"file":"/home/mario/Projects/flutter/fediverse_client/fediverse_client/lib/main.dart","lineLength":80,"selectionLength":0,"selectionOffset":0},"clientRequestTime":1611146156140}
[1:35:56 PM] [Analyzer] [Info] <== {"id":"141","error":{"code":"FORMAT_WITH_ERRORS","message":"Error during `edit.format`: source contains syntax errors."}}
[1:35:56 PM] [General] [Error] Error during `edit.format`: source contains syntax errors.
...
```

I checked also the Dart Processes running on my computer:

```
5040 ?        S      0:00 /bin/sh -c "/home/myusername/Projects/flutter/sdk/flutter/bin/cache/dart-sdk/bin/dart" "/home/myusername/Projects/flutter/sdk/flutter/bin/cache/dart-sdk/bin/snapshots/analysis_server.dart.snapshot" "--client-id=VS-Code" "--client-version=3.18.1"
   5041 ?        Sl     0:41 /home/myusername/Projects/flutter/sdk/flutter/bin/cache/dart-sdk/bin/dart /home/myusername/Projects/flutter/sdk/flutter/bin/cache/dart-sdk/bin/snapshots/analysis_server.dart.snapshot --client-id=VS-Code --client-version=3.18.1
   5065 ?        Sl     0:12 /home/myusername/Projects/flutter/sdk/flutter/bin/cache/dart-sdk/bin/dart --disable-dart-dev --packages=/home/myusername/Projects/flutter/sdk/flutter/packages/flutter_tools/.packages /home/myusername/Projects/flutter/sdk/flutter/bin/cache/flutter_tools.snapshot daemon
```

**Comment by DanTup** [comment] 2021-01-25 11:41
The thing to look for in the log is the `getSuggestions` request - that's what returns the code completions (it's not included in your log above so I can't see it).

Another thing to try is switching to LSP (with the `dart.previewLsp` setting), as the completion works slightly differently there and you might not see the issue.

If you can repro this on a simple new project (using the LSP preview) and can share the entire log (by emailing it to me at logs@dartcode.org), that might also help understand what's going on. Thanks!

**Comment by marJanssen** [comment] 2021-01-25 13:18
When I am activating: 'dart.previewLsp' I am getting this in my output window:

'[Error - 1:57:14 PM] Request textDocument/documentSymbol failed.
  Message: Invalid file path
  Code: -32003 
/home/myuser/Projects/flutter/fediverse_client/fediverse_client/lib/main.dart'

@DanTup I sent you a mail with log files for both cases Lsp preview activated and Lsp deactivated.

**Comment by DanTup** [comment] 2021-01-25 14:35
@marJanssen are you able to capture a full analysis server log with LSP enabled? You'll need to set the log file in the [dart.analyzerLogFile setting](https://dartcode.org/docs/logging/#analyzer). This will begin logging right at the start (whereas the log you sent was only started after the server was initialised).

When reproducing, please use a new project (created with `flutter create`) so I can try to use exactly the same code here.

**Comment by marJanssen** [comment] 2021-01-25 18:00
@DanTup Send you the log files for DAS and LSP with dart.analyzerLogFile path configured. Logs are from a default counter project.

**Comment by DanTup** [comment] 2021-01-26 12:14
@marJanssen when you reproduce this on a new `flutter create` project, can you clarify exactly what characters you're deleting to produce the syntax errors? I can see the errors in the logs, but I've not been able to reproduce it. It looks like you're deleting characters from line 34, but in my sample those are comments so I think something is out of sync.

Can you also check once it's in that state, if you save the file and then reload VS Code, does the issue persist? If so, can you send me an exact copy of that file as it is? Thanks!

**Comment by DanTup** [comment] 2021-01-26 12:23
Actually, looking again - there's an `"isAnalyzing":true` message in the log, and no `"isAnalyzing":false`. I presume this means you see "Analyzing..." stuck on the status bar?

There are two common situations where I've seen this occur before:

1. A _very_ large project (for example with a huge node_modules folder) that took a very long time to analyze
2. A project that had circular symlinks, which resulted in the analyzer walking "down the tree" forever

I'm not sure either of those apply here (since the server is responding to requests afterwards), however I do see some suspicious things in the log, like this:

```
textDocument/publishDiagnostics","params":{"uri":"file:///home/mario/Projects/flutter/sdk/flutter/dev/benchmarks/macrobenchmarks/android/app/src
```

This looks like it's generating diagnostics for the Flutter SDKs code itself, yet as far as I can tell, you haven't opened anything in that folder explicitly. I'll do some more digging and see if I reproduce that.

**Comment by DanTup** [comment] 2021-01-26 12:25
Actually, the open `workspaceFolders` are truncated from the log file so I can't see. Do you actually have the Flutter SDK folder included in your open workspace? In theory, that shouldn't cause issues - however it could affect the performance.

If you do, I'd be interested to know if opening only the project folder without the SDK makes a difference.

**Comment by marJanssen** [comment] 2021-01-26 19:08
@DanTup I just send you my main.dart. I just checked the project and yes maybe while is was testing I added the sdk folder.
workspace file:
`{
	"folders": [
		{
			"path": "."
		},
		{
			"path": "../../sdk/flutter"
		}
	],
	"settings": {}
}`
But when I remove the path entry and restart VSCode the problem still exists.

**Comment by marJanssen** [comment] 2021-01-31 18:00
@DanTup  I also couldn't really find the problem. Maybe it was something with my old notebook. I was also very slow before it stopped working completely. I have a new notebook now and installed everything from scratch. I works fine now. So for me it would be OK to close the Issue. Thanks for all the effort you took into it.

**Comment by DanTup** [comment] 2021-02-01 11:22
Ok, sounds like there's not much we can do to troubleshoot any further if the issue is fixed on the new one. If you do see it come back though, please let me know!

**Closed by DanTup** 2021-02-01 11:22 UTC
Labels: awaiting info, is bug

**Comment by hansbak** [comment] 2023-07-06 23:18
I also had this problem, i found that the directory was disabled in the analysis_options.yaml with the line:

analyzer:
  exclude:
    - "dir_name/**"

**Comment by Bdempsey03** [comment] 2024-03-20 07:47
I had this same problem but my issue was that I had one file missing the ".dart" extension. I renamed the file and everything started to work again.
