### ISSUE TITLE
Pubspec doesn't populate the available versions anymore

### ISSUE THREAD

**Issue by HerrNiklasRaab** [Dart-Code/Dart-Code#3731] opened 2021-12-14 11:11 UTC
[Dart-Code-Log-2021-11-02 11-59-22.txt](https://github.com/Dart-Code/Dart-Code/files/7711039/Dart-Code-Log-2021-11-02.11-59-22.txt)

https://user-images.githubusercontent.com/28401593/145987166-148e3a1c-37ae-4641-9031-35d63bd54e87.mov

**Comment by DanTup** [comment] 2021-12-14 14:42
Nope, this is totally on me. In the case where there's a space at the end of the line, the completion item returned has a range starting from the next line, which I guess is causing VS Code to filter it out.

<img width="1648" alt="Screenshot 2021-12-14 at 14 41 14" src="https://user-images.githubusercontent.com/1078012/146019898-a0c5b280-1b92-4888-91a4-dbf22346acd4.png">

**Comment by DanTup** [comment] 2021-12-14 15:59
@bwilkerson I'm having trouble reproducing this in a test (although I can reproduce it reliably through VS Code) and wonder if you have any ideas that might help understand why. Here's the behaviour I'm seeing:

- open `pubspec.yaml`
- send completion at the end of a line that contains a dependency `"  foo:"` (with no trailing whitespace)
- server returns expected results (the version numbers for package `foo`)
- cancel the completion (don't accept any value)
- modify the pubspec to add trailing space after the colon: `"  foo: "`
- send completion at the new offset (after the space)
- server returns the correct completion results, but the line/col for the edit are wrong (which causes VS Code to filter them out because they're not on the correct line)

The reason the offsets of the edits are wrong seems to be that the `LineInfo` we get seems to be stale. The `lineStarts` for it are the same for both completion requests even though the file had a character inserted in the middle between those requests. Unfortunately I can't reproduce this in a test (nor can I currently attach a debugger to VS Code to debug the live instance due to another bug) so it's difficult to step through.

The `LineInfo` is fetched through this code here and I'm now wondering whether I should be asking a "Dart analysis driver" for non-Dart files to get their `LineInfo`s? Perhaps that's the issue and they're not being invalidated? Although that wouldn't explain why it seems ok in the tests. If that's not correct, what's the correct way to get a `LineInfo` for a YAML file? (should it just be built from the content in the `resourceProvider`)?

https://github.com/dart-lang/sdk/blob/979f3ea79ee188ec2e0c039a3186ebd28e0f636c/pkg/analysis_server/lib/src/lsp/lsp_analysis_server.dart#L264-L270

**Comment by bwilkerson** [comment] 2021-12-14 16:28
> I'm now wondering whether I should be asking a "Dart analysis driver" for non-Dart files to get their LineInfos? Perhaps that's the issue and they're not being invalidated?

That seems quite likely to be the case.

> (should it just be built from the content in the resourceProvider)?

Yes. I'd try making that change to see whether that fixes the problem.

Is this only a problem for LSP, or does this also happen in the legacy protocol?

**Comment by DanTup** [comment] 2021-12-14 17:08
> Is this only a problem for LSP, or does this also happen in the legacy protocol?

Just LSP, but we don't need to translate positions using `LineInfo`s for the legacy protocol (we translate them on the VS Code side in the client).

> Yes. I'd try making that change to see whether that fixes the problem.

Seems like it does! :) I'm not sure why I couldn't repro in tests, I guess something must have been different. Sounds like the old code is bad anyway, so I'll just fix this. Seems like this could have affected any non-Dart file, so not just YAML here but also files being handled by plugins.

**Comment by DanTup** [comment] 2021-12-29 11:48
Fixed by https://github.com/dart-lang/sdk/commit/295aea1eda54a328ff68fe1c38c74fb0a9028c52.

**Closed by DanTup** 2021-12-29 11:48 UTC
Labels: is bug, in editor, in lsp/analysis server
