### ISSUE TITLE
Add a configuration option to configure the suggested behavior of the code snippet and optimize how it is recommended

### ISSUE THREAD

**Issue by czfadmin** [Dart-Code/Dart-Code#1194] opened 2018-09-04 13:25 UTC
Issue Type: <b>Feature Request</b>

Add a configuration option to configure the suggested behavior of the code snippet and optimize how it is recommended.I'm not sure about it, but I'm marked in red in the GIF below.

![1](https://user-images.githubusercontent.com/13393959/45033388-f8bc5b00-b086-11e8-84e2-65ab991ea2fc.png)

Also, in the default settings, this will result in the inability to get the suggested code snippet for the Dart extension the next time you type the code. 
The specific situation depends on the following GIF. (After I type<code>Scaffold</code>, press the Enter key, I want to enter the <code>body</code>, and I want to get suggestions, but I don't have the desired result.)

![dart_2](https://user-images.githubusercontent.com/13393959/45033790-2f46a580-b088-11e8-9d53-baa5c5cff3fc.gif)

Extension version: 2.18.0
VS Code version: Code - Insiders 1.27.0-insider (7b9afc4196bda60b0facdf62cfc02815509b23d6, 2018-09-03T09:14:29.879Z)
OS version: Windows_NT x64 10.0.17134

**Comment by DanTup** [comment] 2018-09-04 13:49
I think this is a dupe of #1173, and may be a VS Code issue: Microsoft/vscode#43270

I so far haven't found a way to fix/workaround it so it may be worth adding comments/👍 to the VS Code case to see if we can make it more visible.

**Comment by DanTup** [comment] 2018-09-05 07:02
@czfadmin See https://github.com/Dart-Code/Dart-Code/issues/914 for discussion about a more flexible formatter (please add a 👍 to that issue if it's something you want to see).

**Comment by DanTup** [comment] 2018-10-18 09:44
Considering this fixed as part of #1173. (Not formatting work, that has another issue linked above).

**Closed by DanTup** 2018-10-18 09:44 UTC
