### ISSUE TITLE
While Using VS Code editor I am getting this message  while debugging please help me out

### ISSUE THREAD

**Issue by saipavankumarrampally** [Dart-Code/Dart-Code#1552] opened 2019-03-24 13:32 UTC
Message is Displayed as: 

`No suitable Android AVD system images are available. You may need to install these using sdkmanager, for example: sdkmanager "system-images;android-27;google_apis_playstore;x86".'

**Comment by DanTup** [comment] 2019-03-24 15:12
I assuming you're seeing this because you're trying to create an emulator? This message says that you don't have the AVD system images installed that Flutter wants to use. You can install them using the command in the message:

> sdkmanager "system-images;android-27;google_apis_playstore;x86"

Please let .me know if that works.

**Comment by tutu612** [comment] 2019-05-03 10:59
I also have this problem when I trying to make a new emulator.
however, I've already installed needed files .here is my emulator and images version.

- emulator                                    | 29.0.6     
- system-images;android-28;google_apis;x86_64 | 8          

And I also ensure all Hyper-V items enabled in my BIOS and system( windows 10 )

**Comment by DanTup** [comment] 2019-05-06 09:35
Can you please run the command `avdmanager create avd -n temp` and post the output here?

**Comment by DanTup** [comment] 2019-05-06 09:36
My guess is that you are missing the _playstore versions:

> system-images;android-27;google_apis_playstore;x86

**Comment by saipavankumarrampally** [comment] 2019-05-07 05:55
I got the message after running the command you've mentioned

Warning: File C:\Users\sai pavan\.android\repositories.cfg could not be loaded.
[=======================================] 100% Computing updates...

**Comment by DanTup** [comment] 2019-05-07 08:45
@saipavankumarrampally after running `sdkmanager "system-images;android-27;google_apis_playstore;x86"`, are you still seeing this issue?

If so, please run the command `avdmanager create avd -n temp` and post the output here. Thanks!

**Comment by saipavankumarrampally** [comment] 2019-05-07 12:56
after running above mentioned command this is what I got

Error: Package path (-k) not specified. Valid system image paths are:
system-images;android-28;google_apis;x86
system-images;android-27;google_apis_playstore;x86
null

**Comment by DanTup** [comment] 2019-05-07 12:58
@saipavankumarrampally this should've solved the original issue with creating emulators. Are you still seeing the original issue (and if so, exactly what steps are leading to it?)?

**Comment by DanTup** [comment] 2019-05-21 13:55
Closing this due to no update, but please let me know if you are still having this issue and we can get to the bottom of it.

**Comment by hashika2** [comment] 2019-07-12 15:44
No suitable Android AVD system images are available. You may need to install these using sdkmanager, for example: sdkmanager "system-images;android-27;google_apis_playstore;x86" please tel me how to solve this problem

**Comment by DanTup** [comment] 2019-07-15 12:18
@hashika2 have you tried the command in the message? Did it complete without errors?

```
sdkmanager "system-images;android-27;google_apis_playstore;x86"
```

**Comment by Infusive** [comment] 2019-07-30 08:20
Having the exact same issue, not resolved yet.

> Warning ... .android\repositories.cfg could not be loaded. ( for this i just created the blank file )

however I cannot add a new device emulator as it gives: 

> No suitable Android AVD system images are available. You may need to install these using sdkmanager, for example:
>   sdkmanager "system-images;android-27;google_apis_playstore;x86"

Output for avdmanager create avd -n temp is:

> Error: Package path (-k) not specified. Valid system image paths are:
> system-images;android-28;google_apis_playstore;x86
> system-images;android-27;google_apis_playstore;x86
> null

Output for flutter doctor is:

> [flutter] flutter doctor
> Doctor summary (to see all details, run flutter doctor -v):
> [√] Flutter (Channel stable, v1.7.8+hotfix.4, on Microsoft Windows [Version 10.0.18362.239], locale en-US)
> [√] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
> [√] Android Studio (version 3.4)
> [√] VS Code (version 1.36.1)
> [!] Connected device
>     ! No devices available
> 
> ! Doctor found issues in 1 category.
> exit code 0

**Comment by DanTup** [comment] 2019-08-05 12:55
@Infusive Could you try posting the output of `which avdmanager` and `flutter doctor -v`?

Can you also confirm whether running `flutter emulator --create` directly gives the same message (try both in the VS Code integration terminal as well as externally).

**Comment by Infusive** [comment] 2019-08-07 09:24
@DanTup apologies for the delay, I only just noticed the message in email, I will revert back to you with the above later this evening. (currently 12:24 PM & at work)

**Comment by Infusive** [comment] 2019-08-12 19:46
@DanTup 
* I'm running on windows, no access to "which". I've installed android studio 3.4.2 version for this
flutter doctor -v
`[√] Flutter (Channel stable, v1.7.8+hotfix.4, on Microsoft Windows [Version 10.0.18362.239], locale en-US)
    • Flutter version 1.7.8+hotfix.4 at C:\Core\flutter
    • Framework revision 20e59316b8 (4 weeks ago), 2019-07-18 20:04:33 -0700
    • Engine revision fee001c93f
    • Dart version 2.4.0


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
    • Android SDK at C:\Users\Infusive\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.4)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 37.1.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[√] VS Code (version 1.37.0)
    • VS Code at C:\Users\Infusive\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.3.0

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.`

flutter emulator --create (This gives the same output for both internal and external terminal.
`Failed to create emulator 'flutter_emulator'.

No suitable Android AVD system images are available. You may need to install these using sdkmanager, for example:
  sdkmanager "system-images;android-27;google_apis_playstore;x86"

You can find more information on managing emulators at the links below:
  https://developer.android.com/studio/run/managing-avds
  https://developer.android.com/studio/command-line/avdmanager`

**Comment by DanTup** [comment] 2019-08-19 12:53
@Infusive do you get the same output from running:

````
avdmanager create avd -n temp
```

and

```
C:\Users\Infusive\AppData\Local\Android\sdk\tools\bin\avdmanager create avd -n temp
```

?

**Comment by Infusive** [comment] 2019-08-19 16:02
@DanTup: Running the requested within Visual Studio Code terminal and externally return the same results.

> **avdmanager create avd -n temp**
`Error: Package path (-k) not specified. Valid system image paths are:
null`

> **C:\Users\Infusive\AppData\Local\Android\sdk\tools\bin\avdmanager create avd -n temp**
`Error: Package path (-k) not specified. Valid system image paths are:
system-images;android-29;google_apis;x86
system-images;android-29;google_apis;x86_64
system-images;android-28;google_apis;x86
null`

after which I tried the below:

> **C:\Users\Infusive\AppData\Local\Android\sdk\tools\bin\avdmanager create avd -n temp -k "system-images;android-28;google_apis;x86" --force**
`arsing legacy package: C:\Users\Infusive\AppData\Local\Android\Sdk\.temp\PackageOperation01\unzip\platform-toolsParsing C:\Users\Infusive\AppData\Local\Android\Sdk\build-tools\28.0.3\package.xmlParsing C:\Users\Infusive\AppData\Local\Android\Sdk\build-tools\29.0.1\package.xmlParsing C:\Users\Infusive\AppData\Local\Android\Sdk\emulator\package.xmlParsing C:\Users\Infusive\AppData\Local\Android\Sdk\extras\google\auto\package.xmlParsing C:\Users\Infusive\AppData\Local\Android\Sdk\extras\intel\Hardware_Accelerated_Execution_Manager\package.xmlParsing C:\Users\Infusive\AppData\Local\Android\Sdk\patcher\v4\package.xmlParsing C:\Users\Infusive\AppData\Local\Android\Sdk\platform-tools\package.xmlParsing C:\Users\Infusive\AppData\Local\Android\Sdk\platforms\android-28\package.xmlParsing C:\Users\Infusive\AppData\Local\Android\Sdk\platforms\android-29\package.xmlParsing C:\Users\Infusive\AppData\Local\Android\Sdk\system-images\android-28\google_apis\x86\package.xmlParsing C:\Users\Infusive\AppData\Local\Android\Sdk\system-images\android-29\google_apis\x86\package.xmlParsing C:\Users\Infusive\AppData\Local\Android\Sdk\system-images\android-29\google_apis\x86_64\package.xmlParsing C:\Users\Infusive\AppData\Local\Android\Sdk\tools\package.xmlAuto-selecting single ABI x86
Do you wish to create a custom hardware profile? [no] no`

Now to be fair it did create an virtual machine from within visual studio code terminal, for now though I do feel like it is much less hassle/frustration to bootup android studio.
Below is how it looks from visual studio without doing the custom profile (I don't really know much about how to setup proper pixel 3 profile for example, but in AS it's two clicks away):
![image](https://user-images.githubusercontent.com/1739163/63280422-6b800f80-c2b3-11e9-933e-9103039db658.png)

**Comment by DanTup** [comment] 2019-08-19 17:08
```
avdmanager create avd -n temp
Error: Package path (-k) not specified.
Valid system image paths are: null
```

```
C:\Users\Infusive\AppData\Local\Android\sdk\tools\bin\avdmanager create avd -n temp
Error: Package path (-k) not specified.
Valid system image paths are:
  system-images;android-29;google_apis;x86
  system-images;android-29;google_apis;x86_64
  system-images;android-28;google_apis;x86
  null
```

Hmmmm, these giving different results makes me think you may have a different `avdmanager` on `PATH` than the one you expect. Can you try running `where avdmanager`? (I believe `where` is a rough equiv of `which` on Windows).

**Comment by Infusive** [comment] 2019-08-19 17:27
@DanTup >**where avdmanager**
`C:\Users\Infusive\Desktop\Android\sdk-tools-windows-4333796\tools\bin\avdmanager.bat`

I see your point, I tried to set up sdk tools after the fact, not sure what to do with this now though.

**Comment by DanTup** [comment] 2019-08-19 17:50
Aha, that explains that :-)

My recommendation would be to change any paths in your `PATH` environment variable that start with `C:\Users\Infusive\Desktop\Android\sdk-tools-windows-4333796` to instead have `C:\Users\Infusive\AppData\Local\Android\sdk\tools\bin\avdmanager` and then remove the one from your desktop (in the first instance you may wish to just rename it so nothing can find it, but you can easily put it back if things go awry).

You may also want to ensure Flutter doesn't point at that one (run `flutter config --machine` to see your config, and use `flutter config --android-sdk /path/to/sdk` to update it).

Once everything is on the same single version, then running

```
sdkmanager "system-images;android-27;google_apis_playstore;x86
```

should get you the bits you need for the emulator creation stuff to work. You should also check in Android SDK and make sure everything in the SDK manager there is up-to-date.

**Comment by Infusive** [comment] 2019-08-20 11:32
Done as you noted.

> **PS C:\..> flutter config --machine**
```
{
  "android-studio-dir": "C:\\Program Files\\Android\\Android Studio",
  "android-sdk": "C:\\Users\\Infusive\\AppData\\Local\\Android\\sdk"
}
```

Running:

> **PS C:\..> flutter config --machine**

```
{
  "android-studio-dir": "C:\\Program Files\\Android\\Android Studio",
  "android-sdk": "C:\\Users\\Infusive\\AppData\\Local\\Android\\sdk"
}
```

> **PS C:\..>sdkmanager "system-images;android-27;google_apis_playstore;x86"**

`sdkmanager : The term 'sdkmanager' is not recognized as the name of a cmdlet, function, script file, or operable program.`

> Changed PATH variable to point towards: %USERPROFILE%\AppData\Local\Android\Sdk\tools\bin

Running

> **PS C:\..> sdkmanager "system-images;android-27;google_apis_playstore;x86"**

`[=======================================] 100% Unzipping... x86/vendor.img`

After which if I click on "No Device" -> "Create Android Emulator" from whithin visual studio, this seems to be working now, let's see if it stays that way now.

Thank you @DanTup for all the help, have a great week :)

**Comment by DanTup** [comment] 2019-08-20 12:21
Great! :)

I'm gonna close this since nobody else has replied for a while, but if anyone else is still having thie issue please let me know (and please review the comments above to try and figure out if you might have multiple Android SDKs, and if so resolve that first). Thanks!

**Closed by DanTup** 2019-08-20 12:21 UTC
Labels: awaiting info

**Comment by Ans447766** [comment] 2019-09-13 14:37
> Can you please run the command `avdmanager create avd -n temp` and post the output here?

sdkmanager: command not found?

**Comment by DanTup** [comment] 2019-09-16 08:34
@Ans447766 `avdmanager` and `sdkmanager` are part of the SDK, if you get `command not found` it suggests they're not in your `PATH`. How to add these depends a little on your OS, but an example of the paths is here:

```
export ANDROID_HOME=/Users/foo/Library/Android/sdk 
export PATH=$PATH:$ANDROID_HOME/tools 
export PATH=$PATH:$ANDROID_HOME/tools/bin
export PATH=$PATH/:$ANDROID_HOME/platform-tools
```

**Comment by Dalexz4** [comment] 2019-10-24 22:06
I just got this error "No suitable Android AVD system images are available. You may need to install these using sdkmanager, for example:
  sdkmanager "system-images;android-27;google_apis_playstore;x86""

**Comment by balajiks-dev** [comment] 2019-12-28 23:38
@DanTup
I had run this command in terminal but it shows the error 
'sdkmanager' is not recognized as an internal or external command. operable program or batch file.

**Comment by DanTup** [comment] 2020-01-02 13:26
@balajiks-dev that probably means your Android SDK is not in your `PATH` environment variable. You can run it with a full path if you know where your Android SDK is. For example, for me I can run:

```
/Users/danny/Library/Android/sdk/tools/bin/sdkmanager "system-images;android-27;google_apis_playstore;x86"
```

**Comment by kareemX** [comment] 2020-01-07 00:21
> @balajiks-dev that probably means your Android SDK is not in your `PATH` environment variable. You can run it with a full path if you know where your Android SDK is. For example, for me I can run:
> 
> ```
> /Users/danny/Library/Android/sdk/tools/bin/sdkmanager "system-images;android-27;google_apis_playstore;x86"
> ```

it gaves me this
ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation.

**Comment by DanTup** [comment] 2020-01-07 12:45
@kareemX it looks like you also need to also either have Java on your `PATH` or the `JAVA_HOME` env variable set to its location in order to sun `sdkmanager`.

**Comment by eujin0212** [comment] 2020-02-13 17:48
Hi i also got this problem :

**No suitable Android AVD system images are available. You may need to install these using sdkmanager, for example:
  sdkmanager "system-images;android-27;google_apis_playstore;x86"**

When i type "D:\Documents\Flutter project\hello> **sdkmanager "system-images;android-27;google_apis_playstore;x86**"" the result is as below :
  
**sdkmanager : The term 'sdkmanager' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, 
or if a path was included, verify that the path is correct and try again.
At line:1 char:1**

**Comment by DanTup** [comment] 2020-02-13 17:55
@eujin0212 that's because the folder that `sdkmanager` is in is not in your `PATH` environment variable. You should try running `"D:\Android SDK\tools\bin\sdkmanager" "system-images;android-27;google_apis_playstore;x86"` but replacing `D:\Android SDK` with the path to your Android SDK.

**Comment by eujin0212** [comment] 2020-02-15 06:01
> @eujin0212 that's because the folder that `sdkmanager` is in is not in your `PATH` environment variable. You should try running `"D:\Android SDK\tools\bin\sdkmanager" "system-images;android-27;google_apis_playstore;x86"` but replacing `D:\Android SDK` with the path to your Android SDK.

hi can i know how should i running the **"D:\Android SDK\tools\bin\sdkmanager" "system-images;android-27;google_apis_playstore;x86" but replacing D:\Android SDK with the path to your Android SDK.**??

i have added this to my enviroment **C:\Users\Eu Jin\AppData\Local\Android\Sdk\tools\bin\sdkmanager.bat** and i go to vs i typed **system-images;android-27;google_apis_playstore;x86** this error message came out **system-images : The term 'system-images' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the 
name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1**

**Comment by DanTup** [comment] 2020-02-16 21:45
You need to add only `C:\Users\Eu Jin\AppData\Local\Android\Sdk\tools\bin\` to your `PATH` environment (without `sdkmanager.bat`), and then run the command:

```
sdkmanager "system-images;android-27;google_apis_playstore;x86"
```

Or, alternatively just this command may work without setting `PATH`:

```
"C:\Users\Eu Jin\AppData\Local\Android\Sdk\tools\bin\sdkmanager.bat" "system-images;android-27;google_apis_playstore;x86"
```

**Comment by keerthima** [comment] 2020-04-20 07:01
Exception in thread "main" java.net.UnknownHostException: services.gradle.org
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:666)
	at sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1156)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1050)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1564)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:263)
	at org.gradle.wrapper.Download.downloadInternal(Download.java:58)
	at org.gradle.wrapper.Download.download(Download.java:44)
	at org.gradle.wrapper.Install$1.call(Install.java:61)
	at org.gradle.wrapper.Install$1.call(Install.java:48)
	at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)
	at org.gradle.wrapper.Install.createDist(Install.java:48)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:128)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
Finished with error: Gradle task assembleDebug failed with exit code 1

**Comment by DanTup** [comment] 2020-04-20 07:43
@keerthima your issue isn't the same as this one so it should be opened in its own issue.

This issue seems more like a connectivity issue though, your machine was unable to resolve services.gradle.org.

> java.net.UnknownHostException: services.gradle.org

Can you load https://services.gradle.org/ in your browser successfully?

**Comment by keerthima** [comment] 2020-04-20 07:57
Yes sir . I loaded https://services.gradle.org/

**Comment by DanTup** [comment] 2020-04-20 08:06
Does it work if you run `flutter run` in your project from the terminal?

**Comment by keerthima** [comment] 2020-04-20 08:14
Where should I run.. chrome?

**Comment by DanTup** [comment] 2020-04-20 08:18
You can run `flutter run` from a terminal / command prompt (after changing to the directory where your project is). This is similar to running with the **Run** menu in VS Code, but without debugging.

There's info on using the terminal to run Flutter apps here:

https://flutter.dev/docs/get-started/test-drive?tab=terminal

I'm curious if your error only occurs when running from VS Code, or if also from the terminal.

**Comment by keerthima** [comment] 2020-04-20 08:27
No its happening while I'm running flutter project from android atudio too

**Comment by keerthima** [comment] 2020-04-20 08:44
Is it a problem of my jdk?

**Comment by keerthima** [comment] 2020-04-20 08:49
It has been 4 days .. I was stuked with this. Everything was fine in my
another lap. It has been damaged recently.  That's why i switched to this
lap. Please help.me

**Comment by DanTup** [comment] 2020-04-20 09:12
I'm not very familiar with Gradle so I'm not sure what's wrong here (I don't think it's a VS Code issue if it happens in Android Studio too). Do you have a proxy server? There's some [info here](https://stackoverflow.com/a/57324396) suggesting if you have a proxy you may need to tell Gradle to use it.

Could you run flutter doctor -v also in a terminal / command prompt, and paste the full output? Please raise in a new issue though, since this one is unrelated.

**Comment by keerthima** [comment] 2020-04-20 10:08
[-] Android toolchain - develop for Android devices
    • Android SDK at D:\Android\sdk
    ✗ Android SDK is missing command line tools; download from
https://goo.gl/XxQghQ
    • Try re-installing or updating your Android SDK,
      visit https://flutter.dev/setup/#android-setup for detailed
instructions.

**Comment by DanTup** [comment] 2020-04-20 10:13
@keerthima it looks like your Android SDK is incomplete. Try following the steps at the page linked in the output you posted, and then if you still have issues open a new issue and include the updated full output of `flutter doctor -v`. Thanks!

**Comment by charity1475** [comment] 2020-10-23 19:42
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
	at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156)
I'm getting the error for ./sdkmanager "system-images;android-27;google_apis_playstore;x86"

**Comment by DanTup** [comment] 2020-10-26 12:10
@charity1475 that seems like an issue with your Android SDK - which may be that you're running it using a newer version of Java than it supports (see https://stackoverflow.com/questions/46402772/failed-to-install-android-sdk-java-lang-noclassdeffounderror-javax-xml-bind-a).

**Comment by AbubakarOM** [comment] 2021-02-09 23:47
Hi, @DanTup  I have read through the chat above but after I pasted this, I got this 
                                        flutter config --machine
I got this result
                                        {
                                              "android-studio-dir": "C:\\Program Files\\Android\\Android Studio",
                                             "android-sdk": "C:\\Users\\admin\\AppData\\Local\\Android\\sdk"
                                         }
then I pasted this 
                                        sdkmanager "system-images;android-27;google_apis_playstore;x86"
I go the below result
                                          'sdkmanager' is not recognized as an internal or external command,
                                           operable program or batch file.

Kindly assist

**Comment by DanTup** [comment] 2021-02-10 10:41
@AbubakarOM that will happen if the folder that contains `sdkmanager` is not in your `PATH` environment variable. You can instead call it with a full path, like:

```
C:\Users\admin\AppData\Local\Android\sdk\tools\bin\sdkmanager.bat "system-images;android-27;google_apis_playstore;x86"
```

**Comment by AbubakarOM** [comment] 2021-02-10 10:46
@DanTup after I clicked on No Device and select Create Android Emulator, I still get this 

No suitable Android AVD system images are available. You may need to install these using sdkmanager, for example:
  sdkmanager "system-images;android-27;google_apis_playstore;x86"

**Comment by AbubakarOM** [comment] 2021-02-10 10:48
When I used this 

C:\Users\admin\AppData\Local\Android\sdk\tools\bin\sdkmanager.bat "system-images;android-27;google_apis_playstore;x86"

I got this

C:\Users\admin\wordpair_generator>C:\Users\admin\AppData\Local\Android\sdk\tools\bin\sdkmanager.bat "system-images;android-27;google_apis_playstore;x86"
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
        at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156)
        at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75)
        at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81)
        at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:73)
        at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:48)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:606)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:168)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        ... 5 more

**Comment by DanTup** [comment] 2021-02-10 10:54
@AbubakarOM that seems like something may be wrong with your Android SDK, or it may be trying to run using the wrong version of Java. There's some info [here](https://github.com/flutter/flutter/issues/66458#issuecomment-697483466) about the required version of Java and the environment variable you'd need to set to point at it.

**Comment by AbubakarOM** [comment] 2021-02-10 10:58
@DanTup, thanks I am currently checking that out.

**Comment by ShankarTheBoss** [comment] 2021-12-27 10:21
> avdmanager create avd -n temp



> Can you please run the command `avdmanager create avd -n temp` and post the output here?
![sdasds](https://user-images.githubusercontent.com/96463221/147462341-bb716e74-40e1-4913-a1f8-5f342141eb06.png)

**Comment by DanTup** [comment] 2021-12-29 12:19
@ShankarTheBoss I think you may have the wrong version of Java - see https://askubuntu.com/questions/1025743/avdmanager-throws-exception-when-trying-to-run-it-from-bash

**Comment by Jkudjo** [comment] 2022-06-18 22:44
sdkmanager "system-images;android-27;google_apis_playstore;x86"

 having the same issue .

**Comment by Jkudjo** [comment] 2022-06-20 10:21
@DanTup  Thanks i got it fixed.

**Comment by bloodreaper005** [comment] 2022-09-22 05:27
> 

how to run that command
