### ISSUE TITLE
Allow formatter to use 4 spaces instead of 2

### ISSUE THREAD

**Issue by mfearby** [Dart-Code/Dart-Code#4477] opened 2023-04-02 02:45 UTC
**Is your feature request related to a problem? Please describe.**
The dart_style formatter only allows 2 spaces which is very annoying for people with vision issues. It's hard to see the structure of the code.

**Describe the solution you'd like**
Allow us to configure the number of spaces for the formatter.

**Describe alternatives you've considered**
Not using Flutter

**Comment by DanTup** [comment] 2023-04-03 10:11
Unfortunately this isn't currently possible. The extension is only able to use `dart_style` which has the limitations you describe. As far as I know, there isn't currently a Dart formatter that supports 4-spaces or tabs.

There's an issue at https://github.com/Dart-Code/Dart-Code/issues/914 about supporting a more flexible formatter because I think it's a reasonable request, but there isn't an existing formatter that can be used, and I don't think building it directly into this extension is the right approach.

I'll close this as a dupe of https://github.com/Dart-Code/Dart-Code/issues/914 because it's essentially the same request.

**Closed by DanTup** 2023-04-03 10:11 UTC
Labels: is enhancement

**Comment by rwolfcastle74** [comment] 2023-04-04 11:57
Hmm. Dupe of a 5-year-old ticket. I guess there's my answer. Flutter ain't ever going to be nice to new users.

**Comment by mfearby** [comment] 2023-04-04 12:03
There doesn't seem to be anything unfortunate about it: [#914](https://github.com/Dart-Code/Dart-Code/issues/914) has been open for 5 years now. It's a good thing JetBrains is working on Kotlin Multiplatform (whose formatter supports any indentation you want). 

Surely Dart as a language can't be so bad that its formatter can't cope with 2 or 4 spaces for indentation? It just seems laughable.

**Comment by DanTup** [comment] 2023-04-04 12:31
The answer to your question is in the [formatter's FAQ](https://github.com/dart-lang/dart_style/wiki/FAQ#why-cant-i-configure-it). This repository is not for the formatter, the extension is just a user of it.

I understand the frustration, but please be respectful when posting here. There's nothing requiring you to use the Dart formatter (the flutter/flutter repo itself is mostly hand-formatted for readability).

**Comment by thooton** [comment] 2025-09-04 04:37
This is a totally ridiculous decision by Google and no amount of Dart developers shutting down conversations or making false claims that this is "impossible" is going to change that fact.

My solution to this issue is to post-process the formatted file to double the number of spaces at the beginning of each line. In Zed, I modify my `settings.json` like this:

```json
{
    "languages": {
        "Dart": {
            "tab_size": 4,
            "hard_tabs": false,
            "formatter": {
                "external": {
                    "command": "sh",
                    "arguments": [
                        "-c",
                        "tmpfile=$(mktemp /tmp/dart_format.XXXX.dart) && cat > \"$tmpfile\" && dart format \"$tmpfile\" >/dev/null 2>/dev/null && cat \"$tmpfile\" | perl -pe 's/^( {2})+/\" \" x (length($&) * 2)/e' && rm \"$tmpfile\""
                    ]
                }
            }
        }
    }
}
```

I do not use visual studio code, but I believe that the above solution can be tweaked to work with its `settings.json` like so (note that this is untested):

```json
"customLocalFormatters.formatters": [
    {
        "command": "dart format ${file} && perl -i -pe 's/^( {2})+/\" \" x (length($&) * 2)/e' ${file}",
        "languages": ["dart"]
    }
]
```
