### ISSUE TITLE
GetX controllers initiaizations not been logged in the console as it used to be 

### ISSUE THREAD

**Issue by miikhaaeel** [Dart-Code/Dart-Code#4871] opened 2023-12-02 14:07 UTC
Using GetX, controllers initializations, creation and deletion are always being logged to the console before this update when running without debugging.
Now it doesn't get logged except i start debugging.

**Comment by DanTup** [comment] 2023-12-06 11:41
Closing as a dupe of https://github.com/Dart-Code/Dart-Code/issues/4875.

**Closed by DanTup** 2023-12-06 11:41 UTC
Labels: awaiting info

**Comment by DanTup** [comment] 2023-12-06 14:09
A fix is available in the pre-release version of the extension - details here:

https://github.com/Dart-Code/Dart-Code/issues/4875#issuecomment-1842960845

**Comment by miikhaaeel** [comment] 2023-12-06 20:54
Alright.
-- create a flutter project
-- Add getx package to dependencies
-- Change MaterialApp to GetMaterialApp in main.dart
-- Run with Ctrl+F5 and check the consloe.

Note-- Running with both Ctrl+F5 and just F5 will log the initialization of GetX controller when the app starts in the previous version of the plugin. But in this new plugin, only F5 does this.
I love running my app with Ctrl+F5

**Comment by miikhaaeel** [comment] 2023-12-06 20:55
> A fix is available in the pre-release version of the extension - details here:
> 
> [#4875 (comment)](https://github.com/Dart-Code/Dart-Code/issues/4875#issuecomment-1842960845)

Oh, alright.
I will check it out.
Thank you

**Comment by DanTup** [comment] 2023-12-07 10:35
> I love running my app with Ctrl+F5

FWIW there is very little difference between Run/Debug for Dart/Flutter. To fix this issue we have to force a connection to the VM Service in Run mode.

The only real difference is whether breakpoints and break-on-exception work (something you can also toggle in debug mode). 

I do want to revisit this though and document (and be deliberate) about exactly what the differences are (which is being tracked in https://github.com/Dart-Code/Dart-Code/issues/4875).

Please let me know if everything is working as expected in the pre-release version.

**Comment by miikhaaeel** [comment] 2023-12-07 11:47
Yes, it works as expected in the pre-release version

**Comment by DanTup** [comment] 2023-12-07 12:30
Great, thanks for confirming :-)
