### ISSUE TITLE
Code/widget completion/intellisense issue

### ISSUE THREAD

**Issue by rajeshzmoke** [Dart-Code/Dart-Code#3047] opened 2021-01-05 10:04 UTC
Proper widget suggestion is not shown... seems something is broken and i am not able to fix this. Tried it in new flutter project same issue is present

<img width="744" height="400" alt="Screenshot 2021-01-05 at 2 26 37 PM" src="https://user-images.githubusercontent.com/30038668/103628498-22426580-4f65-11eb-8b89-7abd59a559ab.png">

settings.json

```
{
    "dart.flutterSdkPath": "/Users/dhruv/Desktop/flutter",
    "workbench.iconTheme": "vscode-great-icons",
    "diffEditor.ignoreTrimWhitespace": false,
    "dart.lineLength": 120,
    "editor.fontSize": 14,
    "window.zoomLevel": 0,
    "git.enableSmartCommit": true,
    "git.confirmSync": false,
    "files.autoSave": "onFocusChange",
    "gitlens.blame.ignoreWhitespace": true,
    "dart.debugExternalLibraries": true,
    "dart.debugSdkLibraries": true,
    "dart.autoImportCompletions": false,
    "[dart]": {
        "editor.formatOnSave": true,
        "editor.formatOnType": true,
        "editor.rulers": [
            160
        ],
        "editor.selectionHighlight": false,
        "editor.suggest.snippetsPreventQuickSuggestions": false,
        "editor.suggestSelection": "first",
        "editor.tabCompletion": "onlySnippets",
        "editor.wordBasedSuggestions": false
    },
}
```
VSCode version

```
Version: 1.52.1
Commit: ea3859d4ba2f3e577a159bc91e3074c5d85c0523
Date: 2020-12-16T16:30:02.420Z
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.6.0
```

flutter doctor -v
```
[✓] Flutter (Channel stable, 1.22.5, on Mac OS X 10.15.7 19H2 darwin-x64, locale en-IN)
    • Flutter version 1.22.5 at /Users/dhruv/Desktop/flutter
    • Framework revision 7891006299 (4 weeks ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/dhruv/Library/Android/sdk
    • Platform android-30, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.10.0

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 49.0.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.0
```

**Comment by DanTup** [comment] 2021-01-06 14:18
Can you clarify what you're expecting to see here? Are there items missing from the completion list, or is the problem just the ranking (eg. there's something you'd expect to be closer to the top)?

Did you previously see something different here?

**Comment by rajeshzmoke** [comment] 2021-01-06 16:10
yes previously it used to show the relevant widget
for example it used to show `TextStyle()` as the widget suggestion for `style` param as shown in the description 

<img width="942" alt="Screenshot 2021-01-06 at 9 37 31 PM" src="https://user-images.githubusercontent.com/30038668/103790572-63bb3980-5067-11eb-8cbb-5d9c53daac63.png">

but now its random stuff

**Comment by DanTup** [comment] 2021-01-06 16:35
Got it - I think this is a dupe of https://github.com/dart-lang/sdk/issues/38739 then. There have been some changes that have affected the ranking. The options you want should still be in the list and shown if you start typing `TextStyle`, they're just further down than they probably should be.

I'll close this as a dupe of https://github.com/dart-lang/sdk/issues/38739 because once that's addressed there should not need to be any changes in the VS Code extension as it uses the ranking from the SDK language server.

Thanks!

**Closed by DanTup** 2021-01-06 16:35 UTC
Labels: awaiting info
