### ISSUE TITLE
Outline view crosses first characters of Widgets

### ISSUE THREAD

**Issue by escamoteur** [Dart-Code/Dart-Code#1984] opened 2019-09-11 11:55 UTC
![image](https://user-images.githubusercontent.com/16635729/64695074-923cfa80-d49b-11e9-9714-fe872b2d9235.png)

I attach a demo project:

[vs_code_outline_bug.zip](https://github.com/Dart-Code/Dart-Code/files/3600613/vs_code_outline_bug.zip)

```
[√] Flutter (Channel master, v1.10.1-pre.41, on Microsoft Windows [Version 10.0.18362.295], locale de-DE)
    • Flutter version 1.10.1-pre.41 at C:\Entwicklung\flutter
    • Framework revision 5a3a46ada2 (4 days ago), 2019-09-07 18:37:41 -0400
    • Engine revision c9ea4dba8d
    • Dart version 2.5.0 (build 2.5.0-dev.4.0 ec7ec4ecf7)

[√] IntelliJ IDEA Community Edition (version 2018.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2018.2.5
    • Flutter plugin version 29.1.3
    • Dart plugin version 182.4892.25

[√] VS Code, 64-bit edition (version 1.38.0)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.4.1

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.
PS C:\Entwicklung\tests\vs_code_outline_bug>
```

**Comment by DanTup** [comment] 2019-09-11 13:05
Closing this as a dupe of https://github.com/Dart-Code/Dart-Code/issues/1887, where I've added some notes on the cause and possible workarounds (which sadly are not very good).

**Closed by DanTup** 2019-09-11 13:05 UTC
