### ISSUE TITLE
Logpoint error when hit

### ISSUE THREAD

**Issue by skybur** [Dart-Code/Dart-Code#974] opened 2018-06-04 06:36 UTC
Hello,

I have encountered an error when trying to use logpoint. When the logpoint hit debug console print this message, instead of printing specified log message 
```
Debugger failed to evaluate expression `print("""${_counter}""")`
```
Here is the output of flutter doctor:
```
[√] Flutter (Channel master, v0.5.2-pre.42, on Microsoft Windows [Version 10.0.17134.48], locale en-ID)
    • Flutter version 0.5.2-pre.42 at D:\Repos\flutter-dev\flutter
    • Framework revision 4cd5870ece (2 days ago), 2018-06-01 15:57:01 -0700
    • Engine revision 6cef519598
    • Dart version 2.0.0-dev.59.0.flutter-1a185867a9

[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at D:\Android\android-sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • ANDROID_HOME = D:\Android\android-sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
    • All Android licenses accepted.

[√] Android Studio (version 3.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 24.2.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)

[√] IntelliJ IDEA Community Edition (version 2017.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2017.3.5
    • Flutter plugin version 22.2.2
    • Dart plugin version 173.4548.30

[√] VS Code, 64-bit edition (version 1.23.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 2.13.0

[√] Connected devices (1 available)
    • G621 TL00 • 127.0.0.1:62001 • android-x86 • Android 4.4.2 (API 19)

• No issues found!
```
DartCode version is 2.13.0

**Comment by DanTup** [comment] 2018-06-04 06:41
@skybur Can you try putting a breakpoint on that line and then just typing `_counter` into the `Debug Console` when paused at the breakpoint? If that doesn't give you a reasonable error, can you enable [Observatory Logging](https://dartcode.org/docs/logging/#observatory) and reproduce the issue, and the log file should contain the real error message (it'll be in the response to `evaluateInFrame`).

**Comment by skybur** [comment] 2018-06-04 07:38
Sorry for the wait. When I typed `_counter`, there is no problem and the value is printed in debug console.
Here is the relevant (I hope) observatory log:
```
[14:32:52]: <== {"jsonrpc":"2.0","method":"streamNotify","params":{"streamId":"Debug","event":{"type":"Event","kind":"PauseBreakpoint","isolate":{"type":"@Isolate","fixedId":true,"id":"isolates\/909101337","name":"main.dart:main()","number":"909101337"},"timestamp":1528097574255,"pauseBreakpoints":[{"type":"Breakpoint","fixedId":true,"id":"breakpoints\/1","breakpointNumber":1,"resolved":true,"location":{"type":"SourceLocation","script":{"type":"@Script","fixedId":true,"id":"libraries\/@16336690\/scripts\/file%3A%2F%2F%2FD%3A%2FRepos%2Fflutter-dev%2Fbug%2Flib%2Fmain.dart\/163c9b66589","uri":"file:\/\/\/D:\/Repos\/flutter-dev\/bug\/lib\/main.dart","_kind":"kernel"},"tokenPos":2142}}],"topFrame":{"type":"Frame","kind":"Regular","location":{"type":"SourceLocation","script":{"type":"@Script","fixedId":true,"id":"libraries\/@16336690\/scripts\/file%3A%2F%2F%2FD%3A%2FRepos%2Fflutter-dev%2Fbug%2Flib%2Fmain.dart\/163c9b66589","uri":"file:\/\/\/D:\/Repos\/flutter-dev\/bug\/lib\/main.dart","_kind":"kernel"},"tokenPos":2142},"function":{"type":"@Function","fixedId":true,"id":"classes\/1101\/closures\/367","name":"<anonymous closure>","owner":{"type":"@Function","fixedId":true,"id":"classes\/1101\/functions\/_incrementCounter%4016336690","name":"_incrementCounter","_vmName":"_incrementCounter@16336690","owner":{"type":"@Class","fixedId":true,"id":"classes\/1101","name":"_MyHomePageState","_vmName":"_MyHomePageState@16336690"},"_kind":"RegularFunction","static":false,"const":false,"_intrinsic":false,"_native":false},"_kind":"ClosureFunction","static":false,"const":false,"_intrinsic":false,"_native":false},"code":{"type":"@Code","fixedId":true,"id":"code\/117701142-74163c00","name":"_MyHomePageState._incrementCounter.<anonymous closure>","_vmName":"<anonymous closure>","kind":"Dart","_optimized":false,"_intrinsic":false,"_native":false},"vars":[{"type":"BoundVariable","name":"this","value":{"type":"@Instance","class":{"type":"@Class","fixedId":true,"id":"classes\/1101","name":"_MyHomePageStat…
[14:32:52]: ==> {"id":"400","method":"evaluateInFrame","params":{"expression":"print(\"\"\"_counter\"\"\")","frameIndex":0,"isolateId":"isolates/909101337"}}
[14:32:52]: <== {"jsonrpc":"2.0", "result":{"type":"@Error","_vmType":"UnhandledException","kind":"UnhandledException","id":"objects\/1","message":"Unhandled exception:\nNoSuchMethodError: Class '_MyHomePageState' has no instance method 'print'.\nReceiver: Instance of '_MyHomePageState'\nTried calling: print(\"_counter\")\n#0      Object.noSuchMethod (dart:core\/runtime\/libobject_patch.dart:46:5)\n#1      _MyHomePageState.Eval (evaluate:source:1:7)\n#2      _MyHomePageState._incrementCounter.<anonymous closure> (file:\/\/\/D:\/Repos\/flutter-dev\/bug\/lib\/main.dart:55:7)\n#3      State.setState (package:flutter\/src\/widgets\/framework.dart:1125:30)\n#4      _MyHomePageState._incrementCounter (file:\/\/\/D:\/Repos\/flutter-dev\/bug\/lib\/main.dart:49:5)\n#5      _InkResponseState._handleTap (package:flutter\/src\/material\/ink_well.dart:494:14)\n#6      _InkResponseState.build.<anonymous closure> (package:flutter\/src\/material\/ink_well.dart:549:30)\n#7      GestureRecognizer.invokeCallback (package:flutter\/src\/gestures\/recognizer.dart:102:24)\n#8      TapGestureRecognizer._checkUp (package:flutter\/src\/gestures\/tap.dart:161:9)\n#9      TapGestureRecognizer.acceptGesture (package:flutter\/src\/gestures\/tap.dart:123:7)\n#10     GestureArenaManager.sweep (package:flutter\/src\/gestures\/arena.dart:156:27)\n#11     _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter\/src\/gestures\/binding.dart:147:20)\n#12     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter\/src\/gestures\/binding.dart:121:22)\n#13     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter\/src\/gestures\/binding.dart:101:7)\n#14     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter\/src\/gestures\/binding.dart:64:7)\n#15     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter\/src\/gestures\/binding.dart:48:7)\n#16     _invoke1 (dart…
[14:32:52]: ==> {"id":"401","method":"resume","params":{"isolateId":"isolates/909101337"}}
```
Let me know if you need more info.

**Comment by DanTup** [comment] 2018-06-04 08:29
Got it, I can repro. Will investigate. Thanks!

**Comment by DanTup** [comment] 2018-06-04 08:44
This is bizarre... If I set up the same logpoint that's in the release notes, it fails for the same reason. Yet there's a screenshot of it working right there! I tried rolling back to Flutter v0.3.2 to confirm it hasn't broken in a newer release, and it's failing there. Yet the code appears to not have changed.

I'll keep digging and will put out a patch early this week if I can get it fixed.

**Comment by skybur** [comment] 2018-06-04 08:58
No rush, it's not really urgent for me. I'm just trying this out since it's a cool & helpful feature. Thanks for your hard work 😄

**Comment by DanTup** [comment] 2018-06-04 09:07
Sure, but since we announced it as a new feature in the release notes it'd be good if it worked :D

Strangely, it still works in the tests (although they're CLI and not Flutter)... I'll keep digging!

```js
[
  {"id":"22","method":"evaluateInFrame","params":{"expression":"print(\"\"\"${s} The {year} is ${(new DateTime.now()).year}\"\"\")","frameIndex":0,"isolateId":"isolates/578268991"}},
  {"jsonrpc":"2.0", "result":{"type":"@Instance","_vmType":"null","class": {"type":"@Class","fixedId":true,"id":"classes\/121","name":"Null"},"kind":"Null","fixedId":true,"id":"objects\/null","valueAsString":"null"},"id":"22"}
]
```

**Comment by DanTup** [comment] 2018-06-04 09:38
@devoncarew Any ideas what might have happened here? In a Dart CLi script, if I'm at a breakpoint and I type `print(1)` in the debug console (which goes via `debugInFrame`) it prints fine (it prints both `null`, as the return value of the print, and the `1` from the print). If I do the same thing in Flutter, I see:

```
Unhandled exception:
NoSuchMethodError: No top-level method 'print' declared.
Receiver: top-level
```

Strangely, this worked at some point, because the release notes for v2.13 have a screenshot showing a log point working, yet I can't make it work at all on any version of Flutter (I've tried various versions from 0.3.1 up to current master).

For now, I'm going to look at removing the print and writing it client-side. This may mean multiple trips to Observatory to get the string representation so I'd rather push the print back into the VM if I can, but I need to figure out what's happening here before doing that. Any idea why `print` might not be valid to call? I even tried putting an explicit `print` right before the breakpoint, and that works fine!

**Comment by DanTup** [comment] 2018-06-04 10:12
Even switching this to print client-side seems to have issues, because things like Class names aren't recognised either:

```js
{
	"id": "399",
	"method": "evaluateInFrame",
	"params": {
		"expression": "\"\"\"The {year} is ${(new DateTime.now()).year}\"\"\"",
		"frameIndex": 0,
		"isolateId": "isolates/854818401"
	}
}
```

Results in:

```
Unhandled exception:\n'file:\/\/\/Users\/dantup\/Dev\/Dart-Code\/test\/test_projects\/flutter_hello_world\/lib\/main.dart':
malformed type: line 1 pos 9: cannot resolve class 'DateTime' from 'MyHomePage'
```

I'm sure this should work so I'll open an issue in Flutter for help.

**Comment by DanTup** [comment] 2018-06-04 10:22
I've opened https://github.com/flutter/flutter/issues/18160. I can't explain how this ever worked when I implemented it and got that screenshot as it seems broken both in latest flutter and older Flutters (it's possible it worked for a short period while I implemented it, but that would be some coincidence).

I'm going to stash my workaround on a branch until I hear back.

**Comment by DanTup** [comment] 2018-06-06 06:17
This has now been fixed in Flutter's master branch (it'll roll into `dev` and `beta` in upcoming updates). Thanks for the report!

**Closed by DanTup** 2018-06-06 06:17 UTC
Labels: in debugger, is bug

**Comment by skybur** [comment] 2018-06-06 06:32
Yep it works now. Thanks for this cool feature 😄 

![code_2018-06-06_13-29-21](https://user-images.githubusercontent.com/11155424/41020604-c0749aae-698d-11e8-8715-152da72454a8.png)

**Comment by DanTup** [comment] 2018-06-06 09:07
Yeah; IO use it so much in TypeScript for debugging Dart Code now - so much faster than restarting :)
(ofcourse, I often forget and start writing console.logs!).

The best bit is that it persists, so I can leave them in important places in the code without having to add conditions or remove when committing!
