### ISSUE TITLE
The `debug console` still has character encoding issue in `flutter project`

### ISSUE THREAD

**Issue by shithappens2016** [Dart-Code/Dart-Code#4238] opened 2022-11-02 02:00 UTC
![199195581-070c73da-b5f4-4c29-8238-b641edea2324](https://user-images.githubusercontent.com/13523412/199377090-cb476b4d-1468-4ebc-9e3f-ffa3b9ee7259.jpg)
microsoft/vscode#165130

**Comment by DanTup** [comment] 2022-11-02 10:09
@shithappens2016 can you provide steps to reproduce this?

Does the same occur if you run `flutter run` from an external terminal or only when running from VS Code?

**Comment by DanTup** [comment] 2022-11-02 10:13
There's a similar issue open in Flutter at https://github.com/flutter/flutter/issues/108667 which might be related to using a Chinese edition of Windows. Can you confirm the language of your Windows install?

**Comment by shithappens2016** [comment] 2022-11-02 12:56
@DanTup
You are right. The exact same thing happened to me here.  `chcp 936` or `chcp 65001` wouldn't change a thing.

**Comment by DanTup** [comment] 2022-11-02 12:58
@shithappens2016 do you mean the same occurs if you run from the terminal outside of VS Code?

If so, then I believe this needs fixing in Flutter and is not something fixable here in the VS Code extension. I'll close this as a dupe and if you can add any additional information to https://github.com/flutter/flutter/issues/108667, that might help the Flutter team understand and fix the issue.

Thanks!

**Closed** 2022-11-02 12:58 UTC
Labels: upstream in dart / flutter
