### ISSUE TITLE
Code completion ordering is wrong when autoImportCompletions is enabled

### ISSUE THREAD

**Issue by maRci002** [Dart-Code/Dart-Code#1742] opened 2019-05-23 18:09 UTC
- VSCode Version
1.34.0

- OS Version:
Windows 10

- Extensions:
       - Dart 3.0.2
       - Flutter 3.0.2

- Language
Dart

My problem is that when a constructor (let's say `new ListView.builder(...)`) waits for specific type of arguments then the IDE should consider type matching while using autocomplete feature.

Here's a simplified example of this issue, the `padding` argument shoud implemet `EdgeInsetsGeometry` abstract class but autocomplete shows me random methods / keywords...:
![VS code autocomplete](https://user-images.githubusercontent.com/8436039/58275874-579d3e00-7d96-11e9-844a-9134ccabcf3b.gif)

I think the IDE is smart enough to know there are some classes which implement `EdgeInsetsGeometry` abstract class like: `class EdgeInsets extends EdgeInsetsGeometry` and should offer them as first results.

I don't know maybe the autocomplete results come from Dart analysis server and not related to VSCode at all. I tried to make some changes in the Settings.json but no success, [even I tried the original recommended settings](https://dartcode.org/docs/recommended-settings/).

However in Android Studio everything works is fine, I hope this behavior can be implemented in VSCode too :ok_hand:
![Android Studio autocomplete](https://user-images.githubusercontent.com/8436039/58275898-61bf3c80-7d96-11e9-9937-1cf925349a8d.gif)

I would like to mention in Android Studio autocomplete is 2x times faster than in VSCode, but this is not related to this issue.

**Comment by DanTup** [comment] 2019-05-27 17:29
The completions do come from the server, and it gives us some relevance that we're supposed to sort by. It seems likely we're not interpreting it correctly somewhere though, we should get the same results as Android Studio.

**Comment by DanTup** [comment] 2019-05-29 09:21
Hmmm... I can't repro this - I get the results you want:

![Screenshot 2019-05-29 at 10 18 53 am](https://user-images.githubusercontent.com/1078012/58545465-3657aa00-81fb-11e9-942e-f08a66e76efe.png)

**Comment by DanTup** [comment] 2019-05-29 09:24
Oh wait, I had auto-import-completions off... Got it now:

[stash.txt](https://github.com/Dart-Code/Dart-Code/files/3231698/stash.txt)

We must be calculating ranks wrong when using this new mechanism for completions (which supports auto-importing when you haven't already imported a file).

I'll take a look. Thanks!

**Comment by DanTup** [comment] 2019-05-29 11:28
@bwilkerson @scheglov I'm not sure if there's a server issue here or if I'm misinterpreting the results..

Looking at my first screenshot above (using original completions), the `EdgeInsets` items appear at the top of the list (above `context`). However when using suggestion sets, here's the numbers I see:

## AvailableSuggestionSets

```
EdgeInsets has tags of package:flutter/src/painting/edge_insets.dart::EdgeInsets,EdgeInsets
EdgeInsets.all has tags of undefined
EdgeInsets has tags of package:flutter/src/painting/edge_insets.dart::EdgeInsets,EdgeInsets
EdgeInsets.all has tags of undefined
EdgeInsets has tags of package:flutter/src/painting/edge_insets.dart::EdgeInsets,EdgeInsets
EdgeInsets.all has tags of undefined
EdgeInsets has tags of package:flutter/src/painting/edge_insets.dart::EdgeInsets,EdgeInsets
EdgeInsets.all has tags of undefined
EdgeInsets has tags of package:flutter/src/painting/edge_insets.dart::EdgeInsets,EdgeInsets
EdgeInsets.all has tags of undefined
```

## Standard completions:

```
context has a relevance of 1059
```

## Included SuggestionSets:

```
includedSuggestionRelevanceTags:
    package:flutter/src/painting/edge_insets.dart::EdgeInsetsGeometry = 10

Suggestion EdgeInsets.all from SuggestionSet ID:992
    Suggestion relevance tags: (none), suggestion set relevance: 7
Suggestion EdgeInsets.all from SuggestionSet ID:890
    Suggestion relevance tags: (none), suggestion set relevance: 4
Suggestion EdgeInsets.all from SuggestionSet ID:551
    Suggestion relevance tags: (none), suggestion set relevance: 4
Suggestion EdgeInsets.all from SuggestionSet ID:863
    Suggestion relevance tags: (none), suggestion set relevance: 4
Suggestion EdgeInsets.all from SuggestionSet ID:458
    Suggestion relevance tags: (none), suggestion set relevance: 7
```

So the "EdgeInsets" class gets tags of "package:flutter/src/painting/edge_insets.dart::EdgeInsets,EdgeInsets" (which doesn't include the tags of its abstract base (`package:flutter/src/painting/edge_insets.dart::EdgeInsetsGeometry`) which comes in the `includedSuggestionRelevanceTags`), and the values (for ex `.all`) don't get any tags at all.

As such, everything just gets its included relevance (4 and 7) which is way lower than the 1059 assigned to `context`, so they appear further down.

The things that seem wrong are:

- EdgeInsets doesn't include `EdgeInsetsGeometry` in its tags
- EdgeInsets.all doesn't include *any* tags

Strangely, I can't repro in Android Studio (though admittedly, I don't know how to confirm it's using suggestion sets).

Is there something I'm overlooking of misinterpreting?

**Comment by scheglov** [comment] 2019-05-29 15:03
Relevance is one of the victims of this auto-imports.
We tried to alleviate this, but only to some extent.

* We compute available suggestions using only parsed AST, so we don't know that `EdgeInsets` implements `EdgeInsetsGeometry`.
* I will look at constructors and their tags.
* Tags for top-level declarations are intended to to establish order among top-level declarations. So, yes, relevances of top-level declarations and local elements are not comparable.

**Comment by DanTup** [comment] 2019-05-29 15:49
> We compute available suggestions using only parsed AST, so we don't know that EdgeInsets implements EdgeInsetsGeometry.

Ah, I see :( Is there any way around this? (for ex, could we use "the old way" for files that are already imported?)

> relevances of top-level declarations and local elements are not comparable.

I'm not sure what to do here.. How should the items be sorted by the client?

I may have found why it looks ok in Android Studio, the release notes say the suggestionsets work isn't supported there yet (only IntelliJ - though I don't have that installed to check there currently).

**Comment by scheglov** [comment] 2019-05-29 17:30
I don't have a good solution for this.

Using the old way for already imported libraries is not really an option, in case of Flutter this is a lot of suggestions to send from DAS.

When a tag from an `AvailableSuggestion` matches a tag in `includedSuggestionRelevanceTags`, it is up to the client to prioritize. I think making it a "top relevance" might work. These tags, at least now, are type based. So, if something expects type `String`, we would suggest top-level variables of type `String` higher than of type `int`.

**Comment by DanTup** [comment] 2019-05-29 17:40
In that case, couldn't we just crank the relevance in those tags up to be higher than the normal relevances (eg. add 10000 to them)?

For LSP, we can't have any logic "on the client", so the server will need logic on how to handle this anyway (which makes me think it may be better to fix it in the server for all?).

**Comment by scheglov** [comment] 2019-05-29 17:48
Yes, we could change these relevance boosts as we want.
Do you want to play with this to see if it leads to reasonable sorting on the client?
See https://github.com/dart-lang/sdk/blob/a31a72521b56f2b46782af7fa706017a43f89e56/pkg/analyzer_plugin/lib/utilities/completion/relevance.dart#L16

Hm... Whatever values we choose, it would still require some code on the client to compute relevance, wouldn't it?

**Comment by DanTup** [comment] 2019-05-29 18:39
> Yes, we could change these relevance boosts as we want.
> Do you want to play with this to see if it leads to reasonable sorting on the client?

Sure! Looking at that file, maybe we just need to change `DART_RELEVANCE_BOOST_AVAILABLE_DECLARATION` to be something really high?

> Hm... Whatever values we choose, it would still require some code on the client to compute relevance, wouldn't it?

For LSP, we don't have any control over the client so everything has to be done in the server (the `LspAnalysisServer` class, which speaks the LSP protocol). For completions, this means there's code that behaves like a "client" and builds a single completion list from the suggestion sets here:

https://github.com/dart-lang/sdk/blob/master/pkg/analysis_server/lib/src/lsp/handlers/handler_completion.dart#L153

So when I said it needs doing in the server for LSP, we can do it here. However if we need to have the logic somewhere in the server, I think we may as well do it somewhere that it gives the best results for both (to avoid any clients needing to know that those with tags need additional boosting).

**Comment by bwilkerson** [comment] 2019-05-29 18:50
We need to experiment with including suggestions from non-imported libraries. We had found that the volume of suggestions increased dramatically, which impacts performance. It isn't clear that we can afford to send all of these suggestions in the LSP case. If not, then we'll need to fall back to sending only suggestions from imported libraries, in which case this won't be an issue.

**Comment by scheglov** [comment] 2019-05-29 21:41
Yes, making `DART_RELEVANCE_BOOST_AVAILABLE_DECLARATION` a greater number might work.

**Comment by maRci002** [comment] 2019-05-30 12:59
If suggestions for non-imported libraries causes performace issues then there should be some lazy cache for non-overridable libraries like Flutter SDK libraries, however somehow I'm able to edit those libraries :sweat_smile:.

**Comment by DanTup** [comment] 2019-06-04 15:56
@scheglov 

I tried playing around with `DART_RELEVANCE_BOOST_AVAILABLE_DECLARATION` but it doesn't really help in this case.. It moves EdgeInsetsGeometry above the top level things, but in this case that's not really what we want (we want the subclasses). I'm not sure how we can fix that without knowing the subclasses though.

Another thing that makes this seem weird is that Flutter re-exports a lot of types, we end up with a chunk of 5-6 `EdgeInsetGeometry` together in the completion where the top one is already imported and the others are not. Ideally we wouldn't duplicate types if they're the same type (just re-exported) and already imported into the file (though I'm not sure if we have this info either from just the parsed AST).

@bwilkerson 

> We need to experiment with including suggestions from non-imported libraries. We had found that the volume of suggestions increased dramatically, which impacts performance. It isn't clear that we can afford to send all of these suggestions in the LSP case.

Are there reports of performance issues here other than the Emacs deserialisation perf? In my testing it seemed very fast - though I do think dropping the docs (which are *huge* for Flutter - as well as duplicated across many libraries because of the re-exported types) would slash the serialisation/deserialisation costs a fair bit. I'll try and get some timings of this and may open an issue about that (removing docs, but providing them in getSuggestionDetails).

**Comment by DanTup** [comment] 2019-06-04 15:59
@maRci002 

> If suggestions for non-imported libraries causes performace issues then there should be some lazy cache for non-overridable libraries like Flutter SDK libraries

I think the performance issues are mainly around transmitting the full list of them (esp. in LSP) to the client, not the initial building of the index. For non-LSP we already send these to the client in advance and cache them.

> Flutter SDK libraries, however somehow I'm able to edit those libraries 😅.

They're just source files on your disk, so this is expected (it's how I work on Flutter - modifying those files and re-running! though often there are snapshots you need to delete to see changes). If using VS Code, you should get a warning if you start modifying files outside of your open folders though.

**Comment by bwilkerson** [comment] 2019-06-04 16:04
> Are there reports of performance issues here ...

No. I just remember that when we first started implementing this functionality @scheglov saw issues with passing back such a large number of suggestions. That observation is what prompted us to compute the data in advance and send it in smaller chunks.

I suppose it's possible that the issues had more to do with computing the suggestions than with the actual transport cost, and that by caching them on the server side we could avoid the complexity of asking clients to merge multiple lists. If so, we should consider making that change, as I think it would simplify some other issues we've run into.

**Comment by DanTup** [comment] 2019-06-04 16:12
Ah, got it. It would definitely be good to see a breakdown of the time (including serialisation/deserialisation, and merging on the client), though it's a bit hard to capture across the multiple processes. I think the existing way is probably faster though (since merging the lists is cheap - we don't need to sort them, since VS code does that on the other side of the fence).

For LSP, we can't do anything on the client, so we either have to pay the full cost of transporting a big list (what we do now) or we could send a shorter list by filtering based on the type prefix and only sending the top X, at the expense of the client calling us on every keystroke for an updated list (so faster requests, but many more of them).

I'll see if I can get some numbers of the current LSP implementation with a Flutter project to see how much time we spend on the server versus how much the total round trip from the client is (and how that differs if I remove the doc comments). I'll open a new issue if it looks like we may need to do work there though, to keep this one on the topic of ranking.

**Comment by DanTup** [comment] 2019-06-04 16:41
Based on some quick testing, I think I hadn't tested with a Flutter project previously :( The full round-trip is 2-3 seconds in a Flutter project.

The issue definitely seems related to transferring the results to VS Code (serialisation/deserialisation/over-the-wire) because if I leave all the server processing in, but just return an empty list at the end, it drops to 134ms (and the way I'm testing it skipping the sorting that VS Code will do, since I'm handling the request directly).

I've opened https://github.com/dart-lang/sdk/issues/37163 about the performance, and will do some testing to see if I can track down how the time is split between those things mentioned above.

**Comment by scheglov** [comment] 2019-06-04 17:01
Regarding duplicate completion suggestions, we extended DAS to provide information about existing imports, which should allow the clients to know which suggestions to use. https://dart-review.googlesource.com/c/sdk/+/103561

@lambdabaa works on adding support for this in IntelliJ. https://github.com/JetBrains/intellij-plugins/pull/665

There is no existing solution for suggesting subtypes.

**Comment by DanTup** [comment] 2019-06-17 13:01
The duplicates are handled by https://github.com/Dart-Code/Dart-Code/pull/1789.

I'll keep this issue open about the sorting to avoid getting duplicate issues if others come across it.

**Comment by DanTup** [comment] 2019-10-07 17:03
I opened https://github.com/dart-lang/sdk/issues/38739 to track this in the SDK repo, since I don't think there's enough info to handle this on the client (I couldn't find an existing issue tracking it).

**Comment by DanTup** [comment] 2020-11-18 17:29
Closing this as a dupe of https://github.com/dart-lang/sdk/issues/38739 (though I think there may have been improvements since that was opened). With LSP, any changes to the ranking are done entirely in the server and won't need changes in the VS Code extension here.

(I also think the perf issues discussed above for LSP have been resolved by no longer sending the full lists, but filtering by prefixes and capping the results).

**Closed by DanTup** 2020-11-18 17:29 UTC
Labels: blocked on dart / flutter, in editor, is bug
