### ISSUE TITLE
Add an option to control hot-reload-on-save behaviour when using auto-save

### ISSUE THREAD

**Issue by skateboarder** [Dart-Code/Dart-Code#3110] opened 2021-01-31 02:28 UTC
**Describe the bug**

**To Reproduce**
1. Run a project
2. Edit it while having the auto-save setting enabled

**Expected behavior**
On completion of auto-save, hot reload should've been triggered. But instead, its not triggered until manual save/reload

**Versions (please complete the following information):**
 - VS Code version: 1.52.1
 - Dart extension version: 3.19.1
 - Dart/Flutter SDK version: 2.12.0-133.7.beta/1.25.0-8.3.pre

**Comment by RandalSchwartz** [comment] 2021-01-31 05:33
This is intended behavior!  See #3033.

**Comment by RandalSchwartz** [comment] 2021-01-31 05:34
This is an intended change to fix #3033!  Doesn't anyone read the release notes?

**Comment by DanTup** [comment] 2021-01-31 10:28
If this was working well for some, then I think it's probably fair to have a setting to control it (perhaps extend the existing setting to be an enum for on/off/manual or similar).

**Comment by CoderUni** [comment] 2021-01-31 10:32
> If this was working well for some, then I think it's probably fair to have a setting to control it (perhaps extend the existing setting to be an enum for on/off/manual or similar).
Thanks, the only way to solve this issue for now is to downgrade both extensions but adding a feature to change the setting would help us a lot. I'll be updating my solution in https://stackoverflow.com/questions/65975713/flutter-doesnt-hot-reload-on-autosave-in-vscode/65975714#65975714 once the feature rolls out.

**Comment by encikpulasan** [comment] 2021-02-02 11:06
This is one of the best feature and why i chose VSCode as my primary IDE. Should've make it optional since it works well on mac. Just my 2 cents.

**Comment by DanTup** [comment] 2021-02-02 11:12
I guess I underestimated how many people were using this without issues! The `dart.flutterHotReloadOnSave` will be updated to be an enum in the next release:

### dart.flutterHotReloadOnSave

Whether to automatically send a Hot Reload request during a debug session when saving files.

- `never` - do not reload when saving.
- `always` - reload for all saves, manual or automatic.
- `manual` - only reload for manual saves (requires pressing Save explicitly if using autosave).

**Comment by DanTup** [comment] 2021-02-03 10:12
This change hasn't landed yet, so keeping this open until it does.

**Comment by Scienticious** [comment] 2021-02-03 11:56
@DanTup would you please announce when the next version will be released

**Closed** 2021-02-04 13:38 UTC
Labels: in editor, in flutter, is enhancement

**Comment by Malware656** [comment] 2021-03-24 17:28
> I guess I underestimated how many people were using this without issues! The `dart.flutterHotReloadOnSave` will be updated to be an enum in the next release:
> 
> ### dart.flutterHotReloadOnSave
> Whether to automatically send a Hot Reload request during a debug session when saving files.
> 
> * `never` - do not reload when saving.
> * `always` - reload for all saves, manual or automatic.
> * `manual` - only reload for manual saves (requires pressing Save explicitly if using autosave).

Worked for me

**Comment by madd-project** [comment] 2021-07-04 14:14
Asking from @DanTup and @Malware656 can provide a working screenshot
