### ISSUE TITLE
Go to Implementations on a getter gives random-looking results

### ISSUE THREAD

**Issue by jcollins-g** [Dart-Code/Dart-Code#4531] opened 2023-05-09 16:03 UTC
**Describe the bug**
Right click and show implementations on a specific getter, and the in-line dialog shows obviously implausible suggestions.  The feature works most of the time so I'm not sure what set of conditions is causing this.   IntelliJ's plugin seems to give good results here, so to start with, filing with the VSCode plugin. 

**To Reproduce**

1. `git clone git@github.com:dart-lang/dartdoc.git`
2. `cd dartdoc && git checkout e8c5de44294d61890ef28ca91e3ecf38e50c1c69`
3. Set up directory as a Dart project 
4. Open `lib/src/model/model_object_builder.dart` in VSCode
5. Go to line 36 and right click on `modelBuilder`, select "Go to Implementations".

**Expected behavior**
Show only links to valid implementations.

**Screenshots**
![Screenshot 2023-05-08 at 1 34 46 PM](https://github.com/Dart-Code/Dart-Code/assets/14116827/a9b8ccc7-7bbd-4368-bbdd-b2e3b490bc81)

**Please complete the following information:**
 - Operating System and version: macOS 13.13.1
 - VS Code version: 1.78.0 (Universal)
 - Dart extension version: 3.63.20230502
 - Dart/Flutter SDK version: 3.1.0-86.0.dev
 - Target device (if the issue relates to Flutter debugging):  n/a

**Comment by DanTup** [comment] 2023-05-09 16:26
😬

Thanks for the detailed steps, I can reproduce this - taking a look.

(btw, I'm curious what "Set up directory as a Dart project" meant in your steps though - you shouldn't need to do anything special for VS Code to load the Dart extension?)

**Comment by DanTup** [comment] 2023-05-09 16:44
```
1683650484067:Info:Found item at 1111::11 of /Users/danny/Dev/Google/dartdoc/lib/src/element_type.dart
1683650484067:Info:Changed to member at 1759::12 of /Users/danny/Dev/Google/dartdoc/lib/src/model/model_object_builder.dart
```

Looks like we get confused by implementations coming from `mixin`s in other files. We find `abstract class ElementType` in `element_type.dart` and then see if it has an implementation of `modelBuilder` and find it from the `ModelBuilder` mixin, but we use the original filename with the new offset/length.

**Comment by DanTup** [comment] 2023-05-09 17:49
Got it, thanks!

I've got a fix open at https://dart-review.googlesource.com/c/sdk/+/302400.

**Comment by DanTup** [comment] 2023-05-10 09:32
Fix landed in https://github.com/dart-lang/sdk/commit/334ce04906462f7aad2ebac1d029248b51098a23.

(the fix is part of the SDK so will show up with an SDK update, not Dart-Code update)

**Closed by DanTup** 2023-05-10 09:32 UTC
Labels: is bug, in editor, in lsp/analysis server
