### ISSUE TITLE
Use formatter version specified in pubspec

### ISSUE THREAD

**Issue by jathak** [Dart-Code/Dart-Code#796] opened 2018-04-10 06:10 UTC
It seems like Dart Code uses the `dartfmt` executable in the current SDK to run the formatter. However, I'm currently switching frequently between the stable 1.24 release and the Dart 2 dev release and the formatter in these two versions differs (see example below). I'd like my formatting to be consistent regardless of the SDK I'm currently using, so it would be nice if Dart Code could use the version of dart_style specified in the pubspec.

**Example of differing output:**

dartfmt 1.0.6 (in 1.24.3 SDK):
```dart
main() {
  function(
      a,
      """multi
line""");
}
```
dartfmt 1.0.10 (in 2.0.0-dev.45.0 SDK):
```dart
main() {
  function(a, """multi
line""");
}
```

**Comment by DanTup** [comment] 2018-04-10 18:59
> It seems like Dart Code uses the `dartfmt` executable in the current SDK to run the formatter

It's not quite that - we actually spawn a server ("the analysis server") that ships inside the SDK. It provides a lot of services useful to Dart Code, such as diagnostics, code completion, quick-fixes, refactors, and ofcourse formatting.

> I'm currently switching frequently between the stable 1.24 release and the Dart 2 dev release

Is this on the same project, or are you using different SDK versions in different projects? The reason I ask, is that changing between these versions on the same project would affect far more than just formatting?

> it would be nice if Dart Code could use the version of dart_style specified in the pubspec

Unfortunately, since we're using the analysis server, this wouldn't be a trivial change and switching to using the command line analyzer wouldn't be a good change, the performance would be worse (we'd be constantly spawning/killing VMs) and I think it'd be hard to support formatting unsaved files (AFAIK it only works with files on disk, so would need the file buffers to be written?).

**Comment by DanTup** [comment] 2018-05-24 09:50
I'm closing this as a kind-of dupe of #914. Currently formatting is provided by the same server that is providing other languages features and using another SDK wouldn't be a good solution. If people want control over formatting, we should have a custom formatter (either in the SDK or not).

Please 👍 #914 if this is something you'd like to see.

**Closed by DanTup** 2018-05-24 09:50 UTC
