### ISSUE TITLE
App freezes on HTTP request after upgrading to Flutter 3.13.0

### ISSUE THREAD

**Issue by Fraeng** [Dart-Code/Dart-Code#4695] opened 2023-08-20 15:20 UTC
**Describe the bug**
After upgrading to Flutter 3.13.0, any HTTP request made using the http package or httpclient causes the app to freeze in Debug mode. flutter run works fine.

**To Reproduce**
1. Create a new Flutter project.
2. Add http and logger as dependencies.
3. Use the provided code to make an HTTP request on app startup.
4. Run the app with F5.

<pre>
import 'package:flutter/material.dart';
import 'dart:io';
import 'package:logger/logger.dart';

final logger = Logger();

void main() async {
  logger.i('before http.get call');
  var client = HttpClient();
  var request = await client.getUrl(Uri.parse('https://api.github.com/users'));
  var response = await request.close();
  logger.i('Response Code: ${response.statusCode}');

  runApp(const MainApp());
}

class MainApp extends StatelessWidget {
  const MainApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: Scaffold(
        body: Center(
          child: Text('Hello World!'),
        ),
      ),
    );
  }
}

</pre>

**Expected behavior**
Log output for response.statusCode.

**Please complete the following information:**
 - Operating System and version: Windows10
 - VS Code version: 1.81.1
 - Flutter extension version: 3.70.0
 - Dart extension version: 3.70.0
 - Dart/Flutter SDK version: 3.1.0/3.13.0
 - Target device (if the issue relates to Flutter debugging): SM T580 (android-arm)

**Comment by andynewman10** [comment] 2023-08-20 17:30
Just out of curiosity, when you run your app, have you looked at the debug pane (on the left side)?

For me, I see that the app freezes, but it is because the debugger is stopped at the following location in `socket_patch.dart` (look at the `// THIS LINE` comment below):
```

  static Future<List<InternetAddress>> lookup(String host,
      {InternetAddressType type = InternetAddressType.any}) {
    return _IOService._dispatch(_IOService.socketLookup, [host, type._value])
        .then((response) {
      if (isErrorResponse(response)) {
        throw createError(response, "Failed host lookup: '$host'"); // THIS LINE
      }
      return [
        for (List<Object?> result in (response as List).skip(1))
          _InternetAddress(
              InternetAddressType._from(result[0] as int),
              result[1] as String,
              host,
              result[2] as Uint8List,
              result[3] as int)
      ];
    });
  }

```
From there, you can click on Continue and carry on execution.

This error is weird, because the host name is perfectly valid.

As a matter of fact, Flutter 3.10.6 also raises this exception, at the same place, but I have noticed the following difference between Flutter 3.10.6 and 3.13.0:

- 3.10.6: `Uncaught exceptions` set, `Debug my code`: the debugger does not stop
- 3.13.0: `Uncaught exceptions` set, `Debug my code`: the debugger DOES stop, which is not what I expect.

Can you try on your side?

**Comment by Fraeng** [comment] 2023-08-20 22:23
I have the same stack error messages.

If I let the debugger continue, I still get the error `HandshakeException: Connection terminated during handshake` in main.

**Comment by DanTup** [comment] 2023-08-21 09:07
I think the behaviour you're seeing is related to one of the following:

- https://github.com/dart-lang/sdk/issues/52615
- https://github.com/flutter/devtools/issues/5883
- https://github.com/dart-lang/sdk/issues/47985
- https://github.com/flutter/flutter/issues/129121

There are some cases where the debugger treats _caught_ errors as _uncaught_, and there are also some places inside the framework that throw/catch exceptions that will result in the debugger pausing if _All Exceptions_ is ticked and does not take into account which code is marked as debuggable (which is what the DevTools issue is discussing changing).

I don't think there's anything to do in the extension once those are fixed, so I'll close this in favour of those. Please subscribe to those issues and/or add additional information if you have any that isn't already noted. Thanks!

**Closed** 2023-08-21 09:07 UTC
Labels: is bug

**Comment by bivek1** [comment] 2023-11-14 18:09
I have got the same issue with many version of flutter. It needs to be solved any how.

**Comment by DanTup** [comment] 2023-11-15 14:25
@bivek1 it's very difficult to help without more information. If you're on the latest version of Flutter and believe you're seeing a bug, please open a new issue with a code sample and detailed description of what you're seeing and what you expect to see. There are still some known issues linked above, but I don't know if you're seeing one of those without more info. Thanks!

**Comment by AniqqKhaizii** [comment] 2023-12-05 04:41
![image](https://github.com/Dart-Code/Dart-Code/assets/55343638/3e71cd04-faf5-4615-ab84-2e8c2e9aa2a0)
My debugging pause here. i dont know how to fix it

**Comment by DanTup** [comment] 2023-12-05 16:03
@AniqqKhaizii it's hard to say without more context, but first I would ensure you're on the latest version of Dart/Flutter and ensure you don't have "All exceptions" ticked here:

![image](https://github.com/Dart-Code/Dart-Code/assets/1078012/eecf801a-9501-4922-a2e9-e0959e9d54d8)

If that doesn't seem to be your problem, please open a new issue with steps to reproduce the issue and a screenshot that includes the exception details from the Variables pane and the Call Stack visible.
