### ISSUE TITLE
Completion for @override doesn't work well at the end of a class

### ISSUE THREAD

**Issue by timsneath** [Dart-Code/Dart-Code#3182] opened 2021-03-06 20:22 UTC
**Describe the bug**
DartCode is over-eager to offer class autocompletions to attributes. See the screenshot: here it should ideally be offering me `@override` as the completion, rather than trying to auto-import random classes from `dart:io` :) 

**To Reproduce**
Create a class, attempt to add an override (e.g. `toString()`)

**Expected behavior**
Either offer me autocomplete for available attributes, or don't offer me autocomplete. The proffered choices will always create a syntax error.

**Screenshots**
![image](https://user-images.githubusercontent.com/2319867/110219796-29f38d00-7e76-11eb-9b43-6a88e3e020e0.png)

**Versions (please complete the following information):**
 - VS Code version: 1.54.1
 - Dart extension version: 3.20.1
 - Dart/Flutter SDK version: 2.0 stable

(preview LSP is on)

**Comment by DanTup** [comment] 2021-03-07 12:24
I think this is the same as https://github.com/dart-lang/sdk/issues/32677 and/or https://github.com/dart-lang/sdk/issues/42266. Given the code above, the parser doesn't create an annotation (annotations are normally attached to other nodes, but there isn't on here) so the completion doesn't have the right context and produces bad results.

I think it will require some parser changes (perhaps to create a synthetic element to attach the annotation to) in order to fix.

**Comment by DanTup** [comment] 2021-03-08 10:50
Closing this as a dupe of https://github.com/dart-lang/sdk/issues/42266. If I insert a method below, then the completion works as expected, so it's definitely restricted only to where there isn't a node for the annotation.

**Comment by DanTup** [comment] 2022-08-23 10:39
The issue I closed this as a dupe of (completing the method names) was fixed, but it didn't resolve this issue (completing an annotation itself at the end of the class).

**Comment by DanTup** [comment] 2022-08-24 19:44
Fixed by https://github.com/dart-lang/sdk/commit/ece330a70089a8d82aace31d1cd9a89d0064f7d0.

**Closed by DanTup** 2022-08-24 19:44 UTC
Labels: is bug, in editor, in lsp/analysis server
