### ISSUE TITLE
vscode 3.23.0 can not infer path but in 3.22.0 is ok

### ISSUE THREAD

**Issue by Silentdoer** [Dart-Code/Dart-Code#3390] opened 2021-06-08 00:52 UTC
vscode 3.23.0 can not infer path but in 3.22.0 is ok;
such as import 'package....' will not show available completion'

**Comment by DanTup** [comment] 2021-06-08 09:35
Do you mean the code completion does not _open_ automatically, or that it does not work at all?

For example if you press `ctrl`+`space` to manually trigger completion, does it work?

<img width="678" alt="Screenshot 2021-06-08 at 10 35 10" src="https://user-images.githubusercontent.com/1078012/121161848-49b79a00-c845-11eb-85f8-efa25215dba1.png">

**Comment by hristo-kanchev** [comment] 2021-06-08 10:56
Duplicate of https://github.com/Dart-Code/Dart-Code/issues/3385

**Closed** 2021-06-08 11:33 UTC
Labels: duplicate
