### ISSUE TITLE
iOS devices not detected until window is reloaded/VSCode restarted

### ISSUE THREAD

**Issue by jamie1192** [Dart-Code/Dart-Code#2659] opened 2020-07-22 04:26 UTC
New issue here as requested in #1634 

I've found that there's a particular use case where iOS devices are not detected in VSCode (but have no issues seeing it in the device list when running `flutter doctor -v`.)

Scenario 1:
* boot Macbook 
* open VSCode with no iOS device connected 
* connect iOS device via usb, VSCode doesn't detect it
daemon log for this:
```
Dart Code extension: 3.12.2
Flutter extension: 3.12.2 (not activated)

App: Visual Studio Code
Version: 1.47.2
Platform: mac

Workspace type: Flutter
Multi-root?: false

Dart SDK:
    Loc: /Users/{username}/Library/flutter/bin/cache/dart-sdk
    Ver: 2.8.4
Flutter SDK:
    Loc: /Users/{username}/Library/flutter
    Ver: 1.17.5

HTTP_PROXY: undefined
NO_PROXY: undefined

Wed Jul 22 2020 [14:05:38 GMT+1000 (Australian Eastern Standard Time)] Log file started
[2:05:38 PM] [FlutterDaemon] [Info] Spawning /Users/{username}/Library/flutter/bin/flutter with args ["daemon"]
[2:05:38 PM] [FlutterDaemon] [Info] ..  in /Users/{username}/Library/flutter
[2:05:38 PM] [FlutterDaemon] [Info] ..  with {"toolEnv":{"FLUTTER_HOST":"VSCode","PUB_ENVIRONMENT":"vscode.dart-code"}}
[2:05:38 PM] [FlutterDaemon] [Info]     PID: 39125
[2:05:38 PM] [FlutterDaemon] [Info] ==> [{"id":"1","method":"emulator.getEmulators"}]
[2:05:38 PM] [FlutterDaemon] [Info] <== Starting device daemon...
[2:05:38 PM] [FlutterDaemon] [Info] <== [{"event":"daemon.connected","params":{"version":"0.5.3","pid":39187}}]
[2:05:38 PM] [FlutterDaemon] [Info] ==> [{"id":"2","method":"device.enable"}]
[2:05:39 PM] [FlutterDaemon] [Info] <== [{"id":"1","result":[{"id":"Pixel_2_XL-_SDK_30","name":"Pixel 2 XL- SDK 30","category":"mobile","platformType":"android"},{"id":"apple_ios_simulator","name":"iOS Simulator","category":"mobile","platformType":"ios"}]}]
[2:05:41 PM] [FlutterDaemon] [Info] <== [{"id":"2","result":[null,null,null,null,null,null]}]
[2:05:43 PM] [FlutterDaemon] [Info] <== [{"event":"device.added","params":{"id":"{redacted-deviceID}","name":"Pixel 2","platform":"android-arm64","emulator":false,"category":"mobile","platformType":"android","ephemeral":true,"emulatorId":null}}]
[2:05:43 PM] [FlutterDaemon] [Info] ==> [{"id":"3","method":"daemon.getSupportedPlatforms","params":{"projectRoot":"/Users/{username}/Workspace/{projectName}"}}]
[2:05:43 PM] [FlutterDaemon] [Info] <== [{"id":"3","result":{"platforms":["ios","android"]}}]
[2:05:54 PM] [FlutterDaemon] [Info] ==> [{"id":"4","method":"daemon.getSupportedPlatforms","params":{"projectRoot":"/Users/{username}/Workspace/{projectName}"}}]
[2:05:54 PM] [FlutterDaemon] [Info] <== [{"id":"4","result":{"platforms":["ios","android"]}}]
[2:05:54 PM] [FlutterDaemon] [Info] ==> [{"id":"5","method":"emulator.getEmulators"}]
[2:05:54 PM] [FlutterDaemon] [Info] <== [{"id":"5","result":[{"id":"Pixel_2_XL-_SDK_30","name":"Pixel 2 XL- SDK 30","category":"mobile","platformType":"android"},{"id":"apple_ios_simulator","name":"iOS Simulator","category":"mobile","platformType":"ios"}]}]
```

Scenario 2:
* After doing the above, leave iOS device connected
* run Reload Window command via VSCode
* Device is now detected once extensions have loaded
daemon log for this scenario:
```
!! PLEASE REVIEW THIS LOG FOR SENSITIVE INFORMATION BEFORE SHARING !!

Dart Code extension: 3.12.2
Flutter extension: 3.12.2 (not activated)

App: Visual Studio Code
Version: 1.47.2
Platform: mac

Workspace type: Flutter
Multi-root?: false

Dart SDK:
    Loc: /Users/{username}/Library/flutter/bin/cache/dart-sdk
    Ver: 2.8.4
Flutter SDK:
    Loc: /Users/{username}/Library/flutter
    Ver: 1.17.5

HTTP_PROXY: undefined
NO_PROXY: undefined

Wed Jul 22 2020 [14:08:47 GMT+1000 (Australian Eastern Standard Time)] Log file started
[2:08:47 PM] [FlutterDaemon] [Info] Spawning /Users/{username}/Library/flutter/bin/flutter with args ["daemon"]
[2:08:47 PM] [FlutterDaemon] [Info] ..  in /Users/{username}/Library/flutter
[2:08:47 PM] [FlutterDaemon] [Info] ..  with {"toolEnv":{"FLUTTER_HOST":"VSCode","PUB_ENVIRONMENT":"vscode.dart-code"}}
[2:08:47 PM] [FlutterDaemon] [Info]     PID: 39896
[2:08:47 PM] [FlutterDaemon] [Info] ==> [{"id":"1","method":"emulator.getEmulators"}]
[2:08:48 PM] [FlutterDaemon] [Info] <== Starting device daemon...
[2:08:48 PM] [FlutterDaemon] [Info] <== [{"event":"daemon.connected","params":{"version":"0.5.3","pid":39958}}]
[2:08:48 PM] [FlutterDaemon] [Info] ==> [{"id":"2","method":"device.enable"}]
[2:08:48 PM] [FlutterDaemon] [Info] <== [{"id":"1","result":[{"id":"Pixel_2_XL-_SDK_30","name":"Pixel 2 XL- SDK 30","category":"mobile","platformType":"android"},{"id":"apple_ios_simulator","name":"iOS Simulator","category":"mobile","platformType":"ios"}]}]
[2:08:51 PM] [FlutterDaemon] [Info] <== [{"id":"2","result":[null,null,null,null,null,null]}]
[2:08:51 PM] [FlutterDaemon] [Info] <== [{"event":"device.added","params":{"id":"{redacted-device-UUID}","name":"iPhone-SE","platform":"ios","emulator":false,"category":"mobile","platformType":"ios","ephemeral":true,"emulatorId":null}}]
[2:08:51 PM] [FlutterDaemon] [Info] ==> [{"id":"3","method":"daemon.getSupportedPlatforms","params":{"projectRoot":"/Users/{username}/Workspace/{projectName}"}}]
[2:08:51 PM] [FlutterDaemon] [Info] <== [{"id":"3","result":{"platforms":["ios","android"]}}]
[2:08:52 PM] [FlutterDaemon] [Info] <== [{"event":"device.added","params":{"id":"{redacted-deviceID}","name":"Pixel 2","platform":"android-arm64","emulator":false,"category":"mobile","platformType":"android","ephemeral":true,"emulatorId":null}}]
```

Flutter doctor -v output:
```bash
[✓] Flutter (Channel stable, v1.17.5, on Mac OS X 10.15.6 19G60d, locale en-AU)
    • Flutter version 1.17.5 at /Users/{username}/Library/flutter
    • Framework revision 8af6b2f038 (3 weeks ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/{username}/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.9.1

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[!] IntelliJ IDEA Ultimate Edition (version 2020.1.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] VS Code (version 1.47.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.2

[✓] Connected device (2 available)
    • Pixel 2   • {redacted-deviceID}              • android-arm64 • Android 11 (API 30)
    • iPhone-SE • {redacted-UUID} • ios           • iOS 13.5

```

**Comment by DanTup** [comment] 2020-07-22 08:17
Can you reproduce this reliably?

> - boot Macbook
> - open VSCode with no iOS device connected
> - connect iOS device via usb, VSCode doesn't detect it

If so, can you see if it happens outside of VS Code:

- boot macbook
- run `flutter daemon` in the terminal
- paste in `[{"id":"2","method":"device.enable"}]` and press enter (you should see a response)
- connect iOS device via USB

This is essentially the same thing VS Code is doing, so I would expect you'd see the same issue. If so, repeating it with `flutter daemon -v` might be more revealing (verbose logs) and then we should file an issue at flutter/flutter.

If it doesn't repro from the terminal, then I'll make a build that can run the daemon in verbose mode from VS Code so we can capture detailed logs there.

Thanks!

**Comment by DanTup** [comment] 2020-07-22 08:19
Also - does this happen for you with the Simulator? (Unfortunately I don't have an iPhone to test with!).

**Comment by jamie1192** [comment] 2020-07-23 05:15
@DanTup nope Simulator works perfectly, I can only reliably reproduce this with physical iOS devices.


> If so, can you see if it happens outside of VS Code:
> 
>     * boot macbook
> 
>     * run `flutter daemon` in the terminal
> 
>     * paste in `[{"id":"2","method":"device.enable"}]` and press enter (you should see a response)
> 
>     * connect iOS device via USB

following this, the terminal output:
```bash
 % flutter daemon
Starting device daemon...
[{"event":"daemon.connected","params":{"version":"0.5.3","pid":7498}}]
[{"id":"2","method":"device.enable"}] #<-- my input as instructed
[{"id":"2","result":[null,null,null,null,null,null]}]
[{"event":"device.added","params":{"id":"{redactedID}","name":"Pixel 2","platform":"android-arm64","emulator":false,"category":"mobile","platformType":"android","ephemeral":true,"emulatorId":null}}]
# connected iPhone SE here
[{"id":"2","method":"device.enable"}] #<-- input this again and the below was output
[{"id":"2","result":[null,null,null,null,null,null]}]

[{"event":"device.added","params":{"id":"{redactedID}","name":"iPhone-SE","platform":"ios","emulator":false,"category":"mobile","platformType":"ios","ephemeral":true,"emulatorId":null}}]
Oops; flutter has exited unexpectedly: "Exception: xcdevice observe restart failed".
 
A crash report has been written to /Users/{username}/Workspace/{project}/flutter_01.log.
This crash may already be reported. Check GitHub for similar crashes.
https://git.io/JJlHD

To report your crash to the Flutter team, first read the guide to filing a bug.
https://flutter.dev/docs/resources/bug-reports

Create a new GitHub issue by pasting this link into your browser and completing the issue template. Thank you!
https://git.io/JJlHy

```

here is said crash report Flutter created:

```
Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter daemon

## exception

_Exception: Exception: xcdevice observe restart failed

#0      XCDevice._startObservingTetheredIOSDevices (package:flutter_tools/src/macos/xcode.dart:334:9)
#1      _runGuarded (dart:async/stream_controller.dart:820:24)
#2      _BroadcastStreamController._subscribe (dart:async/broadcast_stream_controller.dart:215:7)
#3      _ControllerStream._createSubscription (dart:async/stream_controller.dart:833:19)
#4      _StreamImpl.listen (dart:async/stream_impl.dart:475:9)
#5      IOSDevices.startPolling (package:flutter_tools/src/ios/devices.dart:83:75)
<asynchronous suspension>
#6      DeviceDomain.enable (package:flutter_tools/src/commands/daemon.dart:794:28)
#7      Domain.handleCommand.<anonymous closure> (package:flutter_tools/src/commands/daemon.dart:227:34)
#8      new Future.sync (dart:async/future.dart:224:31)
#9      Domain.handleCommand (package:flutter_tools/src/commands/daemon.dart:225:5)
#10     Daemon._handleRequest (package:flutter_tools/src/commands/daemon.dart:152:28)
#11     _rootRunUnary (dart:async/zone.dart:1192:38)
#12     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#13     _CustomZone.runUnaryGuarded (dart:async/zone.dart:987:7)
#14     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#15     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:266:7)
#16     _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:134:11)
#17     _MapStream._handleData (dart:async/stream_pipe.dart:234:10)
#18     _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:166:13)
#19     _rootRunUnary (dart:async/zone.dart:1192:38)
#20     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#21     _CustomZone.runUnaryGuarded (dart:async/zone.dart:987:7)
#22     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#23     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:266:7)
#24     _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:134:11)
#25     _WhereStream._handleData (dart:async/stream_pipe.dart:209:12)
#26     _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:166:13)
#27     _rootRunUnary (dart:async/zone.dart:1192:38)
#28     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#29     _CustomZone.runUnaryGuarded (dart:async/zone.dart:987:7)
#30     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#31     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:266:7)
#32     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:70:11)
#33     _EventSinkWrapper.add (dart:async/stream_transformers.dart:17:11)
#34     _StringAdapterSink.add (dart:convert/string_conversion.dart:238:11)
#35     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:152:13)
#36     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:127:5)
#37     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:165:5)
#38     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:122:24)
#39     _rootRunUnary (dart:async/zone.dart:1192:38)
#40     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#41     _CustomZone.runUnaryGuarded (dart:async/zone.dart:987:7)
#42     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#43     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:266:7)
#44     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:70:11)
#45     _EventSinkWrapper.add (dart:async/stream_transformers.dart:17:11)
#46     _StringAdapterSink.add (dart:convert/string_conversion.dart:238:11)
#47     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:243:7)
#48     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:314:20)
#49     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:307:5)
#50     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:74:18)
#51     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:122:24)
#52     _rootRunUnary (dart:async/zone.dart:1192:38)
#53     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#54     _CustomZone.runUnaryGuarded (dart:async/zone.dart:987:7)
#55     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#56     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:266:7)
#57     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:779:19)
#58     _StreamController._add (dart:async/stream_controller.dart:655:7)
#59     _StreamController.add (dart:async/stream_controller.dart:597:5)
#60     _Socket._onData (dart:io-patch/socket_patch.dart:1982:41)
#61     _rootRunUnary (dart:async/zone.dart:1196:13)
#62     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#63     _CustomZone.runUnaryGuarded (dart:async/zone.dart:987:7)
#64     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#65     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:266:7)
#66     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:779:19)
#67     _StreamController._add (dart:async/stream_controller.dart:655:7)
#68     _StreamController.add (dart:async/stream_controller.dart:597:5)
#69     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1527:33)
#70     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1019:14)
#71     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#72     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#73     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#74     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)

## flutter doctor


[✓] Flutter (Channel stable, v1.17.5, on Mac OS X 10.15.6 19G60d, locale en-AU)
    • Flutter version 1.17.5 at /Users/{username}/Library/flutter
    • Framework revision 8af6b2f038 (3 weeks ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/{username}/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.9.1

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[!] IntelliJ IDEA Ultimate Edition (version 2020.1.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] VS Code (version 1.47.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.2

[✓] Connected device (2 available)
    • Pixel 2   • {redactedID}              • android-arm64 • Android 11 (API 30)
    • iPhone-SE • {redactedID} • ios           • iOS 13.5

! Doctor found issues in 1 category.
```

**Comment by DanTup** [comment] 2020-07-23 09:50
@jamie1192 thanks for testing! Seems like an issue that will need to be fixed in Flutter - I see you've already filed a bug there so I'll close this one as a dupe of that. Thanks!

**Closed by DanTup** 2020-07-23 09:50 UTC
Labels: awaiting info
