### ISSUE TITLE
Can not launch simulator with “log: must be admin to run stream command” message

### ISSUE THREAD

**Issue by jaxondu** [Dart-Code/Dart-Code#1168] opened 2018-08-22 08:28 UTC
Run VSCode/Dart Code with a login user who has no admin right, launch app to iOS simulator, only blank white screen appear. When run the app in shell with “flutter run”, the app runs fine in simulator. Running both ways the console will have this message “log: Must be admin to run stream command”. This is similar to this Flutter issue 
https://github.com/flutter/flutter/issues/18409

**Comment by DanTup** [comment] 2018-08-22 08:37
I think this is just a dupe of https://github.com/flutter/flutter/issues/18409 - I don't think it can be fixed in Dart Code but needs fixing in Flutter (though I'm curious that someone claims to have fixed it with a `PATH` change!).

I'll see if I can repro on my MacBook and post back in that thread.

**Closed by DanTup** 2018-08-22 08:37 UTC
