### ISSUE TITLE
[Question] How to pass arguments to F5 (RUN-DEBUG) ?

### ISSUE THREAD

**Issue by fabiojansenbr** [Dart-Code/Dart-Code#2405] opened 2020-04-28 15:24 UTC
When i run my flutter apps with F5(debug) im receiving some strange messages on terminal, like:
D/ViewRootImpl@38eee14[MainActivity]( 7994): ViewPostIme pointer 0.

Is there any way to pass an argument to F5 shortcut to hide this message?

In my terminal, i can hide the message with this command: flutter run | grep -v "D/ViewRootImpl"

Thanks

**Comment by DanTup** [comment] 2020-04-28 15:34
It's possible to pass arguments to the `flutter run` process, but it's not possible to do what you want here, as `| grep` isn't a valid argument for starting a process.

There are some related issues about having filters in VS Code or having less verbose output from Flutter here:

- https://github.com/microsoft/vscode/issues/93750
- https://github.com/flutter/flutter/issues/42849

I don't think there's really a great fix in the VS Code extension. We could add settings that allow adding regexes to filter the logs, but it feels like a very clumsy workaround. In any case, I'll consider this a dupe of https://github.com/Dart-Code/Dart-Code/issues/1980 since we do already have an issue in this repo for the same problem.

**Closed by DanTup** 2020-04-28 15:34 UTC
