### ISSUE TITLE
Pressing the "run" button on a test case does nothing (almost)

### ISSUE THREAD

**Issue by incendial** [Dart-Code/Dart-Code#4541] opened 2023-05-13 08:22 UTC
**Describe the bug**
Pressing the "run" button does not run the test. I tried both on the pre-release and stable - the result is the same. I think it might be connected to me having Dart 3.1.0-63.1.beta (flutter beta channel).
Debugging works as expected (but feels a bit slower (?)), dart test also works.

https://github.com/Dart-Code/Dart-Code/assets/21116742/820182ce-2b9a-43cb-8f80-4affb37f12b1

and yes, the progress bar is infinite, only reloading the IDE helps.

**To Reproduce**
Can you try with the same setup? If the problem won't repro, I'll try to extract steps.

**Please complete the following information:**
 - Operating System and version: macOS
 - VS Code version: Version: 1.78.1
 - Dart extension version: v3.64.0
 - Dart/Flutter SDK version: 3.1.0-63.1.beta

**Comment by incendial** [comment] 2023-05-13 08:25
Clicking on the "play |>" button leads to the same behaviour.

**Comment by DanTup** [comment] 2023-05-13 09:54
Is this inside the SDK? If so, this may be related to https://github.com/Dart-Code/Dart-Code/issues/4502. The test functionality for running individual tests is supposed to be disabled for the SDK because of some issues noted in there (running `dart test` can break things).

In that case, the Run/Debug links on each test should be hidden though so you can't click them. What happens if you right click on the test icon in the gutter, does it have run/debug icons there? If so, we're not detecting the SDK correctly. If it doesn't, then it's probably just a CodeLens issue.

**Comment by incendial** [comment] 2023-05-13 09:54
It's not inside the SDK.

**Comment by incendial** [comment] 2023-05-13 09:56
> What happens if you right click on the test icon in the gutter, does it have run/debug icons there?

This?
<img width="316" alt="Screenshot 2023-05-13 at 13 55 52" src="https://github.com/Dart-Code/Dart-Code/assets/21116742/81ed99be-b067-47b5-b707-84eb03a09a4d">

**Comment by DanTup** [comment] 2023-05-13 09:57
Ah sorry, I was mislead by similar looking paths. I presume this is DCM? Will try and repro later (not at proper machine atm). In the meantime, running the **Dart: Capture Debugging Logs** command before trying to run (then after a short while, clicking Cancel to stop logging and open the log file) might provide some useful info (I notice the "progress" indicator on the debug side bar seems to be visible for a while).

> This?

Yep! Although since it's not the SDK, that's less relevant :) It looks like it should for non-SDK projects.

**Comment by incendial** [comment] 2023-05-13 10:00
>Ah sorry, I was mislead by similar looking paths

Hm... 😅

> I presume this is DCM? Will try and repro later (not at proper machine atm).

Yes, but not the open sourced version. Yesterday I was on Dart 3.0-beta and everything was fine. So my guess is that something is wrong in Dart 3.1.0-63.1.beta

**Comment by incendial** [comment] 2023-05-13 10:05
> In the meantime, running the Dart: Capture Debugging Logs 

Does not see anything suspicious here...

[Dart-Code-Log-2023-04-06 14-03-24.txt](https://github.com/Dart-Code/Dart-Code/files/11469385/Dart-Code-Log-2023-04-06.14-03-24.txt)

**Comment by incendial** [comment] 2023-05-13 10:05
Noticed a strange thing though, sending a video.

**Comment by incendial** [comment] 2023-05-13 10:07
But tests never end.

https://github.com/Dart-Code/Dart-Code/assets/21116742/36efb49f-34ee-41bf-b9dc-b7d54a9e02fe

**Comment by DanTup** [comment] 2023-05-15 10:27
Thanks - using the beta I can definitely reproduce some of this.. taking a look, thanks!

**Comment by DanTup** [comment] 2023-05-15 10:36
This feels a bit like https://github.com/dart-lang/sdk/issues/52222.. however, that was fixed in https://github.com/dart-lang/sdk/commit/7a6352a9b13b3b4ae80d24d73fdc31102f505e41 which was two weeks ago, and the beta is from only a week ago.

Weirdly, I don't seem to be able to repro on the latest bleeding-edge SDK. I don't want to say it's fixed without understanding what changed though.

**Comment by DanTup** [comment] 2023-05-15 10:42
Oh, it is that. The beta was tagged last week, but the commits in it are older. The beta branch is from b4c5f310d703da03a85737a1c317d3d4419fbf0b May 2nd, 12:23 AM but my fix was landed May 2nd, 7:35pm.

So although the issue is fixed and didn't affect the stable release (or current bleeding edge), the current Dart beta is a little out of date and was taken between the break and the fix.

So, I would avoid that beta for Dart and roll back to the previous. When the next beta drops, it should include the fix.

This does make me wonder what version of the Dart SDK shipped in the recent Flutter stable though (because I thought it would be unaffected). I'll check this shortly and post back.

**Comment by incendial** [comment] 2023-05-15 10:46
Stable has some compilation issues with the patterns, so I decided to switch to the beta instead. But good to know that this one is already addressed, thank you.

Do you by any chance know when the new beta version will be published?

**Comment by incendial** [comment] 2023-05-15 10:47
Right now I run test via copy absolute path + cli 😁🥲

**Comment by incendial** [comment] 2023-05-15 10:48
The good part is it seems to be faster + keeps the output in the console which is quite handy🤔

**Comment by DanTup** [comment] 2023-05-15 10:51
> This does make me wonder what version of the Dart SDK shipped in the recent Flutter stable though (because I thought it would be unaffected). I'll check this shortly and post back.

Ok, my original understand was correct. The change that broke this (https://github.com/dart-lang/sdk/commit/5ef021b116bc9bf08daf447b79dfe7815bd29490) was _not_ in the stable 3.0. Stable was branched before this was broken, so only the beta is affected (although things were slightly different for Flutter, but that was cherry-picked, and you are running using the Dart debug adapter here, even though it's coming from Dart inside the Flutter SDK).

> Do you by any chance know when the new beta version will be published?

Afraid not - I'm not very familiar with the release process. If you can't use stable, you could try master or a bleeding-edge Dart SDK build in the meantime, but they obvious come with potential other risks/breakages.


> The good part is it seems to be faster + keeps the output in the console which is quite handy🤔

How much faster? Are you measuring Run or Debug (debug will certainly be slower, but I wouldn't expect Run to differ much). I think the Debug Console clearing is done by VS Code unfortunately, so not something we can change.

**Comment by DanTup** [comment] 2023-05-15 10:51
Closing as a dupe of https://github.com/dart-lang/sdk/issues/52222 since I believe fixed, but if you're seeing a big discrepancy in Run performance versus CLI, please do post back (or file a new issue) :-)

**Closed by DanTup** 2023-05-15 10:52 UTC
Labels: duplicate
