### ISSUE TITLE
Search usages shows stale results after switching git branches

### ISSUE THREAD

**Issue by Aetet** [Dart-Code/Dart-Code#269] opened 2017-03-15 19:44 UTC
I have project with large codebase. Sometimes `editor.action.referenceSearch.trigger ` does not show me all the results. When I search with regular grep - open this file - after this everything works fine. What is the workaround for it? #

**Comment by DanTup** [comment] 2017-03-15 22:23
Can you reliably reproduce this? Is the project your seeing this on open source?

**Comment by Aetet** [comment] 2017-03-16 04:21
Yes. It is reproduced reliably. No it is not open source project. I can debug project locally to figure out what is the reason. Atom version https://github.com/dart-atom/dartlang works fine.

**Comment by DanTup** [comment] 2017-03-16 07:45
Interesting; both Atom and Dart Code use the same analysis server from the SDK so I wonder whether the issue is in the mapping of Code.

You can enable the analyzer instrumentation file by setting the option `dart.analyzerInstrumentationLogFile` in your VS Code options (note: you won't get intellisense and it might tell you it's not a valid option because it's a hidden option) to generate a log of what comes back from the analyzer (that'll help figure out if the problem is in the analyzer or not). It will generate a very large file though!

**Comment by Aetet** [comment] 2017-03-22 18:47
Thanks for reply. I bring it on for me. I hope it won't be gathered without percaution in next version ;-) As I will have result I reply for this issue.

**Comment by DanTup** [comment] 2017-03-22 19:26
> I hope it won't be gathered without percaution in next version

Not sure what this means - the log option will remain enabled until you remove it, so you'll need to remember to remove it in the future once you have a useful log for it.

**Comment by Aetet** [comment] 2017-03-22 19:30
I mean content of this file won't be transfered by http to some server occasionally.

**Comment by DanTup** [comment] 2017-03-22 19:35
Enabling these logs only records to the filename specified, nothing it sent anywhere (the analyzerInstrumentationLogFile behaviour is actually created by the Dart team and not part of Dart Code - it just gets passed to the Dart analyzer).

The only things Dart Code ever transmits automatically are some basic analytics that used to build [these charts](https://datastudio.google.com/open/0B7od1qw9-sxIZXYzWEFVWmJXRDg).

Hope this helps!

**Comment by Aetet** [comment] 2017-05-15 09:57
Currently I reproduce this issue. It occurs after switch git branch and analyzer not reanalyze new files. And you need reanalyze it manually.

**Comment by DanTup** [comment] 2017-05-15 19:33
Thanks for the info; I'll see if I can repro. How are you changing git branches - via command line or using something like GitHub desktop?

**Comment by Aetet** [comment] 2017-05-16 12:15
Command line

**Comment by DanTup** [comment] 2017-06-07 10:40
I've spent a little while testing this and cannot reproduce. Here's what I did:

1. Created a file `one.dart` and added a function that prints to the console
2. Committed the file to `master`
3. Created a new branch, named `two` and added a new file `two.dart` which `imports` `one.dart` and calls the function
4. Committed the file to `two`
5. Switched back to `master`, reloaded Code and did `Find References` on the function - no results (as expected)
6. Switched to `two` branch (I tried both using the command line `git co two` and using GitHub desktop)
7. Again did `Find References` on the function - the result from `two.dart` showed up

Can you confirm if these are equivalent to the steps you're performing? Also, are you sure that after changing branch that analysis has finished? (eg., does it say `Analyzing...` in the status bar?). Also, can you confirm what OS you're using?

**Comment by DanTup** [comment] 2018-02-21 15:18
Has this been seen recently?

**Comment by Aetet** [comment] 2018-02-21 17:39
That's difficult question. Because I have issues with branch switch with build_runner cache and doesn't know is it analyzer issue or build_runner.

**Comment by DanTup** [comment] 2018-02-21 17:50
Ugh ;( What OS are you using? We have #316 which seems similar (Mac OS).

**Comment by Aetet** [comment] 2018-02-21 18:14
Linux 16.04.

**Comment by DanTup** [comment] 2018-05-03 16:58
Are you still seeing this?

**Comment by pq** [comment] 2018-05-16 17:04
@DanTup : I can't recall exactly but maybe @scheglov @bwilkerson can?  Changing git branches used to consistently botch things up but can't recall what's been done about it...

**Comment by DanTup** [comment] 2018-05-17 06:39
Yeah, I remember we did some investigation some time ago but never really got to the bottom of it. Something I've heard recently is that people sometimes get confused when they have a modified file open in VS Code and then do a git operation - VS Code shows no warning that the underlying file has changed *until the user tries to save*. This makes it easy to work with a stale file for a while in the editor and not really notice (it does have a dirty indicator, but with lots of tabs open this can quickly be off-screen).

I'm gonna close this for now, but if @Aetet is still seeing this one recent builds, we can re-open and look further.

**Closed by DanTup** 2018-05-17 06:39 UTC
Labels: awaiting info, is bug
