### ISSUE TITLE
Create missing override is producing incorrect text

### ISSUE THREAD

**Issue by lukepighetti** [Dart-Code/Dart-Code#2571] opened 2020-06-18 20:09 UTC
I have seen this a few times in the past on a friends computer and I just now saw this myself on my own project.

<img width="568" alt="Screen Shot 2020-06-18 at 4 08 06 PM" src="https://user-images.githubusercontent.com/666539/85067058-0d93b100-b17e-11ea-84d4-a74d304ae805.png">

What's interesting is if I hit "undo" once, it goes back to a correct result.

<img width="534" alt="Screen Shot 2020-06-18 at 4 10 24 PM" src="https://user-images.githubusercontent.com/666539/85067156-39af3200-b17e-11ea-8312-c34702dba893.png">

**Comment by DanTup** [comment] 2020-06-22 11:36
Thanks for the report! This is an issue in the analysis server and there's an open issue at dart-lang/sdk#41147 so I'll close this as a dupe of that.

**Closed** 2020-06-22 11:36 UTC
Labels: upstream in dart / flutter
