### ISSUE TITLE
Device not showing up in VSCode, but detected in flutter

### ISSUE THREAD

**Issue by Iamjustin25** [Dart-Code/Dart-Code#4132] opened 2022-08-31 08:22 UTC
![187211818-7f4dabb5-0365-433c-b06d-acf9a9f6980c](https://user-images.githubusercontent.com/91855195/187630574-63cd2578-dc2c-4667-a543-0219aebc35aa.png)

flutter devices
3 connected devices:

4d006569ec9e5200 (mobile) • 4d006569ec9e5200 • android-arm • Android 4.4.4 (API 19)
Linux (desktop) • linux • linux-x64 • Kali GNU/Linux Rolling
5.18.0-kali2-amd64
Chrome (web) • chrome • web-javascript • Google Chrome 103.0.5060.114

flutter devices -v
[ +118 ms] executing: uname -m
[ +44 ms] Exit code 0 from: uname -m
[ ] x86_64
[ +7 ms] executing: [/home/jus/development/flutter/] git -c log.showSignature=false log -n 1
--pretty=format:%H
[ +30 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[ ] https://github.com/flutter/flutter/commit/f1875d570e39de09040c8f79aa13cc56baab8db1
[ +1 ms] executing: [/home/jus/development/flutter/] git tag --points-at
https://github.com/flutter/flutter/commit/f1875d570e39de09040c8f79aa13cc56baab8db1
[+1118 ms] Exit code 0 from: git tag --points-at https://github.com/flutter/flutter/commit/f1875d570e39de09040c8f79aa13cc56baab8db1
[ ] 3.0.5
[ +19 ms] executing: [/home/jus/development/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[ +5 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[ ] origin/stable
[ ] executing: [/home/jus/development/flutter/] git ls-remote --get-url origin
[ +4 ms] Exit code 0 from: git ls-remote --get-url origin
[ ] https://github.com/flutter/flutter.git
[ +133 ms] executing: [/home/jus/development/flutter/] git rev-parse --abbrev-ref HEAD
[ +4 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[ ] stable
[ +134 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[ ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[ ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[ ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[ +16 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[ ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[ ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[ ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[ ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[ ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[ ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[ ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +125 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[ ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[ ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[ ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[ ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[ ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[ ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[ ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[ ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[ ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[ ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[ ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[ ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[ ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[ ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[ ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[ ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[ ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[ ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[ ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[ ] Artifact Instance of 'PubDependencies' is not required, skipping update.
[ +45 ms] executing: /home/jus/Android/Sdk/platform-tools/adb devices -l
[ +114 ms] List of devices attached
4d006569ec9e5200 device usb:1-1.2 transport_id:1
[ +5 ms] 3 connected devices:

[ +3 ms] /home/jus/Android/Sdk/platform-tools/adb -s 4d006569ec9e5200 shell getprop
[ +72 ms] ro.hardware = sc8830
[ ] ro.build.characteristics = phone
[ +250 ms] 4d006569ec9e5200 (mobile) • 4d006569ec9e5200 • android-arm • Android 4.4.4 (API 19)
[ +3 ms] Linux (desktop) • linux • linux-x64 • Kali GNU/Linux Rolling
5.18.0-kali2-amd64
[ +1 ms] Chrome (web) • chrome • web-javascript • Google Chrome
103.0.5060.114
[ +3 ms] executing: /home/jus/Android/Sdk/platform-tools/adb devices -l
[ +7 ms] List of devices attached
4d006569ec9e5200 device usb:1-1.2 transport_id:1
[ +22 ms] "flutter devices" took 743ms.
[ +260 ms] ensureAnalyticsSent: 253ms
[ +2 ms] Running shutdown hooks
[ ] Shutdown hooks complete
[ ] exiting with code 0

VS Code (version 1.70.1)

flutter doctor -v
[✓] Flutter (Channel stable, 3.0.5, on Kali GNU/Linux Rolling 5.18.0-kali2-amd64, locale ar_EG.UTF-8)
• Flutter version 3.0.5 at /home/jus/development/flutter
• Upstream repository https://github.com/flutter/flutter.git
• Framework revision https://github.com/flutter/flutter/commit/f1875d570e39de09040c8f79aa13cc56baab8db1 (7 weeks ago), 2022-07-13 11:24:16 -0700
• Engine revision e85ea0e79c
• Dart version 2.17.6
• DevTools version 2.12.2

Checking Android licenses is taking an unexpectedly long time...[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
• Android SDK at /home/jus/Android/Sdk/
• Platform android-33, build-tools 33.0.0
• Java binary at: /home/jus/Downloads/android-studio/jre/bin/java
• Java version openjdk version "11.0.12" 2021-07-20
• All Android licenses accepted.

[✓] Chrome - develop for the web
• Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
• Debian clang version 14.0.6-2
• cmake version 3.23.3
• ninja version 1.11.0
• pkg-config version 0.29.2

[✓] Android Studio (version 2021.2)
• Android Studio at /home/jus/Downloads/android-studio
• Flutter plugin version 69.0.2
• Dart plugin version 212.5744
• Java version openjdk version "11.0.12" 2021-07-20

[✓] Android Studio
• Android Studio at /home/jus/Downloads/android-studio/
• Flutter plugin can be installed from:
hammer https://plugins.jetbrains.com/plugin/9212-flutter
• Dart plugin can be installed from:
hammer https://plugins.jetbrains.com/plugin/6351-dart
• android-studio-dir = /home/jus/Downloads/android-studio/
• Java version openjdk version "11.0.12" 2021-07-20

[✓] VS Code (version 1.70.1)
• VS Code at /usr/share/code
• Flutter extension version 3.46.0

[✓] Connected device (3 available)
• 4d006569ec9e5200 (mobile) • 4d006569ec9e5200 • android-arm • Android 4.4.4 (API 19)
• Linux (desktop) • linux • linux-x64 • Kali GNU/Linux Rolling
5.18.0-kali2-amd64
• Chrome (web) • chrome • web-javascript • Google Chrome 103.0.5060.114

[✓] HTTP Host Availability
• All required HTTP hosts are available

• No issues found!

**Comment by DanTup** [comment] 2022-08-31 09:09
@Iamjustin25 can you post the full output of running **Flutter: Run Flutter Doctor** from the VS Code command palette? (the output can differ from running it at the terminal because it doesn't pick up anything you have in terminal startup scripts, which can often be the cause of issues like this).

Thanks!

**Comment by Iamjustin25** [comment] 2022-08-31 11:22
@DanTup 
is that rigth??

Run Flutter Doctor 
Command 'Run' not found, did you mean:
  command 'zun' from deb python3-zunclient
Try: sudo apt install <deb name>

**Comment by DanTup** [comment] 2022-08-31 11:24
@Iamjustin25 press `F1` to open the VS Code command palette, and then search for it there:

<img width="408" alt="Screenshot 2022-08-31 at 12 24 18" src="https://user-images.githubusercontent.com/1078012/187667688-eef0be10-fcf5-4f0e-8123-e82bc7959ac1.png">

**Comment by Iamjustin25** [comment] 2022-08-31 11:29
@DanTup  [flutter] flutter doctor -v
/usr/bin/env: 'bash': No such file or directory
exit code 127

**Comment by DanTup** [comment] 2022-08-31 11:45
@Iamjustin25 can you post the output of running `where bash` and `echo $PATH` in a terminal (removing anything sensitive)?

**Comment by DanTup** [comment] 2022-08-31 11:46
Could you also press `F1` and run the **Dart: Open Extension Log** command and post the log (with anything sensitive removed). Thanks!

**Comment by Iamjustin25** [comment] 2022-08-31 11:53
@DanTup  where: command not found

/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/games:/usr/games

!! PLEASE REVIEW THIS LOG FOR SENSITIVE INFORMATION BEFORE SHARING !!

Dart Code extension: 3.46.1
Flutter extension: 3.46.0 (not activated)

App: Visual Studio Code
Version: 1.70.1
Platform: linux

HTTP_PROXY: undefined
NO_PROXY: undefined

Logging Categories:
    General

Wed Aug 31 2022 [13:14:57 GMT+0200 (توقيت شرق أوروبا الرسمي)] Log file started
[١:١٤:٥٧ م] [General] [Info] Searching for SDKs...
[١:١٤:٥٧ م] [General] [Info] Environment PATH:
[١:١٤:٥٧ م] [General] [Info]     /home/jus/.local/bin
[١:١٤:٥٧ م] [General] [Info]     /usr/local/sbin
[١:١٤:٥٧ م] [General] [Info]     /usr/sbin
[١:١٤:٥٧ م] [General] [Info]     /sbin
[١:١٤:٥٧ م] [General] [Info]     /usr/local/bin
[١:١٤:٥٧ م] [General] [Info]     /home/jus/Desktop/development/flutter/bin/
[١:١٤:٥٧ م] [General] [Info]     /usr/lib/dart/bin
[١:١٤:٥٨ م] [General] [Info] Took 585ms to search for projects (5 levels)
[١:١٤:٥٨ م] [General] [Info] Took 38ms to filter out excluded projects (0 exclusion rules)
[١:١٤:٥٨ م] [General] [Info] Found Flutter project at /home/jus/development/flutter_apps/mytest:
			Mobile? true
			Web? false
			Create Trigger? false
			Flutter Repo? false
[١:١٤:٥٨ م] [General] [Info] Searching for flutter
[١:١٤:٥٨ م] [General] [Info]     Looking for flutter in:
[١:١٤:٥٨ م] [General] [Info]         /home/jus/development/flutter/bin/
[١:١٤:٥٨ م] [General] [Info]         /home/jus/development/flutter_apps/mytest
[١:١٤:٥٨ م] [General] [Info]         /home/jus/development/flutter_apps/mytest/bin
[١:١٤:٥٨ م] [General] [Info]         /home/jus/development/flutter/bin/
[١:١٤:٥٨ م] [General] [Info]         /home/jus/development/flutter_apps/mytest/.flutter
[١:١٤:٥٨ م] [General] [Info]         /home/jus/development/flutter_apps/mytest/.flutter/bin
[١:١٤:٥٨ م] [General] [Info]         /home/jus/development/flutter_apps/mytest/vendor/flutter
[١:١٤:٥٨ م] [General] [Info]         /home/jus/development/flutter_apps/mytest/vendor/flutter/bin
[١:١٤:٥٨ م] [General] [Info]         /home/jus/snap/flutter/common/flutter
[١:١٤:٥٨ م] [General] [Info]         /home/jus/snap/flutter/common/flutter/bin
[١:١٤:٥٨ م] [General] [Info]         /home/jus/flutter-sdk
[١:١٤:٥٨ م] [General] [Info]         /home/jus/flutter-sdk/bin
[١:١٤:٥٨ م] [General] [Info]         /google/flutter
[١:١٤:٥٨ م] [General] [Info]         /google/flutter/bin
[١:١٤:٥٨ م] [General] [Info]         /home/jus/.local/bin
[١:١٤:٥٨ م] [General] [Info]         /usr/local/sbin
[١:١٤:٥٨ م] [General] [Info]         /usr/sbin
[١:١٤:٥٨ م] [General] [Info]         /sbin
[١:١٤:٥٨ م] [General] [Info]         /usr/local/bin
[١:١٤:٥٨ م] [General] [Info]         /home/jus/Desktop/development/flutter/bin/
[١:١٤:٥٨ م] [General] [Info]         /usr/lib/dart/bin
[١:١٤:٥٩ م] [General] [Info]     Found at:
[١:١٤:٥٩ م] [General] [Info]         /home/jus/development/flutter/bin/
[١:١٤:٥٩ م] [General] [Info]         /home/jus/development/flutter/bin/
[١:١٤:٥٩ م] [General] [Info]     Candidate paths to be post-filtered:
[١:١٤:٥٩ م] [General] [Info]         /home/jus/development/flutter
[١:١٤:٥٩ م] [General] [Info]         /home/jus/development/flutter
[١:١٤:٥٩ م] [General] [Info]     Found at /home/jus/development/flutter
[١:١٤:٥٩ م] [General] [Info]     Returning SDK path /home/jus/development/flutter for flutter
[١:١٤:٥٩ م] [General] [Info] Searching for dart
[١:١٤:٥٩ م] [General] [Info]     Looking for dart in:
[١:١٤:٥٩ م] [General] [Info]         /home/jus/development/flutter/bin/cache/dart-sdk
[١:١٤:٥٩ م] [General] [Info]         /home/jus/development/flutter/bin/cache/dart-sdk/bin
[١:١٤:٥٩ م] [General] [Info]         /home/jus/development/flutter/bin/cache/dart-sdk/
[١:١٤:٥٩ م] [General] [Info]         /home/jus/development/flutter/bin/cache/dart-sdk/bin
[١:١٤:٥٩ م] [General] [Info]         /home/jus/.local/bin
[١:١٤:٥٩ م] [General] [Info]         /usr/local/sbin
[١:١٤:٥٩ م] [General] [Info]         /usr/sbin
[١:١٤:٥٩ م] [General] [Info]         /sbin
[١:١٤:٥٩ م] [General] [Info]         /usr/local/bin
[١:١٤:٥٩ م] [General] [Info]         /home/jus/Desktop/development/flutter/bin/
[١:١٤:٥٩ م] [General] [Info]         /usr/lib/dart/bin
[١:١٤:٥٩ م] [General] [Info]         /home/jus/development/flutter/bin/cache/dart-sdk
[١:١٤:٥٩ م] [General] [Info]         /home/jus/development/flutter/bin/cache/dart-sdk/bin
[١:١٤:٥٩ م] [General] [Info]     Found at:
[١:١٤:٥٩ م] [General] [Info]         /home/jus/development/flutter/bin/cache/dart-sdk/bin
[١:١٤:٥٩ م] [General] [Info]         /home/jus/development/flutter/bin/cache/dart-sdk/bin
[١:١٤:٥٩ م] [General] [Info]         /usr/lib/dart/bin
[١:١٤:٥٩ م] [General] [Info]         /home/jus/development/flutter/bin/cache/dart-sdk/bin
[١:١٤:٥٩ م] [General] [Info]     Candidate paths to be post-filtered:
[١:١٤:٥٩ م] [General] [Info]         /home/jus/development/flutter/bin/cache/dart-sdk
[١:١٤:٥٩ م] [General] [Info]         /home/jus/development/flutter/bin/cache/dart-sdk
[١:١٤:٥٩ م] [General] [Info]         /usr/lib/dart
[١:١٤:٥٩ م] [General] [Info]         /home/jus/development/flutter/bin/cache/dart-sdk
[١:١٤:٥٩ م] [General] [Info]     Found at /home/jus/development/flutter/bin/cache/dart-sdk
[١:١٤:٥٩ م] [General] [Info]     Returning SDK path /home/jus/development/flutter/bin/cache/dart-sdk for dart
[١:١٤:٥٩ م] [General] [Info] !! PLEASE REVIEW THIS LOG FOR SENSITIVE INFORMATION BEFORE SHARING !!

Dart Code extension: 3.46.1
Flutter extension: 3.46.0 (not activated)

App: Visual Studio Code
Version: 1.70.1
Platform: linux

Workspace type: Flutter
Analyzer type: LSP
Multi-root?: false

Dart SDK:
    Loc: /home/jus/development/flutter/bin/cache/dart-sdk
    Ver: 2.17.6
Flutter SDK:
    Loc: /home/jus/development/flutter
    Ver: 3.0.5

HTTP_PROXY: undefined
NO_PROXY: undefined
[١:١٤:٥٩ م] [General] [Info] Returning cached results for project search
[١:١٤:٥٩ م] [General] [Info] Activating Flutter extension for Flutter project...
[١:١٤:٥٩ م] [General] [Info] Extension:Startup timing: 1723ms
[١:١٤:٥٩ م] [General] [Info] Found 0 folders requiring "pub get":
[١:١٤:٥٩ م] [General] [Info] Caching Pub package names from pub.dev...
[١:١٥:٠٠ م] [FlutterDaemon] [Error] /usr/bin/env: 'bash': No such file or directory
[١:١٥:٠١ م] [General] [Info] !! PLEASE REVIEW THIS LOG FOR SENSITIVE INFORMATION BEFORE SHARING !!

Dart Code extension: 3.46.1
Flutter extension: 3.46.0 (activated)

App: Visual Studio Code
Version: 1.70.1
Platform: linux

Workspace type: Flutter
Analyzer type: LSP
Multi-root?: false

Dart SDK:
    Loc: /home/jus/development/flutter/bin/cache/dart-sdk
    Ver: 2.17.6
Flutter SDK:
    Loc: /home/jus/development/flutter
    Ver: 3.0.5

HTTP_PROXY: undefined
NO_PROXY: undefined
[١:١٥:٠٥ م] [General] [Info] Returning cached results for project search
[١:١٥:٠٨ م] [Analyzer] [Error] Could not find a command named "/home/jus/development/flutter/bin/cache/dart-sdk/bin/".

Usage: dart <command|dart-file> [arguments]

Global options:
-h, --help                 Print this usage information.
-v, --verbose              Show additional command output.
    --version              Print the Dart SDK version.
    --enable-analytics     Enable analytics.
    --disable-analytics    Disable analytics.

Available commands:
  analyze    Analyze Dart code in a directory.
  compile    Compile Dart to various formats.
  create     Create a new Dart project.
  devtools   Open DevTools (optionally connecting to an existing application).
  doc        Generate API documentation for Dart projects.
  fix        Apply automated fixes to Dart source code.
  format     Idiomatically format Dart source code.
  migrate    Perform null safety migration on a project.
  pub        Work with packages.
  run        Run a Dart program.
  test       Run tests for a project.

Run "dart help <command>" for more information about a command.
See https://dart.dev/tools/dart-tool for detailed documentation.
[١:١٥:١١ م] [Analyzer] [Error] Could not find a command named "/home/jus/development/flutter/bin/cache/dart-sdk/bin/".

Usage: dart <command|dart-file> [arguments]

Global options:
-h, --help                 Print this usage information.
-v, --verbose              Show additional command output.
    --version              Print the Dart SDK version.
    --enable-analytics     Enable analytics.
    --disable-analytics    Disable analytics.

Available commands:
  analyze    Analyze Dart code in a directory.
  compile    Compile Dart to various formats.
  create     Create a new Dart project.
  devtools   Open DevTools (optionally connecting to an existing application).
  doc        Generate API documentation for Dart projects.
  fix        Apply automated fixes to Dart source code.
  format     Idiomatically format Dart source code.
  migrate    Perform null safety migration on a project.
  pub        Work with packages.
  run        Run a Dart program.
  test       Run tests for a project.

Run "dart help <command>" for more information about a command.
See https://dart.dev/tools/dart-tool for detailed documentation.
[١:١٥:١١ م] [Analyzer] [Error] 
[١:١٥:١١ م] [Analyzer] [Error] Could not find a command named "/home/jus/development/flutter/bin/cache/dart-sdk/bin/".

Usage: dart <command|dart-file> [arguments]

Global options:
-h, --help                 Print this usage information.
-v, --verbose              Show additional command output.
    --version              Print the Dart SDK version.
    --enable-analytics     Enable analytics.
    --disable-analytics    Disable analytics.

Available commands:
  analyze    Analyze Dart code in a directory.
  compile    Compile Dart to various formats.
  create     Create a new Dart project.
  devtools   Open DevTools (optionally connecting to an existing application).
  doc        Generate API documentation for Dart projects.
  fix        Apply automated fixes to Dart source code.
  format     Idiomatically format Dart source code.
  migrate    Perform null safety migration on a project.
  pub        Work with packages.
  run        Run a Dart program.
  test       Run tests for a project.

Run "dart help <command>" for more information about a command.
See https://dart.dev/tools/dart-tool for detailed documentation.
[١:١٥:١١ م] [Analyzer] [Error] 
[١:١٥:١٥ م] [Analyzer] [Error] Could not find a command named "/home/jus/development/flutter/bin/cache/dart-sdk/bin/".

Usage: dart <command|dart-file> [arguments]

Global options:
-h, --help                 Print this usage information.
-v, --verbose              Show additional command output.
    --version              Print the Dart SDK version.
    --enable-analytics     Enable analytics.
    --disable-analytics    Disable analytics.

Available commands:
  analyze    Analyze Dart code in a directory.
  compile    Compile Dart to various formats.
  create     Create a new Dart project.
  devtools   Open DevTools (optionally connecting to an existing application).
  doc        Generate API documentation for Dart projects.
  fix        Apply automated fixes to Dart source code.
  format     Idiomatically format Dart source code.
  migrate    Perform null safety migration on a project.
  pub        Work with packages.
  run        Run a Dart program.
  test       Run tests for a project.

Run "dart help <command>" for more information about a command.
See https://dart.dev/tools/dart-tool for detailed documentation.
[١:١٥:١٥ م] [Analyzer] [Error] 
[١:١٥:١٨ م] [Analyzer] [Error] Could not find a command named "/home/jus/development/flutter/bin/cache/dart-sdk/bin/".

Usage: dart <command|dart-file> [arguments]

Global options:
-h, --help                 Print this usage information.
-v, --verbose              Show additional command output.
    --version              Print the Dart SDK version.
    --enable-analytics     Enable analytics.
    --disable-analytics    Disable analytics.

Available commands:
  analyze    Analyze Dart code in a directory.
  compile    Compile Dart to various formats.
  create     Create a new Dart project.
  devtools   Open DevTools (optionally connecting to an existing application).
  doc        Generate API documentation for Dart projects.
  fix        Apply automated fixes to Dart source code.
  format     Idiomatically format Dart source code.
  migrate    Perform null safety migration on a project.
  pub        Work with packages.
  run        Run a Dart program.
  test       Run tests for a project.

Run "dart help <command>" for more information about a command.
See https://dart.dev/tools/dart-tool for detailed documentation.
[١:١٥:١٨ م] [Analyzer] [Error]

**Comment by DanTup** [comment] 2022-08-31 12:45
@Iamjustin25 how are you launching VS Code? If you're not doing it from a terminal, can you try closing all instances of VS Code, then lauching it _from the terminal_ (running `code`) and see if that makes any difference?

It seems like there may be a difference in the `PATH` variable in your terminal (which includes `/bin`) versus what VS Code is inheriting (which does not include `/bin`).

**Comment by Iamjustin25** [comment] 2022-09-01 07:16
@DanTup  its work thank you

**Comment by DanTup** [comment] 2022-09-01 09:13
@Iamjustin25 do you mean it works if VS Code is launched from the terminal?

If that's the case, it sounds likely to be a `PATH` issue, where your `PATH` environment variable is being set in scripts that run for terminal startup, but not for apps launched outside of the terminal. I'm not very familiar with Linux (and this likely varies by distro), but if you can find a way to ensure your `PATH` includes everything it should even for apps outside of the terminal, that would likely fix the issue when launching VS Code outside of the terminal.

**Comment by Iamjustin25** [comment] 2022-09-01 14:54
@DanTup  yes i mean that
i will look for that thank you

**Comment by DanTup** [comment] 2022-09-01 15:13
Great - will close this as I don't think there's anything to do here as this is just a setup/config issue.

**Closed by DanTup** 2022-09-01 15:13 UTC
Labels: awaiting info
