### ISSUE TITLE
sending data from mobile to dart code is lagging compare to flutter run command

### ISSUE THREAD

**Issue by jagdishjadeja** [Dart-Code/Dart-Code#993] opened 2018-06-08 04:14 UTC
for example, when I use print() to print something it seems a bit of lagging 
but when the app is running with flutter run command in normal cmd it seems faster to communicate between app and computer
I have tried running app via mobile device and emulator both and emulator was faster than the mobile device to communicate between app and computer 

my vs code version: 
Version 1.23.1
Commit d0182c3417d225529c6d5ad24b7572815d0de9ac
Date 2018-05-10T17:11:17.614Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

Dart code version: 2.13.2

Flutter details:
Flutter 0.4.4 • channel beta • https://github.com/flutter/flutter.git
Framework • revision f9bb4289e9 (4 weeks ago) • 2018-05-11 21:44:54 -0700
Engine • revision 06afdfe54e
Tools • Dart 2.0.0-dev.54.0.flutter-46ab040e58

**Comment by DanTup** [comment] 2018-06-11 11:59
How much data are you printing, and what's the delay like?

I just tested and the delay was ver short (only a few ms) for me. However if I spew tons of output, then it does seem to be buffered and only appear periodically. It's possible it's being buffered somewhere; but before I dig in, can you confirm if that sounds like the issue you're having?

**Comment by jagdishjadeja** [comment] 2018-06-11 13:47
it is slow by some milliseconds not sure how much but when I compare it with flutter run it literally feels that it is slow

**Comment by DanTup** [comment] 2018-06-11 14:35
Ok I'll see if I can measure it better, and find out where the delay is. I think VS Code might buffer output events for efficiency, but that could be adding an extra delay.

**Comment by DanTup** [comment] 2018-06-13 11:48
Ok, I've done some testing and can indeed see a delay. If I run from the terminal it's fine. I dumped the raw data as soon as the messages comes in like this:

```ts
this.process.stdout.on("data", (data: Buffer) => {
	const message = data.toString();
	if (message.indexOf("opening") !== -1) {
		console.log(`RAW: ${message}`);
	}
```

Aaaaaand.... it's still delayed. So whatever is going on seems to be somewhere between the `flutter run --machine` process and our `child_process` handle. I've confirmed that it's not the `--machine` variant as that's also fast when run from the console. We are executing via the shell which might not help. I'll do more testing...

**Comment by DanTup** [comment] 2018-06-13 11:50
Actually, it occurs to me that the way I'm seeing the raw output is also via the debug console (just in another Code process), so if the delay is coming from VS Code I'd also see it there! Back to the drawing board...

**Comment by DanTup** [comment] 2018-06-13 12:04
Ok, adding timestamps shows that there's only 0.03ms between us tapping on the screen and getting a print in the debug adapter. From there it's VS Code's job to get back to the editor and render. As such I've opened an issue with VS Code: https://github.com/Microsoft/vscode/issues/51759

I suspect they might WontFix it because it's fairly minor, but we'll see. Thanks for the report!

**Closed** 2018-06-13 12:04 UTC
Labels: upstream in vs code

**Comment by DanTup** [comment] 2018-06-13 15:03
Response on the above case is that this is buffered because the performance of refreshing the tree is bad. Ultimately it'll be addressed by https://github.com/Microsoft/vscode/issues/11462.
