### ISSUE TITLE
"The casing of the open workspace folder does not match the casing on disk; please re-open the folder using the File Open dialog." message on all projects

### ISSUE THREAD

**Issue by ndarilek** [Dart-Code/Dart-Code#2863] opened 2020-10-09 12:57 UTC
My Dart extension recently updated, and I now get this message even on non-Dart projects. I don't develop many Dart/Flutter projects, so it's a bit annoying when it appears for a Rust or Python directory.

How do I fix this? I mean, other than having to re-open my project that doesn't need this extension, to fix something that seems like a non-issue for the extensions I do use? :)

Thanks.

**Comment by DanTup** [comment] 2020-10-09 13:22
@ndarilek it's not intended that this message is shown for non-Dart projects, but mostly not because we scan your workspace, but because the extension itself should not be activated at all for a non-Dart project.

It would be useful to know why the extension is being activated for your Python/Rust projects (it would be better for the extension not to activate at all, than just silence this warning, since it will be spawning a Dart analysis server that is not required).

Could you try:

- Click the **Output** pane and select **Log (Extension Host)** in the dropdown on the right
- Put focus in the Output pane and press Ctrl+F and search for "_doActivateExtension Dart-Code.dart-code"

You should find something like this:

<img width="1361" alt="Screenshot 2020-10-09 at 14 14 53" src="https://user-images.githubusercontent.com/1078012/95587320-d2253700-0a39-11eb-93d0-4f7afb0ff230.png">

This shows the reason the extension was activated. In my case it's:

```js
{
	"startup": true,
	"extensionId": {
		"value": "Dart-Code.dart-code",
		"_lower": "dart-code.dart-code"
	},
	"activationEvent": "workspaceContains:**/pubspec.yaml,**/*.dart"
}
```

This shows that the `workspaceContains` rule fired (meaning there's a `pubspec.yaml` or a `.dart` file in the workspace). I'd be curious to know what shows up for you. Something that's come up in the past is that it took VS Code more than 7 seconds to scan the folder, so aggressively activates all extensions (see https://github.com/microsoft/vscode/issues/73656), which might be a little tricky to work around.

**Comment by ndarilek** [comment] 2020-10-09 13:32
Hmm, what I get is:


```

[2020-10-0908:28:50.796] [exthost] 
[info] ExtensionService#_doActivateExtension 
Dart-Code.dart-code {"startup":false,"extensionId":{"value":"Dart-Code.dart-code","_lower":"dart-code.dart-code"},"activationEvent":"onDebugDynamicConfigurations"}
```
So it isn't activating?

**Comment by DanTup** [comment] 2020-10-12 10:43
That looks like it's being activated because VS Code wants a list of the dynamic debug configurations (which we support). Do you know what actions you're performing that triggers this? Is it only when you try to run your Rust/Python projects, or immediately upon open? I'd like to try to reproduce it here.

**Comment by ndarilek** [comment] 2020-10-12 13:12
When I cd into a Rust project directory and run "code ." this happens.


Not sure how the casing issue is triggered, since at no point do I 
actually type the folder name in outside of the "cd". Using PowerShell 
under Windows.


Thanks.

**Comment by ndarilek** [comment] 2020-10-12 13:17
Sorry, should also mention that I'm running Rust Analyzer and the 
code-lldb extensions for Rust. Not sure if either or both are 
contributing this change.

**Comment by DanTup** [comment] 2020-10-13 09:59
This seems to be a VS Code regression - when opening any project, it eagerly activates all extensions that contribute dynamic debug configurations. I suspect this is a bug and have filed https://github.com/microsoft/vscode/issues/108578.

**Comment by ndarilek** [comment] 2020-10-13 13:31
Thanks! I'll follow that issue for updates.

**Comment by DanTup** [comment] 2020-10-26 18:59
This has been fixed by VS Code and will be in the Insiders release tomorrow, and presumably the next stable release (in a week or two?). I'll do some testing tomorrow to confirm it's definitely fixed, and if not follow up with them on the issue linked above.

**Closed by DanTup** 2020-10-26 18:59 UTC
Labels: blocked on vs code / lsp / dap
