### ISSUE TITLE
VSCode  unable to locate source files in Flutter web project

### ISSUE THREAD

**Issue by RelicOfTesla** [Dart-Code/Dart-Code#5331] opened 2024-11-02 18:06 UTC
**Describe the bug**
Unable to locate source files in Chrome debugger console for Flutter web project.
﻿
I created a basic Flutter project using the command `flutter create --platforms=web demo1` and added `debugPrintStack()` to a click event in the code.
﻿
When debugging in Chrome and clicking on the file location printed in the VSCode Debug Console window (e.g., packages/demo1/main.dart 61:5     main.dart:61), I get the error "The editor could not be opened because the file was not found".
﻿
Additional details:
1. The file actually exists at lib/main.dart.
2. This issue affects both the project source files and Flutter SDK files when trying to locate them through the console window.
3. VSCode is set to "Debug my code + packages + SDK".
4. Using F12 on the import statement `import 'package:flutter/material.dart'` at the top of main.dart correctly jumps to the Flutter SDK source code.
5. The project name in pubspec.yaml is correct. I've tried `flutter clean + flutter pub get + restarting VSCode`, but the issue persists. Note that this is a basic newly created project.
6. The .dart_tool/package_config.json file exists and has the correct path configuration for the demo1 project.
7. I've attempted to add "sourceMaps" and "sourceMapPathOverrides" to launch.json, but they seem to have no effect for Flutter. These configurations appear to be for other languages.
8. VSCode settings.json has "dart.debugSdkLibraries": true and "dart.debugExternalPackageLibraries": true.
﻿
It seems the issue might be related to the inability to recognize the "packages/xxxx" prefix.
﻿

**To Reproduce**
1. Create a new Flutter web project using `flutter create --platforms=web demo1`
2. Add `debugPrintStack();` to a click event in the main.dart file
3. Run the project in debug mode using Chrome
4. Click the event to trigger the stack trace
5. Try to open the source file by clicking on the file location in the console
﻿

**Expected behavior**
The source file should open in the editor when clicked in the console.

﻿
**Actual behavior**
The editor fails to open the file with the error "The editor could not be opened because the file was not found".

﻿
**Screenshots**
![11](https://github.com/user-attachments/assets/cbf3e3cb-eab2-40e7-b858-43b5eab49edd)

﻿
**Please complete the following information:**
﻿
- Operating System and version: win10
- VS Code version: 1.95
- Dart extension version: 3.5.3
- Dart/Flutter SDK version: 3.24.3
﻿

**Comment by DanTup** [comment] 2024-11-04 14:57
I can repro this. The response from `lookupResolvedPackageUris` looks correct, but the output event is broken:

```
==> [VM] {"jsonrpc":"2.0","id":"714","method":"lookupResolvedPackageUris","params":{"isolateId":"739","uris":["package:dartcode_5331/main.dart"],"local":true}}
<== [VM] {"jsonrpc":"2.0","result":{"type":"UriList","uris":["file:///D:/Dev/Test%20Projects/dartcode_5331/lib/main.dart"]},"id":"714"}
<== {
	"seq": 1593,
	"type": "event",
	"body": {
		"category": "stdout",
		"column": 5,
		"line": 12,
		"output": "packages/dartcode_5331/main.dart 12:5                                    build\n",
		"source": {
			"name": "packages\\dartcode_5331\\main.dart",
			"path": "file:///D:/Dev/Test%20Projects/dartcode_5331/packages/dartcode_5331/main.dart"
		}
	},
	"event": "output"
}
```

![image](https://github.com/user-attachments/assets/2ef8f4e9-b83b-482e-8f8e-00e24c238e7b)

**Comment by DanTup** [comment] 2024-11-04 15:01
Oh, the `lookupResolvedPackageUris` call is actually unrelated - we're just parsing this as a relative path and it's wrong.

This is actually a dupe of https://github.com/Dart-Code/Dart-Code/issues/4418 and https://github.com/dart-lang/webdev/issues/949.

I'll close this as a dupe and I've pinged on that issue to try to make sure it's in the right place.

**Closed** 2024-11-04 15:01 UTC
Labels: duplicate
