### ISSUE TITLE
Code completion inserts unnecessary tabstops in LSP

### ISSUE THREAD

**Issue by sooxt98** [Dart-Code/Dart-Code#2975] opened 2020-12-02 18:56 UTC
Is there a way to disable auto comma before this this get fix?

![vscode-flutter-suggesion](https://user-images.githubusercontent.com/13378059/100918008-e570f200-3512-11eb-8de4-00d4c77a4b89.gif)

**Comment by DanTup** [comment] 2020-12-02 19:05
Can you try adding `"editor.suggest.snippetsPreventQuickSuggestions": false,` to your VS Code settings, and see if that stops this from happening?

I think it might be being caused by the extra tab-stop.

**Comment by sooxt98** [comment] 2020-12-02 19:28
@DanTup that's quick reply, ya that magic it fixed

**Comment by sooxt98** [comment] 2020-12-02 19:32
https://github.com/microsoft/vscode/issues/102580

**Comment by DanTup** [comment] 2020-12-02 19:45
Yeah, this is a common complaint. It is on the Dart-Code Recommended Settings page (https://dartcode.org/docs/recommended-settings/).

That said - I want to check whether we can do away with the final tabstop here, as that might prevent it from occurring. In any case, I'd recommend leaving that setting off :-)

**Comment by DanTup** [comment] 2020-12-03 12:03
After some testing, I've decided to leave this as-is. Pre-LSP we would not include the additional tabstop, which meant this would not occur. However, you'd need to use the cursor key to move to after the comma.

In LSP, we have an additional tabstop which allows you to press `<tab>` after typing the argument value to jump after the tab. It feels slightly easier to hit `<tab>` than the cursor key to move after this, so I think it's worth keeping, given that we recommend `snippetsPreventQuickSuggestions: false` anyway.

**Comment by DanTup** [comment] 2020-12-03 12:05
I've changed my mind. This could affect a lot of people when moving to LSP as it never used to happen. The benefit of using tab is minor, but the annoyance for all users that haven't applied the recommended settings (likely most) is likely greater.

**Comment by DanTup** [comment] 2020-12-07 16:28
Fixed by https://github.com/dart-lang/sdk/commit/9a82c5447bf50f3d95c09f663ab168fb87e7742d, thought won't show up until you're using a new SDK that includes this fix.

**Closed by DanTup** 2020-12-07 16:28 UTC
Labels: in editor, is bug
