### ISSUE TITLE
[3.24.0 ver]  is messing up Monokai/Abyss  Theme

### ISSUE THREAD

**Issue by Shiba-Kar** [Dart-Code/Dart-Code#3458] opened 2021-07-04 07:36 UTC
**Describe the bug**
When on Monokai/Abyss  Theme proper color coding is messed up. 
Observed this when the Analyzer finishes analyzing the Flutter code. During the analyzing process the theme is proper.

**To Reproduce**
1.  Install Flutter extension
2. Change Theme to Simple Monokai  or Abyss . 

**Screenshots**
![Screenshot (11)](https://user-images.githubusercontent.com/24454722/124377124-03305080-dcc8-11eb-9b1e-afa2f89757fc.png)

**Versions **
 - VS Code version: 1.57.1
 - Dart extension version: 3.24.0
 - Dart/Flutter SDK version: 3.24.0

**Comment by DanTup** [comment] 2021-07-04 10:20
> When on Monokai/Abyss Theme proper color coding is messed up.

Can you be more specific about which part you think is incorrect? Syntax highlighting now uses LSP's semantic tokens and should be more accurate. Previously, the syntax highlighting was regex based and not quite as accurate, so the new behaviour should better match the theme.

If you can give some specific examples of things that you think are now coloured incorrectly, I'll take a look. Thanks!

**Comment by Shiba-Kar** [comment] 2021-07-04 14:32
When ever I switch to Monokai/Abyss Theme there is underlines in classes and methods which is not normal in these themes.
One more observation this issue is present in my resent projects the older ones works perfectly.

**Comment by weakvar** [comment] 2021-07-05 08:32
Hey there! I'm using a [light theme](https://marketplace.visualstudio.com/items?itemName=GitHub.github-vscode-theme) from GitHub. After updating, function parameters are now yellow. Also noticed that the `@override` annotation is not correctly highlighted (`@` is red, `override` is black). 

Should we now look for another appropriate theme for code highlighting, or is this a bug in the extension and it will be fixed in the near future?

### Before
<img width="1552" alt="before" src="https://user-images.githubusercontent.com/35395520/124441359-45b76300-dd84-11eb-8aa5-a23d7167d5c1.png">

### After
<img width="1552" alt="after" src="https://user-images.githubusercontent.com/35395520/124441342-418b4580-dd84-11eb-82a9-166abda6900f.png">

**Comment by DanTup** [comment] 2021-07-05 09:41
@Shiba-Kar 

> When ever I switch to Monokai/Abyss Theme there is underlines in classes and methods which is not normal in these themes.
> One more observation this issue is present in my resent projects the older ones works perfectly.

As far as I can tell, this is coming from the theme. Class names are defined as being underlined:

https://github.com/microsoft/vscode/blob/main/extensions/theme-monokai/themes/monokai-color-theme.json#L204-L211

![Screenshot 2021-07-05 at 10 40 00](https://user-images.githubusercontent.com/1078012/124451530-6334fe80-dd7d-11eb-8d82-786688b6efa4.png)

These may have not shown up previously because the syntax highlighting was not using semantic tokens until recently. If you're seeing different highlighting in some of your projects, it's possible you have either LSP or semantic tokens disabled for those projects.

**Comment by DanTup** [comment] 2021-07-05 09:51
@weakvar the orange parameters seem to come from VS Code mapping the `parameter` token onto the `variable.parameter` textmate scope and the theme seems to define variables as orange:

<img width="627" alt="Screenshot 2021-07-05 at 10 46 47" src="https://user-images.githubusercontent.com/1078012/124452522-5e247f00-dd7e-11eb-8f26-0038c4ddf877.png">

![Screenshot 2021-07-05 at 10 47 05](https://user-images.githubusercontent.com/1078012/124452533-5f55ac00-dd7e-11eb-925d-b414221a6e5b.png)

This seems to match the colouring in TypeScript too, so I believe it's also correct and as the theme defines it.

<img width="937" alt="Screenshot 2021-07-05 at 10 47 41" src="https://user-images.githubusercontent.com/1078012/124452697-8613e280-dd7e-11eb-891b-8dc2696401a4.png">


> Also noticed that the `@override` annotation is not correctly highlighted (`@` is red, `override` is black).

This one is definitely a little more controversial. The `@` is coloured as an "annotation", but the rest of the annotation is coloured semantically (it should therefore match the colour of whatever that part is, whether it's a getter, a constructor, etc):

<img width="234" alt="Screenshot 2021-07-05 at 10 50 39" src="https://user-images.githubusercontent.com/1078012/124453039-de4ae480-dd7e-11eb-8c41-80ebdfbbdd02.png">


You can disable semantic tokens if you prefer the old textmate grammar colouring, or you could customise these token colours in your settings to change them as you'd like.

Hope this makes sense!

**Comment by weakvar** [comment] 2021-07-25 18:10
Hey everyone who faced the same problem. To fix this issue, you have to turn off `semanticHighlighting` in the Visual Studio Code settings.

**Comment by DanTup** [comment] 2021-07-26 10:56
Turning off semantic highlighting is an option, but you'll miss out on getting proper semantic tokens (for example if you name a method `get` or `set` it will be coloured incorrectly, and you may also get less accurate colourings in things like string interpolation).

A better option may be better to pick a theme (or customise your theme) to look how you'd like _with_ semantic tokens.

I don't think there's anything to do here so I'll close this. I believe things are working as intended, even if they seem different/unexpected. If you find things that don't seem to be coloured as the theme source suggests though, please do file issues. Thanks!

**Closed by DanTup** 2021-07-26 10:56 UTC
Labels: awaiting info, is bug
