### ISSUE TITLE
Dart-code (v3.41.20220516) Not working with flutter 3.0.0 on windows

### ISSUE THREAD

**Issue by nerdraven** [Dart-Code/Dart-Code#3972] opened 2022-05-19 10:06 UTC
I just updated my sdk to flutter 3.0.0 but doesn't work the installed packages
![image](https://user-images.githubusercontent.com/42095620/169268742-d2baac77-a014-472f-9dcb-7e08a6ca56ec.png)

**Comment by DanTup** [comment] 2022-05-19 10:23
Can you try running the **Flutter: Get Packages** command from the command palette (`F1`) and see if that solves this? If it shows any errors while trying to run, please post them here.

**Comment by staxgr** [comment] 2022-05-19 18:53
I'm having the same problem but on Mac with version 3.40. As soon as I upgrade to flutter 3.0.0 all flutter imports stops working. The app still builds and run if I hit F5 or run flutter run from the terminal.

Running **Flutter: Get Packages** renders the following problems:
<img width="1401" alt="Screenshot 2022-05-19 at 20 53 03" src="https://user-images.githubusercontent.com/396310/169378785-403db4da-9af3-4828-8b55-5cd880a35f68.png">

**Comment by DanTup** [comment] 2022-05-19 19:05
Is there any error output when you run **Flutter: Get Packages**? Does it happen on a new project created with **Flutter: New Project**, or only existing projects?

(@bwilkerson FYI in case you've had any other reports of this.. I can't repro on macOS, but will try Windows shortly)

**Comment by staxgr** [comment] 2022-05-19 19:26
No particular error output when I run **Flutter: Get Packages** . 
It happens both with newly created and old projects.

**Comment by bwilkerson** [comment] 2022-05-19 20:12
No, I haven't seen any other reports than these.

**Comment by DanTup** [comment] 2022-05-19 20:17
I don't seem to be able to reproduce this myself either. Here's a newly-created project with **Flutter: New Project**:

![image](https://user-images.githubusercontent.com/1078012/169397044-ae20a6a7-01cc-4777-a64a-7e5353b84d0c.png)

@staxgr @nerdraven are you able to create a new project with **Flutter: New Project** and once it's finished, zip up the entire folder (including it's `.dart_tool`, etc.) and share it? (either here, or email it to me at logs@dartcode.org). Thanks!

**Comment by DanTup** [comment] 2022-05-19 20:44
I think the report at https://github.com/flutter/flutter/issues/103895 is the same issue as this, although on macOS.

There's also a similar looking issue at https://github.com/flutter/flutter/issues/104038 which may have been related to nested projects. @staxgr @nerdraven could you confirm whether you have any `pubspec.yaml`, `analysis_options.yaml`, `.dart_tool` files/folders in any ancestor folders of the project(s) where you see this?

**Comment by staxgr** [comment] 2022-05-19 20:51
Here's a project created with **Flutter: New Project** zipped up
[flutter_application_1.zip](https://github.com/Dart-Code/Dart-Code/files/8734143/flutter_application_1.zip)

**Comment by staxgr** [comment] 2022-05-19 20:55
> I think the report at [flutter/flutter#103895](https://github.com/flutter/flutter/issues/103895) is the same issue as this, although on macOS.
> 
> There's also a similar looking issue at [flutter/flutter#104038](https://github.com/flutter/flutter/issues/104038) which may have been related to nested projects. @staxgr @nerdraven could you confirm whether you have any `pubspec.yaml`, `analysis_options.yaml`, `.dart_tool` files/folders in any ancestor folders of the project(s) where you see this?

Nope, no such files or folders in any ancestor folders

**Comment by DanTup** [comment] 2022-05-19 20:58
@staxgr there doesn't appear to be a `.dart_tool` folder in that project. Was one not created when you run `flutter pub get` / **Flutter: get Packages**?

And out of interest, your project isn't inside a Bazel workspace (with a `WORKSPACE` folder somewhere up the tree)?

**Comment by staxgr** [comment] 2022-05-19 21:06
> @staxgr there doesn't appear to be a `.dart_tool` folder in that project. Was one not created when you run `flutter pub get` / **Flutter: get Packages**?
> 
> And out of interest, your project isn't inside a Bazel workspace (with a `WORKSPACE` folder somewhere up the tree)?

Ha! I actually had a WORKSPACE folder in my home directory (like four levels up in my folders) for some reason! Removing that and restarting VS code solved all problems :). Thanks a lot, hope this helps others as well!

**Comment by staxgr** [comment] 2022-05-19 21:09
Maybe not important anymore but here is a zipped project with the .dart_tool (previously I cleaned the project before zipping it which removed the .dart_tool)
[flutter_application_1.zip](https://github.com/Dart-Code/Dart-Code/files/8734237/flutter_application_1.zip)

**Comment by DanTup** [comment] 2022-05-19 21:35
@staxgr aha! Glad it was an easy fix. Do you know why you might have had that file?

I'll keep this open for now as it's not clear if @nerdraven's issue is similar.

**Comment by staxgr** [comment] 2022-05-19 21:52
Probably tested bazel for some Android project and it created that folder I guess… but honestly not sure how it ended up in my home folder

**Comment by nerdraven** [comment] 2022-05-20 17:29
The project is actually in a Bazel workspace. I tried it outside the tree and it worked

**Comment by DanTup** [comment] 2022-05-23 11:52
@nerdraven ah, thanks for confirming. In that case the issue is https://github.com/flutter/flutter/issues/103706. There were some changes to package resolution in Bazel workspaces that I think assume a project inside a Bazel workspace is using Bazel for its packages, but that might not always be the case.

I'll close this since the fix needs to come from the SDK and there's https://github.com/flutter/flutter/issues/103706 open tracking this. Thanks!

**Closed by DanTup** 2022-05-23 11:52 UTC
Labels: awaiting info
