### ISSUE TITLE
Wrap with column missing in flutter IDEs

### ISSUE THREAD

**Issue by ryaninja** [Dart-Code/Dart-Code#2492] opened 2020-05-25 11:11 UTC
I've tried this in both Android Studio and VSCode, but the context menu to wrap in column simply doesn't appear for me.  I'm trying to follow a layout tutorial, but I get this error at pretty much the first hurdle.  Has this feature been removed/replaced?  Anyone got any ideas?

Here's what the guide looks like:
[https://i.stack.imgur.com/fpKV2.jpg](url)

And here's what I see:
https://i.stack.imgur.com/yZu5M.jpg

**Comment by ryaninja** [comment] 2020-05-25 11:34
Ok, so it turns out you need to right-click and not highlight the widget and then right click.  Wrap in column showed as soon as I did this.

**Comment by DanTup** [comment] 2020-05-25 14:45
@bwilkerson @scheglov does this seem like a bug? When invoking the assist menu one character from the end of a widget class, **Wrap in Row/Column** show up. However if the cursor is after the last character, they do not (however the others do). I can't think of a reason for this (nor can I see an obvious reason from the code why this happens):

<img width="460" alt="Screenshot 2020-05-25 at 15 40 43" src="https://user-images.githubusercontent.com/1078012/82822944-8b75dc80-9e9e-11ea-88a1-7a90ab8e2959.png">
<img width="462" alt="Screenshot 2020-05-25 at 15 40 51" src="https://user-images.githubusercontent.com/1078012/82822951-8e70cd00-9e9e-11ea-98d3-1cb492c8cdc6.png">

**Comment by bwilkerson** [comment] 2020-05-25 16:12
I can't think of any valid reason for the behavior being different between these two selection locations, so I'd consider this to be a bug.

Note that "Wrap with Row" is also missing. Both it and "Wrap with Column" are implemented in a single method. That method uses `SelectionAnalyzer` to convert a selection range to a set of AST nodes, and my guess (though I haven't dug into it enough to know for sure) is that that class selects an AST node that the method in question doesn't handle correctly, and that that's the source of the bug.

**Comment by DanTup** [comment] 2020-05-26 09:28
Ok, took a quick look at this. When the cursor is inside the name of the widget, `analyzer.coveringNode` from the `SelectionAnalzyer` correctly identifies the widget expression. However, when it's like this:

```
WidgetFoo^('test')
```

The selection analyzer picks up the argument list `('test')` as the innermost covering node (since it starts at that offset), and `flutter.identifyWidgetExpression` exits early (without walking up parents) when it finds argument lists:

https://github.com/dart-lang/sdk/blob/93313eb2449099e20ade80d4760f76a325a4e176/pkg/analysis_server/lib/src/utilities/flutter.dart#L325-L327

Removing `node is ArgumentList` from that condition causes this case to work, however it breaks some other tests (for example `test_identifyWidgetExpression_node_instanceCreation` which is explicitly checking for this behaviour).

I'm not sure what a good fix is. If feels like the cursor being to the left of a paren in an argument list maybe should not be treated as being in the argument list, but that also feels like a weird exception.

**Comment by bwilkerson** [comment] 2020-05-26 14:54
A possible short-term work around would be to check in the assists to see whether the covering node is an argument list whose parent is a widget expression. If we add a comment explaining why we're doing it, then we'd have some context in case we decide to change `SelectionAnalyzer` in the future.

@scheglov I'm interested in your thoughts on this.

**Comment by DanTup** [comment] 2020-06-11 11:48
@scheglov do you have any additional thoughts on this? If not, I might have a go at doing what @bwilkerson suggested above. Thanks!

**Comment by bwilkerson** [comment] 2020-06-11 15:06
A note on implementation.

In order to better support being able to apply multiple fixes simultaneously, we changed the way we're implementing both fixes and assists. They now use instances of a subclass of `CorrectionProducer` to build the actual edits. The fixes have all been converted at this point, but most of the assists have not been.

Prior to these changes, fixes and assists each had a slightly different way of computing the node used as the starting point for creating the edits. Usually they produced the same node, but in a few cases they differed. In the new architecture they are consistent. That has meant that sometimes when converting a fix or assist we've had to update the code slightly to adjust for the change in starting node.

So, if you're interested in looking into this, it would be good if you first converted the existing assist to use the `CorrectionProducer` pattern. It's possible that doing so would impact the way the bug needs to be fixed, and it would be nice not to have to do the conversion after the fix is applied. That said, I won't say to no to getting the bug fixed without the extra work!

**Comment by scheglov** [comment] 2020-06-11 17:28
It is mostly a matter of covering reasonable cases.
It is reasonable to propose `Wrap` in this case `Widget^(...)`.
But we might have to do differently for `Widget(..., child^)`.

**Comment by DanTup** [comment] 2020-06-25 16:17
> So, if you're interested in looking into this, it would be good if you first converted the existing assist to use the `CorrectionProducer` pattern.

Looks like you beat me to this :-)

> It is reasonable to propose Wrap in this case Widget^(...).
> But we might have to do differently for Widget(..., child^).

I think we could specifically handle the case where the caret is at exactly the offset of the argument list (eg. the caret is to the left of the open paren) - `coveringNode is ArgumentList && coveringNode.offset == selectionOffset`? I've opened a change that does that here:

https://dart-review.googlesource.com/c/sdk/+/152521/

**Comment by bwilkerson** [comment] 2020-06-25 16:21
lgtm

**Comment by mich040m** [comment] 2022-02-23 12:43
Still happening as described here

> @bwilkerson @scheglov does this seem like a bug? When invoking the assist menu one character from the end of a widget class, **Wrap in Row/Column** show up. However if the cursor is after the last character, they do not (however the others do). I can't think of a reason for this (nor can I see an obvious reason from the code why this happens):
> 
> <img alt="Screenshot 2020-05-25 at 15 40 43" width="460" src="https://user-images.githubusercontent.com/1078012/82822944-8b75dc80-9e9e-11ea-88a1-7a90ab8e2959.png">
> 
> <img alt="Screenshot 2020-05-25 at 15 40 51" width="462" src="https://user-images.githubusercontent.com/1078012/82822951-8e70cd00-9e9e-11ea-98d3-1cb492c8cdc6.png">

**Comment by DanTup** [comment] 2022-02-24 15:55
I can reproduce this, but it's slightly different to the original report/fix - in that case the cursor was at the end of `ModelBinding` (the highlight is just VS code highlighting the references) and that works. However if you _select_ the widget name, Wrap with Column is still missing.

**Comment by DanTup** [comment] 2022-02-24 20:25
With https://github.com/dart-lang/sdk/commit/84806572e0375195337141dd87dd10939f7bb29e, these actions will also work if the whole widget name is selected. The fix is in the SDK so will ship with a future Flutter SDK release (rather than the Dart extension for VS Code).

**Closed by DanTup** 2022-02-24 20:25 UTC
Labels: is bug, in editor, in lsp/analysis server
