### ISSUE TITLE
Exception thrown at runtime appear as print statements in VS code debug console

### ISSUE THREAD

**Issue by ibrahimmohamed2411** [Dart-Code/Dart-Code#4805] opened 2023-10-20 12:26 UTC
**Describe the bug**
where an exception happened it appears as a print statement in the debug console and the reference to the file where this exception happened doesn't appear.

**To Reproduce**

**Expected behavior**
when a runtime exception happens the reference of the file where the exception happened must appear in the debug console.

**Screenshots**
![Screenshot 2023-10-20 151656](https://github.com/Dart-Code/Dart-Code/assets/71408841/81365a1d-6743-4eae-81f8-dce4ac502e67)

**Please complete the following information:**

You can run the **Dart: Collect Diagnostic Information** command from the VS Code command palette (`F1`) to easily capture this information or provide it manually.

 - Operating System and version: Windows 11 Home Single Language - version 22H2
 - VS Code version:  1.83.1
 - Dart extension version: 3.74.0
 - Dart/Flutter SDK version: 3.13.7

**Comment by DanTup** [comment] 2023-10-23 09:19
Can you you share a code example that triggers this and clarify exactly what you mean by "reference to the file where this exception happened doesn't appear" (I can see "main.dart:12:3" in the output).

I think there are a few issues in this area you might be hitting, some of which are fixed in the next Flutter release:

- Throwing exceptions before `runApp()` behaves differently because the Flutter framework does not handle them
- `package:` URIs are only mapped to have clickable links on the right in Debug mode
- Structured errors aren't formatted well with the new debug adapters (https://github.com/Dart-Code/Dart-Code/issues/4571)

Is the exception where you saw this happening before `runApp` or was that just where you reproduced it when debugging? If you're able to test with the Flutter `beta` channel, there have been several improvements made that might address the issue you're seeing. If not, please let me know!

**Comment by ibrahimmohamed2411** [comment] 2023-10-23 20:34
Thank you for your response. I appreciate your attention to this matter. I'll provide more details and a code example to clarify the issue I'm facing.

The issue I encountered involves Flutter exceptions being printed as plain text statements in the debug console, and the reference to the file where the exception occurred doesn't appear as a clickable link. Let me clarify this with a code example:
![code](https://github.com/Dart-Code/Dart-Code/assets/71408841/1a6f8416-2118-474a-8118-76d44a791be7)
When running this code, the exception is thrown within the build method of the MyApp widget. Instead of seeing a structured error message with a clickable link to the file and line where the exception occurred, I see something like this in the debug console:
Exception: This is a test exception

However, it doesn't provide the file and line information (e.g., "main.dart:12:3") as a clickable link, which is the behavior I expected. This is what I meant by "the reference to the file where this exception happened doesn't appear."

I also want to clarify that this issue occurs during the application's runtime, not before runApp(). This behavior is problematic as it makes it difficult to quickly navigate to the source of exceptions during development and debugging.

**Comment by DanTup** [comment] 2023-10-26 14:32
Thanks for clarifying. I think you're seeing https://github.com/Dart-Code/Dart-Code/issues/4571 which was recently fixed. On the current Flutter master branch I see the following:

![image](https://github.com/Dart-Code/Dart-Code/assets/1078012/2b521238-3b09-4d6a-8856-49a905cda6a3)

If you're able to easily test on the master branch, let me know if this is not the behaviour you see. Otherwise, I think we can close this as a dupe of #4571.

Thanks!

**Comment by ibrahimmohamed2411** [comment] 2023-10-26 20:08
I switch to Flutter Master and it works.
Thank you

**Closed** 2023-10-27 11:57 UTC
Labels: is bug, awaiting info

**Comment by DanTup** [comment] 2023-10-27 12:05
Great, thanks for confirming!
