### ISSUE TITLE
Import start with '/' cause Dart Analysis Server crash

### ISSUE THREAD

**Issue by zhxst** [Dart-Code/Dart-Code#4815] opened 2023-10-27 06:42 UTC
**Describe the bug**
Type in VSCode editor with `import '/main.dart';` makes Dart Analysis Server crash, or makes Daemon terminated.
And the auto complete doesn't work with this type of import.
It works fine in Android Studio, but the auto complete suggest the long format.
Is this not the recommend way to import file? I feel it's more convenient than '../../some.dart'.

**To Reproduce**
1. Create or open any Flutter project.
2. Open or create a dart file.
3. Type `import '/main.dart' in the editor.
4. The Daemon Terminated info will appear.

**Expected behavior**
Daemon and Dart Analyzer not crash.
The auto complete works when type '/'.

**Screenshots**
<img width="466" alt="image" src="https://github.com/Dart-Code/Dart-Code/assets/11647836/0887ec57-93e9-4f88-8b18-754687f96f66">

<img width="464" alt="image" src="https://github.com/Dart-Code/Dart-Code/assets/11647836/811fc73e-f804-487e-ba96-1a4e4ea48e56">

**log**
```log
[09:17:41] [Analyzer] [Error] Unhandled exception:
Bad state: No library: file:///Users/[User name]/dev/Projects/[Project folder]/lib
#0      LinkedElementFactory.libraryOfUri2 (package:analyzer/src/summary2/linked_element_factory.dart:232:7)
#1      LibraryBuilder._buildImport (package:analyzer/src/summary2/library_builder.dart:670:48)
#2      LibraryBuilder._buildDirectives.<anonymous closure> (package:analyzer/src/summary2/library_builder.dart:559:14)
#3      MappedListIterable.elementAt (dart:_internal/iterable.dart:415:31)
#4     …
[09:17:41] [Analyzer] [Info] Spawning /Users/[User name]/fvm/versions/stable/bin/cache/dart-sdk/bin/dart with args ["language-server","--protocol=lsp","--client-id=VS-Code","--client-version=3.74.0"]
[09:17:41] [Analyzer] [Info]     PID: 4555
```

**Please complete the following information:**

 - Operating System and version: macOS 13.6 with M1
 - VS Code version: 1.83.1
 - Dart extension version: 3.74.0
 - Dart/Flutter SDK version: 3.1.4 / 3.13.8
 - Target device (if the issue relates to Flutter debugging):

**Comment by DanTup** [comment] 2023-10-30 10:39
I'm unable to reproduce this on Windows or macOS, I just get an error that the path isn't valid like this:

<img width="987" alt="Screenshot 2023-10-30 at 10 36 42" src="https://github.com/Dart-Code/Dart-Code/assets/1078012/ff8b1f20-8f0a-4166-8592-6a34567477d0">


Can you click the **Show Log** button shown in your first screenshot and provide the log here?


> Is this not the recommend way to import file? I feel it's more convenient than '../../some.dart'.

If you want to use a project-absolute path, you need to include the package name like:

```dart
import 'package:my_package/main.dart`
```

That will map to `lib/main.dart` in your project. Otherwise you can use relative paths, but you shouldn't use entire absolute file paths.

**Comment by zhxst** [comment] 2023-10-31 01:19
I have tested by your screen shot.

> I'm unable to reproduce this on Windows or macOS, I just get an error that the path isn't valid like this:
> 
> <img alt="Screenshot 2023-10-30 at 10 36 42" width="987" src="https://user-images.githubusercontent.com/1078012/279023722-ff8b1f20-8f0a-4166-8592-6a34567477d0.png">
> Can you click the **Show Log** button shown in your first screenshot and provide the log here?
> 
> > Is this not the recommend way to import file? I feel it's more convenient than '../../some.dart'.
> 
> If you want to use a project-absolute path, you need to include the package name like:
> 
> ```dart
> import 'package:my_package/main.dart`
> ```
> 
> That will map to `lib/main.dart` in your project. Otherwise you can use relative paths, but you shouldn't use entire absolute file paths.

It's not working in dart project. It only works in Flutter project.
So the behavior is different with dart and flutter, I guess.
The log has added.

**Comment by DanTup** [comment] 2023-10-31 11:09
Thanks for the log. I still haven't been able to reproduce this, however I see there's an existing open issue about this at https://github.com/dart-lang/sdk/issues/53858. I've added a comment about this issue and will close this one as a dupe.

You can subscribe to that issue for updates - although as noted above, you should use relative paths or `package:` imports which will hopefully avoid this issue.

**Closed** 2023-10-31 11:10 UTC
Labels: upstream in dart / flutter
