### ISSUE TITLE
Support running/debugging Flutter unit tests

### ISSUE THREAD

**Issue by kentcb** [Dart-Code/Dart-Code#649] opened 2018-03-05 23:37 UTC
Hi,

This extension says one can debug dart command-line programs, but I can't find any information on _how_ to do so. By piecing together various snippets of information, and by making educated guesses, I came up with this `launch.json`:
```JSON
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Unit Tests",
            "type": "dart",
            "request": "launch",
            "program": "${workspaceRoot}/lib/tests/unit_tests.dart",
        }
    ]
}
```
However, when I try to launch it I get this in the Debug Console:
```
No connected devices.
Exited (1)
```

I also tried `dart-cli` as the `type`, but that gave me a edit-time warning and the same output when launching.

**Comment by Skylled** [comment] 2018-03-05 23:53
Proper test running support is held up by VS Code, see #87. But there's a [workaround](https://github.com/Dart-Code/Dart-Code/issues/87#issuecomment-368845918) you can use for now.

**Comment by kentcb** [comment] 2018-03-05 23:55
@Skylled Thanks. Just tried the workaround, but it fails with the same message. Bummer, guess I'll stick with IntelliJ for now.

**Comment by Skylled** [comment] 2018-03-05 23:55
However, `No connected devices.` seems to imply Flutter is being run instead of dart. So I'm not quite sure why that would be.

**Comment by DanTup** [comment] 2018-03-06 07:32
@kentcb This feels like a bug. Even without proper test support, you can run Dart CLI tests with F5.

Just to clarify - is this a Flutter project but tests that should run without requiring a device?

**Comment by kentcb** [comment] 2018-03-06 09:44
@DanTup yes, it's a flutter app. On a hunch, I removed the flutter launch target, leaving only the unit test target. However, the result was the same.

**Comment by DanTup** [comment] 2018-03-06 09:59
How would you normally run tests tests from the command line? With `dart` or `flutter test`?

**Comment by DanTup** [comment] 2018-03-06 16:39
Ok, I know a little more about this now; will aim to address it for the version after v2.10.

With Dart CLI, running tests is just the same as running a script so there's no special handling, however for Flutter we need to use `flutter test` instead of `flutter run`. I'll need to think about how we'd best configure this.

**Comment by kentcb** [comment] 2018-03-07 01:22
> How would you normally run tests tests from the command line?

I don't tend to run tests via the command line, except as part of CI, in which case I do indeed use `flutter test`. In IntelliJ, I have a "Flutter Test" configuration, which I'm guessing amounts to the same thing.

I just tried running my tests directly via the dart-cli, and they fail with:
```
The built-in library 'dart:ui' is not available on the stand-alone VM.
'package:flutter/src/widgets/app.dart': error: line 6 pos 1: library handler failed
import 'dart:ui' as ui show window;
^
```
TBH, I don't entirely understand why this is, since none of my unit tests do anything flutter-specific, nor use any flutter libraries.

**Comment by DanTup** [comment] 2018-03-07 11:15
@kentcb If they were straight CLI tests then it should work. I suspect you have something referencing a Flutter package to get this error but it's hard to say without seeing code. For Dart CLI, tests are just normal scripts so they work exactly the same as running a any other script.

**Comment by DanTup** [comment] 2018-03-12 14:52
Closing this as a dupe of #636.

**Closed by DanTup** 2018-03-12 14:52 UTC
Labels: awaiting info, in debugger, in flutter, is enhancement
