### ISSUE TITLE
automatic add comma after close parenthesis

### ISSUE THREAD

**Issue by liudonghua123** [Dart-Code/Dart-Code#2410] opened 2020-04-30 03:11 UTC
I use vscode to develop flutter apps a lot. In order to make code format better and look nice, I always manually add comma after each close parenthesis. Could we add a options in flutter extension settings to support automatic add comma after close parenthesis. This would reduce the boring repetitive work.

**Comment by DanTup** [comment] 2020-05-04 12:02
I don't know if this could be done reliably in the editor. There are lots of closing parens that you wouldn't want commas after, for example in:

```
if (true) {
  print('test');
}
```

So it would have to be very context-specific and I think coming up with rules for this would be difficult (and they could be somewhat subjective).

However, there is a request for a fix in dart_style that would automatically insert them when formatting, which I think would be easier to make work well:

https://github.com/dart-lang/dart_style/issues/753

So, I'll close this as a dupe of that. If it gets implemented there, we should expose it as an option here.

**Closed** 2020-05-04 12:02 UTC
Labels: upstream in dart / flutter
