### ISSUE TITLE
Breakpoints are not hit when script path contains Chinese characters

### ISSUE THREAD

**Issue by meflyup** [Dart-Code/Dart-Code#459] opened 2017-11-30 13:17 UTC
Hi, when i use F5 to debug a dart command application,there debugger can't stop it at any of the breakpoint . my vscode version is 1.18.1  and the dart code version is v2.5.0.  
here is the picture:  
![debug1](https://user-images.githubusercontent.com/1710178/33432601-9ed2421a-d613-11e7-8c24-1199c2e81859.png)

and here is the launch.jsonfile:  
```
{
  
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Dart command line",
            "type": "dart-cli",
            "request": "launch",
            "program": "${workspaceRoot}/bin/main.1.dart"
        },
        {
            "name": "Dart command line",
            "type": "dart-cli",
            "request": "launch",
            "program": "${workspaceRoot}/bin/server.dart"
        }
    ]
}
```  

Does anyone experience of this? how to resolve it ?
Thanks!

**Comment by DanTup** [comment] 2017-11-30 20:07
Could you try [enabling some debug logging](https://github.com/Dart-Code/Dart-Code/blob/master/CONTRIBUTING.md#enable-logging) and reviewing the logs or attaching them (please ensure there's nothing sensitive in them first).

The `dart.observatoryLogFile` is the most relevant one here. Set that setting to a full file path and it will log communication with the debugger. Note: Code may tell you this setting is not valid - that's normal, just ignore it (this is currently a hidden setting).

**Comment by DanTup** [comment] 2017-11-30 20:18
Also, could you try running your application from the terminal like this:

```
dart  --enable-vm-service=0 bin/main.1.dart
```

And paste the output? We look for a string like `Observatory listening on http://...` to find the debugger - I don't know whether this text could be localised or something.

**Comment by meflyup** [comment] 2017-12-01 00:45
hi @DanTup ,thanks for your help. 
For the dart.observatoryLogFile i get the message in the file:
[log.txt](https://github.com/Dart-Code/Dart-Code/files/1520001/log.txt)

 and terminal run of the application, the output is :   
![image](https://user-images.githubusercontent.com/1710178/33462675-d47f2724-d673-11e7-87c8-df4903c87988.png)  
 but when I try to visit the localsite ,browser return "ERR_CONNECTION_REFUSED" .

Thansk！

**Comment by DanTup** [comment] 2017-12-01 07:13
I wonder if the problem is encoding. I see you're inside a folder named "web编程（web教育应用设计与开发）" so maybe the path for the breakpoint isn't being matched correctly. If you try in a folder with only English characters (for the whole path) does it still fail?

I'll try it on my machine with a folder named like that today and see if it gives me the same result. Thanks!

**Comment by DanTup** [comment] 2017-12-01 07:35
Btw, the reason you can't open that url is that the program finished running. If you also include `--pause_isolates_on_start=true` before the script name then it will leave the program paused, and then the url will probably load Observatory.

**Comment by DanTup** [comment] 2017-12-01 07:38
I can reproduce this when I name my folder with these characters. I'll do some digging and see where it's going wrong. Thanks for the report!

**Comment by DanTup** [comment] 2017-12-01 07:41
Ok, reviewing the log we're sending paths like `file:///e:/teaching/web编程（web教育应用设计与开发）/2017-2018-1/materials/eduapp/bin/main.dart` but Observatory is sending back a path like `file:\/\/\/e:\/teaching\/web%E7%BC%96%E7%A8%8B%EF%BC%88web%E6%95%99%E8%82%B2%E5%BA%94%E7%94%A8%E8%AE%BE%E8%AE%A1%E4%B8%8E%E5%BC%80%E5%8F%91%EF%BC%89\/2017-2018-1\/materials\/eduapp\/bin\/main.1.dart`. I guess we're missing some encoding of the paths!

**Comment by DanTup** [comment] 2017-12-01 08:07
@meflyup I have a fix for this, but it involves adding encode/decode to functions that are used in a lot of path mappings so it's going to need a good testing (Windows, Mac, local paths, Flutter device paths etc.). I hope to be able to do that later today and push out a fix for you.

In the meantime, you can workaround this by using only English characters in the path.

@devoncarew FYI, it's possible IntelliJ may have similar issues - it seems to have a similar method [here](https://github.com/JetBrains/intellij-plugins/blob/0e89c5dd443bc10c91a4c631feaea4635220f07c/Dart/src/com/jetbrains/lang/dart/ide/runner/server/vmService/DartVmServiceDebugProcess.java#L581).

**Closed** 2017-12-01 13:49 UTC
Labels: is bug

**Comment by DanTup** [comment] 2017-12-01 13:51
This issue is (hopefully) fixed in v2.5.1. Please update and let me know if you still have any issues.

**Comment by meflyup** [comment] 2017-12-04 07:18
It works! thanks a lot!

**Comment by DanTup** [comment] 2017-12-04 07:19
Excellent; thanks for confirming (and reporting it!) 🙂
