### ISSUE TITLE
debug toolbar disappear after debug crash

### ISSUE THREAD

**Issue by tjx666** [Dart-Code/Dart-Code#3432] opened 2021-06-26 09:45 UTC
**Describe the bug**

When I was debug my flutter app, sometime, for example phone screen off cause debug crash. When I try to debug again, the debug toolbar disappear.

**Expected behavior**

Show the toolbar as usual, so I can stop debug.

**Screenshots**

![image](https://user-images.githubusercontent.com/41773861/123509065-04e58d00-d6a6-11eb-8e69-05f6904083fd.png)

**Versions (please complete the following information):**
 
```
Version: 1.58.0-insider (Universal)
Commit: 49e1f9919880c1c96004f9b6ad91bcee7a94a1bd
Date: 2021-06-25T05:14:06.587Z
Electron: 12.0.12
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Darwin x64 20.5.0
Flutter 1.22.4 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 1aafb3a8b9 (8 months ago) • 2020-11-13 09:59:28 -0800
Engine • revision 2c956a31c0
Tools • Dart 2.10.4
```

**Comment by DanTup** [comment] 2021-06-28 14:29
It's expected that the debug toolbar will disappear if the debug session stops (which could happen if the Flutter tool quits). However it should be clear why this happens, it should not leave "Loading..." notifications visible and should print to the Debug Console.

Can you give instructions on how to reproduce what's shown in your screenshot? Thanks!

**Comment by tjx666** [comment] 2021-06-30 02:55
Reproduce:

1. open a flutter project
2. debug project using debug codeLens above main function
3. after application start ready, click stop debug button in debug toolbar
4. repeat step 2, the toolbar disappear

I think this issue may be only reproduce in latest insider version.

**Comment by DanTup** [comment] 2021-06-30 10:57
Looks this was indeed a VS Code bug. There's an issue about it here:

https://github.com/microsoft/vscode/issues/127418

It looks like it's been fixed this morning, so hopefully should be resolved in the next insiders build. If you still see it after then, please let me know!

**Closed** 2021-06-30 10:57 UTC
Labels: fixed in vs code
