### ISSUE TITLE
Segmentation fault when debugging tests with isolates

### ISSUE THREAD

**Issue by FaFre** [Dart-Code/Dart-Code#3725] opened 2021-12-11 17:51 UTC
The test adapter seems to have problems with isolates, when debugger attached.

Following working example:
```dart
import 'package:flutter/foundation.dart';
import 'package:flutter_test/flutter_test.dart';

Future<int> comp(int i) =>
    Future.delayed(const Duration(milliseconds: 500)).then((value) => i);

void main() {
  test('compute', () async {
    const numComputes = 50;

    final result = await Future.wait(
        List.generate(numComputes, (index) => compute(comp, index)));

    expect(result.length, numComputes);
  });
}
```

In 9 out of 10 runs, when clicking "Debug" above the "compute" test I get the following exception:
```
Connecting to VM Service at http://127.0.0.1:44817/MJdWRaXdnc8=/ws
✖ compute
unhandled error during finalization of test:
/home/fafre/Experiments/iso_test/test/widget_test.dart
TestDeviceException(Shell subprocess crashed with segmentation fault.)
#0      FlutterTesterTestDevice.finished (package:flutter_tools/src/test/flutter_tester_device.dart:239:5)
<asynchronous suspension>
#1      FlutterTesterTestDevice.kill (package:flutter_tools/src/test/flutter_tester_device.dart:221:5)
<asynchronous suspension>
#2      FlutterPlatform._startTest.<anonymous closure> (package:flutter_tools/src/test/flutter_platform.dart:486:9)
<asynchronous suspension>
#3      FlutterPlatform._startTest (package:flutter_tools/src/test/flutter_platform.dart:539:11)
<asynchronous suspension>

No tests match regular expression "^compute( \(variant: .*\))?$".
Exited (1)
```
In 1 out of 10 tries, the test is succeeding.

When clicking on 'Run' or with `flutter test` the test is always successful.

In my main project where I discovered this, I also have the side effect that some isolates are just hanging in running state forever:
![image](https://user-images.githubusercontent.com/59543085/145686440-43f5ce75-bd8c-4c8b-88a2-f5cf8498ac4c.png)
"Run" also always works here.

I use the current flutter release together with up-to-date Code (OSS) extension (v3.29.0).
[✓] Flutter (Channel stable, 2.8.0, on Manjaro Linux 5.15.2-2-MANJARO, locale en_US.UTF-8)

**Comment by DanTup** [comment] 2021-12-13 10:55
Do you know if this also happens from Android Studio, or on another machine? I can't reproduce here on my mac, but don't have easy access to a Linux machine (and VS Code's container support doesn't seem to be working for me right now).

Could you also capture a full debug log while reproducing this?

- Run the **Dart: Capture Debug Logs** command
- Click the **Debug** link to reproduce the issue
- Click **Cancel** on the logging notification to stop logging and open the log file
- Provide the log here

Thanks!

**Comment by FaFre** [comment] 2021-12-14 12:48
I uploaded the log here: https://gist.github.com/FaFre/071d32216f656b17cfd50cfcda7a4153

**Comment by DanTup** [comment] 2021-12-14 14:22
Unfortunately I can't see anything useful in the log. It looks like the test device Flutter uses for running tests inside `flutter test` is crashing (possibly during shutdown), as the error originates here:

https://github.com/flutter/flutter/blob/b279ff41786c7e61252f49da2afb0f99d11b3e89/packages/flutter_tools/lib/src/test/flutter_tester_device.dart#L339-L340

I would suggest filing an issue at flutter/flutter with the log/error from above. I'm not very familiar with how flutter-tester works, so it may need some investigation (or at least assistance in capturing more useful information about the crash) from someone more familiar.

Thanks!

**Comment by FaFre** [comment] 2021-12-15 12:12
@DanTup Thank you for your support. I created and linked the corresponding issue.
I'll leave this issue here open for now, please close it if you think it's unrelated.

**Comment by DanTup** [comment] 2021-12-15 12:29
I'll close this since I don't think there's anything to do here, but I've also subscribed to that Flutter issue in case I can be of any help tracking it down.

**Closed by DanTup** 2021-12-15 12:29 UTC
Labels: is bug, upstream in dart / flutter, awaiting info
