### ISSUE TITLE
Let file references in test outputs be clickable? 

### ISSUE THREAD

**Issue by xster** [Dart-Code/Dart-Code#714] opened 2018-03-19 23:14 UTC
Might be pushing my lucks here :)

When a flutter test fails with a printed stack of where the exception was thrown, can strings referencing lines in a file that's in the workspace be clickable/navigable?

**Comment by DanTup** [comment] 2018-03-20 07:53
> Might be pushing my lucks here :)

Not at all, a very valid request!

But I think a dupe of #451. It's supposed to just work, but for some reason doesn't. Needs some debugging (MS basically have a big regex to detect paths).

I'll mark this as a dupe and tweak the title on that one.

**Closed by DanTup** 2018-03-20 07:53 UTC
Labels: duplicate
