### ISSUE TITLE
Other formatters are dominating VSCode by default and preventing Dart formatter from running

### ISSUE THREAD

**Issue by shamilovtim** [Dart-Code/Dart-Code#2205] opened 2020-01-08 21:50 UTC
The Dart extension does not add a `[dart]:{}` entry to VSCode's global JSON settings. What this means is that many other formatters that users had previously installed which came with default settings of (e.g.) `"editor.defaultFormatter": "esbenp.prettier-vscode"` will completely shut out formatters like Dart from running. The way to get past this issue is by providing the setting with greater specificity to the dart code such as:

```json
"[dart]": {
        "editor.defaultFormatter": "Dart-Code.dart-code"
        },
``` 

In the end the user would have this in their settings and Dart formatter will run:
```json
    "[dart]": {
        "editor.defaultFormatter": "Dart-Code.dart-code"
        },
    "editor.defaultFormatter": "esbenp.prettier-vscode",
```

**Comment by shamilovtim** [comment] 2020-01-08 21:55
Related: https://github.com/dart-lang/dart_style/issues/825

**Comment by DanTup** [comment] 2020-01-09 10:11
> The Dart extension does not add a `[dart]:{}` entry to VSCode's global JSON settings

FWIW, the reason we try to avoid `configurationDefaults` is because of https://github.com/microsoft/vscode/issues/58995. If that was fixed, adding this here would be more reasonable.

I'm curious how people are ending up with formatters set globally though - surely they should all be language-specific?

**Comment by DanTup** [comment] 2020-01-09 10:13
Oh, I found this:

https://github.com/prettier/prettier-vscode#default-formatter

It seems like that extension is specifically encouraging this. In which case this somewhat seems working as intended. If you configure a formatter for every language, then of course it will run for every language. I think really that readme should only include languages that it actually formats.

**Comment by DanTup** [comment] 2020-01-23 16:09
Closing this as I don't think there's anything to do here - see comment above (if you configure a formatter to ru for all languages, it will run for Dart overriding ours by-design).

If you disagree and think there's something we could do, please do shout!

**Closed by DanTup** 2020-01-23 16:09 UTC
