### ISSUE TITLE
Unhelpful code completion options in constructor params

### ISSUE THREAD

**Issue by sethladd** [Dart-Code/Dart-Code#250] opened 2017-01-26 16:54 UTC
Tried to see what other named parameters I could provide. Here's what I saw:

![screen shot 2017-01-25 at 12 03 26 pm](https://cloud.githubusercontent.com/assets/5479/22307072/7c2462f4-e2f6-11e6-881d-ae8e312aa38c.png)

Can we do something better here? Can we show only named parameters?

Thanks!

(not sure if this plugin can do something to help, or if we are constrained by what analyzer can tell us... thought I'd open this issue first)

**Comment by DanTup** [comment] 2017-01-26 17:59
These things all come from the analyzer. We do get back a `relevance` field but the Code API doesn't have anywhere to put it and I don't think a non-alphabetical sort would be nice here even if accepted and sorted by it.

I think it's by design that the analyzer returns too much and lets the client filter and usually that seems to work fine. In this case, if it's invalid to put anything other than a parameter name here (I presume you can only put more named params after you already put one?) then maybe the analyzer could filter this list, or at least something to let us filter them out if it makes sense for our IDE.

I wonder if @bwilkerson has any thoughts on this?

I think https://github.com/dart-lang/sdk/issues/27034 is slightly related to this; with that implemented I think Code would give you information about the signature of the constructor you're calling (though I think it'd be ideal if the list was filtered too).

**Comment by bwilkerson** [comment] 2017-01-26 18:05
This is definitely an issue that should be solved in the server; all of our clients have the same issue and need the same solution.

@sethladd Can you move this issue into the sdk issue tracker? (I don't know the magic incantation.)

**Comment by DanTup** [comment] 2017-02-25 11:15
Based on https://github.com/dart-lang/sdk/issues/28529#issuecomment-281428292 I expect this will be fixed in Dart 1.23 :-)

**Closed by DanTup** 2017-02-25 11:15 UTC
Labels: enhancement, fixed externally: dart 1.23
