### ISSUE TITLE
devtools port always binds to 9100

### ISSUE THREAD

**Issue by flbaue** [Dart-Code/Dart-Code#3355] opened 2021-05-20 16:21 UTC
**Describe the bug**
I added a configuration to vscode settings.json to bind the devtools port to 10999. But wenn I start a Flutter app from vscode, the default port 9100 will also be used by the dev tools. In fact, it looks like I have two instances of the devtools running then. One on port 10999 and one on port 9100.

**To Reproduce**
1. Add `"dart.devToolsPort": 10999` to the vscode settings.
2. Start a flutter app from vscode
3. Open the devtools from vscode (will open on port 10999)
4. Open 127.0.0.1:9100 will also open the devtools

**Expected behavior**
The devtools instance should only be available under the configured port 10999.

**Screenshots**
<img width="412" alt="Bildschirmfoto 2021-05-20 um 18 18 10" src="https://user-images.githubusercontent.com/721075/119014372-3462f480-b998-11eb-86ff-74a8dcf0d804.png">
<img width="589" alt="Bildschirmfoto 2021-05-20 um 18 20 06" src="https://user-images.githubusercontent.com/721075/119014378-35942180-b998-11eb-9838-497a584beefc.png">
<img width="589" alt="Bildschirmfoto 2021-05-20 um 18 20 18" src="https://user-images.githubusercontent.com/721075/119014383-35942180-b998-11eb-9427-236750539e20.png">

**Versions (please complete the following information):**
 - VS Code version: 1.56.2
 - Dart extension version: 3.22.0
 - Dart/Flutter SDK version: Flutter 2.0.6

**Comment by DanTup** [comment] 2021-05-24 12:57
I can't reproduce this - is it possible you didn't restart VS code after changing the port (in which case the first server may still have been running), or you did something else that could've started another copy of DevTools (for example having multiple VS Code windows open or running an app from the terminal)?

If not, can you still reproduce this and provide exact instructions (starting from when there is nothing bound to that port, to ending up with two)? Thanks!

**Comment by flbaue** [comment] 2021-05-24 17:04
I just upgraded to Flutter 2.2.0 and that seems to have fixed the issue.

Before, I (and my colleagues) had the issue continuously since upgrading to Flutter 2.0.0. We have a Docker container running on port 9100, which serves the app backend. The result of that was, that after starting the app you always needed to find the Dart process bund to 9100 with `sudo lsof -i :9100` and then kill it.

**Comment by DanTup** [comment] 2021-05-25 11:31
> I just upgraded to Flutter 2.2.0 and that seems to have fixed the issue.

Glad to hear! I'm not sure what changed that would've fixed it, but if it's not happening now I'll close this. If it comes back, please let me know and provide instructions as described above. Thanks!

**Closed by DanTup** 2021-05-25 11:31 UTC
Labels: awaiting info, is bug
