### ISSUE TITLE
High memory consumption

### ISSUE THREAD

**Issue by ValentinVignal** [Dart-Code/Dart-Code#4381] opened 2023-02-09 09:50 UTC
Type: <b>Performance Issue</b>

It is the same issue as https://github.com/Dart-Code/Dart-Code/issues/4380

But here, I'm raising it from the VSCode help option with the hope it will include more information for you

Extension version: 3.58.0
VS Code version: Code 1.75.0 (e2816fe719a4026ffa1ee0189dc89bdfdbafb164, 2023-02-01T15:24:42.903Z)
OS version: Darwin x64 20.6.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|22, 15, 14|
|Memory (System)|16.00GB (0.04GB free)|
|Process Argv|--crash-reporter-id 5f78dc76-1d5f-456c-b50c-b31cf014dea6|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
   16	    82	 18897	code main
    3	    33	 18901	   gpu-process
    0	    16	 18904	   utility-network-service
    0	    49	 19236	   shared-process
    0	    16	 19239	     ptyHost
    0	     0	 21627	       /bin/zsh -il
    0	    16	 31866	     fileWatcher
    0	     0	 42160	     /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    8	   147	 21544	   window (tasks_header.dart — MyProject)
  409	    98	 31865	   extension-host
    0	    16	 31901	     /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/Code Helper (Plugin) --ms-enable-electron-run-as-node /Users/valentin/.vscode/extensions/streetsidesoftware.code-spell-checker-2.16.0/packages/_server/dist/main.js --node-ipc --clientProcessId=31865
    0	    16	 31902	     /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/Code Helper (Plugin) --ms-enable-electron-run-as-node /Users/valentin/.vscode/extensions/redhat.vscode-yaml-1.11.0/dist/languageserver.js --node-ipc --clientProcessId=31865
    0	    16	 31903	     /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/Code Helper (Plugin) --ms-enable-electron-run-as-node /Users/valentin/.vscode/extensions/kisstkondoros.vscode-gutter-preview-0.30.0/dist/server.js --node-ipc --clientProcessId=31865
    0	    16	 31904	     /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/Code Helper (Plugin) --ms-enable-electron-run-as-node /Users/valentin/.vscode/extensions/mtxr.sqltools-0.27.1/dist/languageserver.js --node-ipc --clientProcessId=31865
    0	    16	 31910	     /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/Code Helper (Plugin) --ms-enable-electron-run-as-node /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/json-language-features/server/dist/node/jsonServerMain --node-ipc --clientProcessId=31865
    0	    16	 32155	     electron_node config.js 
    0	     0	 32214	       /usr/bin/script -t 0 /dev/null xcrun xcdevice observe --both
    0	    16	 32215	         /Applications/Xcode.app/Contents/Developer/usr/bin/xcdevice observe --both
    0	    16	 32157	     /Users/valentin/flutter/flutter/bin/cache/dart-sdk/bin/dart devtools --machine --try-ports 10 --allow-embedding
  221	  2867	 32164	     /Users/valentin/flutter/flutter/bin/cache/dart-sdk/bin/dart language-server --protocol=lsp --client-id=VS-Code --client-version=3.58.0
    0	    16	 42016	     /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/Code Helper (Plugin) --ms-enable-electron-run-as-node --max-old-space-size=3072 /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js --serverMode partialSemantic --useInferredProjectPerProjectRoot --disableAutomaticTypingAcquisition --cancellationPipeName /var/folders/pl/d95zgbzd4hbb3z0rt9bl02z40000gn/T/vscode-typescript501/06df53c92d7ace3bcd77/tscancellation-c2c88bcbc4071b7e9627.tmp* --globalPlugins typescript-svelte-plugin --pluginProbeLocations /Users/valentin/.vscode/extensions/svelte.svelte-vscode-107.0.2 --locale en --noGetErrOnBackgroundUpdate --validateDefaultNpmLocation --useNodeIpc
    0	    16	 42017	     /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/Code Helper (Plugin) --ms-enable-electron-run-as-node --max-old-space-size=3072 /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js --useInferredProjectPerProjectRoot --enableTelemetry --cancellationPipeName /var/folders/pl/d95zgbzd4hbb3z0rt9bl02z40000gn/T/vscode-typescript501/06df53c92d7ace3bcd77/tscancellation-b500550a85d081ed41dd.tmp* --globalPlugins typescript-svelte-plugin --pluginProbeLocations /Users/valentin/.vscode/extensions/svelte.svelte-vscode-107.0.2 --locale en --noGetErrOnBackgroundUpdate --validateDefaultNpmLocation --useNodeIpc
    0	    16	 42021	       /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/Code Helper (Plugin) --ms-enable-electron-run-as-node /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typingsInstaller.js --globalTypingsCacheLocation /Users/valentin/Library/Caches/typescript/4.9 --enableTelemetry --typesMapLocation /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typesMap.json --validateDefaultNpmLocation
    0	    16	 42018	     /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/Code Helper (Plugin) --ms-enable-electron-run-as-node /Users/valentin/.vscode/extensions/dbaeumer.vscode-eslint-2.4.0/server/out/eslintServer.js --node-ipc --clientProcessId=31865
    0	    16	 42045	     /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/Code Helper (Plugin) --ms-enable-electron-run-as-node /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/css-language-features/server/dist/node/cssServerMain --node-ipc --clientProcessId=31865
    0	    16	 42046	     /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/Code Helper (Plugin) --ms-enable-electron-run-as-node /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/html-language-features/server/dist/node/htmlServerMain --node-ipc --clientProcessId=31865
    0	    49	 42149	   issue-reporter
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (tasks_header.dart — MyProject)
|    Folder (MyProject): more than 36080 files
|      File types: html(7361) h(721) part(662) pcm(591) svg(568) d(458)
|                  dia(452) o(452) timestamp(450) plist(248)
|      Conf files: github-actions(1) launch.json(1) settings.json(1)
|      Launch Configs: dart(12);
```

</details>
<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
pyindex848:30577860
nodejswelcome1:30587005
3biah626:30602489
89544117:30613380
pythonsymbol12cf:30657549
a9j8j154:30646983

```

</details>

**Comment by DanTup** [comment] 2023-02-09 10:08
Thanks for the extra info. I don't think there's anything additional there, but it's useful to have. I'll close this as a dupe of #4380 so we can keep all the discussion in one place (I've just responded there). Thanks!

**Closed by DanTup** 2023-02-09 10:08 UTC
