### ISSUE TITLE
Asserts are no longer enabled by default for non-debug sessions

### ISSUE THREAD

**Issue by bwilkerson** [Dart-Code/Dart-Code#4379] opened 2023-02-08 14:53 UTC
There might already be a way to do this that I didn't find, but I would like to be able to run code with asserts enabled without having to be running under the debugger. The primary motivation for not using the debugger is that the code runs slower.

My guess is that this would need to be a preference setting, but I'm happy with any solution you think would be best.

**Comment by DanTup** [comment] 2023-02-08 15:08
Hmmm, on the surface this feels like a bug to me. I was under the impression we always ran with asserts enabled from the IDE by default (because I assumed at dev time that's what you'd want), however I can repro this doesn't work and it's because of this `isDebug` here:

https://github.com/Dart-Code/Dart-Code/blob/7a2a7cca930de436a73d9885b312a9e4b23ec491/src/extension/providers/debug_config_provider.ts#L635-L636

It was added during the migration of flags from inside the debug adapter into the VS Code extension (to simplify the new debug adapters), but it doesn't appear to have had this condition when it was in the debug adapter. The [change](https://github.com/Dart-Code/Dart-Code/commit/09d51b6a2fab1dc8b09eafb80e5d7705c2985a02) doesn't describe that it was deliberate, although it seems hard to do this accidentally.

I'm going to try removing that condition and running the bots and see what happens.

In the meantime, if you have a launch.json you can add `--enable-asserts` to `toolArgs`. This will apply to running using the Run/Debug **menu** (and pressing `F5` etc.), but to make it apply to the Run/Debug **CodeLens** (the links above main/test/group methods), it needs to be marked as a template with `templateFor: ""`:

```js
{
	"version": "0.2.0",
	"configurations": [
		{
			"name": "dart",
			"request": "launch",
			"type": "dart",
			"toolArgs": [
				"--enable-asserts" // enable asserts
			],
			"templateFor": "", // use as the template for Run/Debug for the whole project (this is a path prefix, empty string matches the entire project)
		}
	]
}
```

**Comment by DanTup** [comment] 2023-02-08 15:32
This was originally implemented in https://github.com/Dart-Code/Dart-Code/commit/af06b7f6d5e5c00d4edbe0fea94b82454fdf7cbe for #3702 but had no tests which would've probably have picked up the regression.

Bots are all green so I'm going to restore this (and add tests).

**Closed** 2023-02-08 15:51 UTC
Labels: is bug, in debugger

**Comment by DanTup** [comment] 2023-02-08 16:41
@bwilkerson btw I kicked off a pre-release version with this in it earlier. If you're on the pre-release Dart extension and have updated to v3.59.20230208 (note the last digit is an 8, there was a pre-release yesterday ending 7 but otherwise the same) and reloaded, then asserts should be on by default and not need the `launch.json` gymnastics above (unless you want to disable asserts).

I can't be certain this change in default behaviour won't upset anyone, but it was the original and intended behaviour. If this poses a problem we can add a setting to make it easier to control without needing a launch configuration.
