### ISSUE TITLE
Running iOS app from VS Code stuck on "Waiting for VM Service port to be available..."

### ISSUE THREAD

**Issue by GrzesiekZbozien** [Dart-Code/Dart-Code#4593] opened 2023-06-19 06:17 UTC
When running app form VS code (debug or F5). iOS app stuck with "Waiting for VM Service port to be available..." message and blank white screen. 

When using console: 
`(cd implementations/clm6_app && flutter run -d 9C50A24D-DFA0-4502-8FAF-82CE18BEB980 --flavor clm6test1 -t "lib/main_clm6test1.dart")` 
or Xcode app runs fine.

For other project run works fine so I'm guessing it's because of custom target/scheme configuration. I've created 2 targets and 2 schemas to run those two. 
It seems that VS Code isn't able to connect for Debug and result with white screen. When running from console or Xcode app starts just fine

` [   +3 ms] executing: /usr/bin/arch -arm64e xcrun simctl launch 9C50A24D-DFA0-4502-8FAF-82CE18BEB980 [bundle].test1 --enable-dart-profiling --start-paused --enable-checked-mode --verify-entry-points
[ +237 ms] [bundle].test1: 38858
[        ] Waiting for VM Service port to be available...`
 
 - Operating System and version: macOS 13.4
 - VS Code version: 1.79.2 (Universal)
 - Dart extension version: v3.66.0
[✓] Flutter (Channel stable, 3.10.4, on macOS 13.4 22F66 darwin-arm64, locale pl-PL)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.2)
[✓] VS Code (version 1.79.2)
[✓] Connected device (4 available)
[✓] Network resources

**Comment by DanTup** [comment] 2023-06-19 09:46
> For other project run works fine so I'm guessing it's because of custom target/scheme configuration. I've created 2 targets and 2 schemas to run those two.

Are you able to apply these changes to a new project to see if you have the same problem, so you have a shareable project that triggers the issue?

Could you also confirm if this only happens when you use "Debug" (and not "Run"), and also try capturing a log (please remove anything sensitive before sharing):

- Run the [**Dart: Capture Debugging Logs** command](https://dartcode.org/docs/logging/#capture-debugging-logs)
- Reproduce the issue
- Click **Cancel** on the logging notification to stop logging and open the log
- Remove anything sensitive from the log
- Attach the log here, in a [gist](https://gist.github.com/), or email to me at logs@dartcode.org.

Thanks!

**Comment by GrzesiekZbozien** [comment] 2023-06-20 06:36
I've created project that gets stuck just the same way ours do.
It's here: https://github.com/GrzesiekZbozien/tst-flutter, with readme how to reproduce it.

**Comment by DanTup** [comment] 2023-06-20 10:55
@GrzesiekZbozien when I try to run `xcodegen` I get:

```
2 Spec validations errors:
        - Target "test1Target" has a missing source directory "/Users/danny/Dev/TestStuff/tst-flutter/ios/Flutter/Generated.xcconfig"
        - Target "test2Target" has a missing source directory "/Users/danny/Dev/TestStuff/tst-flutter/ios/Flutter/Generated.xcconfig"
```

The files mentioned don't exist in the repo. Is there something missing?

**Comment by DanTup** [comment] 2023-06-20 11:04
When I try to run using the TEST1 configuration, I get an error about not providing flavour. I get the same thing running from the terminal:

```
danny@Dannys-MacBook-Pro tst-flutter % flutter run -d macos --target lib/main_test1.dart --flavor test1 
Launching lib/main_test1.dart on macOS in debug mode...

The Xcode project defines schemes: Flutter Assemble, Runner
Exception: You must specify a --flavor option to select one of the available schemes.
```

However I don't see this error if I remove `--flavor test1`. Is there a step I'm missing? The xcodegen script completed fine:

```
danny@Dannys-MacBook-Pro tst-flutter % sh ./xcodegen.sh                                                                         
⚙️  Generating plists...
⚙️  Generating project...
⚙️  Writing project...
Created project at /Users/danny/Dev/TestStuff/tst-flutter/ios/Runner.xcodeproj
```

**Comment by DanTup** [comment] 2023-06-20 11:29
I can reproduce this, but also from the terminal. If you run:

```
flutter run -v -d  iphone --target  lib/main_test1.dart  --flavor  test1
```

You'll notice that the output gets stuck in the same place:

```
[   +7 ms] executing: xcrun simctl launch C901B07A-DCB8-4FD6-9275-89F592336219 com.example.test1 --enable-dart-profiling --enable-checked-mode --verify-entry-points
[ +317 ms] com.example.test1: 10046
[        ] Waiting for VM Service port to be available...
```

It's less clear that something has gone wrong here because the app is visible. The reason you're seeing a white screen from VS Code is that the app is being started _paused_ (to avoid race conditions with breakpoints) and since the VM Service is never set up, VS Code is never able to connect to the debugger to unpause it. The white screen is just a symptom of the issue, and not the issue.

Perhaps the easiest way to see that it's not actually working from the terminal is that usually when the app starts you would see output like this:

```
Syncing files to device macOS...                                    67ms

Flutter run key commands.
r Hot reload. 🔥🔥🔥
R Hot restart.
h List all available interactive commands.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).

A Dart VM Service on macOS is available at: http://127.0.0.1:52197/yutrX368HRg=/
The Flutter DevTools debugger and profiler on macOS is available at: http://127.0.0.1:9100?uri=http://127.0.0.1:52197/yutrX368HRg=/
```

Because it's getting stuck, you don't see this output (nor can you hot reload/restart).

So I don't think this is a VS Code issue. I think if whatever is causing the output to get stuck (and the output above to not be printed) is preventing VS Code from connecting to the debugger. If that is resolved, I think it'll start working.

I don't know enough about this to say whether this is a Flutter bug, or something not configured correctly in `test1`, but I would suggest filing an issue in flutter/flutter. If it's a configuration issue and Flutter can detect it, it would be better for it to print out an error messages rather than just get stuck like it is. And ofc if it's a bug, it'll need fixing in Flutter. Feel free to ping me if you file an issue there in case I can provide any useful info.

Hope this helps!

**Comment by GrzesiekZbozien** [comment] 2023-06-21 09:18
Created Flutter issue here: https://github.com/flutter/flutter/issues/129246

**Comment by DanTup** [comment] 2023-06-21 09:45
Great thanks - closing this in favour of that one.

**Closed by DanTup** 2023-06-21 09:45 UTC
Labels: is bug, awaiting info
