### ISSUE TITLE
Unable to connect to Chrome debug port: 37095

### ISSUE THREAD

**Issue by mictadlo** [Dart-Code/Dart-Code#3568] opened 2021-09-17 23:26 UTC
Hi all,
I described the problem at https://github.com/flutter/flutter/issues/90265 .

What did I miss?

Thank you in advance

**Comment by DanTup** [comment] 2021-09-20 09:10
Two things I would check:

1. Do you have a proxy server configured? (eg. run `echo $HTTP_PROXY` and `echo $NO_PROXY` in the VS Code terminal and see if there is any output)
2. This may be similar to https://github.com/flutter/flutter/issues/73743 which this [this comment](https://github.com/flutter/flutter/issues/73743#issuecomment-836642774) says may be fixed by using the Snap version of Chromium. If you're not already using the Snap version, could you try that?
3. [This comment](https://github.com/flutter/flutter/issues/73743#issuecomment-856438379) also suggests using Snap versions causes the problem, so using VS Code, Flutter and Chromium _not_ from Snap might help (this is the opposite of above)

**Comment by DanTup** [comment] 2021-09-21 08:36
Based on https://github.com/flutter/flutter/issues/90265#issuecomment-923286840 this appears fixed, and was caused be a mix of Snap/non-Snap installs of Chromium/VS Code/Flutter.

I'm not certain what the issue is with mixing them, but it's not something Dart-Code can resolve, and likely would need handling by Snap or Flutter (if the issue is even fixable).

**Closed by DanTup** 2021-09-21 08:36 UTC
Labels: is bug
