### ISSUE TITLE
Dart Analyzer stops

### ISSUE THREAD

**Issue by roelpaulo** [Dart-Code/Dart-Code#2182] opened 2019-12-22 11:23 UTC
Issue Type: <b>Bug</b>

- Create new flutter project
- Debug and run on any device
- Hover on any Methods or Variables
- A notification will show that the dart analyzer stoped.

Extension version: 3.7.1
VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz (4 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.92GB (0.99GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by DanTup** [comment] 2019-12-23 09:24
This sounds a little like https://github.com/flutter/flutter/issues/46616 which I've had no luck tracking down yet.

Can you reproduce this on a small project (for example the output of `flutter create`)? Could you capture an instrumentation log (see https://github.com/flutter/flutter/issues/46616#issuecomment-567120293) for this happening?

**Comment by roelpaulo** [comment] 2019-12-23 10:03
Strangely, I can't reproduce the error. But it seems it happens when you have a big project. The Analyzer seems to be having problems while reading your code and reading the debug output of the app while running it on debug mode. I'll comment something here when it happens again.

**Comment by DanTup** [comment] 2019-12-23 12:44
> The Analyzer seems to be having problems while reading your code and reading the debug output of the app while running it on debug mode

The analyzer doesn't read any output from Flutter - however my suspicion is that it's because it's analyzing the content being written by Flutter into `.dart_tool`/`build` folders and something there is causing it to crash (possibly along the same lines of https://github.com/dart-lang/sdk/issues/31564).

If it comes back, please do try to capture an instrumentation log, as seeing what's being analyzed for the period leading up to it terminating might be useful. It'd also be useful to know what type of project/device you're running on, in case it's specific to that.

**Comment by dikatok** [comment] 2019-12-24 12:30
I actually experienced this issue in Android Studio as well. I have an instrumentation log just before it happened, do I email it to logs@dartcode.org?

**Comment by DanTup** [comment] 2019-12-24 12:36
Sure - if you can't post it publicly you can email it to me there (please ensure there's nothing sensitive in there). If it's huge, probably on the last few tens(/hundreds) of lines are relevant (if at all). Previously logs didn't reveal much, I'm still a bit unsure what's going on (I've tried a few times to reproduce with no luck).

Other things that would help:

- Exact Flutter version
- Whether you've swapped between Flutter versions
- What device(s) you've run that project on (and which you ran on when it caused the analyzer to terminate)
- How reproducible it is (with the project you experienced it with, and also a new `flutter create` app)

**Comment by dikatok** [comment] 2019-12-26 11:52
Sorry for the delay, I will try to reproduce it few more times. From my experience, running flutter debug from the command prompt / PowerShell (yes, Windows) instead of using the extension seems to lessen the occurrence in VS Code, just one termination when building for the first time, but it breeze trough subsequent hot reloads / hot restarts.

**Comment by marcos930807** [comment] 2019-12-26 16:17
Waiting for this.

**Comment by roelpaulo** [comment] 2020-01-05 14:28
Here is the analyzerInstrumentation.txt log file.

[analyzerInstrumentation.txt](https://github.com/Dart-Code/Dart-Code/files/4023484/analyzerInstrumentation.txt)

Now it happens a lot when I do `flutter clean` then press "Debug with Dart & Flutter" then hover on any class, methods and or variables.

**Comment by DanTup** [comment] 2020-01-08 11:37
Thanks - unfortunately the log doesn't seem to contain anything that stands out. Definitely seems to match the reports in https://github.com/flutter/flutter/issues/46616, but still no joy in reproducing here.

**Comment by roelpaulo** [comment] 2020-01-08 11:58
I think this is an issue with the PC resources. When Flutter builds, it takes up a lot of resources, and when you hover on any of your code, the Dart Analyzer kicks in and tries to take some resources which is isn't available much and then crashes if it can't get much resource. If this is not the case on those people who have a very "High-End Specs" PC's, I think maybe that is what is happening.

**Comment by DanTup** [comment] 2020-01-08 12:01
I believe the analyzer has already terminated at the point that you hover - we just don't show a notification until something next tries to use the analyzer (I'll try to improve this, so there's instant feedback when it crashes).

Can you reproduce this with Task Manager (or similar) open to see what the resource usage is like when this happens?

**Comment by DanTup** [comment] 2020-01-08 12:01
(also, can you post rough specs of your machine?)

**Comment by roelpaulo** [comment] 2020-01-08 12:10
Here is the machine that I use -> https://support.hp.com/ph-en/document/c04799946.

And this the the resource while building:
[https://pasteboard.co/IP0KsJw.jpg](url)

**Comment by marcos930807** [comment] 2020-01-08 14:12
I don't think is a resource problem, because my laptop is an i5 8365U 16GB RAM SDD M2 256GB and build time is short.

**Comment by RollyPeres** [comment] 2020-01-11 01:40
Yesterday happened to work for like 2 hours without this error. Really weird. I personally noticed longer build time for flutter with CPU around 99%-100%, on hotfix5 and 6, which are usually spamming me with the analyzer exception.

**Comment by DanTup** [comment] 2020-01-15 17:46
I was able to reproduce this (see https://github.com/flutter/flutter/issues/46616#issuecomment-574180181). Seems like it may only occur on Windows (which is why it took me a while - I mostly use Mac). I'll ping here/close this issue once a fix has landed.

**Comment by DanTup** [comment] 2020-01-17 11:21
I've landed a fix which is now available in Flutter's master channel. It solves the repro cases I had, though one user has reported it still happening. Please try updating to see if it fixes for you (and post back on https://github.com/flutter/flutter/issues/46616#issuecomment-575556867).

**Closed** 2020-01-17 11:21 UTC
Labels: upstream in dart / flutter
