### ISSUE TITLE
Failed test doesn't change color to red

### ISSUE THREAD

**Issue by hashemp206** [Dart-Code/Dart-Code#2465] opened 2020-05-17 11:07 UTC
after running the test, test fails but status color still is green.
See the animated image below:

![test_failure](https://user-images.githubusercontent.com/3206748/82142792-2db91300-9854-11ea-9e74-af8b3704b51a.gif)

**Comment by DanTup** [comment] 2020-05-18 08:31
The issue here seems to be that the test you're running is not in the tree at all (the one in the tree says `Loading, Error` but this one says `Loading, Loading`.

Can you reproduce getting into this state?

**Comment by hashemp206** [comment] 2020-05-18 08:43
I can't reproduce it. after trying now I can see it in the test tree and color changes to red.

this test is part of 'GetTriviaForConcreteNumber' test group. but I don't know why it was not shown in the test tree.

**Comment by DanTup** [comment] 2020-05-18 08:46
Ok, if you see this happen again, could you try:

1. Run **Dart: capture Logs** and **untick Analysis Server** but leave everything else ticked, and click OK.
2. Re-run the test
3. Click **Cancel** on the logging dialog to stop logging and open the log

And also, can you click Help -> Toggle Developer Tools in VS Code and go to the Console and see if there are any errors/warnings listed.

I'll close this as not-reproducible for now as it'll be hard to investigate without reproducing, but can re-open if it's seen again and we can get the above info.

Thanks!

**Closed** 2020-05-18 08:46 UTC
Labels: cannot reproduce
