### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by aramix** [Dart-Code/Dart-Code#2020] opened 2019-09-24 08:24 UTC
- Issue Type: `Performance`
- Extension Name: `dart-code`
- Extension Version: `3.4.1`
- OS Version: `Darwin x64 19.0.0`
- VSCode version: `1.38.1`

[Dart-Code.dart-code-unresponsive.cpuprofile.txt](https://github.com/Dart-Code/Dart-Code/files/3646069/Dart-Code.dart-code-unresponsive.cpuprofile.txt)

**Comment by larssn** [comment] 2019-09-24 11:42
I'm also seeing heavy CPU and RAM usage. Dart can take over 4GB of RAM total, after a while.

I think they need to debouce some of the "scanning" operations. It scans you entire workspace a bit too often.

I like how the TypeScript analyzer does things, by only analyzing open files, unless you refactor something.

**Comment by DanTup** [comment] 2019-09-30 15:09
@aramix thanks for the profile! I believe this issue will be fixed by https://github.com/Dart-Code/Dart-Code/pull/2003 which changes our directory scanning to be async (the message you get is misleading - the issue is that we block the thread on FS access - there's no actual high CPU).

@larssn your issues are different, as the issue reported here is from the extension (Typescript) code running in the extension host.

If you're having performance issues with the analysis server, please file an issue with info at https://github.com/dart-lang/sdk.

> I think they need to debouce some of the "scanning" operations. It scans you entire workspace a bit too often.

The Dart analysis server doesn't frequently scan your entire workspace - it works incrementally as you make changes to files (and some functions are on-demand).

> I like how the TypeScript analyzer does things, by only analyzing open files

One of the highest voted issues in the VS Code repo is actually to change this:

https://github.com/Microsoft/vscode/issues/13953

However there are many features (for example hovers and type resolution) that can only be done by scanning other files (and TypeScript also does this - for example you'll notice it includes items in code-completion that aren't yet imported - because it's scanned all the files to find exported symbols).

If you're having memory and/or CPU issues with the analysis server, please file bugs with details.

**Comment by DanTup** [comment] 2019-09-30 15:10
(closing this as a dupe of https://github.com/Dart-Code/Dart-Code/issues/1840).

**Closed by DanTup** 2019-09-30 15:10 UTC
Labels: duplicate
