### ISSUE TITLE
ReAnalyze command

### ISSUE THREAD

**Issue by Lisenish** [Dart-Code/Dart-Code#349] opened 2017-07-05 13:53 UTC
Looks like sometimes analyzer is frozen and shows incorrect messages. I want a command to refresh analyzer results.

**Comment by DanTup** [comment] 2017-07-05 17:46
You can run the `Reload Window` command in Code to force everything to be reinitialised (including the analyzer).

However, if you see this frequently or can reproduce on demand I'd really like to look into why. If you enable logging (see [CONTRIBUTING.md](https://github.com/Dart-Code/Dart-Code/blob/master/CONTRIBUTING.md)) there might be some clues in the analyzer log/instrumentation file.

**Comment by DanTup** [comment] 2017-07-05 17:53
I'm resolving this as wontfix because I don't want to add a command that is almost the same as running the built-in `Reload Window`. However, I really would rather track down the issues and get the analyzer fixed than have people do this.

If you're able to get a log, please post back here or raise a new issue so we can do some investigation.

**Closed by DanTup** 2017-07-05 17:53 UTC

**Comment by Lisenish** [comment] 2017-07-10 20:45
Ok, I will try to reproduce it and get logs. I assume this mostly happens after checkout on a different branch within VS Code. Looks like there is some cache issue because I am getting errors after checkout like if there is no new code from the checkouted branch. And when I open files with errors from analyzer - errors disappear.
Also, thanks for `Reload Window` advice, didn't know about that command

**Comment by DanTup** [comment] 2017-07-10 22:23
#269 and #316 may be related.. had other reports of things not working correctly after changing branches but so far nobody has provided logs to help debug (cc @bwilkerson).

The instrumentation log file might be useful in tracking this down though will contain source code etc so please review before attaching (or distribute privately).

**Comment by ThinkDigitalSoftware** [comment] 2020-11-05 18:45
> You can run the `Reload Window` command in Code to force everything to be reinitialised (including the analyzer).
> 
> However, if you see this frequently or can reproduce on demand I'd really like to look into why. If you enable logging (see [CONTRIBUTING.md](https://github.com/Dart-Code/Dart-Code/blob/master/CONTRIBUTING.md)) there might be some clues in the analyzer log/instrumentation file.

What about in IntelliJ? Also, Since restarting the analyzer is a potentially expensive process, reanalyzing a single file is useful. I'm in a large project and it takes around 15-20 seconds to analyze all the files and I really do just need only one done.

**Comment by DanTup** [comment] 2020-11-09 12:15
> What about in IntelliJ?

I don't work on the IntelliJ plugin so I don't know exactly how it works, though I think it has an option somewhere to restart the analyzer (I don't know about just reanalyzing).

> Since restarting the analyzer is a potentially expensive process, reanalyzing a single file is useful.

The server doesn't currently have a way to re-analyze only a single file (we call [this method](https://htmlpreview.github.io/?https://github.com/dart-lang/sdk/blob/master/pkg/analysis_server/doc/api.html#request_analysis.reanalyze)) however it would probably be better to track down why you're needing to call it frequently rather than adding that. If you can provide a repro that triggers the analysis results becoming out-of-date, I'd be interested in understanding what's gone wrong. Thanks!

**Comment by bwilkerson** [comment] 2020-11-09 15:19
> ... I think it has an option somewhere to restart the analyzer (I don't know about just reanalyzing).

Yes, it has an option to restart the analyzer, though our goal is that users won't ever need to use that option.

It no longer has an option to just reanalyze. We used to support both options, but the reanalyze option was removed when we discovered that users were confused about what the difference was and chose to keep the one that was more likely to resolve the problems that users were seeing (most of which have now been fixed).
