### ISSUE TITLE
VisualCode Flutter is writing until is running out of space

### ISSUE THREAD

**Issue by K-Jean** [Dart-Code/Dart-Code#2450] opened 2020-05-12 19:43 UTC
**Summary :** 

When I connect my iPhone 11 Pro on my MacBook and Visual Code is open with flutter extension, flutter write like a crazy on my hard drive until he runs out of space.

<img width="1176" alt="image" src="https://user-images.githubusercontent.com/10814715/81737704-cc322680-9498-11ea-9103-e48d25fc1b6e.png">

After reboot :

<img width="1177" alt="image" src="https://user-images.githubusercontent.com/10814715/81737775-ea982200-9498-11ea-909b-eb2de65d219f.png">

And in the trash bin this folder * 166 (size 1go / folder) :

<img width="1650" alt="image" src="https://user-images.githubusercontent.com/10814715/81737875-14e9df80-9499-11ea-8eeb-7f25548c700b.png">

And in each folder :

<img width="1489" alt="image" src="https://user-images.githubusercontent.com/10814715/81737984-3945bc00-9499-11ea-8155-78360a4afedc.png">

The disk-space stop increasing when I close visual code studio or when I disconnect my iPhone from my Mac.

Device:

MacBook Pro (15 pouces, 2019)
Processeur : 2,6 GHz Intel Core i7 6 cœurs
RAM: 16 Go 2400 MHz DDR4
Intel UHD Graphics 630 1536 Mo

Software : 

**Visual Code Studio** 

> Version: 1.45.0
> Commit: d69a79b73808559a91206d73d7717ff5f798f23c
> Date: 2020-05-07T15:57:33.467Z (5 days ago)
> Electron: 7.2.4
> Chrome: 78.0.3904.130
> Node.js: 12.8.1
> V8: 7.8.279.23-electron.0
> OS: Darwin x64 19.4.0

**extension dart-code.flutter**

> Version 3.10.1

**flutter**

> Flutter 1.17.0 • channel stable • https://github.com/flutter/flutter.git
> Framework • revision e6b34c2b5c (10 days ago) • 2020-05-02 11:39:18 -0700
> Engine • revision 540786dd51
> Tools • Dart 2.8.1

**Comment by DanTup** [comment] 2020-05-13 09:28
This has come up before - I believe it's something weird going on with the Xcode/Simulator tools. There's some info here:

https://apple.stackexchange.com/questions/387634/temporary-dyld-shared-cache-taking-a-lot-of-space/387843#387843

> It was fixed after opening Xcode and going to Window/Devices and Simulators. There select your iPhone and wait for the process of "Copying cache files from device" to finish

Please let me know if this resolves the issue.

**Comment by DanTup** [comment] 2020-05-18 09:45
Closing as a dupe of https://github.com/flutter/flutter/issues/56826.

**Closed by DanTup** 2020-05-18 09:45 UTC
Labels: awaiting info
