### ISSUE TITLE
Dart Ectension Keeps Stopping while using MathJax via Flutter_tex

### ISSUE THREAD

**Issue by sehbanalam** [Dart-Code/Dart-Code#2204] opened 2020-01-08 21:22 UTC
Logs are as follows

!! PLEASE REVIEW THIS LOG FOR SENSITIVE INFORMATION BEFORE SHARING !!

Dart Code extension: 3.7.1
Flutter extension: 3.7.1 (not activated)
VS Code: 1.41.1
Platform: win
HTTP_PROXY: undefined
NO_PROXY: undefined

Thu Jan 09 2020 [02:49:00 GMT+0530 (India Standard Time)] Log file started
[2:49:00 AM] [General] [Info] Searching for SDKs...
[2:49:00 AM] [General] [Info] Environment PATH:
[2:49:00 AM] [General] [Info]     C:\Windows\system32
[2:49:00 AM] [General] [Info]     C:\Windows
[2:49:00 AM] [General] [Info]     C:\Windows\System32\Wbem
[2:49:00 AM] [General] [Info]     C:\Windows\System32\WindowsPowerShell\v1.0\
[2:49:00 AM] [General] [Info]     C:\Windows\System32\OpenSSH\
[2:49:00 AM] [General] [Info]     C:\Program Files (x86)\QuickTime\QTSystem\
[2:49:00 AM] [General] [Info]     C:\Program Files\Dart\dart-sdk\bin
[2:49:00 AM] [General] [Info]     C:\Program Files\Git\cmd
[2:49:00 AM] [General] [Info]     C:\src\flutter\bin
[2:49:00 AM] [General] [Info] Found Flutter project at D:\OFFICE\Edukiran\Flutter\edukiran_student\edukiran_student:
			Mobile? true
			Web? false
			Create Trigger? false
			Flutter Repo? false
[2:49:00 AM] [General] [Info] Searching for flutter.bat
[2:49:00 AM] [General] [Info]     Looking for flutter.bat in:
[2:49:00 AM] [General] [Info]         D:\OFFICE\Edukiran\Flutter\edukiran_student\edukiran_student
[2:49:00 AM] [General] [Info]         D:\OFFICE\Edukiran\Flutter\edukiran_student\edukiran_student\bin
[2:49:00 AM] [General] [Info]         C:\src\flutter\bin\
[2:49:00 AM] [General] [Info]         D:\OFFICE\Edukiran\Flutter\edukiran_student\edukiran_student\.flutter
[2:49:00 AM] [General] [Info]         D:\OFFICE\Edukiran\Flutter\edukiran_student\edukiran_student\.flutter\bin
[2:49:00 AM] [General] [Info]         D:\OFFICE\Edukiran\Flutter\edukiran_student\edukiran_student\vendor\flutter
[2:49:00 AM] [General] [Info]         D:\OFFICE\Edukiran\Flutter\edukiran_student\edukiran_student\vendor\flutter\bin
[2:49:00 AM] [General] [Info]         C:\Windows\system32
[2:49:00 AM] [General] [Info]         C:\Windows\system32\bin
[2:49:00 AM] [General] [Info]         C:\Windows
[2:49:00 AM] [General] [Info]         C:\Windows\bin
[2:49:00 AM] [General] [Info]         C:\Windows\System32\Wbem
[2:49:00 AM] [General] [Info]         C:\Windows\System32\Wbem\bin
[2:49:00 AM] [General] [Info]         C:\Windows\System32\WindowsPowerShell\v1.0\
[2:49:00 AM] [General] [Info]         C:\Windows\System32\WindowsPowerShell\v1.0\bin
[2:49:00 AM] [General] [Info]         C:\Windows\System32\OpenSSH\
[2:49:00 AM] [General] [Info]         C:\Windows\System32\OpenSSH\bin
[2:49:00 AM] [General] [Info]         C:\Program Files (x86)\QuickTime\QTSystem\
[2:49:00 AM] [General] [Info]         C:\Program Files (x86)\QuickTime\QTSystem\bin
[2:49:00 AM] [General] [Info]         C:\Program Files\Dart\dart-sdk\bin
[2:49:00 AM] [General] [Info]         C:\Program Files\Git\cmd
[2:49:00 AM] [General] [Info]         C:\Program Files\Git\cmd\bin
[2:49:00 AM] [General] [Info]         C:\src\flutter\bin
[2:49:00 AM] [General] [Info]     Found at:
[2:49:00 AM] [General] [Info]         C:\src\flutter\bin\
[2:49:00 AM] [General] [Info]         C:\src\flutter\bin
[2:49:00 AM] [General] [Info]     Candidate paths to be post-filtered:
[2:49:00 AM] [General] [Info]         C:\src\flutter
[2:49:00 AM] [General] [Info]         C:\src\flutter
[2:49:00 AM] [General] [Info]     Found at C:\src\flutter
[2:49:00 AM] [General] [Info]     Returning SDK path C:\src\flutter for flutter.bat
[2:49:00 AM] [General] [Info] Searching for dart.exe
[2:49:00 AM] [General] [Info]     Looking for dart.exe in:
[2:49:00 AM] [General] [Info]         C:\src\flutter\bin\cache\dart-sdk
[2:49:00 AM] [General] [Info]         C:\src\flutter\bin\cache\dart-sdk\bin
[2:49:00 AM] [General] [Info]         C:\Windows\system32
[2:49:00 AM] [General] [Info]         C:\Windows\system32\bin
[2:49:00 AM] [General] [Info]         C:\Windows
[2:49:00 AM] [General] [Info]         C:\Windows\bin
[2:49:00 AM] [General] [Info]         C:\Windows\System32\Wbem
[2:49:00 AM] [General] [Info]         C:\Windows\System32\Wbem\bin
[2:49:00 AM] [General] [Info]         C:\Windows\System32\WindowsPowerShell\v1.0\
[2:49:00 AM] [General] [Info]         C:\Windows\System32\WindowsPowerShell\v1.0\bin
[2:49:00 AM] [General] [Info]         C:\Windows\System32\OpenSSH\
[2:49:00 AM] [General] [Info]         C:\Windows\System32\OpenSSH\bin
[2:49:00 AM] [General] [Info]         C:\Program Files (x86)\QuickTime\QTSystem\
[2:49:00 AM] [General] [Info]         C:\Program Files (x86)\QuickTime\QTSystem\bin
[2:49:00 AM] [General] [Info]         C:\Program Files\Dart\dart-sdk\bin
[2:49:00 AM] [General] [Info]         C:\Program Files\Git\cmd
[2:49:00 AM] [General] [Info]         C:\Program Files\Git\cmd\bin
[2:49:00 AM] [General] [Info]         C:\src\flutter\bin
[2:49:00 AM] [General] [Info]         C:\src\flutter\bin\cache\dart-sdk
[2:49:00 AM] [General] [Info]         C:\src\flutter\bin\cache\dart-sdk\bin
[2:49:00 AM] [General] [Info]     Found at:
[2:49:00 AM] [General] [Info]         C:\src\flutter\bin\cache\dart-sdk\bin
[2:49:00 AM] [General] [Info]         C:\Program Files\Dart\dart-sdk\bin
[2:49:00 AM] [General] [Info]         C:\src\flutter\bin\cache\dart-sdk\bin
[2:49:00 AM] [General] [Info]     Candidate paths to be post-filtered:
[2:49:00 AM] [General] [Info]         C:\src\flutter\bin\cache\dart-sdk
[2:49:00 AM] [General] [Info]         C:\Program Files\Dart\dart-sdk
[2:49:00 AM] [General] [Info]         C:\src\flutter\bin\cache\dart-sdk
[2:49:00 AM] [General] [Info]     Found at C:\src\flutter\bin\cache\dart-sdk
[2:49:00 AM] [General] [Info]     Returning SDK path C:\src\flutter\bin\cache\dart-sdk for dart.exe
[2:49:00 AM] [General] [Info] Activating Flutter extension for Flutter project...
[2:49:00 AM] [General] [Info] Extension:Startup timing: 250ms
[2:49:00 AM] [General] [Info] Analyzer:Startup timing: 661ms
[2:49:05 AM] [General] [Info] Analyzer:FirstAnalysis timing: 3462ms
[2:49:06 AM] [General] [Info] Returning cached promise for getSupportedPlatforms()
[2:49:06 AM] [General] [Info] Returning cached promise for getSupportedPlatforms()
[2:49:06 AM] [General] [Info] Checking 1 projects for supported platforms
[2:49:07 AM] [General] [Info] Supported platforms for the workspace are ios, android, web
[2:49:28 AM] [General] [Info] Starting debug session...
[2:49:28 AM] [General] [Info]     workspace: D:\OFFICE\Edukiran\Flutter\edukiran_student\edukiran_student
[2:49:28 AM] [General] [Info] Using found common entry point: D:\OFFICE\Edukiran\Flutter\edukiran_student\edukiran_student\lib\main.dart
[2:49:28 AM] [General] [Info] Using workspace as cwd: D:\OFFICE\Edukiran\Flutter\edukiran_student\edukiran_student
[2:49:28 AM] [General] [Info] Detected launch project as Flutter
[2:49:28 AM] [General] [Info] Using Flutter debug adapter for this session
[2:49:28 AM] [General] [Info] Checking for errors before launching
[2:49:28 AM] [General] [Info] Spawning a new flutter debugger
[2:49:28 AM] [General] [Info] Debug session starting...
    {
        "name": "Flutter",
        "request": "launch",
        "type": "dart",
        "program": "D:\\OFFICE\\Edukiran\\Flutter\\edukiran_student\\edukiran_student\\lib\\main.dart",
        "cwd": "D:\\OFFICE\\Edukiran\\Flutter\\edukiran_student\\edukiran_student",
        "args": [],
        "vmAdditionalArgs": [],
        "vmServicePort": 0,
        "dartPath": "C:\\src\\flutter\\bin\\cache\\dart-sdk\\bin\\dart.exe",
        "maxLogLineLength": 2000,
        "pubPath": "C:\\src\\flutter\\bin\\cache\\dart-sdk\\bin\\pub.bat",
        "pubSnapshotPath": "C:\\src\\flutter\\bin\\cache\\dart-sdk\\bin\\snapshots\\pub.dart.snapshot",
        "debugSdkLibraries": true,
        "debugExternalLibraries": true,
        "showDartDeveloperLogs": true,
        "useFlutterStructuredErrors": true,
        "debuggerHandlesPathsEverywhereForBreakpoints": true,
        "evaluateGettersInDebugViews": true,
        "previewDebuggerStepBack": false,
        "forceFlutterVerboseMode": false,
        "flutterTrackWidgetCreation": true,
        "flutterMode": "debug",
        "flutterPlatform": "default",
        "flutterPath": "C:\\src\\flutter\\bin\\flutter.bat",
        "deviceId": "6dd21593e26c",
        "deviceName": "Mi A3 (android-arm64)",
        "showMemoryUsage": false,
        "debugServer": 61081,
        "debuggerType": 2
    }
[2:49:28 AM] [General] [Warn] Did not find session 7cc77ed9-cf03-42c8-bf12-4d7d58730c18 to handle dart.launching. There were 0 sessions:
[2:49:28 AM] [General] [Warn] Event will be queued and processed when the session start event fires
[2:49:28 AM] [General] [Info] Processing delayed event dart.launching for session 7cc77ed9-cf03-42c8-bf12-4d7d58730c18
[2:50:32 AM] [General] [Error] Cannot call write after a stream was destroyed
Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
	at doWrite (_stream_writable.js:413:19)
	at writeOrBuffer (_stream_writable.js:401:5)
	at Socket.Writable.write (_stream_writable.js:301:11)
	at m.sendMessage (c:\Users\Sehban Alam\.vscode\extensions\dart-code.dart-code-3.7.1\out\dist\extension.js:1:45556)
	at m.sendMessage (c:\Users\Sehban Alam\.vscode\extensions\dart-code.dart-code-3.7.1\out\dist\extension.js:1:39197)
	at c:\Users\Sehban Alam\.vscode\extensions\dart-code.dart-code-3.7.1\out\dist\extension.js:1:45364
	at new Promise (<anonymous>)
	at m.sendRequest (c:\Users\Sehban Alam\.vscode\extensions\dart-code.dart-code-3.7.1\out\dist\extension.js:1:45176)
	at m.analysisGetHover (c:\Users\Sehban Alam\.vscode\extensions\dart-code.dart-code-3.7.1\out\dist\extension.js:1:288185)
	at c.<anonymous> (c:\Users\Sehban Alam\.vscode\extensions\dart-code.dart-code-3.7.1\out\dist\extension.js:1:247508)
	at Generator.next (<anonymous>)
	at c:\Users\Sehban Alam\.vscode\extensions\dart-code.dart-code-3.7.1\out\dist\extension.js:1:247263
	at new Promise (<anonymous>)
	at r (c:\Users\Sehban Alam\.vscode\extensions\dart-code.dart-code-3.7.1\out\dist\extension.js:1:247008)
	at c.provideHover (c:\Users\Sehban Alam\.vscode\extensions\dart-code.dart-code-3.7.1\out\dist\extension.js:1:247442)
	at c:\Users\Sehban Alam\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:575:255
	at c:\Users\Sehban Alam\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:52:287
	at new Promise (<anonymous>)
	at Object.t.asPromise (c:\Users\Sehban Alam\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:52:259)
	at E.provideHover (c:\Users\Sehban Alam\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\servic…
[2:50:32 AM] [General] [Error] Cannot call write after a stream was destroyed
Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
	at doWrite (_stream_writable.js:413:19)
	at writeOrBuffer (_stream_writable.js:401:5)
	at Socket.Writable.write (_stream_writable.js:301:11)
	at m.sendMessage (c:\Users\Sehban Alam\.vscode\extensions\dart-code.dart-code-3.7.1\out\dist\extension.js:1:45556)
	at m.sendMessage (c:\Users\Sehban Alam\.vscode\extensions\dart-code.dart-code-3.7.1\out\dist\extension.js:1:39197)
	at c:\Users\Sehban Alam\.vscode\extensions\dart-code.dart-code-3.7.1\out\dist\extension.js:1:45364
	at new Promise (<anonymous>)
	at m.sendRequest (c:\Users\Sehban Alam\.vscode\extensions\dart-code.dart-code-3.7.1\out\dist\extension.js:1:45176)
	at m.analysisGetHover (c:\Users\Sehban Alam\.vscode\extensions\dart-code.dart-code-3.7.1\out\dist\extension.js:1:288185)
	at c.<anonymous> (c:\Users\Sehban Alam\.vscode\extensions\dart-code.dart-code-3.7.1\out\dist\extension.js:1:247508)
	at Generator.next (<anonymous>)
	at c:\Users\Sehban Alam\.vscode\extensions\dart-code.dart-code-3.7.1\out\dist\extension.js:1:247263
	at new Promise (<anonymous>)
	at r (c:\Users\Sehban Alam\.vscode\extensions\dart-code.dart-code-3.7.1\out\dist\extension.js:1:247008)
	at c.provideHover (c:\Users\Sehban Alam\.vscode\extensions\dart-code.dart-code-3.7.1\out\dist\extension.js:1:247442)
	at c:\Users\Sehban Alam\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:575:255
	at c:\Users\Sehban Alam\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:52:287
	at new Promise (<anonymous>)
	at Object.t.asPromise (c:\Users\Sehban Alam\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:52:259)
	at E.provideHover (c:\Users\Sehban Alam\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\servic…
[2:50:33 AM] [General] [Error] Cannot call write after a stream was destroyed
Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
	at doWrite (_stream_writable.js:413:19)
	at writeOrBuffer (_stream_writable.js:401:5)
	at Socket.Writable.write (_stream_writable.js:301:11)
	at m.sendMessage (c:\Users\Sehban Alam\.vscode\extensions\dart-code.dart-code-3.7.1\out\dist\extension.js:1:45556)
	at m.sendMessage (c:\Users\Sehban Alam\.vscode\extensions\dart-code.dart-code-3.7.1\out\dist\extension.js:1:39197)
	at c:\Users\Sehban Alam\.vscode\extensions\dart-code.dart-code-3.7.1\out\dist\extension.js:1:45364
	at new Promise (<anonymous>)
	at m.sendRequest (c:\Users\Sehban Alam\.vscode\extensions\dart-code.dart-code-3.7.1\out\dist\extension.js:1:45176)
	at m.analysisGetHover (c:\Users\Sehban Alam\.vscode\extensions\dart-code.dart-code-3.7.1\out\dist\extension.js:1:288185)
	at c.<anonymous> (c:\Users\Sehban Alam\.vscode\extensions\dart-code.dart-code-3.7.1\out\dist\extension.js:1:247508)
	at Generator.next (<anonymous>)
	at c:\Users\Sehban Alam\.vscode\extensions\dart-code.dart-code-3.7.1\out\dist\extension.js:1:247263
	at new Promise (<anonymous>)
	at r (c:\Users\Sehban Alam\.vscode\extensions\dart-code.dart-code-3.7.1\out\dist\extension.js:1:247008)
	at c.provideHover (c:\Users\Sehban Alam\.vscode\extensions\dart-code.dart-code-3.7.1\out\dist\extension.js:1:247442)
	at c:\Users\Sehban Alam\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:575:255
	at c:\Users\Sehban Alam\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:52:287
	at new Promise (<anonymous>)
	at Object.t.asPromise (c:\Users\Sehban Alam\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:52:259)
	at E.provideHover (c:\Users\Sehban Alam\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\servic…
[2:50:34 AM] [General] [Error] Cannot call write after a stream was destroyed
Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
	at doWrite (_stream_writable.js:413:19)
	at writeOrBuffer (_stream_writable.js:401:5)
	at Socket.Writable.write (_stream_writable.js:301:11)
	at m.sendMessage (c:\Users\Sehban Alam\.vscode\extensions\dart-code.dart-code-3.7.1\out\dist\extension.js:1:45556)
	at m.sendMessage (c:\Users\Sehban Alam\.vscode\extensions\dart-code.dart-code-3.7.1\out\dist\extension.js:1:39197)
	at c:\Users\Sehban Alam\.vscode\extensions\dart-code.dart-code-3.7.1\out\dist\extension.js:1:45364
	at new Promise (<anonymous>)
	at m.sendRequest (c:\Users\Sehban Alam\.vscode\extensions\dart-code.dart-code-3.7.1\out\dist\extension.js:1:45176)
	at m.analysisGetHover (c:\Users\Sehban Alam\.vscode\extensions\dart-code.dart-code-3.7.1\out\dist\extension.js:1:288185)
	at c.<anonymous> (c:\Users\Sehban Alam\.vscode\extensions\dart-code.dart-code-3.7.1\out\dist\extension.js:1:247508)
	at Generator.next (<anonymous>)
	at c:\Users\Sehban Alam\.vscode\extensions\dart-code.dart-code-3.7.1\out\dist\extension.js:1:247263
	at new Promise (<anonymous>)
	at r (c:\Users\Sehban Alam\.vscode\extensions\dart-code.dart-code-3.7.1\out\dist\extension.js:1:247008)
	at c.provideHover (c:\Users\Sehban Alam\.vscode\extensions\dart-code.dart-code-3.7.1\out\dist\extension.js:1:247442)
	at c:\Users\Sehban Alam\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:575:255
	at c:\Users\Sehban Alam\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:52:287
	at new Promise (<anonymous>)
	at Object.t.asPromise (c:\Users\Sehban Alam\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:52:259)
	at E.provideHover (c:\Users\Sehban Alam\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\servic…
[2:50:34 AM] [General] [Error] Cannot call write after a stream was destroyed
Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
	at doWrite (_stream_writable.js:413:19)
	at writeOrBuffer (_stream_writable.js:401:5)
	at Socket.Writable.write (_stream_writable.js:301:11)
	at m.sendMessage (c:\Users\Sehban Alam\.vscode\extensions\dart-code.dart-code-3.7.1\out\dist\extension.js:1:45556)
	at m.sendMessage (c:\Users\Sehban Alam\.vscode\extensions\dart-code.dart-code-3.7.1\out\dist\extension.js:1:39197)
	at c:\Users\Sehban Alam\.vscode\extensions\dart-code.dart-code-3.7.1\out\dist\extension.js:1:45364
	at new Promise (<anonymous>)
	at m.sendRequest (c:\Users\Sehban Alam\.vscode\extensions\dart-code.dart-code-3.7.1\out\dist\extension.js:1:45176)
	at m.analysisGetHover (c:\Users\Sehban Alam\.vscode\extensions\dart-code.dart-code-3.7.1\out\dist\extension.js:1:288185)
	at c.<anonymous> (c:\Users\Sehban Alam\.vscode\extensions\dart-code.dart-code-3.7.1\out\dist\extension.js:1:247508)
	at Generator.next (<anonymous>)
	at c:\Users\Sehban Alam\.vscode\extensions\dart-code.dart-code-3.7.1\out\dist\extension.js:1:247263
	at new Promise (<anonymous>)
	at r (c:\Users\Sehban Alam\.vscode\extensions\dart-code.dart-code-3.7.1\out\dist\extension.js:1:247008)
	at c.provideHover (c:\Users\Sehban Alam\.vscode\extensions\dart-code.dart-code-3.7.1\out\dist\extension.js:1:247442)
	at c:\Users\Sehban Alam\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:575:255
	at c:\Users\Sehban Alam\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:52:287
	at new Promise (<anonymous>)
	at Object.t.asPromise (c:\Users\Sehban Alam\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:52:259)
	at E.provideHover (c:\Users\Sehban Alam\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\servic…
[2:50:35 AM] [General] [Error] Cannot call write after a stream was destroyed
Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
	at doWrite (_stream_writable.js:413:19)
	at writeOrBuffer (_stream_writable.js:401:5)
	at Socket.Writable.write (_stream_writable.js:301:11)
	at m.sendMessage (c:\Users\Sehban Alam\.vscode\extensions\dart-code.dart-code-3.7.1\out\dist\extension.js:1:45556)
	at m.sendMessage (c:\Users\Sehban Alam\.vscode\extensions\dart-code.dart-code-3.7.1\out\dist\extension.js:1:39197)
	at c:\Users\Sehban Alam\.vscode\extensions\dart-code.dart-code-3.7.1\out\dist\extension.js:1:45364
	at new Promise (<anonymous>)
	at m.sendRequest (c:\Users\Sehban Alam\.vscode\extensions\dart-code.dart-code-3.7.1\out\dist\extension.js:1:45176)
	at m.analysisGetHover (c:\Users\Sehban Alam\.vscode\extensions\dart-code.dart-code-3.7.1\out\dist\extension.js:1:288185)
	at c.<anonymous> (c:\Users\Sehban Alam\.vscode\extensions\dart-code.dart-code-3.7.1\out\dist\extension.js:1:247508)
	at Generator.next (<anonymous>)
	at c:\Users\Sehban Alam\.vscode\extensions\dart-code.dart-code-3.7.1\out\dist\extension.js:1:247263
	at new Promise (<anonymous>)
	at r (c:\Users\Sehban Alam\.vscode\extensions\dart-code.dart-code-3.7.1\out\dist\extension.js:1:247008)
	at c.provideHover (c:\Users\Sehban Alam\.vscode\extensions\dart-code.dart-code-3.7.1\out\dist\extension.js:1:247442)
	at c:\Users\Sehban Alam\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:575:255
	at c:\Users\Sehban Alam\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:52:287
	at new Promise (<anonymous>)
	at Object.t.asPromise (c:\Users\Sehban Alam\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:52:259)
	at E.provideHover (c:\Users\Sehban Alam\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\servic…

**Comment by DanTup** [comment] 2020-01-11 09:12
This sounds like the ame thing as https://github.com/flutter/flutter/issues/46616 - where the analyzer sometimes terminates when launching a Flutter app. I haven't been able to reproduce it to debug yet, though I think it might be an analysis server bug.

**Comment by DanTup** [comment] 2020-01-11 09:13
I'll close this as a dupe, since there are already a few open issues - subscribe to https://github.com/flutter/flutter/issues/46616 for notifications. Thanks!

**Closed by DanTup** 2020-01-11 09:13 UTC
