### ISSUE TITLE
Contributing internationalization extensions

### ISSUE THREAD

**Issue by alanknight-wk** [Dart-Code/Dart-Code#4331] opened 2023-01-04 17:34 UTC
**Is your feature request related to a problem? Please describe.**
We have written our own (currently private) small VS Code extension for converting strings to be internationalized. So you can click on a literal string and have a quick fix action that turns it into an Intl message call. In talking with @mosuem, he mentioned that this might be something that a broader user base would find useful. It might also be more capable. For example, ours doesn't integrate with the analysis server, but if it were integrated here it presumably could take advantage of existing analysis server integration, and would do better at finding the string boundaries, handling more complex string literals, and probably other things. So we'd be interested in contributing this and helping integrate it.

However, it's not trivial. There's the point about converting to use the analyzer. But we also do our Intl calls differently from Flutter - we start from the Dart source, extract them into a class in a known place per-package, and then we generate the ARB files via extracting. If this were to be broadly useful, it would also want to support putting the strings into an ARB file and changing the message to expect the code to be generated with the Flutter conventions. It seems challenging to try to make that fully general. It might be good to just delegate to an external program, or to an analysis server plugin, but that's not clear.

**Describe the solution you'd like**
Is this something you think would be interesting to pursue? We'd need to get our existing work open-sourced, and would be happy to work on integrating it, but would definitely need some help and advice.

**Comment by DanTup** [comment] 2023-01-04 18:13
It would definitely be good to improve this. There's an open issue at https://github.com/dart-lang/sdk/issues/46722 which I think this is probably a duplicate of?

I think @mosuem may be looking at whether Dart/Flutter's internationalisation could be aligned more, but I don't know the current status. I do think that whatever is done should be in the server rather than directly in a VS Code extension, since it could be used by many editors and take advantage of all the existing parsing/code-gen work there.

Is there anything you think couldn't be done in the server? (If not, we could close this issue and continue in https://github.com/dart-lang/sdk/issues/46722 to keep things in one place - and where the changes are likely to be).

**Comment by alanknight-wk** [comment] 2023-01-05 14:20
Yes, that looks very interesting. Doing that in an analyzer plugin does
seem like a good approach, but I don't know much about them. So yes, I
think that we can close this as a duplicate.

**Closed** 2023-01-05 14:45 UTC
Labels: duplicate

**Comment by alanknight-wk** [comment] 2023-01-05 15:12
I suspect there will be a lot of variation in individual usage, even if we
could reconcile the different basic approaches, which would be tricky
enough in itself. There's going to need to be some significant
configurability.
