### ISSUE TITLE
Have to restart the dart analysis server every time i build the project

### ISSUE THREAD

**Issue by Afsal102** [Dart-Code/Dart-Code#2990] opened 2020-12-07 06:47 UTC
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Versions (please complete the following information):**
 - VS Code version:
 - Dart extension version:
 - Dart/Flutter SDK version:

**Comment by DanTup** [comment] 2020-12-07 11:11
@Afsal102 are you seeing a notification that says "The analyzer has terminated" when running your Flutter app on Windows? Can you confirm the exact version of Flutter you're using (run `flutter --version`).

**Comment by stijnie2210** [comment] 2020-12-09 16:13
@DanTup  I'm running into the exact same problem. I'm running Flutter version 1.22.4 and it's been going on for ages. I used to get a notification that it's been terminated but it doesn't even do that anymore nowadays. It's basically everytime I build.

**Comment by Afsal102** [comment] 2020-12-09 16:37
Yup same issue but in vs code u cld use  ctrl+shft+p and restart dart
analysis server

**Comment by DanTup** [comment] 2020-12-09 18:47
Are you both on Windows? If you can reproduce this on a clean project with Flutter v1.22.4, please enable crash dumps as described here:

https://docs.microsoft.com/en-us/windows/win32/wer/collecting-user-mode-dumps

Then file an issue at https://github.com/dart-lang/sdk with a link to the crash dump. This sounds like a similar issue to https://github.com/dart-lang/sdk/issues/40348 (though the fixes for that should already be in v1.22.4).

Thanks!

(FYI @aam)

**Comment by stijnie2210** [comment] 2020-12-09 21:39
I’m indeed on windows, I’ll try to provide a crash dump in the upcoming
days. According to messages I’ve seen before these issues should’ve been
fixed on multiple stable builds, but even on 1.22.4 its happening to me
every day and it makes developing rather slow at the moment. I’ll get back
to you ASAP.

**Comment by baku-apps** [comment] 2020-12-14 07:09
I have the same issue with Flutter 1.22.4 and 1.22.5.

Restarting de Dart Analyser makes hot reload not work anymore.

**Comment by DanTup** [comment] 2020-12-14 11:11
> Restarting de Dart Analyser makes hot reload not work anymore.

@baku-apps that sounds like a different issue. Can you reproduce it in a small sample app? Could you file a new issue here and use the **Dart: Capture Debugging Logs** command to capture a log. Thanks!

**Comment by stijnie2210** [comment] 2020-12-17 14:58
@DanTup I've tried to setup the Windows error logging (I've upgraded to Flutter 1.22.5 and it's still happening to me btw), but it's not putting any logs in the folder i've set up for it. Can you see anything wrong with it?

![image](https://user-images.githubusercontent.com/8982310/102504066-aa2d0200-4080-11eb-9d5f-992ffcb4a900.png)

**Comment by stijnie2210** [comment] 2020-12-17 16:38
What I do have noticed, the analyzer server mostly crashes in apps I have used the build_runner package and it has generated code. Could that have something to do with it?

**Comment by baku-apps** [comment] 2020-12-18 07:12
> > Restarting de Dart Analyser makes hot reload not work anymore.
> 
> @baku-apps that sounds like a different issue. Can you reproduce it in a small sample app? Could you file a new issue here and use the **Dart: Capture Debugging Logs** command to capture a log. Thanks!

Will do that when I have some time.

**Comment by baku-apps** [comment] 2020-12-18 07:13
The Dart Analyzer terminates when running the flutter app. However with flutter 1.22.4 and above I don't see a popup message that the analyzer has terminated (in VS Code). With Flutter 1.22.3 I do see a popup message asking me to restart the analyzer. Restarting the analyzer on app build works most of the time. (a manual restart later will loose hot reload as mentioned ealier).

Another issue is that the analyzer sometimes doesn't stop analyzing. Which makes everything slow and eats up resources.

**All these Dart Analyzer issues seem to only happen in 1 project I'm working on. Other projects seems the have no issues. The build_runner doesn't seem to be the cause in my case. (as mentioned by @stijnie2210)**

**Comment by baku-apps** [comment] 2020-12-18 07:14
https://github.com/flutter/flutter/issues/70693#issuecomment-747900038 seems to be the same issue.

**Comment by DanTup** [comment] 2020-12-23 12:08
@stijnie2210 

> @DanTup I've tried to setup the Windows error logging (I've upgraded to Flutter 1.22.5 and it's still happening to me btw), but it's not putting any logs in the folder i've set up for it. Can you see anything wrong with it?

I can't see anything wrong, though I always set it directly in the `LocalDumps` key and not `dart.exe`. Maybe worth doing that temporarily while you reproduce, then remove it?

@baku-apps 

> The Dart Analyzer terminates when running the flutter app. However with flutter 1.22.4 and above I don't see a popup message that the analyzer has terminated (in VS Code). With Flutter 1.22.3 I do see a popup message asking me to restart the analyzer.

That does sound like the same issue - though I'm not sure why you're not seeing the prompt for 1.22.4. The version of Flutter shouldn't affect the VS Code's extension's detection of the analyzer crashing. Is it possible something else also changed, such as enabling the LSP preview at the same time?

**Comment by Bestfastfire** [comment] 2020-12-23 18:42
Same here, I'm doing this so I don't have to restart the IDE:

![Screenshot_156](https://user-images.githubusercontent.com/22732544/103027860-69783180-4535-11eb-98b0-b9631f59a531.png)

**Comment by baku-apps** [comment] 2020-12-25 09:01
[dart.exe.13424.zip](https://github.com/Dart-Code/Dart-Code/files/5741601/dart.exe.13424.zip)

@DanTup Hereby the crash dump. Let me know if you need anything else.


> That does sound like the same issue - though I'm not sure why you're not seeing the prompt for 1.22.4. The version of Flutter shouldn't affect the VS Code's extension's detection of the analyzer crashing. Is it possible something else also changed, such as enabling the LSP preview at the same time?

I have not turned on LSP preview.

**Comment by DanTup** [comment] 2020-12-30 12:47
@baku-apps please file an issue at https://github.com/dart-lang/sdk with the crash dump, as this is an issue that will need to be investigated by the VM team; it's not something I'm very familiar with. Thanks!

**Comment by DanTup** [comment] 2021-01-26 15:45
I believe the issues reported here are a combination of:

https://github.com/dart-lang/sdk/issues/40348 - VM crash on Windows for Flutter < 1.22.4 during Flutter builds
https://github.com/dart-lang/sdk/issues/44650 - Code completion stops returning many items on Windows after Flutter builds

The first issue is fixed in the latest Flutter stable release. The second issue is not in stable, but should be in the next major stable release.

If anyone continues to have issues that don't match those descriptions or that do but are on versions that include the fixes (this won't include stable until after the next Flutter release), please file a new issue with specifics. Thanks!

**Closed by DanTup** 2021-01-26 15:45 UTC
Labels: upstream in dart / flutter
