### ISSUE TITLE
Version 3.24.0 is kind of annoying?

### ISSUE THREAD

**Issue by princ3od** [Dart-Code/Dart-Code#3455] opened 2021-07-03 07:16 UTC
In Dart-Code 3.23.1:
![3.23](https://im2.ezgif.com/tmp/ezgif-2-5365d3877e9b.gif)
And in Dart-Code 3.24.0:
![3.24](https://im2.ezgif.com/tmp/ezgif-2-21d34fe67ca1.gif)

Shortly, *"wrap with widget..."* in **Dart-Code 3.24.0** does not select "widget" text for editting immediately. And as you can see, auto-completion is just not the same as **v3.23.1** but in the way more annoying.
Additionally, *"Analyzing..."* of **v3.24.0** is quite longer than **v3.23.1** and not showing label *"Analyzing..."* at bottom of Visual Code.

**Comment by DanTup** [comment] 2021-07-03 09:38
Your images didn't load here, can you re-attach them?

Can you also confirm your version of the Flutter SDK? I think both the issues you mention could be fixed in the latest stable Flutter (v2.2.2).

**Comment by princ3od** [comment] 2021-07-03 10:27
Oh sorry for error images. 
v3.23:
![3.23](https://i.imgur.com/tI7S5My.gif)
v3.24:
![Imgur](https://i.imgur.com/sp2ZkOE.gif)

And my version of the Flutter SDK:
``` bash
Flutter 2.0.5 • channel stable • https://github.com/flutter/flutter.git  
Framework • revision adc687823a (3 months ago) • 2021-04-16 09:40:20 -0700  
Engine • revision b09f014e96  
Tools • Dart 2.12.3  
```

**Comment by DanTup** [comment] 2021-07-03 11:18
@princ3od please upgrade to Flutter v2.2.2 - it includes https://github.com/dart-lang/sdk/commit/44275c6001837550d4a6b7339237ae1c27bdbc19 that fixes the selection of the widget name, and many improvements to the setting analysis roots that I think may by the cause of additional analysis you're seeing.

If you're still seeing either issue in that version, please let me know!

**Comment by fryette** [comment] 2021-07-06 08:00
@DanTup have a question, just migrated to 2.2.2 and have latest dart code plugin.

On the screenshots above we can see that 3.23 has a lot of *white* parameters/fields and so on.
On 3.24 everything has a slightly different palette. Is it intended?

**Comment by princ3od** [comment] 2021-07-15 13:41
After I had upgraded to Flutter v2.2.2, the problems disappeard!
Thanks for your response.

**Comment by DanTup** [comment] 2021-07-15 13:58
Glad to hear!

**Closed by DanTup** 2021-07-15 13:59 UTC
Labels: awaiting info

**Comment by petrnymsa** [comment] 2021-08-03 08:17
@DanTup I am still facing the same issue. 

Dart-Code version v3.25.0
Flutter version v2.2.3

![flash4](https://user-images.githubusercontent.com/21087414/127982181-bbeafaac-b566-4ef0-bfb6-d8fbb2cd0f21.gif)

**Comment by DanTup** [comment] 2021-08-03 10:52
@petrnymsa that issue is in https://github.com/Dart-Code/Dart-Code/issues/3303 and fixed by https://github.com/dart-lang/sdk/commit/8f2c0e9bb8076225923e86c19fbdf4117dc5d0bb. The fix is in the language server so requires an SDK release. The fix is likely already in dev (maybe beta) channels, but not stable yet.
