### ISSUE TITLE
VS Code Dart debugger fails to evaluate expressions when debugging Angular Dart with Chrome debugger

### ISSUE THREAD

**Issue by PDalc** [Dart-Code/Dart-Code#2847] opened 2020-10-03 15:50 UTC
**Describe the bug**
VS Code Dart debugger fails to evaluate many expressions when debugging Angular Dart with Chrome debugger. Things that don't work:
* Evaluating the simple expression **1+1** in the debug console fails with the following error: **not yet implemented**
* Hovering over local variables does not show their value in a tooltip.
* In the "Variables" pane, expanding an object to show its members gives this error: **getObject: NoSuchMethodError: The method '-' was called on null.**
* Adding local variables to the Watch window shows this error instead of their value: **not yet implemented**

**To Reproduce**
1. Create a simple Angular Dart project using the latest VS Code / VS Code plugin / Flutter SDK / Dart SDK indicated below, which are the latest stable versions as of October 2 2020.
2. Place a breakpoint in an event callback Dart function (like onclick()) that has parameters or local variables of the dart:html Event type (or its subclasses).
3. Launch the web app in debug mode, and trigger the event that causes the breakpoint to be hit.
4. Try to hover your mouse over local variables (which have already been initialized).
   Expected behavior: a tooltip showing the current value
   Actual behavior: no value is shown. This problem occurs with variables of all types, including "simple" types (e.g. int) and dart:html Event types.
5. Try to add the local variable of the dart:html Event type (or its subclasses) to the Watch window.
   Expected behavior: the current value is displayed in the watch window
   Actual behavior: the error **not yet implemented** is shown in the watch window. Note that this problem does not occur with variables of "simple" types (e.g. int or List<int>).
6. Try to evaluate the expression 1+1 in the interactive Debug Console.
   Expected behavior: the console should show the evaluated value "2"
   Actual behavior: the error **not yet implemented** is shown in the Debug Console.

I've been experiencing this problem since I started with Angular Dart about 2 months ago, and nothing I have tried has solved it. It is unfortunately making development more difficult.

Importantly, all of the above functionalities work correctly when debugging a simple Dart command-line (console) project (using the exact same VS Code / plugins / Flutter SDK / Dart SDK). The above issues only occur when debugging an Angular Dart project with Chrome Debugger in VS Code.

**Expected behavior**
See "To Reproduce" for details on expected versus actual behavior.

**Versions (please complete the following information):**
 - OS: Windows 10 version 1909
 - VS Code version: 1.49.2
 - Dart extension version:
VS Code "Dart" plugin (version 3.15.0)
VS Code "Debugger for Chrome" plugin (version 4.12.11)
 - Dart/Flutter SDK version: Flutter SDK (1.22.0 channel stable) which includes Dart SDK (2.10.0).
 - Chrome browser: Version 85.0.4183.121 (Official Build) (64-bit)

**Comment by DanTup** [comment] 2020-10-05 10:42
I believe work for expression evaluation in web is not yet complete. There's a PR that looks like work-in-progress for this:

https://github.com/dart-lang/webdev/pull/1105

I think once it is supported, there will need to be a new AngularDart published that allows using the updated versions of the web compilers package (it seems to have quite tight constraints, and even the latest pre-release of Angular doesn't seem to allow using the latest buidld_web_compilers etc.).

@grouma @annagrin is this accurate?

**Comment by grouma** [comment] 2020-10-05 16:18
Correct. VS Code evaluation only works for Flutter Web today. We are working on adding support in `package:webdev` which is what is used to build and run AngularDart applications.

**Comment by PDalc** [comment] 2020-10-05 17:15
Thanks for the quick feedback. I will keep an eye on webdev PR #1105

What is Google using internally to debug their own AngularDart apps? I guess you guys use a different IDE? Do you happen to know which combinations of IDE+browser can successfully debug AngularDart apps without these kinds of issues? Many thanks for any insight you can share on this.

**Comment by DanTup** [comment] 2020-10-05 17:32
Great - I'll close this then as I don't think there's anything to do here. When it's supported by webdev/Angular it should just work here (ofc, if it doesn't, we can re-open or raise new issues). Thanks!

(I don't know the answers to the other questions - I'm not aware of any of the IDEs supporting debugging Dart-web except for debugging the JavaScript directly - which is also possible in VS Code, though the compilation from Dart->JS makes it not a fantastic experience).

**Closed by DanTup** 2020-10-05 17:32 UTC
Labels: upstream in dart / flutter

**Comment by davidmednikov** [comment] 2020-10-07 07:55
> Correct. VS Code evaluation only works for Flutter Web today. We are working on adding support in `package:webdev` which is what is used to build and run AngularDart applications.

I'm using VS Code for Flutter web and getting the exact same error (`getObject: NoSuchMethodError: The method '-' was called on null.`) as mentioned in the OP. Any ideas? Haven't seen much about it online.

![image](https://user-images.githubusercontent.com/17204940/95303185-bf431480-0837-11eb-91e7-c4dbccee475c.png)

**Comment by DanTup** [comment] 2020-10-07 10:11
Turns out there were two different issues described in the top issue here:

1. `NoSuchMethodError: The method '-' was called on null` when populating the Variables list
2. `<no implemented yet>` messages when evaluating expressions

The first one was a real bug that also affected Flutter web, and the second is explained above (not yet supported for non-Flutter).

I raised a separate issue for the first (https://github.com/Dart-Code/Dart-Code/issues/2855) as it was also reported on Discord. It turned out to be caused by VS Code incorrectly sending an `offset` to `getObject()` calls for non-collections. I think the standard VM just ignored this, but it was tripping up the web expression evaluation.

I've fixed that here by not sending `offset` (fyi @grouma @annagrin I don't know if the web expression evaluation should also handle, though it's probably unlikely clients would send it except for a silly bug like the one I fixed here).

**Comment by davidmednikov** [comment] 2020-10-07 16:59
Hi DanTup,

Thank you for the response. Of the 2 issues you mentioned, #1 is exactly what I've been experiencing. I noticed you said you fixed it by not sending `offset` to `getObject()` calls for non-collections. Is this something I can fix on my end as well? Or will I need to wait for an updated release of Flutter / Dart?

Thanks in advance for your help!

**Comment by DanTup** [comment] 2020-10-07 17:02
You'd need a new version of the Dart extension for VS Code. If you really want it, I did a dev build earlier that does include that change:

https://github.com/Dart-Code/Dart-Code/releases/tag/v3.16.0-dev.3

You'd need to:

- download the vsix file
- run the **Extensions: Install from VSIX** command in VS Code
- select the vsix file
- click **Reload**

If you still see the issue with that version, let me know. Thanks!

**Comment by davidmednikov** [comment] 2020-10-07 17:09
You are a lifesaver my friend. Fix is working perfectly!

![image](https://user-images.githubusercontent.com/17204940/95364016-21763680-0885-11eb-8d13-b995bdd60e81.png)

**Comment by davidmednikov** [comment] 2020-10-07 17:18
Sorry to bump - Getting a similar error message and not sure if it's directly related to what was addressed earlier but the Variables section now show an error message that says:

`"<getObject: NoSuchMethodError: The getter 'uri' was called on null.>"`

![image](https://user-images.githubusercontent.com/17204940/95364993-5fc02580-0886-11eb-9601-d02eaab3c005.png)

Any ideas?

**Comment by DanTup** [comment] 2020-10-07 17:20
@davidmednikov I don't think it would be related to the fix, though perhaps the previous bug was masking it. Could you file a new issue (if you can provide steps to repro from a new flutter project, that would help too). Thanks!

**Comment by grouma** [comment] 2020-10-07 17:23
> Thanks for the quick feedback. I will keep an eye on [webdev PR #1105](https://github.com/dart-lang/webdev/pull/1105)
> 
> What is Google using internally to debug their own AngularDart apps? I guess you guys use a different IDE? Do you happen to know which combinations of IDE+browser can successfully debug AngularDart apps without these kinds of issues? Many thanks for any insight you can share on this.

We generally direct users to use Dart DevTools. It is integrated in `webdev` today with the `--debug` flag. You'll need to hit `Alt + D` to debug. Alternatively you can use the Dart Debug Extension.

**Comment by PDalc** [comment] 2020-10-07 17:42
I also downloaded and tested the v3.16.0-dev.3 version of Dart Code and it does appear to solve the error "getObject: NoSuchMethodError: The method '-' was called on null." This is a good improvement in my debugging experience with Dart in VS Code--thanks Dan! I will eagerly wait for the implementation of the expression evaluation.

I tried Dart DevTools and I notice it appears to have the same debugging / expression evaluation limitations as VS Code + Dart plugin. Dart DevTools also seems to be lacking syntax highlighting and a "search in files" command, so I will stick to VS Code for now unless I hit some other VS Code-specific issue.

Again, thanks for your help in resolving this issue.

**Comment by grouma** [comment] 2020-10-07 17:50
> @grouma I tried Dart DevTools and I notice it appears to have the same debugging / expression evaluation limitations as VS Code + Dart plugin.

Sorry I should have been more clear. The tool speaks the same protocol so the expression evaluation support won't work until the PR mentioned above is landed and the feature is turned on.
