### ISSUE TITLE
[Proposal] Provide an option for enabling the forced debug mode

### ISSUE THREAD

**Issue by akemimadoka** [Dart-Code/Dart-Code#4894] opened 2023-12-12 08:10 UTC
**Is your feature request related to a problem? Please describe.**
When debugging a single Dart file and setting the cwd to the root of another Flutter project, the debug mode switches to Flutter.

**Describe the solution you'd like**
Provide a forced debug mode option that uses the user-provided value when available, without performing automatic checks if the value has been set by the user.

**Describe alternatives you've considered**
Downgrade to v3.76.1

**Comment by DanTup** [comment] 2023-12-13 15:14
Can you provide more details about the setup (for example the `launch.config` you're using)?

I think your problem might be solved by having your CLI script inside the `bin/` or `tool/` folder, since those folders are always considered Dart scripts even when in Flutter projects.

**Comment by akemimadoka** [comment] 2023-12-13 15:40
The script is placed in the `bin/` directory

**Comment by DanTup** [comment] 2023-12-13 15:47
There's a related issue at https://github.com/Dart-Code/Dart-Code/issues/4867 with an example that failed because `cwd` was not set, but when setting `cwd` it worked.

Can you provide an example so I can reproduce your issue?

**Comment by akemimadoka** [comment] 2023-12-13 15:56
![image](https://github.com/Dart-Code/Dart-Code/assets/8528322/078f98c6-0294-4e0c-a9de-1bcd47c5752e)
![image](https://github.com/Dart-Code/Dart-Code/assets/8528322/adc55a82-50cc-4d08-81b9-115c1c04b869)
In my case, when I set the cwd to the root directory of the Flutter project, it will be debugged as a Flutter project.

**Comment by DanTup** [comment] 2023-12-13 16:00
Oh, I see - I thought your cwd was the same as the project containing the script. This is actually the case I imagined in the comment at https://github.com/Dart-Code/Dart-Code/issues/4867#issuecomment-1838565019

I'll close this as a dupe of https://github.com/Dart-Code/Dart-Code/issues/4867#issuecomment-1838565019 and we'll tackle it there.

**Closed** 2023-12-13 16:01 UTC
Labels: is enhancement, awaiting info
