### ISSUE TITLE
Cannot find include file when there is sub package

### ISSUE THREAD

**Issue by jeiea** [Dart-Code/Dart-Code#3466] opened 2021-07-08 02:34 UTC
**Describe the bug**
I'm getting the message `The include file package:flutter_lints/flutter.yaml in /Users/jeiea/Documents/2021-02/flutter_example/analysis_options.yaml cannot be found.` despite of correct lint working.

**To Reproduce**
1. Be careful at branch `lints`.
```
git clone https://github.com/jeiea/flutter_example.git -b lints --recurse-submodules
cd flutter_example
flutter pub get
(cd packages/webview_cookie_manager; flutter pub get)
code .
```
2. Open `analysis_options.yaml`.

**Expected behavior**
No error should appear.

**Screenshots**
![image](https://user-images.githubusercontent.com/4188984/124848538-084b1380-dfd8-11eb-9a6e-384cbc4f9740.png)

**Versions:**
```
➜  code --version
1.57.1
507ce72a4466fbb27b715c3722558bb15afa9f48
x64
➜  code --list-extensions --show-versions | rg Dart
Dart-Code.dart-code@3.24.2
Dart-Code.flutter@3.24.0
➜  flutter --version
Flutter 2.2.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision f4abaa0735 (6 days ago) • 2021-07-01 12:46:11 -0700
Engine • revision 241c87ad80
Tools • Dart 2.13.4
```

**Comment by DanTup** [comment] 2021-07-08 09:39
This appears to be the same issue as #3259. The problem is that the `analysis_options.yaml` file is being used for the nested project, but the nested project does not reference `flutter_lints` and therefore the URI cannot be resolved in that context (and produces the warning).

In https://github.com/dart-lang/sdk/commit/6d763b4565765524dda8a00db92a96aea5972cbe I've improved the generated error, so with the latest Flutter master the reported error would be more specific:

> The include file 'package:flutter_lints/flutter.yaml' in '/private/tmp/flutter_example/analysis_options.yaml' can't be found when analyzing '/private/tmp/flutter_example/packages/webview_cookie_manager/example'.

If I add `flutter_lints:` to the `dev_dependencies` in `packages/webview_cookie_manager/example` then the message goes away.

Hope this makes sense!

**Closed** 2021-07-08 09:39 UTC
Labels: duplicate

**Comment by jeiea** [comment] 2021-07-08 09:51
Are you saying recommended action is adding `flutter_lints` as dev dependency of `packages/webview_cookie_manager`?

I can't understand the reason well. Could you explain to me why this is an error?

**Comment by DanTup** [comment] 2021-07-08 10:11
> Are you saying recommended action is adding `flutter_lints` as dev dependency of `packages/webview_cookie_manager`?

Actually in `packages/webview_cookie_manager/example`.

The reason is that you have a project at `packages/webview_cookie_manager/example`. The `analysis_options.yaml` file further up the tree is being used to analyze this project (because the analyzer walks up the tree looking for the nearest analysis_options.yaml` file). Since that file is being used when analyzing `packages/webview_cookie_manager/example`, that project needs to be able to resolve `package:flutter_lints`, and that means it needs to be listed as a dependency.

Alternatively, you could put another `analysis_options.yaml` in the `example` folder which will prevent the one in the parent folder from being used when analyzing the `example` project.

**Comment by ankit9607** [comment] 2023-04-27 13:46
Thanks @DanTup
