### ISSUE TITLE
Debugger stuck on pause when using new SDK DAP

### ISSUE THREAD

**Issue by SuperPenguin** [Dart-Code/Dart-Code#4368] opened 2023-01-29 16:15 UTC
**Describe the bug**
Debugger stuck on pause when exiting program using new SDK DAP

**To Reproduce**
1. Run code below
2. Debugger stuck on paused

```dart
import 'dart:isolate';

Future<void> main() async {
  final result = await Isolate.run(_compute);
  print('Result: $result');
}

Future<String> _compute() async {
  final String str = 'Hello';
  print(str);
  await Future<void>.delayed(Duration(seconds: 1));
  return str;
}
```

**Expected behavior**
Program should exit after 1s

**Screenshots**

https://user-images.githubusercontent.com/1574722/215339215-5ec015b9-ed33-466e-b90a-cf33a87a7ef3.mp4

**Please complete the following information:**
 - Operating System and version: Windows 11 
 - VS Code version: 1.74.3
 - Dart extension version: v3.58.0
 - Dart SDK version: 2.19.0 (stable) (Mon Jan 23 11:29:09 2023 -0800) on "windows_x64"

**Comment by DanTup** [comment] 2023-01-30 12:26
As far as I can tell, we're doing the right thing here - we resume the isolate when it hits pause-in-exit. I can reproduce the same issue when running from DevTools.

I've filed https://github.com/dart-lang/sdk/issues/51164 for some insight from the VM team.

**Comment by DanTup** [comment] 2023-02-01 10:00
This has been fixed in the SDK. As a workaround in the short-term, you can disable use of the new SDK DAPs (falling back to the legacy DAPs which don't pause-on-exit, but have some other races with logging as a result) with the following setting in your VS Code User Settings JSON:

```js
// Disable new SDK DAPs - https://github.com/Dart-Code/Dart-Code/issues/4368
"dart.previewSdkDaps": false,
```

Once the next (non-hotfix) versions of the SDK ship (which may be a little while, since stable versions just shipped) you'll be able to remove this and things should continue to work as expected.

**Closed by DanTup** 2023-02-01 10:00 UTC
Labels: is bug, in debugger
