### ISSUE TITLE
Need to reboot cell before using "Start Debugging"

### ISSUE THREAD

**Issue by mpoirier101** [Dart-Code/Dart-Code#3437] opened 2021-06-28 15:27 UTC
Hello !

VSCode GitHub issues support ( https://github.com/microsoft/vscode/issues/125660 ) are sending me your way I suppose...

`This issue is caused by an extension, please file it with the repository (or contact) the extension has linked in its overview in VS Code or the marketplace for VS Code. See also our issue reporting guidelines.
`
I disabled ALL extensions except Flutter and Dart and same result...

Version: 1.57.1 (user setup)
Commit: 507ce72a4466fbb27b715c3722558bb15afa9f48
Date: 2021-06-17T13:28:07.755Z
Electron: 12.0.7
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 10.0.19042

I am debugging Flutter Android app on 2 different cellphones with same result.

If I select "Stop Debugging", I cannot use "Start Debugging" again. I get this error message:

Built build\app\outputs\flutter-apk\app-debug.apk.
**_Error connecting to the service protocol: failed to connect to http://127.0.0.1:52727/GHBDsITxCfo=/_**
Exited (sigterm)
I need to reboot the cells before I can use "Start Debugging" again...

Steps to Reproduce:

Start Debugging.
Stop Debugging.
Start Debugging.

Any help greatly apreciated !

**Comment by DanTup** [comment] 2021-06-28 15:48
I don't seem to be able to reproduce this, could you confirm the exact versions of:

- VS Code
- Flutter SDK
- Dart extension for VS Code
- The type of device you're using (emulator vs physical)

Can you also check whether this happens in a brand new project created with the **Flutter: New Application Project** command?

If so, could you try capturing logs:

- Run the **Dart: Capture Debugging Logs** command
- Run the app for the first time (which should work)
- Stop debugging
- Run the app for a second time (should not work)
- Click **Cancel** on the logging notification to stop logging and open the log file

The log file might be quite large, you can past it into a [gist](https://gist.github.com/) and paste the link here, or email to me at logs@dartcode.org. Remove anything sensitive first (though if you're repro'd using a clean new app, there shouldn't be much beyond file paths/device names).

Thanks!

**Comment by mpoirier101** [comment] 2021-06-28 16:54
Thanks for reply !

This issue seems to have begun after updating to Flutter 2.##... Previous developped 3 other Flutter apps for many months without problem...

Here's the requested info:

VS Code
```
Version: 1.57.1 (user setup)
Commit: 507ce72a4466fbb27b715c3722558bb15afa9f48
Date: 2021-06-17T13:28:07.755Z
Electron: 12.0.7
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 10.0.19042
```

Flutter SDK
```
D:\DEV\test>flutter doctor -v

[√] Flutter (Channel stable, 2.2.2, on Microsoft Windows [Version 10.0.19042.1052], locale en-US)
    • Flutter version 2.2.2 at C:\Apps\flutter
    • Framework revision d79295af24 (2 weeks ago), 2021-06-11 08:56:01 -0700
    • Engine revision 91c9fc8fe0
    • Dart version 2.13.3

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\Michel\AppData\Local\Android\sdk
    • Platform android-30, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = C:\Program Files\Android\Android Studio
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[√] VS Code (version 1.57.1)
    • VS Code at C:\Users\Michel\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.0.2

[√] Connected device (3 available)
    • SM J120W (mobile) • 420040159a4d539b • android-arm    • Android 6.0.1 (API 23)
    • Chrome (web)      • chrome           • web-javascript • Google Chrome 91.0.4472.114
    • Edge (web)        • edge             • web-javascript • Microsoft Edge 91.0.864.54

• No issues found!
```

Dart extension for VS Code
```
D:\DEV\test>dart --version
Dart SDK version: 2.13.3 (stable) (Wed Jun 9 12:44:44 2021 +0200) on "windows_x64"
```

The type of device you're using (emulator vs physical)
```
C:\Program Files (x86)\Android\android-sdk\platform-tools>adb devices -l
List of devices attached
420040159a4d539b       device product:j1xltevl model:SM_J120W device:j1xltecan transport_id:4

Samsung physical device model SM_J120W, Android v6.0.1
```

Captured Log:

[Dart-Code-Log-2021-05-01 12-47-47.txt](https://github.com/Dart-Code/Dart-Code/files/6728014/Dart-Code-Log-2021-05-01.12-47-47.txt)

**Comment by DanTup** [comment] 2021-07-07 11:59
I'm very suspicious about this in the logs... For the first run:

```
[12:48:26 PM] [FlutterRun] [Info] [Flutter] <== [        ] Waiting for observatory port to be available...
[12:48:28 PM] [FlutterRun] [Info] [Flutter] <== [+2115 ms] Observatory URL on device: http://127.0.0.1:45005/GAJxF3KpkdY=/
```

and the second run:

```
[12:49:42 PM] [FlutterRun] [Info] [Flutter] <== [        ] Waiting for observatory port to be available...
[12:49:43 PM] [FlutterRun] [Info] [Flutter] <== [+1216 ms] Observatory URL on device: http://127.0.0.1:45005/GAJxF3KpkdY=/
```

It seems to me like when Flutter is scraping the device logs to find the Observatory URI, it might be picking up the old run of the app and trying to connect to that rather than the latest one. Can you reproduce the same issue from the terminal, or does it only occur from VS Code?

https://github.com/flutter/flutter/issues/85559 might be the same issue.

**Comment by mpoirier101** [comment] 2021-07-07 17:05
Never used the terminal for this...
It works !! But won't stop on breakpoints... Can this be fixed ?
Or can I fix VSCode to run correctly ?
Thanks !

D:\DEV\MedicLite>flutter run
Launching lib\main.dart on SM J120W in debug mode...
...
Running Gradle task 'assembleDebug'...
Running Gradle task 'assembleDebug'... Done                        48.2s
√  Built build\app\outputs\flutter-apk\app-debug.apk.
Installing build\app\outputs\flutter-apk\app.apk...                94.7s
Syncing files to device SM J120W...                                175ms

Flutter run key commands.
r Hot reload.
R Hot restart.
h Repeat this help message.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).

 Running with sound null safety

An Observatory debugger and profiler on SM J120W is available at:
http://127.0.0.1:62342/p1h8_ze2Pec=/
I/art     (18744): Rejecting re-init on previously-failed class
java.lang.Class<androidx.core.app.JobIntentService$JobServiceEngineImpl>
I/art     (18744): Rejecting re-init on previously-failed class
java.lang.Class<androidx.core.app.JobIntentService$JobServiceEngineImpl>
I/FlutterBackgroundExecutor(18744): Starting AlarmService...
D/libEGL  (18744): eglInitialize EGLDisplay = 0xbebb6fa4
I/AndroidAlarmManagerPlugin(18744): onAttachedToEngine
I/flutter (18744): initialize test = true
I/AlarmService(18744): AlarmService started!
I/flutter (18744): initState
I/flutter (18744): loadData
I/flutter (18744): loadData done
The Flutter DevTools debugger and profiler on SM J120W is available at:
http://127.0.0.1:9101?uri=http%3A%2F%2F127.0.0.1%3A62342%2Fp1h8_ze2Pec%3D%2F


*Michel Poirier*
Développeur WEB/Mobile
Sainte-Agathe-des-Monts, QC
[image: LinkedIn]
<http://ca.linkedin.com/in/michelpoirier101>

**Comment by DanTup** [comment] 2021-07-07 17:44
Thanks for confirming - I did expect the same thing to happen at the terminal, but it's good to confirm (this means it's not something the VS Code extension is doing - though that also unfortunately means it's not something I can fix here).

I think https://github.com/flutter/flutter/issues/85559 is tracking the same issue (and is the right place for it) so I'll close this one as a dupe of that. I'm subscribed to that issue, so I'll keep an eye on the replies to try and help track it down.

One thing that might be worth posting on that issue is the exact device you're using (and OS version), in case it's the device that's behaving badly rather than Flutter (I recall there have been some issues where `logcat` worked differently on some devices). Thanks!

**Closed** 2021-07-07 17:44 UTC
Labels: upstream in dart / flutter

**Comment by mpoirier101** [comment] 2021-07-07 17:54
Like I mentionned before, I previously developed several apps on 2 similar devices for almost a year without any problem.
Now, all of them have same issue...

Main device: Samsung Galaxy J16, Android 6.0.1
D:\DEV\MedicLite>adb devices -l    
List of devices attached
420040159a4d539b       device product:j1xltevl model:SM_J120W device:j1xltecan transport_id:2

**Comment by DanTup** [comment] 2021-07-07 17:58
I can't explain why that is (at least, without having tracked down the issue 🙂). I suspect it may be related to a change in Flutter if it started happening recently (perhaps after upgrading Flutter?). That doesn't neccessarily mean it's Flutter's fault, but if it was caused by a change there then it seems likely it can be fixed there. I would post any useful information in the thread linked above to try and help track it down.
