### ISSUE TITLE
Inferred type generic function literals with 2 or more type parameters from imported files break syntax parsing

### ISSUE THREAD

**Issue by krooq** [Dart-Code/Dart-Code#1879] opened 2019-07-18 23:19 UTC
The following will pass static analysis, compile and run however dart code will not understand anything in the `usage.dart` file.
```
// func.dart
final f = <A,B>(A a) => (B b) => a;
```
```
// usage.dart
import 'func.dart';
int a = 1;
String b = "string";
final result= f<int,String>(a)(b);
main(){
    print(result); // prints "1"
}
```

Strangely if the function `f` is in the same file as the usage or even if the `part` and `part of` directives are used instead of import then `usage.dart` is parsed fine.
Also if the file is declared in a top level library file e.g. `library func` for example, then this library can be imported and used without issue.
Function literals with single type parameters seem to be imported fine.
```
//importing and using causes no issue
final f = <A>(A a) => (String b) => a;
```
Providing an explicit type signature to the function literal avoids the issue too.
```
//importing and using causes no issue
final A Function(B) Function(A) f = <A,B>(A a) => (B b) => a;
```

Difficult to place this bug, similar behavior was observed in Android Studio.

Using: 
Dart 2.4.0
Dart Code 3.2.1

**Comment by DanTup** [comment] 2019-07-19 06:22
This is likely a server issue, since that's where the parsing is done (it makes sense it also happens in Android Studio since we use the same server). It should be raised at https://github.com/dart-lang/sdk. Please post back a link once you've raised it there in case anyone else finds this issue looking for answers. Thanks!

**Comment by DanTup** [comment] 2019-07-19 06:24
That said, I just re-read it and I'm not sure I understand exactly what this bit means:

> dart code will not understand anything in the `usage.dart` file

What is the behaviour you see? What doesn't work?

**Comment by krooq** [comment] 2019-07-19 09:26
Thanks for your prompt reply.

I have updated my submission to be more explicit.
N.B. 
I need to add a type parameter when calling the generic function or else dart cant infer the type even for a function with a single generic type parameter 
i.e.. the following simpler function would not work without giving a parameter for `a` even though what was passed in was of type `int` and was statically assigned.
`final g = <A>(A a) => (String b) => a;`


The behavior is observe is what I would imagine would happen if the analysis server has stopped.  
No more syntactic errors are reported, but existing ones remain. 
The syntax highlighting appears to still be running but can get a bit messed up (not 100% on this one).

It seems like maybe the routine running type inference gets hits a loop when attempting to infer the `f`.
Ahhhh and the console does give an error.
```
 ERR Tree element not found: [object Object]: Error: Tree element not found: [object Object]
    at s.getElementLocation (file:///C:/dev/tools/Microsoft_VS_Code/resources/app/out/vs/workbench/workbench.main.js:96:851)
    at s.isCollapsed (file:///C:/dev/tools/Microsoft_VS_Code/resources/app/out/vs/workbench/workbench.main.js:96:191)
    at q.isCollapsed (file:///C:/dev/tools/Microsoft_VS_Code/resources/app/out/vs/workbench/workbench.main.js:953:992)
    at W.revealMarkersForCurrentActiveEditor (file:///C:/dev/tools/Microsoft_VS_Code/resources/app/out/vs/workbench/workbench.main.js:5410:345)
    at W.autoReveal (file:///C:/dev/tools/Microsoft_VS_Code/resources/app/out/vs/workbench/workbench.main.js:5410:202)
    at W.onActiveEditorChanged (file:///C:/dev/tools/Microsoft_VS_Code/resources/app/out/vs/workbench/workbench.main.js:5407:531)
    at W._register.e (file:///C:/dev/tools/Microsoft_VS_Code/resources/app/out/vs/workbench/workbench.main.js:5406:572)
    at d.fire (file:///C:/dev/tools/Microsoft_VS_Code/resources/app/out/vs/workbench/workbench.main.js:79:780)
    at setTimeout (file:///C:/dev/tools/Microsoft_VS_Code/resources/app/out/vs/workbench/workbench.main.js:76:344)
```

**Comment by krooq** [comment] 2019-07-19 10:12
Also posted here: https://github.com/dart-lang/sdk/issues/37578

**Comment by DanTup** [comment] 2019-07-23 08:36
Thanks, this looks entirely like an SDK issue (and the SDK issue has a repro attached now) so I'll close this as an upstream issue.

As for this bit:

> ERR Tree element not found: [object Object]:

This is a VS Code bug that I see periodically but haven't been able to track down (see https://github.com/microsoft/vscode/issues/71126). If you can repliably reproduce it, please file a VS Code bug with steps, and ping me the link :-)

**Closed** 2019-07-23 08:37 UTC
Labels: upstream in dart / flutter
