### ISSUE TITLE
Terminating debug session don't goes off on restart

### ISSUE THREAD

**Issue by yahu1031** [Dart-Code/Dart-Code#3358] opened 2021-05-23 07:57 UTC
**Describe the bug**

When I debug the code and restart the program, Terminating debug session is not going off from bottom right corner.

**To Reproduce**
1. Use any sample code in dart and run once and restart again
Eg: 
```dart
import 'dart:developer' as console;
import 'package:shelf/shelf.dart' show Request, Response;

import 'package:shelf/shelf_io.dart' as shelf_io;
import 'package:shelf_router/shelf_router.dart' show Router;

Future<void> main() async {
  /// Router object
  Router app = Router();

  app.get('/', (Request request) {
    return Response.ok(
      'Hey there 👋🏻',
      headers: {'Content-Type': 'text/plain'},
    );
  });

  /// Serving
  await shelf_io.serve(app, 'localhost', 1031).then((value) => console
      .log('API running at http://${value.address}:${value.port} 🔥🔥🔥'));
}

```

**Expected behavior**
It must not show that `Terminating debug session....` notification

**Screenshots**
![image](https://user-images.githubusercontent.com/35523357/119252352-5d1e0080-bbc9-11eb-95d1-951ccd45eeb5.png)

**Versions (please complete the following information):**
 - VS Code version: 1.56.2
 - Gitpod code version: 1.55.1
 - Dart extension version: v3.22.0
 - Dart SDK version: 2.13.0 (stable)
 - Flutter SDK version: 2.2.0 (stable)

**Comment by DanTup** [comment] 2021-05-24 09:23
I'm not able to reproduce this - are you able to capture a log file using this sample?

- Run the **Dart: Capture Debugging Logs** command
- Run the script
- Click the Stop button to try to terminate the debug session
- Wait for at least 10-15 seconds to ensure it's not just slow
- Click **Cancel** on the logging notification to stop logging and open the log file

Thanks!

**Comment by yahu1031** [comment] 2021-05-24 09:44
@DanTup Here is the log file - [dart.log](https://github.com/Dart-Code/Dart-Code/files/6531379/dart.log)

**Comment by DanTup** [comment] 2021-05-24 10:34
Thanks! I was able to reproduce this from the log - I'd misread the original report. It'll be fixed in the next release.

**Closed by DanTup** 2021-05-24 10:34 UTC
Labels: awaiting info, is bug
