### ISSUE TITLE
Missing contextual information when hovering over extension type declarations

### ISSUE THREAD

**Issue by incendial** [Dart-Code/Dart-Code#5005] opened 2024-02-24 07:57 UTC
Consider the following example:

```dart
extension type ET(Future<void> value) implements Future<void> {}

class SomeClass implements String {
  const SomeClass();
}

enum SomeEnum { first }
```

both enum and class have contextual info when hovering over their name (e.g. that it's a class and implements String):
<img width="291" alt="Screenshot 2024-02-24 at 11 55 06" src="https://github.com/Dart-Code/Dart-Code/assets/21116742/0c62384f-1ea2-4569-b528-afde4bc40003">

for extension types this tooltip has only the name:
<img width="294" alt="Screenshot 2024-02-24 at 11 55 36" src="https://github.com/Dart-Code/Dart-Code/assets/21116742/3da6f0e7-611a-402c-8586-fcb191f696d3">

**Please complete the following information:**

Dart Code extension: 3.82.0

App: Visual Studio Code
App Host: desktop
Version: mac 1.86.2

Workspace type: Dart (LSP)

Dart (3.3.0): /Users/incendial/Desktop/flutter/bin/cache/dart-sdk
Flutter (3.19.1): /Users/incendial/Desktop/flutter (No device)

**Comment by incendial** [comment] 2024-02-24 08:00
Also noticed that for cmd + hover extension types have a bit confusing constructor (without the extension type name)
<img width="215" alt="Screenshot 2024-02-24 at 11 58 07" src="https://github.com/Dart-Code/Dart-Code/assets/21116742/9ba76060-c7e1-4b22-9805-f28ca27dbb4a">

It gets a bit worse for named constructors 
<img width="278" alt="Screenshot 2024-02-24 at 11 59 31" src="https://github.com/Dart-Code/Dart-Code/assets/21116742/c34d2568-2e04-4b9a-b552-95ebdc8e9963">

When classes, for example, have the name
<img width="231" alt="Screenshot 2024-02-24 at 11 59 47" src="https://github.com/Dart-Code/Dart-Code/assets/21116742/2e550bd4-44dc-423f-bee8-760e823cc35f">

Is it by design or you'd want this to be fixed?

**Comment by incendial** [comment] 2024-02-24 08:00
The example above is not for declaration, but for instantiation:

```dart
void fn() {
  ET.named();
  SomeClass();
}
```

**Comment by DanTup** [comment] 2024-02-28 12:51
Fixed by https://github.com/dart-lang/sdk/commit/8a62f4ac1ae2d63017c4ebf8436000f99205f6df, but ships in an SDK release.

**Comment by DanTup** [comment] 2024-02-28 12:51
Oops, I missed some of the extra things noted above, I need to check if the fix covered them too.

**Comment by DanTup** [comment] 2024-02-28 13:27
@incendial do you have a complete code sample to trigger the bad preview on the named constructor of an extension type?

I can reproduce the issue for unnamed constructors:

![image](https://github.com/Dart-Code/Dart-Code/assets/1078012/8de5678b-fde8-435b-8991-f8d1146185ad)

And I understand the cause of this (which seems specific to the default constructor), however I can't reproduce for named constructors:

![image](https://github.com/Dart-Code/Dart-Code/assets/1078012/b0c390e6-6e36-4f17-964e-f49b5b232602)

**Comment by incendial** [comment] 2024-02-28 13:29
```dart
extension type ET.named(Future<void> value) implements Future<void> {}

void fn() {
  ET.named();
}
```

<img width="291" alt="Screenshot 2024-02-28 at 17 29 42" src="https://github.com/Dart-Code/Dart-Code/assets/21116742/58e49ce3-9dc8-4267-bce4-466b536ecb8d">

**Comment by DanTup** [comment] 2024-02-28 13:30
Perfect - thanks! I didn't realise we could put the name there like that 😄

**Comment by DanTup** [comment] 2024-02-28 13:50
With my fix, that shows up too:

![image](https://github.com/Dart-Code/Dart-Code/assets/1078012/03fc099e-da4c-4d99-a60d-67424aad0da3)

The issue is basically the "primary constructor" of an extension type, which has a small "codeRange". My change expands this to be the whole declaration (so it works the same as for an implied unnamed constructor on a class).

**Comment by DanTup** [comment] 2024-04-18 14:25
Fixe dby https://github.com/dart-lang/sdk/commit/c22f054a40e01a5ef4ffc2272d449c6010ffbbed. The change is in the Dart SDK so will ship in a future SDK release (rather than a Dart-Code release).

**Closed by DanTup** 2024-04-18 14:25 UTC
Labels: is bug, in editor, in lsp/analysis server, relies on sdk changes
