### ISSUE TITLE
Getting T Code: -32602

### ISSUE THREAD

**Issue by jascodes** [Dart-Code/Dart-Code#2671] opened 2020-07-25 17:01 UTC
Hey @DanTup 
Getting `Request completionItem/resolve failed. Message: No such element: T Code: -32602`. And when this happens focus is stolen to output window. 

Does this issue sound familiar?

@jascodes

**Comment by DanTup** [comment] 2020-07-27 10:05
It seems a bit like https://github.com/dart-lang/sdk/issues/41841. What version of Dart/Flutter SDK do you have? Do you have code to reproduce it? Thanks!

**Comment by jascodes** [comment] 2020-07-27 14:06
Another thing is I loose ability to import anything. Moving back to dart version 3.11.0 fixed it by kept flutter v3.12.3.

Its seems to trigger anytime do a typo and there are there are less number of intellisense fields.

Flutter sdk - 1.17.5 Dart 2.8.4
OS- Catlina 10.15.6 

Let me know if you wish me to probe something specific.

Thx

**Comment by jascodes** [comment] 2020-07-27 14:08
Now I just got a new error
```
[Error - 7:37:46 PM] Request textDocument/codeAction failed.
  Message: An error occurred while handling textDocument/codeAction request
  Code: -32001 
[Error - 7:37:46 PM] An error occurred while handling textDocument/codeAction request: NoSuchMethodError: The method 'getLocation' was called on null.
Receiver: null
Tried calling: getLocation(0)
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
#1      toRange (package:analysis_server/src/lsp/mapping.dart:884:45)
#2      toTextEdit (package:analysis_server/src/lsp/mapping.dart:971:5)
#3      toTextDocumentEdit.<anonymous closure> (package:analysis_server/src/lsp/mapping.dart:965:27)
#4      MappedListIterable.elementAt (dart:_internal/iterable.dart:417:31)
#5      ListIterable.toList (dart:_internal/iterable.dart:221:19)
#6      toTextDocumentEdit (package:analysis_server/src/lsp/mapping.dart:965:57)
#7      MappedListIterable.elementAt (dart:_internal/iterable.dart:417:31)
#8      ListIterable.toList (dart:_internal/iterable.dart:221:19)
#9      toWorkspaceEdit (package:analysis_server/src/lsp/mapping.dart:990:41)
#10     createWorkspaceEdit (package:analysis_server/src/lsp/mapping.dart:83:10)
#11     CodeActionHandler._createFixAction (package:analysis_server/src/lsp/handlers/handler_code_actions.dart:119:7)
#12     CodeActionHandler._getFixActions.<anonymous closure> (package:analysis_server/src/lsp/handlers/handler_code_actions.dart:214:34)
#13     MappedListIterable.elementAt (dart:_internal/iterable.dart:417:31)
#14     ListIterator.moveNext (dart:_internal/iterable.dart:346:26)
#15     List.addAll (dart:core-patch/growable_array.dart:195:13)
#16     CodeActionHandler._getFixActions (package:analysis_server/src/lsp/handlers/handler_code_actions.dart:213:25)
<asynchronous suspension>
#17     CodeActionHandler._getCodeActions (package:analysis_server/src/lsp/handlers/handler_code_actions.dart:172:7)
#18     CodeActionHandler.handle.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:analysis_server/src/lsp/handlers/handler_code_actions.dart:67:18)
#19     ErrorOr.mapResult (package:analysis_server/lsp_protocol/protocol_special.dart:220:12)
#20     CodeActionHandler.handle.<anonymous closure>.<anonymous closure> (package:analysis_server/src/lsp/handlers/handler_code_actions.dart:64:26)
#21     ErrorOr.mapResult (package:analysis_server/lsp_protocol/protocol_special.dart:220:12)
#22     CodeActionHandler.handle.<anonymous closure> (package:analysis_server/src/lsp/handlers/handler_code_actions.dart:63:26)
#23     ErrorOr.mapResult (package:analysis_server/lsp_protocol/protocol_special.dart:220:12)
#24     CodeActionHandler.handle (package:analysis_server/src/lsp/handlers/handler_code_actions.dart:60:17)
#25     _rootRunUnary (dart:async/zone.dart:1192:38)
#26     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#27     _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#28     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#29     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#30     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#31     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:36:15)
#32     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:298:13)
#33     Handler.requireResolvedUnit (package:analysis_server/src/lsp/handlers/handlers.dart)
#34     _rootRunUnary (dart:async/zone.dart:1192:38)
#35     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#36     _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#37     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#38     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#39     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#40     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:556:7)
#41     _rootRun (dart:async/zone.dart:1184:13)
#42     _CustomZone.run (dart:async/zone.dart:1077:19)
#43     _CustomZone.runGuarded (dart:async/zone.dart:979:7)
#44     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1019:23)
#45     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#46     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#47     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#48     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)

[Error - 7:37:47 PM] Request textDocument/codeAction failed.
  Message: An error occurred while handling textDocument/codeAction request
  Code: -32001 
[Error - 7:37:47 PM] An error occurred while handling textDocument/codeAction request: NoSuchMethodError: The method 'getLocation' was called on null.
Receiver: null
Tried calling: getLocation(0)
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
#1      toRange (package:analysis_server/src/lsp/mapping.dart:884:45)
#2      toTextEdit (package:analysis_server/src/lsp/mapping.dart:971:5)
#3      toTextDocumentEdit.<anonymous closure> (package:analysis_server/src/lsp/mapping.dart:965:27)
#4      MappedListIterable.elementAt (dart:_internal/iterable.dart:417:31)
#5      ListIterable.toList (dart:_internal/iterable.dart:221:19)
#6      toTextDocumentEdit (package:analysis_server/src/lsp/mapping.dart:965:57)
#7      MappedListIterable.elementAt (dart:_internal/iterable.dart:417:31)
#8      ListIterable.toList (dart:_internal/iterable.dart:221:19)
#9      toWorkspaceEdit (package:analysis_server/src/lsp/mapping.dart:990:41)
#10     createWorkspaceEdit (package:analysis_server/src/lsp/mapping.dart:83:10)
#11     CodeActionHandler._createFixAction (package:analysis_server/src/lsp/handlers/handler_code_actions.dart:119:7)
#12     CodeActionHandler._getFixActions.<anonymous closure> (package:analysis_server/src/lsp/handlers/handler_code_actions.dart:214:34)
#13     MappedListIterable.elementAt (dart:_internal/iterable.dart:417:31)
#14     ListIterator.moveNext (dart:_internal/iterable.dart:346:26)
#15     List.addAll (dart:core-patch/growable_array.dart:195:13)
#16     CodeActionHandler._getFixActions (package:analysis_server/src/lsp/handlers/handler_code_actions.dart:213:25)
<asynchronous suspension>
#17     CodeActionHandler._getCodeActions (package:analysis_server/src/lsp/handlers/handler_code_actions.dart:172:7)
#18     CodeActionHandler.handle.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:analysis_server/src/lsp/handlers/handler_code_actions.dart:67:18)
#19     ErrorOr.mapResult (package:analysis_server/lsp_protocol/protocol_special.dart:220:12)
#20     CodeActionHandler.handle.<anonymous closure>.<anonymous closure> (package:analysis_server/src/lsp/handlers/handler_code_actions.dart:64:26)
#21     ErrorOr.mapResult (package:analysis_server/lsp_protocol/protocol_special.dart:220:12)
#22     CodeActionHandler.handle.<anonymous closure> (package:analysis_server/src/lsp/handlers/handler_code_actions.dart:63:26)
#23     ErrorOr.mapResult (package:analysis_server/lsp_protocol/protocol_special.dart:220:12)
#24     CodeActionHandler.handle (package:analysis_server/src/lsp/handlers/handler_code_actions.dart:60:17)
#25     _rootRunUnary (dart:async/zone.dart:1192:38)
#26     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#27     _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#28     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#29     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#30     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#31     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:36:15)
#32     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:298:13)
#33     Handler.requireResolvedUnit (package:analysis_server/src/lsp/handlers/handlers.dart)
#34     _rootRunUnary (dart:async/zone.dart:1192:38)
#35     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#36     _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#37     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#38     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#39     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#40     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:556:7)
#41     _rootRun (dart:async/zone.dart:1184:13)
#42     _CustomZone.run (dart:async/zone.dart:1077:19)
#43     _CustomZone.runGuarded (dart:async/zone.dart:979:7)
#44     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1019:23)
#45     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#46     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#47     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#48     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)

[Error - 7:38:04 PM] Request textDocument/codeAction failed.
  Message: An error occurred while handling textDocument/codeAction request
  Code: -32001 
[Error - 7:38:04 PM] An error occurred while handling textDocument/codeAction request: NoSuchMethodError: The method 'getLocation' was called on null.
Receiver: null
Tried calling: getLocation(0)
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
#1      toRange (package:analysis_server/src/lsp/mapping.dart:884:45)
#2      toTextEdit (package:analysis_server/src/lsp/mapping.dart:971:5)
#3      toTextDocumentEdit.<anonymous closure> (package:analysis_server/src/lsp/mapping.dart:965:27)
#4      MappedListIterable.elementAt (dart:_internal/iterable.dart:417:31)
#5      ListIterable.toList (dart:_internal/iterable.dart:221:19)
#6      toTextDocumentEdit (package:analysis_server/src/lsp/mapping.dart:965:57)
#7      MappedListIterable.elementAt (dart:_internal/iterable.dart:417:31)
#8      ListIterable.toList (dart:_internal/iterable.dart:221:19)
#9      toWorkspaceEdit (package:analysis_server/src/lsp/mapping.dart:990:41)
#10     createWorkspaceEdit (package:analysis_server/src/lsp/mapping.dart:83:10)
#11     CodeActionHandler._createFixAction (package:analysis_server/src/lsp/handlers/handler_code_actions.dart:119:7)
#12     CodeActionHandler._getFixActions.<anonymous closure> (package:analysis_server/src/lsp/handlers/handler_code_actions.dart:214:34)
#13     MappedListIterable.elementAt (dart:_internal/iterable.dart:417:31)
#14     ListIterator.moveNext (dart:_internal/iterable.dart:346:26)
#15     List.addAll (dart:core-patch/growable_array.dart:195:13)
#16     CodeActionHandler._getFixActions (package:analysis_server/src/lsp/handlers/handler_code_actions.dart:213:25)
<asynchronous suspension>
#17     CodeActionHandler._getCodeActions (package:analysis_server/src/lsp/handlers/handler_code_actions.dart:172:7)
#18     CodeActionHandler.handle.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:analysis_server/src/lsp/handlers/handler_code_actions.dart:67:18)
#19     ErrorOr.mapResult (package:analysis_server/lsp_protocol/protocol_special.dart:220:12)
#20     CodeActionHandler.handle.<anonymous closure>.<anonymous closure> (package:analysis_server/src/lsp/handlers/handler_code_actions.dart:64:26)
#21     ErrorOr.mapResult (package:analysis_server/lsp_protocol/protocol_special.dart:220:12)
#22     CodeActionHandler.handle.<anonymous closure> (package:analysis_server/src/lsp/handlers/handler_code_actions.dart:63:26)
#23     ErrorOr.mapResult (package:analysis_server/lsp_protocol/protocol_special.dart:220:12)
#24     CodeActionHandler.handle (package:analysis_server/src/lsp/handlers/handler_code_actions.dart:60:17)
#25     _rootRunUnary (dart:async/zone.dart:1192:38)
#26     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#27     _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#28     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#29     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#30     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#31     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:36:15)
#32     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:298:13)
#33     Handler.requireResolvedUnit (package:analysis_server/src/lsp/handlers/handlers.dart)
#34     _rootRunUnary (dart:async/zone.dart:1192:38)
#35     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#36     _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#37     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#38     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#39     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#40     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:556:7)
#41     _rootRun (dart:async/zone.dart:1184:13)
#42     _CustomZone.run (dart:async/zone.dart:1077:19)
#43     _CustomZone.runGuarded (dart:async/zone.dart:979:7)
#44     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1019:23)
#45     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#46     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#47     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#48     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)

```

**Comment by jascodes** [comment] 2020-07-28 20:54
The last error never reoccurred, so lets focus on the main issue.. do you need more info?

**Comment by DanTup** [comment] 2020-07-29 08:53
Sorry for the delay. I think the first issue is the one I linked - the fix isn't available in the version of Flutter you had, however it is available on the Flutter beta channel if you want to temporarily switch to that to test it.

```
flutter channel beta && flutter upgrade
```

The other issue is stranger - it seems like we tried to generate an edit for a file we had no line info for. If you're able to reproduce that, please do file a separate issue about it (in the [sdk repo](https://github.com/dart-lang/sdk), and feel free to cc me).

If you're still able to repro the original issue on Flutter's beta channel, please provide some code and location where you're invoking completion to trigger it. Thanks!

**Comment by jascodes** [comment] 2020-07-29 09:19
@DanTup No problem at all, and thanks for coming back, it will be hard to reproduce second one, but I see if again, I will let you know. I actually using FVM and use multiple version flutter and will test it out on beta version. Though I will stay at older version of dartcode and just wait for hotfix on stable branch as I only use stable branch of flutter for production project.

Thx

**Comment by DanTup** [comment] 2020-07-29 09:29
I'm not familiar with FVM, but you might also be interested to know you can switch between SDK versions from the status bar in VS Code (see https://dartcode.org/docs/quickly-switching-between-sdk-versions/). You'll need multiple Flutter checkouts (or git worktrees) though.

FWIW based on [this comment](https://github.com/flutter/flutter/issues/55552#issuecomment-665349036) it seems like the current beta branch will be the next stable version (perhaps with some cherry-picks).

**Comment by jascodes** [comment] 2020-07-29 09:53
@DanTup Thats awesome and very useful info. There might be integration opportunity here. Check out repo
https://github.com/leoafarias/fvm

With FVM you download, browse manage multiple versions of flutter. You can freeze version in side repo and that info in .fvm folder is also committed to repo. Your extension can look for the file. Another think is I can proxy fvm version of Flutter by using `fvm flutter` on cli. Because of that I will be sticking to FVM. In fact this is plan to make drop fvm and directly use flutter which will allow FVM to be usable with something like go-flutter.

**Comment by DanTup** [comment] 2020-07-29 10:08
This extension already persists the SDK you select from the status bar (into the workspace settings - so it can handle multi-root workspaces too).

Proxying the flutter script won't currently work very well with VS Code, as VS Code will always use the real flutter script from the real SDK (bypassing the proxied script). I would like to have VS Code also update the `PATH` in the terminal so when you switch here it will also apply to the embedded terminal, however that's currently hold due to to [this issue](https://github.com/microsoft/vscode/issues/99878).

**Comment by DanTup** [comment] 2020-07-29 10:10
Actually, it looks like FVM is already designed to work well with the feature above:

https://github.com/leoafarias/fvm#vscode

It suggests setting `dart.flutterSdkPaths` which is what enables the feature I mentioned above :-)

**Comment by jascodes** [comment] 2020-07-29 10:58
```
{
  "dart.flutterSdkPaths": ["/Users/usr/fvm/versions"]
}
```
Oh yeah, this can be done. But I am doing the dynamic linking like below.
```
{
  "dart.flutterSdkPaths": [".fvm/flutter_sdk"]
}
```
So in .fvm/ there is symlink folder `flutter_sdk` and file `fvm_config.json` which contains current active version for the folder.
When I do `fvm use beta` or something the symlink updates and point to that version. Though I need to reload my vscode for dartcode to see that change. Perhaps if use if using symlink folder in flutterSdkPaths, you can monitor the change of symlink and reload the active version in darcode.
Maybe I should open another issue for this?

**Comment by DanTup** [comment] 2020-07-29 11:16
It would be a little tricky to do that, as we resolve symlinks at the time we find the SDK. Given the extension already has a way to switch between the SDKs (which is arguably easier than doing it from the command line, it's just a click in the status bar) I'm not sure it'd make sense to do extra work to track that.

Any reason not to use the first option? If you stick to running things through VS Code, you shouldn't really need to invoke `flutter` from the command line. Though if the VS Code issue linked above gets improved, the built-in terminal would also update when you changed the SDK from the status bar fixing that anyway.

**Comment by jascodes** [comment] 2020-07-29 12:33
I need to also update .fvm folder with `fvm use ...`. Advantage is using fvm for now is that it saves version not sdk path which can be diff on other machines for other users. If the later comes true where vscode terminal will automatically be linked to selected version of statusbar, it will be certainly improvement, but fvm will soon provide this option all terminals where I don't need to proxy flutter cli via fvm. If flutter cli were to handle multiple version, and project useage of multiple versions, that will be most ideal and useful. Maybe you can bring this to their attension.

**Comment by DanTup** [comment] 2020-07-30 11:06
> Advantage is using fvm for now is that it saves version not sdk path which can be diff on other machines for other users

Yeah, that's a fair point. I've been thinking more about how we locate SDKs for some recent changes with Snap, so I'll bear these in mind if I make changes to see if we can be more compatible with tools like this.

We got a bit off-topic though - was the original issue here resolved on the beta branch, or do you think there's still an issue?

**Comment by jascodes** [comment] 2020-07-30 14:46
Yea, just got little time to test. Seems fine with beta. But current users are stuck with this issue. Don't want to rollback feature etc; which are causing issues while the beta makes into stable?

**Comment by DanTup** [comment] 2020-07-30 14:53
Unfortunately that's always the way - if bug fixes were merged to stable all the tie, stable would become less stable (both because fixes sometimes introduce other issues, and it would be more of a moving target, when stable users tend to want less frequent updates).

If you don't want to temporarily use the beta branch, you could disable the LSP preview in VS Code (that should also avoid the issue).

I'll close this as the issue is fixed and there's nothing else to do, but do let me know if you find other issues. Thanks!

**Closed by DanTup** 2020-07-30 14:53 UTC
Labels: awaiting info

**Comment by jascodes** [comment] 2020-07-30 15:03
Oh sorry I didn't realised LSP was preview feature my bad 🙂

**Comment by DanTup** [comment] 2020-07-30 15:50
Yeah, though I'd like to move over to LSP-by-default soon, so finding issues in it is very helpful! 🙂
