### ISSUE TITLE
Exception on vs code startup

### ISSUE THREAD

**Issue by Maksimka101** [Dart-Code/Dart-Code#2642] opened 2020-07-15 17:44 UTC
Happens when I launch vs code. After this error I can't run app or use code completion. 

Logs:

### Request

Server was responding to request: `analysis.setAnalysisRoots`

### Versions

- Visual Studio Code v1.47.1
- Dart Code v3.12.2
- Flutter SDK v1.17.5

### Analyzer Info

The analyzer was launched using the arguments:

- /Users/zemlyanikinmax/flutter/bin/cache/dart-sdk/bin/snapshots/analysis_server.dart.snapshot
- --client-id=VS-Code
- --client-version=3.12.2

### Exception

FormatException: Unexpected character (at character 1)
x{
^

#0      _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1394:5)
#1      _ChunkedJsonParser.parseNumber (dart:convert-patch/convert_patch.dart:1261:9)
#2      _ChunkedJsonParser.parse (dart:convert-patch/convert_patch.dart:926:22)
#3      _parseJson (dart:convert-patch/convert_patch.dart:31:10)
#4      JsonDecoder.convert (dart:convert/json.dart:505:36)
#5      JsonCodec.decode (dart:convert/json.dart:153:41)
#6      _PackageConfigJsonParser.parse (package:analyzer/src/context/package_config_json.dart:113:30)
#7      parsePackageConfigJson (package:analyzer/src/context/package_config_json.dart:13:49)
#8      parsePackageConfigJsonFile (package:analyzer/src/context/packages.dart:73:20)
#9      parsePackagesFile (package:analyzer/src/context/packages.dart:128:14)
#10     ContextManagerImpl._computeFolderDisposition (package:analysis_server/src/context_manager.dart:949:24)
#11     ContextManagerImpl._createContext (package:analysis_server/src/context_manager.dart:990:9)
#12     ContextManagerImpl._createContexts (package:analysis_server/src/context_manager.dart:1081:16)
#13     ContextManagerImpl.setRoots (package:analysis_server/src/context_manager.dart:644:9)
#14     AnalysisServer.setAnalysisRoots (package:analysis_server/src/analysis_server.dart:481:22)
#15     AnalysisDomainHandler.setAnalysisRoots (package:analysis_server/src/domain_analysis.dart:357:14)
#16     AnalysisDomainHandler.handleRequest (package:analysis_server/src/domain_analysis.dart:296:16)
#17     AnalysisServer.handleRequest.<anonymous closure>.<anonymous closure> (package:analysis_server/src/analysis_server.dart:319:40)
#18     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:256:15)
#19     AnalysisServer.handleRequest.<anonymous closure> (package:analysis_server/src/analysis_server.dart:315:50)
#20     _rootRun (dart:async/zone.dart:1184:13)
#21     _CustomZone.run (dart:async/zone.dart:1077:19)
#22     _runZoned (dart:async/zone.dart:1619:10)
#23     runZonedGuarded (dart:async/zone.dart:1608:12)
#24     AnalysisServer.handleRequest (package:analysis_server/src/analysis_server.dart:314:5)
#25     ByteStreamServerChannel._readRequest.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:171:16)
#26     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:256:15)
#27     ByteStreamServerChannel._readRequest (package:analysis_server/src/channel/byte_stream_channel.dart:161:47)
#28     ByteStreamServerChannel.listen.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:106:26)
#29     _rootRunUnary (dart:async/zone.dart:1192:38)
#30     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#31     _CustomZone.runUnaryGuarded (dart:async/zone.dart:987:7)
#32     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#33     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:266:7)
#34     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:70:11)
#35     _EventSinkWrapper.add (dart:async/stream_transformers.dart:17:11)
#36     _StringAdapterSink.add (dart:convert/string_conversion.dart:238:11)
#37     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:152:13)
#38     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:127:5)
#39     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:165:5)
#40     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:122:24)
#41     _rootRunUnary (dart:async/zone.dart:1192:38)
#42     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#43     _CustomZone.runUnaryGuarded (dart:async/zone.dart:987:7)
#44     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#45     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:266:7)
#46     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:70:11)
#47     _EventSinkWrapper.add (dart:async/stream_transformers.dart:17:11)
#48     _StringAdapterSink.add (dart:convert/string_conversion.dart:238:11)
#49     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:243:7)
#50     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:314:20)
#51     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:307:5)
#52     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:74:18)
#53     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:122:24)
#54     _rootRunUnary (dart:async/zone.dart:1192:38)
#55     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#56     _CustomZone.runUnaryGuarded (dart:async/zone.dart:987:7)
#57     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#58     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:266:7)
#59     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:779:19)
#60     _StreamController._add (dart:async/stream_controller.dart:655:7)
#61     _StreamController.add (dart:async/stream_controller.dart:597:5)
#62     _Socket._onData (dart:io-patch/socket_patch.dart:1982:41)
#63     _rootRunUnary (dart:async/zone.dart:1196:13)
#64     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#65     _CustomZone.runUnaryGuarded (dart:async/zone.dart:987:7)
#66     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#67     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:266:7)
#68     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:779:19)
#69     _StreamController._add (dart:async/stream_controller.dart:655:7)
#70     _StreamController.add (dart:async/stream_controller.dart:597:5)
#71     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1527:33)
#72     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1019:14)
#73     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#74     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#75     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#76     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)

**Comment by DanTup** [comment] 2020-07-15 17:51
Can you see if you have a file at `.dart_tool/packages.json` or similar, and attach it here? It looks like it may contain invalid json (though I'm not sure why).

**Comment by Maksimka101** [comment] 2020-07-15 18:46
You are right. My .dart_tool/packages.json starts with "x{" . I think that I change this file accidently.

**Comment by DanTup** [comment] 2020-07-15 20:49
Ok, so if you remove the `x` (or delete the file and re-run `pub get`) that should fix the issue for you. If you see it come back (and don't think you've modified the file yourself), please do re-raise it.

@bwilkerson do you think it's worth trying to handle this more gracefully? I'm not sure if the server can do much if the file is invalid, but maybe wrapping the exception in one that includes the file path would help?

**Comment by bwilkerson** [comment] 2020-07-15 21:07
> do you think it's worth trying to handle this more gracefully?

Yes, absolutely! Server exceptions should only be returned when there is an exception that server failed to handle. If nothing else we should add an error code that we can return from `analysis.setAnalysisRoots` to indicate the failure. It might be better to handle the error by analyzing the directory as if there were no packages defined. That would be noisy, but probably better than a total lack of feedback. Under LSP we could also display a dialog for the user asking them to re-run `pub`.

@scheglov In case you have other ideas.

**Comment by DanTup** [comment] 2020-07-29 12:49
I had a look at this, and it seems like here might be an appropriate place to handle this:

https://github.com/dart-lang/sdk/blob/bac90ab84f42d36aaf2b8ed7894b3b00fda723b3/pkg/analysis_server/lib/src/context_manager.dart#L873-L879

We could return a `NoPackageFolderDisposition` to make it behave as if there was no file. However, it's not clear how this could be communicated further up to where `setRoots` was handled (it's possible there's also a mix of multiple contexts where some are good and some are bad).

Any suggestions?

**Comment by bwilkerson** [comment] 2020-07-29 15:16
That looks like a fairly likely place for it, but the code looks out of date. It's checking for a `.packages` file, so I think it also needs to be updated for other reasons. I'll ping Konstantin to try to get his input on this issue.

**Comment by scheglov** [comment] 2020-07-29 16:14
We need a way to report errors on files that are nor Dart files themselves, but affect how we analyze dart files. If IntelliJ and VS Code allow us, we could just report these errors on the configuration files. If not - we need another mechanism. The only thing I know is a sever error, but not a fatal error. But it is not targeted, and might have only text. I sill don't know how IDEs will react on a server error, even not fatal.

Also related https://github.com/dart-lang/sdk/issues/40525

**Comment by DanTup** [comment] 2020-07-29 16:19
> If IntelliJ and VS Code allow us, we could just report these errors on the configuration files.

I think that would probably work in VS Code. If it's likely to work for IntelliJ, I can do some testing to confirm.

**Comment by bwilkerson** [comment] 2020-07-29 16:26
We can definitely send diagnostics for non-Dart files; we already do so for `pubspec.yaml` and `analysis_options.yaml` files, and I know that IntelliJ handles those cases.

But that doesn't answer the question of how to handle the exception in server nor the question of whether server needs to be updated to use the `package_config.json` file.

**Comment by DanTup** [comment] 2020-07-29 16:42
> But that doesn't answer the question of how to handle the exception in server

If we're able to generate a diagnostic for the json file, we may be able to just return `NoPackageFolderDisposition` in the code above (as it does if the file is missing)?

> nor the question of whether server needs to be updated to use the `package_config.json` file.

That seems to be handled inside the `parsePackagesFile` function:

https://github.com/dart-lang/sdk/blob/687bef277f33f5e2b18df52c9c3eb8019ad52c04/pkg/analyzer/lib/src/context/packages.dart#L118-L132

**Comment by bwilkerson** [comment] 2020-07-29 16:56
Yes, we could, and arguably should, return a `NoPackageFolderDisposition` if the file's content isn't valid.

But the condition in the [code you referenced](https://github.com/dart-lang/sdk/blob/bac90ab84f42d36aaf2b8ed7894b3b00fda723b3/pkg/analysis_server/lib/src/context_manager.dart#L873-L879) only compares the file name to `.packages`. That seems wrong.

**Comment by scheglov** [comment] 2020-07-29 17:10
Looks like a bug, we should not check for `.packages`, and should let `parsePackagesFile` understand what kind of file we have. But we specify `File packagesFile` which we `_findPackageSpecFile` from the context folder... And we look only for `.packages` and `pubspec.yaml` files. Ugh... It seems complicated.

**Comment by DanTup** [comment] 2020-07-29 17:20
I think right now `pub` will always write `.packages`, so if the code is finding `.packages` but then reading `._dart_tool/packages.json` in preference, it'll probably work fine up until `pub` stops writing that file?

It might be better for you to look at that than me 🙃

Should we also consider this issue a dupe of https://github.com/dart-lang/sdk/issues/40525? I don't think the current behaviour is silent as suggested in that issue, but I think the gist is the same (handle errors in the file better).

**Comment by bwilkerson** [comment] 2020-07-29 17:47
> Ugh... It seems complicated.

It is. I really hope we can get rid of `ContextManager` soon. It's hopelessly out dated and way too complex now that we don't need to preserve cached state the same way.

> Should we also consider this issue a dupe ...

I'd leave this one. #40525 is about the analyzer package's behavior, while this is about server's behavior.

**Comment by DanTup** [comment] 2020-07-30 11:00
> I'd leave this one. #40525 is about the analyzer package's behavior, while this is about server's behavior.

Ok, though it makes more sense in the SDK repo so I've filed https://github.com/dart-lang/sdk/issues/42885 and will close this one.

**Closed** 2020-07-30 11:00 UTC
