### ISSUE TITLE
A Document Being Saved by xcdevice

### ISSUE THREAD

**Issue by rgb1380** [Dart-Code/Dart-Code#2460] opened 2020-05-15 13:07 UTC
I am seeing large documents (1.6GB) being created in MacBook Air's temporary folder (in my case: /private/var/folders/xb/j4_1kvcx0x1679jq7slr5vvm0000gn/T/TemporaryItems/(A Document Being Saved By xcdevice)/dyld_shared_cache_arm64, then in another folder: (A Document Being Saved By xcdevice 2) with the same file. These type of folders continue to be created with the same file inside until the entire disk is used up. The documents seem to be created by vscode.

VSCode Version: 1.45.1
OS Version: macOS 10.15.4
Xcode Version: 11.4 (11E146)

Steps to Reproduce:

1. Open vscode
2. Load a flutter project
3. Connect an iPhone (in my case it is an iPhone 7 plus, iOS 13.1.3)
For me, this is a repeatable problem. Disconnecting the iPhone, or closing vscode stops the temporary files from being created.

**Comment by DanTup** [comment] 2020-05-18 09:41
This has come up before - I believe it's something weird going on with the Xcode/Simulator tools. There's some info here:

https://apple.stackexchange.com/questions/387634/temporary-dyld-shared-cache-taking-a-lot-of-space/387843#387843

> It was fixed after opening Xcode and going to Window/Devices and Simulators. There select your iPhone and wait for the process of "Copying cache files from device" to finish

Please let me know if this resolves the issue.

**Comment by DanTup** [comment] 2020-05-18 09:45
Closing as a dupe of https://github.com/flutter/flutter/issues/56826.

**Closed by DanTup** 2020-05-18 09:45 UTC
Labels: awaiting info

**Comment by rgb1380** [comment] 2020-05-18 11:50
Thanks. The solution worked.
