### ISSUE TITLE
Configurable suggested import order

### ISSUE THREAD

**Issue by Zekfad** [Dart-Code/Dart-Code#5033] opened 2024-03-12 18:59 UTC
**Is your feature request related to a problem? Please describe.**
In our projects we use single file to (re)export internal libraries and use linter rule prefer local import over library prefix import.
Here's the example structure:
* `models.dart` (exports `models/base_model.dart` and `models/sub_lib.dart`)
  * `models/base_model.dart` (class `BaseModel`)
  * `models/sub_lib.dart` (exports `sub_lib/sub_model.dart`
    * `models/sub_lib/sub_model.dart` (class `SubModel`)

Currently the order is as follows:
- models/sub_lib/sub_model.dart
- package:pkg/models/sub_lib/sub_model.dart
- models.dart
- package:pkg/models.dart
- models/sub_lib.dart
- package:pkg/models/sub_lib.dart

It would be great to have more controls over suggestions order.

**Describe the solution you'd like**
We'd like to have a more granular control over suggestions order.
- Respect [`prefer_relative_imports`](https://dart.dev/tools/linter-rules/prefer_relative_imports) or [`always_use_package_imports`](https://dart.dev/tools/linter-rules/always_use_package_imports) if they are defined by linter config.
- Make it possible to have a higher priority for indirect re-exports.
- With `prefer_relative_imports` utilize `/` syntax instead of `package:pkg/`.

With configured feature we'd like to see suggestions list like that:

From root folder:
- models.dart
- /models.dart
- models/sub_lib.dart
- /models/sub_lib.dart
- models/sub_lib/sub_model.dart
- /models/sub_lib/sub_model.dart

Notice slashes instead of `package:` prefix, because we have `prefer_relative_imports`.

From inner folder:
- /models.dart
- ../models.dart
- /models/sub_lib.dart
- ../models/sub_lib.dart
- /models/sub_lib/sub_model.dart
- ../models/sub_lib/sub_model.dart

Notice, that because target file is requires travelling upward package local import have higher priority.

**Comment by DanTup** [comment] 2024-03-14 16:02
Closing this as a dupe of https://github.com/Dart-Code/Dart-Code/issues/4522 as I think it's substantially the same. I agree there's probably some work to do here. I'm not sure we need the fixes to be customisable themselves, I think we should continue to take hints from the enabled lints (but perhaps remove items that would produce lint errors rather than just demoting them).

**Closed by DanTup** 2024-03-14 16:02 UTC
Labels: is enhancement
