### ISSUE TITLE
Improve visual feedback when running tests / debugging

### ISSUE THREAD

**Issue by pulyaevskiy** [Dart-Code/Dart-Code#322] opened 2017-06-16 04:57 UTC
Currently I can see how status bar turns yellow during a test run, which is nice. However

1. There is no visual indication when tests fail. Maybe turning status bar into red if debug process exited with non-0 code is something to consider? Or a bubble / popup notification of some sort?
2. It would be nice to automatically switch to "Debug console" when I start a debug session.

Wondering if Code provides APIs to perform such things? I might be able to contribute if that's the case.

**Comment by DanTup** [comment] 2017-06-16 05:46
Currently there is no support for running tests (see #87). I don't know how you're running them (I guess you added some custom stuff to launch.json?) but any feedback will have to be done as part of supported integration (otherwise Dart Code has no idea you're running tests).

That said, something I have sat in my inbox to fix today is to send the correct channels for `OutputEvents` from the debugger; which means anything from `stderr` will probably get coloured red (see https://github.com/Microsoft/vscode/issues/2665) which might be a good start. If you can tell me exactly how you're invoking the tests I'll test that today.

As for switching to the Debug console; I'm sure that normally happens for me when I start a debug session (or at least, when something writes to it). I'll do some testing of that too.

**Comment by DanTup** [comment] 2017-06-16 10:11
Actually, the first part is already done! Stuff from stderr is already red, output is white and info stuff is yellow.

The request for openign debug console automatically can be solved by setting `"internalConsoleOptions": "openOnSessionStart",` in your `launch.json`.

I'm in two minds about whether to override the default here; I think the default (of not showing it) is bad, but I don't want to start messing around with Code defaults just for one language, it might not be expected.

**Comment by DanTup** [comment] 2017-06-16 10:12
Since this case was specifically about testing; I'm going to close as a dupe of #87. However I believe with the setting mentioned above and that the errors are spat into the debug console in red, that probably this is sufficient in the meantime?

**Closed by DanTup** 2017-06-16 10:12 UTC
Labels: enhancement

**Comment by pulyaevskiy** [comment] 2017-06-16 20:54
Thanks for all the info! I'll try `internalConsoleOptions` and see how it works.
Currently, it only automatically switches for me the very first time after I opened a project.

Sorry, I should I've clarified about tests. I'm using cli launch to just run `dart test/foo_test.dart`. Works fine for tests which don't involve transformations / Pub.

I will follow updates in #87 from now on.

**Comment by DanTup** [comment] 2017-06-17 08:11
> Currently, it only automatically switches for me the very first time after I opened a project.

Yeah, I think the default isn't very good :( If you don't close it after the first run I guess it'd be fine, but if you're going back to editing that's something you're likely to do!

That said, maybe this'll change when we switch to using the terminal (#99). I really don't like the current way we handle this because if your program expects to read stdin it just hangs.
