### ISSUE TITLE
Can not Open Devtools Widget Inspector Page in the VS Code

### ISSUE THREAD

**Issue by Faamica** [Dart-Code/Dart-Code#4388] opened 2023-02-14 08:57 UTC
**Describe the bug**
Hello, I am developing with flutter using vscode.

By the way, if you select OpenDevtools (running Android Emulator)

It doesn't open a new tab inside vscode, it opens devtools in the browser.

thank you

**To Reproduce**
1. shift + command + p 
2. select "dart: opendevtools" menu 
3. select Widget Inspector Page
4. can't open it in the vscode, but "open in browser" is ok

**Expected behavior**
open widget inspector in the VS Code

**Screenshots**
<img width="332" alt="image" src="https://user-images.githubusercontent.com/87428594/218686576-eff107f3-3087-4d68-a66a-039d41884d62.png">

**Please complete the following information:**
 - Operating System and version:

<img width="594" alt="image" src="https://user-images.githubusercontent.com/87428594/218686856-1ee18851-946b-453f-a712-d518b882da54.png">

 - VS Code version: Code 1.73.1 (Universal) (https://github.com/microsoft/vscode/commit/6261075646f055b99068d3688932416f2346dd3b, 2022-11-09T02:08:38.961Z)
OS version: Darwin arm64 22.1.0
Modes:
Sandboxed: No

 - Dart extension version:
 
<img width="463" alt="image" src="https://user-images.githubusercontent.com/87428594/218687043-27b056e6-47bf-4c24-a8f9-14300260050b.png">

 - Dart/Flutter SDK version:
<img width="589" alt="image" src="https://user-images.githubusercontent.com/87428594/218687218-b5c58965-367d-464d-815f-378007a65d64.png">

 - Target device (if the issue relates to Flutter debugging):

**Comment by DanTup** [comment] 2023-02-14 10:54
I think this may be a caching issue from switching Flutter versions. I've made some changes recently that I hope might improve this - is it possible you could switch to the Pre-release version of the Dart extension and restart VS Code and see if it solves the issue?

<img src="https://user-images.githubusercontent.com/1078012/155162164-d81940cb-9576-4468-8c03-a4bc2fd599c9.png" alt="Dart/Flutter pre-release versions" width="570" height="330" />

(note: there isn't currently a Flutter pre-release, this is just a shared screenshot I had handy.. it's just the Dart one you should switch).

Please let me know if that doesn't help. Thanks!

**Comment by Faamica** [comment] 2023-02-14 11:33
@DanTup Hi, Thanks to your reply.

I switched to pre-release version like below.
<img width="735" alt="image" src="https://user-images.githubusercontent.com/87428594/218725644-d7d09757-71d7-4820-991a-d28bfae68957.png">

and result is same T T

<img width="679" alt="image" src="https://user-images.githubusercontent.com/87428594/218725698-6c8eb777-264e-4e7b-bb97-038e3f8ad42d.png">

**Comment by DanTup** [comment] 2023-02-14 11:50
@Faamica thank you for testing. Could you try changing the port that DevTools runs on the VS Code settings and restart VS Code and see if that changes anything?

<img width="610" alt="Screenshot 2023-02-14 at 11 49 43" src="https://user-images.githubusercontent.com/1078012/218730151-4491feb3-8363-48bf-bf8c-8ec96eeed8aa.png">

The default port is 9100, so picking anything in the range 9101-9200 should be fine.

**Comment by Faamica** [comment] 2023-02-14 11:56
Omg!!!!!!!!!!! you saved my life..........
Thank you sooooooooooooo much T ____________ T Thank you!!!!

<img width="1057" alt="image" src="https://user-images.githubusercontent.com/87428594/218731401-13bb7e7f-eeff-4aa7-9faf-6be05a2b5666.png">

**Comment by DanTup** [comment] 2023-02-14 12:02
Great - thanks for confirming. I'll close this as a dupe of https://github.com/flutter/devtools/issues/3896 where we're trying t track down the caching issues that cause issues like this. For now, changing the port number is a way to avoid any caching from previous SDK versions causing issues like this.

**Closed by DanTup** 2023-02-14 12:02 UTC
Labels: is bug, awaiting info

**Comment by Faamica** [comment] 2023-02-14 12:04
@DanTup thank you again!

**Comment by DanTup** [comment] 2023-02-14 12:09
np! :)
