### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by xandr-hill** [Dart-Code/Dart-Code#1747] opened 2019-05-27 00:18 UTC
- Issue Type: `Bug`
- Extension Name: `dart-code`
- Extension Version: `3.0.2`
- OS Version: `Darwin x64 17.7.0`
- VSCode version: `1.34.0`

```json 
{
	"messages": [],
	"activationTimes": {
		"startup": true,
		"codeLoadingTime": 16764,
		"activateCallTime": 3910,
		"activateResolvedTime": 0,
		"activationEvent": "workspaceContains:**/pubspec.yaml,**/*.dart"
	},
	"runtimeErrors": []
}
```

**Comment by DanTup** [comment] 2019-05-27 08:14
@xandr-hill it's not clear from this info what the issue is you're seeing - can you provide some more details?

**Comment by DanTup** [comment] 2019-06-11 13:47
I'm going to guess maybe you saw a report from VS Code about bad performance (since the above suggests 16 seconds to activate). This means it's likely a dupe of https://github.com/Dart-Code/Dart-Code/issues/1628 which is fixed for the next version.

If you don't think that's the case, please provide some more info and I can take a look.

**Closed by DanTup** 2019-06-11 13:47 UTC
Labels: awaiting info
