### ISSUE TITLE
Debugger crash on flutter projets placed on a sub-directory.

### ISSUE THREAD

**Issue by rrousselGit** [Dart-Code/Dart-Code#581] opened 2018-02-16 18:01 UTC
When a flutter project is placed on a sub-directory, and you try to debug it using the usual launch.json ; we get the following error:

> The built-in library 'dart:ui' is not available on the stand-alone VM.
'package:flutter/src/material/animated_icons.dart': error: line 9 pos 1: library handler failed
import 'dart:ui' as ui show Paint, Path, Canvas;
^

It is fairly simple to reproduce :

```
mkdir foo
cd foo
flutter create bar
code .
```

then add to `.vscode/launch.json`

```
{
  // Use IntelliSense to learn about possible attributes.
  // Hover to view descriptions of existing attributes.
  // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Test",
      "type": "dart",
      "request": "launch",
      "program": "${workspaceRoot}/bar/lib/main.dart",
    }
  ]
}
```

and hit f5

**Comment by DanTup** [comment] 2018-02-16 18:13
We don't detect flutter projects in sub directories so we're just treating this as a Dart project (for this reason, you'll actually be missing other stuff - like the device selector in the status bar). There was some discussion around it a while back, but we decided it made more sense to use [multi-root workspaces](https://code.visualstudio.com/docs/editor/multi-root-workspaces). Otherwise Dart Code would have to walk the tree trying to guess which things are projects and which are not. By using MRWs this is clearly defined by the user.

Note: It's possible to have overlapping workspace folders, so if you do File -> Add Folder to Workspace and choose your flutter app subfolder then it might fix things without otherwise changing anything.

Btw, I presume you're using 2.9.1-beta.1 based on your launch.json? If so, we support running Flutter apps without a launch.json at all in that version (though they do need to be the a root workspace folder).

**Comment by DanTup** [comment] 2018-02-16 18:14
Gonna consider this a dupe of #493. I think we do need to do something here help users get set up correctly.

**Closed** 2018-02-16 18:15 UTC
Labels: duplicate

**Comment by DanTup** [comment] 2018-03-03 11:12
FWIW, I'm revisiting this and plan to better support projects in sub-folders (see #493).
