### ISSUE TITLE
Analysis server does not update problems/ linting errors over LiveShare

### ISSUE THREAD

**Issue by ThinkDigitalSoftware** [Dart-Code/Dart-Code#2094] opened 2019-11-06 20:55 UTC
**If I'm working on a project in Liveshare and fix a linting error, it doesn't disappear in the problems section. This is the output of Flutter doctor -v on the host machine**

> Microsoft Windows [Version 10.0.17763.805]
> (c) 2018 Microsoft Corporation. All rights reserved.
> 
> C:\Users\RTH\Desktop\Flutter Dart App Portfolio\firebase_crud1> flutter doctor -v
> [√] Flutter (Channel stable, v1.9.1+hotfix.6, on Microsoft Windows [Version 10.0.17763.805], locale en-US)
>     • Flutter version 1.9.1+hotfix.6 at C:\Users\RTH\flutter
>     • Framework revision 68587a0916 (8 weeks ago), 2019-09-13 19:46:58 -0700
>     • Engine revision b863200c37
>     • Dart version 2.5.0
> 
> 
> [√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
>     • Android SDK at C:\Users\RTH\AppData\Local\Android\sdk
>     • Android NDK location not configured (optional; useful for native profiling support)
>     • Platform android-28, build-tools 28.0.3
>     • Java binary at: F:\Android Files\jre\bin\java
>     • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
>     • All Android licenses accepted.
> 
> [√] Android Studio (version 3.5)
>     • Android Studio at F:\Android Files
>     • Flutter plugin version 41.0.2
>     • Dart plugin version 191.8593
>     • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
> 
> [√] VS Code (version 1.39.2)
>     • VS Code at C:\Users\RTH\AppData\Local\Programs\Microsoft VS Code
>     • Flutter extension version 3.6.0
> 
> [!] Connected device
>     ! No devices available
> 
> ! Doctor found issues in 1 category.
> 

**flutter doctor -v on the client machine:**

> [✓] Flutter (Channel master, v1.10.15-pre.384, on Mac OS X 10.15.1 19B88, locale en-US)
>     • Flutter version 1.10.15-pre.384 at /Users/thinkdigital/development/flutter
>     • Framework revision ee032f67c7 (4 days ago), 2019-11-02 09:46:25 -0700
>     • Engine revision 8ea19b1c76
>     • Dart version 2.6.0 (build 2.6.0-dev.8.2 bbe2ac28c9)
> 
>  
> [✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
>     • Android SDK at /Users/thinkdigital/Library/Android/sdk
>     • Android NDK location not configured (optional; useful for native profiling support)
>     • Platform android-29, build-tools 29.0.2
>     • ANDROID_SDK_ROOT = /Users/thinkdigital/Library/Android/sdk
>     • Java binary at: /Users/thinkdigital/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/191.5900203/Android
>       Studio.app/Contents/jre/jdk/Contents/Home/bin/java
>     • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
>     • All Android licenses accepted.
> 
> [✓] Xcode - develop for iOS and macOS (Xcode 11.2)
>     • Xcode at /Applications/Xcode.app/Contents/Developer
>     • Xcode 11.2, Build version 11B44
>     • CocoaPods version 1.8.4
> 
> [✓] Chrome - develop for the web
>     • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
> 
> [✓] Android Studio (version 3.5)
>     • Android Studio at /Applications/Android Studio.app/Contents
>     • Flutter plugin version 41.0.2
>     • Dart plugin version 191.8593
>     • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
> 
> [✓] Android Studio (version 3.5)
>     • Android Studio at /Users/thinkdigital/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/191.5900203/Android Studio.app/Contents
>     • Flutter plugin version 41.0.2
>     • Dart plugin version 191.8593
>     • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
> 
> [✓] IntelliJ IDEA Community Edition (version 2019.2.4)
>     • IntelliJ at /Applications/IntelliJ IDEA CE.app
>     • Flutter plugin version 41.0.4
>     • Dart plugin version 192.7402
> 
> [✓] VS Code (version 1.39.2)
>     • VS Code at /Applications/Visual Studio Code.app/Contents
>     • Flutter extension version 3.6.0
> 
> [✓] Connected device (4 available)
>     • Android SDK built for x86 • emulator-5554                        • android-x86    • Android 8.1.0 (API 27) (emulator)
>     • iPhone 11 Pro Max         • F3A5BA32-2FC7-491B-9862-A42B54C487A5 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-13-2 (simulator)
>     • Chrome                    • chrome                               • web-javascript • Google Chrome 78.0.3904.97
>     • Web Server                • web-server                           • web-javascript • Flutter Tools
> 
> • No issues found!

**Comment by DanTup** [comment] 2019-11-07 10:10
Can you clarify  exactly what your setup is. Are the changes being made on the host or client, and where are they not updating? Are they updating on the other machine?

Also - could you check if there are any errors shown in the dev console (Help -> Toggle Developer Tools -> Console). Thanks!

**Comment by ThinkDigitalSoftware** [comment] 2019-11-07 15:12
What do you mean by setup?
Changes are being made on both sides with the same effect. They're updating on the host, but not the client. I'm the client. I'll have to open another session to check the logs. I'll update the post when I do so

**Comment by DanTup** [comment] 2019-11-07 15:40
> They're updating on the host, but not the client

Thanks, that's what I wasn't sure about :)

@lostintangent before I dig too much into this, are there any known issues like this (sorry if you're not the right person to ask, but you assisted with a previous issue :-))? This seems like something the live sharing extension should be keeping synchronised, I can't think of what could go wrong in the language extension to cause this?

**Comment by DanTup** [comment] 2020-04-21 13:34
I'm unable to reproduce this issue today. I started a session and clicked the "Try joining yourself" link which spawns a new VS Code, and the errors seem to be synced fine (though only those for the current file seem to show up on the client - I presume that's Live Share functionality).

Can you still reproduce any issues here?

**Comment by ThinkDigitalSoftware** [comment] 2020-04-21 15:11
You did a local session? I wouldn't say that that's guaranteed to be the same. I always get this issue. Even still now. I haven't tried in a few weeks, but I can't recall a time where I didn't have the issue

**Comment by DanTup** [comment] 2020-04-21 15:27
> You did a local session? I wouldn't say that that's guaranteed to be the same.

I did. I figured it'd be the same since they're two separate VS Code instances and connecting via the URL, but I don't know if it has shortcuts.

Can you give an example of exactly what you did so I can make sure when I try it across multiple machines I do the same thing? Thanks!

**Comment by ThinkDigitalSoftware** [comment] 2020-05-22 05:18
@DanTup I connected with another user. That's it. Multiple users over remote sessions with the same results. It would update rarely, most of the times, it would show old analysis errors and warnings so I'd have to ask the other user if there were any issues with the code.

**Comment by DanTup** [comment] 2020-05-26 13:17
There's an open issue at https://github.com/MicrosoftDocs/live-share/issues/3509 about sync and performance issues. I don't think there's a lot that can be done in the Dart extension (at least without some guidance from Live-Share). The synchronisation of things like errors is entirely done by Live Share, so if they're out of sync between client/host, that seems like a Live Share bug.

There are some perf issues when `autoImportCompletions` is enabled (because LiveShare is transferring thousands of completion items over to the client, and it's about 2.6MB/10k items for a typical Flutter project) which I've made a suggestion about on the issue.

I'll close this as a dupe of that one (as we can't fix sync issues here), but I'm subscribed to that LiveShare issue, so if things come up that we can do in the Dart/Flutter extensions to improve performance etc., I'lll take a look.

**Closed** 2020-05-26 13:17 UTC
Labels: upstream in vs code
