### ISSUE TITLE
Flutter app does not stop at breakpoints

### ISSUE THREAD

**Issue by pprk-prjs** [Dart-Code/Dart-Code#2156] opened 2019-12-09 06:23 UTC
Hi,

I'm not able to debug flutter application on an emulator/device. 
[Dart-Code-Log-2019-11-01 06-37-01.txt](https://github.com/Dart-Code/Dart-Code/files/3938110/Dart-Code-Log-2019-11-01.06-37-01.txt)

Launcher:

> "configurations": [
        {
            "name": "Flutter",
            "type": "dart",
            "request": "launch",
            "program": "lib/main.dart",
            // "vmAdditionalArgs": ["--debug", "--stacktrace", "--verbose"],
            "args": ["--debug"]
        },

peperk

**Comment by DanTup** [comment] 2019-12-09 12:51
Can you clarify what you mean but you are unable to debug? The log file seems to show an app loading and being hot reloaded so it's not clear which bit wasn't working.

**Comment by pprk-prjs** [comment] 2019-12-10 05:48
If I put several breakpoints in a code then the application is running without stopping on these breakpoints. It stops only if there is any exception.

**Comment by DanTup** [comment] 2019-12-10 07:39
@pprk-prjs got it. Could you capture a log file using the [**Dart: Capture Logs**](https://dartcode.org/docs/logging/#capture-logs-command) command?

If you're using `flutter generate` then this may be the same as https://github.com/Dart-Code/Dart-Code/issues/1976.

**Comment by pprk-prjs** [comment] 2019-12-11 20:50
Here is the log file: [Dart-Code-Log.txt](https://github.com/Dart-Code/Dart-Code/files/3952500/Dart-Code-Log.txt)
Yes, I used  `flutter generate` in this case.

**Comment by DanTup** [comment] 2019-12-12 07:38
Ah ok, then I'll close this as a dupe of #1976. There's something about the way `flutter generate` works that seems to be preventing the breakpoints from resolving correctly - subscribe to that issue for updates.

Thanks!

**Closed by DanTup** 2019-12-12 07:38 UTC
Labels: awaiting info
