### ISSUE TITLE
IconData's from Icons don't preview

### ISSUE THREAD

**Issue by sersht** [Dart-Code/Dart-Code#3472] opened 2021-07-13 17:32 UTC
**Describe the bug**
IconData's from Icons class don't preview (none of them) when developing in VSCode. However, they preview near line-of-code numbers (screenshots attached)

**Screenshots**
![Screenshot from 2021-07-13 20-26-23](https://user-images.githubusercontent.com/26171151/125498630-6b2b9e0f-6184-4c73-a729-0ea30319ef8f.png)
![Screenshot from 2021-07-13 20-27-34](https://user-images.githubusercontent.com/26171151/125498644-33baeee7-9539-47d7-9bbf-c526e644bf52.png)

**Versions:** 
- VS Code version:
```
Version: 1.58.0
Commit: 2d23c42a936db1c7b3b06f918cde29561cc47cd6
Date: 2021-07-08T06:53:55.113Z
Electron: 12.0.13
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Linux x64 5.8.0-59-generic
```
 - Dart extension version:
```
3.24.2
```
 - Flutter extension version:
```
3.24.0
```
 - Dart/Flutter SDK version: 
```
Dart SDK version: 2.13.4 (stable) (Wed Jun 23 13:08:41 2021 +0200) on "linux_x64"

Flutter 2.2.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision f4abaa0735 (12 days ago) • 2021-07-01 12:46:11 -0700
Engine • revision 241c87ad80
Tools • Dart 2.13.4
```

**Comment by DanTup** [comment] 2021-07-13 17:47
Thanks for the report. This seems to be a regression in VS Code. There's an open issue here:

https://github.com/microsoft/vscode/issues/119786

Although it doesn't seem like that issue is marked as serious, but others are being closed as duplicates of it (eg. https://github.com/microsoft/vscode/issues/128315).

Unfortunately I don't think there's a way we can workaround this until it's fixed there. Once it is, it should just start working again automatically. Sorry for the inconvenience!

**Closed** 2021-07-13 17:48 UTC
Labels: upstream in vs code / lsp / dap
