### ISSUE TITLE
VS Code Extension  'A Request has Failed'

### ISSUE THREAD

**Issue by Potatoes57** [Dart-Code/Dart-Code#3464] opened 2021-07-06 01:57 UTC
**Describe the bug**

I put a ButtonStyle type in custom theme class AppTheme, after that every dart language query returned 'A Request has failed, see output for more information.' appears when hovering over code to get context.

Output shows:
[Error - 11:53:13 AM] Request textDocument/codeAction failed.
  Message: Invalid file path
  Code: -32003 

**To Reproduce**
1. Open Dart File in VS Code
2. Hover cursor over Class

**Expected behavior**
VS code shows normal information of where the cursor is.

**Versions (please complete the following information):**
 - VS Code version: 1.57.1
 - Dart extension version: 3.24.2
 - Dart/Flutter SDK version: 2.2.3

**Comment by DanTup** [comment] 2021-07-06 09:34
Can you reproduce this and share the exact contents of the file when this was triggered? Thanks!

**Comment by Potatoes57** [comment] 2021-07-07 23:02
This was the file I changed before it started, removing the const blueButton, fixes the problem across every open file in the IDE.


`import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';

class AppTheme {
  AppTheme._();

  static const Color medBlue = Color(0xFF4D95CC);
  static const Color lightBlue = Color(0xFFD9E8FF);
  static const Color medGreen = Color(0xFF74BE98);
  static const Color grey = Color(0xFF656565);
  static const Color white = Color(0xFFFFFFFF);
  static const Color background = Color(0xFFF0F2F5);
  static const Color greyShadow = Color(0x0F000000);

  static const String fontName = 'Sans';

  static const double largeIcon = 56;
  static const double medIcon = 38;
  static const double smlIcon = 25;

  static const TextStyle title = TextStyle(
    fontFamily: fontName,
    fontWeight: FontWeight.bold,
    fontSize: 18,
    letterSpacing: 0.18,
    color: white,
  );

  static const TextStyle titleBlue = TextStyle(
    fontFamily: fontName,
    fontWeight: FontWeight.bold,
    fontSize: 18,
    letterSpacing: 0.18,
    color: medBlue,
  );

  static const TextStyle headline = TextStyle(
    fontFamily: fontName,
    fontWeight: FontWeight.bold,
    fontSize: 28,
    letterSpacing: 0.27,
    color: grey,
  );

  static const TextStyle headlineWhite = TextStyle(
    fontFamily: fontName,
    fontWeight: FontWeight.bold,
    fontSize: 28,
    letterSpacing: 0.27,
    color: white,
  );

  static const TextStyle headlineBlue = TextStyle(
    fontFamily: fontName,
    fontWeight: FontWeight.bold,
    fontSize: 28,
    letterSpacing: 0.27,
    color: medBlue,
  );

  static const TextStyle listBold = TextStyle(
    fontFamily: fontName,
    fontWeight: FontWeight.bold,
    fontSize: 22,
    letterSpacing: 0.4,
    height: 0.9,
    color: medBlue,
  );

  static const TextStyle listLight = TextStyle(
    fontFamily: fontName,
    fontWeight: FontWeight.normal,
    fontSize: 22,
    letterSpacing: 0.4,
    height: 0.9,
    color: medBlue,
  );

  static const TextStyle listGrey = TextStyle(
    fontFamily: fontName,
    fontWeight: FontWeight.normal,
    fontSize: 22,
    letterSpacing: 0.4,
    height: 0.9,
    color: grey,
  );

  static const TextStyle titleGrey = TextStyle(
    fontFamily: fontName,
    fontWeight: FontWeight.normal,
    fontSize: 18,
    letterSpacing: 0.18,
    color: grey,
  );

  static const TextStyle appBarWhite = TextStyle(
    fontFamily: fontName,
    fontWeight: FontWeight.bold,
    fontSize: 28,
    letterSpacing: 0.18,
    color: white,
  );

  static const TextStyle questionText = TextStyle(
    fontFamily: fontName,
    fontWeight: FontWeight.bold,
    fontSize: 22,
    letterSpacing: -0.04,
    color: grey,
  );

  static const TextStyle QuestionBlue = TextStyle(
    fontFamily: fontName,
    fontWeight: FontWeight.bold,
    fontSize: 22,
    letterSpacing: -0.04,
    color: medBlue,
  );

  static const TextStyle subtitle = TextStyle(
    fontFamily: fontName,
    fontWeight: FontWeight.w400,
    fontSize: 14,
    letterSpacing: -0.04,
    color: grey,
  );

  static const TextStyle caption = TextStyle(
    fontFamily: fontName,
    fontWeight: FontWeight.bold,
    fontSize: 30,
    letterSpacing: 0.2,
    color: Colors.white,
  );

  //Adding this causes the error
  static const ButtonStyle blueButton = ButtonStyle(
    backgroundColor: MaterialStateProperty.all(AppTheme.medBlue),
    textStyle: MaterialStateProperty.all(AppTheme.buttonWhite),
  );

  static const TextStyle captionBlue = TextStyle(
      fontFamily: fontName,
      fontWeight: FontWeight.bold,
      fontSize: 20,
      letterSpacing: 0.2,
      color: medBlue);

  static const TextStyle buttonWhite = TextStyle(
    fontFamily: fontName,
    fontWeight: FontWeight.bold,
    fontSize: 22,
    letterSpacing: 0.2,
    color: white,
  );

  static const TextStyle buttonBlue = TextStyle(
    fontFamily: fontName,
    fontWeight: FontWeight.bold,
    fontSize: 22,
    letterSpacing: 0.2,
    color: medBlue,
  );

  static const TextStyle navBarLabel = TextStyle(
    fontFamily: fontName,
    fontSize: 10,
    letterSpacing: 0.2,
    color: white,
  );

  static const BoxShadow cardShadow = BoxShadow(
      color: greyShadow, blurRadius: 3, spreadRadius: 6, offset: Offset(0, 4));

  static const BoxDecoration card = BoxDecoration(
    color: white,
    borderRadius: BorderRadius.all(Radius.circular(5)),
    boxShadow: [
      cardShadow,
    ],
  );
}
`

**Comment by DanTup** [comment] 2021-07-08 09:44
I don't seem to be able to reproduce it with that code, it reports an error but otherwise everything is fine:

<img width="941" alt="Screenshot 2021-07-08 at 10 43 16" src="https://user-images.githubusercontent.com/1078012/124900865-5f9db380-dfd9-11eb-84c3-313c8eefe31e.png">

I tried with Flutter 2.2.3 and latest master. Does it reproduce for you if you copy that code into a new file? I wonder if it requires something else too?
(my suspicion is this is a parser error, as we've seen this error a few times if the parser fails to parse a file correctly)

**Comment by Potatoes57** [comment] 2021-07-08 11:55
You might be right on the parser issue. I made a new file in the same project and the error persisted, but when I created a new project it was fine.

**Comment by DanTup** [comment] 2021-07-08 13:07
I suspect there may be something in one of your other files triggering it then. Could you try making a copy of your project, and then deleting code/files until the issue goes away and see what the last thing you deleted was?

Could it be similar to #46301 which I closed earlier? This was caused by having a variable list declaration with both public + private variables:

```
var foo, _bar;
```

It's been fixed, but the fix has not reached the stable channel yet.

**Comment by Robbendebiene** [comment] 2021-07-21 09:13
I've encountered the exact same problem. The moment I add the `MaterialStateProperty.all` inside the `ButtonStyle()` the mentioned error appears. However using the same file in a newly created flutter project doesn't cause the error.

> I suspect there may be something in one of your other files triggering it then. Could you try making a copy of your project, and then deleting code/files until the issue goes away and see what the last thing you deleted was?

I've tried this and the problem only occurs in conjunction with `import 'package:flutter/material.dart';` After some trial and error I can finally reproduce this issue reliably with the following steps:

1. Create a new flutter project via `flutter create test`
2. Change the `main.dart` code to:
    ```
    import 'package:flutter/material.dart';
    ButtonStyle(
      backgroundColor: MaterialStateProperty.all(Colors.white),
    );
    ```
3. Change the SDK version under environment in the `pubspec.yaml` to `sdk: ">=2.7.0 <3.0.0"`
4. **Restart VSCode**

**Comment by DanTup** [comment] 2021-07-21 11:04
@Robbendebiene thanks for the repro! I was able to reproduce on Flutter stable. I got the error from the logs:

```
1626865120033:Ex:Analysis failed:: /private/tmp/dc3464/lib/main.dart context:: exception_20210721_115839_951
Null check operator used on a null value
#0      ResolutionSink._enclosingClassTypeArguments.<anonymous closure> (package::analyzer/src/summary2/bundle_writer.dart::599::62)
#1      MappedListIterable.elementAt (dart::_internal/iterable.dart::412::31)
#2      ListIterator.moveNext (dart::_internal/iterable.dart::341::26)
#3      new _List._ofEfficientLengthIterable (dart::core-patch/array.dart::93::27)
#4      new _List.of (dart::core-patch/array.dart::55::20)
#5      new List.of (dart::core-patch/array_patch.dart::52::20)
#6      ListIterable.toList (dart::_internal/iterable.dart::212::44)
#7      ResolutionSink._enclosingClassTypeArguments (package::analyzer/src/summary2/bundle_writer.dart::600::12)
#8      ResolutionSink.writeElement (package::analyzer/src/summary2/bundle_writer.dart::393::27)
#9      AstBinaryWriter.visitSimpleIdentifier (package::analyzer/src/summary2/ast_binary_writer.dart::1664::22)
```

This was was fixed by https://github.com/dart-lang/sdk/commit/ae39dee6fa2d6d9cedffa884c3f73bb22c21d75d. I tried on Flutter master and confirmed it doesn't occur there. So it seems this has already been fixed, and should be included in a future SDK release.

Thanks!

**Closed** 2021-07-21 11:04 UTC
Labels: fixed in dart / flutter
