### ISSUE TITLE
'Do not format' setting does not work with LSP

### ISSUE THREAD

**Issue by guidezpl** [Dart-Code/Dart-Code#3586] opened 2021-09-29 21:24 UTC
I'm trying to exclude my flutter repo from being auto-formatted. I added patterns for the directory as well as a single file `flutter-dev/packages/flutter_tools/lib/src/commands/downgrade.dart`. Yet, saving that file still formats it.

**To Reproduce**
1. Add paths to 'Do not format' setting
2. Save modified file `downgrade.dart` inside 'flutter-dev' folder

**Expected behavior**
`downgrade.dart` is not formatted

**Versions (please complete the following information):**
 - VS Code version:  1.60.2 
 - Dart extension version: 3.26.0
 - Dart/Flutter SDK version: 2.6.0-12.0.pre.27, Dart version 2.15.0

`settings.json`
```
{
    "[dart]": {
        "editor.formatOnSave": true,
        "editor.rulers": [
            80
        ],
        "editor.selectionHighlight": false,
        "editor.suggest.snippetsPreventQuickSuggestions": false,
        "editor.suggestSelection": "first",
        "editor.tabCompletion": "onlySnippets",
        "editor.wordBasedSuggestions": false
    },
    "dart.doNotFormat": [
        "**/development/flutter/**",
        "**/development/flutter-dev/**",
        "**/flutter-dev/**",
        "*/downgrade.dart"
    ],
    "workbench.sideBar.location": "right",
    "workbench.colorTheme": "Material Theme Darker",
    "workbench.iconTheme": "eq-material-theme-icons-darker",
    "dart.debugExternalPackageLibraries": false,
    "dart.debugSdkLibraries": false,
    "git.autofetch": true,
    "dart.hotReloadProgress": "statusBar",
    "files.autoSave": "onFocusChange",
    "explorer.confirmDragAndDrop": false,
    "workbench.tree.indent": 16,
}
```

**Comment by DanTup** [comment] 2021-09-30 08:28
The `doNotFormat` setting is not currently supported when using the LSP integration (which is the new default). The way it was implemented was a little awkward and if it's still being used we should probably find a better way of handling it than just mirroring what we had into LSP.

In the meantime, if there are specific projects you don't want to format, you can use the VS Code Workspace Settings to disable format-on-save for just those specific workspaces (for example in my Flutter framework checkout, I have `"editor.formatOnSave": false` in the workspace settings so it never formats on save). If you use Git in VS Code, then using [only format modified text](https://code.visualstudio.com/updates/v1_49#_only-format-modified-text) may also reduce the formatting to only the lines you're changing.

**Comment by DanTup** [comment] 2021-10-13 11:29
@guidezpl are all of your cases covered by disabling format-on-save at a workspace level (eg. for Flutter), or do you have cases where you need this to apply to specific files in the workspace (and where the **Save Without Formatting** command isn't good enough)?

I don't have a great idea for how to support this in LSP now (without reproducing some annoying drawbacks, like also not being able to _manually_ format in those files) so if it's not pressing, it may be better to wait until there's more demand and/or a better solution.

**Comment by DanTup** [comment] 2021-10-18 11:23
@guidezpl I'm not certain - VS Code's UI is not clear whether this setting is "set to false" at the workspace level, or "not set, so inherits".

Can you confirm exactly how your workspace is set up? Is it a `.code-workspace` file? If so, can you check inside that file and see if `editor.formatOnSave` is set to `false` or not? If it's not listed, try adding it manually and see if that helps?

**Comment by DanTup** [comment] 2022-01-20 10:40
@guidezpl is this still an issue, or is the above working fine?

Implementing this feels a little awkward to me (I don't think any of the options we currently have for where to define this are particularly great), but as well as being able to disable it per-workspace-folder as described above, you can also set VS Code to only format the lines you've changed (if you have its source control enabled) which would also avoid formatting whole files if you're making small changes to them.

I suspect it's not very common to want to format some files entirely on-save and others not within the same project (it seems like a project would generally either be all formatted, or none formatted - with the exception of generated files that probably aren't modified/saved) so I think the benefit to handling this might be fairly low.

**Comment by guidezpl** [comment] 2022-01-20 11:25
Found it btw https://github.com/microsoft/vscode/issues/58038. Yeah, this is only of interest at the project level

**Comment by DanTup** [comment] 2022-01-25 11:36
Okey, closing this as as-intended for now. If there's demand for disabling format-on-save for specific files we can try to get this via VS Code. Thanks!

**Closed** 2022-01-25 11:36 UTC
Labels: is bug, in editor, in lsp/analysis server
