### ISSUE TITLE
Analyzer doesn't detect changes in l10n Flutter tool.

### ISSUE THREAD

**Issue by jamesblasco** [Dart-Code/Dart-Code#3074] opened 2021-01-16 18:42 UTC
**Describe the bug**
https://flutter.dev/docs/development/accessibility-and-localization/internationalization

In Flutter 1.22, a new tool for generating translations was released. This tool generates a synthetic package in the root 
`.dart_tool/flutter_gen/l10n_gen` and updates the code when `flutter run` is running and the arb template file changes .

But the new code generated inside that package is not reanalyzed and saw an error like if the methods inside the package don't exists. Once the file `.dart_tool/flutter_gen/l10n_gen/app_localizations.dart` is opened the error disapears. 

**To Reproduce**
1. Follow the steps at https://flutter.dev/docs/development/accessibility-and-localization/internationalization

**Screenshots**

**Versions (please complete the following information):**
 - VS Code version: 1.52.1
 - Dart extension version: 3.18.1
 - Dart/Flutter SDK version: Channel dev, 1.26.0-8.0.pre, on macOS 11.1 20C69 darwin-x64, locale es-E

**Comment by DanTup** [comment] 2021-01-18 14:07
@bwilkerson I can reproduce this [in a test](https://gist.github.com/DanTup/fa7b6e4c40c119ad2992e177b1642bfc) - it appears that files inside `.dart_tool` are analyzed at context creation but if they are modified while the analysis server is active, the updates are ignored.

It seems to be caused by this line in the watcher handler that skips anything in dot-folders:

https://github.com/dart-lang/sdk/blob/04e8aa58ee81bed52a63d4bbb10791a9eb018d7e/pkg/analysis_server/lib/src/context_manager.dart#L1319

It looks like that was added in https://github.com/dart-lang/sdk/commit/f9aebddc67191b9c136ddff2e95db6869ce1b569 to fix https://github.com/dart-lang/sdk/issues/24212 - although perhaps that would also now also fixed by https://github.com/dart-lang/sdk/commit/0450462503eb4faf79efd246b6de15e2e7229ec0 (which prevents the errors being sent to the user, but doesn't prevent analysis).

**Comment by bwilkerson** [comment] 2021-01-18 16:31
I suspect that you're right, that if we re-analyzed files in hidden folders we would now be OK. I certainly think it's worth doing an experiment.

**Comment by DanTup** [comment] 2021-01-19 11:30
@bwilkerson with the change at https://dart-review.googlesource.com/c/sdk/+/179776/ this seems to work as expected. I've opened a Flutter project, fetched packages, built and run and I haven't noticed any negative effects. There is likely some overhead in that files that were previously just ignored will be analyzed (though this seems unavoidable to support something like the `flutter_gen` project that lives inside `.dart_tool`).

It does however break [test_watch_addFile_pathContainsDotFile](https://github.com/dart-lang/sdk/blob/903e92a1963c38f6825b738c222af849c834e3a4/pkg/analysis_server/test/context_manager_test.dart#L1081-L1095). I think this is probably expected but would like a second opinion. The test is checking that if you explicitly add (eg. open in the ide) a file inside a dot file that it's also not included in the context, although with this change it will be, it just would not produce error notifications. If that seems reasonable to you, I can remove it, or invert its logic (in which case it would function much like the test immediately below it).

**Comment by bwilkerson** [comment] 2021-01-19 15:57
If analyzing all changed files in those directories proves to be a problem, we can probably find a way to optimize it further. That said, I'm going to ask @scheglov for his opinion on this one.

**Comment by scheglov** [comment] 2021-01-21 21:28
It seems reasonable to me that requirements changed, and now we want to handle *some* files in dot-directories.  I think that the biggest reason to avoid doing this was to avoid handling changes in not user facing directories like `.git`. So, I would limit it to specifically `.dart_tool` and `package:build`.

**Comment by DanTup** [comment] 2021-01-25 14:19
I've updated https://dart-review.googlesource.com/c/sdk/+/179776 to only handle `.dart_tool` (I'm not aware of any dot-folders `package:build` writes to outside of that, but more can be added if that's not true).

**Comment by DanTup** [comment] 2021-02-01 10:25
This has been fixed in https://github.com/dart-lang/sdk/commit/77353dc380967dc011ac343f7753b53031e2305a which should be included in a future Dart/Flutter SDK release.

**Closed by DanTup** 2021-02-01 10:25 UTC
Labels: in editor, in lsp/analysis server, is bug

**Comment by orestesgaolin** [comment] 2022-03-14 11:34
I wonder if you know which Flutter or DartCode version is going to include this fix?

**Comment by DanTup** [comment] 2022-03-14 11:57
@orestesgaolin the fix above should have shipped in stable releases quite some time ago, but perhaps you're still seeing #3438? The fix for that was in the Dart SDK, but looks like it wasn't in v2.16 (the current stable), so I'd expect it to be in the next major Dart/Flutter release.

I think it's probably already in the Flutter beta channel, as that reports `2.17.0-69.2.beta` for the Dart SDK and the commit above includes the tag `2.17.0-20.0.dev`.
