### ISSUE TITLE
argument "--machine" disables "--multidex"

### ISSUE THREAD

**Issue by MCredbear** [Dart-Code/Dart-Code#3837] opened 2022-02-18 15:40 UTC
**Describe the bug**
As we know `--machine` is a default argument of this plugin (At `spawnRunDaemon()`), but it can fail `--multidex` which is a required one for new Android Apps.  
Usually, `--multidex` is default to be enabled, and if it isn't enabled and it's required, the SDK would report.  
But after adding `--machine`, although you have added `--multidex`, the SDK still tells yout to add it.

 - VSCodium version: 1.64.2
 - Dart extension version: 3.34.0
 - Dart/Flutter SDK version: 2.11.0-0.0.pre.501

**Comment by DanTup** [comment] 2022-02-22 17:54
I think this is something that will need handling in the `flutter` tool (https://github.com/flutter/flutter/). I'm not very familiar with multidex though - if you can provides steps for me to reproduce this issue I can have a look. Thanks!

**Comment by MCredbear** [comment] 2022-02-23 13:55
> I think this is something that will need handling in the `flutter` tool (https://github.com/flutter/flutter/). I'm not very familiar with multidex though - if you can provides steps for me to reproduce this issue I can have a look. Thanks!

This is my codes: https://github.com/MCredbear/netease_cloudmusic_flutter  
Clone it and open it in VSCode, delete line 51 and 69 in `android/app/build.gradle`, then press F5, then you will see the error

**Comment by DanTup** [comment] 2022-03-16 10:52
Sorry I didn't respond -  have started looking at this over at https://github.com/flutter/flutter/pull/99010, but need some input from someone on the Flutter team. I've removed the awaiting-info tag and will update here when that progresses. Thanks!

**Comment by DanTup** [comment] 2022-04-11 20:14
Fixed by https://github.com/flutter/flutter/pull/101689. Since the fix is in the Flutter SDK, it'll show up in a future Flutter release rather than a VS Code extension release.

**Closed by DanTup** 2022-04-11 20:14 UTC
Labels: is bug, in flutter
