### ISSUE TITLE
VS Code(Linux) Unable To Launch Chrome For Flutter For Web

### ISSUE THREAD

**Issue by azwalzaman** [Dart-Code/Dart-Code#3328] opened 2021-05-07 11:56 UTC
**Describe the bug**
When I run my flutter application from VS Code using the debugger chrome briefly opens and closes and I get an HttpException. Same application works fine with `flutter run -d chrome` on terminal.

**To Reproduce**
1. Create a flutter application in stable channel on Ubuntu 20.04
2. Try to run application from the VS Code debugger using chrome as the device

**Expected behavior**
Chrome opening and running the application while connected to the VS Code debugger

**Versions:**
 - VS Code version: 1.56.0
 - Dart extension version: 3.22.0
 - Flutter SDK version: 2.0.6
 - Chrome Version: 90.0.4430.93 (Official Build) (64-bit)

**Comment by azwalzaman** [comment] 2021-05-07 15:19
> > and I get an HttpException
> 
> Where does this exception show up? Can you see the full exception message?
> 
It shows up in the debug console. The full exception message is:
`HttpException: Connection closed before full header was received, uri = http://localhost:46283/devtools/page/4CA04AF82E927D18567D93EA74A123C3`
> Does this also occur if you use `Run -> Run without Debugging`, or only when using `Run -> Start Debugging`?
> 
It happens with both
> When you tried using `flutter run -d chrome` from the terminal, was it the built-in terminal in VS Code, or external? If external, can you test whether you see the same when using the one inside VS Code?
> 
It was in the built-in terminal
> Thanks!

**Comment by DanTup** [comment] 2021-05-07 17:31
Thanks! I think this might be a Flutter issue being tracked here:

https://github.com/flutter/flutter/issues/73743

Specifically, this comment here has the same exception:

https://github.com/flutter/flutter/issues/73743#issuecomment-758272078

The most recent comment on there suggests it might be related to Snap:

https://github.com/flutter/flutter/issues/73743#issuecomment-819405942

I'll close this one as a dupe of that to keep everything in one place, and we can re-open here if it turns out not to be something Flutter related.

**Closed by DanTup** 2021-05-07 17:31 UTC
Labels: awaiting info, is bug

**Comment by azwalzaman** [comment] 2021-05-07 18:41
Oh yeah I saw another issue where snap was the problem and unintalled the flutter snap package and chrome snap package. I then manually installed flutter and used a deb package for chrome. I still had the same issue

**Comment by azwalzaman** [comment] 2021-05-08 06:50
Uninstalling snap vscode and installing apt vs code fixed it

**Comment by DanTup** [comment] 2021-05-10 09:20
@azwalzaman could you confirm (in reply to https://github.com/flutter/flutter/issues/73743) whether your Chrome was also installed via Snap or not? (and if not and you're able to easily test whether that also fixes it when using the VS Code Snap, that may be interesting to know). Please reply in https://github.com/flutter/flutter/issues/73743 to keep the discussion together. Thanks!
