### ISSUE TITLE
Support for debugging add-to-app flutter app

### ISSUE THREAD

**Issue by LinusU** [Dart-Code/Dart-Code#1669] opened 2019-04-30 14:23 UTC
I've switched my app to be the [add-to-app](https://github.com/flutter/flutter/wiki/Add-Flutter-to-existing-apps) setup in order to better support app extensions on the iOS platform. While this is working great, and it's nice to have full control over the Xcode Project generation, the drawback is that I can no longer start/debug the app from VS Code.

Would it be possible to add a new debug configuration for starting a custom app and connecting to that one?

I imagine it would look something like this:

```json
{
  "name": "Flutter",
  "request": "launch-custom",
  "type": "dart",
  "xcworkspace": "ios/MyApp.xcworkspace",
  "xcscheme": "MyApp"
}
```

**Comment by DanTup** [comment] 2019-04-30 14:33
@LinusU you should be able to do this today by running the "Dart: Attach to Flutter process" command (or by setting `request` to `attach` in `launch.json`):

<img width="402" alt="Screenshot 2019-04-30 at 3 31 32 pm" src="https://user-images.githubusercontent.com/1078012/56969441-129e3700-6b5d-11e9-8690-a56cd4f5efc6.png">

For now, you need to run that command before your app loads the Flutter view (since it watches the logs to get the VM service URI).

There's some more info in the release notes here:

https://dartcode.org/releases/v2-19/#flutter-attach

Let me know if this works for you (and if not, feel free to file bugs or suggestions for it) :-)

**Comment by LinusU** [comment] 2019-04-30 14:39
I was actually going to file a separate issue about my problems with "Attach to Flutter Process", for some reason it isn't working even though I can get `flutter attach` from the CLI to work. I'll do some more testing to further document exactly what is going wrong though.

That being said, I would still like it if VS Code could also build and start the app for me, is this a valid feature request, or is it out of scope? ☺️ 

-----

> For now, you need to run that command before your app loads the Flutter view (since it watches the logs to get the VM service URI).

It prompts me for the Observatory URL, so it seems like I have to start the app first? But once I paste it in it seems like it's connected, but hot reload, hot restart, etc. doesn't seem to be working...

**Comment by DanTup** [comment] 2019-04-30 14:45
> That being said, I would still like it if VS Code could also build and start the app for me, is this a valid feature request, or is it out of scope?

I don't know exactly how it needs to be launched, but since the VS Code extensions are for Dart + Flutter, I think starting to build in and maintain the knowledge for launching native iOS apps is out of scope (and would likely result in expectations to do the same for Android, and potentially other platforms in future).

That said, you may be able to get some of the way yourself - for example in launch.json you can add a `"preLaunchTask"` and you can then define tasks in `tasks.json` that can call shell commands.

For example, see:

https://github.com/flutter/devtools/blob/master/packages/devtools/.vscode/launch.json#L10

and:

https://github.com/flutter/devtools/blob/master/packages/devtools/.vscode/tasks.json#L7

This shows using a task in a launch config, and also how to define shell tasks (in this case, the task in launch.json is not one defined in tasks.json, but it could be).


> It prompts me for the Observatory URL

Have you opened the Flutter project as the (a) main workspace root folder? Does your status bar show a Flutter version? This sounds like it thinks your project is Dart and not Flutter.

**Comment by LinusU** [comment] 2019-04-30 14:52
> I think starting to build in and maintain the knowledge for launching native iOS apps is out of scope

Yeah, that might make sense 🤔 

> That said, you may be able to get some of the way yourself - for example in launch.json you can add a "preLaunchTask" and you can then define tasks in tasks.json that can call shell commands.

Ah, maybe this is the way to go! Thanks for the links!

> Have you opened the Flutter project as the (a) main workspace root folder?

Hmm, maybe not. I've opened a folder with a `flutter` and `ios` folder. The flutter root thus is in `{workspace_root}/flutter`, should that work? 🤔 

> Does your status bar show a Flutter version? This sounds like it thinks your project is Dart and not Flutter.

It does:

<img width="409" alt="Screenshot 2019-04-30 at 15 50 03" src="https://user-images.githubusercontent.com/189580/56970706-a1ac4e80-6b5f-11e9-9c81-6cf5ffd15ef7.png">

Thanks for the help ❤️

**Comment by LinusU** [comment] 2019-04-30 15:02
> Hmm, maybe not. I've opened a folder with [...]

This was the problem, using [multi-root workspaces](https://code.visualstudio.com/docs/editor/multi-root-workspaces) solved this part.

Now I get this error when trying to attach to a flutter process though:

```text
Checking for advertised Dart observatories...
Unhandled exception:
FormatException: Bad UTF-8 encoding 0xc (at offset 22)
#0      _Utf8Decoder.convert (dart:convert/utf.dart:444:15)
#1      Utf8Decoder.convert (dart:convert/utf.dart:327:13)
#2      Utf8Codec.decode (dart:convert/utf.dart:59:56)
#3      _readFQDN (package:multicast_dns/src/packet.dart:165:24)
#4      decodeMDnsResponse.readResourceRecord (package:multicast_dns/src/packet.dart:240:36)
#5      decodeMDnsResponse (package:multicast_dns/src/packet.dart:350:55)
#6      MDnsClient._handleIncoming (package:multicast_dns/multicast_dns.dart:194:45)
#7      _rootRunUnary (dart:async/zone.dart:1136:13)
#8      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#9      _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#10     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#11     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#12     _SyncStreamController._sendData (dart:async/stream_controller.dart:764:19)
#13     _StreamController._add (dart:async/stream_controller.dart:640:7)
#14     _StreamController.add (dart:async/stream_controller.dart:586:5)
#15     new _RawDatagramSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1859:33)
#16     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:844:14)
#17     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#18     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#19     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:115:13)
#20     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:5)

Exited (255)
```

Please let me know if this is not the appropriate place to report this ☺️

**Comment by LinusU** [comment] 2019-04-30 16:05
The error doesn't seem related to the VS Code extension: https://github.com/flutter/flutter/issues/31854

The reason `flutter attach` worked before is probably because I was on a different network...

**Comment by DanTup** [comment] 2019-04-30 16:28
> Hmm, maybe not. I've opened a folder with a `flutter` and `ios` folder. The flutter root thus is in `{workspace_root}/flutter`, should that work? 🤔

Sort-of :)

The problem here is that because you're attaching (and not launching), we don't know what part of your workspace is the project. I think if you create a `launch.json` and set the `cwd` to point at the `flutter` folder, probably that will fix it (since then we'd spot that it contained a `pubspec` that references the Flutter SDK).

To avoid confusion, if that doesn't work - open a new issue with the details, and include a log (run `Dart: Capture Logs`, then run the attach command, then when it asks for Observatory URI, cancel it and click Stop Logging).

The other issue does look like a Flutter bug. I think the method for finding the Observatory URI is being changed to use mDNS (which should mean doing things in a specific order will not be required), but seems there's something wrong with it. If you're on `master`, you might be able to avoid it by switching to something like `beta` temporarily.

I don't think there's anything else for this issue so I'll close it but feel free to post back on it if you have any questions about the above (for ex. if you can't get the tasks/launch.json stuff working) and I'll try to help out.

Thanks!

**Closed by DanTup** 2019-04-30 16:28 UTC
Labels: awaiting info

**Comment by wickedman1976** [comment] 2019-07-23 06:51
Thanks for all your hard work so far.

I can attach to the ios project and works as expected. 

However I don't see any debug logs from flutter. Is that expected behaviour? 

This is in vscode and debug attach to process. It waits correctly for ios debugger to launch.

**Comment by DanTup** [comment] 2019-07-23 07:00
> However I don't see any debug logs from flutter. Is that expected behaviour?

I guess when we attach we don't have access to the `stdout` of the process, so anything that should usually go there would not be found.

I don't know if there may be an alternative way to get at this stream though, so please open an issue and I can take a look.

That said, if you want to try the next beta version (https://github.com/Dart-Code/Dart-Code/releases/tag/v3.3.0-beta.3), you can use `dart:developer`'s `log()` function, and that should show up in the debug console whether you launched or attached.

**Comment by wickedman1976** [comment] 2019-07-23 08:17
Thank you.

I have downloaded the beta, in order to use the log function.  I assume I need to add import 'dart:developer'; at the top of the file?

The idea does not seem to recognise the log function.  Are there any examples around?

**Comment by wickedman1976** [comment] 2019-07-23 08:19
Ignore that, I had to reboot VSCode

**Comment by DanTup** [comment] 2019-07-23 08:23
You shouldn't have needed to restart VS Code, though glad it's working now :-)
