### ISSUE TITLE
Breaking change in how breakpoints are handled by the debugger

### ISSUE THREAD

**Issue by hermanbergwerf** [Dart-Code/Dart-Code#334] opened 2017-06-22 19:55 UTC
See: https://github.com/dart-lang/sdk/issues/29988. I noticed that with dart 1.25.0-dev.1.0 the debugger did not pause at all breakpoints (in particular some inside a closure, where I did not experience any issues previously). It seems that something was updated in the SDK and something has to be fixed in this plugin.

**Comment by DanTup** [comment] 2017-06-23 09:57
I'm struggling to reproduce this; I've got this:

```dart
main() {
  print(getThing().length);
}

getThing() {
  var result = [1, 2, 3, 4];
  return result.map((v) => v / 2).toList();
}
```

I'm putting a breakpoint on the `map` line and it always gets hit. I'm using `v.1.25.0-dev.2.1`. Are you able to make a simple repro?

**Comment by hermanbergwerf** [comment] 2017-06-23 11:36
It took me some tries to reproduce this as well, but this reproduces the bug:

```
lib/src/test.dart
```
```dart
```

```
lib/test.dart
```
```dart
```
```
test/test.dart
```
```dart
```
(it doesn't work without the `part of`)

**Comment by DanTup** [comment] 2017-06-23 13:19
@hermanbergwerf Perfect; I can repro with these files. I'll investigate!

**Comment by DanTup** [comment] 2017-06-23 13:34
Ok, I ran this same test in 1.24 and 1.25 and found this..

We currently send breakpoints *twice* because we previously found that depending on how a file was imported, the debugger would not break on it (some discussion in #134). So the requesyt to add breakpoints looks like this:

```text
==> {"id":"5","method":"addBreakpointWithScriptUri","params":{"isolateId":"isolates/11111111","scriptUri":"file:///c:/Users/danny/Desktop/DartDebugSample/lib/src/test.dart","line":4}}
==> {"id":"6","method":"addBreakpointWithScriptUri","params":{"isolateId":"isolates/11111111","scriptUri":"package:yourpackage/src/test.dart","line":4}}
```

In 1.24, both of these breakpoints are accepted:

```text
<== {"jsonrpc":"2.0", "result":{"type":"Breakpoint","fixedId":true,"id":"breakpoints\/1","breakpointNumber":1,"resolved":false,"location":{"type":"UnresolvedSourceLocation","scriptUri":"file:\/\/\/c:\/Users\/danny\/Desktop\/DartDebugSample\/lib\/src\/test.dart","line":4}},"id":"5"}
<== {"jsonrpc":"2.0", "result":{"type":"Breakpoint","fixedId":true,"id":"breakpoints\/2","breakpointNumber":2,"resolved":false,"location":{"type":"UnresolvedSourceLocation","script":{"type":"@Script","fixedId":true,"id":"libraries\/@17134453\/scripts\/package%3Ayourpackage%2Fsrc%2Ftest.dart\/15cd52126c7","uri":"package:yourpackage\/src\/test.dart","_kind":"source"},"line":4}},"id":"6"}
```

and when we go on to execute, we stop at the **second** breakpoint - the "package" version.

However, here's what happens in 1.25. We send the same requests:

```text
==> {"id":"5","method":"addBreakpointWithScriptUri","params":{"isolateId":"isolates/11111111","scriptUri":"file:///c:/Users/danny/Desktop/DartDebugSample/lib/src/test.dart","line":4}}
==> {"id":"6","method":"addBreakpointWithScriptUri","params":{"isolateId":"isolates/11111111","scriptUri":"package:yourpackage/src/test.dart","line":4}}
```

But here's the response:

```text
<== {"jsonrpc":"2.0", "result":{"type":"Breakpoint","fixedId":true,"id":"breakpoints\/1","breakpointNumber":1,"resolved":false,"location":{"type":"UnresolvedSourceLocation","scriptUri":"file:\/\/\/c:\/Users\/danny\/Desktop\/DartDebugSample\/lib\/src\/test.dart","line":4}},"id":"5"}
<== {"jsonrpc":"2.0", "error":{"code":102,"message":"Cannot add breakpoint","data":{"request":{"method":"addBreakpointWithScriptUri","params":{"isolateId":"isolates\/11111111","scriptUri":"package:yourpackage\/src\/test.dart","line":"4"}},"details":"addBreakpointWithScriptUri: Cannot add breakpoint at line '4'"}},"id":"6"}
```

Note that the second breakpoint (which is the one that breaks in 1.24) is the one being rejected.

So, I have no idea how to fix this - the breakpoint we can't set is the one that would actually work.

[DartDebugSample.zip](https://github.com/Dart-Code/Dart-Code/files/1097923/DartDebugSample.zip)

I'm gonna add this comment also to https://github.com/dart-lang/sdk/issues/29988 because I need input from Google on how this is supposed to work.

**Comment by DanTup** [comment] 2017-07-06 16:42
Looks like this has been fixed in Dart, so hopefully won't occur in any release SDKs.

**Closed by DanTup** 2017-07-06 16:42 UTC
Labels: area: debugger, bug, fixed externally: dart

**Comment by DanTup** [comment] 2017-07-13 19:02
This seems fixed in SDK .dev.6.0 :-)

**Comment by hermanbergwerf** [comment] 2017-07-30 07:00
Again having issues in `1.25.0-dev.8.0` :-(

**Comment by DanTup** [comment] 2017-07-30 07:25
I think it's best posting back in https://github.com/dart-lang/sdk/issues/29988 or raising a new case there with a sample. You can get a log like I posted above by setting the `"dart.observatoryLogFile"` setting to a file path/name, which should help track things down. Feel free to post it here for me to have a look before you raise an SDK issue if you want.

**Comment by hermanbergwerf** [comment] 2017-07-30 12:23
Alright, will look into this a bit.
Also loading the scope variables for anything but the top of the stack trace is not working.

**Comment by DanTup** [comment] 2017-07-31 10:53
@hermanbergwerf Using `dev.8.0` and performing the same steps on the above repro I hit the breakpoint fine. If you can provide new repro steps/sample I can take a look.

**Comment by hermanbergwerf** [comment] 2017-07-31 12:23
I tried as well, and had no issues with the previous repro. I am quite sure
I missed a breakpoint somewhere but I cannot find/reproduce it now. Will
post back if I find something :-)

Op ma 31 jul. 2017 om 18:53 schreef Danny Tuppeny <notifications@github.com

**Comment by DanTup** [comment] 2017-07-31 13:27
@hermanbergwerf I'm just investigating an issue with breakpoints not being hit that may or may not be related - see #398. I think I know the cause and fix, but not why it's never been noticed before!

**Comment by hermanbergwerf** [comment] 2017-07-31 15:46
The number of developers effectively using breakpoints might be quite low,
especially for Dart. I struggled with print/printf/console.log for years
because no one had told me I should use breakpoints haha. Maybe people have
noticed and not reported though.
