### ISSUE TITLE
Use completion commit characters so `(` is only inserted when used to commit

### ISSUE THREAD

**Issue by vogella** [Dart-Code/Dart-Code#2125] opened 2019-11-25 12:33 UTC
If I code complete on "_saySomething" I get _saySomething() which the compiler immediately complains about.

```dart
    return AppBar(
          title: Text("Super application"),
          actions: [
            IconButton(
              icon: Icon(Icons.access_alarm),
              onPressed: _saySomething,
            )
          ],
        );
  }
 void _saySomething() {
    print("pressed");
  }

```

**Comment by DanTup** [comment] 2019-11-26 10:45
This is essentially a dupe of #687. We don't really have the context to know when a user is completing a function of whether it'll be correct to include parens on the end. The ideal solution IMO is that we never insert the parens, but if you're calling the function then you use the `(` key to commit the completion (which would also insert it, and the closing one).

This is possible if you disable `insertArgumentPlaceholders` and turn on `completionCommitCharacters`, however there are other quirks in that behaviour which may make it worse (ultimately, I think that should be the end goal though).

I'll leave this open as a reminder that this still sucks (since the other issue is closed) and I'll try to work through the remaining issues that make using commit characters bad (or at least document the specifics).

**Comment by DanTup** [comment] 2020-09-22 13:24
I've added a preview flag to enable these when using LSP, though in my current testing it doesn't seem to be working. I've opened https://github.com/microsoft/vscode-languageserver-node/issues/673.

**Comment by DanTup** [comment] 2020-10-21 16:32
With https://dart-review.googlesource.com/c/sdk/+/168653/, this is supported in LSP with the `dart.previewCommitCharacters` setting. I've opened https://github.com/Dart-Code/Dart-Code/issues/2895 as a reminder to enable it by-default in a future release.

**Closed by DanTup** 2020-10-21 16:33 UTC
Labels: in editor, in lsp/analysis server, is bug
