### ISSUE TITLE
Flutter fix in VScode

### ISSUE THREAD

**Issue by Karlooie** [Dart-Code/Dart-Code#3186] opened 2021-03-08 09:00 UTC
The new feature "Flutter Fix" is not working or at least not showing fixes for deprecated expressions.

with Flutter 2, expected behaviour of the new feature:
https://flutter.dev/docs/development/tools/flutter-fix
![image](https://user-images.githubusercontent.com/10740439/110297931-41f11b00-7ff4-11eb-97ce-e53523d138d5.png)

how it appears to me:
![image](https://user-images.githubusercontent.com/10740439/110298038-664cf780-7ff4-11eb-849f-794ae9eba48b.png)

versions (flutter doctor output):

[√] Flutter (Channel stable, 2.0.0, on Microsoft Windows [Version 10.0.19041.804], locale en-GB)
• Flutter version 2.0.0 at C:\src\flutter
• Framework revision 60bd88d (4 days ago), 2021-03-03 09:13:17 -0800
• Engine revision 40441def69
• Dart version 2.12.0

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
• Android SDK at C:\Users\carlo\AppData\Local\Android\Sdk
• Platform android-29, build-tools 29.0.3
• ANDROID_HOME = C:\Users\carlo\AppData\Local\Android\Sdk
• Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
• Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
• All Android licenses accepted.

[√] Android Studio (version 3.6)
• Android Studio at C:\Program Files\Android\Android Studio
• Flutter plugin version 44.0.2
• Dart plugin version 192.7761
• Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] VS Code (version 1.54.1)
• VS Code at C:\Users\carlo\AppData\Local\Programs\Microsoft VS Code
• Flutter extension version 3.20.0

Suggested to move here from flutter repository: [https://github.com/flutter/flutter/issues/77504](https://github.com/flutter/flutter/issues/77504)

**Comment by DanTup** [comment] 2021-03-08 10:03
I've not been able to reproduce this - it seems to work on Flutter 2.0 here:

<img width="860" alt="Screenshot 2021-03-08 at 10 01 40" src="https://user-images.githubusercontent.com/1078012/110306061-4cf87b00-7ff5-11eb-9cc5-0572995d8362.png">

Can you confirm in the status bar of VS Code you also see "Flutter 2.0.0" and it's not picking up another version?

If it is 2.0, could you try in a new project (created with the **Flutter: New Application Project** command)? If it happens there too, please try capturing a log (in the newly created project):

- Run the **Dart: capture Analysis Server Logs** command
- Invoke the lightbulb menu
- Click **Cancel** on the logging prompt to stop logging and open the log file
- Attach the log here

Thanks!

**Comment by Karlooie** [comment] 2021-03-08 13:47
Thank you @DanTup !

 In a clean new project it's working as expected.
Both projects in VSCode display "Flutter 2.0.0"

Old project was created more than a year ago, was upgraded to flutter 2.0 from: 

```
Flutter (Channel stable, v1.12.13+hotfix.8, on Microsoft Windows [Version 10.0.19041.804], locale en-GB)
    • Flutter version 1.12.13+hotfix.8 at C:\src\flutter
    • Framework revision 0b8abb4724 (1 year, 1 month ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0
```

I closed and opened the IDE a few times... I'm not sure where to check for differences between the two projects...


Dart Server Log in NOT working project:
```
Dart Code extension: 3.20.1
Flutter extension: 3.20.0 (activated)

App: Visual Studio Code
Version: 1.54.1
Platform: win

Workspace type: Flutter
Analyzer type: DAS
Multi-root?: false

Dart SDK:
    Loc: C:\src\flutter\bin\cache\dart-sdk
    Ver: 2.12.0
Flutter SDK:
    Loc: C:\src\flutter
    Ver: 2.0.0

HTTP_PROXY: undefined
NO_PROXY: undefined

Logging Categories:
    General, Analyzer, CommandProcesses

Mon Mar 08 2021 [14:26:09 GMT+0100 (Central European Standard Time)] Log file started
[14:26:12] [Analyzer] [Info] ==> {"id":"118","method":"edit.getFixes","params":{"file":"C:\\Users\\carlo\\Dropbox\\flutter\\hello_blue2\\lib\\mainScreen.dart","offset":9367},"clientRequestTime":1615209972565}
[14:26:12] [Analyzer] [Info] ==> {"id":"119","method":"edit.getAssists","params":{"file":"C:\\Users\\carlo\\Dropbox\\flutter\\hello_blue2\\lib\\mainScreen.dart","length":0,"offset":9367},"clientRequestTime":1615209972566}
[14:26:12] [Analyzer] [Info] ==> {"id":"120","method":"edit.getAvailableRefactorings","params":{"file":"C:\\Users\\carlo\\Dropbox\\flutter\\hello_blue2\\lib\\mainScreen.dart","length":0,"offset":9367},"clientRequestTime":1615209972566}
[14:26:12] [Analyzer] [Info] <== {"id":"118","result":{"fixes":[]}}
[14:26:12] [Analyzer] [Info] <== {"id":"120","result":{"kinds":["EXTRACT_LOCAL_VARIABLE","EXTRACT_METHOD"]}}
[14:26:12] [Analyzer] [Info] <== {"id":"119","result":{"assists":[{"message":"Wrap with widget...","edits":[{"file":"C:\\Users\\carlo\\Dropbox\\flutter\\hello_blue2\\lib\\mainScreen.dart","fileStamp":0,"edits":[{"offset":9309,"length":213,"replacement":"[\r\n            widget(\r\n              children: <Widget>[\r\n                Stack(overflow: Overflow.visible,),\r\n                VolumeButton(CMD.volUp),\r\n                VolumeButton(CMD.volDown),\r\n                VolumeButton(CMD.volMute),\r\n                GyroVol(),\r\n              ],\r\n            ),\r\n          ]"}]}],"linkedEditGroups":[{"positions":[{"file":"C:\\Users\\carlo\\Dropbox\\flutter\\hello_blue2\\lib\\mainScreen.dart","offset":9324}],"length":6,"suggestions":[]}],"id":"dart.assist.flutter.wrap.generic"}]}}
[14:26:14] [Analyzer] [Info] ==> {"id":"121","method":"analysis.getHover","params":{"file":"C:\\Users\\carlo\\Dropbox\\flutter\\hello_blue2\\lib\\mainScreen.dart","offset":9342},"clientRequestTime":1615209974295}
[14:26:14] [Analyzer] [Info] <== {"id":"121","result":{"hovers":[{"offset":9338,"length":8,"dartdoc":"Whether overflowing children should be clipped. See [Overflow].\n\nSome children in a stack might overflow its box. When this flag is set to\n[Overflow.clip], children cannot paint outside of the stack's box.\n\nWhen set to [Overflow.visible], the visible overflow area will not accept\nhit testing.\n\nThis overrides [clipBehavior] for now due to a staged roll out.\nWe will remove it and only use [clipBehavior] soon.\n\nDeprecated. Use [clipBehavior] instead.","elementDescription":"{Overflow overflow = Overflow.clip}","elementKind":"parameter","isDeprecated":true,"staticType":"Overflow"}]}}
[14:26:14] [Analyzer] [Info] ==> {"id":"122","method":"edit.getFixes","params":{"file":"C:\\Users\\carlo\\Dropbox\\flutter\\hello_blue2\\lib\\mainScreen.dart","offset":9338},"clientRequestTime":1615209974480}
[14:26:14] [Analyzer] [Info] <== {"id":"122","result":{"fixes":[]}}
[14:26:18] [Analyzer] [Info] ==> {"id":"123","method":"analysis.getHover","params":{"file":"C:\\Users\\carlo\\Dropbox\\flutter\\hello_blue2\\lib\\mainScreen.dart","offset":9329},"clientRequestTime":1615209978110}
[14:26:18] [Analyzer] [Info] <== {"id":"123","result":{"hovers":[{"offset":9309,"length":213,"staticType":"List<Widget>"}]}}
Mon Mar 08 2021 [14:26:25 GMT+0100 (Central European Standard Time)] Log file ended
```


log in working clean project:
```

!! PLEASE REVIEW THIS LOG FOR SENSITIVE INFORMATION BEFORE SHARING !!

Dart Code extension: 3.20.1
Flutter extension: 3.20.0 (activated)

App: Visual Studio Code
Version: 1.54.1
Platform: win

Workspace type: Flutter
Analyzer type: DAS
Multi-root?: false

Dart SDK:
    Loc: C:\src\flutter\bin\cache\dart-sdk
    Ver: 2.12.0
Flutter SDK:
    Loc: C:\src\flutter
    Ver: 2.0.0

HTTP_PROXY: undefined
NO_PROXY: undefined

Logging Categories:
    General, Analyzer, CommandProcesses

Mon Mar 08 2021 [14:24:02 GMT+0100 (Central European Standard Time)] Log file started
[14:24:05] [Analyzer] [Info] ==> {"id":"47","method":"edit.getFixes","params":{"file":"C:\\Users\\carlo\\GoogleDrive\\CARLO\\test_flutter_fix\\test_fix\\lib\\main.dart","offset":4027},"clientRequestTime":1615209845135}
[14:24:05] [Analyzer] [Info] ==> {"id":"48","method":"edit.getAssists","params":{"file":"C:\\Users\\carlo\\GoogleDrive\\CARLO\\test_flutter_fix\\test_fix\\lib\\main.dart","length":0,"offset":4027},"clientRequestTime":1615209845136}
[14:24:05] [Analyzer] [Info] ==> {"id":"49","method":"edit.getAvailableRefactorings","params":{"file":"C:\\Users\\carlo\\GoogleDrive\\CARLO\\test_flutter_fix\\test_fix\\lib\\main.dart","length":0,"offset":4027},"clientRequestTime":1615209845136}
[14:24:05] [Analyzer] [Info] <== {"id":"47","result":{"fixes":[{"error":{"severity":"INFO","type":"HINT","location":{"file":"C:\\Users\\carlo\\GoogleDrive\\CARLO\\test_flutter_fix\\test_fix\\lib\\main.dart","offset":3999,"length":8,"startLine":96,"startColumn":19},"message":"'overflow' is deprecated and shouldn't be used. Use clipBehavior instead. See the migration guide in flutter.dev/go/clip-behavior. This feature was deprecated after v1.22.0-12.0.pre..","correction":"Try replacing the use of the deprecated member with the replacement.","code":"deprecated_member_use","url":"https://dart.dev/tools/diagnostic-messages#deprecated_member_use","hasFix":false},"fixes":[{"message":"Migrate to clipBehavior","edits":[{"file":"C:\\Users\\carlo\\GoogleDrive\\CARLO\\test_flutter_fix\\test_fix\\lib\\main.dart","fileStamp":0,"edits":[{"offset":4025,"length":0,"replacement":"clipBehavior: Clip.none"},{"offset":3999,"length":26,"replacement":""}]}],"linkedEditGroups":[],"id":"dart.fix.dataDriven"}]}]}}
[14:24:05] [Analyzer] [Info] <== {"id":"49","result":{"kinds":["EXTRACT_LOCAL_VARIABLE","EXTRACT_METHOD"]}}
[14:24:05] [Analyzer] [Info] <== {"id":"48","result":{"assists":[{"message":"Wrap with widget...","edits":[{"file":"C:\\Users\\carlo\\GoogleDrive\\CARLO\\test_flutter_fix\\test_fix\\lib\\main.dart","fileStamp":0,"edits":[{"offset":3970,"length":291,"replacement":"[\r\n            widget(\r\n              children: <Widget>[\r\n                Stack(overflow: Overflow.visible),\r\n                Text(\r\n                  'You have pushed the button this many times:',\r\n                ),\r\n                Text(\r\n                  '$_counter',\r\n                  style: Theme.of(context).textTheme.headline4,\r\n                ),\r\n              ],\r\n            ),\r\n          ]"}]}],"linkedEditGroups":[{"positions":[{"file":"C:\\Users\\carlo\\GoogleDrive\\CARLO\\test_flutter_fix\\test_fix\\lib\\main.dart","offset":3985}],"length":6,"suggestions":[]}],"id":"dart.assist.flutter.wrap.generic"}]}}
[14:24:06] [Analyzer] [Info] ==> {"id":"50","method":"analysis.getHover","params":{"file":"C:\\Users\\carlo\\GoogleDrive\\CARLO\\test_flutter_fix\\test_fix\\lib\\main.dart","offset":4006},"clientRequestTime":1615209846467}
[14:24:06] [Analyzer] [Info] ==> {"id":"51","method":"analysis.getHover","params":{"file":"C:\\Users\\carlo\\GoogleDrive\\CARLO\\test_flutter_fix\\test_fix\\lib\\main.dart","offset":4004},"clientRequestTime":1615209846780}
[14:24:06] [Analyzer] [Info] <== {"id":"50","result":{"hovers":[{"offset":3999,"length":8,"dartdoc":"Whether overflowing children should be clipped. See [Overflow].\n\nSome children in a stack might overflow its box. When this flag is set to\n[Overflow.clip], children cannot paint outside of the stack's box.\n\nWhen set to [Overflow.visible], the visible overflow area will not accept\nhit testing.\n\nThis overrides [clipBehavior] for now due to a staged roll out.\nWe will remove it and only use [clipBehavior] soon.\n\nDeprecated. Use [clipBehavior] instead.","elementDescription":"{Overflow overflow = Overflow.clip}","elementKind":"parameter","isDeprecated":true,"staticType":"Overflow"}]}}
[14:24:06] [Analyzer] [Info] <== {"id":"51","result":{"hovers":[{"offset":3999,"length":8,"dartdoc":"Whether overflowing children should be clipped. See [Overflow].\n\nSome children in a stack might overflow its box. When this flag is set to\n[Overflow.clip], children cannot paint outside of the stack's box.\n\nWhen set to [Overflow.visible], the visible overflow area will not accept\nhit testing.\n\nThis overrides [clipBehavior] for now due to a staged roll out.\nWe will remove it and only use [clipBehavior] soon.\n\nDeprecated. Use [clipBehavior] instead.","elementDescription":"{Overflow overflow = Overflow.clip}","elementKind":"parameter","isDeprecated":true,"staticType":"Overflow"}]}}
[14:24:07] [Analyzer] [Info] ==> {"id":"52","method":"edit.getFixes","params":{"file":"C:\\Users\\carlo\\GoogleDrive\\CARLO\\test_flutter_fix\\test_fix\\lib\\main.dart","offset":3999},"clientRequestTime":1615209847016}
[14:24:07] [Analyzer] [Info] <== {"id":"52","result":{"fixes":[{"error":{"severity":"INFO","type":"HINT","location":{"file":"C:\\Users\\carlo\\GoogleDrive\\CARLO\\test_flutter_fix\\test_fix\\lib\\main.dart","offset":3999,"length":8,"startLine":96,"startColumn":19},"message":"'overflow' is deprecated and shouldn't be used. Use clipBehavior instead. See the migration guide in flutter.dev/go/clip-behavior. This feature was deprecated after v1.22.0-12.0.pre..","correction":"Try replacing the use of the deprecated member with the replacement.","code":"deprecated_member_use","url":"https://dart.dev/tools/diagnostic-messages#deprecated_member_use","hasFix":false},"fixes":[{"message":"Migrate to clipBehavior","edits":[{"file":"C:\\Users\\carlo\\GoogleDrive\\CARLO\\test_flutter_fix\\test_fix\\lib\\main.dart","fileStamp":0,"edits":[{"offset":4025,"length":0,"replacement":"clipBehavior: Clip.none"},{"offset":3999,"length":26,"replacement":""}]}],"linkedEditGroups":[],"id":"dart.fix.dataDriven"}]}]}}
[14:24:09] [Analyzer] [Info] ==> {"id":"53","method":"analysis.getHover","params":{"file":"C:\\Users\\carlo\\GoogleDrive\\CARLO\\test_flutter_fix\\test_fix\\lib\\main.dart","offset":3984},"clientRequestTime":1615209849639}
[14:24:09] [Analyzer] [Info] <== {"id":"53","result":{"hovers":[{"offset":3970,"length":291,"staticType":"List<Widget>"}]}}
[14:24:09] [Analyzer] [Info] ==> {"id":"54","method":"analysis.getHover","params":{"file":"C:\\Users\\carlo\\GoogleDrive\\CARLO\\test_flutter_fix\\test_fix\\lib\\main.dart","offset":3983},"clientRequestTime":1615209849944}
[14:24:09] [Analyzer] [Info] <== {"id":"54","result":{"hovers":[{"offset":3970,"length":291,"staticType":"List<Widget>"}]}}
Mon Mar 08 2021 [14:24:18 GMT+0100 (Central European Standard Time)] Log file ended

```

**Comment by DanTup** [comment] 2021-03-08 14:09
I'm not sure what's going on there. Does running the `Flutter: Clean Project` command and then `Flutter: Get Packages` make any difference?

Is the related code in the new project exactly the same as in the main project?

**Comment by Karlooie** [comment] 2021-03-08 14:28
No, the code is not the same. Sorry, I was testing on a clean new project just adding a line with Overflow.

I'm testing now with copying various part of the project into the new one, I'll get back soon

**Comment by Karlooie** [comment] 2021-03-08 14:58
I created various new project and having it working only sometimes, you were right to look in the actual code!
Long story short:

when I have a trailing comma and overflow: is the only parameter, the migration is not showing, when I remove the comma or there are other parameters, it's showing. Can you check if you can reproduce?
![image](https://user-images.githubusercontent.com/10740439/110337804-9ad9a700-8026-11eb-816e-818c319c3f0a.png)
![image](https://user-images.githubusercontent.com/10740439/110337891-afb63a80-8026-11eb-9951-e155a3c16c08.png)
![image](https://user-images.githubusercontent.com/10740439/110338128-f4da6c80-8026-11eb-8134-eb5fc6e0ea30.png)

Thankyou!!

**Comment by Karlooie** [comment] 2021-03-08 15:21
@llh-him can you check on your side if something similar is happening?

**Comment by jobi-li** [comment] 2021-03-08 15:49
> @llh-him can you check on your side if something similar is happening?

Nope, still can't get the migrate option.

Actually, would the flutter fix works with a deprecated widget? In my situation, I need to migrate the "FlatButton" widget.

![Screenshot 2021-03-08 at 23 49 20](https://user-images.githubusercontent.com/69352414/110344894-f0cf3e80-8068-11eb-9564-60e3f8efe83f.png)

**Comment by llh-him** [comment] 2021-03-08 15:51
> > @llh-him can you check on your side if something similar is happening?
> 
> Nope, still can't get the migrate option.
> 
> Actually, would the flutter fix works with a deprecated widget? In my situation, I need to migrate the "FlatButton" widget.
> 
> ![Screenshot 2021-03-08 at 23 49 20](https://user-images.githubusercontent.com/69352414/110344894-f0cf3e80-8068-11eb-9564-60e3f8efe83f.png)

@Karlooie Sorry, I just used another account to reply.

**Comment by DanTup** [comment] 2021-03-08 16:02
@Karlooie yes, I can repro! Thanks for figuring it out. It looks like an analysis server issue to me, so I've filed it over in the SDK repo https://github.com/dart-lang/sdk/issues/45242. Please subscribe there for updates and I'll close this as a dupe.

> Actually, would the flutter fix works with a deprecated widget? In my situation, I need to migrate the `FlatButton` widget.

The fixes have to be created specifically (see https://github.com/flutter/flutter/blob/master/packages/flutter/lib/fix_data.yaml). As far as I can tell, there is not currently a fix for migrating from `FlatButton`.

**Closed** 2021-03-08 16:05 UTC
Labels: upstream in dart / flutter

**Comment by Karlooie** [comment] 2021-03-08 17:49
Perfect, thank you!
