### ISSUE TITLE
Support running fixes coming from analyzer plugins on-save / via Fix All command

### ISSUE THREAD

**Issue by roman-petrov** [Dart-Code/Dart-Code#3575] opened 2021-09-22 10:22 UTC
**Is your feature request related to a problem? Please describe.**
There is a great feature released in Dart Code 3.25 - [fix all command](https://dartcode.org/releases/v3-25/#fix-all-command). It is working perfectly for built-in Dart fixes but unfortunately doesn't work for [dart-code-metrics](https://github.com/dart-code-checker/dart-code-metrics) fixes. 

So when I save the file - all dart fixes are applied automatically, but I need to manually apply `dart-code-metrics` fixes by clicking a light bulb and choosing (usually) the first quick fix for each issue.

**Describe the solution you'd like**
It would be great to have the ability to automatically apply fixes comping from plugins (maybe, additional configuration option will be required?).

**Describe alternatives you've considered**
I do not see any alternatives at the moment.

**Additional context**
Dart code metrics currently provides fixes to analyzer as analyzer plugin `PrioritizedSourceChange / SourceChange / SourceFileEdit / SourceEdit` objects, the implementation [can be found here](https://github.com/dart-code-checker/dart-code-metrics/blob/master/lib/src/analyzer_plugin/analyzer_plugin_utils.dart#L39). Maybe there is something that can be changed in dart code metrics to make automatic fixes work?

**Comment by DanTup** [comment] 2021-09-22 10:34
Thanks for the request! This requires some support from the Dart analyzer. There's an existing issue in the SDK you can 👍 's here:

https://github.com/dart-lang/sdk/issues/46760

If support is added there, and the dart-metrics plugin updated to support it, then it should just automatically work here (the Fix All command here does the same as running "dart fix", albeit just for the current file).

I'll close this as a dupe of that - but if it turns out the server supports it in a way that requires changes here, we can re-open this and make any necessary changes. Thanks!

**Closed** 2021-09-22 10:34 UTC
Labels: upstream in dart / flutter

**Comment by roman-petrov** [comment] 2021-09-22 10:47
@DanTup , sorry, I didn't notice that a duplicate issue already exists, and thank you for your great support!

**Comment by DanTup** [comment] 2021-09-22 10:53
No worries - that issue is in the SDK repo and it's not always obvious where things belong, so dupes are somewhat inevitable :-)
