### ISSUE TITLE
Edge和Chrome Flutter Web调试报错

### ISSUE THREAD

**Issue by mzhitech** [Dart-Code/Dart-Code#4174] opened 2022-09-23 16:21 UTC
Flutter assets will be downloaded from https://storage.flutter-io.cn. Make sure you trust this source!
Launching lib\main.dart on Chrome in debug mode...
lib\main.dart:1
Failed to bind web development server:
SocketException: Failed to create server socket (OS Error: Failed to start accept), address = localhost, port = 53446
#0      _NativeSocket.bind (dart:io-patch/socket_patch.dart:996:7)
<asynchronous suspension>
#1      WebAssetServer.start (package:flutter_tools/src/isolated/devfs_web.dart:208:22)
<asynchronous suspension>
#2      WebDevFS.create (package:flutter_tools/src/isolated/devfs_web.dart:739:22)
<asynchronous suspension>
#3      ResidentWebRunner.run.<anonymous closure> (package:flutter_tools/src/isolated/resident_web_runner.dart:281:25)
<asynchronous suspension>
#4      asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:24)
<asynchronous suspension>
2

Failed to bind web development server:
SocketException: Failed to create server socket (OS Error: Failed to start accept), address = localhost, port = 53446
Exited (sigterm)

**Please complete the following information:**
 - Operating System and version:**Windows 11 22h2**
 - VS Code version:**1.71.2**
 - Dart/Flutter SDK version:**3.3.2**

**Comment by DanTup** [comment] 2022-09-24 16:24
Do you see the same problem if you run `flutter run -d chrome` from a terminal?

If so, can you try whether the problem also occurs if you run `flutter run -d chrome --web-hostname=127.0.0.1` ?

**Comment by mzhitech** [comment] 2022-09-24 16:49
flutter run -d chrome，会看到相同问题
flutter run -d chrome --web-hostname=127.0.0.1，正常调试。

这到底是哪里的问题？之前没问题，更新完Windows后出现的

**Comment by DanTup** [comment] 2022-09-26 08:59
Thanks for confirming. I think the issue is IPv6 related. I think Flutter is using the host `localhost` which is resolving to an IPv6 address in your machine, but trying to find to the IPv6 address is causing the "Failed to create server socket (OS Error: Failed to start accept)" error.

I'm not sure why this happens, although a workaround would be to add `--web-hostname=127.0.0.1` to the `dart.flutterRunAdditionalArgs` setting:

- Run the **Preferences: Open User Settings (JSON)** command
- Add the following inside the JSON:
  ```
	"dart.flutterRunAdditionalArgs": [
		// Force 127.0.0.1 because "localhost" doesn't work if resolved to IPv6 loopback address
		"--web-hostname=127.0.0.1"
	],
  ```

This should resolve the issue when running from VS Code.

**Comment by DanTup** [comment] 2022-09-26 09:12
No problem. Did the solution work? Can we close this?

**Comment by mzhitech** [comment] 2022-09-26 09:12
关闭吧

**Closed** 2022-09-26 09:14 UTC
Labels: is bug, awaiting info
