### ISSUE TITLE
sigterm on nexus7

### ISSUE THREAD

**Issue by tsalinger** [Dart-Code/Dart-Code#690] opened 2018-03-14 06:13 UTC
>This issue has been moved from [Microsoft/vscode/](https://github.com/Microsoft/vscode/issues/45633#issuecomment-372775777)
Author is @petervrichards.
---
Issue Type: <b>Bug</b>

Bog standard first flutter app. get a sigterm

VS Code version: Code 1.21.0 (9a199d77c82fcb82f39c68bb33c614af01c111ba, 2018-03-07T11:04:09.969Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4600M CPU @ 2.90GHz (4 x 2893)|
|Memory (System)|15.43GB (6.79GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
dart-code|Dar|2.10.0
fs-flutter-snippets|fra|0.1.3

</details>
Reproduces only with extensions

---

>This is a reply from @tsalinger.

Please provide steps on how to reproduce this bug.
Also, which of your extensions is causing this?

---

>This is a reply from @petervrichards.

Sorry, I thought you got logs on this. 

I am using completely bog standard Windows 10 professional. 

Standard implementation of Flutter install. Visual Code + Flutter extensions. Flutter doctor - no errors. Using Android Emulator Nexus 7 API 23. 
First Flutter App - no changes. Flutter run - I get the sigterm when the app tries to transfer the app to the emulator. No errors from output. 
I cannot find Android API24 emulator available for download. 

peter richards 

---

>This is a reply from @petervrichards.

more info re sigterm 
Resolving dependencies... 26.7s 
Running 'gradlew assembleDebug'... 4.9s 
Built build\app\outputs\apk\debug\app-debug.apk (24.6MB). 
Installing build\app\outputs\apk\app.apk... 10.1s 
I/FlutterActivityDelegate( 1233): onResume setting current activity to this 
E/flutter ( 1233): [ERROR:flutter/shell/gpu/gpu_surface_gl.cc(39)] Failed to setup Skia Gr context. 
D/skia ( 1233): [SkFontMgr Android Parser] '/system/etc/fonts.xml' could not be opened 
D/skia ( 1233): [SkFontMgr Android Parser] '/vendor/etc/fallback_fonts.xml' could not be opened 
Syncing files to device Nexus 10 KitKat... 4.0s 
same as android emulator 
this is a Bliss emulator 
peter richards

**Comment by DanTup** [comment] 2018-03-14 07:49
@petervrichards The title mentions a sigterm but I can't see that in the logs (they seem to stop with `Syncing files to device Nexus 10 KitKat... 4.0s`).

Can you provide more info, including:

- Which channel of Flutter are you using?
- How are you running the program?
- What is the full output? Where is the error/sigterm shown?
- If launching from within VS Code, can you repro from a terminal with `flutter run`?

**Comment by DanTup** [comment] 2018-03-14 17:13
My guess is that this is a dupe of #631, which is something going wrong during running but we're not surfacing the error. It'll be fixed for vNext.

For now, in order to find out what your problem is, please run `flutter run` from the command line in your projects folder and the error message should be output explaining what's wrong.

If you still have issues, please shout!

**Closed by DanTup** 2018-03-14 17:13 UTC
Labels: awaiting info

**Comment by petervrichards** [comment] 2018-03-14 17:16
thanks for this. 
I am just booting the environment. Will forward the results. 
I'll try to answer the questions you pose as well as i can. 
(not a noobie to software - just to dart/flutter/visual code) 
cheers 
peter richards

**Comment by DanTup** [comment] 2018-03-14 17:25
@petervrichards Don't worry about the original questions, just run `flutter run` from your terminal in your folder and I think you will find the issue (most probably something like Android SDK issues similar to the linked case).

Let me know how you get on!

**Comment by petervrichards** [comment] 2018-03-14 18:02
Dan - this has been reported before - and I think fixed in API 24 - 




BUT I cant load API24 android because its not an option in the currently available Xamarin Android emulator. 

so it completely stops me from developing on Windows ( fortunately I have a mac ) 

So far the development environment is compelling. 

peter richarrds 













C:\Users\peter\Documents\test1>flutter doctor 

Doctor summary (to see all details, run flutter doctor -v): 

[√] Flutter (Channel beta, v0.1.5, on Microsoft Windows [Version 10.0.16299.309], locale en-CA) 


[√] Android toolchain - develop for Android devices (Android SDK 27.0.3) 

[√] Android Studio (version 3.0) 

[√] VS Code (version 1.21.0) 

[√] Connected devices (1 available) 


    * No issues found! 



C:\Users\peter\Documents\test1>flutter run 

Launching lib/main.dart on Nexus 4 KitKat in debug mode... 

Initializing gradle... 1.0s 

Resolving dependencies... 1.9s 

Running 'gradlew assembleDebug'... 2.5s 

Built build\app\outputs\apk\debug\app-debug.apk (24.6MB). 

I/FlutterActivityDelegate( 1341): onResume setting current activity to this 

E/flutter ( 1341): [ERROR:flutter/shell/gpu/gpu_surface_gl.cc(39)] Failed to setup Skia Gr context. 

D/skia ( 1341): [SkFontMgr Android Parser] '/system/etc/fonts.xml' could not be opened 

D/skia ( 1341): [SkFontMgr Android Parser] '/vendor/etc/fallback_fonts.xml' could not be opened 

Syncing files to device Nexus 4 KitKat... 1.9s 


🔥 To hot reload your app on the fly, press "r". To restart the app entirely, press "R". 

An Observatory debugger and profiler on Nexus 4 KitKat is available at: http://127.0.0.1:8101/ 

For a more detailed help message, press "h". To quit, press "q".

**Comment by DanTup** [comment] 2018-03-14 18:17
Ah, I see. I'm not sure there's much we can do then if it's already fixed. Can't you use the Google emulator?

**Comment by petervrichards** [comment] 2018-03-14 19:28
I will have to wait until Android updates its emulator. 
Game emulator? 
I dont see a google emulator when I do a google search. 
Is that the Game emulator? 
peter richards

**Comment by DanTup** [comment] 2018-03-14 20:49
The android SDK has emulators:

https://developer.android.com/studio/run/emulator.html

**Comment by petervrichards** [comment] 2018-03-15 01:07
yes bbbbbut none of them have the current fixed API 24. 
my point 
all the newer ones I tried give the same error. 
peter richards

**Comment by DanTup** [comment] 2018-03-15 07:37
If you've have issues on the newest versions (26/27) I think you should raise an issue at https://github.com/flutter/flutter for investigation. Include the full output from `flutter run` when using a newer (eg. 26/27) API emulator.
