### ISSUE TITLE
Request textDocument/codeAction failed

### ISSUE THREAD

**Issue by nbros** [Dart-Code/Dart-Code#3205] opened 2021-03-14 08:35 UTC
Hello, I got the following errors while editing Dart code:

```
[Error - 09:30:29] Request textDocument/codeAction failed.
  Message: An error occurred while handling textDocument/codeAction request
  Code: -32001 
[Error - 09:30:29] An error occurred while handling textDocument/codeAction request: NoSuchMethodError: The getter 'firstTokenAfterCommentAndMetadata' was called on null.
Receiver: null
Tried calling: firstTokenAfterCommentAndMetadata
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:54:5)
#1      AddStatic.compute.<anonymous closure> (package:analysis_server/src/services/correction/dart/add_static.dart:19:32)
#2      ChangeBuilderImpl.addDartFileEdit (package:analyzer_plugin/src/utilities/change_builder/change_builder_core.dart:101:20)
<asynchronous suspension>
#3      AddStatic.compute (package:analysis_server/src/services/correction/dart/add_static.dart:18:5)
<asynchronous suspension>
#4      FixProcessor._addFromProducers.compute (package:analysis_server/src/services/correction/fix_internal.dart:1187:9)
<asynchronous suspension>
#5      FixProcessor._addFromProducers (package:analysis_server/src/services/correction/fix_internal.dart:1209:11)
<asynchronous suspension>
#6      FixProcessor.compute (package:analysis_server/src/services/correction/fix_internal.dart:1144:5)
<asynchronous suspension>
#7      DartFixContributor.computeFixes (package:analysis_server/src/services/correction/fix_internal.dart:181:19)
<asynchronous suspension>
#8      CodeActionHandler._getFixActions (package:analysis_server/src/lsp/handlers/handler_code_actions.dart:333:23)
<asynchronous suspension>
#9      Future.wait.<anonymous closure> (dart:async/future.dart)
<asynchronous suspension>
#10     CodeActionHandler._getCodeActions (package:analysis_server/src/lsp/handlers/handler_code_actions.dart:271:21)
<asynchronous suspension>
#11     ServerStateMessageHandler.handleMessage (package:analysis_server/src/lsp/handlers/handlers.dart:183:22)
<asynchronous suspension>
#12     LspAnalysisServer.handleMessage.<anonymous closure> (package:analysis_server/src/lsp/lsp_analysis_server.dart:301:26)
<asynchronous suspension>

[Error - 09:30:29] Request textDocument/codeAction failed.
  Message: An error occurred while handling textDocument/codeAction request
  Code: -32001 
[Error - 09:30:29] An error occurred while handling textDocument/codeAction request: NoSuchMethodError: The getter 'firstTokenAfterCommentAndMetadata' was called on null.
Receiver: null
Tried calling: firstTokenAfterCommentAndMetadata
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:54:5)
#1      AddStatic.compute.<anonymous closure> (package:analysis_server/src/services/correction/dart/add_static.dart:19:32)
#2      ChangeBuilderImpl.addDartFileEdit (package:analyzer_plugin/src/utilities/change_builder/change_builder_core.dart:101:20)
<asynchronous suspension>
#3      AddStatic.compute (package:analysis_server/src/services/correction/dart/add_static.dart:18:5)
<asynchronous suspension>
#4      FixProcessor._addFromProducers.compute (package:analysis_server/src/services/correction/fix_internal.dart:1187:9)
<asynchronous suspension>
#5      FixProcessor._addFromProducers (package:analysis_server/src/services/correction/fix_internal.dart:1209:11)
<asynchronous suspension>
#6      FixProcessor.compute (package:analysis_server/src/services/correction/fix_internal.dart:1144:5)
<asynchronous suspension>
#7      DartFixContributor.computeFixes (package:analysis_server/src/services/correction/fix_internal.dart:181:19)
<asynchronous suspension>
#8      CodeActionHandler._getFixActions (package:analysis_server/src/lsp/handlers/handler_code_actions.dart:333:23)
<asynchronous suspension>
#9      Future.wait.<anonymous closure> (dart:async/future.dart)
<asynchronous suspension>
#10     CodeActionHandler._getCodeActions (package:analysis_server/src/lsp/handlers/handler_code_actions.dart:271:21)
<asynchronous suspension>
#11     ServerStateMessageHandler.handleMessage (package:analysis_server/src/lsp/handlers/handlers.dart:183:22)
<asynchronous suspension>
#12     LspAnalysisServer.handleMessage.<anonymous closure> (package:analysis_server/src/lsp/lsp_analysis_server.dart:301:26)
<asynchronous suspension>

[Error - 09:30:30] Request textDocument/codeAction failed.
  Message: An error occurred while handling textDocument/codeAction request
  Code: -32001 
[Error - 09:30:30] An error occurred while handling textDocument/codeAction request: NoSuchMethodError: The getter 'firstTokenAfterCommentAndMetadata' was called on null.
Receiver: null
Tried calling: firstTokenAfterCommentAndMetadata
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:54:5)
#1      AddStatic.compute.<anonymous closure> (package:analysis_server/src/services/correction/dart/add_static.dart:19:32)
#2      ChangeBuilderImpl.addDartFileEdit (package:analyzer_plugin/src/utilities/change_builder/change_builder_core.dart:101:20)
<asynchronous suspension>
#3      AddStatic.compute (package:analysis_server/src/services/correction/dart/add_static.dart:18:5)
<asynchronous suspension>
#4      FixProcessor._addFromProducers.compute (package:analysis_server/src/services/correction/fix_internal.dart:1187:9)
<asynchronous suspension>
#5      FixProcessor._addFromProducers (package:analysis_server/src/services/correction/fix_internal.dart:1209:11)
<asynchronous suspension>
#6      FixProcessor.compute (package:analysis_server/src/services/correction/fix_internal.dart:1144:5)
<asynchronous suspension>
#7      DartFixContributor.computeFixes (package:analysis_server/src/services/correction/fix_internal.dart:181:19)
<asynchronous suspension>
#8      CodeActionHandler._getFixActions (package:analysis_server/src/lsp/handlers/handler_code_actions.dart:333:23)
<asynchronous suspension>
#9      Future.wait.<anonymous closure> (dart:async/future.dart)
<asynchronous suspension>
#10     CodeActionHandler._getCodeActions (package:analysis_server/src/lsp/handlers/handler_code_actions.dart:271:21)
<asynchronous suspension>
#11     ServerStateMessageHandler.handleMessage (package:analysis_server/src/lsp/handlers/handlers.dart:183:22)
<asynchronous suspension>
#12     LspAnalysisServer.handleMessage.<anonymous closure> (package:analysis_server/src/lsp/lsp_analysis_server.dart:301:26)
<asynchronous suspension>

[Error - 09:30:31] Request textDocument/codeAction failed.
  Message: An error occurred while handling textDocument/codeAction request
  Code: -32001 
[Error - 09:30:31] An error occurred while handling textDocument/codeAction request: NoSuchMethodError: The getter 'firstTokenAfterCommentAndMetadata' was called on null.
Receiver: null
Tried calling: firstTokenAfterCommentAndMetadata
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:54:5)
#1      AddStatic.compute.<anonymous closure> (package:analysis_server/src/services/correction/dart/add_static.dart:19:32)
#2      ChangeBuilderImpl.addDartFileEdit (package:analyzer_plugin/src/utilities/change_builder/change_builder_core.dart:101:20)
<asynchronous suspension>
#3      AddStatic.compute (package:analysis_server/src/services/correction/dart/add_static.dart:18:5)
<asynchronous suspension>
#4      FixProcessor._addFromProducers.compute (package:analysis_server/src/services/correction/fix_internal.dart:1187:9)
<asynchronous suspension>
#5      FixProcessor._addFromProducers (package:analysis_server/src/services/correction/fix_internal.dart:1209:11)
<asynchronous suspension>
#6      FixProcessor.compute (package:analysis_server/src/services/correction/fix_internal.dart:1144:5)
<asynchronous suspension>
#7      DartFixContributor.computeFixes (package:analysis_server/src/services/correction/fix_internal.dart:181:19)
<asynchronous suspension>
#8      CodeActionHandler._getFixActions (package:analysis_server/src/lsp/handlers/handler_code_actions.dart:333:23)
<asynchronous suspension>
#9      Future.wait.<anonymous closure> (dart:async/future.dart)
<asynchronous suspension>
#10     CodeActionHandler._getCodeActions (package:analysis_server/src/lsp/handlers/handler_code_actions.dart:271:21)
<asynchronous suspension>
#11     ServerStateMessageHandler.handleMessage (package:analysis_server/src/lsp/handlers/handlers.dart:183:22)
<asynchronous suspension>
#12     LspAnalysisServer.handleMessage.<anonymous closure> (package:analysis_server/src/lsp/lsp_analysis_server.dart:301:26)
<asynchronous suspension>
```

**Versions**
 - VS Code version: 1.54.2
 - Dart extension version: 3.20.1
 - Dart/Flutter SDK version: 2.0.2

**Comment by DanTup** [comment] 2021-03-15 10:09
@nbros do you know what code you had that triggered this? The fix it was trying to produce was to add `static` to a `const` instance field, although I've not been able to reproduce it.

@bwilkerson not sure if you have any ideas? It looks like `node.thisOrAncestorOfType<FieldDeclaration>();` [here](https://github.com/dart-lang/sdk/blob/d63d5d93a59b370bf5f5c277109110cb67a96b75/pkg/analysis_server/lib/src/services/correction/dart/add_static.dart#L17) returns null, though I wasn't able to trigger it (I presume it requires some specific invalid code).

**Comment by bwilkerson** [comment] 2021-03-15 15:22
No, I don't see how this could occur. The diagnostic is only reported when we have a `FieldDeclaration` that is not static but that has a `const` keyword, and the highlight range is the `const` token. In order for this to happen the `NodeLocator` would have to return a node that isn't the same as or a child of the `FieldDeclaration` when locating the node at the location of the token, and I don't know how that would happen.

**Comment by nbros** [comment] 2021-03-20 10:14
Hello,

I could reproduce the error by typing `const late`, which of course is wrong but maybe it shouldn't crash this way even when typing something stupid :-)

![image](https://user-images.githubusercontent.com/141089/111866346-1ca5ca80-896d-11eb-9b92-37acaf8e1782.png)

**Comment by bwilkerson** [comment] 2021-03-20 15:46
I still don't know how to reproduce the bug, but the fix seems fairly obvious, so I've sent https://dart-review.googlesource.com/c/sdk/+/192281 out for review.

**Comment by DanTup** [comment] 2021-03-20 16:12
@bwilkerson I can repro in a test in `test/lsp/code_actions_fixes_test.dart` like this:

```dart
  @soloTest
  Future<void> test_danny() async {
    const content = '''
class Foo {
  const lat[[]]e String strings;
}
    ''';

    newFile(mainFilePath, content: withoutMarkers(content));
    await initialize(
      textDocumentCapabilities: withCodeActionKinds(
          emptyTextDocumentClientCapabilities, [CodeActionKind.QuickFix]),
    );

    // This throws
    await getCodeActions(mainFileUri.toString(),
        range: rangeFromMarkers(content));
  }
```

When it occurs, the `node` in `AddStatic` is the `ClassDecleration`. With the same code in `add_static_test.dart` I couldn't reproduce it, which makes me wonder if LSP is doing something differently (although I can't see anything obvious).

**Comment by bwilkerson** [comment] 2021-03-20 16:21
I used a very similar test case in `add_static_test.dart`.

I haven't tested this, but my current hypothesis is that it has to do with the offset being used. LSP is passing in the offset of the cursor, whereas the tests of `AddStatic` are passing in the offset of the diagnostic. My guess is that the parser is producing as AST that makes one offset work and the other crash.

I think the change I uploaded is still valid, but we should fix the parser to produce the same AST whether the modifiers are correct or out of order.

**Comment by scheglov** [comment] 2021-03-20 19:50
Hm... I was not able to reproduce with https://github.com/Dart-Code/Dart-Code/issues/3205#issuecomment-803396689 :-(

**Comment by DanTup** [comment] 2021-03-20 20:15
@scheglov hmm - did you have Brian's fix already? I synced to master and commented out the null check added in https://github.com/dart-lang/sdk/commit/d56098f1d4774aac346c5c96596301b371dfebfa and see the failure with the code above:

<img width="896" alt="Screenshot 2021-03-20 at 20 11 18" src="https://user-images.githubusercontent.com/1078012/111884276-78e20c00-89b8-11eb-8b3a-1eece5b81fff.png">

I pushed the exact changeset to https://dart-review.googlesource.com/c/sdk/+/192301/

**Comment by scheglov** [comment] 2021-03-21 22:08
I must have been doing something wrong yesterday.
With your CL (and doing things more carefully) I can reproduce the issue.

**Comment by DanTup** [comment] 2021-03-23 11:39
Closing this as fixed by the original change, but lmk if you want me to file an issue in sdk for improving the parsing as [mentioned above](https://github.com/Dart-Code/Dart-Code/issues/3205#issuecomment-803398010). Thanks!

**Closed by DanTup** 2021-03-23 11:39 UTC
Labels: fixed in dart / flutter, is bug

**Comment by scheglov** [comment] 2021-03-23 21:59
I think I found the reason.
https://dart-review.googlesource.com/c/sdk/+/192840

**Comment by DanTup** [comment] 2021-03-24 10:30
Great, thanks!
